### ISSUE TITLE
Restart after Network Update or Lost Connection

### ISSUE THREAD

**Issue by ifunlisted** [homebridge/homebridge#1948]
Is it possible to have HomeBridge restart automatically after a network connection is lost and then restored? I'm running on a Mac Mini and if it ever loses it's connection to the network (router reset, network update, etc), I get "No Response" on everything in my HomeKit. Once the network connection is restored, I would expect everything to be back online but it doesn't happen. The homebridge process never stops running, but it seems like the change in network status is not detected or something. Once I restart the Mini, everything is back to normal.

**Comment by SebDominguez** [comment]
Same here

**Comment by McOrLi1** [comment]
Same behavior for me. Running on a rpi B+.

**Comment by Tommrodrigues** [comment]
I have homebridge running on a Raspberry Pi B+ Wirelessly (due to a very strange problem with ethernet connection). I was quite often experiencing this problem so decided to write a small script which would simply restart the Pi after 5 consecutive instances of no connection. I saved the script as /home/pi/wificheck.sh:

```
#! /bin/bash

file="/home/pi/Desktop/count.txt"

ping -c4 192.168.1.1 > /dev/null #Change 192.168.1.1 to the IP of your router
if [ $? != 0 ]
then
  count="$( head $file )"

  if [ "$count" == "5" ]; then
    echo "NO CONNECTION (FINAL ATTEMPT)"
    echo 0 > $file
    echo "Restarting"
    sleep 1
    sudo reboot #Change this to your reboot command
  elif [ "$count" -lt "5" ]; then
    echo "NO CONNECTION, waiting..."
    newnumber=$(($count + 1))
    echo "$newnumber" > $file
  else
    echo "ERROR, NUMBER NOT EXPECTED"
  fi

else
echo 0 > $file
fi
```
Then I got a cron task to run `bash /home/pi/wificheck.sh` every minute so that after 5 minutes of constantly no Wi-Fi, it would restart. (You can change `file` to any location you want, just as long as it can be used to store a number 0-5 to count failed connection attempts).

In my rc.local, I have the following before `exit 0`:

```
rm -r /home/pi/.homebridge/accessories/cachedAccessories && sleep 0.5
su -c "/home/pi/homebridge.sh" -s /bin/sh pi &
```

This means that after a restart (either due to a power cut or as a result of the wificheck.sh script), it will remove homebridge's cachedAccessories which can often be helpful in helping homebridge to start correctly.
Finally, it then calls a script called `/home/pi/homebridge.sh ` which contains the following:

```
#! /bin/bash

until "homebridge" -s /bin/sh pi; do
    echo "Server homebridge crashed with exit code $?.  Respawning.." >&2
    echo "Looks like Homebridge just crashed, restarting it now..." | mail -s "Homebridge Crash" pi
    rm -r /home/pi/.homebridge/accessories/cachedAccessories
    sleep 1
done
```

This will start up homebridge when it is called and **will not** let it die permanently. If it crashes for whatever reason, it will send the user a mail with the time etc. and then restart homebridge after deleting cachedAccessories.

Above is what I use to give homebridge the best chance of staying connected and alive. It works well for me and means that homebridge is never without wifi for more than about 5 mins and that it is always running.

Hope that helps!

**Comment by SebDominguez** [comment]
@Tommrodrigues my Pi is still reachable on the network when Homebridge is down after a router restart.
It can also ping my router, so sadly your script can’t help me.
Thanks you anyway for sharing this workaround.

**Comment by mrquatsch** [comment]
I haven't had this problem, but I have had to solve for mine crashing before. I wrote something that checks the port the app is running on. If the URL doesn't resolve, the script restarts homebridge.

`import requests
import logging
import logging.handlers
import os
import sys
import subprocess

def main():
        initLogging()

        if not checkIfRunning():
                startHomebridge()

def checkIfRunning():
        homebridgeURL = 'http://localhost:51826'
        try:
                r = requests.get(homebridgeURL)
                logger.info("Homebridge is currently running.")
                return 1
        except:
                logger.error("Homebridge is not running. Starting now...")
                return 0

def startHomebridge():
        cmd = '/opt/node/bin/homebridge > /home/pi/.homebridge/log/homebridge.log 2>&1'
        proc = subprocess.Popen([cmd], shell=True, stdin=None, stdout=None, stderr=None, close_fds=True)
        logger.info("Homebridge started with PID: " + str(proc.pid))

def initLogging():
        global logger
        try:
                logger = logging.getLogger('server_logger')
                logger.setLevel(logging.DEBUG)
                log_filename = '/home/pi/.homebridge/log/homebridgeProcCheck.log'
                fh = logging.handlers.RotatingFileHandler(log_filename, maxBytes=10*1024, backupCount=5)
                ch = logging.StreamHandler()
                ch.setLevel(logging.ERROR)
                formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
                fh.setFormatter(formatter)
                ch.setFormatter(formatter)
                logger.addHandler(fh)
                logger.addHandler(ch)
        except:
                print ("FATAL: Unable to set logger... Exiting.\n\n")
                sys.exit(99)

if __name__ == '__main__':
        main()`

I run this on a cron that kicks off every 10 minutes.

**Comment by drewcovi** [comment]
@nfarina this would be a huge asset, ideally some sort of preliminary check and elegant fallback. Would help ensure homebridge functions more like a home utility.

I’ll take a look if I can find some time. But clearly this can be written in node rather than an external cronjob.

**Comment by SebDominguez** [comment]
Maybe some router doesn’t broadcast mDNS stuff after an internet outage?
I’ve read somewhere that someone with Google WiFi also have this issue.
@nfarina what kind of router do you have? I’m using my ISP router and I’m considering replacing it to see if this can solve this problem.

**Comment by nfarina** [comment]
I use the Ubiquity Unifi setup - the "USG" (router) and UAP (access point). It's a bit overkill for most, but @KhaosT sold me on it ;)

**Comment by SebDominguez** [comment]
Alright I was considering trying an UAP-AC (they are not that expensive) Any special setup? Like enabling igmp snooping or spooky things like that?

**Comment by nfarina** [comment]
Nope I keep mine pretty stock. One annoyance to consider is that you'll have to run a "controller" somewhere to configure it. I installed mine on the same Pi that runs homebridge of course. But you can also run it as-needed on your laptop.

The whole setup is extremely powerful and configurable but you definitely feel the "enterprise" nature of it.

**Comment by ifunlisted** [comment]
I'm using an Airport Extreme (2013). Any time I make changes that require restarting/resetting the router, I also have to restart my Homebridge computer (Mac Mini).

**Comment by drewcovi** [comment]
So I’m rolling ubnt as well. Cloudkey, and four in wall AP’s. Normally all is well. We did lose power last night and homebridge didn’t recover elegantly, so perhaps my circumstance is more nuanced. I’d work on refactoring my homebridge-vera plug-in, but all devices (regardless of plugin) were offline until I restarted.

**Comment by SebDominguez** [comment]
I was trying Hassio last week to test they native support of Homekit, but the result is exactly the same.
So it could be a local network problem (my Ubiquiti gears are coming soon).
It could be a bug introduced with iOS11.4 since before that when I was playing with Homebridge I didn't have any problems at all, I believe that I was using iOS 11.2 before Apple fix the Homekit vulnerability.
Some people reported that this could be due to the Wifi power save mode on the pi. (my pi is wired so that didn't helped)
And finally in some threads I'm reading that Avahi that is totally broken.

**Comment by ifeign** [comment]
I also have this problem when my internet drops. I have an Asus RT-AC1900, and I'm running Homebridge in a docker container on an Raspberry Pi 3. Restarting the container or the Pi itself is the only way to get things up and running again.

**Comment by ebaauw** [comment]
Hm, did some more testing.  I haven't been able to reproduce the issue - the advertisement is restored after the network connection is restored.  Avahi seems to work correctly, but `mdns` could do better: it seems to stick to one interface and only uses IPv4.

Normally my test Raspberry `pi1` is connected by Ethernet and the Wifi is disabled.  Using `avahi-browse` on `pi1`, you see the homebridge advertisements (`pi2` is my production Raspberry, with two homebridge instances):
```
$ avahi-browse _hap._tcp.
+   eth0 IPv4 pi1                                           _hap._tcp            local
+   eth0 IPv4 pi2                                           _hap._tcp            local
+   eth0 IPv4 pi2 hue                                       _hap._tcp            local
```
After enabling WiFi and pulling the network cable, the advertisement of the local homebridge instance is lost:
```
$ avahi-browse _hap._tcp.
+  wlan0 IPv4 pi2 hue                                       _hap._tcp            local
+  wlan0 IPv4 pi2                                           _hap._tcp            local
```
I would have hoped, that homebridge would be advertised on wlan0.  I use the same IPv4 address for both network interfaces (assigned by my DHCP server, based on the MAC address), so `ssh` and screen sharing session survive switching interfaces. Raspbian only assigns the IPv4 address to the newly active interface, when the other interface is down.

After re-attaching the network cable and disabling WiFi, the advertisement seems to be restored, and the accessories are reachable again:
```
$ avahi-browse _hap._tcp.
+   eth0 IPv4 pi2                                           _hap._tcp            local
+   eth0 IPv4 pi1                                           _hap._tcp            local
+   eth0 IPv4 pi2 hue                                       _hap._tcp            local
```
Apparently there's something more going on in my network that caused the advertisement to disappear permanently.

Avahi seems to work correctly.  I configured an advertisement for the VNC server in the avahi settings, so I can access it more easily from macOS screen sharing.  While homebridge is advertised over IPv4 only, the static config uses both IPv4 and IPv6:
```
$ avahi-browse _rfb._tcp.
+   eth0 IPv6 pi2                                           VNC Remote Access    local
+   eth0 IPv6 pi1                                           VNC Remote Access    local
+   eth0 IPv4 pi1                                           VNC Remote Access    local
+   eth0 IPv4 pi2                                           VNC Remote Access    local
```
When enabling WiFi, IPv6 advertisements for the newly available interface are added (note that `wlan0` doesn't yet have an IPv4 address):
```
$ avahi-browse _rfb._tcp.
+  wlan0 IPv6 pi2                                           VNC Remote Access    local
+  wlan0 IPv6 pi1                                           VNC Remote Access    local
+   eth0 IPv6 pi2                                           VNC Remote Access    local
+   eth0 IPv6 pi1                                           VNC Remote Access    local
+   eth0 IPv4 pi2                                           VNC Remote Access    local
+   eth0 IPv4 pi1                                           VNC Remote Access    local
```
When pulling the cable, `wlan0` gets the IPv4 address and takes over the IPv4 advertisement:
```
$ avahi-browse _rfb._tcp.
+  wlan0 IPv6 pi2                                           VNC Remote Access    local
+  wlan0 IPv6 pi1                                           VNC Remote Access    local
+  wlan0 IPv4 pi2                                           VNC Remote Access    local
+  wlan0 IPv4 pi1                                           VNC Remote Access    local
```
When re-inserting the cable, the IPv6 advertisements on `eth0` are restored (note that `eth0` now doesn't have an IPv4 address):
```
$ avahi-browse _rfb._tcp.
+  wlan0 IPv6 pi2                                           VNC Remote Access    local
+  wlan0 IPv6 pi1                                           VNC Remote Access    local
+  wlan0 IPv4 pi2                                           VNC Remote Access    local
+  wlan0 IPv4 pi1                                           VNC Remote Access    local
+   eth0 IPv6 pi1                                           VNC Remote Access    local
+   eth0 IPv6 pi2                                           VNC Remote Access    local
```
After disabling WiFi, everything is back to normal:
```
$ avahi-browse _rfb._tcp.
+   eth0 IPv6 pi2                                           VNC Remote Access    local
+   eth0 IPv6 pi1                                           VNC Remote Access    local
+   eth0 IPv4 pi1                                           VNC Remote Access    local
+   eth0 IPv4 pi2                                           VNC Remote Access    local
```

**Comment by dudusandi** [comment]
Same Here

**Comment by daveramirez5** [comment]
Same here. I managed to solve the power cuts using pm2. But still have issue of devices becoming unavailable after a router restart

**Comment by Ant1q** [comment]
Same here. Any updates?

**Comment by william57m** [comment]
Same issue, after a router restart I have to restart homebridge.

**Comment by slef** [comment]
Same problem.

**Comment by jeyremy** [comment]
Yep, Same here, i have a router that randomly reboot, (twice a day) and all hombridge accessories is "not responding" 
i have to manualy restart Homebrige each time..

**Comment by ifeign** [comment]
While your issue is valid.. I'd start with looking into your router. Check
the firmware version, factory reset it and failing that, replace it. If it
randomly reboots, it's likely to continue to get worse.

**Comment by anilgk** [comment]
I’m running homebridge using systemd. 
I have to restart homebridge service because it stops responding randomly even if my router is connected constantly. (My router is an Apple AirPort Extreme which is very stable)

Please help me resolve this. 

Thank you !

**Comment by daveramirez5** [comment]
I think this should not be closed. Is a requested and necessary feature.  

Enviado desde mi iPhone

**Comment by ifeign** [comment]
Agreed. This needs to be resolved. It’s a nightmare of the internet goes down while away from home.

**Comment by NorthernMan54** [comment]
Everyone

There are a lot of different reasons why this could occur, and majority are local setup issues or issues with a particular plugin.  In my setup I went a few days without internet access and everything was fine except for the plugins that scrapped cloud based API's to work.  And when the internet came back, everything just just resumed without any restarts.

So am not sure what the ask is of the developers here. So am closing this

**Comment by Ant1q** [comment]
LOL, after closing this issue my problem is gone.
In fact, i did two things: change firmware on my router(Xiaomi R3G) from stock to padavan and change connection method my Apple TV 4 from ethernet to wifi.
And now i have any problem with "no response" after rebooting router of connection lost. I try to disconnect internet cable, restart and switch off router, but all works fine after restore internet connection.
I dont know how these affect each other, but my problem is solved.

**Comment by dmndrz** [comment]
I have the same issue and looked for a solution but didn't find one.
Too bad it's been closed...

**Comment by ifeign** [comment]
This doesn’t appear to be a problem anymore, at least for the way I run
Homebridge in a Docker container.

**Comment by dudusandi** [comment]
> This doesn’t appear to be a problem anymore, at least for the way I run Homebridge in a Docker container.
> […](#)


> I have the same issue and looked for a solution but didn't find one.
> Too bad it's been closed...

Use home assistant hassio with homekit plugin is too better and stable.
