### ISSUE TITLE
Possibility to clean/flush/rebuild cachedAccessories to remove old entries after plugin deletion

### ISSUE THREAD

**Issue by phenomeus** [homebridge/homebridge#2120]
@nfarina is there a clean way to get old entires from HomeKit removed after a plugin is uninstalled? (i.e.: switches from uninstalled homebridge-harmonyhub are still visible in homekit)

afaik I understood it, the cachedAccessories file keeps the entries there, but the modification by hand using nano is pain in the a and also there is a good chance that after saving the HomeKit service is not starting anymore. so the only solution I had, is to kill the file cachedAccessories but than I lose all my room organisation and naming and I have to start over with all the lights, sensors and switches. 

what I would like to use is maybe a possibility to --rebuild or --rescan command after a plugin uninstall. so that all unused and old entries are getting cleaned or flushed. 

what do you think?

**Comment by ebaauw** [comment]
While refactoring my (platform) plugins to use the dynamic accessory model, I found that if you (your plugin) removes the accessory, it gets deleted from cachedAccessories as well.  I'm doing so when the plugin is loaded, but not specified in config.json.  This does require special user attention when uninstalling a plugin:
- Remove the entry from config.json;
- Restart homebridge with the plugin still installed to clean cachedAccessories;
- Uninstall the plugin;
- Restart homebridge again.

I think a better way could be not to restore the accessory in
https://github.com/nfarina/homebridge/blob/422582ad34a05f7d4510fbea7549a0461b65f063/lib/server.js#L357
when no `platformInstance` is found (i.e. when the plugin has been uninstalled).  If I understand correctly, this should remove the stale accessories, next time `cachedAccessories` is written.

**Comment by phenomeus** [comment]
:/ right now that's not the case with all plugins right? so every dev has to implement the clean way. I can't do anything right now, correct?

**Comment by liambolling** [comment]
Yeah this leaves it up to the dev. There should be a global way to flush the cache.

**Comment by phenomeus** [comment]
can we bump this? a flush command or rebuild caches command with only the installed plugins + right config would be very helpful

**Comment by ebaauw** [comment]
Happy to prepare a PR for this if we can agree on the specs: a command line option to delete cached accessories for which no plugin was loaded.  I.e. plugins that are no longer installed or, when `plugins` is specified in config.json, plugins that are no longer whitelisted.

**Comment by phenomeus** [comment]
@ebaauw that would be awesome, exactly how you proposed

**Comment by lboue** [comment]
Starting homebridge with -R option was fine for me 👍 
Thanks @ebaauw

**Comment by roysbike** [comment]
+1

**Comment by deboiph** [comment]
I have the same problem after uninstalling a plugin (installed with some errors):

[1/29/2020, 21:18:05] [Config] Failed to parse plugin "homebridge-automation-bluetooth-presence": ENOENT: no such file or directory, open '/usr/lib/node_modules/homebridge-automation-bluetooth-presence/package.json'

Starting homebridge with -R option has not solved the problem.
This plugin is not referenced in the configuration.

**Comment by donavanbecker** [comment]
Would recommend using [config ui x](https://github.com/oznu/homebridge-config-ui-x) and clearing accessories through the homebridge settings in the ui.
