### ISSUE TITLE
Plugin Request: Melnor RainCloud\Wifi Aqua Timer

### ISSUE THREAD

**Issue by JangoBritt** [homebridge/homebridge#2214]
Looking for somebody who might be interested in developing a Sprinkler plugin for Melnor's RainCloud/Wifi Aqua Timer. https://www.amazon.com/Melnor-Controlled-Irrigation-Controller-Compatible/dp/B01MZE8J1R

I've found a python library for it, https://github.com/tchellomello/raincloudy but nothing yet for homebridge

**Comment by navidfathi** [comment]
Yeah would be great if a smart developer can make this plugin for Homebridge. Will solve a lot of problems!
