### ISSUE TITLE
how do I stop logging entirely?

### ISSUE THREAD

**Issue by mentaluproar** [homebridge/homebridge#2253]
I've tried posting in the plugin repo but haven't received a response so I'm posting here.  I'm using the homebridge-frigidare plugin.  It spams my daemon.log and syslog to the point that they fill their entire partitions.  It's even useful information.  It's just describing everything it does.  It's like its stuck in debug or something.

Set homebridge up to start from systemd.  Everything will work fine.  Wait 24 hours.  Your server will start to complain and various things will stop working.
homebridge v0.4.50
node v10.15.2
OS openmediavault running the 4.4.167-1213-rockchip-ayufan-g34ae07687fce kernel on the rockpro64
I just need to know how to tell homebridge to stop logging things.  Its better if I can tell it to just ignore everything the frigidare plugin says, but I'm not picky.

**Comment by dev01d** [comment]
I'm curious about this too. Logging is way too verbose when not in debug mode.

**Comment by mshulman** [comment]
+1. I'm using the docker container by @oznu . I don't see where the debug mode is set. I wonder if either the debug flag is set in the docker compose, or if somehow the debug flag is flipped?
