### ISSUE TITLE
Ducted multi zoned AC and homekit

### ISSUE THREAD

**Issue by JaseSmith78** [homebridge/homebridge#2255]
I'm new and learning (sorry) 
I'm having trouble reading the specs for homekit and whether it would support multi room air conditioners as a unit or if they would need to be implemented as whole ac's in each room 

I have an older AdvancedAir AC (version 2 i think) and i have wiresharked its comms and understand how to speak to it - so is it worth learning and implementing completely or should i cheat and just use one of the simple http-ac plugins that have already been build? (i do already have a working http control interface that hides all the xml - but written in python)

**Comment by NorthernMan54** [comment]
Reusing code is what makes open source so powerful, so do use another plugin as a base and modify it for your needs.   If your going to share your effort with the wider community then creating a new GitHub repo with your work is a good idea.

**Comment by halfcherry** [comment]
I'm building a house with Daikin ducted AC and AdvancedAir MyAir controller, it'd be awesome if this can be integrated into Homebridge.

**Comment by JaseSmith78** [comment]
@halfcherry - turns out I'm really crap at node - so why reinvent the wheel - I have an api translation layer written in python (and I'm not saying I'm a great at python either...) that can be used with homebridge-http-switch (as a stateful switch and then set to a 'fan' in homekit)
and then I used  homebridge-web-thermostat to control the actual temp / mode - its all a bit of a hack, but it seems to be working (don't use homebridge-thermostat - it crashes homebridge if it gets an io error on its status updates)

**Comment by mitch7391** [comment]
@halfcherry I have mine in HomeKit now with a bit of a work around here, it is a work in progress though with the obvious limits of HomeKit with multi zone ducted ACs:

https://github.com/mitch7391/cmd4-E-Zone-MyAir

**Comment by halfcherry** [comment]
@mitch7391 Thank you, I've subbed to your work.

**Comment by mitch7391** [comment]
@halfcherry no worries, it was by chance I had an email in my junk folder saying this was closed out and saw your comment. I’m looking for people to test and suggest improvements, I’m a fair bit of a noob and am still learning but want to try and improve it :) so feel free to post issues or suggestions.
