### ISSUE TITLE
Works with Nest being discontinued

### ISSUE THREAD

**Issue by ekolow** [homebridge/homebridge#2262]
Considering setting up the Nest Plugin requires a "Works with Nest" account. How do you plan on keeping this plugin active when Google Nest terminates it

https://blog.google/products/google-nest/updates-works-with-nest/

**Comment by adriancable** [comment]
I am working on a new version of the plug-in that doesn't require WWN. Watch this space.

**Comment by simonrb2000** [comment]
Awesome

**Comment by adriancable** [comment]
homebridge-nest 3.0.0 has now been published. This new release doesn't require WWN. Enjoy!

**Comment by mrjackyliang** [comment]
@adriancable You're awesome! Thanks for contributing to the Homebridge Nest plugin! My nest is back in action!

**Comment by ekolow** [comment]
Thank you!

**Comment by cryptobrian** [comment]
@adriancable You sir, are the real MVP! Thank you so much!

**Comment by adriancable** [comment]
@cryptobrian - you are very welcome!

**Comment by jojogrosso** [comment]
@adriancable So sorry for the stupid question, but I'm just getting started with this. I have a nest thermostat, but want to use HomeKit. Is it still possible without being able to obtain the API from Nest/Google?

**Comment by InDoubt** [comment]
Hi there!
Thank you for developing this wonderful utility!
For me, it was working smoothly to control temps of my Nest via Siri, but when I decided to move Homebrige to a newer MacMini with Catalina, things went down.
In short, I installed Homebridge 4.4.4 successfully, I think. Everything looks right in http://localhost:8581....I added the new accessory with the Homekit / Camera, it shows in Hubs & Bridges tab as MyHome Homebridge 2794, but it doesn't show in the HOME tab or anywhere else....
Would you tell me please, or point to a link that explains how to link the Nest thermostat to Homebrige? or if it is still possible to do this? Google says that dropped all support, but Homebridge continues developing and updating until 4 days ago.
Thank you!

**Comment by mrjackyliang** [comment]
@InDoubt did you connect nest with google? cause you cannot do username/password for nest anymore.

**Comment by InDoubt** [comment]
Thank you, mrjackyliang.
No. I don't. I refuse to migrate my account to Google. 
I use, though, username (email) + password for Nest iOS app and for the webpage.

**Comment by mrjackyliang** [comment]
@InDoubt Yeah, it won't work with a Nest account not connected to Google anymore because Google has implemented reCAPTCHA. That prevents the plugin from accessing the Nest Web robotically which is how the plugin works.

**Comment by InDoubt** [comment]
Thank you!
