### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by tseatah** [homebridge/homebridge#2283]
My setup appears to have stopped working after a recent MacOS update. Currently on MacOS 10.14.6.

Now I'm getting an error of "TypeError: Cannot read property 'length' of null" right after the Wink Authentication succeeds. 

Current module versions are : 
├─┬ homebridge@0.4.50
├─┬ homebridge-hue@0.11.31
│ ├─┬ homebridge-lib@4.4.2
├─┬ homebridge-nest@2.1.4
├─┬ homebridge-wink@2.1.1
├─┬ homebridge-wink2@2.0.8

The output of: DEBUG=* homebridge -D 
[homebridge.log](https://github.com/nfarina/homebridge/files/3484252/homebridge.log)

My config.json:
[config.txt](https://github.com/nfarina/homebridge/files/3484254/config.txt)

**Comment by mattwillems** [comment]
Running into the same issue.
