### ISSUE TITLE
Request YardForce / Mowap (Lawn Mower) Plugin

### ISSUE THREAD

**Issue by clipse2004** [homebridge/homebridge#2288]
Hello,

I have a YardForce Lawn Mower, he works with the IOS App Mowap.
Please can you write me a Plug-in for this to integrate it in Homebridge?  

Big Thanks

**Comment by djsuszi** [comment]
> Hello,

Have you find anything ? :)
As I was tcpdumping, my X60i is connecting with 18.194.44.105 on port 33475
and android app is connecting to port 33473

**Comment by blloyd78** [comment]
I am also interested in a Yardforce mower plugin. 
Failing that, does anyone know how to pair the Yardforce with the Tuna app?
