### ISSUE TITLE
"Additional Setup Required" prompt for cameras?

### ISSUE THREAD

**Issue by adriancable** [homebridge/homebridge#2295]
Hi,
When adding any kind of camera device (using an appropriate plugin) to Homebridge, the camera never adds immediately - the user is always prompted with something like:

**Additional Setup Required**
Add related accessories with "Homebridge" in the manufacturer's app.

You then have to manually go to Add Accessory, I Don't Have A Code, Manual Code and enter the code.

Is it known why this is the case? It's definitely a UX downer.

Thanks!

-Adrian

**Comment by codyc1515** [comment]
I'm fairly sure the way around those steps when adding a camera is to go add an accessory as usual by scanning the QR code. This should add the device without typing it.
