### ISSUE TITLE
Harmony Hub as only 1 device 

### ISSUE THREAD

**Issue by macguru341** [homebridge/homebridge#2296]
Hello
I’ve installed Homebridge and the Logitech hub plugin.
I’ve added to my home app but I see on my device only one box called harmony hub and when I press it I see all the 3 activists I have.
Is there a way to make a single box for each activity?

![A34555F3-8796-45F7-B648-CB55B2CB7961](https://user-images.githubusercontent.com/22807164/64199989-3fa88080-ce94-11e9-8ae4-f4045ec20d45.png)
![443ABCE3-75CB-4B9A-92CD-D1F6DAD10D24](https://user-images.githubusercontent.com/22807164/64199992-3fa88080-ce94-11e9-8810-3d2a28344860.png)

**Comment by onefish2** [comment]
Nothing to do with Homekit or Homebridge. This is the new look for devices in the Home app in iOS 13. I do not like it either.

**Comment by CVHvisuals** [comment]
Yes you can configure for them to be separate switches in the config file. You can find the info for the config on the plugin page on github.
