### ISSUE TITLE
Help needed: Homebridge not showing up in HomeKit-App and Bonjour Browser

### ISSUE THREAD

**Issue by xBotRaid** [homebridge/homebridge#2299]
I had my Homebridge running for about 4 weeks on my Server running  Windows 10, then I had to change my motherboard so I had to reset the Network configuration. Now I cannot get Homebridge to be recognized by any of my iOS Devices, it keeps on failing to find the old accessories. Then I deleted the Homebridge config and tried to do reconnect, also cannot find anything related to my Server inside the Bonjour Browser on the iPhone or iPad on the same Network.

I tried so many suggestions written in Forums and I'll give you a quick recap with links  on what I've already done:

* Deleted persist and accessories folder and all plugins - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories)
* Changed username, pin, name and port + reinstall of Node and HomeKit  - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories)
* Reconfigured WIFI - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#home-couldnt-connect-to-this-accessory)
* Disabled IPv6 in Windows Network Adapter Settings (in forum they did it on Raspbian) - [Can't Pair GitHub Comment](https://github.com/nfarina/homebridge/issues/607#issuecomment-236471712)
* Examined logs for plugin errors - [mDNS packets GitHub Comment](https://github.com/nfarina/homebridge/issues/1957#issuecomment-497756617)
* Run Debug Mode (no errors found) - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#debug-mode)
* Changed Network interface (ethernet adapter instead of built in port - no success either) - [GitHub Comment](https://github.com/nfarina/homebridge/issues/1801#issuecomment-427690849)
* Specified mDNS local Server-IP inside config file - [mDNS packets Comment GitHub](https://github.com/nfarina/homebridge/issues/1957#issuecomment-468709606)
* Checked if port is open via command (worked) - ["Homebridge Running but..." GitHub Comment](https://github.com/nfarina/homebridge/issues/1801#issuecomment-378514491)
* Opened Homebridge Port and Bonjour Ports (UDP: 1900 , 5350, 5351, 5353) in Windows Firewall
* Reset network configuration

I tried literally anything I found online, but no success. Many things are done inside of a Linux based system, mine is on Windows so sometimes a bit difficult to research. How can I solve this... I have been searching for too long now.

Please help...

&#x200B;

Testing config if necessary:

    {
      "mdns": { "interface": "192.168.0.10" },
      "bridge": {
        "name": "MyHomebridge",
        "username": "BB:21:1B:B3:AB:BA",
        "port": 51820,
        "pin": "439-56-562"
      },
      "accessories": [
    		{
             "accessory": "StatefulDummySwitch",
             "name": "My Switch 1"
            }
      ],
    
      "platforms": [
      ]
    }

**Comment by EndorEwoksFC** [comment]
I'm having the same problem with zero luck. There's a number of open issues including #2328 regarding this recently, so I'm wondering if it's an iOS 13 issue.

**Comment by xBotRaid** [comment]
Yea, many have this problem. But it‘s not a iOS 13 Problem, since I had this problem since iOS 12.0.
