### ISSUE TITLE
How to update/upgrade Node.JS version ?

### ISSUE THREAD

**Issue by LegendaryWiz** [homebridge/homebridge#2305]
I'm having great trouble upgrading Node.JS on my RPI 3 B+. I've been on the web for a day, trying almost all solutions but I've yet to get it upgraded. 

Here's a few of what I've tried : all to no avail

$ curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
$ sudo apt-get install -y nodejs

package-lock.json
npm install
npm rebuild

npm cache clean -f
npm install -g n
n stable

After entering these commands they seem to be doing their job, however whenever I enter "node -v" it always says I'm still on 8.2.1 . Why why why ?

I'm concerned over whether my accessories / platforms will still work after NodeJS is upgraded. I'm trying to install Ring plugin but it requires version 8.3.0 , while mine is 8.2.1 . 

I'm also running MagicMirror on the same RPI . Think it uses pm2 . If I eventually successfully upgraded NodeJS , will either MagicMirror / Homebridge work as usual ?

Thank you very much for anyone that has an answer to this ... **_I just need a correct list of steps/commands to upgrade NodeJS safely ._** I'm getting variations of the method everywhere but none of which seem to work . **If Homebridge has to be reinstalled after upgrading NodeJS, what's the correct procedure to do it in this case?** 

My apologies for not being able to provide the Homebridge Log / Command Output. Through multiple tries of upgrading NodeJS a lot of plugins went wrong already , it has taken me ages to get things back to yesterday . For now Homebridge autostart on boot doesn't work anymore . I don't want to mess things up further by redoing the same steps again ...

### Versions

- **Homebridge**: `homebridge --version` : 0.4.49
- **Node**:       `node --version` : v8.2.1
- **OS**:          Windows 10

**Comment by mafyata** [comment]
I used this:
curl -sL https://deb.nodesource.com/setup_10.x | bash -

**Comment by mafyata** [comment]
May be with sudo.

**Comment by LegendaryWiz** [comment]
Thank you very much for the fast reply, unfortunately I got this :

pi@raspberrypi:~ $ sudo curl -sL https://deb.nodesource.com/setup_10.x | bash -

## Installing the NodeSource Node.js 10.x repo...


## Populating apt-get cache...

+ apt-get update
Reading package lists... Done
W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
Error executing command, exiting 

NodeJS version still 8.2.1 , this is driving me nuts ..

**Comment by mafyata** [comment]
How did you install nodejs? What command did you use?

**Comment by LegendaryWiz** [comment]
I didn't really install NodeJS , it's self-installed as part of a command . Hopefully I didn't break the whole system by taking this shortcut ..

curl -sSL goo.gl/Ksdhph | bash 

I used it to finish setting up Homebridge automatically , guess NodeJS is installed as well ?

**Comment by mafyata** [comment]
I had the same problem with this command. I tried everything , but no success. 
Fresh install of OS and then install again homebridge , nodejs...... 
I have txt file with commands for installing homebridge and all components to work normal. If you want to install all again I can send you the file.

**Comment by macjl** [comment]
In this command :
`sudo curl -sL https://deb.nodesource.com/setup_10.x | bash -

the sudo is not at the right place. You doesn't need superuser rights to download the script, but to execute it. Si try this command instead :
`curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -

**Comment by LegendaryWiz** [comment]
> In this command :
> `sudo curl -sL https://deb.nodesource.com/setup_10.x | bash -
> 
> the sudo is not at the right place. You doesn't need superuser rights to download the script, but to execute it. Si try this command instead :
> `curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -

I've tried this method 

curl -sL https://deb.nodesource.com/setup_8.x | sudo bash 
sudo apt-get install -y nodejs

Thank you very much ! It looks like everything is normal and going well during upgrade, but unfortunately :

pi@raspberrypi:~ $ sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libc-ares2 libhttp-parser2.8 libuv1 nodejs-doc
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  nodejs
1 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 14.2 MB of archives.
After this operation, 11.8 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_10.x stretch/main armhf nodejs armhf 10.16.3-1nodesource1 [14.2 MB]
Fetched 14.2 MB in 2s (5,574 kB/s)
apt-listchanges: Reading changelogs...
(Reading database ... 129879 files and directories currently installed.)
Preparing to unpack .../nodejs_10.16.3-1nodesource1_armhf.deb ...
Detected old npm client, removing...
Unpacking nodejs (10.16.3-1nodesource1) over (8.16.1-1nodesource1) ...
Setting up nodejs (10.16.3-1nodesource1) ...
Processing triggers for man-db (2.7.6.1-2) ...
pi@raspberrypi:~ $ node -v
v8.2.1

Still stuck at v8.2.1 afterwards. Closed SSH and reopened, still v8.2.1 
This is driving me nuts... 😭

**Comment by LegendaryWiz** [comment]
> I had the same problem with this command. I tried everything , but no success.
> Fresh install of OS and then install again homebridge , nodejs......
> I have txt file with commands for installing homebridge and all components to work normal. If you want to install all again I can send you the file.

I'm really unwilling to reinstall Homebridge again though, I've 40 + accessories running with it and a whole reset will be disastrous 😞 Is there a way to perform the equivalence of "resetting" without erasing everything in Homebridge? Most of my automation are done on Homekit app and repairing Homebridge again will erase all that. 

But regarding your txt file, yes please I'll like to take a look just in case I need to reset everything.  Really appreciate your help!

**Comment by mafyata** [comment]
This is my file.


[install Homebridge & Config ui x-lite.txt](https://github.com/nfarina/homebridge/files/3613486/install.Homebridge.Config.ui.x-lite.txt)

**Comment by mafyata** [comment]
This is what you installed via curl -sSL goo.gl/Ksdhph | bash

[homebridge.txt](https://github.com/nfarina/homebridge/files/3613489/homebridge.txt)

**Comment by LegendaryWiz** [comment]
Thank you very much! 

Now I see why I've 8.2.1 installed though. Is there something wrong with commands inside this "curl -sSL goo.gl/Ksdhph | bash" that's causing errors will future upgrade of Node? Seems like something is preventing me from upgrading. All my upgrade processes proceeded normal with no errors but in the end it still comes up as v8.2.1

**Comment by LegendaryWiz** [comment]
Okay so ... I've finally found a way to upgrade successfully !!

sudo npm cache clean -f
sudo npm install -g n
sudo n 8.3.0

What on earth ... Took me 2 days to do so. Now it has upgraded successfully. Everything is back to normal and every plugin in Homebridge still works as per normal. 

However with success comes disappointments, the Ring plugin works now but I can't get it to discover and add my Ring Doorbell. Wtf ... Guess it's a problem for another day 😞 

Thank you very much to all that have helped. I really appreciate the fast responses 😄😃

**Comment by oznu** [comment]
Adding a link to the relevant wiki article as this issue is one of the top results in Google.

https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js
