### ISSUE TITLE
homebridge cant start

### ISSUE THREAD

**Issue by matty0511** [homebridge/homebridge#2310]
I am running homebridge on vm in esxi on Ubuntu server 18. When i try to start the service i get the following.
 There was a problem reading your config.json file.
[9/17/2019, 9:41:45 AM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[9/17/2019, 9:41:45 AM]
/usr/local/lib/node_modules/homebridge/lib/server.js:218
    throw err;
    ^

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:212:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
root@homebridge:~#

**Comment by buenyamin-olgun** [comment]
Could you post your config.json here or did you try to use http://jsonlint.com to validate it?

**Comment by matty0511** [comment]
Yes. i kind of got it to work. Its throwing a different error but I think I know what thats caused from. However. the service seems to continually start and stop

**Comment by matty0511** [comment]
[9/17/2019, 10:24:29 AM] TypeError: Cannot read property 'devices' of null
    at new Sonoff (/usr/lib/node_modules/homebridge-sonoff/index.js:16:45)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[9/17/2019, 10:24:29 AM] Got SIGTERM, shutting down Homebridge...
[9/17/2019, 10:24:31 AM] [Config] Homebridge Config UI X v4.6.1 is listening on :: port 8080

**Comment by aswathraja** [comment]
I think you haven’t installed the module for sonoff. Please check the sample config of the eWeLink plugin that you are using. There any many plugins available for eWeLink.

**Comment by matty0511** [comment]
Okay. I think I have everything fixed. I am not familiar with json... do you know of a good article that explains the formatting>

**Comment by matty0511** [comment]
{
    "accessories": [],
    "bridge": {
        "username": "xx:xx:xx:xx:xx",
        "name": "Homebridge",
        "pin": "123-45-678",
        "port": 51826
    },
    "platforms": [
        {
            "port": 8080,
            "sudo": true,
            "tempUnits": "c",
            "platform": "config",
            "restart": "sudo -n systemctl restart homebridge",
            "theme": "teal",
            "auth": "form",
            "log": {
                "method": "systemd"
            },
            "name": "Config"
        }
    ]
}

So where would I addd the config for my sonoffs?

**Comment by buenyamin-olgun** [comment]
Every platform has its own set of json parameters.
Please look at https://github.com/AlexanderBabel/homebridge-sonoff#readme for an example with homebridge-sonoff.

And JSON itself is rather self explaining with correct line formatting.
`{
   "accessories":[

   ],
   "bridge":{
      "username":"xx:xx:xx:xx:xx",
      "name":"Homebridge",
      "pin":"123-45-678",
      "port":51826
   },
   "platforms":[
      {
         "port":8080,
         "sudo":true,
         "tempUnits":"c",
         "platform":"config",
         "name":"Config",
         "restart":"sudo -n systemctl restart homebridge",
         "theme":"teal",
         "auth":"form",
         "log":{
            "method":"systemd"
         }
      }
   ]
}`

So if you want to add one more platform you have to do this:
`{
   "accessories":[

   ],
   "bridge":{
      "username":"xx:xx:xx:xx:xx",
      "name":"Homebridge",
      "pin":"123-45-678",
      "port":51826
   },
   "platforms":[
      {
         "port":8080,
         "sudo":true,
         "tempUnits":"c",
         "platform":"config",
         "name":"Config",
         "restart":"sudo -n systemctl restart homebridge",
         "theme":"teal",
         "auth":"form",
         "log":{
            "method":"systemd"
         }
      },
      {
         "platform":"Sonoff",
		 "name":"Sonoff"
      }
   ]
}`

**Comment by buenyamin-olgun** [comment]
Every platform has its own set of json parameters.
Please look at https://github.com/AlexanderBabel/homebridge-sonoff#readme for an example with homebridge-sonoff.

And JSON itself is rather self explaining with correct line formatting.
```
{
   "accessories":[],
   "bridge":{
      "username":"xx:xx:xx:xx:xx",
      "name":"Homebridge",
      "pin":"123-45-678",
      "port":51826
   },
   "platforms":[
      {
         "platform":"config",
         "name":"Config",
         "port":8080,
         "sudo":true,
         "tempUnits":"c",
         "restart":"sudo -n systemctl restart homebridge",
         "theme":"teal",
         "auth":"form",
         "log":{
            "method":"systemd"
         }
      }
   ]
}
```

So if you want to add one more platform you have to do it this way:
```
{
   "accessories":[],
   "bridge":{
      "username":"xx:xx:xx:xx:xx",
      "name":"Homebridge",
      "pin":"123-45-678",
      "port":51826
   },
   "platforms":[
      {
         "platform":"config",
         "name":"Config",
         "port":8080,
         "sudo":true,
         "tempUnits":"c",
         "restart":"sudo -n systemctl restart homebridge",
         "theme":"teal",
         "auth":"form",
         "log":{
            "method":"systemd"
         }
      },
      {
         "platform":"Sonoff",
         "name":"Sonoff"
      }
   ]
}
```

**Comment by matty0511** [comment]
"port": 51826,
		"pin": "123-45-678"
	},

	"accessories": [],
	"platforms": [{
				"name": "Config",
				"port": 8080,
				"auth": "form",
				"theme": "teal",
				"restart": "sudo -n systemctl restart homebridge",
				"tempUnits": "c",
				"sudo": true,
				"log": {
					"method": "systemd"
					"platform": "Sonoff",
					"name": "Sonoff",
					"devices": [{
						"name": "Name of the accessory",
						"hostname": "The hostname or local ip address of the Sonoff device"
					}]
				}
so what am i doing wrong here? i ran it threw that json validator and it says flagging me at the line that has "method": "systemd"

**Comment by buenyamin-olgun** [comment]
There is a comma missing

**Comment by matty0511** [comment]
okay I got that. but when it i fix that i run into this
{
	"accessories": [],
	"bridge": {
		"username": "xx:xx:xx:xx:xx",
		"name": "Homebridge",
		"pin": "123-45-678",
		"port": 51826
	},
	"platforms": [{
			"platform": "config",
			"name": "Config",
			"port": 8080,
			"sudo": true,
			"tempUnits": "c",
			"restart": "sudo -n systemctl restart homebridge",
			"theme": "teal",
			"auth": "form",
			"log": {
				"method": "systemd"
			}
		},
		{
			"platform": "Sonoff",
			"name": "Sonoff",
			"devices": [
			}
			"name": "Sonoff1"
			"hostname": "172.16.10.146 "
		}
	]
}

"devices": [ is getting flagged

**Comment by matty0511** [comment]
Error: Parse error on line 29:
....10.146"				}]			}
---------------------^
Expecting ',', ']', got 'EOF'
How is the json file suppose to end?

**Comment by buenyamin-olgun** [comment]
You have multiple problems here:
- You are defining "name" for Sonoff Platform twice
- you do not close the square bracket with a square bracket (for devices) 
- there are again multiple commas missing
- your IP has a space in there before closing the string with a "

Here a corrected version:
```
{
   "accessories":[

   ],
   "bridge":{
      "username":"xx:xx:xx:xx:xx",
      "name":"Homebridge",
      "pin":"123-45-678",
      "port":51826
   },
   "platforms":[
      {
         "platform":"config",
         "name":"Config",
         "port":8080,
         "sudo":true,
         "tempUnits":"c",
         "restart":"sudo -n systemctl restart homebridge",
         "theme":"teal",
         "auth":"form",
         "log":{
            "method":"systemd"
         }
      },
      {
         "platform":"Sonoff",
         "name":"Sonoff",
         "devices":[],
         "hostname":"172.16.10.146"
      }
   ]
}
```

**Comment by matty0511** [comment]
So i thought I had an understanding of the for formatting but there still is an issue.
{
	"bridge": {
		"name": "Homebridge",
		"username": "mac",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
	"ports": {
		"start": 52100,
		"end": 52150,
		"comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
	},
	"accessories": [{
		"accessory": "sonoff-tasmota-mqtt-hsb",
		"name": "SONOFF1",
		"url": "soldier.cloudmqtt.com",
		"username": "hdgaxiac",
		"password": " -nSmU9qb-QZp",
		"caption": "sonffmqtt",
		"topics": {
			"setOn": "cmnd/sonoff/Power",
			"setHsb": "cmnd/sonoff/HSBColor",
			"status": "stat/sonoff/RESULT"
		},
		{
			"accessory": "SonoffTasmotaHTTP",
			"name": "Sonoff",
			"password": "The password from the web interface",
			"hostname": "The hostname of the Sonoff device"
		}
	}],
	"platforms": [{
		"platform": "PhilipsHue",
		"name": "Hue"
	}]
}

**Comment by aswathraja** [comment]
{
	"bridge": {
		"name": "Homebridge",
		"username": "mac",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
	"ports": {
		"start": 52100,
		"end": 52150,
		"comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
	},
	"accessories": [{
		"accessory": "sonoff-tasmota-mqtt-hsb",
		"name": "SONOFF1",
		"url": "soldier.cloudmqtt.com",
		"username": "hdgaxiac",
		"password": " -nSmU9qb-QZp",
		"caption": "sonffmqtt",
		"topics": {
			"setOn": "cmnd/sonoff/Power",
			"setHsb": "cmnd/sonoff/HSBColor",
			"status": "stat/sonoff/RESULT"
		}
	}, {
		"accessory": "SonoffTasmotaHTTP",
		"name": "Sonoff",
		"password": "The password from the web interface",
		"hostname": "The hostname of the Sonoff device"
	}],
	"platforms": [{
		"platform": "config",
		"name": "Config",
		"port": 8080,
		"sudo": false
	}]
}



Please check if it work using this config.json template.

**Comment by mafyata** [comment]
Here is your correct json file. Please check it at https://jsonlint.com/ next time. 


{
"bridge": {
"name": "Homebridge",
"username": "mac",
"port": 51826,
"pin": "031-45-154"
},

"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
"ports": {
	"start": 52100,
	"end": 52150,
	"comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
},
"accessories": [{
	"accessory": "sonoff-tasmota-mqtt-hsb",
	"name": "SONOFF1",
	"url": "soldier.cloudmqtt.com",
	"username": "hdgaxiac",
	"password": " -nSmU9qb-QZp",
	"caption": "sonffmqtt",
	"topics": {
		"setOn": "cmnd/sonoff/Power",
		"setHsb": "cmnd/sonoff/HSBColor",
		"status": "stat/sonoff/RESULT"
}	
},
	{
		"accessory": "SonoffTasmotaHTTP",
		"name": "Sonoff",
		"password": "The password from the web interface",
		"hostname": "The hostname of the Sonoff device"
	}
],
"platforms": [{
	"platform": "PhilipsHue",
	"name": "Hue"
}]
}
