### ISSUE TITLE
iOS 13 Device Grouping

### ISSUE THREAD

**Issue by dibble9012** [homebridge/homebridge#2313]
There seems to be no way at this point to group or ungroup accessories in iOS 13. Specifically I use homebridge-homeseer.

**Comment by netRunner0** [comment]
It is necessary for me in plugins

**Comment by benzman81** [comment]
This is a "feature" by apple. All services of an accessory are grouped and accessible by one tile in home app. To avoid this my understanding is that you need to create one accessory for each service.

**Comment by codyc1515** [comment]
This is fixed in iOS 13.2

**Comment by macjl** [comment]
Is there a way in homebridge to group multiple accessories into one with multiple services, to be able show them as one icon in Home?
