### ISSUE TITLE
Tuya Lan stop work

### ISSUE THREAD

**Issue by omriileviii** [homebridge/homebridge#2321]
Hello friends I have issue with Tuya-Lan plug I get this error

`0|homebridge  | [TuyaAccessory] Socket had a problem and will reconnect to פינת אוכל (EHOSTUNREACH)
0|homebridge  | [9/28/2019, 6:19:29 PM] [TuyaLan] Discovered דוד (6220088184f3eb7eae5e) identified as Outlet (3.1)
0|homebridge  | [TuyaAccessory] Socket had a problem and will reconnect to אורות (EHOSTUNREACH)
0|homebridge  | [TuyaAccessory] Socket had a problem and will reconnect to חדר שינה (EHOSTUNREACH)
0|homebridge  | [TuyaAccessory] Socket had a problem and will reconnect to סלון (EHOSTUNREACH)
0|homebridge  | [TuyaAccessory] Socket had a problem and will reconnect to מדרגות (EHOSTUNREACH)
0|homebridge  | [TuyaAccessory] Socket had a problem and will reconnect to מחסן (EHOSTUNREACH)
0|homebridge  | [TuyaAccessory] Socket had a problem and will reconnect to מטבח (EHOSTUNREACH)
0|homebridge  | [TuyaAccessory] Socket had a problem and will reconnect to דוד (EHOSTUNREACH)`

**Comment by Apollon77** [comment]
Better open that issue at the respective plugin repo. Btw: EHostUnreach means that up is noch reachable. Maybe restart device?

**Comment by codyc1515** [comment]
The issue is specific to the plug-in so you should raise it there. With regards to this issue I believe there is a fix if you update to the latest developer version.
