### ISSUE TITLE
Remote access issues with HomeBridge and tvOS13?

### ISSUE THREAD

**Issue by dcac** [homebridge/homebridge#2324]
I noticed today that I was getting a "No response" error on all my HomeBridge devices when not on my home network.

When I returned home (and to the same wifi network), I could again control the devices. I then switched my HomeKit Hub from my Apple TV (on tvOS 13, installed this weekend)  to my HomePod (still on os 12), and then turned wifi off on my iPhone. I could once again access my devices outside my network.

Switching back to my TV as the hub, however, killed external network access again.
Is anyone aware of an issue with tvOS 13 that could be affecting HomeBridge access? I'm concerned that when the new HomePod software is released, it will have the same effect on HomeBridge access.

Thanks for any insight.

**Comment by dcac** [comment]
Follow-up: logging out of, and back into, iCloud on the TV seems to have fixed this.

I'll keep monitoring it.

**Comment by netes** [comment]
I stumbled upon the same today. Homebridge shows `No response`, but only for the hub, accessories are fine (when accessing Home from an external network).

**Comment by masgar** [comment]
Same here. When connected to home WiFi all works fine, when i’m at office WiFi cannot control any device. ATV4k 13 and iPhone 13.1.2. Already erased atv and reconfigured from scratch.

**Comment by arcik100** [comment]
Same problem

**Comment by codyc1515** [comment]
Having a similar issue. All of my accessories work at home and off the network, except for my Samsung TV (which is a bridged accessory).

**Comment by masgar** [comment]
I don’t think is a homebridge problem. My iPhone running iOS 13 cannot access remotely to my accessories while my wife iPhone running latest iOS 12 works fine. I will try to erase my iPhone e reconfigure from scratch.

**Comment by emilletfr** [comment]
managed to make it work too by disconnecting / reconnecting from iCloud on Apple TV, then deleting / adding the automations.

**Comment by lumi74** [comment]
Logging the ATVs out from iCloud and reconnecting to iCloud worked for me too. Don't forget to complete AirPlay- and HomeKit-Setup afterwords.

**Comment by extric99** [comment]
#2040 

All check this topic for some instructions on how to resolve it

**Comment by stecoet46** [comment]
*Do you want to find out if your husband/wife/spouse is cheating on you?
*Do you want to hack your university/college database to change your
grade or do you want to get examination questions before the
examination day?
*Do you want to root/hack/sync your mobile phones?
*Do you want to have unrestricted access to your spouse’s /friends social      
media ( whatsapp, facebook, twitter, viber, BBM, e-mails?
*Do you want to recover deleted messages by your spouse?
*Do you want to clear police/criminal records?     
*Scam recovery    
lordhack242 AT GMAIL COM
