### ISSUE TITLE
Changed my router with new network - can’t add HomeKit to home app

### ISSUE THREAD

**Issue by macguru341** [homebridge/homebridge#2326]
Hello
I’ve changed my router and network in my home.
I delete my home from the home app and want to had from the start Homebridge . This is what i did:

1. kill homebridge
2. delete persist and accessories folders
4. delete homebridge from Home
5. fire up homebridge (restart my Pi)
6. Went  to Home and tried to add homebridge

But still in home app I don’t see the Homebridge when try adding new accessory 

What am I doing wrong ?

**Comment by iRayanKhan** [comment]
Do you get any errors? 
Try changing the Mac ID and Port

**Comment by AppleTechy** [comment]
Hey there. So my guess is that your Wifi network may be configured in a way that is blocking mdns. So I would take a look over in the wiki for basic troubleshooting. But I would download Bonjour Browser(I believe renamed to[ Discovery](https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12)) They have a MacOS and IOS app. See if it can pick up your Homebridge instance on your network.
