### ISSUE TITLE
Cannot add homebridge to iOS app

### ISSUE THREAD

**Issue by tedbrittchevy** [homebridge/homebridge#2328]
Was getting no response so deleted from home app. Now can add back.  Running homebridge on Mac hard wired and Apple TV on WiFi.   Deleted accessory and persist files, renamed bridge, user name and MAC address in config file and re ran.   Cannot scan or add by code.   Lan is 192.168.1... and wan is 10.10.10....   but was like that before without issue.  

Suggestions?

**Comment by iRayanKhan** [comment]
What kinda of HomeHubs do you have and what version are they on. Also it will help to have everything on the same Wi-Fi network *Maybe* even the same band (2.4/5g)

**Comment by tedbrittchevy** [comment]
I have a wink that connects everything.   They are all on 2.4
Jason

________________________________

**Comment by faxioman** [comment]
Same problem here after upgrading to 4.50 (I've already removed all plugins and accesories/persit/plugin-persist folders).
This is the only line logged after the qrcode:

```
[10/11/2019, 10:39:03 AM] Homebridge is running on port 51826.
```
Before the upgrade (sorry, I don't remeber the previous version) all was working.

This is my conf:

```
{
  "bridge": {
    "name": "Mansarda Bridge",
    "username": "xx:xx:xx:xx:xx:xx", // x replaced
    "port": 51826,
    "pin": "347-21-831"
  },
  "description": "Casina",
  "accessories": [],
  "platforms": [
  ]
}
```

**Comment by faxioman** [comment]
Update: no workaround found in older issues works for me... my homekit app never find the homebridge accessory.
Desperate mode enabled :)

**Comment by faxioman** [comment]
Probably related to this: https://github.com/nfarina/homebridge/issues/1893

**Comment by faxioman** [comment]
Setting 
```
"mdns": { "interface": "<my router ip>" }
```
in my config.json worked for me!

**Comment by EndorEwoksFC** [comment]
@faxioman Where exactly did you add this in the config.json?

**Comment by faxioman** [comment]
@EndorEwoksFC at root level.

**Comment by EndorEwoksFC** [comment]
Sorry I meant in your config.json file, where did you add the code you referenced?

**Comment by TheGingerDan** [comment]
I've tried the fix suggested, "interface", but that actually breaks homebridge for me.

via the Homebridge ui in the CONFIG area I added the code suggested:
for "hostip" I put the IP of my NAS server which is running Homebridge via Docker.

{
"mdns": {
"interface": "hostip"
},
"bridge": {
"name": "Homebridge AA5B",
"username": "0E:BC:46:51:AA:5B",
"port": 51712,
"pin": "031-45-154"
},
"accessories": [
{

When I add this to the config, I get this error: Error: bind EADDRNOTAVAIL HostIP:5353
at dgram.js:334:20
at processTicksAndRejections (internal/process/task_queues.js:82:21)

If I remove the interface command, homebridge runs again but I cannot add it to the Home app on iOS. I also don't understand why it shows port 5353.

**Comment by HunterDG** [comment]
homebridge in docker must be running with host or macvlan network.  Default bridge won't work.

**Comment by TheGingerDan** [comment]
> homebridge in docker must be running with host or macvlan network. Default bridge won't work.

Is this something I do through OMV/Docker?  I'm not familiar with what you're saying.

**Comment by HunterDG** [comment]
You are in the Homebridge repo.  See the `--net=host \` part of the docker run command in the [docker-homebridge](https://github.com/oznu/docker-homebridge) repo instructions.

**Comment by TheGingerDan** [comment]
> You are in the Homebridge (native, non-docker) repo. See the `--net=host \` part of the docker run command (or `network_mode: host` part of the docker-compose file) in the [docker-homebridge](https://github.com/oznu/docker-homebridge) repo instructions.

HunaterDG, Thank you!  I changed my Homebridge settings to run as HOST instead of BRIDGE and it now works!  I remember reading somewhere that it is supposed to run in bridge mode so I thought I had to keep it that way.

For anyone with OMV looking to run Homebridge in Docker:  When you run the docker image, choose HOST in the settings instead of BRIDGE.  Once I changed that, I was able to add Homebridge to the Home app.  Most importantly for me, I was able to add the Alexa plugin to Homebridge and can now use Siri to control accessories that only Alexa could before.  Specifically, I have some Kasa light switches that I had to use Alexa for.  Now, I can use Siri for all accessories.  Thank you again!

**Comment by dcuellar** [comment]
> > You are in the Homebridge (native, non-docker) repo. See the `--net=host \` part of the docker run command (or `network_mode: host` part of the docker-compose file) in the [docker-homebridge](https://github.com/oznu/docker-homebridge) repo instructions.
> 
> HunaterDG, Thank you! I changed my Homebridge settings to run as HOST instead of BRIDGE and it now works! I remember reading somewhere that it is supposed to run in bridge mode so I thought I had to keep it that way.
> 
> For anyone with OMV looking to run Homebridge in Docker: When you run the docker image, choose HOST in the settings instead of BRIDGE. Once I changed that, I was able to add Homebridge to the Home app. Most importantly for me, I was able to add the Alexa plugin to Homebridge and can now use Siri to control accessories that only Alexa could before. Specifically, I have some Kasa light switches that I had to use Alexa for. Now, I can use Siri for all accessories. Thank you again!

This helped me. I needed to be on host. Thank you.
