### ISSUE TITLE
HomeKit and Infrared

### ISSUE THREAD

**Issue by Biellmg** [homebridge/homebridge#2329]
Hello people. I have a project to control the air conditioner from Apple's HomeKit. One detail is that the air conditioner does not support HomeKit hahhaha. It would be my first step in this world and automation.

I was thinking of building a system with an infrared emitter, so I would send a "command" via the iOS HOME app to this assembled system and this one would activate the infrared for air conditioning transmitting the command. I'm a beginner and have no idea where to start. Does anyone have assembly suggestions (which hardware and software to use) or links to let me know better. thankful

**Comment by NorthernMan54** [comment]
This is one example of what your looking for

https://github.com/NorthernMan54/homebridge-HTTP-IRBlaster

They are more

**Comment by Biellmg** [comment]
thank you.  I am open for more suggestions.  remembering that I am a beginner and would be very happy if I found a very detailed step by step

**Comment by mafyata** [comment]
You can buy Broadlink Rm/Rm Pro and install homebridge-broadlink-rm plugin
