### ISSUE TITLE
Ability to restart Homebridge service without having to delete Accessories and Persist folder?

### ISSUE THREAD

**Issue by dcedjiayi** [homebridge/homebridge#2334]
Hello,

I know that there is this issue when Homebridge stops running due to either power failure or manual stoppage (Ctrl+C) we have to delete those two folders before we can run Homebridge again. 

Is there anyway to circumvent this because everything my board goes down I have to restart the Homebridge service, which I think is fine. Even up till deleting the two folders is fine but on my iPhone, I have to re-add the Homebridge again via QR or the given code otherwise all the accessories just report 'no response'. I have to plug in a monitor to look for the code or to scan the QR again.

Really appreciate any of your replies. Thank you.

**Comment by iRayanKhan** [comment]
You don't have to delete your ```persist``` and ```accessories``` folders to restart homebridge.
To make it run headless and 24/7 after a reboot is to do the following:
```sudo npm I -g pm2```
``` pm2 startup```
```pm2 startup``` will print out a large string, copy and paste it.
then do:
```pm2 start homebridge```
finally do
```pm2 save```
[PM2 Link NPM](https://www.npmjs.com/package/pm2)

**Comment by dcedjiayi** [comment]
I will try that part out. I still have some other issues with regards to Homebridge I have to settle before coming to this step. 

Thank you for your reply. It will definitely come in useful!

**Comment by iRayanKhan** [comment]
@dcedjiayi What other kinds of issues? I can try to help out where I can.

**Comment by dcedjiayi** [comment]
HI @iRayanKhan I am making progress on the other problems that I am facing. There is one thing that I need clarification. It is with accessory reachability. What does 'accessory.reachbility' do? Does it send like some sort of signal to the accessory to see if it is available or...?
