### ISSUE TITLE
HomeBridge falls on its face when any one platform has an issue

### ISSUE THREAD

**Issue by bwoodruff** [homebridge/homebridge#2339]
### Expected Behavior

If a single platform stops working as expected the accessories associated with that platform can go into a 'not responding' state, but all other platforms/accessories added to homebridge should continue to function.

### Current Behavior

All accessories in homebridge will go to 'not responding' whenever there is a problem with any one platform

### Steps to Reproduce (for bugs)

Add the homebridge-myq2 v1.1 plugin to your homebridge installation
All accessories in homebridge will go to 'not responding' even though the problem is only with homebridge-myq2

(see this issue: https://github.com/hjdhjd/homebridge-myq2/issues/4 )

E.g. All of my Nest accessories went unresponsive because MyQ changed their API. It would be nice if homebridge provided isolation. I realize this could be avoided by running a separate instance of homebridge for each platform, but that further complicates an already relatively complex setup.

### Versions
- **Homebridge**: `0.4.46
- **Node**:       v8.10.0
- **OS**:        Ubuntu 18.04.3 LTS

**Comment by codyc1515** [comment]
This is somewhat on the developers to be proactive on, but even I am guilty of this. I agree that Homebridge could do a better job at handling these issues.

**Comment by dcedjiayi** [comment]
This also happened to me. In my case, I was on a single platform and when one of the accessory is giving issues the rest will not respond as well.

**Comment by NorthernMan54** [comment]
The workaround for this is to create separate homebridge instances, and run the problematic plugins in their own instance

**Comment by codyc1515** [comment]
That’s very much the point though. It’s a _workaround_, not a fix.

**Comment by bwoodruff** [comment]
> It’s a _workaround_, not a fix.

Indeed. And not necessarily a very practical one.

**Comment by bwoodruff** [comment]
This continues to be an issue. Replying to stave off `stale bot`.

**Comment by donavanbecker** [comment]
@bwoodruff if you submit a PR, we can test it and get this in for a fix on this.

In the time being. If using config-ui-x, oznu has hb-service built into it. This make it really easy to create [multiple instances](https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command#multiple-instances).

**Comment by bwoodruff** [comment]
I wish I could. I'm not much of a programmer, just an end-user, so unfortunately I'm not in a position to create a PR.

Is config-ui-x being considered for inclusion by default? And should the homebridge installation instructions be updated to suggest creating a separate instance for each platform, if that is the official answer to avoid having one API change from one vendor bring the whole system down?

**Comment by donavanbecker** [comment]
[Multiple Instances](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS#multiple-instances)

**Comment by armandr** [comment]
Maybe we can ask for better plugin error handling as a feature?  
Technically, it may not be BUG for Homebridge because it works fine.

Keeping it running when a plugin fails sounds pretty reasonable.  The whole MyQ event being a great example.

**Comment by bwoodruff** [comment]
That's exactly what I was hoping for, @armandr. It seems there aren't resources available to implement that, though. :(
