### ISSUE TITLE
Question: Switch that is also set from code

### ISSUE THREAD

**Issue by odrobnik** [homebridge/homebridge#2342]
I have an accessory with a timer that refreshes the battery and AC states of of my electric car. I also have two switches, one to turn on charging, one to turn on AC for 5 minutes.

I am setting the switch to on in code and that is definitely calling the setter for the switch. I noticed that setting the characteristic also causes the setter to be called. But what I don't understand is why the switch doesn't show as turned on in Home app.

Can you provide an example of how I would deal with such a scenario?

**Comment by Frank-Friemel** [comment]
If I got you right you want to reflect the state changes to HomeKit? Here‘s a project that‘s doing exactly this [notification server](https://github.com/Supereg/homebridge-http-notification-server)

**Comment by odrobnik** [comment]
Ok, this is the key line: 

```
this.service.updateCharacteristic(characteristic, value);
```

I was using setValue but that seems to call the setter. I since changed to use getCharacteristic().updateValue()... how is this different from updateCharacteristic?

**Comment by NorthernMan54** [comment]
It is a wrapper around updateValue()

https://github.com/KhaosT/HAP-NodeJS/blob/e87f7743c8f42d5f210a6fabf15591567c665b64/src/lib/Service.ts#L272
