### ISSUE TITLE
HAP-NodeJS 0.5.0 update to fully support Nest CAM

### ISSUE THREAD

**Issue by nscheffer** [homebridge/homebridge#2344]
### Pre Steps
Migration to Google account done.
Homebridge working using a Raspeberry Pi 3.
Currently Protect, Thermostat from Nest are working well.

Adrian Cable is currently updating the chrisjshull/homebridge-nest plug-in to add Camera support but one Homebridge component need to be updated.
### Expected Behavior

Need HAP-NodeJS 0.5.0
### Current Behavior

HAP-NodeJS 0.4.5
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by KhaosT** [comment]
Yeah... updating to hap-nodejs v0.5.x will happen eventually... the TypeScript rewrite unintentionally changed some behavior and we want to be sure we captured those issues before switching homebridge to use it.

cc @adriancable Just curious, so far have you run into any issues that break your setup when running homebridge with hap-nodejs v0.5.x?

**Comment by nscheffer** [comment]
Thanks for the quick update !
Available to do some test if needed to prep the update to 0.5x ?

**Comment by Apollon77** [comment]
Maybe an idea could be to start a branch for homebridge with the neeed changes so that it is easier to install and try out "as package"?!

**Comment by adriancable** [comment]
@KhaosT - it basically just works. The only functional change needed is to support bridged cameras in lib/server.js, around line 440, where we now need to set cameraSource:

    // The returned "services" for this accessory are simply an array of new-API-style
    // Service instances which we can add to a created HAP-NodeJS Accessory directly.

    var accessoryUUID = uuid.generate(accessoryType + ":" + (uuid_base || displayName));

    var accessory = new Accessory(displayName, accessoryUUID);
    **accessory.cameraSource = accessoryInstance.cameraSource;**

If memory serves I needed to change some paths in some of the requires, because HAP-NodeJS 0.5.0 moves some files around.

Other than that, everything works. I have been running in this configuration for about a month with a large number of different kinds of accessories with no issues.

**Comment by cr3ative** [comment]
Great to hear this is being worked on. Exciting times ahead!

**Comment by isaaclimdc** [comment]
Same, I'm super excited for this!

**Comment by jdtsmith** [comment]
What's new in HAP-NodeJS 0.5.x that has people excited?

**Comment by adriancable** [comment]
@jdtsmith - for me, support for bridged cameras.

The camera support in HAP-NodeJS 0.4.5 has a poor UX in the sense that you need to manually type in pairing codes etc. to the phone. You can't make a bridge which emits a camera accessory and have it "just work".

**Comment by jdtsmith** [comment]
Thanks!

**Comment by jonathansimmons** [comment]
@KhaosT I appreciate all the work that has gone into this. Thanks in advance for considering this request at all. Any chance we can get an official bump to HAP-Nodejs 0.5.x before typescript?

From @adriancable input, it seems like a relatively minor adjustment to be parked behind typescript. I'd love to upgrade my nest account and see @adriancable nest plugin have camera support soon.

**Comment by superjunky** [comment]
> @KhaosT I appreciate all the work that has gone into this. Thanks in advance for considering this request at all. Any chance we can get an official bump to HAP-Nodejs 0.5.x before typescript?
> 
> From @adriancable input, it seems like a relatively minor adjustment to be parked behind typescript. I'd love to upgrade my nest account and see @adriancable nest plugin have camera support soon.

+1 👍🏼

**Comment by titoudoc** [comment]
Indeed, it would be wonderfull...

**Comment by cr3ative** [comment]
Bumping to keep it active!

**Comment by gabemunro** [comment]
Would be amazing if PR #2391 can get ironed out!

**Comment by donavanbecker** [comment]
HAP-NodeJS 0.5.0 update for homebridge is currently in beta. But a Bridge API is not currently built into HAP-NodeJS.
