### ISSUE TITLE
Unistall homebridge from raspberry pi 3

### ISSUE THREAD

**Issue by ipatiris** [homebridge/homebridge#2347]
How to unistall entirely Homebridge?

### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by mkellsy** [comment]
sudo npm uninstall -g homebridge  
rm -fR ~/.homebridge

**Comment by gitcloneguy** [comment]
@ipatiris there

**Comment by GabrielDuarteM** [comment]
if someone lands on this from google, the correct way to uninstall it now is shown funny enough on the installation guide:

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux#how-to-uninstall-homebridge
