### ISSUE TITLE
No connection to Homebridge after iOS 13.2 Update

### ISSUE THREAD

**Issue by buenyamin-olgun** [homebridge/homebridge#2348]
Homebridge was just working fine.

After I upgraded my iPhone to iOS 13.2 the homebridge connection couldn't be established anymore.

So I tried to remove it from the Home App and re-add it.

Re-Adding is not possible, it is hanging in the screen "searching for device" for a while and after that "Device could not be found".

What I've tried so far:
- change username
- change PIN
- check if port is open
- restart Raspberry Pi 3B
- restart iPhone
- the WiFi Trick (forget WiFi and reconnect)
- reinstalled the Home-App

### Expected Behavior
Connection should work.

### Current Behavior
Connection does not work.

### Steps to Reproduce (for bugs)
Update to iOS 13.2

### Versions

- **Homebridge**: 0.4.50
- **Node**:      v10.17.0
- **OS**:         DietPi v6.26.3

**Comment by NajibNour** [comment]
I'm Running in the same issue. My configuration has not changed in months. 13.2 seemed to break it

**Comment by tbrek** [comment]
I'm running iOS 13.2 on my phone, still works as a treat on my Pi3.

**Comment by NajibNour** [comment]
One thing I have noticed this morning is when I restart my google wifi system My devices respond for a couple of minutes and then revert back to being not responsive.

**Comment by NajibNour** [comment]
I do not believe this is a homebridge issue for me but more of a network issue for me... will run more tests.

**Comment by heppstux** [comment]
same issue just brings up this errors from Homebridge:
```
[2019-11-1 13:50:29] [Hue] control: 5 accessories
[2019-11-1 13:50:34] [Hue] 192.***.***.21: bridge request 1: get /config
[2019-11-1 13:50:34] [Hue] 192.***.***.21: bridge communication error ETIMEDOUT on 192.***.***.21
```

**Comment by jonerikandersen** [comment]
Same issue for me. This is a 13.2 issue. tvOS on 13.2 breaks Homebridge connections, all items have "no answer". Samme issue on iPhone X with 13,2 and older iPhone 8 with 12.x.

**Comment by HolyGiraffe** [comment]
struggeling with the same issue... did work prior with older version of homebridge (running 13.2). 
needed to update to latest homebride due to installing a plugin, now also no connection to homebridge ;(

**Comment by craigspree** [comment]
Same issue after updating iPhone 11 to iOS 13.2

**Comment by buenyamin-olgun** [comment]
I managed to fix it somehow but I don't know the exact step what fixed it.

Here are the doings I did:
- restarted my home router
- I have installed homebridge-config-ui-x, there I pressed "reset homebridge" at the bottom of the first page
- removed my home from the Home-App, removed the app and installed it again
- scanned the new QR Code of homebridge

I'm letting the issue open for the other people which seem have to also have an issue after upgrading to iOS 13.2.

**Comment by NajibNour** [comment]
> I managed to fix it somehow but I don't know the exact step what fixed it.
> 
> Here are the doings I did:
> 
> * restarted my home router
> * I have installed homebridge-config-ui-x, there I pressed "reset homebridge" at the bottom of the first page
> * removed my home from the Home-App, removed the app and installed it again
> * scanned the new QR Code of homebridge
> 
> I'm letting the issue open for the other people which seem have to also have an issue after upgrading to iOS 13.2.

Let us know after a day or so if it still is working! Not ready to lose my scenes and automations.

**Comment by thetatae** [comment]
I'm not sure if this is related to iOS13.2. I experienced suddenly "no responding" accessories configured on Homebridge even on iOS13.1.3. So far I have tried to removed and reinstalled Homebridge on my Synology (with Docker) and couldn't add it back to HomeKit. It seems like Homebridge is no longer discoverable as Home App couldn't find any accessories anymore.

**Comment by Nousemusic** [comment]
I had the same problems: Homebridge was no longer found in the Home app starting with iOS 13.2 and could therefore not be added again.

My solution: I changed the username and the PIN in config.json, then Homebridge was found again and could be added to the Home app.

**Comment by thetatae** [comment]
> I had the same problems: Homebridge was no longer found in the Home app starting with iOS 13.2 and could therefore not be added again.
> 
> My solution: I changed the username and the PIN in config.json, then Homebridge was found again and could be added to the Home app.

I wonder that's not the case for me as I've done the RESET of the Homebridge which changed the PIN and the username in one shot. Still, Homebridge disappeared and couldn't be found by Home app.

**Comment by pbksol** [comment]
This issue is related to non certified HomeKit devices only. You can reset everything and as often as you want – it just won't solve it. Every certified HomeKit device is still accessible via remote (outside the own network) and works. Homebridge Stuff is showing "no answer" – but you can still command devices (switches, Outlets, and so on) but no cameras or so. I was able to reproduce this by upgrading an Apple TV from tvOS 13.0 to 13.2.

So don't reset your Homebridge, don't remove it from your iCloud account as long as you're using it some kind of productive with automation in place – which will be lost afterwards. My advice would be to wait for somebody more deeply into the technical details of HomeKit looks into this issue.

**Comment by thetatae** [comment]
> This issue is related to non certified HomeKit devices only. You can reset everything and as often as you want – it just won't solve it. Every certified HomeKit device is still accessible via remote (outside the own network) and works. Homebridge Stuff is showing "no answer" – but you can still command devices (switches, Outlets, and so on) but no cameras or so. I was able to reproduce this by upgrading an Apple TV from tvOS 13.0 to 13.2.
> 
> So don't reset your Homebridge, don't remove it from your iCloud account as long as you're using it some kind of productive with automation in place – which will be lost afterwards. My advice is to wait for somebody more deeply into the technical details of HomeKit looks into this issue. And hold back the iOS 13.2 update if you don't want to deal with the limitations.

Please advice how I can add my Homebridge back to Home app or it's not possible as of now?

**Comment by KhaosT** [comment]
So far my setup was still working on iOS 13.2... It sounds like one of the plugin is misbehaving and iOS 13+ added additional validation that resulted homebridge (with the involved plugin) no longer works correctly. If possible, can you guys post what are the plugins you are using with homebridge, and if possible, try collect log from iOS device and see if there are any error shown from `homed`?

**Comment by thetatae** [comment]
> So far my setup was still working on iOS 13.2... It sounds like one of the plugin is misbehaving and iOS 13+ added additional validation that resulted homebridge (with the involved plugin) no longer works correctly. If possible, can you guys post what are the plugins you are using with homebridge, and if possible, try collect log from iOS device and see if there are any error shown from `homed`?

<img width="1310" alt="Screen Shot 2019-11-01 at 7 19 10 PM" src="https://user-images.githubusercontent.com/57340871/68108675-04214580-ff1b-11e9-849b-8ee5edd17e04.png">

here is my list
I start to wonder if the plug-in "Homebridge Config UI X" might cause some issue. I have my finger crossed though. Sorry if I misunderstood something.

**Comment by pbksol** [comment]
> I start to wonder if the plug-in "Homebridge Config UI X" might cause some issue. I have my finger crossed though. Sorry if I misunderstood something.

And you solved the problem. I tried it on one primary and two test installations. With Config-UI installed all installations stop being accessible from remote connections. Removing Config-UI-X and it's platform section in the config and restarting Homebridge afterwards immediately restores remote connectivity.

Reinstalling Config-UI-X shows the same "no response" behavior.

This Config-Plugin is nice but it's the worst one available. It's not the first time is causes massive trouble (currently Homebridge service hangs after rebooting the Pi and you have to manually restart it – which might be related to this issue).

If you have Config-UI-X installed… Remove it. Simple as that :-)

**Comment by thetatae** [comment]
> > I start to wonder if the plug-in "Homebridge Config UI X" might cause some issue. I have my finger crossed though. Sorry if I misunderstood something.
> 
> And you solved the problem. I tried it on one primary and two test installations. With Config-UI installed all installations stop being accessible from remote connections. Removing Config-UI-X and it's platform section in the config and restarting Homebridge afterwards immediately restores remote connectivity.
> 
> Reinstalling Config-UI-X shows the same "no response" behavior.
> 
> This Config-Plugin is nice but it's the worst one available. It's not the first time is causes massive trouble (currently Homebridge service hangs after rebooting the Pi and you have to manually restart it – which might be related to this issue).
> 
> If you have Config-UI-X installed… Remove it. Simple as that :-)

Very nice =D

**Comment by mafyata** [comment]
I don’t have problems on ios13.2
I am using homebridge with config ui x and samsung tizen plugins

**Comment by pbksol** [comment]
> I am using homebridge with config ui x and samsung tizen plugins
You're talking about remote access and not within your own network?

Are you running Homebridge via init.d or systemd?

**Comment by jvdh1978** [comment]
> > > I start to wonder if the plug-in "Homebridge Config UI X" might cause some issue. I have my finger crossed though. Sorry if I misunderstood something.
> > 
> > 
> > And you solved the problem. I tried it on one primary and two test installations. With Config-UI installed all installations stop being accessible from remote connections. Removing Config-UI-X and it's platform section in the config and restarting Homebridge afterwards immediately restores remote connectivity.
> > Reinstalling Config-UI-X shows the same "no response" behavior.
> > This Config-Plugin is nice but it's the worst one available. It's not the first time is causes massive trouble (currently Homebridge service hangs after rebooting the Pi and you have to manually restart it – which might be related to this issue).
> > If you have Config-UI-X installed… Remove it. Simple as that :-)
> 
> Very nice =D

Unfortunately here still the same issue, also after removing config-ui-x...

**Comment by pbksol** [comment]
> Unfortunately here still the same issue, also after removing config-ui-x...
What are the other plugins you've installed?

**Comment by jvdh1978** [comment]
> Unfortunately here still the same issue, also after removing config-ui-x...
> What are the other plugins you've installed?

I have openHAB2-complete, Nest, HarmonyHubWebSocket

**Comment by NajibNour** [comment]
Packages I have installed are 

├── homebridge@0.4.50
├── homebridge-apple-tv@1.0.2
├── homebridge-camera-ffmpeg@0.1.14
├── homebridge-dht@0.1.27
├── homebridge-garagedoor-command@0.2.1
├── homebridge-nest@3.5.1
├── homebridge-nest-cam@0.0.17
├── homebridge-people@0.6.2
├── homebridge-tplink-smarthome@4.0.1
├── homebridge-webos-tv@1.6.2
├── node-appletv@1.0.10
├── node-gyp@5.0.5
├── npm@6.12.1
├── request@2.88.0
└── ws@7.2.0

**Comment by ccie3611** [comment]
I have created new a fresh new RaspberryPi with new install of base components to fire up Homebridge and I can't see it to add as an accessory in Home on ios 13.2. Added a few plug-ins, same result can't find it. Backed dated Homebridge to a few different versions, still can't find it.  Let it site over night with newest homebridge - same result. I did a wireshark capture the multicast mdns announcements coming from the RP on a computer on my network so the traffic is getting through.

**Comment by mafyata** [comment]
> > I am using homebridge with config ui x and samsung tizen plugins
> > You're talking about remote access and not within your own network?
> 
> Are you running Homebridge via init.d or systemd?

Systemd

**Comment by thetatae** [comment]
> > > I start to wonder if the plug-in "Homebridge Config UI X" might cause some issue. I have my finger crossed though. Sorry if I misunderstood something.
> > 
> > 
> > And you solved the problem. I tried it on one primary and two test installations. With Config-UI installed all installations stop being accessible from remote connections. Removing Config-UI-X and it's platform section in the config and restarting Homebridge afterwards immediately restores remote connectivity.
> > Reinstalling Config-UI-X shows the same "no response" behavior.
> > This Config-Plugin is nice but it's the worst one available. It's not the first time is causes massive trouble (currently Homebridge service hangs after rebooting the Pi and you have to manually restart it – which might be related to this issue).
> > If you have Config-UI-X installed… Remove it. Simple as that :-)
> 
> Very nice =D

I got it wrong. My case is not just about remote access to homebridge. The problem is that I couldn't even add any accessories configured on Homebridge to Home app. So I did the test and found out it's not working with or without Config-UI-X. So I'm screwed still as of now.

**Comment by buenyamin-olgun** [comment]
> > I managed to fix it somehow but I don't know the exact step what fixed it.
> > Here are the doings I did:
> > 
> > * restarted my home router
> > * I have installed homebridge-config-ui-x, there I pressed "reset homebridge" at the bottom of the first page
> > * removed my home from the Home-App, removed the app and installed it again
> > * scanned the new QR Code of homebridge
> > 
> > I'm letting the issue open for the other people which seem have to also have an issue after upgrading to iOS 13.2.
> 
> Let us know after a day or so if it still is working! Not ready to lose my scenes and automations.

It works! For the others: I never removed homebridge-config-ui-x. Just did the steps above.


> This issue is related to non certified HomeKit devices only. You can reset everything and as often as you want – it just won't solve it. Every certified HomeKit device is still accessible via remote (outside the own network) and works. Homebridge Stuff is showing "no answer" – but you can still command devices (switches, Outlets, and so on) but no cameras or so. I was able to reproduce this by upgrading an Apple TV from tvOS 13.0 to 13.2.
> 
> So don't reset your Homebridge, don't remove it from your iCloud account as long as you're using it some kind of productive with automation in place – which will be lost afterwards. My advice is to wait for somebody more deeply into the technical details of HomeKit looks into this issue. And hold back the iOS 13.2 update if you don't want to deal with the limitations.

Could you post evidence for that? If that would be right, I couldn't use homebridge right now. But I can and many others also.

**Comment by tekuonline** [comment]
Question, any of you guys have this problem use Google WiFi? I am asking because this is happening on my setup. I have a mac mini running homebridge. When I go to the room where my Mac mini and one google wifi are, it starts working. If my phone is connected to any of the other 3 google wifi devices, it wont work. 

Starting to think that google might have changed something on these mesh network.

**Comment by maastrichtrob** [comment]
Same issue. No response from Homebridge accessoires. I deleted Homebridge from Homekit. Changed Homebridge name,username and code. Added  Homebridge to Homekit again. Accessoires are visible but do not update. Selecting a device (by tapping once) results in a response and device can be controlled. But again no automatic update of the status of the device. Running latest packages.

**Comment by NajibNour** [comment]
> Question, any of you guys have this problem use Google WiFi? I am asking because this is happening on my setup. I have a mac mini running homebridge. When I go to the room where my Mac mini and one google wifi are, it starts working. If my phone is connected to any of the other 3 google wifi devices, it wont work.
> 
> Starting to think that google might have changed something on these mesh network.

I can kinda confirm this. I've had the same behavior too.

**Comment by shereefalkady** [comment]
@NajibNour !! Yes !!! I was waiting for someone to say that ... my problems are also with google wifi ... and I believe it’s their last security update ... as someone with several homes and setups I find it interesting though - not all the homes stopped - only certain homes 
![17B9873F-209D-4C8D-981D-5C8EA8EBDC08](https://user-images.githubusercontent.com/33227062/68207742-4197d880-ffd8-11e9-8b16-a175d280b3c5.png)

**Comment by shereefalkady** [comment]
And they coincide with the google updates

**Comment by maastrichtrob** [comment]
> > Question, any of you guys have this problem use Google WiFi? I am asking because this is happening on my setup. I have a mac mini running homebridge. When I go to the room where my Mac mini and one google wifi are, it starts working. If my phone is connected to any of the other 3 google wifi devices, it wont work.
> > Starting to think that google might have changed something on these mesh network.
> 
> I can kinda confirm this. I've had the same behavior too.

No Google WiFi overhere. Same issue on Ubiquity

**Comment by thetatae** [comment]
> @tekuonline @NajibNour !! Yes !!! I was waiting for someone to say that ... my problems are also with google wifi ... and I believe it’s their last security update ... as someone with several homes and setups I find it interesting though - not all the homes stopped - only certain homes
> ![17B9873F-209D-4C8D-981D-5C8EA8EBDC08](https://user-images.githubusercontent.com/33227062/68207742-4197d880-ffd8-11e9-8b16-a175d280b3c5.png)

I’m using Google WiFi and started experiencing the Homebridge issues on 01/11/19. Damn it. This is it.

**Comment by shereefalkady** [comment]
@thetatae its that along with 13.2 I still have some setups on google wifi that are working - so not necessarily just that too ...
On Friday I will try the following 
1. Changing my switch 
2. Resetting google wifi 
3. Adding brand new bridges to brand new homes 

Will keep you updated ...

**Comment by eford321** [comment]
Same here. Google wifi and iOS 13.2.  

Homebridge does appear in iOS home app after several hours, but devices show "No Response" after most actions. 

Same result after a complete rebuild and only adding 1 dummy switch.

**Comment by thetatae** [comment]
@shereefalkady my iOS was 13.1.2 when I started having the issues. So I don't think my issue was related to 13.2. Perhaps there's some other problems with 13.2 but it's just not my case. It's most likely that my Homebridge didn't work because of Google Wifi (3mesh setup). It happened right after Google put some fancy update on 01/11/19. I will try to prove this when I get a new set of routers in place. And I will keep you guys posted.

**Comment by eford321** [comment]
Issue also started for me on iOS 13.1.2.   My google wifi firmware is 12371.52.22 with a 4 node mesh.
Found a workaround! disconnect all mesh nodes except the primary node.  

Please notify google (via the app) that 12371.52.22 broke HomeKit automation.

**Comment by thetatae** [comment]
> Issue also started for me on iOS 13.1.2. My google wifi firmware is 12371.52.22 with a 4 node mesh.
> Found a workaround! disconnect all mesh nodes except the primary node.
> 
> Please notify google (via the app) that 12371.52.22 broke HomeKit automation.

disconnecting all mesh nodes means that we can't use Google Wifi mesh with Homebridge or just disconnect and reconnect?
It's might be google intention to break apple home automation =D

**Comment by maastrichtrob** [comment]
Don't think it's only Google related. The issue started for me on IOS 13.1.2. I do not use Google Mesh Wifi but Ubiquity Unifi.

**Comment by eford321** [comment]
Works perfectly when mesh nodes are removed from google wifi.   Not sure about Ubiquity.

There are reports of discovery failing on google mesh wifi for other products that use discovery, like Wemo and Nest....

**Comment by shereefalkady** [comment]
@eford321 was your mesh network wired through a switch ?

**Comment by mafyata** [comment]
Using APPLE Home with GOOGLE router , whyyy? I am using Apple airport extreme , 6th gen as primary and 5th gen as wifi extender. I don’t have any problem with apple home .

**Comment by muzzymate** [comment]
I am using the Google Wifi mesh system. The "No Response" issue for me is only occurring on Homebridge items. Native Homekit devices are functioning as expected.

**Comment by Nousemusic** [comment]
> Accessoires are visible but do not update. Selecting a device (by tapping once) results in a response and device can be controlled. But again no automatic update of the status of the device. 

I've have exactly the same behavior since a few days. WIFI is also done via a mesh system, but not Google. 

Until a few days ago, remote access was also possible via Apple TV 3, but this is no longer possible.

**Comment by NajibNour** [comment]
I have just updated my Apple TV to IOS 13.3 beta, and it seems to have fixed the problem! Will confirm Tommorow after a day of testing!

**Comment by dhpeter** [comment]
> Issue also started for me on iOS 13.1.2. My google wifi firmware is 12371.52.22 with a 4 node mesh.
> Found a workaround! disconnect all mesh nodes except the primary node.
> 
> Please notify google (via the app) that 12371.52.22 broke HomeKit automation.

can confirm, disonnected the google wifi bridge that my rPI3 was connected to it is now broadcasting

**Comment by dalethomas81** [comment]
> > Issue also started for me on iOS 13.1.2. My google wifi firmware is 12371.52.22 with a 4 node mesh.
> > Found a workaround! disconnect all mesh nodes except the primary node.
> > Please notify google (via the app) that 12371.52.22 broke HomeKit automation.
> 
> can confirm, disonnected the google wifi bridge that my rPI3 was connected to it is now broadcasting

This fixed it for me as well. Long story short - it started with my Apple TV being connected to wireless backhaul on a google WiFi mesh node. Moves that to a hardwired switch off the primary node and boom instant fix. Then, could we add a new instance of Homebridge via my phone connected to a mesh node. Moved close to the primary Google WiFi node and boom it worked.

**Comment by netRunner0** [comment]
https://youtu.be/a1tfUcQ6gLs

Just see how it works on 13.2 ...

It all started with an update to 13.
I also use a lot of native devices. Apple TV has nothing to do with it. If you run a program for working with Homekit on Apple TV, everything works perfectly (on Apple TV).

Perhaps this is due to the upgrade of HAP or iOS, or the mesh network at home? I will try to use LTE all day and talk about the result.

**Comment by dalethomas81** [comment]
> https://youtu.be/a1tfUcQ6gLs
> 
> Just see how it works on 13.2 ...
> 
> It all started with an update to 13.
> I also use a lot of native devices. Apple TV has nothing to do with it. If you run a program for working with Homekit on Apple TV, everything works perfectly (on Apple TV).
> 
> Perhaps this is due to the upgrade of HAP or iOS, or the mesh network at home? I will try to use LTE all day and talk about the result. Automation also works perfectly.

In my case, the Apple TV is my homekit hub so Homebridge connections route through it. Updated my comment to reflect that.

**Comment by shereefalkady** [comment]
Native HomeKit items are not being affected ... only homebridge

**Comment by netRunner0** [comment]
> Native HomeKit items are not being affected ... only homebridge

This happens with all devices.

**Comment by muzzymate** [comment]
> Native HomeKit items are not being affected ... only homebridge

> This happens with all devices.

In my circumstance, only Homebridge devices are affected by the Not Responding issue. Native Homekit devices are working ok, both while on local network and off.

**Comment by hdcola** [comment]
> One thing I have noticed this morning is when I restart my google wifi system My devices respond for a couple of minutes and then revert back to being not responsive.



> > Accessoires are visible but do not update. Selecting a device (by tapping once) results in a response and device can be controlled. But again no automatic update of the status of the device.
> 
> I've have exactly the same behavior since a few days. WIFI is also done via a mesh system, but not Google.
> 
> Until a few days ago, remote access was also possible via Apple TV 3, but this is no longer possible.



> > > Issue also started for me on iOS 13.1.2. My google wifi firmware is 12371.52.22 with a 4 node mesh.
> > > Found a workaround! disconnect all mesh nodes except the primary node.
> > > Please notify google (via the app) that 12371.52.22 broke HomeKit automation.
> > 
> > 
> > can confirm, disonnected the google wifi bridge that my rPI3 was connected to it is now broadcasting
> 
> This fixed it for me as well. Long story short - it started with my Apple TV being connected to wireless backhaul on a google WiFi mesh node. In my case, the Apple TV is my homekit hub. I moved the Apple TV to a hardwired switch off the primary node and boom instant fix. Then, could we add a new instance of Homebridge via my phone connected to a mesh node. Moved close to the primary Google WiFi node and boom it worked.
> 
> To be clear, it looks like Homebridge specific Bonjour messages do not work over Google WiFi mesh since the update on Nov 1st.

I have the same problem as you. After the 2019 October version update, all the muticasts were blocked. Today I re-initialized the google wifi factory reset and the problem disappeared. I think this is the google network during the upgrade process.  The configuration has been caused by a bad update.  You can try to reconfigure your google wifi after rebooting.  This is really a problem that has bothered me for nearly two weeks.

**Comment by vlar** [comment]
Same issue here.. 
Noticed a Google Wifi update along with an iOS update.. 
I have a slightly different homebridge version compared to you and it tells me it can't see my homekit hub (Apple TV 4k and iPad)

Homebridge is on the green otherwise and homekit works with certified devices.

I'm leaning toward a G wifi set up and I just wonder whether there is an active fix that is proven to work over the mesh network ?

**Comment by netRunner0** [comment]
> https://youtu.be/a1tfUcQ6gLs
> 
> Just see how it works on 13.2 ...
> 
> It all started with an update to 13.
> I also use a lot of native devices. Apple TV has nothing to do with it. If you run a program for working with Homekit on Apple TV, everything works perfectly (on Apple TV).
> 
> Perhaps this is due to the upgrade of HAP or iOS, or the mesh network at home? I will try to use LTE all day and talk about the result. Automation also works perfectly.

Eve Home and had virtually no connection problems.
Check in yourself

**Comment by craigspree** [comment]
I am also on Google WiFi with 3 pucks. The RPi 3b+ is plugged directly into the puck that is plugged directly into the fiber modem. Before the latest G Wifi security update, everything was working great for months.

Reproduction steps:

1. Reboot G Wifi 
2. Note that all Homebridge devices work great for 10-30 minutes
3. Note that after 30 minutes, all 'non-official' Homebridge devices show as "No Response" 
4. Reboot G Wifi
5. Note that all Homebridge devices begin working again for 30 minutes. This process cycles back to step 3...

iPhone is running iOS 13.2.2
Google Wifi is v 12371.52.22

**Comment by SpikeNbg** [comment]
Just wanted to say, i have the exact same problems with my homebridge devices, 
but i don't have a Google Wifi.. (i'm using a Fritzbox Mesh network)

I've just updated all my devices to iOS 13.2.. (or 13.3beta) and the problems started
(homebridge is Version 0.4.50)

**Comment by Nousemusic** [comment]
> Just wanted to say, i have the exact same problems with my homebridge devices,
> but i don't have a Google Wifi.. (i'm using a Fritzbox Mesh network)
> 
> I've just updated all my devices to iOS 13.2.. (or 13.3beta) and the problems started
> (homebridge is Version 0.4.50)

I have the same behavior: I use a Fritz Mesh network and have exactly same problems with my homebridge devices - They react with a delay and do not update themselves automatically.

**Comment by netRunner0** [comment]
See video:
https://youtu.be/wcrcgNuLUOc

**Comment by MAscooby** [comment]
I don’t know if this will help with figuring out what’s happening, but I’m using an eero mesh with Homebridge running on a Pi, and no issues here.

**Comment by rtgoodwin** [comment]
I am running Plume and see the issue. Eve and Home both show devices
unresponsive, but they can be controlled when tapped (and via Siri).

**Comment by eford321** [comment]
With google Wifi, many mDNS devices fail across the mesh, not just HomeKit.  My Wemo devices, tasmota switches and DIY ESP32/ESP8266 devices with mDNS lost discovery with Google Wifi firmware v12371.52.22.   There are many other devices reported on reddit.

Interesting that your devices are controllable via tap or siri on other Wifi brands. This is not the case for me.

**Comment by hdcola** [comment]
> With google Wifi, many mDNS devices fail across the mesh, not just HomeKit. My Wemo devices, tasmota switches and DIY ESP32/ESP8266 devices with mDNS lost discovery with Google Wifi firmware v12371.52.22. There are many other devices reported on reddit.
> 
> Interesting that your devices are controllable via tap or siri on other Wifi brands. This is not the case for me.

I just encountered the same problem. The solution I solved was to re-initialize all the nodes by restoring the factory settings of google wifi.  You can try it, I think this method also works for you.  It feels that when the new version is upgraded, the configuration file is upgraded incorrectly, and the normal terminal is placed in the udp multicast isolation.

**Comment by pisaacson** [comment]
I am also not seeing homebridge sensors in 13.2. I have a unifi based network setup. I removed homebridge config gui x, as  I wasn't using it anyway, with no change in non-responsive sensors. My homebridge on a raspi is operating normally with no errors observed.

├── homebridge@0.4.50
├── homebridge-ds18b20@1.0.3
└── homebridge-ecobee3-sensors@0.1.5

However, locally my iphone 5 with ios 10 still can get updated readings in Home and Eve apps, but siri doesn't "see" them. My ipad pro with ios 13.2 lists them as unrepsonsive in both those apps and siri doesn't "see" them.

Remotely, going through my apple tv with tvos 13, both my iphone and ipad see them as unresponsive.

**Comment by mafyata** [comment]
Router?

**Comment by vlar** [comment]
Here it started on its own to work again. As eford mentioned the issue wasn't just for homebridge across G Wifi but also Xiaomi Gateway and its devices, pushing voice to G Wifi, Wemos.. 
It started to work 48 hours ago properly on iOS 13.2 and G Wifi without having to do anything. I did only plug the home server to the same switch than the ATV 4k and disabled the iPad as home hub. 
From there, my homebridge didn't give any error message about not seeing the gateway but it wasn't working. 

The day after, everything started to work. 

To me there are no causality between what I have done and the fix, I do think there was a silent G WIFI  "we **ed up" upgrade as nothing in version log.

**Comment by pisaacson** [comment]
I have a ubiquity usg, a unifi switch, and a nanohd access point.

**Comment by tekuonline** [comment]
Not sure why, everything started working for me as well. I now have all four node mesh online and working.

**Comment by thetatae** [comment]
my homebridge with Mesh G-WiFi start working as well. I noticed G-WiFi was fully restarted on its own couple days ago. And boom... everything is back to normal. Damn Google.

**Comment by ericcirone** [comment]
Saw people were having success so I tried mine again. Yup it now all works. Something got fixed.

**Comment by CanonCan** [comment]
I had same issue once my goggle account on my nest had logged me out of the iOS app (using homebridge as docker in unRAID)

I followed the directions getting a new oauth key, cookie etc but couldn't get homekit to see the bridge (iPad Air 2 and iPhone X both running iOS/iPadOS 13.3 beta  )

i messed around removing configs from the config.json still not working.
I removed meshing from my 4 Ubiquiti Access points still not working

I when in the shell and ran npm install -g on all the plugins and homebridge updated from 4.46 to 4.50
here is what I had

npm list -g --depth=0
/usr/local/lib
+-- homebridge@0.4.46
+-- homebridge-info@1.2.0
+-- homebridge-nest@3.5.1
+-- homebridge-pilight@2.0.0
+-- homebridge-ring@5.9.1
`-- homebridge-roku@2.1.0

i can now get it added to homekit except my ring doorbell wont show even though the logs for homebridge register the plugin

npm list -g --depth=0
/usr/local/lib
+-- homebridge@0.4.50
+-- homebridge-info@1.2.0
+-- homebridge-nest@3.5.1
+-- homebridge-pilight@2.0.0
+-- homebridge-ring@5.9.1
`-- homebridge-roku@2.1.0

**Comment by vlar** [comment]
Btw FYI, in the future it may be convenient to know about these little browser Google wifi tweaks: 

http://192.168.1.1/api/v1/status

192.168.1.1 being the mother G WIFI IP. 

It returns this which includes build number and uptime (could be compared)

{
   "setupState": "GWIFI_OOBE_COMPLETE",
   "software": {
      "blockingUpdate": 1,
      "softwareVersion": "12371.52.22",
      "updateChannel": "stable-channel",
      "updateNewVersion": "0.0.0.0",
      "updateProgress": 0.0,
      "updateRequired": false,
      "updateStatus": "idle"
   },
   "system": {
      "countryCode": "fr",
      "uptime": 1353058
   },

Credit goes here: 

https://gist.github.com/Zenexer/e1c03b87fee6236c71e4fefcb1ff73a9

**Comment by eford321** [comment]
Still broken for me. Was excited to see others having success. Powered up mesh nodes and moved appleTV back to Ethernet connected remote puck on Ethernet. All Homebridge connected devices show “no response” in HomeKit. Work fine from Homebridge UI. 
Moving back to single node works. 
Output of VLar’s tip:

{
   "setupState": "GWIFI_OOBE_COMPLETE",
   "software": {
      "blockingUpdate": 1,
      "softwareVersion": "12371.52.22",
      "updateChannel": "stable-channel",
      "updateNewVersion": "0.0.0.0",
      "updateProgress": 0.0,
      "updateRequired": false,
      "updateStatus": "idle"
   },
   "system": {
      "countryCode": "us",
      "hardwareId": "GALE C2I-A2A-A3C-A4I-E87",
      "modelId": "ACjYe",
      "uptime": 137408
   },
   "vorlonInfo": {
      "migrationMode": "vorlon_all"
   },
   "wan": {
      "captivePortal": false,
      "ethernetLink": true,
      "gatewayIpAddress": "edited out",
      "invalidCredentials": false,
      "ipAddress": true,
      "ipMethod": "dhcp",
      "ipPrefixLength": 19,
      "leaseDurationSeconds": 86400,
      "localIpAddress": "edited out",
      "nameServers": [ "209.18.47.62", "209.18.47.63" ],
      "online": true,
      "pppoeDetected": false
   }
}

**Comment by aliceforware** [comment]
> > I had the same problems: Homebridge was no longer found in the Home app starting with iOS 13.2 and could therefore not be added again.
> > My solution: I changed the username and the PIN in config.json, then Homebridge was found again and could be added to the Home app.
> 
> I wonder that's not the case for me as I've done the RESET of the Homebridge which changed the PIN and the username in one shot. Still, Homebridge disappeared and couldn't be found by Home app

I fixed it in two ways：
1. Changed the username in config.json, restart. Homebridge app again, add a new home in HomeKit,
2. Delete the homebridge Accessory，add it again.

Both ways need to config your device and all automations again, it seems not the best way to fix this issue, but it works  fine now.

**Comment by ra1nb0w** [comment]
@aliceforware works also for me. thank you.

**Comment by rtgoodwin** [comment]
Just to expand on @aliceforware answer, because I had to do a little bit more:

1. Delete Homebridge from Home. (Find an accessory in Home, go to Settings->Bridge, remove the bridge)
1. Shut down Homebridge (maybe this step first, not sure it matters)
1. Add a new Home in Home app (from iOS, I didn't see option on macOS)
1. Reset Homebridge as noted in https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting 
1. For good measure I manually changed the PIN and username, by changing one digit each, in config.json
1. Start Homebridge
1. In the new Home in Home app, added Homebridge, and identified all accessories. 

Everything worked and I then deleted my old Home in Home app (otherwise if you have location switching on it will keep toggling back to your original Home). You'll also need to update the Home settings on your AppleTV's and re-add any HomePods etc. 

Thanks!

**Comment by zahard** [comment]
I had similiar issue and what i have discovered, that for me it start working when i switch to 5Ghz WiFi network (ac). 
Also after I changed my 2.4Ghz network setting to 'bg' only it magically become working

**Comment by mattiasstahre** [comment]
> I had similiar issue and what i have discovered, that for me it start working when i switch to 5Ghz WiFi network (ac).
> Also after I changed my 2.4Ghz network setting to 'bg' only it magically become working

Same for me! Changed to 2.4Ghz network and it worked.

**Comment by martinhebestreit** [comment]
I think I found the problem. I have two Raspy set up with two different Homebridges connected via Ethernet cable two a Synology 1900ac Router. One HomeBridge with Ui-x and one with deactivated UI-X.

 iPad on iOS 13.2.3 an iPhone 7 on iOS 13.3 (since yesterday) and AppleTV also updated yesterday. Couldn’t re-add either HomeBridge. When I stood on my Balcony, my iPhone network switched to 2.4Ghz (longer Range) instead of the simultaneous 5Ghz - and voila: both Homebridges and a TV Plattform showed up in the home app.

So it seems to me the problem is in the 5Ghz vs. 2.4 ghz Wireless lan.

**Comment by DonGiotto** [comment]
Just do what @rtgoodwin explained. I did this now for both iOS Updates 13.2 and the latest 13.3.

In my setup, the homebridge runs on a little virtual machine on my synology NAS, which is connected though LAN. All my iPhones and iPads are in my 5GHz WLAN.

Looks like Apple screwed up a lot of their stuff in iOS 13, and this just sucks.

**Comment by dilmash** [comment]
Havin the same? problem here with a rather small configuration. I tried all tips that where mentioned above but none of them worked longer than to next configuration change.

Obervations:
 * After deleting the configuration on my phone (13.3) and re-init it, all devices came back to live
 * Changing the configuration and/or restarting Homebridge, got "No Answer" on iPhone, Mac and iPad
 * Controller for Homekit (app) does stil and always see my devices
 * Homebrigde as well shows all devices

No permant solution yet
