### ISSUE TITLE
Characteristic.CurrentTemperature rounding error

### ISSUE THREAD

**Issue by dgow** [homebridge/homebridge#2354]
When I create a TemperatureSensor with a value static value of 19.2:
`
let service = new Service.TemperatureSensor("Temp", '0000008A-0000-1000-8000-0026BB765291');

cx = service.getCharacteristic(Characteristic.CurrentTemperature)
		cx.on('get', function(callback, context){
					callback(false, 19.2);
		}.bind(this)); 

cx.setProps({
		format: Characteristic.Formats.FLOAT,
		minValue: 0,
		maxValue: 100,
		minStep: 0.1
});
`
I get always 19.0 on iOS. Or when I set 11.7 it turns into 11.5. Looks like it alway rounds up to the next 0.5 step.

**Comment by pbksol** [comment]
In the Home App? That’s a Limitation. Only .0 and .5 are supported. All other values are rounded. But it’s only a limitation of the app, not HomeKit. If you use another app like Home+ or Eve or (almost) every other HomeKit app, you’ll see the real decimals
