### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by pierrejochem** [homebridge/homebridge#2359]
Dear @nfarina,

I have converted the project to typescript. I just need some small modifications/optimizations and then it is done.

Here is a first preview:

https://github.com/pierrejochem/homebridge

How do you think about it?

I would make a pull request when I'm done, but you can believe that merging in that case is a bit more tricky.

But the big benefit is to have a single js file after building due to webpack.

If you have a look I also added nodewatch into the project what helps a lot during the development process. I really like the automatic restart of the code after a change.

I really like the project and want to contribute in my free time.

Cheers,
Pierre

**Comment by nfarina** [comment]
Wow, well I am definitely a fan of TypeScript! As long as none of the functionality (i.e. compiled JS) has changed then I don't see the downside of merging in a TS migration.

**Comment by pierrejochem** [comment]
I have renamed all files from js to ts and added the necessary stuff for TS to get it compiled. It will generate a single file. This is already done.

The definition of the types in all classes needs a bit further work, because type "any" is not perfect at all. I need only a bit time to test the plugin loading stuff. That is my current state.

I propose to add jest and do some basic tests to make the deployment chain relieable for the future.

For the plugin development I propose to create an interface for the implementation of the neccessary methods and properties and provide this as npm package so it can be easily added via package.json. The example plugin should be added as seperate repository with some descriptions to make it easier for new developers who want to create them.

What do you think Nick?

**Comment by nfarina** [comment]
Would you mind making a PR? I'm looking at #2366 and it might be good to do both of these at once.

And I like your ideas about plugins! Publishing an abstract class to inherit from would make getting intellisense in TypeScript basically automatic when subclassing. Right now getting the right types imported is pretty awkward for a plugin developer.

**Comment by Apollon77** [comment]
Why it needs to compile to one file? Or did I understand it wrong? Why not stay with compiling to one js per ts and do stay roughly on structure side?

I think plugins partly do magic stuff and access several files directly. This all might break. I do no know if this is wanted.

**Comment by pierrejochem** [comment]
@nfarina I could make the PR but then we need to take care about possible open points, if this is okay for you?

**Comment by pierrejochem** [comment]
@Apollon77 This bundle is only for production and this is a common way with TypeScript. By the way, have you ever seen the compiled Js from Ts?

**Comment by lucavb** [comment]
I saw in the PR that there were still quite a few "any"s. I guess we are interested in removing them since otherwise the transition to TS doesn't really make much sense. Do we want to merge the PR first and then remove them or do this all in one PR @nfarina , @pierrejochem  ?

**Comment by pierrejochem** [comment]
@lucavb when you comment it, then I will remove what is possible.

@nfarina what do you think about merging it before? I know then there would be some things still to do but with some teamwork we could finalize it.

**Comment by lucavb** [comment]
I went ahead and did some typing today. I rebased the branch from you, @pierrejochem, and then added some types. This is currently still a work in progress and TypeScript is currently (rightfully) whining about things like trying to access private attributes. I've labeled them with `// TODO`

But there is one thing that I am especially unclear about and that is accessories. There are accessories and there is the PlatformAccessories and at some point they appear to get mixed. Can you shed some light on this? 

You can find the current status here:
https://github.com/nfarina/homebridge/compare/master...lucavb:ts_rewrite?expand=1

**Comment by Supereg** [comment]
Closing this issue as of #2476
