### ISSUE TITLE
Request: Homematic IP Cloud Access Point Plugin for Homebridge

### ISSUE THREAD

**Issue by steckenpferd** [homebridge/homebridge#2363]
REST-API Python:  https://github.com/coreGreenberet/homematicip-rest-api
C#:                         https://github.com/larsbeck/HomematicIp

Create a Plugin for the Homematic IP Cloud s . solution HomematicIP REST API (Access Point Based)

Other HmIP Plugins available for ioBroker and Home Assistant.

**Comment by steckenpferd** [comment]
Keep it up

**Comment by Supereg** [comment]
Issue on the GitHub repo are not the right place to advertise plugin requests.
A better place would be the `plugin-bounties` channel of our discord server: https://discord.gg/a56she

You may also want to post on the Homebridge or HomeKit subreddit to reach more people.
See the [community section](https://github.com/homebridge/homebridge#community) of the README.
