### ISSUE TITLE
HomeKit Accessory Development Kit (ADK)

### ISSUE THREAD

**Issue by Nastras** [homebridge/homebridge#2371]
FYI:
https://github.com/apple/HomeKitADK

**Comment by smith288** [comment]
This is going to be a big deal for Homebridge.

**Comment by osianSmith** [comment]
Hell has frozen over!  Looking into it, Apple now approved the use of this framework for non-commercial products. Not entirely sure how this will help HomeKit outside of us, the average Joe is not going to use HomeBridge. Maybe it allows easier prototyping? But again it clearly states that any commercial prototypes require MFI? Maybe is this to help startups?

However, it is a really interesting development for HomeBridge nevertheless

**Comment by arihantdaga** [comment]
Hello. A bit late on this, but we were planning to have a commercial product which will be sold with homebridge and a plaugin preloaded. Will that mean that we have to obtain the mfi liceses ? Or we can sell it without mfi licence ?
