### ISSUE TITLE
Plugin Request: AMAZON SMART PLUG

### ISSUE THREAD

**Issue by gleeglee217** [homebridge/homebridge#2376]
Hello everyone, I am new to github and I am sorry if this is not the right place to post a “Plugin Request” but I can not find the right location to post. 

I would like to request Amazon Smart Plug to be included or created for Homebridge so please let me know how I can help as well. Thanks.

**Comment by gadget-monk** [comment]
I added the Alexa smart plugs to Smartthings by using the the device handlers at https://github.com/bjpierron/SmartThings-Alexa and adding a couple of routines in the Alexa app (to trigger the plug on and off based on changes in the contact sensor linked to the smartthings switch device. The smarthings homebridge plugin then imports the device into Homekit. Its a very round about way to getting there but it works.

**Comment by gleeglee217** [comment]
> I added the Alexa smart plugs to Smartthings by using the the device handlers at https://github.com/bjpierron/SmartThings-Alexa and adding a couple of routines in the Alexa app (to trigger the plug on and off based on changes in the contact sensor linked to the smartthings switch device. The smarthings homebridge plugin then imports the device into Homekit. Its a very round about way to getting there but it works.

Thanks for the efforts so if I simply wanted to turn on/off the Amazon smart plug with HomeKit, I need to purchase Amazon contact sensors then link it to smartthings switch device which also needs to be purchased?

Then the smartthings Homebridge plugin imports to Homekit but which one:

https://www.npmjs.com/search?q=keywords%3Ahomebridge-plugin%20Smartthings%20Homebridge

Maybe I should have just fotten Tp-link or Wemo plugs instead 😂. Thanks for the effort though. 👍

**Comment by gadget-monk** [comment]
You need to purchase contact sensors. The Smartthings device handlers create a virtual sensor to Alexa. I use the tonesto7's Smartthings-v2 plugin for Homekit. Like i said, its not straightforward, but it works. The alexa plugs don't have a documented API so I don't think creating a native plugin would be easy.
