### ISSUE TITLE
Connection Issue from non local network

### ISSUE THREAD

**Issue by jiribohm** [homebridge/homebridge#2378]
### Expected Behavior
Connect to Homebridge from non local network.

### Current Behavior
When I try connect from outside network (4G) All accessories from Homebridge are not connected. All original accessories are connected and fully working.

### Versions

- **Homebridge**: 0.4.50
- **Node**:       v12.14.0, npm version: 6.13.4
- **OS**:         Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-1052-raspi2 aarch64), ios 13.3.1, AppleTV 4th Generation 4K: 13.3.1

### Configuration
firewall: off
mosquitto:
mosquitto version 1.4.15 (build date Tue, 18 Jun 2019 11:42:22 -0300)
mosquitto is an MQTT v3.1.1/v3.1 broker.

plugins: 
homebridge-mqttthings

json:
{
  "mdns": { "interface": "192.168.10.207"},
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },

  "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "ports": {
    "start": 52100,
    "end": 52150,
    "comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
  },

Scenario 1: 
When I am on local network everything work like a charm. No difference between original accessories and HomeBridge accessories. Everything run fast.

Scenario 2: 
When I want to connect from outside network (4G, Wifi) Homebridge accessories don't answer -> not connected, but original accessories work well, without problems. So, I suppose, router is configured correct. As home HUB I use Apple TV 4th gen., 4K. I tried restart, log out form iCloud, login back, etc. After restart everything works as expected (I switch off the Wifi on my iPhone and switch on 4G). But after few minutes, are all homebridge accessories not responsive again.

I think, the problem is in the communication between Apple TV and Homebridge. I tried remove everything from Home app and add it again, but the problem remains. Do you have some Idea, how to improve the connectivity? Thanks you very much!

**Comment by masgar** [comment]
Same here

**Comment by mrMiimo** [comment]
same problem here..
 https://github.com/arachnetech/homebridge-mqttthing/issues/184#

**Comment by Odirf** [comment]
Same here

**Comment by jonasophie** [comment]
same issue, I think I posted it on wrong place ...

https://github.com/homebridge/homebridge/issues/2040#issuecomment-603867975
