### ISSUE TITLE
very new to this. please help

### ISSUE THREAD

**Issue by omartos** [homebridge/homebridge#2382]
Hello, im trying to install a nest plug in on my homebridge (raspberry) but its just not working. Can someone just glance over my config file and see if anything looks wrong?Thanks a bunch

{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "restart": "sudo -n systemctl restart homebridge",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
        {
            "platform": "Nest",
            "email": "myemail",
            "password": "mypassword"
        }
    ]
}

### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by iondarie** [comment]
If you updated your Nest account to a Google account then you need the config to be different something like: 
`{'
	"platform": "Nest",
	"googleAuth": {
		"issueToken": "https://accounts.google.com/o/oauth2/iframerpc?action=issueToken...",
		"cookies": "OCAK=TOMPYI3cCPAt...",
		"apiKey": "AIzaS..."
	}
}`

read the info here: https://github.com/chrisjshull/homebridge-nest#readme
