### ISSUE TITLE
Homebridge does not start due to missing Zwave plugin?

### ISSUE THREAD

**Issue by TjebPie** [homebridge/homebridge#2383]
### Pre Steps
Homebridge will not start  using RPI 3 because of missing Zwave plugin. With ssh running Homebridge command results in following - see output below + JSON used and versions running.

### Versions
- **Homebridge**: `homebridge 0.4.50  version`
- **Node**:       `node 8.17.0 version`
- **OS**:         Raspberry Pi3 

### Configuration
```{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
      
    "platforms": [
        {
            "platform" : "ZwavePlatform",
            "name" : "ZwavePlatform",
            "zwave" : {
                "devicepath": "/dev/ttyACM0"
            }
        }
]
}
json

```

### Homebridge Log / Command Output
-->
```
[2020-1-9 22:45:10] Loaded config.json with 0 accessories and 1 platforms.
[2020-1-9 22:45:10] ---
[2020-1-9 22:45:10] No plugins found. See the README for information on installing plugins.
[2020-1-9 22:45:10] Loading 1 platforms...
[2020-1-9 22:45:10] Error: The requested platform 'ZwavePlatform' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
[2020-1-9 22:45:10] Got SIGTERM, shutting down Homebridge...


```
Who can help me?

**Comment by Apollon77** [comment]
Do you have installed the zwave homebridge plugin also via npm?? Check thereafter if the plugin you want to use

**Comment by TjebPie** [comment]
Yes - I had installed it via npm. However, I have tried to upgrade to newest version of npm and homebridge - not sure whether this has worked. Think this is part of the things causing the issue homebridge not running properly.

Pieter Tjebbes
0615033043

**Comment by TjebPie** [comment]
This is what I get when I run the npm install zwave homebridge plugin: 

> openzwave-shared@1.5.10 preinstall /home/pi/.nvm/versions/node/v8.17.0/lib/node_modules/homebridge-platform-zwave/node_modules/openzwave-shared
> node lib/install-ozw.js


> openzwave-shared@1.5.10 install /home/pi/.nvm/versions/node/v8.17.0/lib/node_modules/homebridge-platform-zwave/node_modules/openzwave-shared
> node-gyp rebuild

grep: /usr/*/include/value_classes: Bestand of map bestaat niet
gyp: Call to 'grep -r GetTypeNameFromEnum /usr/*/include/value_classes | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/pi/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/home/pi/.nvm/versions/node/v8.17.0/bin/node" "/home/pi/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.nvm/versions/node/v8.17.0/lib/node_modules/homebridge-platform-zwave/node_modules/openzwave-shared
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.5.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the openzwave-shared@1.5.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-01-12T10_49_59_299Z-debug.log

**Comment by andrewgho** [comment]
> This is what I get when I run the npm install zwave homebridge plugin:
> 
> > openzwave-shared@1.5.10 preinstall /home/pi/.nvm/versions/node/v8.17.0/lib/node_modules/homebridge-platform-zwave/node_modules/openzwave-shared
> > node lib/install-ozw.js
> 
> > openzwave-shared@1.5.10 install /home/pi/.nvm/versions/node/v8.17.0/lib/node_modules/homebridge-platform-zwave/node_modules/openzwave-shared
> > node-gyp rebuild
> 
> grep: /usr/_/include/value_classes: Bestand of map bestaat niet gyp: Call to 'grep -r GetTypeNameFromEnum /usr/_/include/value_classes | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack at ChildProcess.onCpExit (/home/pi/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
> gyp ERR! stack at emitTwo (events.js:126:13)
> gyp ERR! stack at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
> gyp ERR! System Linux 4.19.75-v7+
> gyp ERR! command "/home/pi/.nvm/versions/node/v8.17.0/bin/node" "/home/pi/.nvm/versions/node/v8.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/pi/.nvm/versions/node/v8.17.0/lib/node_modules/homebridge-platform-zwave/node_modules/openzwave-shared
> gyp ERR! node -v v8.17.0
> gyp ERR! node-gyp -v v5.0.5
> gyp ERR! not ok
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! openzwave-shared@1.5.10 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the openzwave-shared@1.5.10 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/pi/.npm/_logs/2020-01-12T10_49_59_299Z-debug.log

I am guessing you installed the OpenZWave libraries with something like `apt install openzwave` or `apt install libopenzwave1.5` and are getting this error building a dependency that requires the header files. The OpenZWave header files that provide `/usr/include/openzwave/value_classes` are in package `libopenzwave1.5-dev` which can be installed via command: `sudo apt install libopenzwave1.5-dev`.
