### ISSUE TITLE
PLUGIN REQUEST - Trigger Hue Scenes directly from the bridge (Fading, Color Loop etc)

### ISSUE THREAD

**Issue by realdannys** [homebridge/homebridge#2389]
Currently the only way with Homekit to get fading Hue scenes (and all the other stuff the bridge can actually do) is to use Shortcuts on an iOS device to trigger the scene as part of something else. The problem with that of course if you can't use Homekit sensors to trigger the scene and you're' stuck using an iOS device.

Pushcut just created a server which you can run to get around this but it requires an iOS device with it running all the time in the foreground - not ideal and struck me as a bit daft when we have Homebridge running 24/7 - I suppose we could send Pushcut webhooks but again requires an iOS device.

Currently you can make scenes which blink, fade, change colour etc and put them natively on the Hue bridge. You obviously can't share these in Homekit. As they're on the bridge you can trigger them with the native API (the way all 3rd party Hue apps work) - we could use something like Hue Lights to easily create the complex scenes we want and then a Homebridge plugin which adds the scenes as switches and triggers them on the bridge when you turn the device on. 

I wouldn't know where to start so hopefully a talented programmer can step in...

**Comment by ebaauw** [comment]
[homebridge-hue](https://github.com/ebaauw/homebridge-hue) exposes deCONZ scenes to HomeKit, but not yet Hue bridge scenes.  This is due to differences in the scenes API.

I am more than willing to support Hue bridge scenes as well, but I'm struggling a bit how to specify what scenes you want to expose under what groups.  See https://github.com/ebaauw/homebridge-hue/issues/475.  Please add your ideas there.

As a workaround, you could, for each scene you want to expose to HomeKit, create a CLIPGenericFlag sensor on the Hue bridge, and a rule to activate a scene when the flag is set (and one to reset the flag after a second or so).  Homebridge-hue already exposes these CLIP sensors as switches to HomeKit.  Note that there's no way to ask the bridge whether a scene is active.

**Comment by realdannys** [comment]
Hi Eric,

I did look at your fantastic plugin actually and wondered if it might do what I needed.

I think what you described with effectively fake momentary push switches would be ideal. I don’t mind knowing if the scene is active it’s more having the ability to trigger fading ones.

For instance I have a slow bedtime routine that triggers a scene which fades the lights over 20 mins. I made the scene in the Hue Lights app, shared it to the bridge so it appears in the native Hue app then triggered it via a Siri shortcut.

It just struck me if it natively appears on the bridge it should be possible to trigger with the API.

There is a plugin which lets you create JSON based Hue scenes and supports all the API tricks not available to Homekit but id be lost trying to program fades etc by hand when I can use a third party app to do it.

**Comment by jqnatividad** [comment]
You may want to check out this Siri Shortcuts routine

https://routinehub.co/shortcut/4310

It allows you to get the required info to invoke your Hue Labs formulas from outside the Hue app. It allows you to not only invoke it from Shortcuts, it gives you the option to get the curl commands to turn on/off the formula.

In combination with the home ridge-switch2 plugin, I then associate the corresponding curl command with the corresponding on/off switch state.

**Comment by ebaauw** [comment]
See https://github.com/ebaauw/homebridge-hue/issues/605, latest homebridge-hue beta exposes `GroupScene` scenes under the group accessory, and `LightScene` and v1 scenes under the accessory for group 0.

**Comment by realdannys** [comment]
@jqnatividad - thanks for this, using the curl commands will be useful for other things.

In the end I used the Hue Scenes Homebridge plugin and programmed my own scenes in Json. It gives me switches for each scene I want to trigger (having extra switches in room is of no concern to me, i've never wanted to turn everything in a room on,  but even if I did, i'd just create a fake automations room and put the virtual switches in there)

I went one further and used API direct with POST commands in Webcore to create a movie on/off mode that records the scene you current have active before the movie starts, call yours movie scene (which now fades in the way I want it to not the default speed) and then when you pause or end the movie returns to whatever the previous scene was before. Works very well.

Will be interesting to use the curl command to active things like the candle effect though on the Hue bridge - I can basically do anything you can think of in Homekit now.
