### ISSUE TITLE
Multiple Apple devices and homebridge works only on device with version 13.xx

### ISSUE THREAD

**Issue by remko2000** [homebridge/homebridge#2400]
I using homebridge with the apple homeapp.
I have struggling the hole weekend with homebridge (I get some errors in homebridge gui X log) and I trought it running OK now till.....I checked my Ipads (both ipad airs with ios versio 12.4.4). I see homebridge doesn't respond on these devices. My and my girlfriend has iphones, both with ios version 13.3. Homekit and homebridge running well on these devices. The problem is I want to use an Ipad like a hub and that is not possible now. We all use the same cloud.
I tried to restart the ipads ands also disconnect from my cloud and after that reconnect. Nothing helps. I googled but nothing what gives my a lead to an solution. Is there someone who can help me with this?

**Comment by zladukas** [comment]
I had same issue with my ipads, but them are on 13.3.
I solved it with ipad restore (also Apple TV reset & restore)

BTW Apple support made some my iCloud check & fix before.

Good luck!

**Comment by remko2000** [comment]
I reset (no restore)my Ipad but unfortunately no improvement. What can I else try? What do you mean by Icloud check and fix? Works an appleTV better as a homekithub?

**Comment by zladukas** [comment]
> I reset (no restore)my Ipad but unfortunately no improvement.

Only restore solved mu problem

 What can I else try? What do you mean by Icloud check and fix? 
I've called to support, I was told they will run some checks

Works an appleTV better as a homekithub?
Way better

**Comment by PatchworkBoy** [comment]
If you add HomeKit accessories of a type introduced in iOS13 (such as the TV device type), then your homehub device **must** be either an iPad on the same or better version of iOS that introduced that accessory type, or an AppleTV4 / HomePod on latest OS.

You have to delete your home completely, and recreate WITHOUT including any iOS13 generation HomeKit accessories... then you can use an iPad on iOS10 thru iOS12 as a HomeHub without a problem.

**Comment by one909** [comment]
ฉันขอ ขอบคุณทุกคนจริงๆ   
 🙏  ฉันจะไม่ลืม  
 ผมได้แต่ทำผิดหรือถูก  ก็ไม่รู้เรื่องผมขอโทษ
