### ISSUE TITLE
Feature Request - Beta With HAP-NodeJS?

### ISSUE THREAD

**Issue by donavanbecker** [homebridge/homebridge#2404]
### Expected Behavior

Would be helpful for plugin developers to have a beta for before hap-nodejs 0.5.x is implemented. [PR](https://github.com/nfarina/homebridge/pull/2391#issuecomment-579207733)

### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **OS**:         
HomeBridge: 0.4.50
Node: 12.8.1
Ubuntu: 19.10

### Configuration

```json
Feature Request
```

### Homebridge Log / Command Output

```
Feature Request
```

**Comment by donavanbecker** [comment]
@nfarina or @KhaosT what are your thoughts?

**Comment by KhaosT** [comment]
We should definitely push a beta when it's ready ^^

**Comment by donavanbecker** [comment]
@KhaosT if one is pushed now would it be easier to fix issues?

**Comment by KhaosT** [comment]
@donavanbecker there are known issues with some of the stuff (https://github.com/nfarina/homebridge/pull/2391#issuecomment-576402917)... before pushing a beta I think we should address that first. Unfortunately none of us work full-time on the project so it kinda feels lack of progress I guess 😅
