### ISSUE TITLE
orchestrator support?

### ISSUE THREAD

**Issue by bonesoul** [homebridge/homebridge#2416]
first of all thank @nfarina for this great project & (you too @KhaosT  for hap-node!)

 is it possible to access accessory instances within a plugin context so I can orchestrate it? (let them interact with each other)

let me be more brief and create a scenario;

I do have both philips hue bulbs and plex installed on my samsung tizen tv installed;
- https://github.com/ebaauw/homebridge-hue
- https://github.com/mpbzh/homebridge-hue

now with homebridge I can get them up and running with homekit and command them over siri as expected.

what I further try to achieve is let them interact with each other and once plex on my tv starts playing a movie, command my hue bulbs to automatically close, and once the movie stops - re-open them.

so I've explored the homebridge & hap-nodejs codebase for last few days and couldn't find a way to manage this (am i missing something?)

I coded a quick prototype ( https://github.com/bonesoul/homer/tree/develop/contrib/nodejs-prototype ) consuming hap-nodejs which also mimics homebridge api - which quickly I was able to consume the same homebridge-hue and homebridge-hue plugins.

eventually i was able to achieve the scenario with this piece of code; ( https://github.com/bonesoul/homer/blob/develop/contrib/nodejs-prototype/src/homekit/server.js#L80 )

```
let orchestrate = async () => {
    // get hue bridge.
    let huePlatform = this._platformRepository.active['Hue.Hue'];

    // wait for hue bridge to expose the bulbs.
    let lights = await getLights(huePlatform);

    // start listening for plex events.
    this._accessoryRepository.active['Plex.Plex'].getService(Service.OccupancySensor).getCharacteristic(Characteristic.OccupancyDetected).on('change', (data) => {
        for(const entry of lights) { // loop through all lights.
          entry.lightService.getCharacteristic(Characteristic.On).setValue(!data.newValue); // if plex started streaming close them, otherwise re-open them.
        }
    });
  }
  
let getLights = async (hue) => {
    return new Promise((resolve, reject) => {
      try {
        let lights = [];
        hue.accessories((accessories) => {
          for(const entry of accessories) {
            if (entry.constructor.name === 'HueAccessory' && entry.lightService) {
              lights.push(entry);
            }
          }
          return resolve(lights);
        });
      } catch (err) {
        return reject(err);
      }
    });
  }  
  
await orchestrate(); // let the magic happen!
```

I basically call this an orchestrator. One more idea is also being able to expose it as an homekit accessory (giving it a name 'DarkCinema') so that we can also command siri to 'enable dark cinema mode' which will make the integration only work when asked so (we may not really want to watch movies in dark all the time :D)

the results is; [youtube](https://www.youtube.com/watch?v=ig6Ax14W_Dg)

![giphy](https://user-images.githubusercontent.com/73215/74374436-785b6700-4def-11ea-912e-0aadb159e6f4.gif)

so if I'm not already missing the existing api horribly, is there any plans for an orchestrator api? if not i guess i'll be crafting this.

i know that simple interactions can be achieved using homekit but what I'm thinking of is possibility of complex interactions that run on home pc rather then homekit interface (automations)

**Comment by NorthernMan54** [comment]
This is available today via Node-Red and the homebridge-automation node.  This node makes all homebridge devices available via node red so you can create advanced automations and other things.  And with its companion node HomeKit-bridged you can also create your own accessories within node-red.  All without any coding required.

Might be worth a look
