### ISSUE TITLE
RGBWZ Color Switch can't controll colors

### ISSUE THREAD

**Issue by rolandbreedveld** [homebridge/homebridge#2421]
I have MQTT Sonoff devices, which are recognized and configured in Domoticz as "RGBWZ Color Switch"
In Domoticz everything works fine, can control all colors, but in the Apple Home app, it is recognized as as a dimmable light, so I can't control the colors.
same issue for the RGBWWZ devices, only RGBW devices have color controls on my iPhone
for  WW RGBWW and RGBWWZ devices there should be a 2nd slider for the warm-color-Tone.

**Comment by anttitai** [comment]
I have a hue light RGBWWZ and it also shows only brightness control on iPhone.
