### ISSUE TITLE
Homebridge no longer available in Home app

### ISSUE THREAD

**Issue by mtjoernelund** [homebridge/homebridge#2425]
I know this issue have been up several times, but none of previous solutions seem to work for me...

I have homebridge installed and running on two Raspberry Pi B+. Both instances have been running for a long time with no issues. However after updating a couple of plugins (config-ui-x, Hue and Eveatmo) on the one Raspberry, this Homebridge instance stopped responding in the Home app. I tried deleting to re-add, but now when I try to add to Home home app it fails. Home app sees the Homebridge, but whether I scan the qr-code or type the code manually it fails to add saying that it could not connect. The other homebridge instance on my other raspberry continues to run smoothly. 

Things I have tried:
- Change username
- Change pin
- Change port
- Delete persist and accessories folder
- Reset in config ui x (am aware that that basically just does the above save for changing port)
- Added mdns record to my config file (binding both to the IP of my eth and wlan)
- Rebooted router

Nothing seems to work, despite all parameters being as far as I can tell identical to my other homebridge setup. 

The only difference I have found is the following. I tried to do netstat -a -n -p tcp | grep 51826 and on the server that works I get the following (192.168.0.76 being the IP of the RPi):
```
tcp6       0      0 :::51826                :::*                    LISTEN      367/homebridge      
tcp6       0      0 192.168.0.76:51826      192.168.0.21:57376      ESTABLISHED 367/homebridge      
tcp6       0      0 192.168.0.76:51826      192.168.0.10:49532      ESTABLISHED 367/homebridge      
tcp6       0      0 fe80::b5b6:9485:b:51826 fe80::4f7:4a3f:c4:59274 ESTABLISHED 367/homebridge      
tcp6       0      0 192.168.0.76:51826      192.168.0.99:58926      ESTABLISHED 367/homebridge

```
But on the server that does not work I get the following:
```
tcp        0      0 127.0.0.1:33254         127.0.0.1:51826         TIME_WAIT   -                   
tcp6       0      0 :::51826                :::*                    LISTEN      -

```
In general I will only get the second line, but if I do it right after trying to add I will get one or more instances of the first line. It seems to me that it listens for multicast messages on the wrong interface, but I thought that the addition of the mdns record in the config file should address that, which does not seem to be the case.

I have (I feel) searched high and low for an answer to what could be happening here. I fear that there is something obvious that I am missing. Any help or pointers would be greatly appreciated.

**Comment by n1zzo** [comment]
I am experiencing the same issue, no error messages on Homebridge, this is the result of the netstat command on my platform:
```
$ sudo netstat -a -n -p tcp | grep 51826
tcp6       0      0 :::51826                :::*                    LISTEN      7959/homebridge
```

**Comment by AppleTechy** [comment]
@n1zzo Can you provide a list of the plugins you have installed as well as your log(with any person information removed)? Also not sure if you realized the OP on github is the same person who's comment you linked to on reddit. However, I am glad you linked it as mtjoernelund  didn't post an update with this information.

**Comment by n1zzo** [comment]
To exclude any interference with plugins I've been able to reproduce the bug with a fresh docker
deployment with an empty config file.
Here's the config file:
```
{
    "bridge": {
        "name": "Gem",
        "username": "A3:C2:86:42:3B:C1",
        "port": 51818,
        "pin": "524-22-242"
    },
    "description": "Configuration file for Vignate Home.",
    "accessories": [],
    "platforms": []
}
```

Here is my log:
```
[4/20/2020, 1:31:53 PM] [HB Supervisor] Starting Homebridge with extra flags: -P /homebridge/node_modules
[4/20/2020, 1:31:53 PM] [HB Supervisor] Started Homebridge with PID: 419
[4/20/2020, 1:31:55 PM] Loaded config.json with 0 accessories and 0 platforms.
[4/20/2020, 1:31:55 PM] ---
[4/20/2020, 1:31:56 PM] Loaded plugin: homebridge-dummy
[4/20/2020, 1:31:56 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[4/20/2020, 1:31:56 PM] ---
[4/20/2020, 1:31:56 PM] Loaded plugin: homebridge-config-ui-x
[4/20/2020, 1:31:56 PM] Registering platform 'homebridge-config-ui-x.config'
[4/20/2020, 1:31:56 PM] ---
[4/20/2020, 1:31:56 PM] Loading 0 platforms...
[4/20/2020, 1:31:56 PM] Loading 0 accessories...
Setup Payload:
X-HM://0024C55CYKA5L
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 524-22-242 │     
    └────────────┘     
                       
[4/20/2020, 1:31:56 PM] Homebridge is running on port 51818.
[4/20/2020, 1:31:59 PM] [Config] Homebridge Config UI X v4.15.1 is listening on :: port 8000
<redacted>
[4/20/2020, 1:32:01 PM] [Config] Username and password have been set to default:
<redacted>
<redacted>
```
I've been running [this docker image](https://github.com/oznu/docker-homebridge) using `docker-compose`.
From the home app I can see the gateway, from the "Add accessory" screen, so I suppose mDNS is fine.
Lastly, my setup was running fine, with several accessories and so on, from one day I wasn't able to reach the accessories, so I tried to remove the gateway and now I cannot add it anymore.
Note that also the docker volumes were cleaned in this new installation, including the `persist` folder.

> Also not sure if you realized the OP on github is the same person who's comment you linked to on reddit.

Yes, I didn't say it clearly, but I realized it was the same guy, who had an update and did not report here.

If I can produce some more debugging material (network captures) or other please tell me.

p.s. thanks for helping me in this, I love this software and I'm suffering a bit without it :)

**Comment by AppleTechy** [comment]
@n1zzo What version of Homebridge are you running?

**Comment by n1zzo** [comment]
The bug manifests itself on different versions,
I've tried with the latest [docker-homebridge](https://github.com/oznu/docker-homebridge) image,
which ships Homebridge v1.0.2, but also with [an older docker image](https://hub.docker.com/layers/oznu/homebridge/2.0.0-aarch64/images/sha256-b3a2937eda6ae1fca49f7a8308f8dc66f6b75342b44582daf0679dd2ca9ace0b?context=explore)
which ships with Homebridge v.0.4.50.
So this makes me think that the problem is not in homebridge, but either in my network or in iOS.
Any tips for troubleshooting?

**Comment by n1zzo** [comment]
When I try to add the accessori in iOS Home app, no connection is made from my iPhone IP, so probably is some iOS Home bug, I'll try to delete and re-create the home.

**Comment by n1zzo** [comment]
Probably this is related to #2098

**Comment by NorthernMan54** [comment]
The latest homebridge version corrects an issue with the addresses, please update and try again.

If issue continues, please install this tool and share the output

https://www.npmjs.com/package/mdns-diagnostics

**Comment by n1zzo** [comment]
Unfortunately the issue manifests itself even in the latest Homebridge v1.0.4.
mans-diagnostics returns without printing anything. However I'm attaching a screenshot
of Bonjour discovery which should be equivalent.

<img width="592" alt="Screenshot 2020-04-30 at 22 39 38" src="https://user-images.githubusercontent.com/6890834/80757341-4d51fb00-8b34-11ea-9b97-78c2a8abe3ca.png">

The IP address listed correspond to the various interfaces of my server, of which 192.168.4.10 is the correct one.
I also tried the fix suggested in #2098 by patching bonjour-hap to inject only a single fixed IPv4 but it did not solve the problem.

**Comment by NorthernMan54** [comment]
@n1zzo That mdns-diagnostics returned nothing is part of the issue.  For HomeKit to work, mDNS device discovery needs to work and your Apple TV and iOS devices need to be able to see the mDNS messages and connect to homebridge.

I'm not a docker guru so can't really comment on the issue

**Comment by Supereg** [comment]
Could you try to reinstall 1.0.4 this will pull the latest version of bonjour-hap released couple hours ago.

**Comment by n1zzo** [comment]
Ok, I've tried with 1.0.4 built from scratch, now `mdns-diagnostics` works as expected:
```
 $ mdns-diagnostics
Unsupported device found, skipping Sonoff Switch-B38E4F
Philips hue - 06E39E, BSB002,  192.168.4.188:8080
Philips hue - 06E39E, BSB002,  fe80::eeb5:faff:fe06:e39e:8080
Legrand Gateway, Legrand Gateway,  192.168.4.158:5001
Legrand Gateway, Legrand Gateway,  fe80::204:74ff:fe25:87e6:5001
Gem B92C, Gem,  192.168.4.10:51818
Gem B92C, Gem,  192.168.252.1:51818
Gem B92C, Gem,  172.20.0.1:51818
Gem B92C, Gem,  172.21.0.1:51818
Gem B92C, Gem,  172.18.0.1:51818
Gem B92C, Gem,  172.23.0.1:51818
Gem B92C, Gem,  172.25.0.1:51818
Gem B92C, Gem,  172.19.0.1:51818
```
With the correct addresses of my gateway, however I'm still unable to add the accessory,
I will try to re-generate homebridge data.

**Comment by NorthernMan54** [comment]
@n1zzo What is this device?

Gem B92C, Gem

Can you explain with a bit of detail what this is and the network topology around it

Tks

**Comment by n1zzo** [comment]
Ok, so homebridge is executed under docker with `network_mode: host` on a machine with hostname gem.
This is my config.json homebridge file:
```
{
    "mdns": { "interface": "192.168.4.10" },
    "bridge": {
        "name": "Gem",
        "username": "A3:C2:86:42:3B:C2",
        "port": 51816,
        "pin": "524-22-245"
    },
    "description": "Configuration file for Vignate Home.",
    "accessories": [],
    "platforms": []
}
```
The 172.*.*.* interfaces are for another network, should not be advertised.
The correct interface to be advertised is 192.168.4.10.
That network is the one with all the Homekit hosts connected, including my laptop on which I'm executing `mdns-diagnostics`.
Please tell me if you need additional details.
