### ISSUE TITLE
Lack of support for DPT7 in Custom Service API

### ISSUE THREAD

**Issue by svollbehr** [homebridge/homebridge#2426]
Current version of knxaccess.js restricts the Data Types to DPT1, DPT5 and DPT9. I have got a pre-programmed KNX device that utilizes DPT7, which cannot be written. Attempts to do so cause errors when data type is passed to the this.myAPI.knxWrite(field, value, 'DPT7').

**Comment by snowdd1** [comment]
Hi, I think you are in the wrong repo.
Let's have that talk in https://github.com/snowdd1/homebridge-knx/issues
homebridge itself is hardware agnostic, so it does not know about KNX data point types!
