### ISSUE TITLE
HomeBrigde seems to ignore commands after idle time

### ISSUE THREAD

**Issue by eludlow** [homebridge/homebridge#2427]
Hi all - recently switched from HomeAssisant to HoemBridge to provide a bridge to my HomeKit instance.  I have a number of Hive device (Active Bulbs and a Hive Thermostat) and that I want to be able to control via Siri voice commands.

Installed fine and set up seems good - using Homebridge Hive Forever to control the Hive devices.

The only oddity is that, after sitting idle for a while, HomeKit isn't actually actioning a command on the first attempt.  For instance I'll ask Siri to "turn all the lights" off and he'll respond that he's done so - not no error - but the lights remain on.  Try again and it will work fine.

I can't work out what the idle time require here is, seems a bit random.  Crucially nothing is showing in the HomeBridge logs - including when debug mode is turned on.

I also have two Flic plugins running (but not configured at the moment) as in time I'd like to integrate Flic buttons, but the above still occurs when these are uninstalled so I don't think relevant.

Any idea what might be causing this, or if it's a known issue?

Many thanks in advance.

- **Homebridge**: 0.4.50
- **Node**:  12.16.1
- **OS**:   Linux arm, Release 4.19.66-v7+

Config:

```
{
    "bridge": {
        "name": "Homebridge 7425",
        "username": "REMOVED",
        "port": 51376,
        "pin": "REMOVED"
    },
    "accessories": [
        {
            "accessory": "HiveForever",
            "product": "HiveLight",
            "name": "Kitchen",
            "displayName": "Kitchen",
            "username": "REMOVED",
            "password": "REMOVED"
        },
        {
            "accessory": "HiveForever",
            "product": "HiveLight",
            "name": "Dining room",
            "displayName": "Dining room",
            "username": "REMOVED",
            "password": "REMOVED"
        },
        {
            "accessory": "HiveForever",
            "product": "HiveLight",
            "name": "Bedroom, corner",
            "displayName": "Bedroom, corner",
            "username": "REMOVED",
            "password": "REMOVED"
        },
        {
            "accessory": "HiveForever",
            "product": "HiveLight",
            "name": "Bedroom, door",
            "displayName": "Bedroom, door",
            "username": "REMOVED",
            "password": "REMOVED"
        },
        {
            "accessory": "HiveForever",
            "product": "HiveLight",
            "name": "LR main",
            "displayName": "Living room, main",
            "username": "REMOVED",
            "password": "REMOVED"
        },
        {
            "accessory": "HiveForever",
            "product": "HiveLight",
            "name": "LR corner",
            "displayName": "Living room, corner",
            "username": "REMOVED",
            "password": "REMOVED"
        },
        {
            "accessory": "HiveForever",
            "product": "HiveThermostat",
            "name": "Heating",
            "displayName": "Heating",
            "username": "REMOVED",
            "password": "REMOVED"
        },
        {
            "accessory": "HiveForever",
            "product": "HiveThermostatBoost",
            "name": "Boost",
            "displayName": "Boost",
            "username": "REMOVED",
            "password": "REMOVED"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

**Comment by eludlow** [comment]
As a follow up to this, I've narrowed it down a bit more - it's not if HomeBridge has been inactive for a while that it requires two attempts, it's when the individual accessory has been "inactive" for a while.

**Comment by normen** [comment]
Rather sounds like an issue in the plugin than homebridge.

**Comment by eludlow** [comment]
OK, thanks - will investigate the plugin more!
