### ISSUE TITLE
removing accesory

### ISSUE THREAD

**Issue by bday1978** [homebridge/homebridge#2428]
Hi,
What's the way to remove an accesory or plugin altogether without messing rest of my setup like automation rules etc. I have 70+ devices sort/hard so doing all my automations from scratch is mad.
Does removing accesories and persists folders reset everything including my custom device names and automations?

Many thanks,

**Comment by ebaauw** [comment]
Remove the plugin from the `platforms` or `accessories` section in config.json (and from the `plugins` array if you use that).  Then restart homebridge with `-R` to remove the stale cached accessories.

Do not mess with the directories.  Deleting `persist` is like factory-resetting your bridge: it will no longer be paired to HomeKit, but HomeKit still thinks it is.  Deleting `accessories` will start homebridge without exposing the cached accessories, causing HomeKit to delete them, incl. the names set in HomeKit and any links to rooms, groups, scenes, and automations.  The plugins will re-expose the accessories shortly, but HomeKit will see these as new accessories.
