### ISSUE TITLE
Retire “engines” field requirement

### ISSUE THREAD

**Issue by alexindigo** [homebridge/homebridge#2434]
@nfarina I think we need to stop checking “engines” field in the package.json, since package.json is a Node thing and homebridge is abstraction on top of that. It meant to describe what can execute your package and it’s always node, homebridge doesn’t parse/evaluate plugins code. And npm/yarn actually complain about unknown engine there.

What could be better is to have standalone “homebridge” branch in package.json, that can have versions and much more, and will be aligned with how package.json meant to be used, and how other meta projects do that.

Something like:

```
“name”: “homebridge-plugin”,
“version”: “1.0.0”,
“dependencies”: {},
“homebridge”: {
  “version”: “0.4.51”
  “other”: “things”,
  “itWants”: “to ask for”
}
```

Thank you.

**Comment by Supereg** [comment]
> And npm/yarn actually complain about unknown engine there.

Are you sure. You will need to specify `node` as an engine as well, otherwise npm will complain. `node` is basically required. But otherwise there is no conflict.
