### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by 1nutty1** [homebridge/homebridge#2435]
After updating Homebridge to 0.4.52 today I now get "[homebridge-mqttthing] Failed to check registry.npmjs.org for updates: Error: ETIMEDOUT" every minute or so after restarting Homebridge.

**Comment by Paredev** [comment]
Same is happening to me, fresh raspbian install and nothing else installed.

**Comment by macjeff** [comment]
I run home bridge in terminal on a Mac and it worked fine

**Comment by 1nutty1** [comment]
I have it running on Buster headless on a Pi Zero (which also freezes randomly)
Only have Homebridge and Mqttthing running on it.

**Comment by krmkrx** [comment]
Are there any updates on this issue? Have you solved it? Currently having the same problem.

**Comment by 1nutty1** [comment]
Nope, keeps happening from time to time.

**Comment by oznu** [comment]
The error just means your the Homebridge UI failed to make a http connection to the npm registry to check if updates were available for that plugin.

ETIMEDOUT means it took longer than 5 seconds to make the request and gave up, this is just a warning so it's not going to break anything else, but could be a sign of other issues in your network or on your device (being a Raspberry Pi Zero it could just be to overloaded at startup time it can't finish the request in 5 seconds).

**Comment by 1nutty1** [comment]
Ahhh, probably poor network... Living in South Africa has its downsides when it comes to up-time and connectivity.

**Comment by oznu** [comment]
The npm registry is down more often than it really should be too 😁

**Comment by pgScorpio** [comment]
Same problem here...

OS: Raspbian GNU/Linux Buster (10)
Node.js v12.16.1
Npm v6.14.2

[3/22/2020, 09:16:57] [Config] [homebridge] Failed to check registry.npmjs.org for updates: Error: ETIMEDOUT
[3/22/2020, 09:17:02] [Config] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: Error: ETIMEDOUT
[3/22/2020, 09:17:02] [Config] [homebridge-gsh] Failed to check registry.npmjs.org for updates: Error: ETIMEDOUT

**Comment by 1nutty1** [comment]
> Same problem here...
> 
> OS: Raspbian GNU/Linux Buster (10)
> Node.js v12.16.1
> Npm v6.14.2
> 
> [3/22/2020, 09:16:57] [Config] [homebridge] Failed to check registry.npmjs.org for updates: Error: ETIMEDOUT
> [3/22/2020, 09:17:02] [Config] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: Error: ETIMEDOUT
> [3/22/2020, 09:17:02] [Config] [homebridge-gsh] Failed to check registry.npmjs.org for updates: Error: ETIMEDOUT
> 
> P.S.: No network problems, everything else is working is working ok.

It appears to be a common NPM problem, not necessarily your network.

**Comment by redtom13** [comment]
me, too
Failed to check registry.npmjs.org for updates: timeout of 5000ms exceeded

OS | Raspbian GNU/Linux Buster (10)
v12.16.3
v6.14.5

**Comment by oznu** [comment]
The npm registry is down / having issues.

https://status.npmjs.org/

**Comment by mazafra1** [comment]
Why is this closed? Cannot be solved in any way?
