### ISSUE TITLE
Homebridge Help!

### ISSUE THREAD

**Issue by cubstitan95** [homebridge/homebridge#2441]
Hello everyone so I’m very new to this coding and scripting thing. After lots of time and trouble I got Homebridge working with my Windows 10 computer. My main reason for setting this up was to integrate my harmony hub with Siri and HomeKit. I have harmony. Setup. But my question is how can I execute Siri commands to switch channels. And by channels I mean the favorite channel list I have set on harmony. When I linked Alexa to harmony awhile back I had it set up like that. I’d like to do the same for Siri. For example, “hey Siri turn on nbc”. My cable provider is xfinity if that helps. Thanks in advance!

**Comment by AppleTechy** [comment]
I'm happy to hear that you got Homebridge all setup and working! So as far as I know Siri does not support commands for TV accessories, but if memory serves me correctly(I used to run the harmony hub plugin a long time ago), the favorites channel list that you have to config in your config.js the activities. These will then get setup as switches in Homekit so you could simply say "Hey Siri turn on NBC" and it would work. 

If I am understanding that as all to your question, this isn't really a question for this repo. I am going to go ahead and close this issue but if I missed something with your question feel free to reopen and respond to my post.  I would suggest that you post an issue on the Harmony Hub Plugin's repo or join the discord server and there is a channel named #harmony and you could talk to some people who run the plugin as well as the plugin developer on there.
