### ISSUE TITLE
Remove old Homebridge istance from Homekit

### ISSUE THREAD

**Issue by vzlgdu** [homebridge/homebridge#2461]
Hi I've installed two Homebridge istances on RPI3 and everithing work fine.
The 2th istance is used as test and sometimes I've has restarted this istance more times.
Now, in Home app on Iphone, I see the message "Homebridge2 (Default) doesn't answare"...

I've removed the 2th istance but i seems that Homekit has stored someting about this istance.

I want remove this message without reset the 1st istance of Homebridge.
Do you have suggest about what check/edit (in var/homebridge?)

Please help

Thanks

**Comment by oznu** [comment]
You need to remove it from the Home app on your iPhone.

Home app > Home > Home icon top left > Hubs and Bridge > select "Homebridge2" > Remove bridge from home.

**Comment by vzlgdu** [comment]
GREAT!!!! I was not informed about this menu!
Thanks a lot!!!!
