### ISSUE TITLE
Unable to turn off my MagicMirror

### ISSUE THREAD

**Issue by Baassievalk** [homebridge/homebridge#2469]
When turning on my MagicMirror i'm getting the following log: (the sudo: no terminal part) I had to translate it so it won't be spot on.
[2020-3-29 22:26:16] [Raspberry Pi] Mirror is off. 
[2020-3-29 22:26:17] [Raspberry Pi] Failed to turn on Mirror 
sudo: no terminal available and no  passwordask(askpass) programs gave up.

I'm using this module.

https://forum.magicmirror.builders/topic/10008/mmm-homekit-control-your-magicmirror-with-apple-homekit
If anyone knows a solution it would be appreciated!

**Comment by AppleTechy** [comment]
Hey there👋. Could you post more details such as your configuration file  and log file (with anything sensitive removed). With the limited information you posted it is kinda of hard for me to know what is going on. It could be an issue with this MMM-Homekit module you installed on your mirror it could be something wrong with your homebridge config.js to tell the mirror to turn on.

**Comment by NorthernMan54** [comment]
Lol, I answered this on the Magic Mirror forum a few weeks ago, check the last message in the forum linked to above.

**Comment by AppleTechy** [comment]
@NorthernMan54 Ok awesome. Github issue never got closed and didn't realize there was some troubleshooting going on in the comments of the post.
