### ISSUE TITLE
Plugins break homebridge or npm?

### ISSUE THREAD

**Issue by iAmRenzo** [homebridge/homebridge#2470]
I've installed Homebridge for the sixth time this week. Somehow it gets broken. Last time I installed the Viera plugin. Rebooted the Pi but Homebridge wouldn't start.
I couldn't edit the config.json file because of rights :( I also couldn't remove the plugin.

I am afraid to either reboot the Pi or install that Viera plugin again.

Uninstall:
```
pi@raspberrypi:/home $ sudo npm remove homebridge-viera
node: relocation error: node: symbol version GLIBC_2.4 not defined in file libc.so.6 with link time reference
```

Log:
```
[0;37m[3/31/2020, 14:15:02] [0m[0;36m[Config][0m Running Command: sudo -E -n npm install homebridge-viera@latest
[0;37m[3/31/2020, 14:16:30] [0m[0;36m[Config][0m Changes to config.json saved.
[0;37m[3/31/2020, 14:16:35] [0m[0;36m[Config][0m [0;33mRebooting linux server with command: "sudo -n shutdown -r now"[0m
[37m[3/31/2020, 14:16:36][0m [36m[HB Supervisor][0m Stopping services...
[37m[3/31/2020, 14:16:36][39m Got SIGTERM, shutting down Homebridge...
```

/var/log/syslog:
```
Mar 31 14:18:02 raspberrypi systemd[1]: Started Homebridge.
Mar 31 14:18:02 raspberrypi hb-service.js[691]: node: relocation error: node: symbol #006 version GLIBC_2.4 not defined in file libc.so.6 with link time reference
Mar 31 14:18:02 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=127/n/a
Mar 31 14:18:02 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mar 31 14:18:05 raspberrypi systemd[1]: homebridge.service: Service RestartSec=3s expired, scheduling restart.
Mar 31 14:18:05 raspberrypi systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 20.
Mar 31 14:18:05 raspberrypi systemd[1]: Stopped Homebridge.
Mar 31 14:18:05 raspberrypi systemd[1]: Starting Homebridge...
Mar 31 14:18:05 raspberrypi run-parts[692]: Ensuring /var/lib/homebridge is owned by homebridge
Mar 31 14:18:05 raspberrypi hb-service.js[695]: node: relocation error: node: symbol #006 version GLIBC_2.4 not defined in file libc.so.6 with link time reference
```

**Comment by oznu** [comment]
> I've installed Homebridge for the sixth time this week. Somehow it gets broken. 

Are you doing fresh installs of Raspbian each time?

**Comment by iAmRenzo** [comment]
> Are you doing fresh installs of Raspbian each time?
Yes. Raspbian Lite.
I am also running a Pi-Hole on it. But in recent times (and before the GUI tutorial) that was never a problem.

**Comment by oznu** [comment]
I've tested installing the `homebridge-viera` on Raspbian Lite and did not encounter this issue.

Is is possible your SD card is faulty / getting old? The errors you posted seem to suggest something is getting corrupted.

**Comment by iAmRenzo** [comment]
> I've tested installing the `homebridge-viera` on Raspbian Lite and did not encounter this issue.
> 
> Is it possible your SD card is faulty / getting old? The errors you posted seem to suggest something is getting corrupted.

I am certain that one plugin cannot damage my homebridge service without any logs and no one complaining about it. I was installing all plugins one after an other and a reboot made it go bad.

My SD card is a bit older yes... could that be it? Can I verify that somehow?

**Comment by netRunner0** [comment]
And when does homebridge stop crashing after some kind of plugin caused a crash?

**Comment by iAmRenzo** [comment]
I don’t know. I’ve installed a plugin, restarted the server or rebooted the pi.
