### ISSUE TITLE
No longer accessible remotely

### ISSUE THREAD

**Issue by Finch106** [homebridge/homebridge#2473]
Hello! Within the last few weeks, I've noticed that any homebridge-connected devices are unavailable if I'm away from my home network. All other HomeKit devices are available, just homebridge devices show not responding. This is resolved when I reconnect to my home network.

**Comment by donavanbecker** [comment]
Have you tired Restart your home hubs? Apple TV or HomePod.

**Comment by Finch106** [comment]
I didn’t since the official HomeKit stuff was still working. I ended up just starting fresh after 3 years, with the new homebridge img, which is phenomenal.
