### ISSUE TITLE
Homebridge start on Windows 10 boot up

### ISSUE THREAD

**Issue by cubstitan95** [homebridge/homebridge#2478]
Hello! 
So I’m kinda new to all this coding and scripting stuff. Setting up homebridge and homebridge Config UI X was a bit difficult. But that’s done and working. Recently we’ve had a few brief brown outs resulting in the computer losing power. I was able to get into my computers BIOS settings and make some adjustments so the the computer powers itself on as soon as the receives power rather than having to push the power button. Now I’m trying to figure out how to get homebridge and homebridge Config UI X to start automaticity at boot up. I did some research and found this, https://github.com/homebridge/homebridge/issues/797 
But as I said earlier I’m a newbie and am having difficulty understanding the instructions. Dose anyone have a link to a video or something with step by step pictures? Or just explain like your explaining it to your grandma haha. Much appreciation!!!

**Comment by oznu** [comment]
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10

**Comment by cubstitan95** [comment]
Perfect! Thank you so much! Will attempt tomorrow and try restarting the computer and see if it works.

**Comment by cubstitan95** [comment]
Ok now I got problem. My all my accessories from homebridge weren’t responding in HomeKit so I took a peek at homebridge and the logs. And there’s some kind of error but I have no idea what it means or how to fix this:/ hears a picture of the logs. 
![442F1964-98FE-4D4E-AA0B-EFE7CA3CD037](https://user-images.githubusercontent.com/61809107/78742558-fdf82080-7921-11ea-9bd2-8340a5c86998.jpeg)

**Comment by Zer0x00** [comment]
The homebridge-harmony plugin throws some errors.
Post your issue on the project page of it. As a workaround you can tinker with the plugin configuration or uninstall it.

**Comment by Final-Hawk** [comment]
if this is solved could you please close it?

**Comment by AppleTechy** [comment]
Original question solved. As Zer0x00 said if that error persists, that is an issue with the Harmony hub plugin please create an issue on that plugin's repository so that plugin developer can review what occured.
