### ISSUE TITLE
Accessory Names Not Set

### ISSUE THREAD

**Issue by jvmahon** [homebridge/homebridge#2487]
It seems that HomeKit accessory names are not being properly set by the Beta. Here's the issue . . . .

1. This relates to my plugin homebridge-homeseer4. When the plugin creates HomeKit accessories, it configures each of them with a default name

2. Using the "release" homebridge, all works as expected and the plugin will generate and assign names to each device which will appear in the iOS Home app.

3. If I then update to the "beta" but keep the "accessories" and "persist" folders, all works fine and the HomeKit accessories names' stay the same - as expected.

4. However, if I delete the 'accessories' and 'persist' folders when switching to the "beta", such that the first run of the beta creates the HomeKit accessories anew, and I add the bridge to a new home by re-scanning the QR code, then the accessories are added, but the are all lacking device names.

Conclusion - It seems the Beta is properly recognizing names stored by the "release" homebridge in "accessories" or "persist" (wherever they are stored), so that a switch-over from "release" to "beta" looks fine; however, there is a name creation / storage problem when the beta is creating its own "accessories" and "persist" names and the default device names being assigned by a plugin aren't recognized.

**Comment by NorthernMan54** [comment]
@jvmahon is your issue possibly this?

With iOS 13.4, I found a new error message in the Home App when editing an Accessory Name

![IMG_4745](https://user-images.githubusercontent.com/19808920/79044167-a1229180-7bd1-11ea-8902-d1477da90a40.jpg)
 
And I found that when re-pairing or adding a plugin that has names don't meet this criteria the device just gets a name like "Switch".  Is the same issue?  Changing the names in homebridge to meet the criteria resolves the issue.

**Comment by jvmahon** [comment]
No, not the same issue. The names I use are starting / ending with a letter - I've tested and even relatively short (10 character) letter-only names have this problem. Tested on iOS 13.4.1. 
This is only a problem where you use the Beta homebridge with a "fresh" "accessories" and "persist" file.

This is on Windows 10, nodejs version 13.12.  As mentioned, the problem does not appear in the non-beta version of homebridge.

**Comment by Supereg** [comment]
Could you **please** supply code that produces an accessory without a name?

**Comment by Supereg** [comment]
And do you mean accessory or service names? A screenshot would be helpful.

**Comment by Supereg** [comment]
Could you check it it’s fixed in 0.4.54-beta.27?

**Comment by jvmahon** [comment]
Unfortunately, its now worse. When I try to add an accessory on a "fresh" bridge - i.e., with no pre-existing"accessories" and "persist" I get a "ReferenceError: N is not defined" - see below for context

[4/12/2020, 6:09:59 AM] [HomeSeer] Host for ASCII Interface set to: 192.168.1.1 at port 11000
[4/12/2020, 6:09:59 AM] Homebridge is running on port 51839.
[4/12/2020, 6:09:59 AM] [HomeSeer] Successfully connected to ASCII Control Interface of HomeSeer.
[4/12/2020, 6:09:59 AM] [HomeSeer] Sent Authorization Data
[4/12/2020, 6:09:59 AM] [HomeSeer] Successfully authorized Telnet port
[4/12/2020, 6:10:09 AM] ReferenceError: N is not defined
    at server_getS (C:\Users\James\AppData\Roaming\npm\node_modules\homebridge\node_modules\fast-srp-hap\lib\srp.js:259:38)
    at Server.setA (C:\Users\James\AppData\Roaming\npm\node_modules\homebridge\node_modules\fast-srp-hap\lib\srp.js:401:17)
    at HAPServer._this._handlePairStepTwo (C:\Users\James\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\HAPServer.ts:452:15)
    at HAPServer._this._handlePair (C:\Users\James\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\HAPServer.ts:417:12)
    at IncomingMessage.<anonymous> (C:\Users\James\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\HAPServer.ts:322:24)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

C:\Users\James>

**Comment by Supereg** [comment]
ADAIK the mentioned issue with the SRP library was fixed/reverted. Could you try reinstalling the latest beta please.

**Comment by jvmahon** [comment]
This morning, it wasn't working with beta.27, now it is.
And the naming issue also seems to be fixed.
Odd. In any case, I'll close the comment for now, and re-open if it reappears.

**Comment by Supereg** [comment]
We had some problems with the underlying libraries for hap-nodejs which got pulled in by mistake.

Great to hear, thanks for raising this issue.

**Comment by jvmahon** [comment]
Thanks. By the way, it seems a lot of changes are being made - is there a summary somewhere of any new features / advantages (other than the use of typescript), or is this just "internal plumbing" fixes and bug fixes rather than new features.

**Comment by Supereg** [comment]
There are some/many new features, some API  improvements and of course lots of bug fixes on the hap-nodejs side. We aim to have a full changelog when it's ready.

**Comment by donavanbecker** [comment]
[Changelog](https://github.com/homebridge/homebridge/blob/beta/CHANGELOG.md)
