### ISSUE TITLE
Installing Homebridge on a Homeseer Zee2

### ISSUE THREAD

**Issue by JCCcccspud** [homebridge/homebridge#2492]
The Instructions say: "Before you get started, make sure you have the following ready:
A Debian, Ubuntu or Raspbian Linux machine."  

Does the Homeseer Zee2 count or do I need to use the separate Raspberry Pi instructions lower down for a Pi1 or zero?

Then it says:  "Access to the Terminal. This can be via a desktop Terminal app, or remotely via SSH. You will need the ability to copy and paste commands from this guide into the terminal."  I don't know how to access the Zee2 via SSH but I can go directly into Linux tools via MyHs to enter commands.  Will that work?  Alternatively can you tell me how to do the SSH.  I downloaded Putty but have not had success in accessing the Zee2 with it.

Then it says to paste the commands in the grey box to install Node.js.  Do I do them one at a time or can I just copy and paste the whole grey box?  And if I do them one at a time do I include the first part with the # or just the text below it:
# setup repo
curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -

As you can tell I am more like an English major than a coder.

**Comment by oznu** [comment]
You can install Homebridge on practically any device you can install Node.js on. 

A quick google search tells me that the Homesee Zee2 seems to run a Raspberry Pi 3. So you could follow those instructions if it's also running Rasbpian Linux. You can always give it a go and see what happens.

> Do I do them one at a time or can I just copy and paste the whole grey box?

One at a time.

> And if I do them one at a time do I include the first part with the # or just the text below it.

No. But if you did nothing would happen.
