### ISSUE TITLE
Delete specific accessories within a plugin.

### ISSUE THREAD

**Issue by Baassievalk** [homebridge/homebridge#2499]
At home I have tons of Hue lights. I only want the ones in my room, is there a way to delete some lights without deleting all of them? For the time being I grouped the unnecessary ones. But when turning off all lights they turn off as well. Any help would be appreciated!

**Comment by ebaauw** [comment]
If you expose these lights using the Hue bridge, you're out of luck: it exposes all.  If you use Homebridge Hue, you can whitelist the lights you want exposed or blacklist the ones you don't want to expose.  See https://github.com/ebaauw/homebridge-hue#configuration.
