### ISSUE TITLE
Eve for HomeKit App v4.2 general Issue with Homebridge Devices

### ISSUE THREAD

**Issue by DJay-X** [homebridge/homebridge#2503]
Hi there,

can anybody else confirm or did notice, that the lates update of [Eve for HomeKit App v4.2](https://apps.apple.com/de/app/eve-für-homekit/id917695792) is brining major issues in handling Homebridge accessories/devices?

When changing an Icon from a device, the Icon is automatically changed on other devices by Eve App, even if they have nothing to do with the first device.

Devices can't be arranged/sorted in the room view. The device is always moving back to the previous position.

First suggestion is that Eve has changed the handling of devices, linking to the serial number together.

If the serial number is identical, Eve interpretation is that it is the same device. Even if the devices from complete different plugins or on other Homebridges or Instances.

And of course homebridge-plugins can generate a serial number, or not. And not rare just "Default-SerialNumber", "<default>" etc. meaning this issue effects a couple of devices.

In my case with around 30+ plugins, it is several devices.

So Eve is taking this serial number connection, link this devices in background and if you change the Icon, move the device in the room, or place it in Favorites, it's doing it with all devices with the same serial. 

As long as devices have the same identical serial number (or just wording in it) this issue with Eve 4.2 is linking everything together, even it is not meant to be. Even devices with same serial like homebridge-harmony generating more than one device, can't be sorted anymore in a room, because of the same serial number.

Because of this, at the moment Eve App is not usable for me. 

I would like to point this out to you because I would like to get more voices and confirmation that this affects a lot of Homebridge plugin users.

Plugins: zway@0.5.0 | eveatmo@0.5.0 | netatmo@0.2.0 | ssh@0.0.6 | platform-wemo@1.5.5 | people@0.6.2 | nest@4.4.4 | harmony@1.3.4 | notification@1.0.0 | ifttt@0.4.1 | cmdswitch2@0.2.10 | iBrew | broadlink-rm@3.6.22 | weather-plus@2.8.2 | bigAssFans@1.1.4 | delay-switch@2.1.0 | config-ui-x@4.15.1 | airrohr@1.1.8 | nello@0.4.5 | alexa@0.4.67 | neato@0.7.2 | script2@0.2.7 | mi-fan@0.1.1 | xiaomi-fan@0.8.1 | mi-gateway-security@0.1.1 | mijia-camera@0.0.2 | smartmi-humidifier@0.1.3 | mi-hygrothermograph@3.0.0 | moodo@2.1.2 | webos-tv@1.6.4 | airtunes-radio@0.2.0 | music@0.2.19 | http-webhooks@0.0.57 | homeconnect@0.17.2 | cmdtriggerswitch@1.2.0

- Sorting Issue. Device sorting slides back. Can't be sorted individually anymore.
Example: [homebridge-harmony](https://github.com/nicoduj/homebridge-harmony) Fixed by @nicoduj 18.04.2020 [#249](https://github.com/nicoduj/homebridge-harmony/issues/249)
![RPReplay_Final1587111763 2020-04-17 10_34_59](https://user-images.githubusercontent.com/3874239/79549333-222ccd80-8097-11ea-95c9-1af63434d97e.gif)

- Sorting Issue. Device sorting slides back. Can't be sorted individually anymore.
Example: [homebridge-people](https://github.com/PeteLawrence/homebridge-people)
![RPReplay_Final1587214664 2020-04-18 15_02_45](https://user-images.githubusercontent.com/3874239/79638539-2d125b80-8186-11ea-8ce1-1701fc6f8a36.gif)

- Changing one Icon of a device, is changing the Icon on every device.
Example: [homebridge-broadlink-rm](https://github.com/lprhodes/homebridge-broadlink-rm)
![RPReplay_Final1587111880 2020-04-17 10_36_52](https://user-images.githubusercontent.com/3874239/79549529-64560f00-8097-11ea-8b90-8258f1691d57.gif)

- Starring only one device is bringing all other devices with same serial to favorite screen.
Example: [homebridge-broadlink-rm](https://github.com/lprhodes/homebridge-broadlink-rm)   
![RPReplay_Final1587112005 2020-04-17 10_38_41](https://user-images.githubusercontent.com/3874239/79549712-9ff0d900-8097-11ea-86cc-2d7ff22f88bf.gif)

- Starring only one device is bringing all other devices with same serial to favorite screen.Also individual sorting is not possible. [homebridge-delay-switch](https://github.com/nitaybz/homebridge-delay-switch)
![RPReplay_Final1587217613 2020-04-18 15_50_01](https://user-images.githubusercontent.com/3874239/79639496-81b8d500-818c-11ea-8068-e04792a70106.gif)

- Individual sorting problem and not able to assign individual icon.
Example: [homebridge-ifttt](https://github.com/ilcato/homebridge-ifttt)
![RPReplay_Final1587222612 2020-04-18 17_14_18](https://user-images.githubusercontent.com/3874239/79641577-b16dda00-8198-11ea-92f0-d0e9023c8bfe.gif)

- Individual sorting problem and not able to assign individual icon.
Example: [homebridge-notification](https://github.com/sergeturgeon/homebridge-notification)
![RPReplay_Final1587223501 2020-04-18 17_28_51](https://user-images.githubusercontent.com/3874239/79641856-4c1ae880-819a-11ea-82c8-16a36f70aab0.gif)

All the mentioned plugins have in common, that there is no individual serial number for each device/accessory/switch. And if they use just "Default-SerialNumer" "unknow" or anything else not unique facing this Eve App issue. Not individual sorting, no individual icon assign, no individual starring for favorite, and mishmash with even other accessories from other plugin developers using the same serial number. 

One solution could that developers implement an option to place in config.json "unique_serial": "xxx" which can then be added by the user. Or they find a way to automatically set a individual uuid by the plugin itself for each generated device/switch....

![Napkin 17 04 20, 10 42 02 AM](https://user-images.githubusercontent.com/3874239/79550193-4b019280-8098-11ea-9d27-8624c4dd5b42.png)

**Comment by ebaauw** [comment]
See https://www.evehome.com/en/blog/eve-app-4-2-update, they introduced _Shared Eve settings_.  Seems they screwed up brilliantly, the ordering (of rooms, services in a room, favourites) on my iPhone has been reset completely; the ordering on my iPad has mostly been retained.  The devices don't seem to be synchronised, though.

> When changing an Icon from a device, the Icon is automatically changed on other devices by Eve App, even if they have nothing to do with the first device.

They are linked to the same HomeKit Home, I would think?

> Devices can't be arranged/sorted in the room view. The device is always moving back to the previous position.

Sounds like issues with iCloud syncing.  Seen many of these with Apple's Home app.  Usually waiting a couple of hours helps.

> If the serial number is identical, Eve interpretation is that it is the same device. Even if the devices from complete different plugins or on other Homebridges or Instances.

Worse, even when exposed from different bridges.  This has been an issue with Eve for a long time, where Eve would link the history of multiple accessories into one.  HomeKit seems to identify accessories by aid of the (HomeKit) bridge and aid of the accessory; Eve seems to use the UUID of the accessory, irrespective of the (HomeKit) bridge.

**Comment by DJay-X** [comment]
> When changing an Icon from a device, the Icon is automatically changed on other devices by Eve App, even if they have nothing to do with the first device.

> They are linked to the same HomeKit Home, I would think?

Sorry I was not clear. Its not that the iCloud Sync vom iDevice to iDevice, which is working okay, it's the issue all-in-all that things getting changed by Eve App because they group homebridge devices by serial number which should not be "grouped". Like showing in the samples above. 

It's most likely the "Serial Number" problem, having Homebridge devices non, default or same.

**Comment by palasinio** [comment]
@DJay-X Wow! Nice work with this post. Today I got version 4.2 of the EVE app and discovered for „homebridge-website-to-camera“ and „homebridge-cmdswitch2“ the unwanted behavior so far. Didn‘t checked everything yet.

**Comment by DJay-X** [comment]
> Today I got version 4.2 of the EVE app and discovered for „homebridge-website-to-camera“ and „homebridge-cmdswitch2“ the unwanted behavior so far. 

@palasinio Thanks. I hope this helps bringing the Eve App 4.2 Issue in focus to other homebridge plugin developers as well. Some already did a great and quick adjustment. 
And having "Default-SerialNumber" or "unknown" as default is in general not pretty. ;) 

Maybe you should also open an Issue "of course you can copy/paste text from one above if you like" to „homebridge-website-to-camera“ and „homebridge-cmdswitch2“.
If you point to this Issue [#2503](https://github.com/homebridge/homebridge/issues/2503) it will be added to the list above and giving a nice overview.

**Comment by DJay-X** [comment]
@oznu @nfarina I would like to make the suggestion that the "unique_serial": availability should be a criteria for https://github.com/homebridge/verified
A Serial number "Default-SerialNumber" "unknown" etc. is in general not fancy and can cause problems in the future. Not only the recent Eve 4.2.
Thank you in advance for considering this.

**Comment by palasinio** [comment]
> But it looks like [homebridge-cmdswitch2](https://github.com/luisiam/homebridge-cmdswitch2#advanced-configuration-optional) is able to use "serial": "XXXXXXXXXXX" in the config.json. Maybe you should try this and give here a short feedback if it also helps to fix the Eve 4.2 Issue.

Nice find. I tried this and you can see the different serials in Home, but th ebehaviour in EVE is the same.

**Comment by DJay-X** [comment]
> > But it looks like [homebridge-cmdswitch2](https://github.com/luisiam/homebridge-cmdswitch2#advanced-configuration-optional) is able to use "serial": "XXXXXXXXXXX" in the config.json. Maybe you should try this and give here a short feedback if it also helps to fix the Eve 4.2 Issue.
> 
> Nice find. I tried this and you can see the different serials in Home, but th ebehaviour in EVE is the same.

If you see it in Home App, it's working. There is another Bug with Eve App in addition. Unfortunately you have to remove Eve App and download it again on your iPhone/iPad. After this, the serial number like you see already in Apple Home App is also then available in Eve. And by have a unique serial you can sort, assign separate icon and starr devices.

**Comment by marli2** [comment]
I have the exact same problem here, but « homebridge-automation-switches» plugin **seems** to be working fine.

**Comment by nicoduj** [comment]
It seems it does not need modifications anymore !

![image](https://user-images.githubusercontent.com/19813688/80411637-ce0ebe00-88cc-11ea-8451-1c3054305500.jpeg)

**Comment by DJay-X** [comment]
Eve Team listenden and did some fast action. 👍 

But as mentioned I don't think it's good for a plugin generating no unique serial or something like "Default-SerialNumber" or "unknown". 
Who knows to what extravagant behavior such thing could cause next. 😉

**Comment by Supereg** [comment]
Okay just to understand this correctly. Eve used the serial number to uniquely identify all accessories? 

What do they mean with accessories that `don't adhere to HomeKit service labeling`.

It seems fixed now. I don't know if we really can do anything about that in the homebridge/HAP-NodeJS codebase? HAP-NodeJS just defines "Default-SerialNumber" as otherwise the Home App would reject the Accessory compleletey if the SerialNumber is not set. I also don't get what of what requirements they are talking about. The HAP spec only defines for the SerialNumber that it must have a length greater than 1.
