### ISSUE TITLE
Cannot couple iPad IOS 10.3.4 with homebridge-config-ui-x v4.15.1

### ISSUE THREAD

**Issue by tobi18ww** [homebridge/homebridge#2505]
cannot couple iPad IOS 10.3.4 with homebridge-config-ui-x v4.15.1 ...
with iOS 13 couple successful. After finishing the Setup on iOS 13 I can see all devices on iPad (iOS 10.3.4) but all devices are "no answer"

**Comment by yilianziyu** [comment]
Same problem.when i logined himebridge-config-ui-x,it showed that "homebridge not running".

**Comment by Supereg** [comment]
@tobi18ww @yilianziyu Could you both verify that your issue still persist with the latest version of Homebridge (currently 1.0.4)?

**Comment by yilianziyu** [comment]
> @tobi18ww @yilianziyu Could you both verify that your issue still persist with the latest version of Homebridge (currently 1.0.4)?

Issue resolved. According to the logs,a plugin made the homebridge server stop running,and I found the answer via https://github.com/normen/homebridge-bravia/issues/42
