### ISSUE TITLE
Warning about unexpected characteristics on Fan Service

### ISSUE THREAD

**Issue by nicoduj** [homebridge/homebridge#2508]
**Describe The Bug:**

While working on a plugin Fan based, I have the following warnings on homebridge 0.4.53. Am I missing something ?

**To Reproduce:**

Code of the plugin : https://github.com/nicoduj/homebridge-deebotEcovacs

**Expected behavior:**

No warnings since characterisitcs are marked as optionnal in hap on the corresponding version (https://github.com/homebridge/HAP-NodeJS/blob/80de04372a9ac3a3bce884e9699a4c72b41b0d23/lib/gen/HomeKitTypes.js - cannot find 0.4.51 only 0.4.50 and 0.4.52)  : 

```
Service.Fan = function(displayName, subtype) {
  Service.call(this, displayName, '00000040-0000-1000-8000-0026BB765291', subtype);

  // Required Characteristics
  this.addCharacteristic(Characteristic.On);

  // Optional Characteristics
  this.addOptionalCharacteristic(Characteristic.RotationDirection);
  this.addOptionalCharacteristic(Characteristic.RotationSpeed);
  this.addOptionalCharacteristic(Characteristic.Name);
};
...
Characteristic.RotationSpeed.UUID = '00000029-0000-1000-8000-0026BB765291';
...
Characteristic.RotationDirection.UUID = '00000028-0000-1000-8000-0026BB765291';

```

**Logs:**

```
HAP Warning: Characteristic 00000028-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 00000029-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
```

**Homebridge Config:**

```json
not relevant
```

**Screenshots:**

![Capture d’écran 2020-04-19 à 22 46 53](https://user-images.githubusercontent.com/19813688/79699460-0b050000-8290-11ea-9d96-28a91c1ea3fc.png)

**Environment:**

* **Node.js Version**: v12.16.2
* **NPM Version**: v6.14.4
* **Homebridge Version**: 0.4.53
* **Operating System**: Docker 
* **Process Supervisor**: hb-service (OZNU DOCKER IMAGE)

**Comment by oznu** [comment]
Is this still the case in 1.0.x?

**Comment by nicoduj** [comment]
It is ok in 1.0.X ! Closed :)
