### ISSUE TITLE
Use JSON5 for parsing config.json

### ISSUE THREAD

**Issue by mgcrea** [homebridge/homebridge#2510]
Before releasing the next version, it would be awesome to use [JSON5](https://github.com/json5/json5) to parse the config.json, it would allow use to use comments inside JSON and would easily handle many errors (trailing commas) that currently break homebridge. Could work on a PR if wanted.

**Comment by donavanbecker** [comment]
Hey @mgcrea, thanks for the suggestion. We will look into this. Currently the Homebridge UI config editor already implements this to automatically fix some syntax issues on save, See [Config UI X v4.14.0](https://github.com/oznu/homebridge-config-ui-x/blob/master/CHANGELOG.md#notable-changes-2).

**Comment by mgcrea** [comment]
Sounds good and it probably makes sense in a UI, but as a plugin developer I would not want my comments to be stripped out by an auto-fix. My main need is to be able to quickly toggle config lines/blocks using comments.
