### ISSUE TITLE
Error: Plugin requires a HomeBridge version of ~0.4.53

### ISSUE THREAD

**Issue by Chimpepe** [homebridge/homebridge#2519]
**Describe The Bug:**
Error: Plugin requires a HomeBridge version of ~0.4.53 which does not satisfy the current HomeBridge version of 1.0.0. You may need to upgrade your installation of HomeBridge.

**To Reproduce:**
Upgrading to v1.0.0

**Expected behavior:**
Normal Upgrade process 

[**Logs:**]()
https://gist.github.com/Chimpepe/99bd23faf986aa6396bc286708611c50

**Comment by ebaauw** [comment]
You need to upgrade homebridge-hue as well, see https://github.com/ebaauw/homebridge-hue/issues/676#event-3274036396.

**Comment by Chimpepe** [comment]
Thank you!
