### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-hue

### ISSUE THREAD

**Issue by Stefan-83** [homebridge/homebridge#2521]
**Describe The Bug:**
Since upgrading to 1.0.0, the homebridge-service isn't starting anymore.

**To Reproduce:**
Rebooted several times - same behavior

**Expected behavior:**
Normal startup

[**Logs:**]()
```
homebridge[6196]: [4/27/2020, 1:32:28 PM] Error: Plugin /usr/local/lib/node_modules/homebridge-hue requires a HomeBridge version of ~0.4.53 which does not satisfy the current HomeBridge version of 1.0.0. You may need to upgrade your installation of HomeBridge.
```

**Homebridge Config:**

**Environment:**

* **Node.js Version**: v12.4.0
* **NPM Version**: 6.9.0
* **Homebridge Version**: 1.0.0
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd

**Comment by oznu** [comment]
Update the Hue plugin.

```
sudo npm install -g homebridge-hue@latest
```

**Comment by u20p17** [comment]
install hue beta with the following command:
 sudo npm -g i homebridge-hue@next

reboot homebridge and it should work again.

**Comment by nin9s** [comment]
> install hue beta with the following command:
> sudo npm -g i homebridge-hue@next
> 
> reboot homebridge and it should work again.

@ebaauw already updated the tags so "latest" is correct as of today

**Comment by netRunner0** [comment]
https://pastebin.com/pTVAg9qd

**Comment by oznu** [comment]
As of v1.0.1 the error message is now more clear that the plugin may require updating; not Homebridge.
