### ISSUE TITLE
TypeError: Cannot read property 'getCharacteristic' of undefined

### ISSUE THREAD

**Issue by Stefan-83** [homebridge/homebridge#2523]
**Describe The Bug:**
Since upgrading to 1.0.0, the homebridge-service isn't starting anymore.
I have updated plugins: homebridge-hue and homebrigde-rpi to latest version.

**To Reproduce:**
Rebooted several times - same behavior

**Expected behavior:**
Normal startup

[**Logs:**]()
```
Apr 27 16:52:06 openHABianPi systemd[1]: Started Node.js HomeKit Server.
Apr 27 16:52:07 openHABianPi homebridge[1256]: [4/27/2020, 4:52:07 PM] Loaded config.json with 8 accessories and 8 platforms.
Apr 27 16:52:07 openHABianPi homebridge[1256]: [4/27/2020, 4:52:07 PM] ---
Apr 27 16:52:08 openHABianPi homebridge[1256]: [4/27/2020, 4:52:08 PM] TypeError: Cannot read property 'getCharacteristic' of undefined
Apr 27 16:52:08 openHABianPi homebridge[1256]:     at Accessory._this._sideloadServices (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1046:17)
Apr 27 16:52:08 openHABianPi homebridge[1256]:     at Function.Accessory.deserialize (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1681:15)
Apr 27 16:52:08 openHABianPi homebridge[1256]:     at Function.deserialize (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:151:33)
Apr 27 16:52:08 openHABianPi homebridge[1256]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:261:34
Apr 27 16:52:08 openHABianPi homebridge[1256]:     at Array.map (<anonymous>)
Apr 27 16:52:08 openHABianPi homebridge[1256]:     at Server.loadCachedPlatformAccessoriesFromDisk (/usr/local/lib/node_modules/homebridge/src/server.ts:260:58)
Apr 27 16:52:08 openHABianPi homebridge[1256]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:147:10)
Apr 27 16:52:08 openHABianPi homebridge[1256]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
Apr 27 16:52:08 openHABianPi homebridge[1256]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 27 16:52:08 openHABianPi homebridge[1256]:     at Module._compile (internal/modules/cjs/loader.js:774:30)


```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

Node.js Version: v12.4.0
NPM Version: 6.9.0
Homebridge Version: 1.0.0
Operating System: Raspbian
Process Supervisor: Systemd

**Comment by ebaauw** [comment]
```
Apr 27 16:52:08 openHABianPi homebridge[1256]:     at Server.loadCachedPlatformAccessoriesFromDisk (/usr/local/lib/node_modules/homebridge/src/server.ts:260:58)
```
Looks like this is happening when Homebridge is trying to load `cachedAccessories`.  Could you attach that file here?

**Comment by Stefan-83** [comment]
hm, the file or folder doesn't exist:
![image](https://user-images.githubusercontent.com/52136837/80390385-a3ad0880-88ac-11ea-986a-71ce0217cd29.png)

**Comment by ebaauw** [comment]
It's in the user folder, `~/.homebridge/accessories` or `/var/homebridge/accessories`.

**Comment by Stefan-83** [comment]
ah, perfect. thanks!

here's the content of cachedAccessories:
```
[{"plugin":"homebridge-sonoff","platform":"Sonoff","context":{"index":0,"relay":"","hostname":"192.168.178.104","url":"http://192.168.178.104/cm?user=admin&password=&cmnd=Power","baseUrl":"http://192.168.178.104/cm$
```

**Comment by Stefan-83** [comment]
that worked... thanks
and after I kicked out the plugin homebridge-fibaro-hc2 from the config.json, the homebridge works again :)
I think, that homebridge-fibaro-hc2 will need an update as well?

one more thing. when using the fsck command, i'll get that message:
```
[18:25:44] openhabian@openHABianPi:/var/homebridge/accessories$ fsck
fsck from util-linux 2.29.2
e2fsck 1.43.4 (31-Jan-2017)
/dev/mmcblk0p2 is mounted.



WARNING!!!  The filesystem is mounted.   If you continue you ***WILL***
cause ***SEVERE*** filesystem damage.


Do you really want to continue<n>? no

```
Is this correct? Can I proceed?

**Comment by Supereg** [comment]
> ah, perfect. thanks!
> 
> here's the content of cachedAccessories:
> 
> ...

As your posted line end with a `$` I assume you just copied it out of a editor like nano? I assume you didn't paste the whole file here.

**Comment by Supereg** [comment]
Would have been important to know what actually caused this issue.

**Comment by ebaauw** [comment]
No, do **not** run `fsck` on a life file system.  You need to boot the Pi in single user mode (requires a monitor and keyboard/mouse), or shutdown the Pi, put the SD As secondary drive in another system and check it from there.

**Comment by Stefan-83** [comment]
@Supereg : don't know, what the issue was. Yes, it was copied from a editor (nano)
@ebaauw : thanks for your help. One question about cachedAccessories: what does this file actually do?

**Comment by ebaauw** [comment]
As the name suggests, it stores accessories for dynamic platform plugins, so that when homebridge (re-)starts, they can be loaded without the plugin having to re-expose them.

The problem is that we don't know for sure if the file was corrupted or just copied/pasted incompletely.

**Comment by Supereg** [comment]
Yeah, already suspected nano. Do you still have the file?

**Comment by Stefan-83** [comment]
@Supereg : sorry, I deleted it completly.
@ebaauw : Thanks for clarification
