### ISSUE TITLE
Update Plugin Capatibility Page

### ISSUE THREAD

**Issue by macjeff** [homebridge/homebridge#2524]
This page has been updated for a while

https://github.com/homebridge/homebridge/wiki/Homebridge-Beta-Plugin-Status

Can we change it to public now so that public can see for 1.01 (or later) what will or wont work?

Also how can I add to it?   I have tested a plugin that is not on the list and works fine with 1.01

**Comment by donavanbecker** [comment]
- We have a wiki for [v1.0.1](https://github.com/homebridge/homebridge/wiki/Homebridge-v1.0.1-Plugin-Status).
- You should be able to just click edit and be able to update the page.

**Comment by macjeff** [comment]
DONE.  You can close this one if you want.

**Comment by donavanbecker** [comment]
updated the wiki name.. just fyi... [Homebridge Plugin Status](https://github.com/homebridge/homebridge/wiki/Homebridge-Plugin-Status)
