### ISSUE TITLE
[homebridge] Failed to check registry.npmjs.org for updates: Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by StefanGebhardt** [homebridge/homebridge#2526]
**Describe The Bug:**
After upgrade to 1.0.1 i see this in my log (in normal work, not while booting). despite, homebridge seems to work normal. Also all plugins.

**To Reproduce:**
--

**Expected behavior:**
--

[**Logs:**]()
Apr 27 19:48:54 raspberrypi sudo[29328]: homebridge : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/kill -9 24278
Apr 27 19:48:54 raspberrypi sudo[29328]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 27 19:48:54 raspberrypi sudo[29328]: pam_unix(sudo:session): session closed for user root
Apr 27 19:49:03 raspberrypi sudo[29444]: homebridge : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/kill -9 29362
Apr 27 19:49:03 raspberrypi sudo[29444]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 27 19:49:03 raspberrypi sudo[29444]: pam_unix(sudo:session): session closed for user root
Apr 27 19:49:11 raspberrypi homebridge[24101]: [2020-4-27 19:49:11] [Config] [homebridge] Failed to check registry.npmjs.org for updates: Cannot read property 'latest' of undefined

**Environment:**

* **Node.js Version**: 12.16.2
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.0.1
* **Operating System**: Raspbian
* **Process Supervisor**: ?

**Comment by hoefs** [comment]
Same here 

[4/28/2020, 9:14:43 AM] [Config] [homebridge-tahoma] Failed to check registry.npmjs.org for updates: timeout of 5000ms exceeded
[4/28/2020, 9:14:43 AM] [Config] [homebridge-zp] Failed to check registry.npmjs.org for updates: timeout of 5000ms exceeded

**Comment by oznu** [comment]
These are just notices that the UI couldn't check for updates for whatever reason it logged. npm registry has random issues all the time. It won't effect the operation of Homebridge or Homebridge UI.

**Comment by StefanGebhardt** [comment]
Since 1.0.2 it seems to be vanished...

**Comment by kitsen13** [comment]
Same issue on 1.0.2

**Comment by kitsen13** [comment]
Same issue on 1.1.1

**Comment by jmeross** [comment]
I hope this helps a nerd in need out there. I had the exact same error when trying to search for plugins. Even after a fresh install. I was trying WiFi only and Ethernet. But what I did to resolve was switch off my router and then switched the router on again. All working, I did a little celebration dance.
