### ISSUE TITLE
Zooz Zen21 v3 switch on Smart Things not recognized properly

### ISSUE THREAD

**Issue by jareep** [homebridge/homebridge#2531]
Recently installed a Zooz Zen21 v3 switch (single pole installation) and everything works great with my Smart Things hub, and with Google Assistant. However, the HomeBridge isn't properly recognizing the switch pulled from Smart Things. Attached is a screenshot of the device as HomeBridge sees it. I don't see anything in the logs about the device.

<img width="797" alt="zooz" src="https://user-images.githubusercontent.com/2954436/80450054-ac263300-88ee-11ea-889b-e8104a8854e6.png">

**Comment by oznu** [comment]
Note that the Homebridge UI does not fully implement every accessory type.

If your accessory is also not operating as expected in the iOS Home app then you should report this issue on the corresponding plugins GitHub project page.
