### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by vespino** [homebridge/homebridge#2532]
I just ran an upgrade from Ubuntu 18.04 to 20.04 after which homebridge didn’t seem to start. Before I start hunting for bugs, are there any known issues I could look into?

**Comment by NorthernMan54** [comment]
Likely issue is the version of nodejs being upgraded and individual plugins needing to have ‘npm rebuild’ ran against them

When you start homebridge, the logging is usually pretty verbose with this issue

**Comment by vespino** [comment]
What would you recommend? Upgrade, run npm rebuild and see what happens?

**Comment by NorthernMan54** [comment]
Review the log messages from homebridge when starting, and review the errors messages

**Comment by vespino** [comment]
The following keeps repeating:

Apr 30 09:58:33 homebridge systemd[1]: Stopped Homebridge.
Apr 30 09:58:33 homebridge systemd[1]: Started Homebridge.
Apr 30 09:58:33 homebridge homebridge[1462]: /usr/bin/env: ‘node’: No such file or directory
Apr 30 09:58:33 homebridge systemd[1]: homebridge.service: Main process exited, code=exited, status=127/n/a
Apr 30 09:58:33 homebridge systemd[1]: homebridge.service: Failed with result 'exit-code'.

There is no specific homebridge log btw.

**Comment by vespino** [comment]
I apparently had to reinstall nodejs after which homebridge fired up without problems.

**Comment by oznu** [comment]
I tested the Linux install guide from the Homebridge wiki and it all works as expected on Ubuntu 20.04 😄
