### ISSUE TITLE
Error upgrading to 1.0.0

### ISSUE THREAD

**Issue by arejay73** [homebridge/homebridge#2535]
**Describe Your Problem:**
I am getting this error after following the instructions for MacOS.

` Error: EACCES: permission denied, open '/Users/xxxxxx/.homebridge/accessories/cachedAccessories'`

I made sure that node, npm, homebridge executables has full disk access in the privacy settings.
 
**Environment:**

* **Node.js Version**: v12.1.0
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.0.2
* **Operating System**: macOS
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Run this to fix all the permissions:

```
sudo hb-service uninstall 
sudo hb-service install
```

You won't loose any settings, it just recreates the service and does some sanity checks.

**Comment by arejay73** [comment]
That worked.  Thanks.
