### ISSUE TITLE
Current Nodejs version is not displayed

### ISSUE THREAD

**Issue by devFenix** [homebridge/homebridge#2537]
Hey,

i installed nodejs 12.16.2, but homebridge only sees 12.16.1
<img width="202" alt="Bildschirmfoto 2020-04-28 um 22 09 44" src="https://user-images.githubusercontent.com/62382487/80532819-fbc33800-899c-11ea-945c-556514462dd3.png">
<img width="1222" alt="Bildschirmfoto 2020-04-28 um 22 10 25" src="https://user-images.githubusercontent.com/62382487/80532906-18f80680-899d-11ea-928b-106181cb52b3.png">

**Comment by oznu** [comment]
Make sure you update Node.js using the same method you originally used to install it.

Your node path suggests you did not use `nvm` originally.

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#step-1-install-nodejs

**Comment by devFenix** [comment]
I didn't know the original method. Can I fix it (remove / reinstall)?

**Comment by codyc1515** [comment]
If you're going to go through all of that you may as well just install the official image. https://github.com/homebridge/homebridge-raspbian-image

**Comment by oznu** [comment]
This guide shows how to ensure you are only running a single version of Node.js:

https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux
