### ISSUE TITLE
Trouble connecting homebridge to the home app

### ISSUE THREAD

**Issue by xBotRaid** [homebridge/homebridge#2538]
Following scenario: 
Have been running homebridge for a while now with everything working like a charm.
Then recently (2-3 days ago) all my accessories just turned unresponsive with the red "No response" message from below every accessory. After that I deleted the homebridge bridge in the home app and tried reconnecting since then without any success so far. Also no _hap._tcp entry in the Bonjour Browser.

Setup:
- Win10 Pro running as a server with homebridge installed(homebridge can boot without any error messages)
- AppleTV, iPad and iPhone as clients trying to connect to the server

VERSIONS:
- Homebridge: currently 1.0.3 / also tried 0.4.53, 1.0.0, 1.0.1 and 1.0.2
- node: v12.16.2
- npm: 6.13.7

Config:
```
{
    "mdns": {
        "interface": "192.168.0.XX"
    },
    "bridge": {
        "name": "Homebridge-of-SM",
        "username": "43:21:22:XX:XX:XX",
        "port": 51821,
        "pin": "483-XX-XXX"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "indigo",
            "tempUnits": "c",
            "proxyHost": "XXX/XXX",
            "platform": "config"
        }
    ],
    "accessories": [
        {
            "accessory": "MagicHome",
            "name": "LED Strip",
            "ip": "192.168.0.XXX",
            "setup": "RGBW",
            "purewhite": false
        },
        {
            "accessory": "Sony-Television",
            "name": "Sony Television",
            "ipaddress": "192.168.0.XXX",
            "presharedkey": "CENSORED",
            "port": "80"
        }
    ]
}
```

Log when starting up and connecting with the device (note: nothing special, no sign of error in the logs):

> `[2020-4-28 23:06:21] [HB Supervisor] Homebridge Path: C:\Users\SilvanM\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge
> [2020-4-28 23:06:21] [HB Supervisor] UI Path: C:\Users\SilvanM\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\bin\standalone.js
> [2020-4-28 23:06:21] [HB Supervisor] Starting Homebridge with extra flags: -I
> [2020-4-28 23:06:21] [HB Supervisor] Started Homebridge with PID: 18564
> [2020-4-28 23:06:21] Loaded config.json with 2 accessories and 1 platforms.
> [2020-4-28 23:06:21] ---
> [2020-4-28 23:06:21] Loaded plugin: homebridge-config-ui-x
> [2020-4-28 23:06:21] Registering platform 'homebridge-config-ui-x.config'
> [2020-4-28 23:06:21] ---
> [2020-4-28 23:06:21] Loaded plugin: homebridge-delay-switch
> [2020-4-28 23:06:21] Registering accessory 'homebridge-delay-switch.DelaySwitch'
> [2020-4-28 23:06:21] ---
> [2020-4-28 23:06:21] Loaded plugin: homebridge-magichome
> homebridge API version: 2.4
> [2020-4-28 23:06:21] Registering accessory 'homebridge-magichome.MagicHome'
> [2020-4-28 23:06:21] ---
> [2020-4-28 23:06:22] Loaded plugin: homebridge-sony-television
> [2020-4-28 23:06:22] Registering accessory 'homebridge-sony-television.Sony-Television'
> [2020-4-28 23:06:22] ---
> [2020-4-28 23:06:22] Loaded plugin: homebridge-statefuldummy
> [2020-4-28 23:06:22] Registering accessory 'homebridge-statefuldummy.StatefulDummySwitch'
> [2020-4-28 23:06:22] ---
> [2020-4-28 23:06:22] Loading 1 platforms...
> [2020-4-28 23:06:22] [Config] Initializing config platform...
> [2020-4-28 23:06:22] [Config] Running in Service Mode
> [2020-4-28 23:06:22] Loading 2 accessories...
> [2020-4-28 23:06:22] [LED Strip] Initializing MagicHome accessory...
> [2020-4-28 23:06:22] [Sony Television] Initializing Sony-Television accessory...
> Setup Payload:
> X-HM://00249Q1JUNBKI
> Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
>                        
>     ┌────────────┐     
>     │ 483-58-XXX │     
>     └────────────┘     
>                        
> [2020-4-28 23:06:22] Homebridge is running on port 51821.
> [2020-4-28 23:06:22] [LED Strip] DEVICE COLOR: 255,100,50
> [2020-4-28 23:06:22] [Config] Homebridge Config UI X v4.16.0 is listening on :: port 8581`

**Comment by Supereg** [comment]
Could you try removing the `mdns` configuration section from your config.json?

**Comment by xBotRaid** [comment]
> Could you try removing the `mdns` configuration section from your config.json?

Thanks for the suggestion, just updated to hombridge@latest (v1.0.3-official) and removed the mdns config. unfortunately the issue persists.

**Comment by Supereg** [comment]
Just to get the context from the other issue into here:

> I had my Homebridge running for about 4 weeks on my Server running Windows 10. Suddenly everything lost connection. All accessories „not responding“, then I deleted them... Now I cannot get Homebridge to be recognized by any of my iOS Devices, it keeps on failing to find the old accessories. Then I deleted the Homebridge config and tried to do reconnect, also cannot find anything related to my Server inside the Bonjour Browser on the iPhone or iPad on the same Network.
> 
> I tried so many suggestions written in Forums and I'll give you a quick recap with links on what I've already done:
> 
> * Deleted persist and accessories folder and all plugins - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories)
> * Changed username, pin, name and port + reinstall of Node and HomeKit  - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories)
> * Reconfigured WIFI - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#home-couldnt-connect-to-this-accessory)
> * Disabled IPv6 in Windows Network Adapter Settings (in forum they did it on Raspbian) - [Can't Pair GitHub Comment](https://github.com/nfarina/homebridge/issues/607#issuecomment-236471712)
> * Examined logs for plugin errors - [mDNS packets GitHub Comment](https://github.com/nfarina/homebridge/issues/1957#issuecomment-497756617)
> * Run Debug Mode (no errors found) - [Basic Troubleshooting GitHub Wiki](https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting#debug-mode)
> * Changed Network interface (ethernet adapter instead of built in port - no success either) - [GitHub Comment](https://github.com/nfarina/homebridge/issues/1801#issuecomment-427690849)
> * Specified mDNS local Server-IP inside config file - [mDNS packets Comment GitHub](https://github.com/nfarina/homebridge/issues/1957#issuecomment-468709606)
> * Checked if port is open via command (worked) - ["Homebridge Running but..." GitHub Comment](https://github.com/nfarina/homebridge/issues/1801#issuecomment-378514491)
> * Opened Homebridge Port and Bonjour Ports (UDP: 1900 , 5350, 5351, 5353) in Windows Firewall
> * Reset network configuration
> 
> I tried literally anything I found online, but no success. Many things are done inside of a Linux based system, mine is on Windows so sometimes a bit difficult to research. How can I solve this... I have been searching for too long now.
> 
> Please help...
> 
> ​
> 
> Testing config if necessary:
> 
> ```
> {
>   "mdns": { "interface": "192.168.0.10" },
>   "bridge": {
>     "name": "MyHomebridge",
>     "username": "BB:21:1B:B3:AB:BA",
>     "port": 51820,
>     "pin": "439-56-562"
>   },
>   "accessories": [
> 		{
>          "accessory": "StatefulDummySwitch",
>          "name": "My Switch 1"
>         }
>   ],
> 
>   "platforms": [
>   ]
> }
> ```

**Comment by Supereg** [comment]
I'm going to bed right now, try to reach back tomorrow with some further guidance to investigate the issue.

**Comment by xBotRaid** [comment]
> I'm going to bed right now, try to reach back tomorrow with some further guidance to investigate the issue.

Thanks alot! Wish you a nice day!

**Comment by Supereg** [comment]
Just adding some more context for potential help from other people.

> @Supereg (running Win10)
> Still got following error with v1.0.3-beta4 [while loading](https://imgur.com/24LAVhP) and following error [after waiting](https://imgur.com/6HIKycb). While having absolutely no response in the logs and no _hap._tcp entry in the Bonjour Browser.

**Comment by donavanbecker** [comment]
@xBotRaid have you tried resetting homebridge pairing in the config ui?

**Comment by xBotRaid** [comment]
> @xBotRaid have you tried resetting homebridge pairing in the config ui?

Do you mean the "Reset Homebridge" option [shown here](https://imgur.com/a/8K2Le0g)?
I just tried that, sadly didn't change much.

**Comment by donavanbecker** [comment]
> > @xBotRaid have you tried resetting homebridge pairing in the config ui?
> 
> 
> 
> Do you mean the "Reset Homebridge" option [shown here](https://imgur.com/a/8K2Le0g)?
> 
> I just tried that, sadly didn't change much.

Yes,
So still not seeing bridge in home app?

**Comment by xBotRaid** [comment]
Yes unfortunately, tried now with the QR-Code as well as the code on two devices

**Comment by oznu** [comment]
Ensure you have allowed Node.js through the firewall. You could also try recreating the service:

```
hb-service uninstall 
hb-service install
```

**Comment by domic** [comment]
I am having the same issue as @xBotRaid with the exception of usage Config UI.

The HB was working perfectly until yesterday, where all HB accessories including the bridge in HomeKit started saying "No response". I updated the bridge to 1.0.2, then to 1.0.3, but still I'm not able to pair the HB with HK.

I tried the procedure mentioned in https://github.com/homebridge/homebridge/issues/2538#issuecomment-620874778.

My config is below:

```json
{
  "bridge": {
    "name": "HomeBridge",
    "username": "****",
    "pin": "***-**-***",
    "port": 53459
  },
  "description": "",
  "ports": {
    "start": 52100,
    "end": 52150
  },
  "accessories": [
    {
      "accessory": "GreeHeaterCooler",
      "host": "192.168.68.136",
      "name": "Ložnice Klimatizace",
      "acModel": "Gree V2",
      "acTempSensorShift": 40,
      "updateInterval": 10000
    },
    {
      "accessory": "GreeHeaterCooler",
      "host": "192.168.68.137",
      "name": "Pokoj2 Klimatizace",
      "acModel": "Gree V2",
      "acTempSensorShift": 40,
      "updateInterval": 10000
    },
    {
      "accessory": "GreeHeaterCooler",
      "host": "192.168.68.138",
      "name": "Mia Klimatizace",
      "acModel": "Gree V2",
      "acTempSensorShift": 40,
      "updateInterval": 10000
    }
  ],
  "platforms": [
    {
      "platform": "Tahoma",
      "name": "My TaHoma Box",
      "service": "Connexoon",
      "user": "***",
      "password": "***"
    }
  ]
}
```

When I start homebridge, the QR code is displayed followed by code, and no errors are in logs.

**Comment by armandoi75** [comment]
Hi guys, yesterday I followed another bug but this one is exactly the problem I have.
homebridge installed in a VM (lubuntu) inside Windows 10. In lubuntu I stopped "ufw" and the etherrnet is in bridged mode. From the host machine i can see the homebridge UI on port 8581 and everything is working properly. My problem is the connection between an iphone and homebridge. I'm able to add the hub, the accessories but the are always in "not responding". 
homebridge -V
1.0.3
node -v
v12.16.2
npm -v
6.14.4

**Comment by xBotRaid** [comment]
> Ensure you have allowed Node.js through the firewall. You could also try recreating the service:
> 
> ```
> hb-service uninstall 
> hb-service install
> ```

Checked the firewall, the application node.exe is allowed to accept incoming and outcoming connections for both local and global connections.

**Comment by armandoi75** [comment]
Hi, 
I have an update, looking on internet I see this: https://www.reddit.com/r/homebridge/comments/dvy4gt/no_response_until_i_tap_on_the_tile/
Checking on my installation, the problem looks the same. If I tap one accessory, even if written "not responding" it start to work. Hope this can help in troubleshooting (in the link there is a video with the problem)

**Comment by xBotRaid** [comment]
> Hi,
> I have an update, looking on internet I see this: https://www.reddit.com/r/homebridge/comments/dvy4gt/no_response_until_i_tap_on_the_tile/
> Checking on my installation, the problem looks the same. If I tap one accessory, even if written "not responding" it start to work. Hope this can help in troubleshooting (in the link there is a video with the problem)
> 
> I edit my same post because I found the solution. I was inspired by this: [aarons22/homebridge-bond#50](https://github.com/aarons22/homebridge-bond/issues/50)
> removing the first accessory in the config.json everything started to work again. So I suppose the problem is the plugin I removed "accessory": "Script2".
> Hope can be usefull for some of you ;-)

Thanks for the idea but sadly didn‘t work either, removed the first accessory didn‘t work then added it back in and delted the second one, didn‘t work either. 1.0.4 did not help as well.

**Comment by misanthrophy** [comment]
Same issue here. I went from 0.4.53 to 1.0.4 and after that all home bridge device were unresponsive.

Already tried:

Homebridge restart
Raspberry Pi restart
Router Restart
HomePod and ATV restart
Log out and in from HomeKit on iCloud
changed username, port and pin in config
reset Homebridge with deleting persist/accessories folder and all content
Tried with iPhone and iPad to pair
Rolled back to 0.4.53 (still unable to pair)
Installed 1.0.0 same issue
went back to 1.0.4 same issue

Configured shortly a second Homebridge on my Mac with homebridge 1.0.4 and it worked immediately.

What I "investigated":

QR code in Terminal differs from config-ui-x in the upper left corner

using QR code in upper left corner of config-ui-x results in a longer time to try to connect with homebridge than when I try the code on terminal, there I got the error message no connection possible almost immediately.
Same with adding manually with PIN. No success...

Additionally the devices menu is now empty. But using my freshly installed home bridge with same pin etc. I see there all my devices and I can control them...

how could I fix that issue? :-(

**Comment by misanthrophy** [comment]
Issue is in my case related to the eveatmo Plugin and some characteristics:

https://github.com/skrollme/homebridge-eveatmo/issues/40

Anything that can be done from homebridge side, or only developer/plugin-side to fix this issue?

**Comment by Supereg** [comment]
@misanthrophy It is what it is: Just a warning. Will continue to work as expected.

**Comment by xBotRaid** [comment]
I guess the problem could be that the homebridge connection gets blocked somewhere, the question is just where...
In Win10, what I did to prevent connections being blocked:
- Run homebridge as administrator and allow connections after popup
- Temporarily disable Windows Firewall > Did not work, but I did set up rules for the homebridge port in- and outcoming connections TCP and UPD
- After disabling the firewall, also disabling Avast or any other Virus-Scanner
- Port forwarding not needed, since it's only local
Did I miss something? What else could be blocking it?

Another problem as I read in other forums could be IPv6, but this issue is only documented on linux and raspberry pis. So what do the experts mean? Disable IPv6 in the Network Adapters or what?

Lastly I want to mention, that I had this problem one year ago after I changed my motherboard, therefore the Network Adapter Settings are reset in Windows. Maybe this could also lead to a problem? Since today I have not figured out what the problem was one year ago, it just started working from one day to another without me realizing what the determining factor was (maybe BIOS reset, which leads to Network Adapter Settings reset).

Also commenting on the weird behaviour @armandoi75 described, I remember having these problems too, maybe they are related, or maybe not... 

Sadly his resolution did not work for me.

Thanks, any opinion appreciated, have had this problem for a while now and still got no clue where to look for...

**Comment by TheUglyKorean** [comment]
I've got the same issue with adding my HB to HK.  Just stopped working today.  The accessories still operate in the HB GUI, but the bridge won't add to HK.  HB running on macOS Catalina 10.15.5.  I've tried using a couple different internet connections, turned off firewalls, the works.  I've gone as far as wiping everything and installing a pure vanilla HB instance and it still won't add.

**Comment by Supereg** [comment]
Would you mind trying to reinstall the latest version of homebridge (also if you already have it installed). It's gonna pull in some minor updates made to some dependencies.
Would be great to check if that changes anything for you.

**Comment by TheUglyKorean** [comment]
> Would you mind trying to reinstall the latest version of homebridge (also if you already have it installed). It's gonna pull in some minor updates made to some dependencies.
> Would be great to check if that changes anything for you.

I nuked it all including node and NPM.  After reinstalling I'm now running:
HB: 1.0.4
Node: 12.16.3
NPM: 6.14.4

**Comment by TheUglyKorean** [comment]
I figured it out.  My VPN is running as a service and has been perfect for years.  Suddenly the "allow LAN traffic" functionality has stopped working.  It was blocking all my LAN in/out.  What a waste.

**Comment by ssllii** [comment]
I am encountering the same issue.  I had a 3-year setup that entered some weird problem after I updated one plug-in.
Tomorrow, I did the complete fresh installation:

Raspbian GNU/Linux Buster(10)
Node.js. v12.16.3
npm. v6.14.5
homebridge v1.0.4

I had only one very simple plug-in, but "HOME" still came back with "Accessory not found".

With my old setup that I did 3-year ago, I had to disable IPv6.  Will try that next.

**Comment by ssllii** [comment]
added ipv6.disable=1 to /boot/cmdline.txt
reboot
Wala! That did the trick.  Successfully scanned the QR code to add homebridge to HOME, and even the simple device showed up and I was able to control it.
Seems like the old ipv6 issue is still not fixed, refer to https://github.com/homebridge/homebridge/issues/607

**Comment by xBotRaid** [comment]
> added ipv6.disable=1 to /boot/cmdline.txt
> reboot
> Wala! That did the trick. Successfully scanned the QR code to add homebridge to HOME, and even the simple device showed up and I was able to control it.
> Seems like the old ipv6 issue is still not fixed, refer to #607
Nice that this worked for you!

I saw this resolution too... But as it seems you are running Linux, could this approach also work on Win10? And what would I have to do?

@Supereg I just updated my plugins and reinstalled homebridge to latest and yes some dependecies were installed, but did not solve the issue... 

Thanks any help appreciated!

**Comment by xBotRaid** [comment]
@Supereg 
What do you think about the idea of disabling ipv6 on Win10? Could this be related to my issue?
I saw many forums suggesting this for Linux, but not one post for Win10.
Also Microsoft does not recommend disabling ipv6, but it seems to be possible...

Should I give it a try and if how?

Thanks

**Comment by scotteby** [comment]
@xBotRaid Just went through this same exercise today with my windows installation. I had the same problem and was able to get it working but I'm not sure what the fix was as I reinstalled Homebridge with a new pin, in addition to adjusting some of my AP settings such as Enable IGMP snooping and Enabling multicast.

Since you mentioned you can't see the _hap._tcp entry in the Bonjour Browser, I would take another look at your wireless network settings. Have you tried connecting from both 2.4 Ghz and 5 Ghz wireless networks as a test? I'm curious what router and/or access points you are using? 

Another thing I did to troubleshoot this was to use Wireshark on the Windows machine to make sure I could see the requests coming in from the iphone on the homebridge port.

I can tell you that I did not need to disable ipv6 on my windows machine.

**Comment by xBotRaid** [comment]
> @xBotRaid Just went through this same exercise today with my windows installation. I had the same problem and was able to get it working but I'm not sure what the fix was as I reinstalled Homebridge with a new pin, in addition to adjusting some of my AP settings such as Enable IGMP snooping and Enabling multicast.
> 
> Since you mentioned you can't see the _hap._tcp entry in the Bonjour Browser, I would take another look at your wireless network settings. Have you tried connecting from both 2.4 Ghz and 5 Ghz wireless networks as a test? I'm curious what router and/or access points you are using?
> 
> Another thing I did to troubleshoot this was to use Wireshark on the Windows machine to make sure I could see the requests coming in from the iphone on the homebridge port.
> 
> I can tell you that I did not need to disable ipv6 on my windows machine.

So firstly nice that you resolve the issuse.
Now for the record, I do not have a Wireless Card on my Win10 Machine, it is directly connected via the Gigabyte Motherboards Ethernet Port to a DIR-860L D-Link router, wich acts as an AP to my main router a [Wingo Internet Box](https://www.tuxone.ch/2015/06/what-you-see-is-what-you-get.html) (Router by our ISP here in Switzerland).

And regarding Wireshark, what did you search for?

**Comment by scotteby** [comment]
In the wireshark filter, I had something like src.ip=="Iphone IP address" and tcp.port=="Homebridge Port"

I don't have a wireless card in the Windows machine here either. I was referring to the wireless settings in your router. You might want to look at the settings in the D-LINK and see if multicast is enabled.

I think you did say that you turned off the firewall and antivirus software on the windows machine for now?

**Comment by scotteby** [comment]
What do you see when you run this from the windows command line:

netstat -na | grep 51826 (port for Homebridge)

I just noticed you have that mdns entry in your config. Do you remember why you needed to add that in there? Do you have multiple network adapters?

**Comment by xBotRaid** [comment]
So I again disabled the firewall and antivirus. Checked router for multicast, is enabled.
When filtering the port in wireshark I see no traffic. Also not when loading the Bonjour Discovery App.

„netstat -na | grep 51821“ returned a command not found error

I added that mdns entry because of a forum post that recommended it. But I have, since Supereg recommended, removed it.

**Comment by scotteby** [comment]
Have you tried disabling all the extra network adapters? 

That command was not the right one for windows. Try:
netstat -na | find "51821"

**Comment by xBotRaid** [comment]
> Have you tried disabling all the extra network adapters?
> 
> That command was not the right one for windows. Try:
> netstat -na | find "51821"

Just disabled them all without the "mdns" in the config file and restarted homebridge. Still no response on port 51821.

netstat did now return following:
  TCP    0.0.0.0:51821          0.0.0.0:0              ABHÖREN
  TCP    [::]:51821             [::]:0                 ABHÖREN

**Comment by xBotRaid** [comment]
Also intersting:
I have AirServer running (AirPlay Reciever for Windows) and all my iDevices flawlessly detect them and connect to it.

**Comment by scotteby** [comment]
That is interesting because that would also use Bonjour services. Can you see those in the Bonjour Browser? https://support.airserver.com/support/solutions/articles/43000534713-what-ports-bonjour-services-are-used-by-airserver-windows-10-desktop-edition-

Have you tried shutting down that service as a test? 

Do you have another windows pc you could install homebridge on?

**Comment by scotteby** [comment]
Also, since you aren't seeing the requests coming in from Wireshark, I would still not rule out your router. I did find this thread where the user has the same router as you and had multicast issues: 

http://forums.dlink.com/index.php?topic=61315.0

He was able to resolve it by putting the DD-WRT firmware on his router. I'm not sure if you are familiar or comfortable doing that, but that would be another option. This looks like the link to the dd-wrt version for your router:

https://dd-wrt.com/support/other-downloads/?path=betas%2F2020%2F05-07-2020-r43078%2Fdlink-dir860l-a1%2F

Another idea would be to borrow or buy another router as another test.

**Comment by xBotRaid** [comment]
> Also, since you aren't seeing the requests coming in from Wireshark, I would still not rule out your router. I did find this thread where the user has the same router as you and had multicast issues:
> 
> http://forums.dlink.com/index.php?topic=61315.0
> 
> He was able to resolve it by putting the DD-WRT firmware on his router. I'm not sure if you are familiar or comfortable doing that, but that would be another option. This looks like the link to the dd-wrt version for your router:
> 
> https://dd-wrt.com/support/other-downloads/?path=betas%2F2020%2F05-07-2020-r43078%2Fdlink-dir860l-a1%2F
> 
> Another idea would be to borrow or buy another router as another test.

Oh wow, thanks for pointing this out!
I installed this open-source firmware and now it works like a charm. And even the cross-device clipboard (iOS to macOS) seems to work again.
Thanks alot, really had this issue for ages but never thought about the router being the problem.

So what I think is the essence of this, is that everytime you can't resolve these kinds of issues it might be closely related to your network setup. You just have to check everything.

**Comment by feld** [comment]
This started happening to me out of the blue without my changing anything with my software which was running in a container. I am truly lost as to what could have happened, but I just want this documented for future reference that the solution was to remove and re-add the accessory but also I was missing the mdns setting from my config:

```
    "mdns": {
        "interface": "192.168.0.XX"
    },
```

After doing that it immediately showed up in `dns-sd -Z _hap._tcp local.` on my Mac. Very strange!

**Comment by qx2** [comment]
I read this entire thread, the easiest and best to solution for this problem on windows 10 is to uncheck (disable) IP v6 on the network adapter that is used to advertise on the network. Do that restart and it all works as expected, even faster than before.
