### ISSUE TITLE
Is this necessary to let apple devices and homebridge in same ip section

### ISSUE THREAD

**Issue by TomatoFryEggs** [homebridge/homebridge#2539]
I installed hb docker on openwrt use host network mode,the docker inherit my router wan ip from optical modem(192.168.1.1),all my others device obtained ip from soft router lan (10.110.0.1),the log sign homebridge can connected to my smart home devices,but I can’t add homebridge to my iphone, that’s  loading all the time.I can visit homebridge ui sites through my iphone.
I installed the least homebridge 1.0.3.

**Comment by oznu** [comment]
Homebridge and HomeKit use the Bonjour/mDNS protocol which won't work across different subnets.

You can get around this using an mDNS reflector service, some routers provide this as a feature.

**Comment by TomatoFryEggs** [comment]
> Homebridge and HomeKit use the Bonjour/mDNS protocol which won't work across different subnets.
> 
> You can get around this using an mDNS reflector service, some routers even provide this as a feature.

In addition,how could I set docker ip in Lan ip section(10.110.0.x).

**Comment by TomatoFryEggs** [comment]
macvlan could solve it.
