### ISSUE TITLE
Long Home app refresh when device is offline

### ISSUE THREAD

**Issue by OwlBawl** [homebridge/homebridge#2543]
**Describe The Bug: long time (few seconds) load of Home App on IOS if device if Unreachable / Offline

**To Reproduce: When power off with classic wall switch my Philips Ceiling Lamp (using plugin - Homebridge Mi Philips Light)

**Expected behavior: send "offline" status without refresh (waiting)? or maybe set to "off"?

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 12.16.2
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.0.3
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by NorthernMan54** [comment]
Long load time issues are a plugin design issue, please raise an issue against the plugin.
