### ISSUE TITLE
old Homebridge  session

### ISSUE THREAD

**Issue by marcgrc** [homebridge/homebridge#2544]
**Describe Your Problem:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by marcgrc** [comment]
Hi everyone
I installed hombridge with backup from the previous UI, everything works but if I type homebridge -I it is as if I saw the old session telling me
[2020-4-29 23:35:43] config.json (/home/pi/.homebridge/config.json) not found.
can I delete defined the old session?

**Comment by oznu** [comment]
Homebridge runs as a background service so you don't need to start it manually like that. When you do it looks for the config in the default location, but chances are, if you followed the wiki instructions, it's located at `/var/lib/homebridge/config.json`.

**Comment by marcgrc** [comment]
Thank you 
I don’t change nothing is it ok ?

**Comment by codyc1515** [comment]
Yeah you don't need to do anything. Just configure it with the web ui.
