### ISSUE TITLE
plugins stopped working, for example loxone-ws

### ISSUE THREAD

**Issue by skinc0ffin** [homebridge/homebridge#2545]
Hello,

After yesterday's upgrade I am experiencing an error with multiple plugins, but my main request is that the loxone-ws can not log in into my loxone miniserver, which worked before.
os: ubuntu server 18.04 LTS

the log shows:
```
AbstractItem (/usr/lib/node_modules/homebridge-loxone-ws-adv/items/AbstractItem.js:22:25)
    at PushbuttonItem.SwitchItem (/usr/lib/node_modules/homebridge-loxone-ws-adv/items/SwitchItem.js:12:23)
    at new PushbuttonItem (/usr/lib/node_modules/homebridge-loxone-ws-adv/items/PushbuttonItem.js:6:27)
    at exports.Factory.parseSitemap (/usr/lib/node_modules/homebridge-loxone-ws-adv/libs/ItemFactory.js:66:29)
    at Request._callback (/usr/lib/node_modules/homebridge-loxone-ws-adv/index.js:88:38)
    at Request.self.callback (/usr/lib/node_modules/homebridge-loxone-ws-adv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-loxone-ws-adv/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-loxone-ws-adv/node_modules/request/request.js:1076:12)
[4/30/2020, 10:51:41] Got SIGTERM, shutting down Homebridge...
```

config.json:

{
    "bridge": {
        "name": "MyHome",
        "username": "0E:05:CD:57:42:3F",
        "port": 51484,
        "pin": "907-20-397"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "LoxoneWs",
            "name": "Loxone",
            "host": "10.0.0.10",
            "port": "80",
            "username": "username",
            "password": "password"
        }
    ]
}

**Comment by Cardo1** [comment]
Most of my installed plugins break on update from 1.0.3 to 1.0.4. Only the Ring plugin seems to survive. Reverting back to 1.0.3 fixed it.

**Comment by FlyingKiwiJosh** [comment]
@Cardo1  how do you roll back to vs 1.0.3. It has all but broke my homebridge. I can no longer get it to add to homekit

**Comment by Cardo1** [comment]
> @Cardo1 how do you roll back to vs 1.0.3. It has all but broke my homebridge. I can no longer get it to add to homekit

npm install -g --unsafe-perm homebridge@1.0.3

Adding @ and a version number to the package name tells it to install that version.

**Comment by FlyingKiwiJosh** [comment]
Thanks. Thought it might help but alas still cannot add homebridge to HomeKit.

**Comment by Supereg** [comment]
@skinc0ffin the actual error message seems to be cut off. Would be great if you could supply the complete error message so we can investigate that.

@Cardo1 @FlyingKiwiJosh It would be great if you could actually report what plugins break and paste the error appearing in the log messages, so we can actually fix those problems.

@FlyingKiwiJosh what do you mean when saying "cannot add to HomeKit" what errors are shown (in the Home App or in the homebridge log). What plugins do you have currently configured.

**Comment by Supereg** [comment]
@skinc0ffin it seems that his is actually a problem which needs to be fixed in homebridge-loxone-ws plugin itself, see https://github.com/Sroose/homebridge-loxone-ws/issues/51

**Comment by FlyingKiwiJosh** [comment]
> @skinc0ffin the actual error message seems to be cut off. Would be great if you could supply the complete error message so we can investigate that.
> 
> @Cardo1 @FlyingKiwiJosh It would be great if you could actually report what plugins break and paste the error appearing in the log messages, so we can actually fix those problems.
> 
> @FlyingKiwiJosh what do you mean when saying "cannot add to HomeKit" what errors are shown (in the Home App or in the homebridge log). What plugins do you have currently configured.

Hi. I have narrowed down that the issue is caused by a windows update. It seems to not be allowing my devices to see homebridge. However homebridge can control the accessories fine within the web interface. So working on rolling back the update, but that is being a pain. Sigh

**Comment by skinc0ffin** [comment]
@FlyingKiwiJosh 
Thank you very much for your reply. The log is just looping what I've pasted here, so nothing else that I can show.
@Supereg 
Thank you too! I saw that you have replied at the plugin's site the bug. I guess I should continue there. Thank for the help again!

Closing the bug.

**Comment by skinc0ffin** [comment]
i rolled back, and everything works like charm. i think i’ll stay with 0.4...

**Comment by Cardo1** [comment]
> @Cardo1 @FlyingKiwiJosh It would be great if you could actually report what plugins break and paste the error appearing in the log messages, so we can actually fix those problems.

I updated to 1.0.4 again and this time it all worked.  ??  Must've glitched when I updated it the first time (I had last updated a few weeks ago, so jumped a few versions?)
