### ISSUE TITLE
razberry Zwave

### ISSUE THREAD

**Issue by droudrou22** [homebridge/homebridge#2546]
hello, i have a raspberry 3b and a razberry card.  I tried to install the zwave network but I only got error codes.  can i operate my card?  I work today with jeedom and the zwave network with the razberry card works very well.  thank you

**Comment by codyc1515** [comment]
You will need to the post the errors here so that people can understand.

**Comment by Pltnorwich** [comment]
Hi, I also have an issue with zwave (razzberry uzb1) 

Ive tried different combinations of pw and local login.

To access the wave from my browser i have to enter the ID/Username together then the password.

[5/5/2020, 18:54:08] Loading 2 platforms...
[5/5/2020, 18:54:08] [Config] Initializing config platform...
[5/5/2020, 18:54:08] [Config] Running in Service Mode
[5/5/2020, 18:54:08] [ZWayServer] Initializing ZWayServer platform...
[5/5/2020, 18:54:08] [ZWayServer] ERROR: Request failed! Error code undefined. Check the URL in config.json and ensure that the URL can be reached from this system!

   "bridge": {
        "name": "Homebridge B976",
        "username": "0E:25:4B:90:B9:76",
        "port": 51510,
        "pin": "XXX-64-XXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "ZWayServer",
            "url": "http:192.168.1.242:8083/",
            "login": "XXXX/admin",
            "password": "XXXXX-pumrik-XXXXX?"
        }
    ]
}
