### ISSUE TITLE
Problem with shutting down

### ISSUE THREAD

**Issue by paha2209** [homebridge/homebridge#2550]
Hello! I am sure it is a simple question, but I would much appreciate your help. I installed Homebridge on my Macbook. When I close it, the connection in Homekit goes "no response" with the accessories. Have I missed something? Please help me.

**Comment by donavanbecker** [comment]
homebridge needs the MacBook to be on to be able to keep the connection with HomeKit. you will either have to leave your MacBook on or get a raspberry pi and install the homebridge image on it.

**Comment by NorthernMan54** [comment]
You need to tell your Mac not to go sleep when you close the lid or are not using it.

Best approach is to buy a RaspberryPI and run it there.
