### ISSUE TITLE
Breaking change `identify` event on PlatformAccessory

### ISSUE THREAD

**Issue by ebaauw** [homebridge/homebridge#2551]
**Describe The Bug:**

The signature of the `identify` event from `PlatformAccessory` has changed.  I think with the refactor of Homebridge to typescript.

The event used to be emitted as:
```
this.emit('identify', paired, callback);
```
but now it's:
https://github.com/homebridge/homebridge/blob/736b3fac6d8ebbb75ff56d917a8679d1d8229a4f/src/platformAccessory.ts#L85
The `paired` parameter is missing.

This causes a `TypeError` for (dynamic platform) plugins calling the `callback` as second argument, see https://github.com/ebaauw/homebridge-zp/issues/134.

**To Reproduce:**

Press ID in Eve, or pair the accessory in Home.

**Expected behavior:**

Backwards compatibility or explicitly documented as breaking change.

**Environment:**

* **Node.js Version**: v12.16.3
* **NPM Version**: v6.14.4
* **Homebridge Version**: v1.0.3

**Comment by Supereg** [comment]
Thanks for noticing, was corrected in https://github.com/homebridge/homebridge/commit/cfe4d2ea0a5b14ae5247148876a41b4503248b77.

Is currently published as homebridge@1.0.5-beta.1.

If you want to keep backwards compatibility with your homebridge-lib plugin (for homebridge instances running a version < 1.0.0) you may want revert to still calling that callback.
