### ISSUE TITLE
Dont work this plugin

### ISSUE THREAD

**Issue by sergoo-lbt** [homebridge/homebridge#2552]
Updated homebridge to version 1.0.0.the Homebridge g-On Alice plugin Doesn't work. Homebridge doesn't start.

**Comment by oznu** [comment]
The plugin seems to be doing non-standard things outside what Homebridge would expect a plugin to do.

https://github.com/G-On-dev/homebridge-g-on-alice/blob/master/lib/parse/Accessory.js#L22

@Supereg thoughts? There are a couple people commenting on the a related issue on this plugins GitHub page.

https://github.com/G-On-dev/homebridge-g-on-alice/issues/9

**Comment by oznu** [comment]
This will require fixing in the plugin as it makes use of HAP insecure mode which had breaking changes in 1.0.0.
