### ISSUE TITLE
send EHOSTUNREACH Error on 1.04

### ISSUE THREAD

**Issue by macjeff** [homebridge/homebridge#2554]
Was running 1.0, 1.01, 102, 1.03 just fine.  Installed 1.04 I think yesterday.  Just looked and homebridge said PROCESS COMPLETED  (no longer running) with this on the screen.   No time stamp so not sure exactly when it stopped.  I started it again and did a couple things and its working so no idea what actually crashed it unless its a bug.

send EHOSTUNREACH

Error: send EHOSTUNREACH 224.0.0.251:5353
    at doSend (dgram.js:681:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:313:12)
    at afterDns (dgram.js:627:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

**Comment by macjeff** [comment]
[5/2/2020, 3:25:53 PM] Homebridge is running on port 51840.
[5/3/2020, 4:15:57 AM] Error: send EHOSTUNREACH 224.0.0.251:5353
    at doSend (dgram.js:681:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:313:12)
    at afterDns (dgram.js:627:5)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
[5/3/2020, 4:15:57 AM] Got SIGTERM, shutting down Homebridge...
logout

**Comment by macjeff** [comment]
I found I can ping 224.0.0.251 but not port 5353.

I did some more research.....

I run this on OS X in terminal on older version of OS X like 10.9 since its an old machine I am re-purposing ..... 224.0.0.251 is the multicast IP address and port 5353 and is used by mDNS to advertise the IP address of the raspberry pi.  So OS X could be causing the issue.

On another forum they pointed me to add this command but I think that means on your end?  Or someway to get around the check for Raspberry Pi.  

firewall-cmd --zone=public --add-port=5353/udp --permanent

Also one other thing.  I also upgrade to latest NodeJS 14.1.0 from 12.16.3 at the same time when I went to 1.04 so that could be it but really thinking this issue is something with the port 5353

**Comment by macjeff** [comment]
Update- ran 24 hours with no problems on 1.03.  

I think the MDNS fix in 1.04 is causing this issue.

Now going back to 1.04 but downgrading NodeJS back to previous version (since I upgrade to NodeJS 14.1 the same time I did 1.04).  Now wait another 24 hours.

**Comment by Zer0x00** [comment]
I have the same problem since upgrading to 1.04.

**Comment by macjeff** [comment]
Going back to either nodeJS v14.0.0 or 12.6.3 has fixed the problem.   So went back to 14.1.0 just to verify I still get the crash.   Not sure where to report bugs with 14.1.0 if thats it.

**Comment by macjeff** [comment]
> I have the same problem since upgrading to 1.0.4 on Windows 10.

Zer0x00-  14.0.0 was removed.  I have the mac installer still but wont help you.  Download 12.6.3 from https://nodejs.org/     The mac version installer includes the latest NPM for both 12.6.3 and 14.1.0.  I think 14.1.0 is the issue.    Let me know if your problem goes away for 12.6.3

And also does yours happen overnight also?   So far all the errors have been in middle of the night.

**Comment by macjeff** [comment]
I started an issue with NodeJS.   If any of you have this problem please comment on this issue
https://github.com/nodejs/help/issues/2675
And also report here.   thank you.

**Comment by macjeff** [comment]
of course they dont believe the issue is with NodeJS and basically said it cant be and in a private conversion they basically blamed homebridge.  So I went back to 14.1.0 in hopes it crashes again when it did not in older versions of NodeJS the last few days

**Comment by macjeff** [comment]
Updated to Nodejs 14.2.0.  Now 24 hours and no issues.   I will keep this open until Monday and close if no issues.

**Comment by macjeff** [comment]
NodeJS 14.2.0 has fixed the issue for me.  No problems since installing.
