### ISSUE TITLE
Smart Xiaomi Smart Plug Plug-in Installation

### ISSUE THREAD

**Issue by agtd1989** [homebridge/homebridge#2556]
Hi everyone. I am a newbie here and I really need help. I installed node.js and homebridge without issue. Homebridge is installed in Home app but I cannot add an accessory. Planning to add this device on my Apple Homekit but I always fail:

**Brand:** Xiaomi
**Smart Device:** Smart Plug
**Model Number:** ZNCZ03CM

I changed my config.json and saved it. But everytime I restart homebridge, config.json resets to default and a new file is added in the .homebridge folder. Am I doing plug-in installation wrong?

**Screenshot:**

![image](https://user-images.githubusercontent.com/64782163/80962006-c4420900-8e3e-11ea-8a33-836a811130a8.png)

**Homebridge Logs:** [**Click this link**](https://pastebin.com/FsUSC13G)

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 0E00",
        "username": "0E:FA:8C:2E:0E:00",
        "port": 51763,
        "pin": "463-86-618"
    },
    "accessories": [],
    "platforms": [ 
      "platform" : "XiaomiMiio",
      "name" : "XiaomiMiio",
      "pollChanges": true,
      "pollInterval": 15,
      "searchInterval": 1800,
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

**Environment:**

* **Node.js Version**: v12.16.3
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.0.4
* **Operating System**: Windows
* **Process Supervisor**: hb-service

Looking forward for your help, guys!

**Comment by donavanbecker** [comment]
Hey @agtd1989, how did you install homebridge?

**Comment by agtd1989** [comment]
@donavanbecker installed it via node.js command prompt. Followed what was written in the tutorials for Homebridge - Windows here in github.

**Comment by donavanbecker** [comment]
@agtd1989 perfect. did you install Config UI X?

**Comment by agtd1989** [comment]
@donavanbecker Yep. I installed it.

**Comment by donavanbecker** [comment]
how are you changing your config? in config ui x? or with a text editor? based on your image it looks like a text editor?

**Comment by agtd1989** [comment]
Yeah a text editor. Currently using Visual Studio Code. Is it ok if I directly change it in config ui x?

**Comment by donavanbecker** [comment]
I would recommend trying to change it directly in config ui x. main reason is because it will catch any errors it may see. let me know if you still run into issues.

**Comment by agtd1989** [comment]
Ok will try.

**Comment by donavanbecker** [comment]
> Ok will try.

Did it work?

**Comment by agtd1989** [comment]
Will try later. I reinstalled everything, clean slate. Will let you know once done again.

**Comment by codyc1515** [comment]
Your config file is wrong. Use the below:

{
	"bridge": {
		"name": "Homebridge 0E00",
		"username": "0E:FA:8C:2E:0E:00",
		"port": 51763,
		"pin": "463-86-618"
	},
	"accessories": [],
	"platforms": [{
		"platform": "XiaomiMiio",
		"name": "XiaomiMiio",
		"pollChanges": true,
		"pollInterval": 15,
		"searchInterval": 1800
	}, {
		"name": "Config",
		"port": 8581,
		"platform": "config"
	}]
}

**Comment by agtd1989** [comment]
@codyc1515  Run homebridge and told me that "Device token is hidden, cannot add accessory".

**Comment by agtd1989** [comment]
@codyc1515 I already know the plug’s token but how do I put it in? Thanks.
