### ISSUE TITLE
Help with setting up DNS Server in MACVLAN docker envroirement

### ISSUE THREAD

**Issue by Ferrox85** [homebridge/homebridge#2557]
Is possible to change de DNS setting in a docker container.
Lik domoticz i can change the /etc/resolv.conf to the right dns server (pihole in an other docker container).

My problem now is that my domoticz is in a container, pihole is in a container and i want the hombridge also in a container. It can reach domoticz (cause you can fil that IP in). But it can't update due to no good DNS server (the pi-hole).

Unforntunately it doesn't get the right DNS adress from macvlan.

**Comment by Ferrox85** [comment]
Fixed it with this tutorial: https://blog.oddbit.com/post/2018-03-12-using-docker-macvlan-networks/

**Comment by codyc1515** [comment]
The other way to do this would be to change your gateway to push out the custom PiHole DNS server over DHCP, then override the DNS in PiHole. This means you don't have to customise each device.
