### ISSUE TITLE
local plugins not loading

### ISSUE THREAD

**Issue by MarcBotman** [homebridge/homebridge#2558]
Just after upgrading to 1.0, all my local plugins (homemade on my computer),  refused to load...
They installs correctly but are not loaded by homebridge at run time.
I tried all newest version up to 1.0.4 but it will not work.
Reverting back to previous version, all is fine again...
Is there a new way to install local plugins?
Thanks
Marc

**Comment by NorthernMan54** [comment]
Log messages would help people diagnose the isdue

**Comment by MarcBotman** [comment]
Well... not much to show.... just ignored by homebridge entirely... not even an error message ...
Marc

**Comment by Supereg** [comment]
Please provide details!

How do you install your "local plugins"?
Are they placed in the global installations directory of homebridge (using npm install -g)?
In what exact path are those plugins placed?
If not globally installed, how do you supply the path to homebridge?
Are you using the homebridge command line argument to define this path?

Nobody here has an idea what exactly you are trying to do.

**Comment by MarcBotman** [comment]
Many thanks Andi for your interest.
Server is a Raspberry Pi 3b+. It is loaded with an all fresh Raspbian Buster Lite from a few days ago and "sudo apt-get updated/upgraded".
WiringPi is installed so that I can manage HW pins from CLI, nothing else!
Then npm and homebridge are installed. npm is 6.14.4. homebridge 1.0.4. Homebridge is installed globally as a daemon running as root.
My plugin resides in a directory, user pi and is installed with "sudo npm install -g" run form the plugin directory itself. A symlink is correctly placed in /usr/lib/node_modules.
restarting homebridge, reboot or whatever, the plugin is not loaded by homebridge.
So I downgraded homebridge to 0.4.53 with "sudo npm install -g --unsafe-perm homebridge@0.4.53" and them my plugin magically appears, is loaded and running fine.
Upgrading again homebridge, my plugin disappear.... Dowgrading, my plugin comes back...
I am fine with 0.4.53 but I thought interesting to let you know...
homebridge is run with following options: HOMEBRIDGE_OPTS=-C -I -U "/var/lib/homebridge"
I attach my installation logs..
[install-homebridge.txt](https://github.com/homebridge/homebridge/files/4592286/install-homebridge.txt)
[install-service.txt](https://github.com/homebridge/homebridge/files/4592303/install-service.txt)

Marc

**Comment by Supereg** [comment]
And there is absolutely no log messages outputted at Homebridge start up?
I would be great to check some of the structure of your plugin. Is it hosted on GitHub somewhere so we can have a look at the source?
In any case, supplying  the log message of the homebridge startup would help very much

**Comment by MarcBotman** [comment]
Thanks again Andi,
My plugin is a customised/simplified version of the MForge homebridge-garage-gate-opener plugin which I thank very much here for providing it. So nothing special about it. I attach the (very  short) source below, it exist only on my computer for now until it is completely implemented.
I attach also the log of the existing system with homebridge 0.4.53.  The log with homebridge 1.0.4 is the same but the line "Loaded plugin x" is not there... no error listed whatsoever (other than my accessory not finding the plugin).
I could rerun it on another raspberry (I need to keep my current system running as is...) if necessary but it could take a few days...
Marc
[garage.txt](https://github.com/homebridge/homebridge/files/4598121/garage.txt)
[log.txt](https://github.com/homebridge/homebridge/files/4598142/log.txt)
[package.txt](https://github.com/homebridge/homebridge/files/4598171/package.txt)

**Comment by Supereg** [comment]
Ah I see. There is a convention that homebridge plugins need to be named like `homebridge-*` (so for example `homebridge-bfirm-garage` at least that is what the current version of homebridge enforces. I thought his is what it always has been.
For now adjusting the name of your plugin should make it load again.
We will investigate why the behavior changed (why the old version seemingly didn't enforce that) and if we are going to do something about that.

ping @oznu

**Comment by MarcBotman** [comment]
All is clear now. I thought the rule was for published item only. I can see the rationale for them; for the private, local ones, it is less so...
Many thanks Andi for helping me on this so nicely. I t is very appreciated.
This homebridge is a great thing!
Marc
