### ISSUE TITLE
Multiple Plugins with BLE connections

### ISSUE THREAD

**Issue by jannisberry** [homebridge/homebridge#2562]
Hi,
I have a Question about the Bluetooth functionallity within Homebridge.
I have 2 BLE Hygrothermographs made by Xiaomi, they are connected through the Homebridge Mi Hygrothermograph Plugin. I now aquired a Plant Sensor which is made by VegTrug but is compatible with the Xiaomi Mi app and i want to use the Homebridge Mi Flora Filtered Plugin. This is on the same RaspberryPi. In the Log it only starts scanning for the two Hygrothermographs from the Plugin i installed first and the 2nd Plugin just never starts scanning as if it is in a queue that is always occupied by the first Plugin. Am i doing something wrong or is it just not intended to have multiple BLE Plugins in use?

Thanks in advance

**Comment by codyc1515** [comment]
You may want to take a read of the following: https://github.com/hannseman/homebridge-mi-hygrothermograph#multiple-sensors

**Comment by jannisberry** [comment]
@codyc1515 you Are Right for multiple of the same Type of Sensors and I actually rum 2 if them but the Plant Monitor I want to add is not compatible with this Plugin and I need another Plugin for this but the other Plugin does not want to search for the Plant monitor. I think it is a Problem with the occupation of the BLE service

**Comment by esgie** [comment]
Yeah, as far as I understood these flora sticks require sending some packet on initialization first and then keep connection alive.
Meanwhile hygrothermograph plugin seem to reset ble connection and breaks above process before any value read is possible.
The issue should be discussed with the plugins’ developers I guess, in particular the developer of hygrothermograph plugin, as hygrothermographs and flora sticks utilize similiar protocol, there are some code for mi flora in the code already and adding stick to the config  as it was a hygrothermograph results in some succeful communication, so the unified plugin for both of those device types might be just around the corner.
Anyway, implementing some fix for the interfering bluetooth plugins - I mean in general, as it is very common situation when it comes to bluetooth devices - would be really appreciated. There is also already a bluetooth range extender/gateway plugin available in the wild, I am willing to test it soon using some rpi zeros (which are pretty problematic as I am failing to expose more than 2 ble devices per rpi to homekit succefully, and no more than one device in total in some cases.) to pass the readings so they can be still processed by my main instance.
