### ISSUE TITLE
Enhancement: Enable “ButtonText” option for mutable array’s in config.schema.json

### ISSUE THREAD

**Issue by newmans99** [homebridge/homebridge#2563]
In the config.schema.json file it would be helpful to support a Button Text entity to change the default “ADD TO {arrayname}” to something else.

For example...
"schema": {
    "type": "object",
    "properties": {
      "calendars":{
        "title": "Calendars",
        “buttonText”:”Add a new calendar”,
        "type": "array",
        "orderable": false,
        "required": true,
        "description": "Add a calendar configuration.",
.... 

This would change the button from “ADD TO CALENDARS” to “Add a new calendar”.

**Environment:**

* **Node.js Version**: All supported
* **NPM Version**: All supported
* **Homebridge Version**: 1.x+
* **Operating System**: All supported
* **Process Supervisor**: N/A

**Comment by NorthernMan54** [comment]
This makes no sense, did you post to the correct repository?

**Comment by donavanbecker** [comment]
> This makes no sense, did you post to the correct repository?

This is from discord, but I think it should go to config ui x instead of homebridge. Am I correct @oznu ?

**Comment by newmans99** [comment]
Yes. Wrong repository. I will move it. Sorry.

**Comment by donavanbecker** [comment]
> Yes. Wrong repository. I will move it. Sorry.

Your good @newmans99 ! Thanks!
