### ISSUE TITLE
Error: attempt to register an accessory that isn't PlatformAccessory!

### ISSUE THREAD

**Issue by beele** [homebridge/homebridge#2572]
I'm updating my plugin to support the latest version of Homebridge.
On my mac everything works fine, but on my existing Hombridge installation (RBPI) things go south.

When starting I get: 
Error: homebridge-unifi-protect-camera-motion attempt to register an accessory that isn't PlatformAccessory!

In the Homebridge source:
https://github.com/homebridge/homebridge/blob/736b3fac6d8ebbb75ff56d917a8679d1d8229a4f/src/api.ts#L276

I need to remove the camera's accessories and add them again for them to work.
If I comment the check I can add the camera's and they work (I tried deleting the cache/persist folder to no avail)

My code is an adjusted sample from https://www.npmjs.com/package/homebridge-camera-ffmpeg

My code: 
https://github.com/beele/homebridge-unifi-protect-camera-motion/blob/37e5e706ff5b81690de3cef015eefd0bd9636500/src/unifi-protect-motion-platform.ts#L70

Where it is clear I am instantiating the correct type.
I've added some extra instanceof checks in my code and it always shows true: 
`console.log('Instance of PlatformAccessory: ' + ((cameraAccessory instanceof PlatformAccessory) ? 'true' : 'false'));`
but the actual call in the Homebridge source keeps failing. 
Any ideas?

Both dev mac and my rbpi are running the latest homebridge version and node 12.16.3
Clearing persist/accessories folder does not help either

**Comment by oznu** [comment]
Try use this instead:

```ts
const cameraAccessory = new this.api.PlatformAccessory(camera.name, uuid, Categories.CAMERA);
```

You should only import homebridge for Typings and Enums.

Also beware we are removing the non-type exports from Homebridge in the next release.

https://github.com/homebridge/homebridge/blob/beta/CHANGELOG.md#for-developers

**Comment by beele** [comment]
Thx, that fixed the issue! 
Also thx for the heads up!
