### ISSUE TITLE
Error or Intentional - limits to hap-nodejs version in package.json

### ISSUE THREAD

**Issue by jvmahon** [homebridge/homebridge#2573]
I wasn't sure if this was a typo or not, but package.json limits hap-nodejs to one specific version in the dependencies section, i.e.,

`````
"hap-nodejs": "0.6.11"
`````

Should it have been ...
`````
"hap-nodejs": ">=0.6.11"
`````

or even
`````
"hap-nodejs": ">=0.7.3"
`````

The hap-nodejs site indicates a major (10x) performance improvement when doing crypto and other functions, so unless there's an incompatibility problem, it seems advantageous to allow this later version.

**Comment by oznu** [comment]
It's currently in beta testing:

https://github.com/homebridge/homebridge/blob/beta/CHANGELOG.md#next

**Comment by jvmahon** [comment]
Thanks. That addresses the point I raised so I'll close this issue.
