### ISSUE TITLE
Homebridge Version 1.04 couldn't find zmq

### ISSUE THREAD

**Issue by BUMPRW** [homebridge/homebridge#2574]
**Describe The Bug:**
Homebridge 1.04 would not load because it didn't find zmq

**To Reproduce:**
I was just upgrading as I have done for years, only difference is that I did it from your web version versus a terminal

**Expected behavior:**
Server should have started, but I checked the log and saw one zmq error after another

[**Logs:**]() too late deleted it last night unintentionally, but I have the fix.  I just put a zmq alias every place there should be one.  My zmq is located in /Users/_my-name_/.npm-global/lib/node_modules/zmq-3.0/zmq-3.0.js  . . . I just made an alias of the js file and put it wherever the errors said

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment]
Homebridge doesn't use zmq, it may have been a plugin or something else.

Either way, thanks for reporting your solution, I'm sure someone else may find it useful.
