### ISSUE TITLE
Working with hap-nodejs

### ISSUE THREAD

**Issue by jvmahon** [homebridge/homebridge#2575]
The package.json file for my plugin currently includes hap-nodejs as one of its dependencies.

When I start homebridge (the 1.0.4 beta), I now get the message: 
`````
[5/11/2020, 3:13:54 PM] The plugin "homebridge-homeseer4" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!
`````

This makes sense as it seems it should be unnecessary to include hap-nodejs when homebridge already installs it. However, in one of my plugin files, I do need to access the Characteristic and Service variables provided by hap-nodejs, so I include the following lines:
`````
var Characteristic = require("hap-nodejs").Characteristic;
var Service = require("hap-nodejs").Service;
`````

When hap-nodejs is one of my dependencies, all works fine. However, when I remove them as a dependency, the hap-nodejs module isn't found. I had assumed that node would have some set of paths it followed to get to the module, but that doesn't seem to be the case.

My question - what is the correct way to get to these Characteristic and Service values when hap-nodejs isn't a dependency? Is there something I have to do in the module "require" that I'm missing?

This is on node Version 14.2 on Windows 10.
Thanks

**Comment by grzegorz914** [comment]
U can use this:

```
let Accessory, Characteristic, Service, UUID;


module.exports = homebridge => {
	Accessory = homebridge.platformAccessory;
       Characteristic = homebridge.hap.Characteristic;
       Service = homebridge.hap.Service;
       UUID = homebridge.hap.uuid;
	homebridge.registerPlatform(PLUGIN_NAME, PLATFORM_NAME, denonTvPlatform, true);
};
```

**Comment by jvmahon** [comment]
That worked. Thanks.
