### ISSUE TITLE
Homebridge Error in Installation for Windows 10

### ISSUE THREAD

**Issue by agtd1989** [homebridge/homebridge#2577]
**Describe Your Problem:**
Tried installing homebridge config UI on Windows 10 and got error on this. Somebody help please! Thanks!

[**Logs:**]()
```
C:\Windows\System32>hb-service install
i Installing Homebridge Service
Access is denied.
Error: Command failed: "C:\Users\Admin\.homebridge\nssm.exe" install Homebridge "C:\Program Files\nodejs\node.exe" """C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\dist\bin\hb-service.js""" run -I -U """C:\Users\Admin\.homebridge"""
Access is denied.

```

**Environment:**

* **Node.js Version**: v12.16.3
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.0.4
* **Operating System**: Windows 10

**Comment by nikonratm** [comment]
It says access denied. Are you running the node.js command prompt as administrator as explained in the guide? https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10#step-2-install-homebridge

![](https://user-images.githubusercontent.com/3979615/63936518-51a8ae80-caa3-11e9-8035-12b6ebbb20cf.gif)

**Comment by agtd1989** [comment]
Yep. Run as admin but didn’t work still.

**Comment by nikonratm** [comment]
Did you just try starting over, re-doing all the steps in the guide? Seems like something didn't get setup properly.
