### ISSUE TITLE
can't open Homebridge Config UI X

### ISSUE THREAD

**Issue by TomatoFryEggs** [homebridge/homebridge#2581]
open `http://<xx.xx.xx.xx>:8581`
chrome returns:
`This site can’t be reached10.110.0.11 refused to connect.`
when I execute 
`sudo hb-service start`

returns
```
ℹ Restarting Homebridge Service
ℹ Restarting Homebridge Service...
Running in chroot, ignoring request.
✔ Homebridge Restarted
````

**Comment by oznu** [comment]
> "Running in chroot, ignoring request."

Where are you trying to run this?

**Comment by TomatoFryEggs** [comment]
> > "Running in chroot, ignoring request."
> 
> Where are you trying to run this?

A virtualmachine Deploy APP on Android. 
Ubuntu 16.04

**Comment by oznu** [comment]
hb-service will not work there. It needs a running instance of systemd which you're chroot does not have.

You can start homebridge manually.

https://github.com/homebridge/homebridge#installation-details

**Comment by TomatoFryEggs** [comment]
> hb-service will not work there. It needs a running instance of systemd which you're chroot does not have.
> 
> You can start homebridge manually.
> 
> https://github.com/homebridge/homebridge#installation-details

Gotit.
THX!

**Comment by DilVika** [comment]
Hi, I just dont know how to 'start homebridge manually'. Can you help me with this please?

**Comment by DilVika** [comment]
> > hb-service will not work there. It needs a running instance of systemd which you're chroot does not have.
> > You can start homebridge manually.
> > https://github.com/homebridge/homebridge#installation-details
> 
> Gotit. THX!

Hi, I just dont know how to 'start homebridge manually'. Can you help me with this please?

**Comment by sdgrs546547Q** [comment]
> > > hb-service will not work there. It needs a running instance of systemd which you're chroot does not have.
> > > You can start homebridge manually.
> > > https://github.com/homebridge/homebridge#installation-details
> > 
> > 
> > Gotit. THX!
> 
> Hi, I just dont know how to 'start homebridge manually'. Can you help me with this please?

you have discovered the issue? thanks
