### ISSUE TITLE
Unable to stream cameras > 960px wide on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by shamoon** [homebridge/homebridge#2582]
**Describe The Bug:**

- **Update:** see below, seems streaming is limited to < 960px wide?
- I had originally thought this was a docker issue (see [docker-homebridge#304](https://github.com/oznu/docker-homebridge/issues/304)) but this issue seems present on native Homebridge too.
-  On a hard-wired Ubuntu 20.04 LTS I am unable to stream any cameras when a device is using Wi-Fi or ethernet, the only time it works (and it always does work) is via cellular connection on my iOS device. 
- The problem exists for a plugin I work on ([simplisafe3](https://github.com/nzapponi/homebridge-simplisafe3)) which uses new bridged cameras but same problem with camera-ffmpeg (which uses old platform cameras setup) with a generic input file. 
-  In the logs the stream starts just fine and I am watching ffmpeg output frames.
- Servers running on macOS (and previously RPi) do not seem to have this issue.

**To Reproduce:**

Install native Homebridge as usual on Ubuntu 20.04 LTS, add camera plugin, attempt to stream over wifi or ethernet.

**Expected behavior:**

Video should stream, I just get spinning wheel and eventually "Not Responding"

[**Logs**](https://pastebin.com/eibBpuYA) (no obvious errors, just correctly show plugin spawning ffmpeg & streaming frames)

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:32",
        "port": 51894,
        "pin": "031-45-154"
    },
    "accessories": [
    ],
    "platforms": [
        {
            "name": "SimpliSafe",
            "auth": {
                "username": "xxx",
                "password": "xxx"
            },
            "cameras": true,
            "debug": true,
            "cameraOptions": {
                "ffmpegPath": "/usr/bin/ffmpeg"
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        },
        {
            "cameras": [
                {
                    "name": "Test Stream",
                    "videoConfig": {
                        "source": "-re -i http://docs.evostream.com/sample_content/assets/bun33s.flv",
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
    ]
}
```

**Screenshots:**

If curious, here's a video reproducing: [https://imgur.com/a/iSab781](https://imgur.com/a/iSab781)

**Environment:**

* **Node.js Version**: v12.16.3
* **NPM Version**: v6.14.4
* **Homebridge Version**: v1.1.0
* **Operating System**: Ubuntu Focal Fossa (20.04 LTS)
* **Process Supervisor**: hb-service (issue [also present in docker](https://github.com/oznu/docker-homebridge/issues/304))

Appreciate any help / thoughts.

**Comment by nikonratm** [comment]
I have discovered how to workaround this but I wonder if it points to the underlying issue, it seems you cannot stream video > 960px. If I set the video filter (`-vf`) to use 960:-1 it works fine, anything wider than that I get the spinning wheel of death.

[Here's a video of the issue](https://imgur.com/a/Ruw6r8x), you can see I try with the video with out filtering and it doesnt work, then I change it to 720px wide and it works just fine (later I tested it up to 960px at it works). Is this some kind of undocumented limitation somewhere? Again, seems to work fine on macOS (maybe others). To be clear, my Ubuntu server box has 16GB ram + core i7 so I dont think its a resources issue. This same fix seems to be true for my own plugin as well as camera-ffmpeg.

Huh?!

**Comment by nikonratm** [comment]
🦗
