### ISSUE TITLE
Mirabella Genio

### ISSUE THREAD

**Issue by tomx420** [homebridge/homebridge#2583]
Hi, 
Is there a plug-in I can use for Mirabella Genio (https://mirabellagenio.net.au/ ) products?

**Comment by Olepir** [comment]
You can try Tuya plugins. Also some of devices can be flashed to native HomeKit with Tuya-Convert.

**Comment by tomx420** [comment]
Yes tuya plug-in worked. 
Just added to HA with HomeKit plugin and the iOS home app instantly recognised the devices. 
Thanks.

**Comment by georgysh** [comment]
Guys, can you give a some details which plugin/configuration in particular worked? 
I see more than dosen "...tuya..." plugins in homebridge-config-ui search page...

**Comment by tomx420** [comment]
> Guys, can you give a some details which plugin/configuration in particular worked?
> I see more than dosen "...tuya..." plugins in homebridge-config-ui search page...

Hi, Sorry for the late reply and probably wrong forum. I ended up using Home Assistant (HA) an alternative to HomeBridge. HA allows u to add Tuya platform and integrate all Tuya based smart devices (e.g. smartlife, mirabella genio, laser, mistral etc). You can also add Homekit as an integration to HA. Then just use your Homekit app on iOS to scan the HA code and all the Tuya smart devices will pop-up.
Hope this helps. Cheers!!
