### ISSUE TITLE
HAPType = 'Temperature' limited to 100 °???

### ISSUE THREAD

**Issue by medicus07** [homebridge/homebridge#2584]
Hi there,

it seems to me, that there is a limit for HAPType 'CurrentTemperature'/ 'TargetTemperature' and the accessoryType 'TemperatureSensor'.
I use this sensor type to visualize some photovoltaics data (pv production and current house consumption in W) in the Home App. It is only a workaround because the W is shown in °, but is still very useful.

So is it possible to remove this limit or raise it to 50.000?

Thanks a a lot!

Cheers
Michael

**Comment by NorthernMan54** [comment]
You have to keep within the HomeKit accessory spec, but you can adjust the min and max with setProps - see below for an example

    this.accessory
      .getService(Service.Thermostat)
      .getCharacteristic(Characteristic.CurrentTemperature)
      .setProps({
        minValue: -100, // If you need this, you have major problems!!!!!
        maxValue: 100
      });

**Comment by Supereg** [comment]
As NothernMan already stated you can adjust the Characteristic definition as you like and just raise the maximum or minimum accepted values.
