### ISSUE TITLE
V1.1.0 Loses connection with Homebridge App

### ISSUE THREAD

**Issue by gdotp01** [homebridge/homebridge#2585]
Ive recently updated from V0.4.5.3 to V1.1.0 due to some dependencies. What Im seeing now is that after startup all appears to be working and at some random time later the Home App loses connection to most but not all of the homebridge plugins.  The accessories show 'No response'. A reboot of home bridge fixes again but after a time it stops again. There are no errors showing in the log file.
Node.js Version     v11.9.0 
Npm Version         v6.14.5

Im running 
BlinkCameras    (the reason I updated) 
IFTTT
LinkTapPlatform
HarmonyHub
WeatherPlus
People
OccupancyDelay
DelaySwitch

What is strange is that it is all still working in Homebridge it just dos not link to the App.

**Comment by jplongo** [comment]
+1 Same issue after updating to 1.1.0 and on 
I can reproduce the bug by going in log view or basically outside the main page. 
I have an error message and Homebridge reboot alone to come back de seconds later
![2416CCDC-7332-422B-B703-05C7617BC17E](https://user-images.githubusercontent.com/22789876/82737667-f99d9080-9d32-11ea-8d29-46de46714286.png)

**Comment by nikonratm** [comment]
Neither of you have supplied your config file or log output, which is required as part of the issue template. Without that its hard to know where to start but "No Response" issues are often related to networking issues or a problematic plugin (hence the logs + config requirement).

**Comment by jplongo** [comment]
In my case there is nothing in logs. I just can see the stat log but nothing before. It’s like I ask HomeKit to reboot. And I’ve tried with an empty config file to be sure and same thing.  

I’m using homebridge on a raspberry pi 0W with official raspbian and homebridge. Everything is up to date. 
I only use one plugin to my control my rolling shutter. The plugin is working great. I will try to check proc and sys log to try to find is an error is logged

**Comment by jplongo** [comment]
After some search, I found this error in daemon.log. The `SIGABRT signal(6)` sent could be the reason why homebridge is restarting and it could be a heap size issue. Rolling back from previous version doesn't change anything. I will try to investigate more about this issue this week. But I think a full reinstall of raspbian + Homebridge could quickly solve the issue.
![image](https://user-images.githubusercontent.com/22789876/82788362-9d3c8d00-9e68-11ea-8ecc-1cffd68ff986.png)

**Comment by c-o-m-m-a-n-d-e-r** [comment]
can confirm losing connection to the home app.

Running from Docker (on Synology) with the Plugins: Config UI X, Alexa, KNX, Nuki, Xioami Roborock.

Controlling via Web IF is working fine, also Voice Control via Alexa... 
Nothing special in the Logs (also after Restart)

I know its hard to debug without any Logs. But there is really nothing.

**Comment by xelypse** [comment]
Here exactly the same with RaspberryPi3...

**Comment by Cardo1** [comment]
Double posting from the other, similar thread...

I’ve been struggling with my devices occasionally becoming unresponsive. The issue started around the time Homebridge went to version 1.*, though I also moved my HB instance to an Raspberry Pi from a Mac Mini around the same time. My house has solid walls that block WiFi signals, so I have a few APs dotted around connected via a couple of switches. Sometimes HB would work, other times it wouldn’t. I could always access the Pi through the Config, even if the devices were showing as unresponsive. My usual hub is my HomePod in my kitchen, which can connect to one of two APs. Sometimes I could access the HB devices remotely, other times I couldn’t.

I think I have finally narrowed it down to the way HB now advertises itself, my network’s config and possibly the way the Pi does its networking. In the end, the trick was to disable “IGMP Snooping” on all routers/switches/APs. It appears IGMP Snooping can sometimes break mDNS, especially across different network interfaces on a single device (2.4Ghz/5Ghz/Eth).

I’m probably jinxing it by posting this, but so far so good.

**Comment by gdotp01** [comment]
Sorry its taken me a few days to get back. I can confirm that when it loses connection to the Home App there is nothing in the log file, i can post if you want but it only has the normal status changes in it.

However what I have done is isolate the issue to a single plugin which is the BlinkCameras plugin. If I remove this it remains stable. It looks like something this plugin is doing is causing Homebridge to lose its connection to the Home App but remain working in the background and through the Web UI supplied by Homebridge Config UI X, some sort of unhandled exception ?

**Comment by c-o-m-m-a-n-d-e-r** [comment]
Nope, can't be the only problem or its just a side effect.
I don't using the Blink Plugin.

@Cardo1 : good hint, but i already disabled IGMP Snooping in my Unifi Enviroment.

**Comment by tekbuddha** [comment]
Will add to chorus of issues with 1.1.0. For a long while, I've been running Homebridge in docker with a small set of plugins (harmonyhub, nest-cam, adt-pulse, platform-wemo) which have all worked quite fine and with their configurations untouched. Recently did an upgrade from v1.0.4 to v1.1.0 (along with upgrade to plugins to suit new homebridge release) and have now started experiencing "accessories not responding". To be clear, I get accessories responding from homebridge what seem like a few minutes at a time, then they go into "not responding" mode. A few minutes later, they're responding again.

I started with a completely fresh config, made sure it was a different pin and MAC, then set about re-installing and setting each plugin from scratch. I deleted the old bridge from Home.app, added the new one, and setup all the accessories. No luck. Almost immediately, I began getting the "not responding" status.

So, considering this might be a docker thing, I started the process on a raspberry pi4 (running latest Raspbian and from-source installed node/npm) that I'd just done with docker. Same deal: accessories from homebridge are flapping every few minutes.

I'll also add the experience happens both in Home.app on my iPhone (wifi, obviously) and my MacMine (wired). So with clean installs on two separate devices (one containerized, one not) and wifi/wired apps still misbehaving, this seems to me like something in the latest release is truly amiss.

Hope some of that additional info helps in diagnosis.

**Comment by soumaxetuirk** [comment]
I am having same type of issue after update.
When this happens :
1. Devices don't respond in home App (iOS & OSx).
2. In Config-UI-X 's accessories section becomes empty.
3. No error in log,I can see homebridge reading MQTT messages without error (telemetry updates)
4. STRANGELY homebridge-alexa plugins still works and I can control devices from echo devices. 

 A single restart of homebridge solves the issue always. May be HAP discovery issue ?
Tried "Reset Homebridge Accessory ". No changes made to config after update. 

[accessoriesdump.txt](https://github.com/homebridge/homebridge/files/4703923/accessoriesdump.txt)

[config.json.txt](https://github.com/homebridge/homebridge/files/4703933/config.json.txt)

**Comment by nikonratm** [comment]
There are definitely multiple issues in this thread so hard to comment overall but often when homebridge looks like it’s running but loses its iOS connection it is related to mdns aka bounjour. It’s helpful to investigate this using the appropriate (os-specific) command line tools or for example the Discovery app on macOS.

To the docker user, I just had an epic battle with this too. Ultimately was mdns (related to avahi on Ubuntu in my case).
but ultimately I ended up going with a macvlan setup (my setup is fairly complicated tho)

But with upcoming changes to homebridge mdns implementation (aka HAP-nodejs’s implementation) not sure how things will change...

**Comment by soumaxetuirk** [comment]
thank you.
But why Homebrige-UI-Config-X also becomes blank in "accessories" section?

**Comment by nikonratm** [comment]
@soumaxetuirk Yea that sounds like a different issue. Im guessing your config file is unaffected? One thought, do you have [`Homebridge Insecure Mode / Enable Accessory Control -I`](https://github.com/oznu/homebridge-config-ui-x/wiki/Enabling-Accessory-Control) enabled (its supposed to warn you if you dont but still)?

**Comment by soumaxetuirk** [comment]
Yeah, Insecure mode is enabled.

**Comment by jplongo** [comment]
The issue seems to come from .  With test version the issue has gone. 
I now have a side effect with my accessories but could be the test version. I will try to investigate more on the new issue on my side.

**Comment by jojogrosso** [comment]
I seem to be having similar issues with my devices showing “No Response”. I used to have homebridge hosted on a Windows 10 machine, and recently moved it to my Synology. Ever since then I’ve had to restart daily to get the devices back up and running. 

Hope this tidbit helps.

**Comment by gdotp01** [comment]
There is an issue but for me I can confirm that it was caused by the Blink camera plugin. I suspect other plugins cause a similar issue. I removed Blink and since then it’s worked ever since.

**Comment by xelypse** [comment]
But there are user, who don‘t have the blink plugin and the simular problem. I suppose, that is not the only reason...

**Comment by xelypse** [comment]
> Nope, can't be the only problem or its just a side effect.
> 
> I don't using the Blink Plugin.
> 
> 
> 
> @Cardo1 : good hint, but i already disabled IGMP Snooping in my Unifi Enviroment.
> 
>

**Comment by gdotp01** [comment]
That’s not my point. The point is the Blink plugin is causing the problem for me. I suspect other plugins are having a similar effect.

**Comment by jojogrosso** [comment]
Thanks @gdotp01 
The Blink Plugin was something I just added, and I guess that was causing the problem for me. Off to the Blink issue page!

**Comment by gdotp01** [comment]
> Thanks @gdotp01
> The Blink Plugin was something I just added, and I guess that was causing the problem for me. Off to the Blink issue page!

It’s already logged there. There is something to say it’s fixed but my testing suggests not.

**Comment by Supereg** [comment]
Anyone still experiencing connection issues might have a look at https://github.com/homebridge/homebridge/issues/2619

**Comment by gdotp01** [comment]
I’m not. I’m on 1.1.1 and ditched the Blink camera plugin that seemed to be surfacing the issue for me.
