### ISSUE TITLE
Homebridge on apple time capsule [rooted]

### ISSUE THREAD

**Issue by exrector** [homebridge/homebridge#2586]
good afternoon.  Sorry for the English, but I really appreciate your help in installing.  I was inspired by this article[Link](https://habr.com/ru/post/501404/) .  from which we have root access.  and so we can install packages netBSD.  I do not have sufficient knowledge and I beg you to help me.  If you do root for this article, then you can install the homebridge package on the capsule.  Please, try! please notify me of your experience 🙏🏻🙏🏻🙏🏻

**Comment by oznu** [comment]
If you can install Node.js, you can follow the generic instructions in the README to install Homebridge:

https://github.com/homebridge/homebridge#installation-details
