### ISSUE TITLE
NetBSD 6.0

### ISSUE THREAD

**Issue by exrector** [homebridge/homebridge#2587]
how to install on NetBSD 6.0?

**Comment by joaoofreitas** [comment]
Hello **exrector**!
Basically if you can run _NodeJS_ on it and install all the dependencies needed to run _homebridge_, following the documentation it should work like a charm. 

Clone the repository
Install _npm_, _nodejs_, and other dependencies
And follow the guide. After that send a message to the developers of _homebridge_ and tell them how was the experience in a Unix-Like distribution.

**Comment by oznu** [comment]
The generic installation instructions in the README will work on ant platform Node.js can run on:

https://github.com/homebridge/homebridge#quick-overview
