### ISSUE TITLE
Homebridge plugins do not show up in wife's Home app

### ISSUE THREAD

**Issue by mikesalz** [homebridge/homebridge#2589]
**Describe The Bug:**

My HomeKit setup uses my iCloud account, and I have added my wife as a user.  This setup has worked perfectly for years.  I have several bridges, both physical and virtual.  All work correctly on her iPhone.  Even Home Assistant.  But for some reason, Homebridge does not show up on her phone.  As far as I can tell, I have enabled all permissions in the Home app.  Thoughts?

**To Reproduce:**

**Expected behavior:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**:  1.1.0
* **Homebridge Version**: 1.1.0
* **Operating System**: Synology Docker
* **Process Supervisor**: Synology Docker

**Comment by Olepir** [comment]
I think only an “owner” of a Home can have access to hubs and bridges.

**Comment by mikesalz** [comment]
> I think only an “owner” of a Home can have access to hubs and bridges.

Maybe I wasn't clear in my description.  Not only is the bridge not showing, but none of the accessories are showing either.  That is the real issue.

**Comment by Olepir** [comment]
Try to log out from iCloud on your HomeKit hubs oh your wife phone, restart and log back in.

**Comment by mikesalz** [comment]
Interestingly, I removed her as a guest from my home (in the app, not in real life!) and then added her back.  Homebridge showed up in her Home app temporarily.  Then all the devices went to unresponsive, and a few minutes later the entire bridge disappeared again.

**Comment by mikesalz** [comment]
@oznu - Sorry to pull you into this!  Just wondering if you have any thoughts?

**Comment by Soldiiier** [comment]
You might need to remove from additional users from the home and re-invite them.

See the 'Breaking Change' from v1.0.0
https://github.com/homebridge/homebridge/releases/tag/1.0.0

**Comment by mikesalz** [comment]
Thanks for the suggestion, @Soldiiier.  But I actually already tried that.  See my previous post.  It did work temporarily.  I was able to use all Homebridge devices on her phone.  But shortly afterward they all went unresponsive.  And then the entire bridge disappeared.

**Comment by EjvindHald** [comment]
I also suggest to log out and in again in iCloud. With Homekit this can sometimes invoke some sync, which cannot be invoked in other ways.

**Comment by mafyata** [comment]
I have the same problem. Logout from icloud did not help. Waiting for ios14 and hope they fix it.

**Comment by mikesalz** [comment]
Just for the record, this is now fixed for me.  It was a Homebridge issue; Not iCloud.  I'm not sure which fixed it, but I did both of these under Homebridge Settings:

- Remove All Cached Accessories
- Unpair Bridges / Cameras / TVs / External Accessories
- Reset Homebridge Accessory
