### ISSUE TITLE
getServices asynchronous or with delay?

### ISSUE THREAD

**Issue by merdok** [homebridge/homebridge#2590]
Hi,

so i know that homebridge at some point calls the getServices method for an Accessory to get the required services and that makes sense. But i was wondering if it is possible to delay that call or maybe first leave it empty and send an updated services later to homebridge? 
The background is that i first want to retrieve some data from the device and then based on that data i create the services. 
So i know that i can do that with a platform because the workflow is different there, but is this also somehow possible with the getServices for accessories?

**Comment by oznu** [comment]
You'll need to use a dynamic platform plugin type.

https://developers.homebridge.io/#/api/platform-plugins

**Comment by merdok** [comment]
Ok 👌
