### ISSUE TITLE
mdns.interface no longer works

### ISSUE THREAD

**Issue by tvand** [homebridge/homebridge#2591]
**Describe The Bug:**

I use Homebridge on macOS High Sierra with two network interfaces. With 1.0.2, I needed to add the mdns interface configuration to make it work. Now I updated to 1.1.0 and the mdns limitation somehow stopped working.

**To Reproduce:**
The MDNS announcement (with mdns-diagnostics) looks like this:
```
Homebridge E1A5, Homebridge,  fe80::cd0:e69:5dc1:xxxx:51826
Homebridge E1A5, Homebridge,  fd00::1b:381e:eb64:xxxx:51826
Homebridge E1A5, Homebridge,  172.16.34.4:51826
Homebridge E1A5, Homebridge,  fd00::119a:524a:3b78:xxxx:51826
Homebridge E1A5, Homebridge,  fd00::296a:d477:1e31:xxxx:51826
Homebridge E1A5, Homebridge,  fd00::3562:fcbc:10fb:xxxx:51826
Homebridge E1A5, Homebridge,  fd00::89bd:300c:48cf:xxxx:51826
Homebridge E1A5, Homebridge,  fd00::f1dc:d566:9b78:xxxx:51826
Homebridge E1A5, Homebridge,  fd00::902a:a783:f36:xxxx:51826
Homebridge E1A5, Homebridge,  fd00::1df3:90d2:1d47:xxxx:51826
Homebridge E1A5, Homebridge,  fe80::cc2:8bcd:8602:xxxx:51826
Homebridge E1A5, Homebridge,  172.16.33.1:51826
Homebridge E1A5, Homebridge,  fe80::7f07:be7e:84c9:xxxx:51826
Homebridge E1A5, Homebridge,  fe80::4c3c:a9b2:f2f4:xxxx:51826
```

**Expected behavior:**

My expectation would be one line like:
```
Homebridge E1A5, Homebridge,  172.16.34.4:51826
```

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
    "mdns": {
        "interface": "172.16.34.4"
    },
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.16.3
* **NPM Version**: 6.14.5
* **Homebridge Version**: 1.1.0
* **Operating System**: macOS 10.13.6
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
We are currently working on a module to completely replace the current mdns implementation. It's very much in beta, but you can see if it works for you:

```
sudo npm install -g homebridge@beta
```

If that doesn't work, rollback to 1.0.4 for now until we release `v1.2.0`.

```
sudo npm install -g homebridge@1.0.4
```

**Comment by tvand** [comment]
I needed to go back to 1.0.3 to (almost) get the expected behavior.
```
Homebridge E1A5, Homebridge,  172.16.34.4:51826
Homebridge E1A5, Homebridge,  fe80::cd0:e69:5dc1:xxxx:51826
```
Still the iPhone does not connect. Any hints on how to debug this?

**Comment by JamieBerghmans** [comment]
Couldn't get it to work at all with the current implementation, but the beta worked first try. Thanks!

**Comment by tvand** [comment]
I'm back on 1.1.0

My problem turned out to lie elsewhere. I removed all accessories and platforms and could add the bridge to Homekit then. The I added the components back one by one. Somehow the sprinkler is no longer accepted as an accessory. I'll dig on.

The MDNS stuff is still broken, though.

**Comment by iJaffa** [comment]
I can replicate the mdns issue in both Raspbian Stretch and Oracle Linux 8.2 on a Raspberry Pi Zero and Raspberry Pi 3 respectively.

**Comment by Supereg** [comment]
Anybody still having connection issues or weird stuff happening with the mdns advertisement might check out the latest beta https://github.com/homebridge/homebridge/issues/2619
