### ISSUE TITLE
Homebridge should advertise _http._tcp. Bonjour service

### ISSUE THREAD

**Issue by lilyball** [homebridge/homebridge#2594]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by ebaauw** [comment]
Why?  Native HomeKit devices don't.

Or do you mean the web UI of Homebridge Config UI X?  In that case, better open an issue in that repo.

**Comment by lilyball** [comment]
Sorry I accidentally submitted this before writing up the ticket, hence the lack of description.

I didn’t realize there was a separate repo for that. I’ll file it there.
