### ISSUE TITLE
Why does HB occupy so much RAM?

### ISSUE THREAD

**Issue by Hochiss** [homebridge/homebridge#2600]
Please see attached screenshot:
![docker_HB](https://user-images.githubusercontent.com/36304198/84358621-b4e57680-abc7-11ea-85da-4dee3c9e6dde.png)

HB demands the highest RAM comparing to Django, SQL server, and ubuntu containers (currently all idle).

Could anyone help me to understand or to optimize? 
(only 4 platforms/devices in config.json, works well though) 

**Environment:**

* **Node.js Version**: <v12.16.3>
* **NPM Version**: <6.14.4>
* **Homebridge Version**: <1.0.4>
* **Operating System**: Docker (`cat /proc/version` : Linux version 3.10.105)
* **Process Supervisor**:   Docker 
env:
* **QEMU_ARCH**=x86_64
* **HOME**=/root
* **HOMEBRIDGE_CONFIG_UI**=1
* **HOMEBRIDGE_VERSION**=1.0.4
* **CONFIG_UI_VERSION**=4.19.0

**Comment by Supereg** [comment]
Is the RAM usage with plugins running? I don't know what's a typical homebridge RAM usage (without any plugins or plugins which don't use much RAM).

**Comment by NorthernMan54** [comment]
I'm not sure if comparing complied programs versus an interpreted language is a valid comparison.  The memory requirements of the two are not the same as the nodeJS runtime would be interpreting code in real time versus the complied programs just running.

I looked at my various homebridge environments and they are similar in memory footprints.
