### ISSUE TITLE
Homebridge stopped working

### ISSUE THREAD

**Issue by combi06** [homebridge/homebridge#2602]
I recently updated the Homebridge UI X straight from the Update button and home bridge has stopped working altogether as it did not come back after the restart required post-update. I type in 'homebridge' to start it manually from Terminal but it returns as 'command not found'. I can't access it through localhost:8080 either.

Help is appreciated. Thank you.

**Comment by oznu** [comment]
Logs?

**Comment by jochenpa** [comment]
Hi

I had the same problem. After the update of homebridge-config-ui-x from version 4.22.0 to 4.23.0 my homebridge was deinstalled/removed.

Which log do you need?
