### ISSUE TITLE
I can't see devices added directly to the Apple Home Kit

### ISSUE THREAD

**Issue by Damianeq90** [homebridge/homebridge#2603]
Hi,

Today I bought a Fibaro motion sensor dedicated for the Apple Home Kit, I added it directly to the system using an iPhone.

I use a homebridge with Samsung SmartThings on a daily basis.

This is my first device cooperating and certified for Apple, is there a chance that I would also see this device in HomeBridge?

Sorry for my English.

**Comment by wwhite74** [comment]
it doesn't work that way.
homebridge will only add smarthings to homekit
it won't add homekit to smart things. 


you'll nee to add the motion sensor directly in smart things
https://support.smartthings.com/hc/en-us/articles/204075624-Fibaro-Motion-Sensor
