### ISSUE TITLE
HOMEBRIDGE LOGIN

### ISSUE THREAD

**Issue by VEGATRON3** [homebridge/homebridge#2605]
HOMEBRIDGE.LOCAL  is not working. will not load in browsers. I can not login to re set up and connect home bridge to HomeKit. please help

**Comment by iRayanKhan** [comment]
Go to deviceIP:8080 

For example mine is 192.158.4.42:8080

**Comment by VEGATRON3** [comment]
![Screen Shot 2020-06-24 at 12 59 28 PM](https://user-images.githubusercontent.com/66878144/85599561-9eeda200-b61a-11ea-828f-dafbd28911f2.png)

I have the IP address, how will this help me get back to this login page. I need this page above to load and it doesn't.

**Comment by toshibochan** [comment]
Use your web browser and type you homebridge device IP-ADDRESS:8581

**Comment by VEGATRON3** [comment]
thanks, hard a buddy, direct me... Pi is running again. but home kit is not recognizing any of the wize devices like it was before
