### ISSUE TITLE
Homebridge install on Synology

### ISSUE THREAD

**Issue by jojogrosso** [homebridge/homebridge#2607]
I recently installed homebridge on my Synology and I’m noticing I have to restart it every day. My devices show up as not responsive in Home otherwise. Once I restart all is back to normal. 

I used to have homebridge installed on a Windows 10 machine, but would rather host it on my Synology. Any idea on what can be causing me needing to restart every day?

**Comment by Supereg** [comment]
If you still have regular connection issues, you might want to check out the latest beta version https://github.com/homebridge/homebridge/issues/2619 and check if that might help with your issue?
