### ISSUE TITLE
Connection works, but light colors can't be changed

### ISSUE THREAD

**Issue by sortino** [homebridge/homebridge#2611]
I have successfully added all of my lights (Philips Wiz, and Hue) to my Homebridge setup. Unfortunately, I can only control the brightness and not the color of the lights. Any ideas?

Edit: It should also be noted, the Apple Home app seems to be bugging out as well? Weird colors are showing up when I go to edit, even in the "Tempature" mode where no colors should show. It's almost like the Homebridge connection is causing it to bug out.

Edit 2: This issue might be due to the fact that I have not manually added lights into the config file (I used the auto config plugin). Can anyone provide me with the correct syntax (and basic instructions if possible)?

**Comment by milo526** [comment]
Hello,

You are now commenting on the homebridge repository, this seems to be an issue with a homebridge plugin. It might be better to ask your question at the plugins repository as to reach the maintainer directly.
