### ISSUE TITLE
Which version am I running?

### ISSUE THREAD

**Issue by samsonrosen** [homebridge/homebridge#2612]
Hi, 

When I updated Homebridge I am informed I'm installing the latest version. But the command 'homebridge -V' says otherwise.

Is my .bash mapped incorrectly?

`Church-Server:~ churchserver$ sudo npm install -g --unsafe-perm homebridge
/usr/local/Cellar/node/12.4.0/bin/homebridge -> /usr/local/Cellar/node/12.4.0/lib/node_modules/homebridge/bin/homebridge
+ homebridge@1.1.1
updated 3 packages in 6.888s
Church-Server:~ churchserver$ homebridge -V
0.4.53
Church-Server:~ churchserver$ 
`

Running Mac OS 10.3.6: 

Versions:
Church-Server:~ churchserver$ node -v
v14.3.0
Church-Server:~ churchserver$ npm -v
6.14.5
Church-Server:~ churchserver$ homebridge -V
0.4.53

**Comment by oznu** [comment]
See https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-macOS
