### ISSUE TITLE
Move Homebridge parallel to a new PI

### ISSUE THREAD

**Issue by Phoenix-DH** [homebridge/homebridge#2613]
Hey,

I got a maybe simple question:
Actually I am running homebridge on my pi2. I think something is broken, maybe the RAM or something else, it is not running stable.

I think to order a PI4 and set it up in parallel.

What is the best way to do that I will not loose my home config?
As far as I know all depends on the homebridge ID, right.
Can‘t imagine that it will work when 2 bridges are online in parallel or?

If yes, backup and restore would be easy.

Or are there some other dependencies that home is aware of the „same“ bridge when all is set up.

Thanks guys.

**Comment by Zer0x00** [comment]
Don't run them in parallel, just backup and restore by following this wiki:
https://github.com/homebridge/homebridge/wiki/Backup-and-Restore

**Comment by Phoenix-DH** [comment]
Great thanks 👌🏻
