### ISSUE TITLE
get and set status from Homebridge to openHAB

### ISSUE THREAD

**Issue by slydlake** [homebridge/homebridge#2614]
Hi,

I have little question.

For some devices I just use Homebridge. For all other devices I use openHAB.
So I want to merge all information into openHAB.

Do you know a good way to do this?

I cannot find a way to GET or PUT Homebridge status over curl.

Or do you know another solution for this problem?

**Comment by dkrizic** [comment]
There are a few hundred homebridge plugins out there. Check for example this one:

https://github.com/benzman81/homebridge-http-webhooks
