### ISSUE TITLE
Error from MyQ Plugin will cause all Homebridge devices to come back "not responding"

### ISSUE THREAD

**Issue by kevinchau** [homebridge/homebridge#2615]
**Describe The Bug:**
There is a new bug in the MyQ app that is easily solved by editing the index.js. However, even though other plugins/devices are working just fine, the MyQ devices returning an error will cause all devices to show up as not responding in the Home app.

After fixing the bug in MyQ, all devices show as working again. This issue: https://github.com/hjdhjd/homebridge-myq2/issues/32

**To Reproduce:**
Use `homebridge-myq2 v1.2.22`
All devices will show not responding

**Expected behavior:**
Only MyQ devices should show not responding

**Comment by sandeen** [comment]
This seems to fix the problem of the plugin knocking out all other platforms when it fails due to issue #32
Note: I'm a javascript hack, not sure if this is correct, but it worksforme.

```
--- a/index.js	2020-05-31 14:03:03.973635105 -0500
+++ b/index.js	2020-06-25 21:25:05.956742499 -0500
@@ -97,6 +98,9 @@
           self.updateDoorStates(accessory);
         }
       }
+    } else {
+          self.log('addAccessory: login failed');
+          self.removeAccessory(accessory);
     }
   });
 }
@@ -217,6 +227,7 @@
     }
   }).catch(error => {
       self.log('Login error: ' + error);
+      callback(error);
   });
 }

``` 
Something seems wrong w/ the retry interval though, the retries and failures come pretty fast.

**Comment by sandeen** [comment]
I'm not sure why the rest of homebridge stopped responding after the unhandled error in myq2, though.

**Comment by bwoodruff** [comment]
> I'm not sure why the rest of homebridge stopped responding after the unhandled error in myq2, though.

I pushed for a fix for that (here: https://github.com/homebridge/homebridge/issues/2339) and was told the solution is either to

1. write the fix myself (I'm not a developer so that is a non-starter)
2. run a separate instance of homebridge for each plugin.

Option 2 is the more realistic fix but would mean a lot of work due to having to set up all of my automations etc again. Plus it frankly seems silly to me that is the answer, instead of building the system such that it is robust enough to survive an invalid API response in one plugin, but 🤷

**Comment by Dudleydogg** [comment]
So I discovered today that yes this Plugin no longer works, and its a Verified plugin does that mean it will get fixed eventually?

**Comment by donavanbecker** [comment]
> So I discovered today that yes this Plugin no longer works, and its a Verified plugin does that mean it will get fixed eventually?

this is what a verified status means, [please read here](https://github.com/homebridge/verified)

**Comment by donavanbecker** [comment]
I am closing this since this is a plugin issue not homebridge.

**Comment by bwoodruff** [comment]
@Dudleydogg FYI it has been fixed

**Comment by Dudleydogg** [comment]
Yes it has I saw it was updated and installed again worked just fine, Thank you for the Update
