### ISSUE TITLE
Creating 2 identical Services in a single accessory

### ISSUE THREAD

**Issue by rjcarlson49** [homebridge/homebridge#2616]
I have a WindowCovering (shades) plugin and I am trying to add 2 switches (Services) to act as simple open/close buttons. This is not ideal, but I can't find any other Service that meets the need.

Here's the code:

    this.swServiceOpen = this.accessory.getService(this.platform.Service.Switch)
                        || this.accessory.addService(this.platform.Service.Switch, this.displayName + ' Open', 'Open');
    this.swServiceClose = this.accessory.getService(this.platform.Service.Switch)
                        || this.accessory.addService(this.platform.Service.Switch), this.displayName + ' Close', 'Close';
    this.swServiceOpen.displayName = this.displayName + ' Open';
    this.swServiceOpen.subtype = 'Open';
    this.swServiceClose.displayName = this.displayName + ' Close';
    this.swServiceClose.subtype = 'Close';

I added the last 4 lines because I saw that "solution" in an Issue comment. It did not help. When I look at the Accessories on the Homebridge UI, I see only the Open switches, not the Close ones.

How do I properly set the subtype?

**Comment by rjcarlson49** [comment]
I should have added that these switches are being created within the WindowCovering Accessory. They are additional services for the same device.

**Comment by rjcarlson49** [comment]
It also appears that when a get or set is called on the switch from Homekit, the listener for both switches is being called. When the second listener calls the callback, it crashes with the "already called that callback" error. So, I have simply removed temporarily one of the two callbacks so I can keep debugging. This seems to keep me afloat for now.

**Comment by NorthernMan54** [comment]
Here is an example of subtype's from a plugin I wrote a few years ago that used subtype's to set different programs on a LED light strip.

https://github.com/NorthernMan54/homebridge-mculed/blob/5ee3e7d4ce931b37025a724753b00eb62865265e/mculed.js#L577

**Comment by rjcarlson49** [comment]
That appears to be identical to my code with the exception that I am restoring cached Accessories with getService. The original addService that created the accessory the first time was just like yours.

**Comment by NorthernMan54** [comment]
When you restore, you only need to bind the get/set events

**Comment by rjcarlson49** [comment]
> When you restore, you only need to bind the get/set events
 
I don't understand. Are you saying the getService||addService calls are unnecessary? These are there because I started with the Dynamic Platform example in the Homebridge wiki.

**Comment by NorthernMan54** [comment]
Without seeing the context it is pretty hard to say

**Comment by rjcarlson49** [comment]
What do you need to see? The entire constructor and code from the Platform?

**Comment by rjcarlson49** [comment]
Platform:

    constructor(
        public readonly log: Logger,
        public readonly config: PlatformConfig,
        public readonly api: API) {
        this.log.debug('Finished initializing DooyaController platform:', this.config.name);
        this.log.info('Serial Port:', this.config.serialPort);

        this.SerialPort = require('serialport');
        this.arduinoPort = new this.SerialPort(this.config.serialPort, {baudRate: 9600});
        this.xmitWait = this.config.xmitWait;
        this.requestWait = this.config.updateWait;
        this.logTime('requestWait: ' + this.requestWait + ' xmitWait: ' + this.xmitWait);
        this.nowBase = 0;
        this.now();
        this.dooyaObjects = []; // Empty array to start

        // When this event is fired it means Homebridge has restored all cached accessories from disk.
        // Dynamic Platform plugins should only register new accessories after this event was fired,
        // in order to ensure they weren't added to homebridge already. This event can also be used
        // to start discovery of new accessories.
        this.api.on('didFinishLaunching', () => {
         log.debug('Executed didFinishLaunching callback');
          // run the method to discover / register your devices as accessories
          this.discoverDevices();
        });
    }

    /**
     * This function is invoked when homebridge restores cached accessories from disk at startup.
     * It should be used to setup event handlers for characteristics and update respective values.
     */
     configureAccessory(accessory: PlatformAccessory) {
         this.log.info('Loading accessory from cache:', accessory.displayName);

        // add the restored accessory to the accessories cache so we can track if it has already been registered
        this.accessories.push(accessory);
    }

    /**
    * Accessories must only be registered once, previously created accessories
    * must not be registered again to prevent "duplicate UUID" errors.
    */
    discoverDevices() {
        this.log.info('DooyaController platform - discoverDevices');
        // EXAMPLE ONLY
        // A real plugin you would discover accessories from the local network, cloud services
        // or a user-defined array in the platform config.
        const devices = this.config.shades;

        // loop over the discovered devices and register each one if it has not already been registered
        for (const device of devices) {

        // generate a unique id for the accessory this should be generated from
        // something globally unique, but constant, for example, the device serial
        // number or MAC address
        const uuid = this.api.hap.uuid.generate(this.config.fixedCode + device.channelCode);

        // see if an accessory with the same uuid has already been registered and restored from
        // the cached devices we stored in the `configureAccessory` method above
        const existingAccessory = this.accessories.find(accessory => accessory.UUID === uuid);

        if (existingAccessory) {
            // the accessory already exists
            this.log.info('Restoring existing accessory from cache:', existingAccessory.displayName);

            // if you need to update the accessory.context then you should run `api.updatePlatformAccessories`. eg.:
            // existingAccessory.context.device = device;
            // this.api.updatePlatformAccessories([existingAccessory]);
            existingAccessory.context.device = device;
            this.api.updatePlatformAccessories([existingAccessory]);

            // create the accessory handler for the restored accessory
            // this is imported from `platformAccessory.ts`
            this.dooyaObjects.push(new DooyaAccessory(this, existingAccessory));
        
        } else {
            // the accessory does not yet exist, so we need to create it
            this.log.info('Adding new accessory:', device.displayName);

            // create a new accessory
            const accessory = new this.api.platformAccessory(device.displayName, uuid);
    
            // store a copy of the device object in the `accessory.context`
            // the `context` property can be used to store any data about the accessory you may need
            accessory.context.device = device;
    
            // create the accessory handler for the newly create accessory
            // this is imported from `platformAccessory.ts`
            this.dooyaObjects.push(new DooyaAccessory(this, accessory));

            // link the accessory to your platform
            this.api.registerPlatformAccessories(PLUGIN_NAME, PLATFORM_NAME, [accessory]);
            }

        // it is possible to remove platform accessories at any time using `api.unregisterPlatformAccessories`, eg.:
        // this.api.unregisterPlatformAccessories(PLUGIN_NAME, PLATFORM_NAME, [accessory]);  
        }
    }

**Comment by rjcarlson49** [comment]
Accessory: (6 of these are configured)

    constructor(
        private readonly platform: DooyaHomebridgePlatform,
        private readonly accessory: PlatformAccessory) {

        // .... Set config values    

        this.id = this.accessory.UUID;

        // ...
  
        // set accessory information
        this.accessory.getService(this.platform.Service.AccessoryInformation)!
          .setCharacteristic(this.platform.Characteristic.Manufacturer, 'Dooya')
          .setCharacteristic(this.platform.Characteristic.Model, 'Shades')
          .setCharacteristic(this.platform.Characteristic.SerialNumber, '0000-0000');

        // get the WindowCovering service if it exists, otherwise create a new service
        // you can create multiple services for each accessory
        this.service = this.accessory.getService(this.platform.Service.WindowCovering) 
                    || this.accessory.addService(this.platform.Service.WindowCovering);
    
        this.swServiceOpen = this.accessory.getService(this.platform.Service.Switch) 
                          || this.accessory.addService(this.platform.Service.Switch, this.displayName + ' Open', 'Open');
    
        this.swServiceClose = this.accessory.getService(this.platform.Service.Switch)
                          || this.accessory.addService(this.platform.Service.Switch), this.displayName + ' Close', 'Close';

        this.swServiceOpen.displayName = this.displayName + ' Open';
        this.swServiceOpen.subtype = 'Open';
        this.swServiceClose.displayName = this.displayName + ' Close';
        this.swServiceClose.subtype = 'Close';
    
        // To avoid "Cannot add a Service with the same UUID another Service without also defining a unique 'subtype' property." error,
        // when creating multiple services of the same type, you need to use the following syntax to specify a name and subtype id:
        // this.accessory.getService('NAME') ?? this.accessory.addService(this.platform.Service.Lightbulb, 'NAME', 'USER_DEFINED_SUBTYPE');

        // set the service name, this is what is displayed as the default name on the Home app
        // in this example we are using the name we stored in the `accessory.context` in the `discoverDevices` method.
        this.service.setCharacteristic(this.platform.Characteristic.Name, this.displayName);

        // Also tried this code:
        //this.swServiceOpen.setCharacteristic(this.platform.Characteristic.Name, this.displayName + ' Open');
        //this.swServiceClose.setCharacteristic(this.platform.Characteristic.Name, this.displayName + ' Close');
        // each service must implement at-minimum the "required characteristics" for the given service type
        // see https://developers.homebridge.io/#/service/Lightbulb

        this.targetPosition = 100;
        if (accessory.context.tP >= 0 && accessory.context.tP <= 100) {
            this.targetPosition = accessory.context.tP;
        }
    
        this.currentPosition = this.targetPosition;
        this.positionState = PosState.Stopped; // Aways start assuming shade is not moving
    
        this.switchPosOpen = false;
        this.switchPosClose = false;
    
        this.logState();
    
        // register handlers for the CurrentPosition Characteristic
        this.service.getCharacteristic(this.platform.Characteristic.CurrentPosition)
          .on('get', this.getCurrentPos.bind(this)); // GET - bind to the `getCurrentPos` method below
    
        // register handlers for the TargetPosition Characteristic
        this.service.getCharacteristic(this.platform.Characteristic.TargetPosition)!
          .on('get', this.getTargetPos.bind(this))        // GET - bind to the 'getTarget` method below
          .on('set', this.setTargetPos.bind(this));       // SET - bind to the 'setTarget` method below
    
        // register handlers for the PositionState Characteristic
        this.service.getCharacteristic(this.platform.Characteristic.PositionState)
          .on('get', this.getPosState.bind(this));       // GET - bind to the 'getPosState` method below
        
        this.swServiceOpen.getCharacteristic(this.platform.Characteristic.On)!
          .on('set', this.setSwitchOpen.bind(this))       // SET - bind to the 'setSwitchOpen` method below
          .on('get', this.getSwitchOpen.bind(this));       // SET - bind to the 'getSwitchOpen` method below
    
        this.swServiceClose.getCharacteristic(this.platform.Characteristic.On)!
          .on('set', this.setSwitchClose.bind(this))       // SET - bind to the 'setSwitchClose` method below
          .on('get', this.getSwitchClose.bind(this));       // SET - bind to the 'getSwitchClose` method below
    
        this.updateState();
        this.updateTarget();
        this.updateCurrent();
    }

**Comment by NorthernMan54** [comment]
A github repo is easiest

**Comment by rjcarlson49** [comment]
I made the repo public. https://github.com/rjcarlson49/homebridge-dooya-0

**Comment by rjcarlson49** [comment]
I tried this code:
 
    this.swServiceClose = <Service>this.accessory.getService(this.platform.Service.Switch);
    if (!this.swServiceClose) {
      this.swServiceClose = new this.platform.Service.Switch(this.displayName + ' Close', 'Close');
      if (this.swServiceOpen) {
        this.logCh('New Close Switch Service');
      } else {
        this.logCh('New Close Switch Service -- Failed!');
      }
    } 
    
After deleting the Accessory from the cache I ran this. It reports that the Switch services are created, but the switches do not show up in Home or the Accessories page on the HB web UI.

**Comment by rjcarlson49** [comment]
OK, I finally found code that works.

    this.service = this.accessory.getService(this.platform.Service.WindowCovering) 
                || this.accessory.addService(this.platform.Service.WindowCovering);
    
    this.swServiceOpen = <Service>this.accessory.getServiceById(this.platform.Service.Switch, 'Open');
    if (!this.swServiceOpen) {
      this.swServiceOpen = new this.platform.Service.Switch(this.displayName + ' Open', 'Open');
      if (this.swServiceOpen) {
        this.swServiceOpen = this.accessory.addService(this.swServiceOpen);
        this.logCh('New Open Switch Service');
      } else {
        this.logCh('New Open Switch Service -- Failed!');
      }
    } 
    this.swServiceClose = <Service>this.accessory.getServiceById(this.platform.Service.Switch, 'Close');
    if (!this.swServiceClose) {
      this.swServiceClose = new this.platform.Service.Switch(this.displayName + ' Close', 'Close');
      if (this.swServiceClose) {
        this.swServiceClose = this.accessory.addService(this.swServiceClose);
        this.logCh('New Close Switch Service');
      } else {
        this.logCh('New Close Switch Service -- Failed!');
      }
    } 
   
When restoring a multiple service, you have to search for the cached service with getServiceByID, passing the service type and subtype. When creating the service the first time, use the equivalent of 'new  this platform.Service.Switch' passing display name and subtype. The service must then be added with .addService.

**Comment by NorthernMan54** [comment]
Sorry been away for a few days vacation

Glad you have worked out your issues.
