### ISSUE TITLE
Installatoin help on Zee2

### ISSUE THREAD

**Issue by JCCcccspud** [homebridge/homebridge#2620]
I started installing node JS.  The first step seems to have gone fine.  The second step starting with sudo apr-get does not seem to have worked.  Here is a screenshot.  What do I do now?
![Capture](https://user-images.githubusercontent.com/63560486/86495485-2e900080-bd3f-11ea-81f1-5480fb7a4d77.JPG)

**Comment by TautFlorian** [comment]
@JCCcccspud try to install libstdc++6 manually with the correct version >= 5.2 and then restart the process.

Maybe you should upgrade your pi before trying to install nodejs.
Debian Jessie has been released in 2016 and LTS already ended end of june.

**Comment by JCCcccspud** [comment]
Thanks for the response ( I was starting to worry that nobody had answer), but I am not sure how to install libstdc++6 manually.  If I upgrade the OS to Jesse I am afraid I will lose the Homeseer software.  Not sure how to do that safely.  Any advice?

Thanks again.

**Comment by JCCcccspud** [comment]
Just checked, I am running Jesse.  Is that the problem?

**Comment by JCCcccspud** [comment]
In case this helps others, I believe I found a solution.  You can install nodeJS 10 on Jessie without getting the dependency error and then install Homebridge and it seems to work.
