### ISSUE TITLE
Error with updating plug-in after installing node-red (preconfigured Rpi HB image)

### ISSUE THREAD

**Issue by rakgupta** [homebridge/homebridge#2626]
**Describe The Bug:**
After installing node-red along with the pre-configured Hombridge version, updating plug-ins from the UI is giving an error. The error is below:

`USER: pi
DIR: /usr/local/lib
CMD: sudo -E -n npm install homebridge-ring@latest

npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "node_modules": node_modules is a blacklisted name

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-08T22_02_08_114Z-debug.log

Command failed. Please review log for details.
`

**To Reproduce:**
Install Node-Red along with the pre-configured RPi Homebridge image. Node-Red install was done by running the following command from the HB terminal window

bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered)
(https://nodered.org/docs/getting-started/raspberrypi)

Update or install a new HB plug-in

**NOTE:** both Homebridge and node-red are working as expected (lights work from Home app, node-red flows work. The only issue is with updating plug-ins.

**Expected behavior:**
Plug-in should update.

[**Logs:**]()
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'homebridge-ring@latest'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.0
4 verbose npm-session 15f95a8658716d8b
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-ring 233ms
8 http fetch GET 200 https://registry.npmjs.org/homebridge-ring/-/homebridge-ring-9.4.1.tgz 176ms
9 silly pacote tag manifest for homebridge-ring@latest fetched in 443ms
10 verbose stack Error: Invalid package name "node_modules": node_modules is a blacklisted name
10 verbose stack     at invalidPackageName (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:86:15)
10 verbose stack     at Result.setName (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:121:11)
10 verbose stack     at new Result (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:111:23)
10 verbose stack     at Function.resolve (/usr/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:58:15)
10 verbose stack     at computeVersionSpec (/usr/lib/node_modules/npm/lib/install/deps.js:320:21)
10 verbose stack     at Installer.normalizeCurrentTree (/usr/lib/node_modules/npm/lib/install.js:410:68)
10 verbose stack     at Array.<anonymous> (/usr/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
10 verbose stack     at LOOP (/usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
10 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
10 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:368:5
10 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/iferr.js:3:64
10 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
10 verbose stack     at /usr/lib/node_modules/npm/node_modules/call-limit/call-limit.js:28:43
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:79:11)
11 verbose cwd /usr/local/lib
12 verbose Linux 4.19.97-v7l+
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "homebridge-ring@latest"
14 verbose node v12.18.0
15 verbose npm  v6.14.5
16 error code EINVALIDPACKAGENAME
17 error Invalid package name "node_modules": node_modules is a blacklisted name
18 verbose exit [ 1, true ]
```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "username-clean",
        "port": 51330,
        "pin": "pin-clean"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "teal",
            "tempUnits": "f",
            "platform": "config"
        },
        {
            "platform": "Hubitat-MakerAPI",
            "name": "Hubitat MakerAPI",
            "app_url": "http://xxx.xxx.x.xxx/apps/api/3",
            "access_token": "removed",
            "local_ip": "xxx.xxx.x.xxx",
            "local_port": 20010,
            "mode_switches": false,
            "hsm": false,
            "debug": false,
            "logFile": {
                "enabled": true,
                "path": "",
                "file": "",
                "compress": true,
                "keep": 5,
                "size": "10m"
            }
        },
        {
            "refreshToken": "remved",
            "platform": "Ring"
        }
    ],
    "accessories": []
```

**Screenshots:**

**Environment:**
Node.js Version -  v12.18.0
Npm version - v6.14.5
Username -  pi
Storage Path - /var/lib/homebridge
Config Path -  /var/lib/homebridge/config.json
Service Mode Yes

**Comment by oznu** [comment]
The node-red installer you ran installs its own version of Node.js which has caused this issue.

The image includes a tool called `hb-config` which you can run to install node-red in a way that won't mess up the Node.js installation.

As for fixing your existing setup, I'd use the Homebridge UI to do a backup, then flash a fresh copy of the image to your SD card.

**Comment by rakgupta** [comment]
> The image includes a tool called `hb-config` which you can run to install node-red in a way that won't mess up the Node.js installation.

Thanks. Yes - I found hb-config last night and was going to try it today. I already made a backup of both (HB and node-red flows), so hopefully all will go smoothly.
