### ISSUE TITLE
Error: Did not bind any sockets! v1.2.0 beta

### ISSUE THREAD

**Issue by eliottha** [homebridge/homebridge#2627]
As a reply to:

>@eliottha @niechen (or anyone else experiencing the **"Error: Did not bind any sockets!"** error):
>
>In order to get a better understanding on why this error occurs, we would need some information about your network setup (of the device homebridge is running on).
>This includes a rough description what device it is (like a RaspberryPi, NAS or something else), what operating system it is running and what network connection it has (WiFi, Ethernet, both, ...) and anything else you consider special.
>
>Bust most importantly, we need the list of network interfaces your device has.
>To make this easy, we updated our tool [mdns-diagnostics](https://github.com/homebridge/mdns-diagnostics#readme) to show the required information about your network. We are interested in the upper part of the printed output, which should look like shown below (network information can be a lot longer depending on the device).
>
>The linked repository shows instruction on how to install the tool and how to run it. It would be very helpful if you could share this information so we can start investigating this issue.
>When using docker, make sure to run `mdns-diagnostics` from INSIDE the container.
>
>After that we currently advise you to rollback your homebridge installation to the stable version as shown in the issue above, so you can enjoy a running homebridge again. Thanks for testing.
>
>**Output example**:
>
>```
>Platform: darwin
>Version: Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
>Network information:
>{
>  "lo0": [
>    "ipv4: 127.0.0.1/8",
>    "routableIpv6: ::1/128",
>    "ipv6: fe80::1/64"
>  ],
>  "en0": [
>    "ipv6: fe80::1ff:fe23:4567:890a/64",
>    "ipv4: 192.168.1.34/24",
>    "routableIpv6: 2001:db8:85a3::8a2e:370:7334/64"
>  ]
>}
>```

_Originally posted by @Supereg in https://github.com/homebridge/homebridge/issues/2619#issuecomment-653693431_

**Comment by eliottha** [comment]
So I'm using Ubuntu 18.04.5 LTS on custom machine with Intel i5, it has both Ethernet and WiFi, but WiFi is disabled. So only Ethernet shows up. Further I have my en0 interface bridged to br0 for use with Linux KVM. Networking works fine in both the virtual machines or the host machine. I'm getting this error on the host machine in the beta while I did not have it before. I can say that homebridge (latest stable version) uses en0.

Further find the demanded log:
```
Platform: linux
NodeJS Version v14.5.0
Network information:
{
  "lo": [
    "ipv4: 127.0.0.1/8 (internal)",
    "routableIpv6: ::1/128 (internal)"
  ],
  "br0": [
    "ipv4: 192.168.1.1/16",
    "routableIpv6: 2a02:1812:1e01:1400:8d6:62bc:23ee:2202/64",
    "routableIpv6: 2a02:1812:1e01:1400:57f:68b6:4c10:d3b8/64",
    "routableIpv6: 2a02:1812:1e01:1400:c18:6647:141f:17b0/64",
    "routableIpv6: 2a02:1812:1e01:1400:9556:e931:e80d:a9a/64",
    "routableIpv6: 2a02:1812:1e01:1400:1cf7:4f9a:ba8b:56af/64",
    "routableIpv6: 2a02:1812:1e01:1400:6d5f:7bd4:b166:ebd9/64",
    "routableIpv6: 2a02:1812:1e01:1400:60e3:f541:1d92:ea86/64",
    "routableIpv6: 2a02:1812:1e01:1400:c62c:3ff:fe1a:c5cb/64",
    "ipv6: fe80::c62c:3ff:fe1a:c5cb/64"
  ],
  "vnet0": [
    "ipv6: fe80::fc54:ff:fe3b:bc2/64"
  ]
}
```

**Comment by Supereg** [comment]
Thanks, your issue might already be fixed with the latest beta. Would be great if you could check that by reinstalling the latest homebridge beta using:

```
sudo npm install -g --unsafe-perm homebridge@beta
```

Cause the error message `Error: Did not bind any sockets` does not exist anymore in the latest codebase.

If it works as expected homebridge should advertise itself correctly on the network via the interface `br0`. Though you may experience known issues as listed in https://github.com/homebridge/homebridge/issues/2619#issue-650305018.

**Comment by oznu** [comment]
Please use #2619 for 1.2.0 betta issues.
