### ISSUE TITLE
Homebridge showing different version of nodejs

### ISSUE THREAD

**Issue by duceduc** [homebridge/homebridge#2628]
Homebridge Ver: 1.1.1
Platform: RPI 3

On the Homebridge GUI, it is showing Node.js Version:  v12.18.1.
On the raspberry pi, nodejs -v outputs v12.18.2

**Comment by oznu** [comment]
Make sure you've restarted the Homebridge service from the command line, `sudo hb-service restart`.

If the issue persists you've probably installed two copies of Node.js using different methods. This guide will show you how to fix it:

https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux
