### ISSUE TITLE
Thermostat Heat Only Button

### ISSUE THREAD

**Issue by Faisalthe01** [homebridge/homebridge#2629]
Hello, 
Sorry if it is not correct place to raise an issue.

I have recently created a fork of Broadlink RM TV plugin and disabled the Auto and Cool in Thermostat accessory as i use with my heater only and some other users were requesting it. 

I have successfully removed the Auto and Cool mode but in HomeKit app the On/Off button of Thermostat accessory looks unusual. It is missing the I/O graphic in the middle of the button. I am using iOS 14 beta so I thought it could be related but then i tried on iOS 13 and it looks the same.

This is how it looks like when it’s turned on

![42487489-652B-42F1-A176-8734D416D632](https://user-images.githubusercontent.com/62862684/87306012-bbfefc00-c55a-11ea-8771-d9c21e30c8a4.png)

This is how it should look like in HomeKit

![4A72FCEE-B28D-4268-A2EC-9B822B667C8A](https://user-images.githubusercontent.com/62862684/87306081-d5a04380-c55a-11ea-927e-86e3c9831297.png)

**Comment by CyberMrProper** [comment]
Hi @Faisalthe01 this is not a homebridge bug, if you want to get that on/off button you have to change the accessory type. That is, from Thermostat to HeaterCooler, but you will have to change the plugin because heater cooler uses other characteristics.

**Comment by Faisalthe01** [comment]
> Hi @Faisalthe01 this is not a homebridge bug, if you want to get that on/off button you have to change the accessory type. That is, from Thermostat to HeaterCooler, but you will have to change the plugin because heater cooler uses other characteristics.

Hi @CyberMrProper, thank you for the reply. It is a Thermostat and i have disabled the Auto and Heat function, it has on/off button, as you can see in my screenshot. It is just missing the I/O graphic in that button, so you reckon that it is due to service being Thermostat not HeaterCooler but isn’t it a bit unusual that button is there in Thermostat but missing the graphic.

**Comment by Faisalthe01** [comment]
> Hi @Faisalthe01 this is not a homebridge bug, if you want to get that on/off button you have to change the accessory type. That is, from Thermostat to HeaterCooler, but you will have to change the plugin because heater cooler uses other characteristics.

@CyberMrProper, Thank you. I have replaced the service to HeaterCooler and i can see the button with I/O now. Thank you.
