### ISSUE TITLE
How to have homebridge listen on multiple network interfaces?

### ISSUE THREAD

**Issue by SidShetye** [homebridge/homebridge#2632]
**Describe Your Problem:**

I have most of my IOT devices on a separate 'guest' WiFi (192.168.1.X) and just 2 on my main WiFi + wired network (192.168.1.Y) . 
Homebridge is running on a raspberry pi 4 and the raspberry pi 4's eth0 is connected to the main network and wlan0/WiFi is connected to the guest network. Right now Homebridge listens only on eth0 and doesn't see most of my devices.
How do I configure Homebridge to use both network interfaces (to work with devices on both networks) ?

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge  <snip for privacy>",
        "username": "<snip for privacy>",
        "port": 51620,
        "pin": "<snip for privacy>"
    },
    "accessories": [
       <snip for privacy>
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
       <snip for privacy>
    ]
}
```

**Environment:**

HomeBridge v1.1.1 
Node.js Version v12.18.2, 
Npm Version v6.14.6
Operating System**: Raspbian GNU/Linux 10 (buster)
Process Supervisor**: hb-service

**Comment by SidShetye** [comment]
Also adding

    "mdns": {
        "interface": "192.168.1.110"
    },

doesn't really work for two reasons 

1) it's still ignored and binds to the eth0 interface instead of wlan0 interface (I wish it asked for interface name like `wlan0` instead of an IP address though) and 
2) it only allows choosing one network interface `wlan0` instead of multiple like `wlan0` and `eth0`

**Comment by NorthernMan54** [comment]
If your having your raspberrypi listen to two separate networks you need to us different address spaces for each or the messages get lost.

Ie eth0 should be 192.168.1.x and wlan0 should be 192.168.2.x

**Comment by SidShetye** [comment]
Hmm ... that’s not an option for my network, far reaching ripple effects.

As a step down, jow can I tell homebridge to use a specific interface/IP? I want it to bind to my wlan0 amd the mdns setting seems to be ignored. 

If this works, I might try two homebridge instances on the rpi4, one for each interface.

**Comment by SidShetye** [comment]
@NorthernMan54 - any ideas?

> Hmm ... that’s not an option for my network, far reaching ripple effects.
> As a step down, how can I tell homebridge to use a specific interface/IP? I want it to bind to my wlan0 interface instead and the mdns setting seems to be ignored.
> If this works, I might try two homebridge instances on the rpi4, one for each interface.

**Comment by NorthernMan54** [comment]
@SidShetye The latest beta version of homebridge was designed with multiple networks as part of the goal, and it works very well that way automatically.  It listens on all interfaces, and responds appropriately. If your multiple subnet network is configured properly, it will work without issue.  The homebridge team had tested this particular config as it was a long standing issue of users.  The mdns setting was removed as it was no longer required.

If you have a rpi with both the WiFi interface connected to one network, and eth0 connected to a different network ( with different ip network addresses Ie 192.168.1.x and 192.168.2.x ) it will work.  But if you have the WiFi interface and eth0 connected to different networks but use the same ip range for both, this will not work properly and will cause issues as this is a misconfigured network.

You need to go into the dhcp server for one of the networks and define a different address range.

**Comment by SidShetye** [comment]
@NorthernMan54: I see. Based on how I've seen this work, I don't want HomeBridge to listen on _**all**_ interfaces (`eth0` and `wlan0`) - just one specific interface (`wlan0`). 

How do I do that? I've upgraded to `1.2.0-beta.31` since that seems to be the pathway looking ahead.

**Comment by NorthernMan54** [comment]
Unfortunately that level of configuration is not available

**Comment by oznu** [comment]
I think,  based on a chat I've had with @Supereg, at some point before 1.2.0 is released we will be allowing you to define which interface you want to listen on.

eg.

```
"mdns": {
   "interface": "eth0"
}
```

This will also accept an IP address too, for backwards compatablity with Homebridge < 1.0.0:

```
"mdns": {
   "interface": "192.168.1.1"
}
```

**Comment by SidShetye** [comment]
> I think, based on a chat I've had with @Supereg, at some point before 1.2.0 is released we will be allowing you to define which interface you want to listen on.
> 
> eg.
> 
> ```
> "mdns": {
>    "interface": "eth0"
> }
> ```
> 
> This will also accept an IP address too, for backwards compatablity with Homebridge < 1.0.0:
> 
> ```
> "mdns": {
>    "interface": "192.168.1.1"
> }
> ```

That’ll be perfect for my situation, thanks. Since you’re designing this, perhaps makes sense to have it as an array instead of a singular field. For non-raspberry pi situations with multiple interfaces e.g. my other Linux Pc server has wan0, eth0, eth1, wlan0 - not counting any of the virtual interfaces. 

Side note, thanks for publishing the docker images.

**Comment by Supereg** [comment]
When running the v1.2.0 beta you can already specify the interfaces as an array.
Currently the accessory server will still listen on ALL interfaces, but the advertisement will be limited to the supplied interfaces. This will change until the final release.

**Comment by Supereg** [comment]
Just to have it updated.
This feature was added in the 1.3.0 beta using the new `bridge.bind` config option.
