### ISSUE TITLE
Modules not found after update

### ISSUE THREAD

**Issue by cstromme** [homebridge/homebridge#2634]
Updated Homebridge to the latest version today, and after the update it fails to start with the following error:

> internal/modules/cjs/loader.js:983
>   throw err;
>   ^
> 
> Error: Cannot find module 'source-map-support/register'
> Require stack:
> - /usr/local/lib/node_modules/homebridge/lib/cli.js
> - /usr/local/lib/node_modules/homebridge/bin/homebridge
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:862:27)
>     at Module.require (internal/modules/cjs/loader.js:1040:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/cli.js:24:1)
>     at Module._compile (internal/modules/cjs/loader.js:1151:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
>     at Module.load (internal/modules/cjs/loader.js:1000:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
>     at Module.require (internal/modules/cjs/loader.js:1040:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/usr/local/lib/node_modules/homebridge/lib/cli.js',
>     '/usr/local/lib/node_modules/homebridge/bin/homebridge'
>   ]
> }

After running a "npm -g list" I see the following:

> npm ERR! missing: node-persist@^0.0.11, required by homebridge@1.1.1
> npm ERR! missing: qrcode-terminal@^0.12.0, required by homebridge@1.1.1
> npm ERR! missing: semver@^7.3.2, required by homebridge@1.1.1
> npm ERR! missing: source-map-support@^0.5.19, required by homebridge@1.1.1
> npm ERR! missing: es-to-primitive@^1.2.1, required by es-abstract@1.17.6
> npm ERR! missing: has@^1.0.3, required by es-abstract@1.17.6
> npm ERR! missing: object.assign@^4.1.0, required by es-abstract@1.17.6
> npm ERR! missing: string.prototype.trimend@^1.0.1, required by es-abstract@1.17.6
> npm ERR! missing: string.prototype.trimstart@^1.0.1, required by es-abstract@1.17.6
> npm ERR! missing: ansi-styles@^4.1.0, required by chalk@4.1.0
> npm ERR! missing: supports-color@^7.1.0, required by chalk@4.1.0
> npm ERR! missing: debug@^4.1.1, required by hap-nodejs@0.7.7
> npm ERR! missing: decimal.js@^10.2.0, required by hap-nodejs@0.7.7
> npm ERR! missing: futoin-hkdf@~1.3.2, required by hap-nodejs@0.7.7
> npm ERR! missing: ip@^1.1.3, required by hap-nodejs@0.7.7
> npm ERR! missing: node-persist@^0.0.11, required by hap-nodejs@0.7.7
> npm ERR! missing: tweetnacl@^1.0.3, required by hap-nodejs@0.7.7
> npm ERR! missing: array-flatten@^2.1.2, required by bonjour-hap@3.5.11
> npm ERR! missing: deep-equal@^2.0.2, required by bonjour-hap@3.5.11
> npm ERR! missing: ip@^1.1.5, required by bonjour-hap@3.5.11
> npm ERR! missing: multicast-dns@^7.2.2, required by bonjour-hap@3.5.11
> npm ERR! missing: multicast-dns-service-types@^1.1.0, required by bonjour-hap@3.5.11

So I tried doing "npm install -g npm-install-missing", but that doesn't seem to do anything. Manually installing each package works, but I still get the same errors as above.

**Comment by oznu** [comment]
Uninstall / reinstall Homebridge using npm.

**Comment by butenbremer** [comment]
> Uninstall / reinstall Homebridge using npm.

Could you detail the implications on existing configuration/plugins etc?
