### ISSUE TITLE
Installing nodejs 10 instead of 12 on Raspbian

### ISSUE THREAD

**Issue by JCCcccspud** [homebridge/homebridge#2638]
I tried to install node JS **12** on my Zee2, which is a Pi3 running Jessie.  I got a dependency error relating to libstdc++6, which I posted an issue about and no one seemed to have an answer.  I think Jessie is just too old.  However, someone else had the same problem and was able to install nodeJS **10** and said it worked for Homebridge.

So my question is can someone list the correct commands for installing nodejs 10 so I can try that please?  Specifically, what would I change in the following:

# setup repo
curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -

# install Node.js
sudo apt-get install -y nodejs gcc g++ make python

# test node is working
node -v

# upgrade npm (version 6.13.4 has issues with git dependencies)
sudo npm install -g npm

**Comment by ebaauw** [comment]
Only the `2` in the first command.  See https://github.com/nodesource/distributions/blob/master/README.md.

**Comment by JCCcccspud** [comment]
Thanks.  Since I already ran the first command with the 12 and ran into the dependency error on the second step, do I need to do anything to undo what I previously did trying to install 12?

**Comment by ebaauw** [comment]
Sorry, dunno.  I don't recall ever having seen these errors.  Jesse is quite old, I think it might even be out of support.  Wouldn't be surprised if that contributes to your dependency errors.  You might want to plan moving to Stretch or Buster.

**Comment by JCCcccspud** [comment]
Yes, moving to Stretch would make sense, but I am a complete novice and am afraid I would lose Homeseer if I upgraded the OS.  Not sure I can back the whole thing up and reinstall it correctly.

**Comment by JCCcccspud** [comment]
For anyone who is interested, I was able to install nodejs 10 and it allowed me to install Homebridge so If you are having the same issue this appears to work.
