### ISSUE TITLE
New Fibaro device visible in home bridge logs but how to add in Apple iPhone Home?

### ISSUE THREAD

**Issue by birdfish14** [homebridge/homebridge#2639]
I'm using Homebridge between Apple Home and Fibaro Home Center 2. But when I add a new device in Fibaro I can't find a way to add it in the Apple Home application on my Apple device (iPhone). Do I need to remove Homebridge and then add it again to be able to use the new device? A lot of work to arrange everything as it was.

I can see that Homebridge is discovering the newly added device in the log files

**Comment by oznu** [comment]
Closing in favour of https://github.com/ilcato/homebridge-Fibaro-HC2/issues/197.
