### ISSUE TITLE
HomeKit - Error Domain=NSCocoaErrorDomain Code=4097

### ISSUE THREAD

**Issue by homeconnector** [homebridge/homebridge#2640]
Having issues adding mqttthing 

iPad IOS12
iPhone IOS14 Beta 3

Received when trying to add accessory on HomeKit 
Error Domain=NSCocoaErrorDomain Code=4097

Seems to be happening quite regularly when 2 homebridge instances listening for both mqttthing on different ports

Found the issue.   MQTTTHING.   Added " to the parameters for min and max temperature.   Not sure if this is a bug with Homebridge or MQTTTHING?

        {
            "accessory": "mqttthing",
            "type": "thermostat",
            "name": "Air Conditioner",
            "url": "mqtt://localhost",
            "username": "",
            "password": "",
            "caption": "",
            "topics": {
                "getCurrentHeatingCoolingState": "zwave/Dining/thermostat/64/1/0",
                "getCurrentTemperature": "zwave/Dining/thermostat/49/1/1",
                "getTargetHeatingCoolingState": "zwave/Dining/thermostat/64/1/0",
                "getTargetTemperature": "zwave/Dining/thermostat/67/1/1",
                "setTargetHeatingCoolingState": "zwave/Dining/thermostat/64/1/0/set",
                "setTargetTemperature": "zwave/Dining/thermostat/67/1/1/set"
            },
            "heatingCoolingStateValues": [
                "Off",
                "Heat",
                "Cool",
                "Auto"
            ],
            **"maxTemperature": "28",
            "minTemperature": "15"**
        },

**Comment by Supereg** [comment]
Could you quickly clarify some things. The Error is displayed when trying to pair a fresh instance of homebridge running the mqttthing plugin with the supplied config right? What happens if you pair homebridge first, without the plugin enabled and then add the plugin configuration?

The said error only happens when maxTemperature and minTemperature are supplied, is this correct? Otherwise I'm not quite sure what you are trying to say.

**Comment by homeconnector** [comment]
1. When pairing homebridge (no accessories or platforms) - it works.

2. When adding the MQTTTHING with "maxTemperature": "28" or "minTemperature": "15" with quotes - it it causing homebridge to crash.
It took me a while to work out what was crashing (didn't know if it was IOS 14) but after trial and error I found out that the adding of quotes "" around an integer for this parameter caused homebridge to crash received when trying to add accessory on HomeKit..   I am not sure how wide spread this bug is. 

3. When the values are supplied without the quotes (it works ok).
"maxTemperature": 28 
"minTemperature": 15

Note: this bug appears in both IOS 13 and IOS 14, except it gives different error messages

IOS 14 devices (New Error Message0
Error Domain=NSCocoaErrorDomain Code=4097

IOS 13 devices 
Error adding accessory

**Comment by Supereg** [comment]
Well. Workaround: Properly supply min and max temperature as numbers and not strings.

You may want to raise an issue over at mqttthing so the plugin owner can do proper input sanitation on those values (checking that the given data type is really a number [or properly converting it])
