### ISSUE TITLE
Homebridge More than one Camera

### ISSUE THREAD

**Issue by lfiocco** [homebridge/homebridge#2643]
I posted this on the FFMPEG issues, however it might not be related to the plugin.

I have been experimenting. Fresh install of everything on Raspberry Pi this time...
I have a total of 6 cameras, they can go up to 1080, however for speed, 480x270 is good, if i see something odd, can always switch to the manufacture app and go HD.

So I had time to configure only 2 cameras before leaving, guess what? it was soooo fast... click, 8-10 seconds later i have a stream and this is on LTE..wifi even faster...thumbnails are between 10-15 seconds...

So i started adding and adding cameras util i got to 6, my full config...now everything started slowing down again.

having 6 cameras, just sitting there generating thumbnails between 60-75 seconds...for each. the streams also started to slow down also, between the time I click on the camera and the time I see the frames 45-65 seconds again...

Looks like the more cameras you add, the slower it reacts and sends live streams...

The sweet spot for me is 2 cameras. the reaction time is very good. 3,4 starts slowing down... 5-6 your at 60 seconds waiting time. No idea if it's homebridge or the plug in..

Looks like when there are many devices and generating work, nothing else can be processed until it's queued?
with 6 cameras, the other plugins also suffer.

**Comment by oznu** [comment]
@Sunoo is checking this out here: https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/706
