### ISSUE TITLE
Can't install homebridge: "bonjour-hap is no longer maintained"

### ISSUE THREAD

**Issue by yslupdates** [homebridge/homebridge#2644]
**Describe Your Problem:**
I can't install homebridge due to some dependency being deprecated.

[**Logs:**]()
root@DietPi:~# sudo npm install -g --unsafe-perm homebridge
npm WARN deprecated bonjour-hap@3.5.11: bonjour-hap is no longer maintained. Refer to the Notice section of the README.md. The library should not be used anymore
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge
+ homebridge@1.1.1
updated 1 package in 2.453s

* **Node.js Version**: v14.7.0
* **NPM Version**: 6.14.7
* **Homebridge Version**: 1.1.1
* **Operating System**: Raspbian (Dietpi)
* **Process Supervisor**: Systemd

**Comment by A-vesalius** [comment]
Can't help you with 1.1.1, but have you tried the 1.2.0 homebridge beta?  Bonjour-HAP is now EOL and being replaced by ciao. See the link below for details. Running the beta now and it works well for me. 

https://github.com/homebridge/homebridge/issues/2619

**Comment by oznu** [comment]
```
root@DietPi:~# sudo npm install -g --unsafe-perm homebridge
npm WARN deprecated bonjour-hap@3.5.11: bonjour-hap is no longer maintained. Refer to the Notice section of the README.md. The library should not be used anymore
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

homebridge@1.1.1
updated 1 package in 2.453s
```

That looks like it installed without any errors?

**Comment by oznu** [comment]
Updated comment above.
