### ISSUE TITLE
House does not work on Ipad4 IOS 10.3.3

### ISSUE THREAD

**Issue by floxboy** [homebridge/homebridge#2647]
![photo_2020-08-12_13-57-34](https://user-images.githubusercontent.com/24805643/90015503-21f9b300-dcc2-11ea-8159-bd40bcab3236.jpg)

node version 10.21.0
homebridge version 1.2.0-beta.34
homebridge work on IPhone X, Ipad Air2
dont work Ipad4 Ios 10.3.3

**Comment by floxboy** [comment]
![photo_2020-08-12_13-57-39](https://user-images.githubusercontent.com/24805643/90015879-a1878200-dcc2-11ea-9a77-ee5dcf57959e.jpg)
Node-red Bridge is work

**Comment by petr-29** [comment]
> ![photo_2020-08-12_13-57-34](https://user-images.githubusercontent.com/24805643/90015503-21f9b300-dcc2-11ea-8159-bd40bcab3236.jpg)
> 
> 
> 
> node version 10.21.0
> 
> homebridge version 1.2.0-beta.34
> 
> homebridge work on IPhone X, Ipad Air2
> 
> dont work Ipad4 Ios 10.3.3
> 
>

**Comment by Supereg** [comment]
could you check if this problem is still occurring with the latest v1.2.2?
Also it would be helpful to include log message and [HAP-NodeJS debug output](https://github.com/homebridge/HAP-NodeJS/wiki/FAQ#debug-mode) from the time when you open the non working Home App (aka it can't connect).

**Comment by Supereg** [comment]
This issue will be closed as there is no response from the author.

**Comment by 00enterausername00** [comment]
I have exactly the same problem on v1.3.5. I booted in debug mode with the flag DEBUG = HAP-NodeJS:*. When I connect from a device with 10.3.3, nothing happens in the logs. Everything was working fine before.

**Comment by definitec** [comment]
I have the same issue. 
Node.js Version: v14.17.0
NPM Version: v6.14.13
Homebridge Version: v1.3.8
Operating System: Raspbian GNU/Linux Stretch (9)
