### ISSUE TITLE
I cant install some plugins.

### ISSUE THREAD

**Issue by blogdjmaster** [homebridge/homebridge#2649]
Hello, when i try to install some plugins (like broadlink-rm) show this error:

npm WARN deprecated github-version-checker@1.2.0: Versions below v2.0.0 are outdated and should not be used anymore. Please consider upgrading to the latest release, which is v2.2.0 at this time.
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/lprhodes/homebridge-platform-helper.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2020-08-13T01_01_53_539Z-debug.log

Anyone can help me please?

**Comment by oznu** [comment]
Install git.

**Comment by blogdjmaster** [comment]
> Install git.

Is installed.

`/var/lib/homebridge
└─┬ github-version-checker@2.2.0
  ├── github-graphql-client@1.0.0
  └── semver@5.7.1`

Any other idea?

**Comment by TautFlorian** [comment]
What does git -v say?

**Comment by blogdjmaster** [comment]
> What does git -v say?

6.14.6

**Comment by TautFlorian** [comment]
That cant be true, latest available version 2.28.0, check git's website for how to instal it. https://git-scm.com/

**Comment by blogdjmaster** [comment]
> That cant be true, latest available version 2.28.0, check git's website for how to instal it. https://git-scm.com/

Its true, I installed it again and now say 2.20.1 and i can download the plugins. thanks! :+1:
