### ISSUE TITLE
Stuck on Starting Now Page After Enabling Debug Mode

### ISSUE THREAD

**Issue by ahmadnazirafiq** [homebridge/homebridge#2650]
I accidentally enabled the Debug mode via Homebridge settings. After rebooting its stuck on Starting Now page. I've looked everywhere to disable te Debug mode via SSH but no luck. Any help?
![Screenshot 2020-08-13 at 5 02 36 PM](https://user-images.githubusercontent.com/66505845/90115516-cba27800-dd86-11ea-9be8-f3425d404ea2.png)
![77287677-3dbbe700-6d2a-11ea-834f-660ddbc845ab](https://user-images.githubusercontent.com/66505845/90115535-cf35ff00-dd86-11ea-94e9-047662f346ae.png)

**Comment by oznu** [comment]
What do the logs say?

**Comment by oznu** [comment]
And please also post your config etc.

**Comment by A-vesalius** [comment]
Update to fix this -
4.25.2 (2020-08-14)
Bug Fixes
Fix a bug that caused the UI not to load when it's debug mode was enabled (#811). If you have been encountering issues after installing v4.25.1 please run this command to resolve the issue: npm install -g --unsafe-perm homebridge-config-ui-x.

**Comment by oznu** [comment]
Please reinstall the UI via ssh to fix this:

```
# cleanup
sudo npm install -g --unsafe-perm homebridge-config-ui-x
```
