### ISSUE TITLE
Do invitations work?

### ISSUE THREAD

**Issue by siddrajput** [homebridge/homebridge#2651]
**Describe Your Problem:**

Do invitations for other users work? I invited another person and when they launch their Home app, it shows "Loading accessories and scenes" but then nothing happens. It's stuck in this screen forever.
[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.18.2
* **NPM Version**: 6.14.7
* **Homebridge Version**: 1.1.1
* **Operating System**: Raspbian Lite
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment]
They should work, this side of thing is handled by Apple / iCloud though, not Homebridge.

**Comment by siddrajput** [comment]
Thanks. It worked.
