### ISSUE TITLE
homebridge on docker is using a wrong IP for camera streams

### ISSUE THREAD

**Issue by ecrode** [homebridge/homebridge#2652]
**Describe The Bug:**
When running homebridge via docker, live video sometimes works while not on a local network (via Apple TV relay), but never works while connected the local network.

**To Reproduce:**
Install any of the camera plugins (I've tried Ring and Unifi Protect) and snapshots load just fine, but live video is stuck while loading. When network traffic is captured TCP packets can be seen being sent from the correct MAC address, but arrive from an invalid IP address 169.254.x.x. Homebridge is running as connected to --net=host so it sees an internal network with 169.254.x.x address. 169.254.x.x network appears to be required for docker to route traffic to other subnetworks used by non host containers, so it cannot be removed. I cannot find a way to tie homebridge instance to a specific IP, mdns setting does not appear to effect the functionality.

**Expected behavior:**
All of the traffic from the homebridge should come from IP address shown within "IPv4 (ens192)" section of System Information tab. A way to make sure the process attaches to a specific IP is good for systems with multiple addresses.

[**Logs:**]()
Unfortunately IP addresses are not shown on the logs
Here is an example:
[8/12/2020, 9:38:47 PM] [UniFi Protect] Indoor mini: HomeKit video stream request: 640x360, 30 fps, 132 kbps.
[8/12/2020, 9:39:09 PM] [UniFi Protect] Indoor mini: Stopped video stream.
I'll be happy to provide more detailed logs with help about getting more data on them.
```
Secondary Homebridge Logs here
```

**Homebridge Config:**

`{
    "bridge": {
        "name": "Name",
        "username": "XX:58:XX:C8:XX:99",
        "port": 51343,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "debug": false,
            "options": [
                "Disable.MotionSwitch",
                "Disable.MotionSensor"
            ],
            "controllers": [
                {
                    "address": "ipaddress",
                    "name": "name",
                    "password": "pass",
                    "username": "user"
                }
            ],
            "platform": "UniFi Protect"
        },
        {
            "name": "Config",
            "port": 23555,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "debug": false,
            "proxyHost": "homekit.domain",
            "platform": "config"
        }
    ]
}`

**Screenshots:**
![io](https://user-images.githubusercontent.com/26380074/90184885-d60f4280-dd83-11ea-9f18-67980575fe28.JPG)
![set](https://user-images.githubusercontent.com/26380074/90185089-27b7cd00-dd84-11ea-8b52-612d24eae6f2.JPG)

**Environment:**

* **Node.js Version**: v12.18.3
* **NPM Version**: 6.14.6
* **Homebridge Version**: 1.1.1
* **Operating System**:  Vmware photon OS
* **Process Supervisor**: Docker

**Comment by oznu** [comment]
This is fixed in Homebridge 1.1.3. The IP selected to stream the video is now the one that was used by the inbound request.
