### ISSUE TITLE
How to get rid of the HAP-NodeJS dependency in Homebridge plugins?

### ISSUE THREAD

**Issue by palasinio** [homebridge/homebridge#2653]
As told, the best practice is to not use HAP-NodeJS as a dependency of Homebridge plugins and use HAP-NodeJS of the Homebridge instance instead.

I didn‘t find this in your wiki. The first line of the examples is „require hap-nodes“...

I‘m not a developer or programmer and just want to try if I can remove this dependency of a no longer maintained plugin.

Is there kind of recipe how to accomplish this?

**Comment by oznu** [comment]
The HAP object you should use is passed in via the `api` argument of your plugin constructor.

You can access all the HAP methods using `api.hap.xxxxxxx`.

There is no need to install a seperate copy of HAP-NodeJS or Homebridge as a prod dependency.
