### ISSUE TITLE
Turn on lights transmits brightness next to the on command

### ISSUE THREAD

**Issue by Sonsi79** [homebridge/homebridge#2656]
Since update to 1.1.2 after a long time on 0.x i have a strange error.
I'm using hombridge just with one plugin (homebridge-fhem) to pair all devices with FHEM.

Since update Homebridge transmits the "on" command also with a "brightness" (100%) value by tuning on a Philips Hue Lamp in Apple HomeKit. By using Eve app this error doesn't exists.
The old Version of Homebridge works fine in both apps.

My problem is that every lamp starts with 100% brightness (255) also when it was turned off with a brightness of 40% (102).
Is there any workaround to fix this?

thnx and greetings from Germany
Christoph

**Comment by melnyk10** [comment]
I have a similar problem. When I turn on the RGB strip on iPhone, homebridge send to events, On, Brightness. Also when I changing brightness On event also sends.

**Comment by jvmahon** [comment]
In the iOS Home App, whenever you change brightness, it always triggers the .on('set'   for both the "On" and the "Brightness" characteristic. When the .on('set' is triggered, you can test the new value against the existing value -- if they are the same, you can just discard it (depending on your application).  For an example, see this code: https://github.com/jvmahon/homebridge-hubitat/blob/master/lib/Setup%20LightsFansPlugs.js

This is for a Homebridge to Hubitat plugin I'm working on.

At line 119 I'm setting up a lightbulb.

At line 130, I set up the .on('set' for a change to Characteristic.On for the lightbulb.  When .on('set' is called for that characteristics, this.value is the "old" value. The new value (newHomekitValue) isn't set until you call the callback (line 136). After line 136, this.value becomes the new value newHomekitValue.  So, in that code, this.value is the "old" value and I compare newHomekitValue to the old value (line 132) and then, only if they  are different, I send  the data to Hubitat 134. That way, if what is really changing is the Brighness (lines 142-152), then when the On and Brightness are both triggered, the "On' gets filtered out if its the same, but Brighness always sends. Note, you must always call the callback (line 136) even if you are doing nothing else.

Hope this is helpful to you.

**Comment by Supereg** [comment]
afaik the behavior was never different. The Home App always sends the brightness in addition to the On command, except if it is sure that the brightness is set correctly.
