### ISSUE TITLE
Blacklist devices

### ISSUE THREAD

**Issue by timwegenerDE** [homebridge/homebridge#2659]
Hi there,

it would be nice if I could hide devices, so they don't get exposed to HomeKit. Some plugins have no (easy) possibility to decide wich devices should be exposed - e.g. https://github.com/ebaauw/homebridge-hue/issues/747#issuecomment-674527387

In combination with Homebridge UI it could be very easy to just hide devices from HomeKit.

Kind regards,
Tim

**Comment by iMonZ** [comment]
Is there something new?

**Comment by timwegenerDE** [comment]
🤷🏻‍♂️
