### ISSUE TITLE
Request Notification On Update Available

### ISSUE THREAD

**Issue by masterfordev** [homebridge/homebridge#2663]
Hello, with the products of “koogeek” i remember when an update is available for the device, the “home app” show a notification where say update available for that device. Maybe you can implement such an option with homebridge to show in the home app when an update for homebridge or a plugin is available. 

This in order for us to be able to go to our server and apply the available updates.

I hope there is some way to implement this. Greetings and thank you for your great work.

**Comment by codyc1515** [comment]
I’m fairly sure this is a flag trigger on Apple’s side so wouldn’t be possible.

**Comment by mdombrowski13** [comment]
Maybe kick an email out from homebridge itself?

**Comment by masterfordevs** [comment]
> Maybe kick an email out from homebridge itself?

Maybe @oznu can add an option for Email Notification from the Homebridge Config UI X. Its a good idea.

**Comment by oznu** [comment]
You can get email alerts for your plugin updates via GitHub:

![A88C7766-B457-4D99-A71E-665B73CAA578](https://user-images.githubusercontent.com/3979615/92297307-51c66e80-ef81-11ea-9712-822270da2997.gif)

**Comment by masterfordevs** [comment]
I know. For now is enought with the notifications from github. Maybe later is possible add an option.
