### ISSUE TITLE
Television Set Top Box

### ISSUE THREAD

**Issue by Faisalthe01** [homebridge/homebridge#2665]
Hi,

The update have 2 new categories found in iOS 14 **Television Set Top Box** and **Television Streaming Stick**

Does anyone know where i can find more information on it, like its characteristics. I had a look on Developer page but nothing available

Thank you

https://github.com/homebridge/HAP-NodeJS/releases/tag/v0.7.9

**Comment by oznu** [comment]
They are likely just to make the Home app display different icons for the existing [Television](https://developers.homebridge.io/#/service/Television) service.

**Comment by Faisalthe01** [comment]
> They are likely just to make the Home app display different icons for the existing [Television](https://developers.homebridge.io/#/service/Television) service.

Hey mate, thanks for the reply. Any extra code that needs to go in existing Television accessory for those icons to appear?

**Comment by Supereg** [comment]
These two are just two new accessory **Categories**. Device Categories have no real functional meaning and really only are used to display the icon on the pairing screen. For those new categories there aren’t even new icons, there is just the generic „house“ icon displayed.

See https://github.com/homebridge/HAP-NodeJS/blob/f563641477188e1ac0cbb9fdf47a77c0cbeede5d/src/lib/Accessory.ts#L48
