### ISSUE TITLE
Enhancement/ Feature Request: Add automation to Homebridge

### ISSUE THREAD

**Issue by mdombrowski13** [homebridge/homebridge#2668]
Apple Homekit automations are lacking especially with Homebridge accessories.
EX: ADT Pulse And Foscam Cameras. They have 4 settings Off/Stay/Home/Away.  Apple home kit does not allow automation based on all these settings.  It would be nice to set cameras to arm home when I press arm stay on ADT Pulse.

I think a tab where people could design their own automation plug ins much like the way homebridge supports plugin's would be great.  A separate tab for automation plug ins and an automation tab for creating an automation/viewing list of automations.

**Comment by oznu** [comment]
Checkout https://github.com/NorthernMan54/node-red-contrib-homebridge-automation

**Comment by mdombrowski13** [comment]
Yeah i used it for a while and even a member of a facebook group for it.  It defeats The simplicity of homebridge imo. Thus why an integrated automations tab would be my ask.

**Comment by angyalZK** [comment]
Automation bugs not with HomeBridge, iCloud and HomeKit was modified and has some bugs. Try to sing out iCloud on TV (or on device that you use as home hub) and sign in again. If you using iOS 14 beta on your iPhone, it's recommended on iPhone too.
