### ISSUE TITLE
I delete one platform from config but still showing in Home app

### ISSUE THREAD

**Issue by toshibochan** [homebridge/homebridge#2669]
I delete one platform from config.json but still showing in Home app. How I can make disappear with out affect other accessories and platform. I can just delete cachedAccessories and restart Homebridge? what happens if I delete cachedAccessories?

**Comment by oznu** [comment]
If you uninstall the plugin they should be purged from the cache on the next startup.

**Comment by toshibochan** [comment]
I will try
