### ISSUE TITLE
Homebridge not starting after update from 1.1.2 to 1.1.3, works again after rollback to 1.1.2

### ISSUE THREAD

**Issue by jochenpa** [homebridge/homebridge#2670]
**Describe The Bug:**
I Updated homebridge to 1.1.3, after that it did not start
Here a script of what I did:

pi@raspberrypi:~ $ npm install homebridge@latest
npm WARN pi@1.0.0 No description
npm WARN pi@1.0.0 No repository field.

+ homebridge@1.1.3
removed 1 package, updated 1 package and audited 932 packages in 245.773s

15 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

Now I did a restart by using the web interface ...

pi@raspberrypi:~ $ sudo journalctl -fau homebridge
Sep 07 17:02:31 raspberrypi homebridge[1487]: [9/7/2020, 5:02:31 PM] [Config] Homebridge restart request received
Sep 07 17:02:32 raspberrypi homebridge[1487]: [9/7/2020, 5:02:32 PM] [Config] Executing restart command: sudo -n systemctl restart homebridge
Sep 07 17:02:32 raspberrypi sudo[28304]:       pi : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/systemctl restart homebridge
Sep 07 17:02:32 raspberrypi sudo[28304]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 07 17:02:32 raspberrypi homebridge[1487]: [9/7/2020, 5:02:32 PM] Got SIGTERM, shutting down Homebridge...
Sep 07 17:02:32 raspberrypi systemd[1]: Stopping Node.js HomeKit Server...
Sep 07 17:02:37 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Sep 07 17:02:37 raspberrypi systemd[1]: homebridge.service: Killing process 1509 (homebridge-conf) with signal SIGKILL.
Sep 07 17:02:37 raspberrypi systemd[1]: homebridge.service: Killing process 28303 (sh) with signal SIGKILL.
Sep 07 17:02:37 raspberrypi systemd[1]: homebridge.service: Killing process 28304 (sudo) with signal SIGKILL.
Sep 07 17:02:37 raspberrypi systemd[1]: homebridge.service: Killing process 28309 (systemctl) with signal SIGKILL.
Sep 07 17:02:38 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Sep 07 17:02:38 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Sep 07 17:02:38 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Sep 07 17:02:46 raspberrypi homebridge[28310]: [9/7/2020, 5:02:46 PM] Loaded config.json with 0 accessories and 2 platforms.
Sep 07 17:02:46 raspberrypi homebridge[28310]: [9/7/2020, 5:02:46 PM] ---
Sep 07 17:02:54 raspberrypi homebridge[28310]: [9/7/2020, 5:02:54 PM] Loaded plugin: homebridge-config-ui-x@4.27.0
Sep 07 17:02:54 raspberrypi homebridge[28310]: [9/7/2020, 5:02:54 PM] Registering platform 'homebridge-config-ui-x.config'
Sep 07 17:02:54 raspberrypi homebridge[28310]: [9/7/2020, 5:02:54 PM] ---
Sep 07 17:02:54 raspberrypi homebridge[28310]: [9/7/2020, 5:02:54 PM] Loaded plugin: homebridge-fhem@0.5.17
Sep 07 17:02:54 raspberrypi homebridge[28310]: homebridge API version: 2.6
Sep 07 17:02:54 raspberrypi homebridge[28310]: this is homebridge-fhem 0.5.17
Sep 07 17:03:12 raspberrypi homebridge[28310]: [9/7/2020, 5:03:12 PM] Registering platform 'homebridge-fhem.FHEM'
Sep 07 17:03:12 raspberrypi homebridge[28310]: [9/7/2020, 5:03:12 PM] ---
Sep 07 17:03:12 raspberrypi homebridge[28310]: [9/7/2020, 5:03:12 PM] Loading 2 platforms...
Sep 07 17:03:12 raspberrypi homebridge[28310]: [9/7/2020, 5:03:12 PM] [Config] Initializing config platform...
Sep 07 17:03:12 raspberrypi homebridge[28310]: Server listening on: http://<ip>:8282
Sep 07 17:03:13 raspberrypi homebridge[28310]: [9/7/2020, 5:03:13 PM] Error: option 'insecure' clashes with existing property 'insecure' on Command
Sep 07 17:03:13 raspberrypi homebridge[28310]: - call storeOptionsAsProperties(false) to store option values safely,
Sep 07 17:03:13 raspberrypi homebridge[28310]: - or call storeOptionsAsProperties(true) to suppress this check,
Sep 07 17:03:13 raspberrypi homebridge[28310]: - or change option name
Sep 07 17:03:13 raspberrypi homebridge[28310]: Read more on https://git.io/JJc0W
Sep 07 17:03:13 raspberrypi homebridge[28310]:     at Command._checkForOptionNameClash (/home/pi/node_modules/commander/index.js:472:13)
Sep 07 17:03:13 raspberrypi homebridge[28310]:     at Command._optionEx (/home/pi/node_modules/commander/index.js:499:10)
Sep 07 17:03:13 raspberrypi homebridge[28310]:     at Command.option (/home/pi/node_modules/commander/index.js:622:17)
Sep 07 17:03:13 raspberrypi homebridge[28310]:     at new HomebridgeConfigUi (/home/pi/node_modules/homebridge-config-ui-x/src/index.ts:30:8)
Sep 07 17:03:13 raspberrypi homebridge[28310]:     at config.platforms.forEach (/home/pi/node_modules/homebridge/src/server.ts:397:40)
Sep 07 17:03:13 raspberrypi homebridge[28310]:     at Array.forEach (<anonymous>)
Sep 07 17:03:13 raspberrypi homebridge[28310]:     at Server.loadPlatforms (/home/pi/node_modules/homebridge/src/server.ts:374:27)
Sep 07 17:03:13 raspberrypi homebridge[28310]:     at Server.start (/home/pi/node_modules/homebridge/src/server.ts:153:29)
Sep 07 17:03:13 raspberrypi homebridge[28310]:     at cli (/home/pi/node_modules/homebridge/src/cli.ts:80:10)
Sep 07 17:03:13 raspberrypi homebridge[28310]:     at Object.<anonymous> (/home/pi/node_modules/homebridge/bin/homebridge:17:22)
Sep 07 17:03:14 raspberrypi homebridge[28310]: [9/7/2020, 5:03:13 PM] Got SIGTERM, shutting down Homebridge...

After I roll back to 1.1.2 it works again:
pi@raspberrypi:~ $ npm install homebridge@1.1.2
npm WARN pi@1.0.0 No description
npm WARN pi@1.0.0 No repository field.

+ homebridge@1.1.2
added 1 package from 1 contributor, updated 1 package and audited 933 packages in 423.316s

15 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

pi@raspberrypi:~ $ sudo journalctl -fau homebridge
Sep  7 17:16:26 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Sep  7 17:16:42 raspberrypi homebridge[28855]: [9/7/2020, 5:16:42 PM] Loaded config.json with 0 accessories and 2 platforms.
Sep  7 17:16:42 raspberrypi homebridge[28855]: [9/7/2020, 5:16:42 PM] ---
Sep  7 17:16:57 raspberrypi homebridge[28855]: [9/7/2020, 5:16:57 PM] Loaded plugin: homebridge-config-ui-x@4.27.0
Sep  7 17:16:57 raspberrypi homebridge[28855]: [9/7/2020, 5:16:57 PM] Registering platform 'homebridge-config-ui-x.config'
Sep  7 17:16:57 raspberrypi homebridge[28855]: [9/7/2020, 5:16:57 PM] ---
Sep  7 17:16:57 raspberrypi homebridge[28855]: [9/7/2020, 5:16:57 PM] Loaded plugin: homebridge-fhem@0.5.17
Sep  7 17:16:57 raspberrypi homebridge[28855]: homebridge API version: 2.6
Sep  7 17:16:57 raspberrypi homebridge[28855]: this is homebridge-fhem 0.5.17
Sep  7 17:17:01 raspberrypi CRON[28879]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Sep  7 17:17:14 raspberrypi homebridge[28855]: [9/7/2020, 5:17:14 PM] Registering platform 'homebridge-fhem.FHEM'
Sep  7 17:17:14 raspberrypi homebridge[28855]: [9/7/2020, 5:17:14 PM] ---
Sep  7 17:17:14 raspberrypi homebridge[28855]: [9/7/2020, 5:17:14 PM] Loading 2 platforms...
Sep  7 17:17:14 raspberrypi homebridge[28855]: [9/7/2020, 5:17:14 PM] [Config] Initializing config platform...
Sep  7 17:17:14 raspberrypi homebridge[28855]: [9/7/2020, 5:17:14 PM] [Config] Spawning homebridge-config-ui-x with PID 28889
Sep  7 17:17:14 raspberrypi homebridge[28855]: [9/7/2020, 5:17:14 PM] [FHEM] Initializing FHEM platform...
Sep  7 17:17:24 raspberrypi homebridge[28855]: starting longpoll: http://127.0.0.1:8083/fhem?XHR=1&inform=type=status;addglobal=1;filter=.*;since=null;fmt=JSON&timestamp=1599491844604
Sep  7 17:17:24 raspberrypi homebridge[28855]: [9/7/2020, 5:17:24 PM] [FHEM] Fetching FHEM devices...
Sep  7 17:17:24 raspberrypi homebridge[28855]: Server listening on: http://<ip>:8282
Sep  7 17:17:25 raspberrypi homebridge[28855]: [9/7/2020, 5:17:25 PM] [FHEM] Fetching FHEM devices...
Sep  7 17:17:25 raspberrypi homebridge[28855]: [9/7/2020, 5:17:25 PM] [FHEM] Checking devices and attributes...
...

**To Reproduce:**
Update homebridge to 1.1.3 on my system.

**Expected behavior:**
Restarting without a problem like the version before.

**Homebridge Config:**
```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "manufacturer": "homebridge.io",
        "model": "homebridge",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "indigo",
            "restart": "sudo -n systemctl restart homebridge",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": false,
            "log": {
                "method": "custom",
                "command": "journalctl -o cat -n 500 -f -u homebridge"
            },
            "platform": "config"
        },
        {
            "platform": "FHEM",
            "name": "FHEM",
            "server": "127.0.0.1",
            "port": "8083",
            "filter": "room=Homekit"
        }
    ],
    "accessories": []
}
```

**Environment:**
Environment:
    Node.js Version: v10.20.1
    NPM Version: v6.14.8
    Operating System: raspbian
    Homebridge Version: v1.1.3

**Comment by dgreif** [comment]
@Supereg it looks like this issue is caused by the newer version of `commander`.  See https://github.com/tj/commander.js/blob/master/CHANGELOG.md#added-1 - `Breaking throw an error if there might be a clash between option name and a Command property, with advice on how to resolve`.  The logs above show issues with the `insecure` option.  I'm also running into issues with the `-P` or `--plugin-path` option in my dev environment.  Not sure what the best fix is, but we may start seeing wide spread issues with this if the `insecure` flag is breaking.

**Comment by jochenpa** [comment]
Hi

Sorry, but the "advice on how to resolve" looks like infos for a programmer to me, I am only a user.
Where is this "insecure", I don't see it in the config.
Where do I set "storeOptionsAsProperties(true)" for example?
Could I set that in the Homebridge Config to let it work again? In which section?
Where is this "insecure", I don't see it in the config.
Or should I wait till someone fixed this up and I can update to 1.1.4 or such?

Jochen

**Comment by jochenpa** [comment]
Hi again

I possibly found my command property:
/home/pi/homebridge/options:
# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS=-I -U /home/pi/homebridge
 
# To enable web terminals via homebridge-config-ui-x 
HOMEBRIDGE_CONFIG_UI_TERMINAL=1
 
# If you uncomment the following line, homebridge will log more
# You can display this via systemd's journalctl: journalctl -f -u homebridge
# DEBUG=*

Is "-I" the option for "insecure"?
So I only need to remove that option flag?
(I use an old raspberry pi 1B ... so it took a while to test it and revert back ...)

Jochen

**Comment by jochenpa** [comment]
Hi again

Next problem, now it don't like the "no-timestamp" option which I did not set ...
Help ... :-)

```
Sep 07 19:52:29 raspberrypi homebridge[1738]: [9/7/2020, 7:52:29 PM] Loading 2 platforms...
Sep 07 19:52:29 raspberrypi homebridge[1738]: [9/7/2020, 7:52:29 PM] [Config] Initializing config platform...
Sep 07 19:52:29 raspberrypi homebridge[1738]: Server listening on: http://<ip>:8282
Sep 07 19:52:31 raspberrypi homebridge[1738]: [9/7/2020, 7:52:31 PM] Error: option 'no-timestamp' clashes with existing property 'timestamp' on Command
Sep 07 19:52:31 raspberrypi homebridge[1738]: - call storeOptionsAsProperties(false) to store option values safely,
Sep 07 19:52:31 raspberrypi homebridge[1738]: - or call storeOptionsAsProperties(true) to suppress this check,
Sep 07 19:52:31 raspberrypi homebridge[1738]: - or change option name
Sep 07 19:52:31 raspberrypi homebridge[1738]: Read more on https://git.io/JJc0W

```

**Comment by Supereg** [comment]
@dgreif I see, but can't reproduce the exception on my machine when setting the insecure option (or other) 🤔

**Comment by Supereg** [comment]
@jochenpa currently working on this issue, trying to release a fix in the next few hours. in the mean time you may revert to 1.1.2

**Comment by Supereg** [comment]
@jochenpa v1.14 which will be released shortly should fix your problem.

**Comment by jochenpa** [comment]
Hi

Oh ... thank you.
Yes, I go back to 1.1.2 for now.


Jochen

**Comment by jochenpa** [comment]
Hi

Sorry, something went wrong with 1.1.4:

```
Sep 07 20:36:04 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Sep 07 20:36:13 raspberrypi homebridge[3263]: /home/pi/node_modules/commander/index.js:685
Sep 07 20:36:13 raspberrypi homebridge[3263]:       throw new Error('call .storeOptionsAsProperties() before adding options');
Sep 07 20:36:13 raspberrypi homebridge[3263]:             ^
Sep 07 20:36:13 raspberrypi homebridge[3263]: Error: call .storeOptionsAsProperties() before adding options
Sep 07 20:36:13 raspberrypi homebridge[3263]:     at Command.storeOptionsAsProperties (/home/pi/node_modules/commander/index.js:685:13)
Sep 07 20:36:13 raspberrypi homebridge[3263]:     at cli (/home/pi/node_modules/homebridge/src/cli.ts:30:6)
Sep 07 20:36:13 raspberrypi homebridge[3263]:     at Object.<anonymous> (/home/pi/node_modules/homebridge/bin/homebridge:17:22)
Sep 07 20:36:13 raspberrypi homebridge[3263]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
Sep 07 20:36:13 raspberrypi homebridge[3263]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
Sep 07 20:36:13 raspberrypi homebridge[3263]:     at Module.load (internal/modules/cjs/loader.js:653:32)
Sep 07 20:36:13 raspberrypi homebridge[3263]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Sep 07 20:36:13 raspberrypi homebridge[3263]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Sep 07 20:36:13 raspberrypi homebridge[3263]:     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
Sep 07 20:36:13 raspberrypi homebridge[3263]:     at startup (internal/bootstrap/node.js:283:19)
Sep 07 20:36:13 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Sep 07 20:36:13 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

```

**Comment by Samfox2** [comment]
Same for me, 1.1.4 is broken

**Comment by Supereg** [comment]
sorry, completely messed up, 1.1.5 is out

**Comment by jochenpa** [comment]
Hey, please wait a little bit before closing this issue ...
I still have issues:

```
Sep 07 20:51:26 raspberrypi systemd[1]: Started Node.js HomeKit Server.
Sep 07 20:51:34 raspberrypi homebridge[3632]: [9/7/2020, 8:51:34 PM] Loaded config.json with 0 accessories and 2 platforms.
Sep 07 20:51:34 raspberrypi homebridge[3632]: [9/7/2020, 8:51:34 PM] ---
Sep 07 20:51:42 raspberrypi homebridge[3632]: [9/7/2020, 8:51:42 PM] Loaded plugin: homebridge-config-ui-x@4.27.0
Sep 07 20:51:42 raspberrypi homebridge[3632]: [9/7/2020, 8:51:42 PM] Registering platform 'homebridge-config-ui-x.config'
Sep 07 20:51:42 raspberrypi homebridge[3632]: [9/7/2020, 8:51:42 PM] ---
Sep 07 20:51:42 raspberrypi homebridge[3632]: [9/7/2020, 8:51:42 PM] Loaded plugin: homebridge-fhem@0.5.17
Sep 07 20:51:42 raspberrypi homebridge[3632]: homebridge API version: 2.6
Sep 07 20:51:42 raspberrypi homebridge[3632]: this is homebridge-fhem 0.5.17
Sep 07 20:51:58 raspberrypi homebridge[3632]: [9/7/2020, 8:51:58 PM] Registering platform 'homebridge-fhem.FHEM'
Sep 07 20:51:58 raspberrypi homebridge[3632]: [9/7/2020, 8:51:58 PM] ---
Sep 07 20:51:58 raspberrypi homebridge[3632]: [9/7/2020, 8:51:58 PM] Loading 2 platforms...
Sep 07 20:51:58 raspberrypi homebridge[3632]: [9/7/2020, 8:51:58 PM] [Config] Initializing config platform...
Sep 07 20:51:58 raspberrypi homebridge[3632]: Server listening on: http://<ip>:8282
Sep 07 20:52:00 raspberrypi homebridge[3632]: [9/7/2020, 8:52:00 PM] Error: Storage path was already accessed and cannot be changed anymore. Try initializing your custom storage path earlier!
Sep 07 20:52:00 raspberrypi homebridge[3632]:     at Function.setStoragePath (/home/pi/node_modules/homebridge/src/user.ts:32:13)
Sep 07 20:52:00 raspberrypi homebridge[3632]:     at commander_1.default.storeOptionsAsProperties.version.option.option.option.option.option.option.option.option.option.path (/home/pi/node_modules/homebridge/src/cli.ts:42:152)
Sep 07 20:52:00 raspberrypi homebridge[3632]:     at Command.on (/home/pi/node_modules/commander/index.js:541:15)
Sep 07 20:52:00 raspberrypi homebridge[3632]:     at Command.emit (events.js:198:13)
Sep 07 20:52:00 raspberrypi homebridge[3632]:     at Command.parseOptions (/home/pi/node_modules/commander/index.js:1120:18)
Sep 07 20:52:00 raspberrypi homebridge[3632]:     at Command._parseCommand (/home/pi/node_modules/commander/index.js:964:25)
Sep 07 20:52:00 raspberrypi homebridge[3632]:     at Command.parse (/home/pi/node_modules/commander/index.js:801:10)
Sep 07 20:52:00 raspberrypi homebridge[3632]:     at new HomebridgeConfigUi (/home/pi/node_modules/homebridge-config-ui-x/src/index.ts:32:8)
Sep 07 20:52:00 raspberrypi homebridge[3632]:     at config.platforms.forEach (/home/pi/node_modules/homebridge/src/server.ts:397:40)
Sep 07 20:52:00 raspberrypi homebridge[3632]:     at Array.forEach (<anonymous>)
Sep 07 20:52:00 raspberrypi homebridge[3632]: [9/7/2020, 8:52:00 PM] Got SIGTERM, shutting down Homebridge...
Sep 07 20:52:05 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Sep 07 20:52:05 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

```

**Comment by Supereg** [comment]
@jochenpa would be nice if you could supply your startup options

**Comment by jochenpa** [comment]
Hi

I have changed like this:
`HOMEBRIDGE_OPTS=--user-storage-path /home/pi/homebridge`

Whole file: (/home/pi/homebridge/options)
```
# Defaults / Configuration options for homebridge
# The following settings tells homebridge where to find the config.json file and where to persist the data (i.e. pairing and others)
HOMEBRIDGE_OPTS=--user-storage-path /home/pi/homebridge
 
# To enable web terminals via homebridge-config-ui-x 
HOMEBRIDGE_CONFIG_UI_TERMINAL=1
 
# If you uncomment the following line, homebridge will log more
# You can display this via systemd's journalctl: journalctl -f -u homebridge
# DEBUG=*

```

/etc/systemd/system/homebridge.service:
```
[Unit]
Description=Node.js HomeKit Server
After=syslog.target network-online.target
 
[Service]
Type=simple
User=pi
EnvironmentFile=/home/pi/homebridge/options
ExecStart=/home/pi/node_modules/homebridge/bin/homebridge $HOMEBRIDGE_OPTS
Restart=on-failure
RestartSec=10
KillMode=mixed
TimeoutStopSec=10
 
[Install]
WantedBy=multi-user.target

```

**Comment by jochenpa** [comment]
Going to bed for now, I can test anything in about 12 hours ...
I will promise to close this issue myself if I have a working version which is higher than 1.1.2 :-)

Jochen

**Comment by Supereg** [comment]
the contents of the file `/home/pi/homebridge/options` would be of interest. As this is probably the place were `$HOMEBRIDGE_OPTS` is defined.

**Comment by jochenpa** [comment]
Hi
That file is also in my post ...

**Comment by dgreif** [comment]
@Supereg with `1.1.5`, the error about `--plugin-path` is gone, but now I'm getting `Error: Storage path was already accessed and cannot be changed anymore. Try initializing your custom storage path earlier!`.  For reference, my command that I'm running is `homebridge -P ./release-homebridge -U ./.homebridge`.  This is a test script that I use for local development in `homebridge-ring`.

**Comment by Supereg** [comment]
we reverted to an older v5, seemingly more stable version of `commander` with the 1.1.6 update, which fixes mentioned issues. We may reach out in the future when we decide to upgrade to the v6 version. Sorry for the mess.

**Comment by jochenpa** [comment]
Yes it works again, thank you.
You may close this Bug now.

**Comment by paulw11** [comment]
I still have this issue - I have tried downgrading to 1.1.3, but Homebridge is just stuck in a restart loop reporting a conflict with the insecure parameter

**Comment by paulw11** [comment]
I was able to get Homebridge to start by commenting line 499 of commander/index.js so that it omits the duplicate check, but this is obviously just a work-around

**Comment by gillesguillemin** [comment]
Just being hit by the same problem on 1.1.6 too.

About to try @paulw11 suggestion but something fishy is still going on.

**Comment by gillesguillemin** [comment]
Ok, never mind me, for whatever reason 1.1.6 wasn't being flagged as (largely) outdated 🤷

**Comment by gillesguillemin** [comment]
Actually, do mind me, issue still happening on 1.2.3 too as soon as I uncommented `Commander`'s line 499
