### ISSUE TITLE
Can I develop for selling?

### ISSUE THREAD

**Issue by dinosaur156** [homebridge/homebridge#2672]
Nowadays, I have developed Homekit in Node-red to simulate the door and the light to control my car by raspberry pi. To switch on, and start engine.
I'd like to sell it. Is it possible? I know that I copy and develop. Is it illegal?

**Comment by oznu** [comment]
What you can and can't do with Homebridge is covered in the project licence:

https://github.com/homebridge/homebridge/blob/master/LICENSE

You should also check the license for each of the dependencies Homebridge uses as they may have their own distribution restrictions.
