### ISSUE TITLE
Homebridge log file shows date as MM/DD/YY, how to change

### ISSUE THREAD

**Issue by Muller59** [homebridge/homebridge#2674]
Running homebridge Version 1.1.6 on lubuntu 20.04
Date set correct in os for user id homebridge
  $ date
  2020-09-09T14:30:14 CEST

the homebridge log shows: [9/8/2020, 10:23:52 PM] [HB Supervisor] Started Homebridge v1.1.6 with PID: 1231

i want date and time as DD/MM/YYYY 22:23:52 (24 hr format, like the os)

there is no config option that i can find to do that.
What am i missing?

never mind, found an answer here: https://github.com/oznu/homebridge-config-ui-x/issues/229
it seems this is a node.js issue, not a homebridge issue.

**Comment by oznu** [comment]
I think `YYYY-MM-DD 22:23:52` would be the most universally accepted format.

While it's not what everyone may use on a day to day basis, there is no confusion about what date `YYYY-MM-DD` is, unlike the ambiguity of using `MM/DD/YYYY` or `DD/MM/YYYY`.

**Comment by Muller59** [comment]
> I think YYYY-MM-DD 22:23:52 would be the most universally accepted format.
@oznu 
that would be fine. 
But since this seems a nodejs problem, how to go about is?

**Comment by oznu** [comment]
It's just the use of `toLocaleString()` that does not work as expected in Node.js. There is nothing stopping us from formatting the date however we like manually.

**Comment by Muller59** [comment]
in the meantime i went over to nodejs.org to see if this error was ever reported.
i could not find anything, so i reported the issue. here-> https://github.com/nodejs/node/issues/35140
i'd rather fix the source of the  problem than mitigate the symptoms. 

however, further research brought to light this is by design, not by accident, so the only way forward seems to be the band-aid instead of the cure. 

thanks anyway for your response.

**Comment by oznu** [comment]
It looks like this is already addressed in Node.js 14.

v14.x:

```
> new Date().toLocaleString()
'10/09/2020, 21:19:18'

> new Date().toLocaleString('en-AU')
'10/09/2020, 9:21:25 pm'

> new Date().toLocaleString('en-US')
'9/10/2020, 9:21:27 PM'

> new Date().toLocaleString('de-DE')
'10.9.2020, 21:21:53'
```

v12.x:

```
> new Date().toLocaleString()
'9/10/2020, 21:19:38'

> new Date().toLocaleString('en-AU')
'9/10/2020, 9:22:36 PM'

> new Date().toLocaleString('en-US')
'9/10/2020, 9:22:29 PM

> new Date().toLocaleString('de-DE')
'9/10/2020, 21:22:21'
```

**Comment by Muller59** [comment]
Thanks. Guess i'll install version 14 then.
i'll close this issue.

**Comment by oznu** [comment]
If you are running the Homebridge UI on macOS or Linux you can update using:

```
sudo hb-service update-node 14.10.0
```

**Comment by oznu** [comment]
Confirmed updating fixed this log timestamp:

![image](https://user-images.githubusercontent.com/3979615/92724310-b9c7eb00-f3ad-11ea-8049-173bf3a29c5a.png)

**Comment by danfratamico** [comment]
Example to change to US locale:

1. SSH into Linux and run "locale". Verify it is not set to en_US.
2. sudo vi /etc/default/locale
3. Update to "LANG=en_US.UTF-8"
4. Reboot
