### ISSUE TITLE
2nd Instance appears to start all 1st Instance Plugins

### ISSUE THREAD

**Issue by proactivematter** [homebridge/homebridge#2675]
Hey all,

I'm running homebridge on my Mac. I successfully created a second instance using "sudo hb-service install".

My issue is that this 2nd instance is somehow initializing all of the 1st instance's plugins, as can be seen in the 2nd instance's log and plugins page. This confuses me since I have not yet began to ad anything to the freshly created config.json of the 2nd instance. Why is this happening?

I would like to run 2 independent instances, each with their own set of plugins.

Please assist. Thank you.

**Comment by oznu** [comment]
https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command#multiple-instances

Note that the default will `hb-service install` command will use the config in `~/.homebridge`.

**Comment by proactivematter** [comment]
Sorry, I thought it would be understood that I used `hb-service install` with a different `--service-name` and different port from my default homebridge instance.

More specifically, I have one instance called "Homebridge" and one instance called "Homeyamaha", yet "Homeyamaha" lists all my plugins from the 1st instance on it.

What am I missing?

**Comment by ebaauw** [comment]
Homebridge loads all installed plugins on startup, but only starts plugins listed under `platforms` or `accessories`.  Set `plugins` in config.json to whitelist which installed plugins are to be loaded.

**Comment by proactivematter** [comment]
Thanks @ebaauw, got everything set up.

@oznu I would suggest adding @ebaauw's instructions from #287 to the #multiple-instances guide.

Thanks for the help.
