### ISSUE TITLE
Homekit Not Responding

### ISSUE THREAD

**Issue by paiigebowliin** [homebridge/homebridge#2676]
**Describe Your Problem:**
Homekit devices are showing "Not Responding" in the Home app, but all the devices are working fine in the Homebridge browser under "Accessories".

[**Logs:**]()

**From last known working task**

[37m[9/11/2020, 6:01:02 PM] [39m[36m[myQ] [39mGarage Door Opener: Opening.
[37m[9/11/2020, 6:01:15 PM] [39m[36m[myQ] [39mGarage Door Opener: Open.
[37m[9/11/2020, 6:01:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:02:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:03:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:03:53 PM] [39m[36m[myQ] [39mGarage Door Opener: Closing.
[37m[9/11/2020, 6:04:07 PM] [39m[36m[myQ] [39mGarage Door Opener: Closed.
[37m[9/11/2020, 6:04:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:05:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:06:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:07:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:08:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:09:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:10:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:11:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:12:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:13:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:14:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:15:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:16:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:17:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:18:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:19:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:20:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:21:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:22:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:23:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:24:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:25:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:26:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:27:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:28:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:29:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:30:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:31:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:32:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:33:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:34:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:35:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:36:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:37:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:38:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:39:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:40:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:41:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:42:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:43:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:44:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:45:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:46:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:47:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE181400054D22 Baker's Lamp
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B4026 Door Lamp
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140005388C Front Porch Bulb 1
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814000537CD Front Porch Bulb 2
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002DA22 Paige’s Lamp
[37m[9/11/2020, 6:48:07 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE181400054D22 Baker's Lamp
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B4026 Door Lamp
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140005388C Front Porch Bulb 1
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814000537CD Front Porch Bulb 2
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002DA22 Paige’s Lamp
[37m[9/11/2020, 6:48:10 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:15 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:15 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:15 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE181400054D22 Baker's Lamp
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B4026 Door Lamp
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140005388C Front Porch Bulb 1
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814000537CD Front Porch Bulb 2
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002DA22 Paige’s Lamp
[37m[9/11/2020, 6:48:17 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:18 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:18 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:18 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:19 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE181400054D22 Baker's Lamp
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B4026 Door Lamp
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140005388C Front Porch Bulb 1
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814000537CD Front Porch Bulb 2
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002DA22 Paige’s Lamp
[37m[9/11/2020, 6:48:20 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE181400054D22 Baker's Lamp
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B4026 Door Lamp
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140005388C Front Porch Bulb 1
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814000537CD Front Porch Bulb 2
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002DA22 Paige’s Lamp
[37m[9/11/2020, 6:48:21 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:22 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE181400054D22 Baker's Lamp
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B4026 Door Lamp
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140005388C Front Porch Bulb 1
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814000537CD Front Porch Bulb 2
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002DA22 Paige’s Lamp
[37m[9/11/2020, 6:48:23 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE181400054D22 Baker's Lamp
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B4026 Door Lamp
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140005388C Front Porch Bulb 1
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814000537CD Front Porch Bulb 2
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002DA22 Paige’s Lamp
[37m[9/11/2020, 6:48:24 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE181400054D22 Baker's Lamp
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B4026 Door Lamp
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140005388C Front Porch Bulb 1
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814000537CD Front Porch Bulb 2
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002DA22 Paige’s Lamp
[37m[9/11/2020, 6:48:26 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:48:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:49:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:50:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:51:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:52:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:53:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:54:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:55:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE181400054D22 Baker's Lamp
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B4026 Door Lamp
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140005388C Front Porch Bulb 1
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814000537CD Front Porch Bulb 2
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002DA22 Paige’s Lamp
[37m[9/11/2020, 6:56:11 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE181400054D22 Baker's Lamp
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002E512 Cory’s Lamp
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B3648 Couch Lamp
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814033B4026 Door Lamp
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140005388C Front Porch Bulb 1
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE1814000537CD Front Porch Bulb 2
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE18140002DA22 Paige’s Lamp
[37m[9/11/2020, 6:56:15 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:56:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:57:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:58:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 6:59:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 7:00:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.
[37m[9/11/2020, 7:01:33 PM] [39m[36m[SengledHub] [39mCookie found, skipping login request.

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 39C0",
        "username": "***********",
        "port": 51251,
        "pin": "***-**-***"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "refreshToken": "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTk4NTk5MzEsInJlZnJlc2hfY2lkIjoicmluZ19vZmZpY2lhbF9hbmRyb2lkIiwicmVmcmVzaF9zY29wZXMiOlsiY2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6MTk3NTYyNjEsInJuZCI6IjR3a0lELXdRMnhPN2FnIiwic2Vzc2lvbl9pZCI6ImY0YjA4OTBhLWUwNjUtNDQ2My05MGNjLTllMjQyYzI5OTc1NCIsInR5cGUiOiJyZWZyZXNoLXRva2VuIn0.eKtMe3YXz9_ftyxvKIdEiuJN48z7d4QV-uGCOYNjEEES9mg9y2PMfpOSs6J-hODVhQhTAFFqSuTdCYjKBK2T5g",
            "platform": "Ring"
        },
        {
            "platform": "SengledHub",
            "name": "SengledHub",
            "username": "*********",
            "password": "********"
        },
        {
            "name": "SmartThings-v2",
            "direct_port": 8000,
            "temperature_unit": "F",
            "validateTokenId": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": true,
                "hideNamePrefix": true,
                "file": {
                    "enabled": true,
                    "level": "good"
                }
            },
            "platform": "SmartThings-v2"
        },
        {
            "email": "*****",
            "password": "****",
            "platform": "myQ"
        },
        {
            "name": "TplinkSmarthome",
            "broadcast": "***********",
            "platform": "TplinkSmarthome"
        }
    ]
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.18.3 
* **NPM Version**: 
* **Homebridge Version**: 1.1.6
* **Operating System**: Windows 10
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by paiigebowliin** [comment]
Did this to me yesterday too. Homebridge Settings and Force Service Restart is the only thing I can do to resolve, but it's only temporary (maybe half an hour) before it all fails again and homekit reports the devices as "Not Responding"

**Comment by paiigebowliin** [comment]
[37m[9/10/2020, 7:46:55 PM] [39m[36m[Ring] [39mHidden accessory 3276d08c-175d-47ed-b927-d8fbade4b8ee range-extender.zwave Ring Z-Wave Extender 58993
(node:504956) UnhandledPromiseRejectionWarning: Error: timeout of 2000ms exceeded
    at createError (C:\Users\Paige Bowlin\AppData\Roaming\npm\node_modules\homebridge-sengled\node_modules\axios\lib\core\createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (C:\Users\Paige Bowlin\AppData\Roaming\npm\node_modules\homebridge-sengled\node_modules\axios\lib\adapters\http.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
(node:504956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:504956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[37m[9/10/2020, 7:47:47 PM] [39m[36m[SengledHub] [39mGetting Status: B0CE181400054D22 Baker's Lamp

**Comment by oznu** [comment]
Hi @paiigebowliin,

These errors are being caused by the homebridge-sengled plugin; please raise the issue on that plugins project page.

**Comment by paiigebowliin** [comment]
> Hi @paiigebowliin,
> 
> 
> 
> These errors are being caused by the homebridge-sengled plugin; please raise the issue on that plugins project page.

I already remove the plugin and the syntax and I'm still expiring the same issue

**Comment by weaverjohnson** [comment]
Any updates on this? I am having the same issues
