### ISSUE TITLE
Circular Dependency Problem

### ISSUE THREAD

**Issue by jvmahon** [homebridge/homebridge#2677]
I'm getting the following warning when I start up my homebridge plugin:

`````
(node:8428) Warning: Accessing non-existent property 'Characteristic' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8428) Warning: Accessing non-existent property 'Service' of module exports inside circular dependency
`````
The code still works, but I'd like to fix this anyway.

To do so, I'd like to enable the node ''--trace-warnings" option as suggested in the warning message so I can identify which module is exhibiting this problem. 

However, I can't figure out how to turn on this feature when using homebridge. Can someone provide guidance of what I'd need to modify to get this to work?

Thanks

**Comment by oznu** [comment]
Please provide a sample to reproduce the issue.

**Comment by jvmahon** [comment]
> Hi @jnewland,
> 
> Please provide a code sample that produced these warnings.

Hi @oznu,

The code is the plugin: www.github.com/jvmahon/homebridge-homeseer4.

BUT, to be clear, I don't think this is a homebridge error. I'm guessing its in my plugin.  All I'm looking for is how to activate the "node --trace-warnings" feature when I start homebridge to help me find this.  Is there a line of code somewhere that I can modify to add the ''--trace-warnings" flag to the node startup?

Thanks
Jim

**Comment by oznu** [comment]
>  All I'm looking for is how to activate the "node --trace-warnings" feature when I start homebridge to help me find this.

Just set it as an env var when starting Homebridge.

```
NODE_OPTIONS="--trace-warnings" homebridge
```

**Comment by Supereg** [comment]
any news on this with added trace warnings? @jvmahon

**Comment by jvmahon** [comment]
Yes - I was able to figure out which section of my code was the problem - it was a problem with my plugin, not homebridge.

**Comment by jvmahon** [comment]
@oznu   Thanks. That fixed my problem. Greatly appreciated!
