### ISSUE TITLE
Homebridge 1.2 update - cannot see any accessories and will not re-add into Home App

### ISSUE THREAD

**Issue by winstano** [homebridge/homebridge#2680]
Running homebridge via docker on unraid. It's auto updated to 1.2, and all of my accessories displayed "not responding" within the Home app. They work fine via the web interface.

Removed the bridge from the Home app and reset it within the homebridge web interface, but when I go to re-add it into the Home app, it just sits on "Searching for accessory" and eventually crashes out with "Cannot find"

Any ideas? :-/

**Comment by dwightstanley** [comment]
I am experiencing the exact same issue with my docker and unraid as well. Thought it was something that i did - man I love this docker and use it all the time - hopefully someone will come up with an idea of what happened.

**Comment by oznu** [comment]
Hi @winstano @dwightstanley - please comment here with the information requested in the first comment:

https://github.com/homebridge/homebridge/issues/2681

We will track all 1.2.0 "not responding" issues in this issue.
