### ISSUE TITLE
TV icon changed after iOS 14 GM version

### ISSUE THREAD

**Issue by Faisalthe01** [homebridge/homebridge#2683]
My TV icons suddenly changed to this generic Home icon after the iOS 14 GM update. It still is a TV icon on my iPhone with 13.7 and in Homebridge. 

I am running v1.2.2 on Windows 10 Pro.

I have restarted both Homebrigde and iPhone then removed the TV accessory and re-added but it still looks like the Home Icon

![TV](https://user-images.githubusercontent.com/62862684/93297189-26bb0500-f834-11ea-8d4e-c5736a41ead0.jpg)

**Comment by weissenheimer** [comment]
It's the same for me.

**Comment by ttimpe** [comment]
Can confirm this with an LG OLED B7D.

**Comment by masterfordev** [comment]
Same issue, but I'm also using the [homebridge-samsung-tizen](https://github.com/tavicu/homebridge-samsung-tizen) plugin with my smart tv samsung and that tv does show a tv icon.

**Comment by Faisalthe01** [comment]
https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/57#issuecomment-694058114

It was more of a Plug in issue that did not specified a category for TV Service.

**Comment by Supereg** [comment]
duplicate https://github.com/homebridge/HAP-NodeJS/issues/846
