### ISSUE TITLE
1.2.2 break homebridge-tydom plugin

### ISSUE THREAD

**Issue by myhomeiot** [homebridge/homebridge#2686]
homebridge-tydom plugin works without any problems with all previous versions including 1.2.1. After I downgrade homebridge from 1.2.2 to 1.2.1 everything start working again.

[**Logs:**]()
Last tydom log record in homebridge 1.2.2:
Creating tydom client with username='XXX' and hostname='XXX'

**Comment by donavanbecker** [comment]
@myhomeiot I would contact the plugin developer also.
