### ISSUE TITLE
Apple Adaptive Lighting - IOS 14

### ISSUE THREAD

**Issue by jeylites** [homebridge/homebridge#2687]
Anyone know anything about getting adaptive lighting to work on IOS14?

**Comment by intrepidsilence** [comment]
As far as I know this is TLV8 and will need to be reverse-engineered. Manufacturers must update device firmware to support it so until there are devices out there that support it that can be used for introspection it will have to wait I am guessing.

**Comment by oznu** [comment]
The [Lightbulb](https://developers.homebridge.io/#/service/Lightbulb) service has two new characteristics:

* [Characteristic Value Transition Control](https://developers.homebridge.io/#/characteristic/CharacteristicValueTransitionControl)
* [Supported Characteristic Value Transition Configuration](https://developers.homebridge.io/#/characteristic/SupportedCharacteristicValueTransitionConfiguration)

As @intrepidsilence mentioned, both of these use `tlv8` encoding, so it's not obvious without some reverse engineering what the `tlv8`  payload should look like. We'll probably know more shorty after the first real device comes on the market.

**Comment by itavero** [comment]
The Eve Light Strip now also supports Adaptive Lighting: https://www.evehome.com/en/blog/adaptive-lighting

@oznu If someone already has one, or if I would get one, how would I start with reverse engineering the characteristics?
Is there any app I can use to look at the raw TLV8 data?

**Comment by ebaauw** [comment]
The small print says you need a home hub for adaptive lighting.  Looks like the actual adaptations are driven from there, much like HomeKit automations.

To reverse engineer the characteristics, use an adapted version of Apple's `HMCatalog` example app.  See https://github.com/simont77/fakegato-history#how-to-contribute.

**Comment by itavero** [comment]
Unfortunately I'm too busy with my other projects. I didn't even find a moment yet to order the light strip. So if someone else wants to give the reverse engineering a try, please don't wait for me to start on it 😅

**Comment by ebaauw** [comment]
My Hue bridge just received a firmware update and now supports Adaptive Lighting.  I won’t be bored this weekend.  I’ll log my progress in https://github.com/ebaauw/homebridge-hue/issues/766.
