### ISSUE TITLE
Homebridge not working with iOS 14 

### ISSUE THREAD

**Issue by gondor5** [homebridge/homebridge#2688]
When I scan the QR code I get "Uncertified Accessory". I Add Anyway then I get "Unable to Add Accessory. Accessory is out of compliance"

![IMG_7410](https://user-images.githubusercontent.com/482807/93628272-48db9100-f9b4-11ea-9cdb-d427382e85bd.png)

![IMG_7411](https://user-images.githubusercontent.com/482807/93628251-3d886580-f9b4-11ea-8151-50d6cee6e322.png)

**Comment by donavanbecker** [comment]
I had this too, you need to do a pairing reset. If you have config ui, you can do it from homebridge settings

**Comment by Phoenix-DH** [comment]
This means that all settings in home are gone?

**Comment by donavanbecker** [comment]
> This means that all settings in home are gone?

Yes, but he hasn't paired his homebridge, so... nothing that will be gone.

**Comment by Phoenix-DH** [comment]
Right, but want to know what will happen with this feature.

**Comment by bart3003** [comment]
I have the same problem
After reset its stil not connect to home

Is there another solotion?

**Comment by gondor5** [comment]
Thanks for the suggestion.  
I did the Reset Homebridge Accessory and tried again but got the same result. 

I, then did Unpair Bridges / Cameras/ TVs / External Accessories. After a restart, I then did Reset Homebridge Accessory and still got the same result. 

Anything else I could try? I am all ears.  
Thanks!

**Comment by gondor5** [comment]
**Update**.  I removed Ring and Nest Plugins and was able to add Homebridge to Home app.  I wish I would have removed one at at time to narrow down which one was the culprit.

Thanks all.

**Comment by mkormendy** [comment]
> I had this too, you need to do a pairing reset. If you have config ui, you can do it from homebridge settings
> 
> ![image](https://user-images.githubusercontent.com/9875439/93633610-d7501280-f9b4-11ea-977b-dc1aa4c865b4.jpeg)

Did this .. still not working. I only have one test plugin in this homebridge instance that won't pair.

**Comment by jaykamalr** [comment]
i have restarted homebridge, my Hub ( IpadMini)
I have also re-installed From Windows to Raspberry PI and reconnected HUB n Bridge again
I have also removed all plugin n test one by one, but the Home app reports not responsive

**Comment by balddaddy33015** [comment]
Has anybody found solutions yet? I'm just shy of reformating my Pi with HB to fix this issue. Looks like it isn't an exact fix though. Has anybody else figured this out?

**Comment by rgstephens** [comment]
I don't have the Nest or Ring plugin that others have mentioned but the MQTTThing plug-in had to be disabled in my case.
