### ISSUE TITLE
Homebridge devices disappear, reappear in default room

### ISSUE THREAD

**Issue by rcoletti116** [homebridge/homebridge#2689]
Randomly my homebridge devices will disappear from HomeKit. The homebridge itself and a single device (Roomba) won't disappear. After a little time or a restart they will appear in the Default Room, having lost all HK room, service groups and automation assignments. This has happened a number of times for me in the last few weeks, both on 1.1.x update and now on 1.2.2. I'm sorry I don't have more details. The issue seems to leave no trace in Homebridge. I do know from Discord and Reddit others have had this happen before.

**Describe The Bug:**
Devices disappear. Later reappear in Default room and lost all assignments.

**To Reproduce:**
It happens randomly, so I don't have steps to reproduce.

**Expected behavior:**
Devices remain in HomeKit.

[**Logs:**]
The logs show no error, including w/ Debug On. Logs look normal.

**Screenshots:**

**Environment:**

* **Node.js Version**: v10.17.0
* **NPM Version**: v6.13.6
* **Homebridge Version**: 1.2.2
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by donavanbecker** [comment]
@rcoletti116, I believe this a plugin issue. I have seen other plugins with this same issue.

**Comment by rcoletti116** [comment]
Interesting, so you think this is caused by a single plugin? It's hard to reproduce, so troubleshooting plugins one by one will be difficult.

Its a stretch but any idea what plugin you've seen this happen with before?

**Comment by donavanbecker** [comment]
Homebridge-nest and homebridge-nest-cam

**Comment by rcoletti116** [comment]
Gotcha. Not using either of those. I'm going to try rebuilding.

**Comment by ebaauw** [comment]
> Interesting, so you think this is caused by a single plugin? It's hard to reproduce, so troubleshooting plugins one by one will be difficult.

It would be the plugin(s) exposing the disappearing accessories.  They would be platform plugins using the static platform accessory model.  They fail to re-discover some devices and re-expose the corresponding accessories, before Homebridge starts its HAP server, so HomeKit removes the accessories.  On next start, the accessories are exposed alright, but HomeKit sees them as new accessories, having lost all associations with rooms, groups, scenes, and automations.

**Comment by rcoletti116** [comment]
You're saying the cause _is likely_  an older plugin not using dynamic platform model? 

Frustratingly it's been all of my devices (about 30) disappearing at once, from a range of plugins. Only one that doesn't disappear is Roomba. It happened 5 times yesterday, with no indication of anything wrong in the HB logs. I'll take a look at my plugins and see which ones are not dynamic.

**Comment by ebaauw** [comment]
> Frustratingly it's been all of my devices (about 30) disappearing at once

Afaik you can only lose accessories by dynamic platform plugins by deleting or corrupting `cachedAccessories`.  I’d check the uSD card for file system corruptions.

> It happened 5 times yesterday, with no indication of anything wrong in the HB logs.

How often did Homebridge restart?

**Comment by rcoletti116** [comment]
It never restarted on its own. Only when I prompted it to get the accessories back.

**Comment by ebaauw** [comment]
I've never seen a running instance of Homebridge losing accessories.  Theoretically, a dynamic platform plugin could un-expose accessories at runtime, but accessories by static platform plugins (or by accessory plugins) cannot disappear without restarting Homebridge.

**Comment by libewa** [comment]
i have the same issue
