### ISSUE TITLE
Remove shelly device from Homebridge and homekit

### ISSUE THREAD

**Issue by Ludelag** [homebridge/homebridge#2692]
One of my devices fall down and it is broken, is the Shelly Door/Window 2 and is not possible to repair, I would like to remove it from Homebridge and that desapear from Home app, because I will replace it.

how can i remove it? I deleted from Shelly app already but still is present in Homekit and in Homebridge.

Thank you

**Comment by donavanbecker** [comment]
@Ludelag are you using config ui x?

**Comment by Ludelag** [comment]
> config ui x

No, Will it help to remove the device? https://www.npmjs.com/package/homebridge-config-ui-x

**Comment by donavanbecker** [comment]
yes, it is a ui that has a homebridge setting
<img width="201" alt="Screen Shot 2020-09-24 at 11 25 06 AM" src="https://user-images.githubusercontent.com/9875439/94172829-9ba3c580-fe58-11ea-8795-0f073f3f78ad.png">
From Homebridge settings you can click `Remove Single Cached Accessory` and select the accessory you want to remove
<img width="1423" alt="Screen Shot 2020-09-24 at 11 25 44 AM" src="https://user-images.githubusercontent.com/9875439/94172880-b24a1c80-fe58-11ea-83aa-3230577d2a7e.png">

**Comment by Ludelag** [comment]
Done!! Thank you !
