### ISSUE TITLE
Homekit.app camera preview works but tapping on image to hear sound and do more load spinner just spins then eventually fails.

### ISSUE THREAD

**Issue by applemacgenius** [homebridge/homebridge#2693]
Homekit.app camera preview works but tapping on image to hear sound and do more load spinner just spins then eventually fails.
**Describe Your Problem:**
When I open the preview window from Homekit to actually hear and see the camera image all I get is a spinner and then eventually a message stating "No Response: This camera is not responding" with a camera logo and a line in it.

[**Logs:**]()
[9/24/2020, 4:05:23 PM] [Nest-cam] [NexusStreamer] Connected
[9/24/2020, 4:05:23 PM] [Nest-cam] [NexusStreamer] Redirecting...
[9/24/2020, 4:05:24 PM] [Nest-cam] [NexusStreamer] Disconnected
[9/24/2020, 4:05:24 PM] [Nest-cam] [NexusStreamer] Connected
```
![IMG_4D3AA3900538-1](https://user-images.githubusercontent.com/46770856/94208962-f43a8900-fe7f-11ea-8d6e-6791bf4a5af0.jpeg)

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by Supereg** [comment]
please report this to the plugin owner, as the issue is most likely found somewhere in the plugin code.
