### ISSUE TITLE
All accessories become unreachable when I leave the accessories tab

### ISSUE THREAD

**Issue by yeetedthehomebridge** [homebridge/homebridge#2694]
Current running the newest version-. node v12.18.4 on a rpi4. I only have the nest plugin for a door lock, thermostat and two temp sensors. When its all freshly started, it works great for a few minutes and immediately becomes 'No response'. Odd thing is, they all come back and are accessible from apple home once I open the Homebridge.local page, and go to the accessories tab. Nothing is showing in the logs, everything is communicating with the Homebridge correctly. I see all the temps and lock stats in the logs as its there. Literally, I move off the accessories tab in the Homebridge and it all goes offline. 

I've tried a few things, disable ipv6, unlinked everything, rebooted all devices, etc. Just did a fresh install and the same thing happens. 

Any suggestions?

**Comment by yeetedthehomebridge** [comment]
Just installed on my Mac, versus using the rpi4 as a test and guess what? The same exact behavior happens. While I'm new to this, I strongly suspect this is an actual issue.

**Comment by samydoesit** [comment]
Same here.

I can re setup everything from the beginning, it is working for some days and suddenly everything gets not reachable.

**Comment by Dweller** [comment]
I’ve exactly the same issue rebooted my fixed IP Mac mini twice and each time all of the homebridge devices become  inaccessible.

Easy fix just delete the home bridge and remind but takes 30 mins to reinput the automations.

Must be something in the current version ?

Am considering ditching homebridge

**Comment by KarstenS123** [comment]
Do I have a similar issue?

All my HomeBridge items are only reachable, as long I'm with my iPhone in the same local subnet as my AppleTV and the server with Homebridge.

When I leave that local network, only my "real" Homekit devices are reachable anylonger.

**Comment by Pawwah** [comment]
I have the same issue--homebridge will communicate with my Apple devices for several minutes and then stop.  When I bring up the UI and log in via a browser, everything automatically gets fixed for a few more minutes.  As to my configuration, I am running a oznu/homebridge docker container on my QNAP NAS via Container Station.

**Comment by yeetedthehomebridge** [comment]
The latest update seems to have fixed my issues. I am now up and running again.

**Comment by Supereg** [comment]
@yeetedthehomebridge could you quickly clarify to which version you refer to when you say „latest“ and what the previous version was which didn’t work.
