### ISSUE TITLE
Current Relative Humidity 

### ISSUE THREAD

**Issue by Faisalthe01** [homebridge/homebridge#2695]
Does anyone know how to disable the Current Relative Humidity in Humidifier-Dehumidifier accessory?

If i try not to define its characteristics, it still shows with 0 value, i want to totally disable it. Is it even possible with Humidifier-Dehumidifier service? is it mandatory in this service?

![3E090C4A-8722-4D0A-B451-4D1391CCA508](https://user-images.githubusercontent.com/62862684/94367132-fa4e9500-011f-11eb-8960-e01ea62de270.jpeg)

**Comment by oznu** [comment]
It is a mandatory characteristic for the service type.

https://developers.homebridge.io/#/service/HumidifierDehumidifier
