### ISSUE TITLE
"sudo npm outdated -g" brings new version 1.1.6 ?!?!?

### ISSUE THREAD

**Issue by roe1974** [homebridge/homebridge#2696]
Hi
Performing a "sudo npm outdated -g" brings today a new version 1.1.6 ?!?!?

Package                     Current  Wanted  Latest  Location
homebridge                  1.2.3   1.2.3   1.1.6  global

But i have installed 1.2.3 ?!?!?
I think something is wrong here .... not ?
Richard

**Comment by LangBalthazar** [comment]
Same here.

I have one Pi 4 that shows 1.1.6 as latest
![image](https://user-images.githubusercontent.com/3634523/94667475-25e3a200-030f-11eb-94de-6273ec0b6c32.png)


So i tried to run the below in terminal on a RPi that was running 1.2.3 and after the installation of latest it now shows me 1.1.6
`sudo npm install -g -unsafe-perm homebridge@latest -g`

![image](https://user-images.githubusercontent.com/3634523/94667987-cafe7a80-030f-11eb-8103-b5f5476a37a3.png)

**Comment by oznu** [comment]
We have set the latest back to 1.1.6 for now due to issues present in 1.2.3.

Users already on 1.2.3 won't be impacted as they are already on a higher version and won't be offered the "downgrade" in the Homebridge UI.

You can manually install v1.2.3 if you still wish.

**Comment by roe1974** [comment]
so what i have to do ?
perform a "sudo npm install -g -unsafe-perm homebridge@latest -g" ..... or do nothing ? (currentliy running 1.2.3)
Richard

**Comment by oznu** [comment]
Do nothing.

**Comment by roe1974** [comment]
v1.2.3 works perfect ... thx for the information ;-)
Richard
