### ISSUE TITLE
Cron related entries in the logs

### ISSUE THREAD

**Issue by monisriz** [homebridge/homebridge#2699]
**Describe The Bug:**

Seeing continuous entries in the log related to cron. Installed homebridge inside a docker container on QNAP NAS. This is a vanilla installation with no plugins added as yet. Able to browse to homebridge config page. So not sure what this log entry signifies.
The entry is something like:
crond[333]: USER root pid 123 cmd run-parts /etc/periodic/15min

**To Reproduce:**
 
**Expected behavior:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Docker
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by Supereg** [comment]
Homebridge itself does not interact with the `crond` process. Log entry seems like regular cron doing it's business(?).
What docker image are you using, the official homebridge one?

**Comment by monisriz** [comment]
Thanks for the reply.
Yes it’s the regular image - I followed the instructions on homebridge.io for Qnap.
If homebridge doesn’t interact with cron then what could be causing these log entries? I also noticed that these entries don’t show up in logs available on the local homebridge web interface/UI. They only seem to be there in the QNAP “Container Station” logs for this container.

**Comment by Supereg** [comment]
They don't show up in the regular log cause it is not a component of homebridge. crond is a separate process coming preinstalled on most linux distributions and is a basic scheduler for time based tasks (see https://en.wikipedia.org/wiki/Cron).

may forward this to @oznu as he maintains the homebridge docker image.

**Comment by oznu** [comment]
The container runs logrotate via a cron - hence the log entries when the process run. They don't show up in the homebridge UI log as intended.
