### ISSUE TITLE
Multiple connection homebridge (home assistant +iPhone)

### ISSUE THREAD

**Issue by 27andrea** [homebridge/homebridge#2700]
Goodmorning,
I have a homebridge connected to iPhone and i was trying to add it to home assistant with no luck.so i remove iPhone and i connect it correctly to home assistant but i can't connect it to iPhone.
I think that you can connect homebridge to only one device.how can i solve it?
Thanks

**Comment by Supereg** [comment]
When you talking about "connections" I assume you are talking about "pairings". This is a requirement of HomeKit itself. A HomeKit accessory can only be paired with **one** device/Apple Account, any further pairings/accounts are added via HomeKit home sharing.
As this violates the HomeKit Accessory Protocol specifications this is currently unsupported. There is the "allowInsecureRequests" option in homebridge to allow regular unencrypted http requests, but other than that, there is nothing to support that.

**Comment by peros550** [comment]
Is @Supereg response still the case? I know for sure HAA firmware offers the functionality of maintaing multiple pairs which is a out of Homekit's protocol, yet it doesn't harm to do it. 
One can have multiple Homekit homes for the same location. This is a workaround in cases where you would want to share very specific accessories (i.e. Lights or Garage Doors in common spaces like multistory buildings) but at the same time you wouldn't want to share your home's door lock or cameres with your neighbors.
