### ISSUE TITLE
Help with Automated Testing of Plugins

### ISSUE THREAD

**Issue by plasticrake** [homebridge/homebridge#2703]
I'm trying to write test scripts in mocha to test my homebridge plugin. I haven't seen any examples from other plugins that are trying to do what I'm doing. I currently can launch an instance of homebridge programmatically and point it to various test configuration files and folders, but I'm struggling to find the best way to wrap my plugin with something like SinonJS to inspect how they are interacting. If I call something like `api.registerPlatform()` from my test scripts then homebridge complains: `Error: Unexpected platform registration. Plugin 'TplinkSmarthome' tried to register outside the initializer function!`

I tried to use the non-public api to replace the existing loaded plugin with my wrapped plugin but was having issues with that and concerned that will break as it's using non-public api. I considered building a separate version of my plugin that is wrapped in SinonJS and pointing homebridge to that folder, but I'd rather be able to do something like call `api.registerPlatform()` and pass in what I want.

Are there any examples of what I'm trying to do out there? I'd like to programmatically "plugin" my plugin which is wrapped with SinonJS.

Thanks!

**Comment by NorthernMan54** [comment]
Not quite as sophisticated as your approach, I just run Homebridge in insecure mode and use curl against the HAP interface

https://github.com/NorthernMan54/homebridge-hampton-bay/blob/master/tools/test.sh

**Comment by elliotwms** [comment]
@plasticrake did you ever find a nice solution for this?
