### ISSUE TITLE
Is there a legacy version for node.js 8.xx ?

### ISSUE THREAD

**Issue by houser42** [homebridge/homebridge#2710]
Long shot probably, but if at all possible, I would like to try to run a small instance of HB on a a beagle box.
with just two plugins for mqtt on it.
It has an old node.js and currently no way of updating any of it.
Node.js version: v8.15.0
Linux 4.9.194-beagle arm LE so not much wiggle room to install packages or dependencies either.
It is for an offgrid cabin where power consumption is at a premium...
A straight no will work too ;) Many thanks...

**Comment by oznu** [comment]
Versions prior to v1.0.0 should work on Node.is v8.
