### ISSUE TITLE
Cannot uninstall Homebridge - still accessibly!

### ISSUE THREAD

**Issue by leecollings** [homebridge/homebridge#2711]
I googled how to uninstall Homebridge will resulted in my having a single command:

sudo npm uninstall -g homebridge

So I did this, and it seemed to run through uninstallation, however when that was finished I could still access Homebridge in a browser.

So I tried rebooting my pi and once it started again, the UX is still accessible....

So it seems the line above does NOT uninstall home bridge. Please advise how I can completely remove it from my Pi.

**Comment by oznu** [comment]
You need to remove the service.

Each guide has instruction for uninstalling:

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#how-to-uninstall-homebridge
