### ISSUE TITLE
How to modify the list of buttons available in the Homekit Remote App (control center)

### ISSUE THREAD

**Issue by Babauzaure** [homebridge/homebridge#2712]
**Describe Your Problem:**
I am coding a new plugin to interface with AMX controllers and I am stuck with a function :
No matter how hard I search the API and various existing pugins, I can't change the list of buttons available in the Homekit Remote app.
I found a clue with the "Target Control List" service of "Target Control Management", but I don't know how to write the tlv8 instruction correctly ...

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/73850246/97908616-3d1b1280-1d47-11eb-9c32-77142bb1df0e.png)

**Environment:**

* **Node.js Version**: v12.14.0
* **NPM Version**: v6.13.4
* **Homebridge Version**: v1.1.6
* **Operating System**: Windows 10 Pro
* **Process Supervisor**: none

**Comment by Supereg** [comment]
"Target Control List", "Target Control Management" are used for Apple TV remotes.
You are doing a HomeKit Television (right?).
What you want to modify is the `RemoteKey` characteristic of the `Television` service.
I'm unsure if Apple allows you to modify the displayed buttons, but you can try by setting a custom array of validValues as the characteristic properties.

**Comment by Babauzaure** [comment]
I didn't really understand what these services really do. I thought it was a modification of the soft remote button list (control center)
Yes, I want to make possible to add Homekit Television with my AMX/Homebridge platform. Everything works except this Homekit Remote changes I would like.
RemoteKey Characteristic is the way to retrieve button press information.
I will try but, to be honest, it seems strange to me.

thank you for your help!

**Comment by mgoeller** [comment]
Hi @Babauzaure
Did you manage to integrate your AMX system into HomeKit with HomeBridge? Do you control appliances via the AXLink Bus? Which hardware are you using to communicate on the Bus?

Thanks
