### ISSUE TITLE
Accessory already been added

### ISSUE THREAD

**Issue by vespino** [homebridge/homebridge#2714]
When scanning the QR code with the HomeKit app it asks me if I would like to add the bridge and afterwards shows that the accessory apparently had already been added. To add it again, I have to reset it, but how? I have already deleted all HomeKit data and removed it from my iCloud account.

**Comment by oznu** [comment]
See https://github.com/homebridge/homebridge/wiki/Connecting-Homebridge-To-HomeKit#how-to-reset-homebridge

**Comment by vespino** [comment]
Thanks.
