### ISSUE TITLE
Can't install using the instructions provided. Getting 404 errors

### ISSUE THREAD

**Issue by artbatista** [homebridge/homebridge#2716]
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

## Populating apt-get cache...

+ apt-get update
Get:1 https://download.docker.com/linux/ubuntu bionic InRelease [64.4 kB]
Get:2 http://dl.google.com/linux/chrome/deb stable InRelease [1,811 B]                                 
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease                                                
Get:4 https://deb.opera.com/opera-stable stable InRelease [2,591 B]                                    
Hit:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                        
Hit:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                      
Hit:7 http://ppa.launchpad.net/malcscott/znapzend/ubuntu bionic InRelease                      
Hit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease                                      
Err:2 http://dl.google.com/linux/chrome/deb stable InRelease                                           
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78BD65473CB3BD13
Hit:9 http://repo.ombi.turd.me/stable jessie InRelease                                                 
Ign:10 http://ppa.launchpad.net/upubuntu-com/ppa/ubuntu bionic InRelease                               
Err:11 http://ppa.launchpad.net/upubuntu-com/ppa/ubuntu bionic Release                  
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Reading package lists... Done                      
W: GPG error: http://dl.google.com/linux/chrome/deb stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78BD65473CB3BD13
E: The repository 'http://dl.google.com/linux/chrome/deb stable InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/upubuntu-com/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting

**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment]
Your "apt" source list contains invalid or out of date repos (not as a result of the Homebridge installation instructions).

You will need to resolve this before you install anything via "apt".

**Comment by oznu** [comment]
https://askubuntu.com/a/310 should get you on the right track.
