### ISSUE TITLE
Problem with updating / installing plugins (latest HB)

### ISSUE THREAD

**Issue by Kfrard** [homebridge/homebridge#2717]
Hey, 
I have a problem, after installing HB on Pi, I can't install / update plugins 
and after installing "Homebridge Config UI X" it has an update. 
I get an error:
```
npm ERR! code EAI_AGAIN
above sea level ERR! errno EAI_AGAIN
above sea level ERR! request to https://registry.npmjs.org/homebridge-sonos failed, reason: getaddrinfo EA
```

I admit that it works on Windows 10, but not on Raspberry Pi 3.

**Comment by oznu** [comment]
> EAI_AGAIN is a DNS lookup timed out error, means it is a network connectivity error or proxy related error.

Check your device network settings. Sometimes rebooting can fix this. It's not an issue with Homebridge / Homebridge UI.

**Comment by Kfrard** [comment]
I ran it several times, even reinstalled go twice.

**Comment by fabriziorizzo** [comment]
Same problem running the homebridge docker within QNAP Container Station.
QNAP container station supports both Docker and Linux Containers.  As such there are two internal non-routed networks created in the QNAP "virtual switch" topology:  10.0.3.0/32 for the LXC network (local interface: lxcbr0) and 10.0.5.0/32 for the Docker network (local interface: docker0).  There is also a  virtual switch for the host's network, which is routable an has the default gateway assigned (local interface: qvs0).

This docker container seems to select the lxcbr0 interface for setting the DNS server IP address in /etc/resolv.conf.
However this is being done as the container initializes, it doesn't seem to be looking for/selecting the interface with the default route on it.

Running the ubuntu release via:

```
[QNAP] # docker run -d --name=homebridge --hostname homebridge  \
  --network="host" \
  --restart unless-stopped \
  -e PUID=1004 \
  -e PGID=1004 \
  -e TZ=Detroit/Americas \
  -e HOMEBRIDGE_CONFIG_UI=1 \
  -e HOMEBRIDGE_CONFIG_UI_PORT=8455 \
  -v /share/CACHEDEV1_DATA/docker/homebridge:/homebridge \
  oznu/homebridge:ubuntu
 
```
When I run a shell within the container and check the /etc/resolv.conf and routing table, the IP address automatically chosen for the resolv.conf file config is on the Linux Container  internal network not the one with the default route to the internet.  Changing resolv.conf manually fixes the issue until the container is restarted.  Obviously not the desired condition.

```
[QNAP] # docker exec -it homebridge sh
# cat /etc/resolv.conf
nameserver 10.0.3.1

# netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.4.1     0.0.0.0         UG        0 0          0 qvs0
10.0.3.0        0.0.0.0         255.255.255.0   U         0 0          0 lxcbr0
10.0.5.0        0.0.0.0         255.255.255.0   U         0 0          0 docker0
127.0.0.0       0.0.0.0         255.0.0.0       U         0 0          0 lo
169.254.4.0     0.0.0.0         255.255.255.0   U         0 0          0 tbtbr0
192.168.4.0     0.0.0.0         255.255.255.0   U         0 0          0 bond1
192.168.4.0     0.0.0.0         255.255.255.0   U         0 0          0 qvs0
224.1.14.48     0.0.0.0         255.255.255.255 UH        0 0          0 lo

# ping github.com
ping: github.com: Temporary failure in name resolution

# cat > /etc/resolv.conf << EOF
> nameserver 192.168.4.1
> EOF

# cat /etc/resolv.conf
nameserver 192.168.4.1

# ping github.com
PING github.com (140.82.114.3) 56(84) bytes of data.
64 bytes from lb-140-82-114-3-iad.github.com (140.82.114.3): icmp_seq=1 ttl=54 time=38.8 ms
64 bytes from lb-140-82-114-3-iad.github.com (140.82.114.3): icmp_seq=2 ttl=54 time=28.8 ms
^C
--- github.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 28.879/33.843/38.807/4.964 ms
#
```

If I restart the container, the nameserver IP in /etc/resolv.conf is replaced  with the 10.0.3.1 address on the lxcbr0 interface and DNS resolution fails again.

Where/how is the IP in the /etc/resolv.conf file getting configured by default?
