### ISSUE TITLE
Logging to own logfile 

### ISSUE THREAD

**Issue by johanvdk1** [homebridge/homebridge#2718]
Running version 0.4.45 on ubuntu kernel 4.15.0-122-generic.

Request is to enable logging to own log file, such as /var/log/homebridge/homebridge.log.
With several thermostats, each reporting temperature every 3 minutes my syslog is filling up rapidly. 
I don't consider roomtemperatures as items I wish to have in syslog. 
Due to homebridge logging, my log rotates much faster which hinders troubleshooting other issues.

Debug option is not enabled.

**Comment by oznu** [comment]
The current install instructions log to that exact location on Linux:

https://github.com/homebridge/homebridge/wiki

**Comment by Supereg** [comment]
> With several thermostats, each reporting temperature every 3 minutes my syslog is filling up rapidly.
I don't consider roomtemperatures as items I wish to have in syslog.

You may want to consider contacting the thermostat plugin author to give an option to reduce logging output, as the plugin is responsible for what it wants to be logged.

**Comment by johanvdk1** [comment]
Thanks, I will update to the latest version. The plug-in has to report the temperatures (to assure that homebridge has the latest room temperatures) and it does that when the temperatures are received from the devices.
