### ISSUE TITLE
No Response after some minutes of devices 

### ISSUE THREAD

**Issue by ebini** [homebridge/homebridge#2719]
### About Troubleshooting Page:
- i setup homebridge again in docker with empty dir and no plugins and changing username/pin
- removed home in homekit, also tried deleting home app
- Wifi "trick": "removed" Wifi and reconnected.

### Summary
A fresh homebridge install via docker-compose on Synology (DS918+) the devices (dummy) works only for some minutes. Then "no response".
Note: also tried with the synology package.

docker-compose configuration
```
   homebridge:
    image: oznu/homebridge:3.3.0
    container_name: dc-homebridge
    restart: always
    #expose:
    #  - 8081
    #ports:
    #  - 8081:8081
    network_mode: "host"
    volumes:
    - /volume1/docker/homebridge_test:/homebridge
    environment:
    - HOMEBRIDGE_CONFIG_UI=1
    - HOMEBRIDGE_CONFIG_UI_PORT=8581
    - HOMEBRIDGE_DEBUG=1
    - DSM_HOSTNAME=diskstation
    - PGID=100
    - PUID=1026


```
* Start with empty homebridge dir
* login as admin
* (also tried to change pin/username)
* add a dummy switch (and restart)
* Add homebrige to iOS Device (iOS14 .2)
Note: sometime - if i was too slow - it also was not able to add the devices
Switch works for a while... then "no reposonse from device" (hope this is the correct translation)

Note:
*  i have an AppleTV within the network. (also latest iOS version). But removing it as control center doesn't change anything
* Also have ipad, mac os with Home and same here.
* If the problem exists, the devices can be controlled via homebrige Web-UI. (i used hue, but setup everying fresh and only with dummy to exclude that the plugin is the problem)

Restarting homebridge: works again for some minutes

It seems that the docker homebridge version below 3.x.x has not this problem within minutes. but my devices seems to get lost also, but sporadically and after hours (and sometimes it works then again after 2-3 tries)
I tried also to connect Macbook directly via Ethernet to Synology NAS to exclude Wifi. Same issue.
Perhaps something is wrong with my synology configuration. But also reduces the complex config (network bonding and everything) to default values and disabled firewall and everything.

I have no idea what i can try. Perhaps i try it with a raspberry pi. and also will try the 2.x version.

**Expected behavior:**
Switching the Switch works forever...

[**Logs:**]
```
[11/15/2020, 8:57:36 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules -D
[11/15/2020, 8:57:36 AM] [HB Supervisor] Started Homebridge v1.2.3 with PID: 2419
[11/15/2020, 8:57:37 AM] Loaded config.json with 1 accessories and 1 platforms.
[11/15/2020, 8:57:37 AM] ---
[11/15/2020, 8:57:37 AM] Loaded plugin: homebridge-dummy@0.4.1
[11/15/2020, 8:57:37 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[11/15/2020, 8:57:37 AM] ---
[11/15/2020, 8:57:38 AM] Loaded plugin: homebridge-config-ui-x@4.33.0
[11/15/2020, 8:57:38 AM] Registering platform 'homebridge-config-ui-x.config'
[11/15/2020, 8:57:38 AM] ---
[11/15/2020, 8:57:38 AM] Loading 1 platforms...
[11/15/2020, 8:57:38 AM] [Config] Initializing config platform...
[11/15/2020, 8:57:38 AM] [Config] Running in Service Mode
[11/15/2020, 8:57:38 AM] Loading 1 accessories...
[11/15/2020, 8:57:38 AM] [Switch1] Initializing DummySwitch accessory...
[11/15/2020, 8:57:38 AM] [Switch1] Setting switch to false
Setup Payload:
X-HM://0023ISYW37IJB
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-123 │     
    └────────────┘     
                       
[11/15/2020, 8:57:38 AM] Homebridge v1.2.3 is running on port 53069.
[11/15/2020, 8:57:50 AM] [Switch1] Setting switch to true
[11/15/2020, 8:57:51 AM] [Switch1] Setting switch to false
[11/15/2020, 8:57:52 AM] [Switch1] Setting switch to true
[11/15/2020, 8:57:53 AM] [Switch1] Setting switch to false
[11/15/2020, 8:57:54 AM] [Switch1] Setting switch to true
[11/15/2020, 8:57:55 AM] [Switch1] Setting switch to false
[11/15/2020, 8:58:00 AM] [Switch1] Setting switch to true
[11/15/2020, 8:58:01 AM] [Switch1] Setting switch to false
[11/15/2020, 8:58:01 AM] [Switch1] Setting switch to true
[11/15/2020, 8:58:02 AM] [Switch1] Setting switch to false```

**Homebridge Config:**
<!-- Paste relevant output between the two ``` lines below -->
<!-- Remove any sensitive information, passwords, etc. -->

```json
{
    "bridge": {
        "name": "Homebridge C332",
        "username": "0E:E5:00:CC:C3:AA",
        "port": 53069,
        "pin": "031-45-123"
    },
    "accessories": [
        {
            "name": "Switch1",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "accessory": "DummySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

**Environment:**

* **Node.js Version**: v12.19.0
* **NPM Version**: v6.14.8
* **Homebridge Version**: v1.2.3
* **Operating System**:  Docker on synology NAS (see above)
* **Process Supervisor**: Docker

**Comment by oznu** [comment]
Try rollback to Homebridge v1.1.6:

![change-homebridge-version](https://user-images.githubusercontent.com/3979615/96521915-15936700-12be-11eb-9826-f19b201d20db.gif)

**Comment by ebini** [comment]
First (short term test): Seems to stay connected. 
will observer today

**Comment by ebini** [comment]
with v1.1.6 it seems to be stable!
should i close this bug, or can i help to analyse the problem with newer versions?

**Comment by SpunkyNoodle** [comment]
Hi there, I just want to confirm. iOS 14.2 as well. Latest version seems to fail with Homekit. I thought it was my TP-Link, Nest devices lost wifi but it was not the case.

Been testing different setup last 2 days it's always the devices connected via Homebridge failed to response after 10min. Rebooting Homebridge wakes it back up no issue but I have to repeats on doing this.

Other AC-HOC and IKEA hub directly connected to router has no issues.

**Comment by SpunkyNoodle** [comment]
> with v1.1.6 it seems to be stable!
> should i close this bug, or can i help to analyse the problem with newer versions?

Should leave it open, it is a bug on newer builds.

**Comment by Supereg** [comment]
We are currently preparing a follow up release to 1.2.x, namely 1.3.0, which is currently in beta. Can anyone of you who has experienced issues with 1.2 test that latest beta build (as long as you feel confident enough to do so) and report that if it improves your situation.

**Comment by SpunkyNoodle** [comment]
> We are currently preparing a follow up release to 1.2.x, namely 1.3.0, which is currently in beta. Can anyone of you who has experienced issues with 1.2 test that latest beta build (as long as you feel confident enough to do so) and report that if it improves your situation.

Just installed 1.3.0-beta.30 - will let you know if there is anything.

**Comment by ebini** [comment]
Hi, updated to this beta. 

<img width="285" alt="Bildschirmfoto 2020-12-05 um 12 41 57" src="https://user-images.githubusercontent.com/7239721/101241567-89b38e00-36f7-11eb-944b-4ea73bfb0ed7.png">

Got still the issue after some minutes: 
<img width="450" alt="Bildschirmfoto 2020-12-05 um 12 42 25" src="https://user-images.githubusercontent.com/7239721/101241571-920bc900-36f7-11eb-985a-8c50a27834e6.png">

**Comment by jnpatrick99** [comment]
1.3.0.beta31 doesn't work on my end (I tried 1.2.4 and 1.1.6 - neither of them works anymore either).

**Comment by SpunkyNoodle** [comment]
1.3.0-beta.30 - didn't have issues.
1.3.0-beta.31 - just updated now.

**Comment by ebini** [comment]
also with 1.3.0-beta.31  the same issue (devices not responding)

**Comment by Supereg** [comment]
@ebini just to be clear, as with 1.2.x, the 1.3.0 beta works at startup but then loses connection after some minutes, right? Or does it not work at all?

Can you do the following:
I would like to check if the bonjour advertising works as expected and like to gain some insights by looking at the hap-nodejs debug logs.

So heres a step by step guide:
* First of all it would be great to verify that 1.1.6 **is working** and that homebridge is correctly paired with your iOS device.
* In order to view bonjour advertisements on your network you can use something like the [Discovery App](https://apps.apple.com/de/app/discovery-dns-sd-browser/id305441017?l=en) available for iOS. Install that on some iDevice which is on the same network as homebridge. When opening you should be able to browser the `local` domain and see an entry like `_hap._tcp` (under this service type it should list all available HomeKit accessories on your network).
* Now install the homebridge 1.3.0 beta 31 via the UI
* Go to the Homebridge settings in the UI and modify the `DEBUG` environment variable like shown in the picture below. Setting it to `HAP-NodeJS:*`. This will enable debug output printed on the next startup.
* Now keep your discovery App ready and restart homebridge
  * Would be great if you can check, that a) a proper advertisement is displayed for homebridge (under domain `local` and service type `_hap._tcp`), b) when you open the advertisement the correct ip addresses are shown for your synonology  device and c) check if the advertising is removed at some point of time or if it stays there (you need to leave to detailed view from b) to see if the service is removed).
  * Secondly it would be great if you can provide the homebridge log **from startup** to the point where the devices **become unresponsive**.

I hope this guide is somewhat understandable. Otherwise just ask if anything is unclear.

<details>
<summary>Setting `DEBUG` variable  (Click to expand)</summary>

![hap-debug-mode](https://user-images.githubusercontent.com/9783857/101282695-d7eb8e80-37d6-11eb-9cba-92f9f1c5f781.jpeg)
</details>

**Comment by ebini** [comment]
Hi,
First of all a quick Feedback:
a) It is working with 1.1.6.
But I have in general a strange behaviour i cannot explain:
Homekit is working from:
2 Mac books, 2 ipads, and 1 iphone.
it has problems from AppleTV and Watch. 
b) With

**Comment by ebini** [comment]
sorry, pressed by accident the wrong button, wanted to close.

**Comment by ebini** [comment]
Hi ,

a) It is working with 1.1.6.

Note: But I have in general a strange behaviour i cannot explain:
Homekit is working from:
2 Mac books, 2 ipads, and 1 iphone.
it has problems from AppleTV and Apple Watch.
(Also disabling AppleTV as homekit as control station, don't know if this is the correct translation) changed the problem.

b) With newer Versions (also 1.3.0-beta.31) it works for a while (Minutes) and then the "Not Responding" appears.

Behavior with Discovery APP:

a) With 1.1.6

```
Homebridge E7A4 AB0C._hap._tcp.local.

0E_AD_5B_5A_E7_BB.local:51781
192.168.1.163:51781
172.17.0.1:51781
172.22.0.1:51781
fe80::42:d6ff:fe05:7e26%en0:51781
fe80::42:88ff:fed3:a056%en0:51781
fe80::d0c2:31ff:fe60:d9a3%en0:51781
fe80::440e:68ff:fe67:84bc%en0:51781
fe80::64c5:aeff:fe2d:7e2e%en0:51781
fe80::d8a6:7fff:fee5:4d84%en0:51781
fe80::d800:b3ff:feb5:1ff%en0:51781
fe80::347b:4dff:fe1b:78ce%en0:51781
fe80::b4bb:21ff:fec3:370e%en0:51781
fe80::4ce5:aeff:fecf:58cf%en0:51781
fe80::d8e5:2dff:fe66:b2e4%en0:51781
fe80::66:35ff:fe88:1963%en0:51781
fe80::18a1:8fff:fe0c:ef8c%en0:51781
fe80::1842:aff:fe62:258c%en0:51781
fe80::cd8:d0ff:fea1:3904%en0:51781
fe80::e007:43ff:fe36:e55e%en0:51781
fe80::78f5:14ff:fe47:3dd8%en0:51781
fe80::f896:93ff:feab:3d94%en0:51781
fe80::e8e7:31ff:fe68:714e%en0:51781
fe80::94fc:1cff:fe9e:f4f8%en0:51781
fe80::6437:9fff:feb1:7bc3%en0:51781
fe80::acc4:7fff:fe29:795c%en0:51781
fe80::486b:59ff:feb2:5922%en0:51781

c# = 8
ci = 2
ff = 0
id = 0E:AD:5B:5A:E7:BB
md = Homebridge E7A4
pv = 1.1
s# = 1
sf = 0
sh = zjgZvg==
```

b) With 1.3.0-beta.31
at the beginning i found the homebridge device with:
```
Homebridge E7A4 AB0C._hap._tcp.local.

Homebridge-E7A4-AB0C.local:51781
192.168.1.163:51781

c# = 9
ci = 2
ff = 0
id = 0E:AD:5B:5A:E7:BB
md = homebridge
pv = 1.1
s# = 1
sf = 0
sh = zjgZvg==
```

Then it disappears also

About the logs.:
[homebridge_backup.log](https://github.com/homebridge/homebridge/files/5649183/homebridge_backup.log)

I'm a little bit confused by
ipv6 adresses:
in synology it is disabled: 
<img width="890" alt="Bildschirmfoto 2020-12-06 um 18 13 58" src="https://user-images.githubusercontent.com/7239721/101287230-4b00ff00-37ef-11eb-8a3d-7192c5bd74f2.png">

also in my router/dhcpserver:

<img width="680" alt="Bildschirmfoto 2020-12-06 um 18 16 48" src="https://user-images.githubusercontent.com/7239721/101287234-518f7680-37ef-11eb-9802-d7736cd7564f.png">

**Comment by SpunkyNoodle** [comment]
I went back to 1.2.4 - error start to shows up for Nest devices.
back to 1.3.0-beta.31 - looks no error, working.

**Comment by Supereg** [comment]
@SpunkyNoodle so Nest devices work with the beta but not with 1.2.4?

@ebini The output of the Discovery App looks good. Regarding your question about IPv6: the old mdns library, probably exposes a lot of internal network interfaces (like docker or so defines a lot of those). The new mdns library improves on those and really only advertises ip addresses which are actually reachable. This should speed up the first connection attempt.

Looked at the logs, so far I can't see anything suspicious really. I see the point after around 2 minutes after startup where suddenly all connections just loose/close connection.

Could you do the following. Could you modify the `DEBUG` environment variable again to enabled debug as well of the mdns library `ciao`. So set the `DEBUG` to `ciao:*,HAP-NodeJS:*`, then restart and send me the logs again.

**Comment by SpunkyNoodle** [comment]
It's working for Nest thermostats E just throwing random errors.

![image](https://user-images.githubusercontent.com/75095713/101532808-0c8c5100-3963-11eb-877a-52f891e30be3.png)

**Comment by ebini** [comment]
> Could you do the following. Could you modify the `DEBUG` environment variable again to enabled debug as well of the mdns library `ciao`. So set the `DEBUG` to `ciao:*,HAP-NodeJS:*`, then restart and send me the logs again.

- adepted DEBUB Variable, upgraded to latest Beta (First line in logs)
- waited until devices gone to "not responding". And Turned on/off the dummy switch (Schalter test)
- Back to stable Version (last line in logs)

[homebridge_DEBUG2.log](https://github.com/homebridge/homebridge/files/5664479/homebridge_DEBUG2.log)

**Comment by Supereg** [comment]
Thanks 👍🏽 I’ll try to have a look at it as soon as possible.

**Comment by genebean** [comment]
I am also on a UDM and noticed that the automatic network optimization disables multicast on wifi... things are looking better for me now that I disabled that setting.
