### ISSUE TITLE
Homebridge should indicate in HomeKit when it has outdated plugins

### ISSUE THREAD

**Issue by lilyball** [homebridge/homebridge#2720]
**Describe The Bug:**
There's no indication in HomeKit that Homebridge has outdated plugins. This is very annoying. Every time I go to Homebridge's UI for some unrelated reason I discover that it has outdated plugins, but I shouldn't have to manually check the homebridge UI to find this out.

**To Reproduce:**
1. Install a plugin and use it
2. Wait for the plugin to put out an update
3. Check Home

**Expected behavior:**
There should be some indication in Home that something is out of date. I don't know if this should show up as the firmware for any accessories vended by the plugin as having outdated firmware (which might be an issue if the plugin can actually expose the real firmware info for the accessory), or if the bridge should show up as having outdated firmware (though this may require synthesizing some fake firmware version number that can be incremented with plugin updates). Or maybe there's some other way to indicate that an updated is needed.

I checked the HAP Non-Commercial Spec and I don't actually see how to declare that there's a firmware update, but there were references to bridges/accessories exposing services for firmware updates. And I'm pretty sure in the past I've had a certified HomeKit accessory indicate that it had a firmware update available in the Home app.

I am not asking to actually be able to update the plugins from Home; I think seeing the changelog is important and I assume Home can't do that. I just want some indication that there are outdated plugins so I can go fix them.

**Environment:**

* **Node.js Version**: v14.15.1
* **NPM Version**: v6.14.8
* **Homebridge Version**: 1.2.3
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd

**Comment by Supereg** [comment]
> I checked the HAP Non-Commercial Spec and I don't actually see how to declare that there's a firmware update, but there were references to bridges/accessories exposing services for firmware updates

Thats exactly it. The HomeKit Accessory Protocol **currently** doesn't support any mechanism to indicate that there is a firmware update available or support any way of running firmware updates via the Home App.
For certified accessories this is done out of band. The Home App checks on an Apple Server if there is a firmware update available for the given (with Apple registered) accessory.

Although support for such a firmware update mechanism is coming with iOS 14.3: https://9to5mac.com/2020/11/12/ios-14-3-changes-features/.
It remains unclear if this will be part of the public Non-commercial spec or if not if we can reverse engineer that to add support for that.

**Comment by Supereg** [comment]
Will close the issue for now, as we can’t really do anything about it.
I assure you, should there be the possibility to support plugin updates via Home App we will try our best to implement that.
