### ISSUE TITLE
Reinstall homebridge using hb-service?

### ISSUE THREAD

**Issue by cappadanna** [homebridge/homebridge#2721]
Hi,

I installed Homebridge a few years ago before Homebridge Config UI X and hb-service. Currently running Homebridge v1.1.6, Node.js v12.18.4 and Npm  v6.14.6 on a Raspberry Pi 3 B+

Now I'm thinking of updating node to v14 but i'm terrified it will screw my system up. I'm not very experienced with this. Can't really remember how I installed node (I used the old Homebridge guide) It seems much easier if I could use "sudo hb-service update-node" but since I installed Homebridge using the old guide, I don't think I can do that right?

Is it possible to reinstall Homebridge using hb-service? I think I'm running Homebridge as systemd as it says "Loading logs using "systemd" method..." in the log

Or is it better to leave it and try to update node?

**Comment by oznu** [comment]
>  It seems much easier if I could use "sudo hb-service update-node" but since I installed Homebridge using the old guide, I don't think I can do that right?

This works even if you're not using `hb-service` to run the process.

If your current service is named "homebridge" and your storage directory is `/var/lib/homebridge` you can do this to easily swap over:

Stop the existing service:

```
sudo systemctl stop homebridge
```

Replace it with the hb-service powered one:

```
sudo hb-service install --user homebridge
```

**Comment by cappadanna** [comment]
Wow, that worked perfectly. Thank you so much!
