### ISSUE TITLE
Can't update node.js

### ISSUE THREAD

**Issue by facundo59** [homebridge/homebridge#2723]
Hello,

I've been trying to update node.js with `sudo hb-service update-node` for one of my plug-ins (Meross) with no avail. It just stucks there totally blank (over 20min already) showing nothing. I can't write a second command. I do no know how to "see the progress" and check where is it failing (is there a verbatim mode?).

`
pi@homebridge:/var/lib/homebridge $ node -v`
`v12.18.1`
`
pi@homebridge:/var/lib/homebridge $ which node`
`/usr/local/bin/node`

I installed Homebridge through the official Pi image and then only used confiig-iu-x. So nothing out of the ordinary.

Just request me if you need any further information.

Cheers,

Facundo

**Comment by oznu** [comment]
I'm guessing a Raspberry Pi Zero or 1?

Please try update using this method: https://github.com/homebridge/homebridge-raspbian-image#updating-nodejs

**Comment by iBanks3** [comment]
I had to download and reinstall Node.JS to get the updated version as I too ran into the same issue as you. Works fine. I had to use.
# setup repo
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

# install Node.js
sudo apt install -y nodejs gcc g++ make python net-tools

# test node is working
node -v

**Comment by facundo59** [comment]
> 
> 
> I'm guessing a Raspberry Pi Zero or 1?
> 
> Please try update using this method: https://github.com/homebridge/homebridge-raspbian-image#updating-nodejs
> 
> > To update Node.js run `sudo hb-config` and select `Upgrade Node.js`.

Actually a Pi 4 with extra RAM.

I tried your suggestion and it worked! Thank you! 👍 

I close the issue :)
