### ISSUE TITLE
unicast response guessing an mdns issue?

### ISSUE THREAD

**Issue by flynhawaiian** [homebridge/homebridge#2724]
**Describe The Bug:**
ciao:Responder Sending response via unicast to {"address":"192.168.1.207","port":5353,"interface":"eth0"} (took 2 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 343B (UPS: 1440)

**Expected behavior:**
New issue guessing due to the mdns change in homebridge I read about?

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 12.18.3
* **NPM Version**:  6.14.8
* **Homebridge Version**:  1.3.0-beta.25
Homebridge
Running
Plugins

* **Operating System**: Raspbian
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment]
This looks like a standard debug message? @Supereg will confirm.

We have forced the ciao debug logs to be enabled on the all beta builds right now.

**Comment by Supereg** [comment]
@flynhawaiian what's the issue. Thats just a status message saying what's going on. As you are seemingly running the beta(?) (or have some special debug messages turned on) it will print additional information by default so we can more easily get to information we need in the case of a bug report.

**Comment by Supereg** [comment]
As there isn’t any problem and the creator didn’t provide any details why there might be a problem, im gonna close the issue for now
