### ISSUE TITLE
sudo npm install -g --unsafe-perm homebridge-alexa

### ISSUE THREAD

**Issue by Metempsicosi** [homebridge/homebridge#2725]
**Describe Your Problem:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by Supereg** [comment]
Please describe your problem and provide any necessary logs/error messages.
Otherwise we can’t help you and the issue will be closed.
