### ISSUE TITLE
Version needs to be updated on NPM

### ISSUE THREAD

**Issue by WTell** [homebridge/homebridge#2726]
NPM currently lists **1.1.6** as the latest version of homebridge, which causes `npm outdated` to complain about the discrepancy.

```
$ npm outdated -g --long
Package     Current  Wanted  Latest  Location  Package Type  Homepage
homebridge    1.2.3   1.2.3   1.1.6  global    dependencies  https://github.com/homebridge/homebridge#readme
```

The version number should be updated on [npmjs.com](https://www.npmjs.com/package/homebridge) as new versions are released.

**Comment by Supereg** [comment]
homebridge 1.1.6 **is** the **latest stable** version. 1.2.3 is deliberately not set as the latest stable version as it has been pulled.

**Comment by WTell** [comment]
No wonder NPM is confused. Github lists [1.2.3 as the latest release](https://github.com/homebridge/homebridge/releases):

![Screenshot 2020-11-24 at 21 09 48](https://user-images.githubusercontent.com/31923174/100145985-799ae380-2e99-11eb-9bec-ffc20c975754.png)

For what it's worth, I've been running homebridge 1.2.3 since release across two installations with six plugins, and I'm enjoying a better experience with 1.2.3 than the pre-1.2-releases.

**Comment by Supereg** [comment]
GitHub just lists the releases in the order they were created.
NPM doesn't care what GitHub lists there, they work independent from each other.

> For what it's worth, I've been running homebridge 1.2.3 since release across two installations with six plugins, and I'm enjoying a better experience with 1.2.3 than the pre-1.2-releases.
