### ISSUE TITLE
Restarting Homebridge via cron

### ISSUE THREAD

**Issue by AviFix** [homebridge/homebridge#2730]
HI,

Once in a while, Siri and Alexa stop responding until I restart Homebridg.

I could like to restart homebridge via cron task every 01:00 AM (without restarting the pi).

What is the command to restart Homebridge?

Thanks

**Environment:**

* **Node.js Version**: 12.18.0
* **NPM Version**: 6.14.4
* **Homebridge Version**: 1.1.6
* **Operating System**: Raspbian

**Comment by oznu** [comment]
The command to restart homebridge will vary based on how you setup Homebridge as a service.

If you followed one of our wiki install guides, you can find the restart the command for your platform in the "Configuration Reference" table at the bottom of each guide:

https://github.com/homebridge/homebridge/wiki
