### ISSUE TITLE
Custom hostname not working

### ISSUE THREAD

**Issue by Hamsterman** [homebridge/homebridge#2731]
I have homebridge for docker (on Ubuntu) running (v1.2.3).

In the UI Settings > Advanced > Reverse Proxy Hostname
I have set the value to "homebridge.mydomain.com"

In my DNS I have pointed homebridge.mydomain.com to the IP of the dockerserver.

I have ReverseProxy (jwilder/nginx-proxy:latest) running which catches all 443/80 trafic.
The hombridge is configured to be running on port 8082

When I type http://<IPofDockerServer>:8082 into the browser it works
When I type https://homebridge.mydomain.com with a port I get a 502 Bad Gateway

What am I missing here ?

**Comment by oznu** [comment]
> When I type https://homebridge.mydomain.com with a port I get a 502 Bad Gateway

This is an issue with your reverse proxy configuration and unrelated to the "hostname" config option.

Setting the host name is not required if you correctly configure nginx. An example config can be found here:

https://github.com/oznu/homebridge-config-ui-x/wiki/Reverse-Proxy:-Nginx-and-SSL

**Comment by Hamsterman** [comment]
I am not looking for a way to install the SSL certificate into the homebridge. Thats why I have the the Reverse Proxy. The homebridge should just respond to simple http trafic but for some reason it does not.

**Comment by oznu** [comment]
The location block in the example is relevant for both http and https endpoints.

```
location / {
    proxy_pass                  http://127.0.0.1:8080; # replace 8080 with the port the ui is running on
    proxy_http_version          1.1;
    proxy_buffering             off;
    proxy_set_header            Host $host;
    proxy_set_header            Upgrade $http_upgrade;
    proxy_set_header            Connection "Upgrade";
    proxy_set_header            X-Real-IP $remote_addr;
    proxy_set_header            X-Forward-For $proxy_add_x_forwarded_for;
  }
```

**Comment by Hamsterman** [comment]
I am not getting what you are saying at all I am afraid.

Are you telling me to update the homebridge setup or the Reverse Proxy ?
And if you are saying the Reverse Proxy I need to have some more understanding of why the homebridge does not work out of the box as all my other images that pass through the Reverse Proxy?

**Comment by oznu** [comment]
Your reverse proxy is not working. A 503 means the connection from your reverse proxy to homebridge was never established.

A reverse proxy running nginx requires those config options to work fully with Homebridge. However since you're getting a 503 - this probably means there is another issue you need to solve with your proxy container first.
