### ISSUE TITLE
setting up mDNS with multiple vlans

### ISSUE THREAD

**Issue by MatthewGCampbell** [homebridge/homebridge#2734]
{
    "mdns": {
        "interface": "10.1.15.107"
    },
    "bridge": {
        "name": "xxxxxx",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51424,
        "pin": "420-69-420"
    },

added mDNS above my bridge block but how would I be able to add more than one address?
issue is that it won't pair to Homekit.
also, when unpairing these bridges after a reboot then come back, where are the paired bridges stored?
<img width="885" alt="Screen Shot 2020-11-29 at 3 03 23 PM" src="https://user-images.githubusercontent.com/31420840/100553216-8719ea00-325a-11eb-9ca7-4328808ef996.png">

**Comment by Supereg** [comment]
What version of homebridge are you running?

**Comment by Supereg** [comment]
And could you quickly describe how your network setup looks exactly?

**Comment by MatthewGCampbell** [comment]
eth0.25 (network that wifi clients connect to) and eth0.332 (all my IOT stuff) when im on the wifi I am unable to find home bridge installed avahi thinking that might help. 
+ eth0.25 IPv4 Raspverry Pi 4 (with POE HAT) D751            _hap._tcp            local
+ eth0.25 IPv4 Entertainment Room LG TV 89FA                 _hap._tcp            local
+ eth0.25 IPv4 hb [dc:a6:32:a6:ff:d8]                        Workstation          local

config file says it allows allow-interfaces=eth0.25,eth0.322 (set at /etc/avahi/avahi-daemon.conf) but I don't see any eth0.332 which could be my problem. But I only need access on eth0.25 also have this in my config.json file
(
    "mdns": {
        "interface": "10.1.15.107"
    },
set but i'm not sure how to setup multiple networks with that, kinda new to Homebridge 
can I do this?
(
    "mdns": {
        "interface": "10.1.15.107", "XX.XX.XX.XX"
    },

**Comment by MatthewGCampbell** [comment]
installed the 1.3.0 beta to see if that would help but it didn't do much

**Comment by Supereg** [comment]
Is the device homebridge is running on connected to both networks (like via two interfaces) or how do you bridge those two vlans?

**Comment by Supereg** [comment]
If you are running homebrige beta 1.3.0 the `mdns` config section is deprecated and not used anymore (as it was quite limiting and used by an old mdns library).

There is a new option `bridge.bind` which accepts interface names and also an array of interface names.
So you could incorporate the following.

```json5
{
  "bridge: {
    "bridge: ["eth0.25", "eth0.322"
  }
}
```

**Comment by MatthewGCampbell** [comment]
Ah got ya so i don’t need avahi?

**Comment by Supereg** [comment]
No. Homebridge ships with its own mdns implementation.

**Comment by MatthewGCampbell** [comment]
So its like?
{
  "bridge: {
    "bind": ["eth0.25", "eth0.322"
  }
}

**Comment by MatthewGCampbell** [comment]
<img width="1792" alt="Screen Shot 2020-11-29 at 8 04 29 PM" src="https://user-images.githubusercontent.com/31420840/100558850-256b7700-327e-11eb-9821-92ec80b51374.png">
i get a error, i forget what the [] mean in json files

**Comment by Supereg** [comment]
You can use something like https://jsonlint.com to verify you json syntax. In your case you are missing a comma `,` behind the closing bracket of the array (line 6).

> Does look to be doing something though without those lines:

Yes ciao (the mdns library) will advertise itself on all interfaces it find by default.

**Comment by MatthewGCampbell** [comment]
So if ciao is working why can I still not find it with the Home app do I still need to add the bridge.bind stuff in the json?

Thanks

**Comment by Supereg** [comment]
Could you maybe describe your current VLAN/network setup?

**Comment by MatthewGCampbell** [comment]
VLAN 25. This is the VLAN that all my trusted wifi devices are on. VLAN 322 is where all my IOT wifi devices are and just the regular lan that homebridge is connected to is all my trusted wired devices. These vlans can’t talk to each other hits the fact that i need them enabled on homebridge, could be that i’m blocking multicast data on the wifi that my iPhone is connected to i just turned that off and ill respond back if finding homebridge is still an issue.

**Comment by MatthewGCampbell** [comment]
Multicast seems to have been the issue
