### ISSUE TITLE
Home bridge not changing the state of lights. 

### ISSUE THREAD

**Issue by kenkomaromi** [homebridge/homebridge#2735]
I'm having issues with lights not changing state.

My lights show up in home bridge and show if they are on or off, but when I go to turn them on or off, nothing happens.

I dont get any errors in the logs either. I tried multiple style lights and even tried running homebridge on a raspberry pi (from windows 10)

Secondary Homebridge Logs here
```

**Homebridge Config:**
{
    "bridge": {
        "name": "Homebridge 3A15",
        "username": "0E:A2:D7:91:86:DE",
        "port": 51830,
        "pin": "178-95-951"
    },
    "description": "Homeseer",
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "HomeSeer",
            "host": "http://192.168.1.50:90/",
            "ASCIIport": 11000,
            "login": "admin",
            "password": "(removed)",
            "Lightbulbs": [
                41
            ],
            "platform": "HomeSeer"
        }
    ],
    "accessories": []
}
```json
Show your homebridge config.json here
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/62118594/101209884-67ebd580-3629-11eb-932c-b37e8561df4c.png)
![image](https://user-images.githubusercontent.com/62118594/101209956-8fdb3900-3629-11eb-9830-f41991ba99a4.png)

[New Compressed (zipped) Folder.zip](https://github.com/homebridge/homebridge/files/5645244/New.Compressed.zipped.Folder.zip)

**Environment:**

* **Node.js Version**: v12.16.1
* **NPM Version**: 
* **Homebridge Version**: 1.1.6
* **Operating System**: **Raspbian** / Ubuntu / Debian / **Windows** / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / **hb-service** / other / none

**Comment by milo526** [comment]
Hey;

You'd probably get a better response from the plugin creator you can reach them [here](https://github.com/jvmahon/homebridge-homeseer4#readme).
