### ISSUE TITLE
iPad hub disconnecting 

### ISSUE THREAD

**Issue by galoiring** [homebridge/homebridge#2737]
**Describe The Bug:**
iPad is the home hub and disconnecting sometimes

my iPad is the home hub , and it sometimes disconnect from all the HB devices (HomeKit devices work fine).
if I open the home app in the iPhone I see all the devices up and running.
after I shut down Wifi on the iPad and reopen in start working again.
I use Tp-Link router.

**To Reproduce:**
Turn off and reopen wifi on the iPad

**Expected behavior:**
nothing showed on the log

**Screenshots:**

**Environment:**

* **Node.js Version**: v15.3.0
* **NPM Version**: v7.0.14
* **Homebridge Version**: v1.2.3
* **Operating System**: Raspbian 
* **Process Supervisor**:  hb-service

**Comment by Supereg** [comment]
As you are running 1.2.3, would you mind upgrading to 1.2.4 ( I assume you have homebridge UI installed). Just click on the homebridge version on the dashboard and it should give you the option to select a new version.

**Comment by galoiring** [comment]
ok im doing that now , I thought it was up to date , because it says "up to date"

**Comment by Supereg** [comment]
> because it says "up to date"

yeah, 1.2.4 is a rather fresh release, and will be suggested as an update over the next few days for people running 1.2.x versions. 

Any results/improvements so far?

**Comment by galoiring** [comment]
this was helpful actually , but now I update to 1.2.5 and it once again disconnecting all the time .. What can I do ?


<img width="1280" alt="צילום מסך 2021-01-03 ב-11 23 00" src="https://user-images.githubusercontent.com/74841666/103475475-149aad80-4db6-11eb-95eb-075bed913a27.png">

**Comment by galoiring** [comment]
Someone ?
