### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by imf123** [homebridge/homebridge#2738]
Hi friends,

I’ve recently installed Homebridge on a new Pi4, my first Pi project. Everything is working great and I can control everything from the Homebridge.local site. However, I’m not able to log in to the actual Pi itself. I’ve tried the default admin / admin login information and the changed login information I set myself and no dice. Any suggestions? This is my first time doing anything remotely this techhy so any help is appreciated!

Thanks!

![image](https://user-images.githubusercontent.com/75583173/101289426-96001f80-37b9-11eb-82f3-2720883ddeaf.jpg)

**Comment by milo526** [comment]
Please see the documentation on [SSH-Access](https://github.com/homebridge/homebridge-raspbian-image#ssh-access).

It states that the username and password to connect to the pi via terminal is `pi`/`raspberry` (this is the default for a "standard" raspbian installation also)

**Comment by oznu** [comment]
@milo526's answer is spot on.

These credentials are listed on the readme and wiki page for the image.
