### ISSUE TITLE
Multiple plugins hitting EHOSTUNREACH errors

### ISSUE THREAD

**Issue by ydogandjiev** [homebridge/homebridge#2739]
**Describe Your Problem:**
I have Homebridge installed on a Raspberry Pi 3. Recently I started seeing multiple plugins hitting the same EHOSTUNREACH errors which is impacting their functionality.

Troubleshooting steps taken:
1. Restarting my Homebridge server multiple times
2. Restarting my routers (Eero Pro)
3. Assigning a static IP address to Homebridge
4. Disabling some of the Eero experimental features (e.g. Local DNS caching)

Unfortunately none of the steps appear to have made a difference and I am still seeing the same errors.

**Logs:**

```
[12/6/2020, 12:52:11 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/23586bbd-5839-4ed8-845d-557d27155344.  connect EHOSTUNREACH 54.242.113.239:443.  Trying again in 5 seconds...
[12/6/2020, 12:52:16 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/23586bbd-5839-4ed8-845d-557d27155344.  connect EHOSTUNREACH 54.242.113.239:443.  Trying again in 5 seconds...
[12/6/2020, 12:52:20 PM] [LitterRobotPlatform] Error syncing Litter-Robot a8afe801fdba02: connect EHOSTUNREACH 13.224.10.93:443
[12/6/2020, 12:52:21 PM] [Ring] Failed to reach Ring server at https://app.ring.com/api/v1/mode/location/23586bbd-5839-4ed8-845d-557d27155344.  connect EHOSTUNREACH 54.242.113.239:443.  Trying again in 5 seconds...
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 1A44",
        "username": "***",
        "port": 51433,
        "pin": "***"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "SmartThings-v2",
            "app_url": "https://graph-na04-useast2.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "***",
            "access_token": "***",
            "direct_port": 8000,
            "temperature_unit": "F",
            "validateTokenId": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": true,
                "hideNamePrefix": true,
                "file": {
                    "enabled": true,
                    "level": "good"
                }
            },
            "platform": "SmartThings-v2"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "***",
                "cookies": "***",
                "apiKey": "***"
            },
            "platform": "Nest"
        },
        {
            "email": "***",
            "password": "***",
            "platform": "NeatoVacuumRobot"
        },
        {
            "refreshToken": "***",
            "platform": "Ring"
        },
        {
            "name": "Tilt Bridge",
            "username": "***",
            "password": "***",
            "closeUp": false,
            "platform": "MySmartBlindsBridge"
        },
        {
            "username": "***",
            "password": "***",
            "hideTrayAccessory": true,
            "pollingFrequency": 60,
            "platform": "LitterRobotPlatform"
        }
    ]
}
```

**Environment:**

* **Node.js Version**: v14.15.0
* **NPM Version**: v6.14.8
* **Homebridge Version**: v1.2.3
* **Operating System**: Raspbian 9 (stretch)
* **Process Supervisor**: hb-service v4.35.0

**Comment by oznu** [comment]
See this article for some tips: https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Fix-Eero-Router-Internet-and-DNS-Connectivity-Issues

Ultimately though this is a network / local issue on your end though; not a homebridge issue.

**Comment by ydogandjiev** [comment]
Thanks @oznu! That article seems to imply that I need to chose between the Eero Advanced Security feature and running Homebridge without issues? Is that correct? That doesn't seem like a great tradeoff especially given that the Advanced Security feature of Eero was one of the reasons I bought that system.

**Comment by oznu** [comment]
> Is that correct? 

I don't know. The steps are to help you highlight where the problem might be and allow you to come up with a solution that works for you. 

If Eero is not allowing network connections to valid devices, then that's an issue with Eero.

**Comment by ydogandjiev** [comment]
> If Eero is not allowing network connections to valid devices, then that's an issue with Eero.
I don't think Eero is blocking connections to valid devices. The errors in my Homebridge log imply that plugins are running into problems when trying to hit Ring's or Litter Robot's web services. I have at least 30 other web-connected devices at home and none of them have hit these issues which makes me wonder if there is something that Raspbian or Homebridge are doing differently. In any case, I've reached out to Eero's customer support so I can see what's their take on the matter.

**Comment by oznu** [comment]
The `HomeKit Accessory Security` feature could be the main issue. Have you turned off restrictions for the Homebridge/Raspberry Pi devices?

**Comment by ydogandjiev** [comment]
> The `HomeKit Accessory Security` feature could be the main issue. Have you turned off restrictions for the Homebridge/Raspberry Pi devices?

I think you might be right! As soon as I turned off HomeKit Accessory Security the errors went away. I am going to try re-enabling the feature now but with Homebridge set to "No Restriction". Reading over the way this feature works, I can totally see how it could have caused the problems I was seeing. Apple probably has no clue what services Homebridge is capable of talking to and as a result ends up blocking various legitimate connections.

![image](https://user-images.githubusercontent.com/3357245/101310500-e2704d00-3803-11eb-8cc4-dac9e7b47253.png)
