### ISSUE TITLE
Custom services not displayed

### ISSUE THREAD

**Issue by mersed** [homebridge/homebridge#2740]
I am having issues creating custom service while implementing homebridge plugin.

I used https://github.com/homebridge/homebridge-plugin-template as a starting point, and everything works fine - all functions within documentation and documented services - all good.

However, I am struggling to display custom service.

Based on the check i performed by checking currently created plugins or older threads with similar questions, creating custom service and custom characteristics seems relatively simple.

For example, in my case, this is the file which would create both of these:

```javascript
import { Characteristic, Service, Perms, Formats, Units } from 'hap-nodejs';

export class Delay extends Characteristic {
    static readonly UUID: string = '000000A4-0000-1000-8000-0026BB765298';

    constructor() {
      super('Delay', Delay.UUID);
      this.setProps({
        format: Formats.UINT32,
        maxValue: 10000000,
        minValue: 0,
        minStep: 0.1,
        unit: Units.SECONDS,
        perms: [Perms.PAIRED_READ, Perms.PAIRED_WRITE, Perms.NOTIFY],
      });
      this.value = this.getDefaultValue();
    }
}

export class Ping extends Service {
    static UUID = '00000085-0000-1000-8000-0026BB765215';
    
    constructor(displayName: string, subtype?: string) {
      super(displayName, Ping.UUID, subtype);

      this.addCharacteristic(Delay)
      this.addOptionalCharacteristic(Characteristic.Name);
    }
}
```

And then within accessory, simply:
```javascript
const customPing = this.accessory.getService('Ping test') ||
        this.accessory.addService(Ping, 'Ping test', 'UniqueIdentifier-qasdasfdgs');
console.log(Ping);
```

And this works fine. No error is throwned, console indicate that we have service with proper characteristis etc ... However, this service is not displayed on phone side, nor within ui of homebridge-config-ui-x.

Do you have any ideas what im doign wrong here?

**Comment by oznu** [comment]
Custom service types are only displayed in an app that knows how to handle the custom service types. 

For example; Eve HomeKit devices have custom characteristics for monitoring energy usage, and they added support for this type in their own app, but it's not displayed in the native Home app.

If you're defining your own services - they'll either need to be for internal use only (like tracking the state of something to facilitate something else) or write your own iOS HomeKit app (not a small job!).

**Comment by ebaauw** [comment]
Have you tried Eve?  Apple’s Hone app doesn’t support custom characteristics, nor services.

**Comment by mersed** [comment]
@oznu @ebaauw I see. Well sorry because of my ignorance, I was not aware of that (this is actually first plugin I am implementing).

Is there something like general service in list of the services Apple Home supports, which I could use to display/represent server data monitoring (like DNS check and Ping) ?

@ebaauw Did not try Eve, but will take a look into that as well. Thank you.

**Comment by ebaauw** [comment]
Generally speaking, Home supports the Apple-defined standard services and characteristics.  See the HAP spec, https://developer.apple.com/support/homekit-accessory-protocol/.  I actually tend to look in the HAP-NodeJS source, https://github.com/homebridge/HAP-NodeJS/tree/master/src/lib/gen.
