### ISSUE TITLE
Cannot Add Devices

### ISSUE THREAD

**Issue by sterrynorman** [homebridge/homebridge#2742]
Connected to Amazon Account, Homebridge installed on a Mac, everything seemingly working correctly.  The Alexa plugin will not get the devices for HomeKit.

If I try to add the bridge to HomeKit I only get the bridge.

Just need some guidance please.

**Comment by NorthernMan54** [comment]
For help with the Alexa plugin, please chat with us on the #Alexa channel of the homebridge discord server or open an issue against the homebridge-alexa repo and not here against homebridge.
