### ISSUE TITLE
Unable to add Homebridge to Homekit

### ISSUE THREAD

**Issue by marasbird** [homebridge/homebridge#2743]
Hello, I updated to 1.2.4 today but after install update my accessories does not reponding.
So I restarted Raspberry Pi 4B and still nothing.
I try remove my Home from HomeApp and try add Homebridge instance again but can't. It's not reachable.
In Homebridge UI every accessories working.
Then i rollback to 1.2.3 and still I have the same problem ...
Try restart router but it don't help.
I can't add homebridge to Homekit.

OS | Raspbian GNU/Linux Buster (10)
Hostname: raspberrypi
IP: 192.168.0.20
IPv6: fe80::dea6:32ff:fe7d:a5a1
Node.js: v14.15.1
Npm: v6.14.8
User: homebridge

I have static IP on eth0 in /etc/dhcpcd.conf

Try "mdns": { "interface": "192.168.0.20" }, but no change :(. Still not working and can't add to Home App.

**Comment by Supereg** [comment]
Just a few questions:
* From which version did you upgrade to 1.2.4
* When you say you updated to 1.2.4, it sounds like your where already running homebridge, why the need to **add** homebridge again to Home? I assume you would have already created a pairing?
* When you say not reachable you mean it doesn't show up in the pairing screen?
* Could it be that homebridge still thinks it is paired with some other HomeKit instance?

**Comment by marasbird** [comment]
> Just a few questions:
> 
> * From which version did you upgrade to 1.2.4
> * When you say you updated to 1.2.4, it sounds like your where already running homebridge, why the need to **add** homebridge again to Home? I assume you would have already created a pairing?
> * When you say not reachable you mean it doesn't show up in the pairing screen?
> * Could it be that homebridge still thinks it is paired with some other HomeKit instance?

I upgraded from 1.2.3
Yes, I already have homebridge without any problems. But when I update from 1.2.3 to 1.2.4 accessories stop respond in Home App. So I try remove all from Home App and try pair it again with QR and code in Homebridge UI X.
When I try add homebridge to Home app again. Nothing is found.

I try reset homebridge and remove all instances from all apple products. 

Still cant add homebridge to Home app. Its look like there is no signal from homebridge.

**Comment by Supereg** [comment]
> But when I update from 1.2.3 to 1.2.4 accessories stop respond in Home App. So I try remove all from Home App and try pair it again with QR and code in Homebridge UI X.

So you unpaired from homebridge while it was not reachable right? This will remove the pairing on the Home App side, but as the Home App can't contact the accessory, the accessory still thinks it is paired and won't show up in the Home App.

When using Homebridge UI, you can navigate to Homebridge settings and open the menu for "Unpair Bridges / Cameras / TVs / External Accessories ". Reset the pairing for any accessories listed there, restart and check if the accessory shows up again.

**Comment by marasbird** [comment]
I did it but still cant pair homebridge to Home App. When I try add homebridge to Home App there is still loading and then it says that there is nothing to add.

**Comment by Supereg** [comment]
Still running 1.2.4 or did you rollback to 1.2.3?

**Comment by Supereg** [comment]
To get stuff working again, I'll got either suggest to try the 1.3.0-beta or to roll back to 1.1.6 🤔

**Comment by marasbird** [comment]
> Still running 1.2.4 or did you rollback to 1.2.3?

Update to 1.2.4 again. But try 1.3.0 beta as well but no difference. Still cant pair. When i rollback to 1.2.3 nothing happen.

**Comment by marasbird** [comment]
> To get stuff working again, I'll got either suggest to try the 1.3.0-beta or to roll back to 1.1.6 🤔

Rollback to 1.1.6 help in search homebridge automaticly. Now its visible. But when try to add, I getting error: cant add accessory
 to Home App.

![7A92CBCF-BE24-43EB-8545-7B7E52BE6F16](https://user-images.githubusercontent.com/60778323/101538206-09ae5200-399d-11eb-91ce-0fcdf726bab2.png)
 
Its in my language, but it says Its unable to add.

**Comment by marasbird** [comment]
I was able to add everything on iPad today.

**Comment by Supereg** [comment]
Could you explain what solved this for you?
What version of homebridge are you running now?

**Comment by marasbird** [comment]
On iPad it was possible to add homebridge to Home App. So now is in iphone as well. Now running 1.1.6

**Comment by daquezada** [comment]
I just installed Homebride and  I am not able to added to HomeKit.

**Comment by scegg** [comment]
I just installed Homebridge from scratch and scan the QR from iOS Home app -> Accessory Not Found.

**Comment by jkhoob** [comment]
I just did fresh install and I'm getting the same message "Accessory Not Found" as well. I was having same issue on Hoobs. I thought maybe it might be Hoobs so I tried homebridge but same. I was able to add other accessories like eufy and ecobee with no issues.

**Comment by LexuSSDriver** [comment]
Same thing here. Setup my Synology NAS this afternoon, Installed HomeBridge. Added some Meross plugs, the single plugs went fine, the double plugs are having issues, submitted a ticket on those, tried adding HomeBridge to Home and nothing with the QR code or the 8 digit code. Tried with both my iPad as well as my iPhone. Nada....

**Comment by RobinMac** [comment]
Wow

**Comment by endy128** [comment]
I believe I was having the same issue and I change the protocol from Bonjour in the settings and HomeKit found the bridge straight away are that.

**Comment by endy128** [comment]
> > I believe I was having the same issue and I change the protocol from Bonjour in the settings and HomeKit found the bridge straight away are that.
> 
> In which settings? In the settings of the ios device or in the homebridge?

On the homebridge

**Comment by NorthernMan54** [comment]
Homebridge UI

three dot menu on the top right side, Homebridge Settings --> mDNS Advertiser

**Comment by sealedge** [comment]
Hey all, also unable to add Homebridge to HomeKit (via iPhone 12). Either Accessory not found (if by QR Code) or Times out on Select an Accessory (if by HB code).

Any suggestions?

**Comment by Dliix66** [comment]
Same here, it times out saying accessory not found :/ Running HomeBridge 1.4.1

**Comment by saymonaraujo** [comment]
same here,
I did the installation on a Ubuntu Focal Fossa (20.04.3 LTS), there's no firewall and app armor is disabled. 
I enabled the debug but no log is generated.
I did a tcpdump during the connection and a lot of packets is coming and going.
Anyone has any clue ? 
I'm using as mDNS Avahi(but I also tried Bonjour).

**Comment by maverick85** [comment]
I'm having the same issue.

RockyLinux 9 - SELinux permissive (no hits)
firewalld: initially allowed mdns and stuff works except adding but added port range 1024-65535 tcp/udp in the meanwhile without luck
added tuya integration, can connect see accessories etc but also can't add the child-bridge gives the same error.

the install was made yesterday i've tried everything I could find.

node.js: v16.16.0

**Comment by maverick85** [comment]
Alright found a fix in my case. In between checking all possible and imaginable settings, I noticed firewalld had forward enabled:
```
# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp0s3
  sources: 
  services: cockpit dhcpv6-client homebridge mdns ssh
  ports: 8581/tcp 51842/tcp 57090/tcp
  protocols: 
  forward: yes
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```

the homebridge service is the one I created opening ports 1024-65535.
So anyway I was thinking "why in the world is that `forward: yes` setting? Checked a couple of older distros, has it disabled by default. Checked a couple newer distros (EL9) comes enabled by default. Have no idea why and I have other servers where this didn't cause any issue. After disabling it with `firewall-cmd --remove-forward` stuff just started working. If anyone is having the same issue, please check this setting. If testing with the above command fixes for you, you can make it permanent with either: `firewall-cmd --permanent --remove-forward` or `firewall-cmd --runtime-to-permanent`.

**Comment by jpae** [comment]
I ran into this myself and was able to solve it by adding a firewall rule for the homebridge. If you go to the homebridge UI, you'll see that the UI might be running in 8581, but the bridge port is something else. Add that to your firewall rules and see if that helps

**Comment by konung** [comment]
2 things solved it for me:

1. I have a fairly complex segmented network (adults, kids, iot, servers, etc) all running on different subnets, with some filtering/firewalling between segments
   1.  NAS & With Docker/Homebridge were not on the same network, and even after I opened some ports, iPhone couldn't find homebridge. 
   2. My NAS has another LAN interface I wasn't using, so I set it up on the same LAN as my iPhone. 
   
2. Changing mDNS protocol in settings as suggested above  here to Avahi

Hope it helps

   
<img width="1199" alt="Screenshot 2023-01-27 at 15 27 40" src="https://user-images.githubusercontent.com/72493/215203902-50eaa014-7f87-49e5-8720-bee4531cc906.png">

**Comment by ALogicianKenny** [comment]
I also had a problem that Homebridge built on QNAP could not be added to Home app, but it was solved.

My iPhone was connected to Wi-Fi but the NAS was not.
I think this is probably the cause of the problem many people are having.
I had the NAS wired to a router, but "by wired directly to the 『Wi-Fi router(not the router I mentioned earlier )』 and changing the mDNS" I was able to add Homebridge to the Home app.

This applies not only to NAS but also to Apple TV with a wired connection.

**Comment by maverick85** [comment]
> I also had a problem that Homebridge built on QNAP could not be added to Home app, but it was solved.
> 
> My iPhone was connected to Wi-Fi but the NAS was not. I think this is probably the cause of the problem many people are having. I had the NAS wired to a router, but "by wired directly to the 『Wi-Fi router(not the router I mentioned earlier )』 and changing the mDNS" I was able to add Homebridge to the Home app.
> 
> This applies not only to NAS but also to Apple TV with a wired connection.

1. This is not valid for all users
2. Yes Home App and HomeKit require mDNS to work properly.
3. This is not about if something is wired or not wired, but how your network is configured. Anyone can have wifi and wired devices in the exact same subnet.
4. Many users end up having separate networks for LAN and IOT.

In such situations it is needed to make the mDNS messages to travel between subnets. For that there is [`avahi`](https://avahi.org) which is a zeroconf facilitator by allowing mDNS messages to be passed between selected subnets.
