### ISSUE TITLE
Question: Does homebridge API allow accessory to push state changes to Home hub?

### ISSUE THREAD

**Issue by newt10** [homebridge/homebridge#2746]
I am trying to build a plugin where I have to update the state of accessory on the accessory (without controller input - like temperature or switch state). I want to notify the home hub of this updated state or that characteristic so that the home hub and the app UI changes. 
Based on [reading the documentation I tried using service.updateCharacteristic() ](https://developers.homebridge.io/#/api/service#serviceupdatecharacteristic)to accomplish this but the UI changes are not being published (at least it appears like this). I need to close the Home app or send it to background and then open it again to get the refreshed state of the accessory.

I would appreciate help with the API in order to resolve this. Thanks for the help. I wasn't able to find the right place to post this so I started here. Please let me know if there is a better place for this discussion.

Also FYI, github has introduced a new discussions section for such conversations. It might be great to enable it so that such conversations aren't cluttering the issues tab.

**Comment by NorthernMan54** [comment]
@newt10 We have a discord server for development discussions, and a bunch of us are around to answer questions about coding.  Link to the server is here

https://github.com/homebridge/homebridge#community

The behaviour you are expecting with Real Time state change pushes to the Home App is a supported behaviour and the updateCharateristics method is the proper approach.  Not sure why this isn't working in your code.

**Comment by Supereg** [comment]
@newt10 as you already discovered updateCharacteristic is the way to go.

Some background to this:
Those so called „HomeKit Event Notifications“ are only supported for characteristics which have the NOTIFY permissions set (which are most of the user facing characteristics). Additionally every HomeKit controller has to explicitly subscribe to receive event notifications for a certain characteristic (which iOS does automatically when opening the Home App; Home Hubs will also do this automatically if the characteristic is part of a automation trigger).
Lastly, homebrige will only send such event notifications if the value actually changed. 

In any case our discord is a great place to discuss and share code as @NorthernMan54 pointed out.

**Comment by newt10** [comment]
Thanks @Supereg , @NorthernMan54. I will checkout the discord server and move the conversation there.

**Comment by newt10** [comment]
I have 3 accessories in my plugin that are essentially a single device (fan + heater + switch). I have set them up as different accessories for better UX. When one accessory is turned on I want to turn off the state of the other accessory and reflect that in the UI. What I discovered is that fan and heater UI updates nearly instantaneously with the updateCharacteristic method while the switch UI does not. Any thoughts on why this might be the case?

**Comment by newt10** [comment]
Also do you have suggestion on which channel to use in discord for these conversations?

**Comment by NorthernMan54** [comment]
#plugin-development

**Comment by newt10** [comment]
Closing this and moving the conversation to discord
