### ISSUE TITLE
Verified plugin is not following rules of verification

### ISSUE THREAD

**Issue by kremik** [homebridge/homebridge#2747]
Latest update of ewelink plugin (HomeBridge verified) requires Node.js 14 only, but it is breaking Homebridge Verified plugin rules which state:
"The plugin must run on all supported LTS versions of Node.js, at the time of writing this is Node.js v10, v12 and v14."

**Comment by oznu** [comment]
According to the plugin developer it still works with Node 10 which is all that is required. They are allowed to recommend the current LTS (while still working with all Active LTS).

https://github.com/bwp91/homebridge-ewelink/issues/162

**Comment by kremik** [comment]
I found the core of the problem - which is simple - there is a mistake in Czech version of the compatibility message - it states that the Node.js 14 is REQUIRED to run the plugin. Not recommended as it states in English.
