### ISSUE TITLE
Installed 1.2.3 ... how to come to 1.2.4 (1.1.6 is latest)

### ISSUE THREAD

**Issue by roe1974** [homebridge/homebridge#2748]
Hi 
I actually have installed 1.2.3 .....
a "sudo npm outdated -g" brings me:

Current      Wanted     Latest
homebridge               1.2.3                    1.2.4                    1.1.6

a "sudo npm install -g --unsafe-perm homebridge" will bring my installation to 1.1.6 ... not ?
should i do a "sudo npm install -g --unsafe-perm homebridge@1.2.4" ????

thx for Info

Richard

**Comment by Bouke** [comment]
See also #2696.

**Comment by Supereg** [comment]
Short answer: `sudo npm install -g --unsafe-perm homebridge@1.2.4` is the way to go if you want to install 1.2.4
