### ISSUE TITLE
Force sync homebridge/domoticz

### ISSUE THREAD

**Issue by vespino** [homebridge/homebridge#2751]
Is it possible to force the sync between homebridge and domoticz? I’m asking because domoticz turns off devices at certain times, but if I ask Google to turn one of those devices on shortly after domoticz has turned it off (tested up to 25 minutes) Google still registers it as “on” and thus doesn’t turn it on again. I was hoping to force a think sooners so this doesn’t happen.

When I manually toggle a device in Domoticz and immediately afterwards go to Google Home, it shows to old state and I have to refresh to have it show the current state.

Maybe I’m asking the wrong thing because homebridge does sync within minutes, but since Google Home is linked to homebridge...

**Comment by oznu** [comment]
Hi @vespino,

There is nothing in Homebridge that would stop this from happening; however you will need to raise this with the author of the domoticz plugin you are using.
