### ISSUE TITLE
1.2.4 or 1.1.7 ... which one ist the latest ?!?!? (confused)

### ISSUE THREAD

**Issue by roe1974** [homebridge/homebridge#2752]
Hi
I am a little bid confused ..... a few days before there was 1.2.4 the latest.
Now we have a 1.1.7 as latest ....
Which one should i use ? (actually 1.2.4 installed)
thx, Richard

**Comment by macjeff** [comment]
> Hi
> I am a little bid confused ..... a few days before there was 1.2.4 the latest.
> Now we have a 1.1.7 as latest ....
> Which one should i use ? (actualls 1.2.4 installed)
> thx, Richard

I was wondering the same thing.  I remember reading about some issues with the 1.2.x series with streaming and they told some to go back.  Also they are working on 1.3.0 beta.   So I figure if you are on 1.2.x series and things are working then leave it alone but if you are on 1.1.x servers and cant go to 1.2.4 then you now have 1.1.7.  But I am not the pro here so I too would like that from the author LOL

**Comment by Apollon77** [comment]
1.1.x is latest, 1.2.x is beta ... see npmjs ob "versions" tab

**Comment by A-vesalius** [comment]
1.  So,1.1.7 is the latest stable.
2. 1.2.4 is an isolated update release. 1.2.x was put out as stable, but later retracted as it caused issues for some, but not all. Some people stuck with this release because it worked well for them.
3. 1.3.x is the current beta release

**Comment by roe1974** [comment]
so can i just update from 1.2.4 to 1.1.7 ?

**Comment by A-vesalius** [comment]
Sure, you can do the same with cli, but homebridge config ui makes rolling back to 1.1.7 stable from either 1.2.x or 1.3.x beta easy. Later you can move back to the 1.2.x or 1.3.x versions if they offer something you need just as easily. 

[https://user-images.githubusercontent.com/3979615/96521915-15936700-12be-11eb-9826-f19b201d20db.gif](url)

**Comment by Supereg** [comment]
Similar to #2696
