### ISSUE TITLE
How can i reset wifi setting on my raspberry pi homebridge ?

### ISSUE THREAD

**Issue by newpoliceman** [homebridge/homebridge#2759]
**Describe Your Problem:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by milo526** [comment]
Hey!

There is a great page regarding exactly this topic on the homebridge raspbian image wiki.

Please find this page [here](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Reset-WiFi).
https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Reset-WiFi

Those steps should be able to help you solve this problem!

**Comment by newpoliceman** [comment]
> Hey!
> 
> There is a great page regarding exactly this topic on the homebridge raspbian image wiki.
> 
> Please find this page [here](https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Reset-WiFi).
> https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Reset-WiFi
> 
> Those steps should be able to help you solve this problem!

It is exactly what I am looking for. Thank you so much.
