### ISSUE TITLE
Devices going back to default room and disappearing

### ISSUE THREAD

**Issue by mareeekkkk** [homebridge/homebridge#2760]
Hi!
A few days ago all lights defaulted back to the default room. After a few seconds, they disappear. For accessorys i use Hue Lights exposed by homebridge-hue. Other accessories are Samsung Tizen, Unifi Protect Camera, Xbox etc. 
When i restart the homebridge server, the lights reappear and after 5-10 seconds they are gone again.

Its similar to #2753 

I did a clean install of homebridge with LTS version of Homebridge, homebridge-plugins and node / npm. Still no change, same problem occurs. The lights come back after a homebridge restart and then disappear after a few seconds.

Switched to Homebridge 1.3.0-beta.33. Still no change, same behaviour.

Any ideas on what is causing the devices to disappear?

**Comment by pezking7p** [comment]
I had a similar issue with my MyQ garage door yesterday.  Running 1.1.7 on a RPi 3.  

I had just added the garage door, I moved it to a new room and the device would disappear.  If I restarted Homebridge the device would re-appear in the old room.  However, in my case, as long as I didn't try to change the device to a new room it would work perfectly.  

I went through this cycle three times and it finally accepted the new room.  No issues since then with the device disappearing.

**Comment by eldrix-4** [comment]
I’ve also been having this issue recently. It’s happened 3 times now, and I have a lot of devices so moving them all back takes time. Running 1.1.7 on RPi3. Happy to provide appropriate logs if it helps someone troubleshoot.

**Comment by JeremyLaurenson** [comment]
My automations also break, so this amounts to basically setting up 80% each time.

**Comment by NorthernMan54** [comment]
This is typically triggered by plugins and device's being added or removed.  Have you raised issues with the plugin's themselves ?  Also if you split your configuration into multiple Homebridge instances and move the problematic plugin into it's own instance then the issue will be reduced.

**Comment by eldrix-4** [comment]
I've not tried splitting across bridges yet, and I also don't think this is related to plugins. I've had devices all move back to a default room when no other changes have been made. But I do have a theory it's going to take some time to prove or disprove. I have an old iPad on a wall that's old enough it can't run latest iOS, and it was set as an available hub. Perhaps having different iOS devices with different versions was messing with the config. I've disabled it as a hub and will see it the behavior happens again or not.

**Comment by mareeekkkk** [comment]
@eldrix-4 try removing your old iPad. I had a old iPad mini 1 as a wall display, displaying some homekit information. As I had the issues with devices disappearing going for too long, I rebuild my whole setup leaving out the old outdated iPad... this solved my issue.

**Comment by ebaauw** [comment]
Disabling the old iPad (or rather: the iPad running on an old iOS version) as hub won't be enough.  You need to remove it from your iCloud account, or at least disallow Home to use your iCloud account.

I think Apple made some serious improvements to the iCloud sync between HomeKit runtimes on your various devices, but in doing so introduced some incompatibilities with older iOS versions.  Even with only iOS 14, I'm seeing some sync issues when a lot of changes happen at once, e.g. during Homebridge ZP startup, changes to the _TV_ inputs are sometimes undone.  All I can say is: "HomeKit really doesn't like configuration changes."

**Comment by eldrix-4** [comment]
I removed the old iPad from my setup and not had a recurrence yet. Fingers crossed.

**Comment by edmarts** [comment]
I had the same issue with my homebridge for about 10 days ago until now. All of my devices appear normally on web browser but when accessing the Home app on iPhone, many devices disappeared.

Some ewlink sensors/devices are missing, others are not.... all the led strips are missing too.

When i restart the homebridge, they appear in the Home app .. but after a few minutes they disappear again.

**Comment by mareeekkkk** [comment]
Do you have any old iOS device connected with your iCloud account? 
It does not need to have HomeKit configured, as long as an old iOS device is accessing your iCloud account it will mess up your HomeKit configuration.

Try turning off older devices (iPads, iPhones etc.)

**Comment by JeremyLaurenson** [comment]
I can confirm this issue is fixed. Please close

**Comment by JackyX2k** [comment]
Am on IOS 16.2 and this same issue exists now! Devices disappeared and reappeared in "Default Room" is there a fix for this? I also can't share home with anyone!?

**Comment by drakkhen** [comment]
I just started experiencing this out of the blue recently, too (maybe from the recent iOS/audioOS updates and/or me migrating to the new/currently-unavailable HomeKit architecture upgrade?).  A few dozen Homebridge devices keep going back to Default Room and I lost automations for those devices.

**Comment by mdeuerlein** [comment]
I had the same Issue but found the following solutions respectively work arounds:

### 1. "Apple Home" on MacOs
In most cases the device can be moved inside the  "Home" App for macOS 
which will also move the device inside  "Apple Home" on iPhone/iPad.

_or_

### 2. "Eve for Matter & HomeKit" on iOs
Just use the free Homekit App from Eve on your iPhone to manage all your devices.
https://apps.apple.com/de/app/eve-f%C3%BCr-matter-homekit/id917695792

It's far more convenient than Apple's "Home", supports all types of HomeKit devices 
(even from manufacturers other than Eve) and so far all general device settings have 
been adopted and show up in Apple's "Home" without any problems


.
