### ISSUE TITLE
Thermostat does support, low battery and tampered state (remove warning and update doku)

### ISSUE THREAD

**Issue by Feilner** [homebridge/homebridge#2768]
**Describe The Bug:**
The service `Thermostat` (0000004A-0000-1000-8000-0026BB765291) does actually support the characteristics `Status Low Battery` (00000079-0000-1000-8000-0026BB765291) and `Status Tampered` (0000007A-0000-1000-8000-0026BB765291)

According to the documentation the service [thermostat](https://developers.homebridge.io/#/service/Thermostat) it does not support `Status Low Battery` or `Status Tampered` thus when the plugin registers it any way there will be a HAP Warning.
The Service Temperature Sensor does support them also according to the documentation.

But at least iOS 14.3 does support these characteristics for the service thermostat see screenshots. (Sorry for the German screenshots).
`Batterie fast leer` means `Low battery`
`Status: Manipuliert` means `Status: Tampered`

**Expected behavior:**
- update documentation
- remove warning

[**Logs:**]()
```
HAP Warning: Characteristic 0000007A-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 00000079-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000004A-0000-1000-8000-0026BB765291. Adding anyway.
```

**Screenshots:**

![IMG_9859](https://user-images.githubusercontent.com/6040107/103583908-e1a10880-4ee0-11eb-996a-2a9fcdf5eb11.PNG)
![IMG_9860](https://user-images.githubusercontent.com/6040107/103583910-e2d23580-4ee0-11eb-85eb-772cc40155cd.PNG)

**Comment by Supereg** [comment]
Even if its supported by the Home App, the spec doesn't list it explicitly as an optional characteristic.
The default configuration of HAP-NodeJS tries to mirror exactly that, the services as defined by the specification.

Just use `addCharacteristic` to explicitly add the Characteristic to the desired service on creation. This will silence the warning when calling `getCharacteristic`.
