### ISSUE TITLE
Custom Logging level

### ISSUE THREAD

**Issue by martin072** [homebridge/homebridge#2770]
**Describe Your Problem:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.14.0
* **NPM Version**: 6.14.8
* **Homebridge Version**:1.1.7
* **Operating System**: Raspbian /
* **Process Supervisor**: Systemd / hb-service / 

I've installed the Free@home plugin for Homebridge, and this will generate Update messages almost every 10 sec. Needles to say on a raspberry with an SSD card I would like to minimise logging as much as possible unless told otherwise (i.e for debugging).

Would there be anyway to reduce the amount of logging with homebridge? or maybe even to set the level of logging?

**Comment by Supereg** [comment]
Currently there is no such feature, but maybe its worth investigating if we should add such a feature.
However probably is worth talking to the plugin author directly to reduce his logging done on `INFO` level. In any case the plugin should properly define its logging levels.

**Comment by AndersKlinting** [comment]
I would like to second this suggestion, thinking it would be good to have control at homebridge level of the level of lpgs rather than having to involve all the plugin developers

**Comment by justme-1968** [comment]
yes. adding a per plugin log level option is the better way to do this. doing it in one central place would be more consistent and apply to all plugins out of the box.

**Comment by kennymc-c** [comment]
Any news on this @Supereg ?
