### ISSUE TITLE
AccessoryPlugin interface is missing name property

### ISSUE THREAD

**Issue by Patrick-Remy** [homebridge/homebridge#2771]
**Describe The Bug:**
TypeScript interface [AccessoryPlugin](https://github.com/homebridge/homebridge/blob/master/src/api.ts#L51-L81) is missing the required `name` property. This property is accessed on [platform creation](https://github.com/homebridge/homebridge/blob/master/src/server.ts#L426) and suppressed with `@ts-ignore`. In the examples it is marked as [private here](https://github.com/homebridge/homebridge-examples/blob/master/accessory-example-typescript/src/accessory.ts#L49), it must be public there either. Another example just places a comment that this property [must exist](https://github.com/homebridge/homebridge-examples/blob/master/static-platform-example-typescript/src/switch-accessory.ts#L18-L19).

I tried to develop a `StaticPlatformPlugin` but failed with the exception `Accessories must be created with a non-empty displayName` and  `Initializing platform accessory 'undefined'...`. After adding the property, everything worked well.

Same for the optional property [`uuid_base`](https://github.com/homebridge/homebridge/blob/master/src/server.ts#L429).

**Expected behavior:**
TypeScript hints for the missing required property `name`.

**Logs:**
```
Jan 06 22:08:13 pi-server homebridge[21128]: [2021-1-6 22:08:13] Initializing platform accessory 'undefined'...
Jan 06 22:08:13 pi-server homebridge[21128]: [2021-1-6 22:08:13] [Artnet Universe] Create lightbulb service
Jan 06 22:08:13 pi-server homebridge[21128]: [2021-1-6 22:08:13] Failed to find plugin to handle accessory Spot 1
Jan 06 22:08:13 pi-server homebridge[21128]: [2021-1-6 22:08:13] Removing orphaned accessory Spot 1
Jan 06 22:08:13 pi-server homebridge[21128]: [2021-1-6 22:08:13] Error: Accessories must be created with a non-empty displayName.
Jan 06 22:08:13 pi-server homebridge[21128]:     at new Accessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:232:29)
Jan 06 22:08:13 pi-server homebridge[21128]:     at Server.createHAPAccessory (/usr/lib/node_modules/homebridge/src/server.ts:463:25)
Jan 06 22:08:13 pi-server homebridge[21128]:     at /usr/lib/node_modules/homebridge/src/server.ts:427:34
Jan 06 22:08:13 pi-server homebridge[21128]:     at Array.forEach (<anonymous>)
Jan 06 22:08:13 pi-server homebridge[21128]:     at /usr/lib/node_modules/homebridge/src/server.ts:417:21
Jan 06 22:08:13 pi-server homebridge[21128]:     at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
Jan 06 22:08:13 pi-server homebridge[21128]:     at ArtNetHomebridgePlatform.accessories (/usr/lib/node_modules/homebridge-artnet2/src/platform/artnet.platform.ts:45:5)
Jan 06 22:08:13 pi-server homebridge[21128]:     at /usr/lib/node_modules/homebridge/src/server.ts:415:24
Jan 06 22:08:13 pi-server homebridge[21128]:     at new Promise (<anonymous>)
Jan 06 22:08:13 pi-server homebridge[21128]:     at Server.loadPlatformAccessories (/usr/lib/node_modules/homebridge/src/server.ts:414:12)
```

**Environment:**

* **Node.js Version**: 12.20.0
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.2.3
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd

**Comment by Patrick-Remy** [comment]
Why is the issue closed, even if there is an open PR? Please check your stale config and reopen this.

**Comment by grillomuto** [comment]
Hi, can someone help me with the Xiaomi / Aqara QBKG24LM switch https://bit.ly/3vslrgg: This is the Json configuration I am using, it works perfectly but both relays turn on, I can't get them to work separately ... . Thank you   :      {
            "accessory": "mqttthing",
            "type": "switch",
            "name": "Valvola",
            "url": "http://192.168.1.17:1883/",
            "username": "xxxxxxxxxxx",
            "password": "xxxxxxxxxxx",
            "integerValue": "true",
            "topics": {
                "getOn": {
                    "topic": "tele/Nodotubo/SENSOR",
                    "apply": "return JSON.parse(message).ZbReceived['0xFACE'].Power;"
                },
                "setOn": {
                    "topic": "cmnd/Nodotubo/ZbSend",
                    "apply": "return '{\"Device\":\"0xFACE\", \"Endpoint\":\"0x01\", \"send\":{\"Power\":' + message + '}}'"
                }
            }
        }

**Comment by bwp91** [comment]
@Patrick-Remy did this issue ever come to some resolution?
