### ISSUE TITLE
Migrating from old way to hb-service

### ISSUE THREAD

**Issue by bwoodruff** [homebridge/homebridge#2778]
**Describe Your Problem:**

I have homebridge installed on an Ubuntu VM running on ESX. I set it up many moons ago before Homebridge UI or hb-service were a thing. I would like to migrate my existing setup to hb-service so I gain the benefits associated.

Some notes:

* My config lives at /var/homebridge/config.json so I don't think the instructions posted [here](https://github.com/homebridge/homebridge/issues/2721#issuecomment-729258981) work out of the box?
* I do have Homebridge UI installed and have made a backup using it
* I have used hb-service to update node (`v14.15.4`)
* Homebridge itself and all plugins are up to date as confirmed by Homebridge UI
* I currently run one large homebridge instance with 6 plugins installed. This has caused problems in the past where one plugin malfunctions and takes the whole system down ([details](https://github.com/homebridge/homebridge/issues/2339)). While I'm making these changes would it be possible / advisable to split this out into multiple homebridge instances? If so, can I do so without having to completely re-do my HomeKit config, automations, etc?

**Environment:**

* **Node.js Version**: 14.15.4
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.1.7
* **Operating System**: Ubuntu 20.04.1 LTS (dedicated VM, does nothing other than homebridge)
* **Process Supervisor**: init.d I believe. The restart command in Homebridge UI is set to `sudo service homebridge restart`

**Comment by A-vesalius** [comment]
Backing up and saving the working config from your current install. Then creating a new minimal ubuntu/Debian vm and doing a current Hb service based install followed by a restore from the just saved backup has worked for me transparently. Uses the prior homekit pin and name. All the plugins and accessory reinstall and work with homekit as set up previously. 

I have used this to move from a proxmox ubuntu vm to a Debian Lxc and just recently to an alpine Linux docker homebridge container and all my homebridge accessories continued for work in homekit, including those built into homekit automations and scenes, without a hiccup. To homekit it seemed no diff than a restart of the homebridge instance.

**Comment by donavanbecker** [comment]
> Backing up and saving the working config from your current install. Then creating a new minimal ubuntu/Debian vm and doing a current Hb service based install followed by a restore from the just saved backup has worked for me transparently. Uses the prior homekit pin and name. All the plugins and accessory reinstall and work with homekit as set up previously. 
> 
> 
> 
> I have used this to move from a proxmox ubuntu vm to a Debian Lxc and just recently to an alpine Linux docker homebridge container and all my homebridge accessories continued for work in homekit, including those built into homekit automations and scenes, without a hiccup. To homekit it seemed no diff than a restart of the homebridge instance.

You can make a backup of all of homebridge and then restore. Then you don't have to setup HomeKit automation again.

**Comment by oznu** [comment]
### Backup

Make a backup as per: https://github.com/homebridge/homebridge/wiki/Backup-and-Restore

### Remove Existing Homebridge Service

The Homebridge service what makes Homebridge automatically start on boot. As part of this change we will change your process supervisor to use `hb-service` which is backed by `systemd`. To do this you will need to remove your existing Homebridge service.

There are several tools you might be using to run Homebridge as a service:

* `systemd` / `systemctl`
* `init.d`
* `pm2`

If you are using `systemd` you can run these commands to remove the service (adjust for your Homebridge service name):

```
sudo systemctl stop homebridge
sudo systemctl disable homebridge
sudo rm -rf /etc/systemd/system/homebridge.service
sudo systemctl daemon-reload
```

If you are running Homebridge with `init.d` you can use these commands to remove the service:

```
sudo service homebridge stop
sudo update-rc.d homebridge remove
rm -rf /etc/init.d/homebridge
```

If you are running Homebridge with `pm2` you can use these commands to remove the service:

```
sudo pm2 stop all
sudo pm2 delete all
```

### Copy Homebridge Config To `/var/lib/homebridge`

If your Homebridge storage folder is not already set to `/var/lib/homebridge`, you will need to move it to this location to avoid loosing any Homebridge settings.

```bash
sudo mkdir -p /var/lib
sudo cp -R /var/homebridge /var/lib/homebridge
```

### Follow the Wiki Install Guide

You can now safely follow the wiki install guides that explain how setup Homebridge as a service again. If you have correctly moved your config to `/var/lib/homebridge` then you won't loose any existing settings (you made a backup at the start just in case).

* [Install Homebridge on Debian or Ubuntu Linux](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux)

**Comment by bwoodruff** [comment]
Thank you! I was able to get this completed today and everything appears to be working. 🙏
