### ISSUE TITLE
Homebridge installation Guide Ubuntu/NTP

### ISSUE THREAD

**Issue by casperse** [homebridge/homebridge#2780]
Hi All
I followed the guide to install Homebridge to Ubuntu from the Homebridge webpage:
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux#prerequisites

But one problem remain, the Homebridge "TIME" is not insynch with the Ubuntu server?
I did a SSH and a data and the time is correct, the time on the Homebridge logs are around 5 min behind the actual time
Seems a reboot fixes this! But is there anyway to let Homebridge synch time to the Ubuntu server? 

I have googled this but the problem I could find was wrong server time, and thats not the case here!

**Describe Your Problem:**
How can I sync Homebridge with the Ubuntu time?

**Screenshots:**

**Environment:**
![image](https://user-images.githubusercontent.com/2026859/105017815-87598900-5a44-11eb-901e-3ec78cc6e0ee.png)

**Comment by oznu** [comment]
Test what Node says:

```
node -e 'console.log(new Date().toLocaleString())';
```

We don't do anything fancy with the timestamps.

**Comment by casperse** [comment]
OK just strange that I was missing 5 min and I got a "alarm" in the log on the homebridge about a miss match of the time?
![Uploading image.png…]()
I have not done any special setup after following the installation instruction

**Comment by casperse** [comment]
![image](https://user-images.githubusercontent.com/2026859/105059782-ed133880-5a77-11eb-9ae9-510ff4bb03e5.png)

**Comment by casperse** [comment]
This is so strange - standard installation following the guide I keep getting this...but not on HOOBS - But I really want to stay on Homebridge better UI and plugin works 1 time
![image](https://user-images.githubusercontent.com/2026859/105640788-2b499700-5e80-11eb-9237-2488711ae4ae.png)

**Comment by casperse** [comment]
Something is not "standard" any command I need to run on Ubuntu so I don't keep getting above pop-up in Homebridge?
