### ISSUE TITLE
Unable to add Homebridge to Home App

### ISSUE THREAD

**Issue by petromaniantz** [homebridge/homebridge#2781]
**Describe Your Problem:**

I'm not able to add my Homebridge bridge to the Home app. I've checked the FAQs and troubleshooting but that hasn't resolved my issue.

I've configured the Homebridge and plugin and confirmed that the accessory works as expected (turns on and off). Homebridge is running on a Pi V3, connected via ethernet. I'm attempting to add to the Home app on the same network (via wifi) but not able to do so. Any help is greatly appreciated.

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here

{
    "mdns": {
        "interface": "192.168.1.158" <NOTE> I added the mdns line based on some tips from other posts. Not sure if it's helping.
    },
    "bridge": {
        "name": "Homebridge 4D41",
        "username": "0E:1A:E3:5A:4D:41",
        "port": 51184,
        "pin": "860-39-455"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "REDACTED",
                "password": "ALSO_REDACTED",
                "countryCode": "1",
                "platform": "tuya"
            },
            "defaults": [
                {
                    "id": "17882087f4cfa2c9315d",
                    "device_type": "light"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        }
    ]
}

```

**Screenshots:**

**Environment:**

* **Node.js Version**:  v14.15.4
* **NPM Version**:  v6.14.10
* **Homebridge Version**: 1.17
* **Operating System**: Raspbian
* **Process Supervisor**: none

**Comment by allcoast** [comment]
Same issue

**Comment by Sergbmw** [comment]
Same issue

**Comment by danparsons** [comment]
Same issue

**Comment by n1zzo** [comment]
I have the same issue when running on ArchLinux ARM + Docker, the issue is not there on Raspberry Pi 2 + ArchLinux ARM.
Following [this issue](https://github.com/homebridge/homebridge/issues/1957) i ran `tcpdump` on my OpenWRT router:

```
$tcpdump -n udp dst port 5353 -i eth0
19:51:30.467321 IP <rock64ip>.5353 > 224.0.0.251.5353: 0*- [0q] 1/0/8 PTR Homebridge 1577 457C._hap._tcp.local. (397)
```
So it appears that mDNS is working. The Home app on my iPhone correctly detects the homebridge but then after a long wait fails to add it. Here's a screenshot of the error.

![photo_2021-02-03_21-21-18](https://user-images.githubusercontent.com/6890834/106804516-c6532580-6665-11eb-86c9-697121fa3d6e.jpg)

I can run further tests to solve this issue.

**Comment by danparsons** [comment]
> I have the same issue when running on ArchLinux ARM + Docker, the issue is not there on Raspberry Pi 2 + ArchLinux ARM.
> Following [this issue](https://github.com/homebridge/homebridge/issues/1957) i ran `tcpdump` on my OpenWRT router:
> 
> ```
> $tcpdump -n udp dst port 5353 -i eth0
> 19:51:30.467321 IP <rock64ip>.5353 > 224.0.0.251.5353: 0*- [0q] 1/0/8 PTR Homebridge 1577 457C._hap._tcp.local. (397)
> ```
> 
> So it appears that mDNS is working. The Home app on my iPhone correctly detects the homebridge but then after a long wait fails to add it. Here's a screenshot of the error.
> 
> ![photo_2021-02-03_21-21-18](https://user-images.githubusercontent.com/6890834/106804516-c6532580-6665-11eb-86c9-697121fa3d6e.jpg)
> 
> I can run further tests to solve this issue.

I ran into a similar issue, also with Docker. I don't know why it was working before and then broke, but I had to add a line like the below to tell Homebridge what IP address it should tell clients to connect back to. Put a line like this above your "bridge" line in config.json:

> "mdns": {"interface": "192.168.0.24"},

Might work for you.

**Comment by n1zzo** [comment]
Unfortunately that did not fix the problem.
Since I have another working instance, I'll try to capture the Home app pairing on both instances and see where it breaks.

**Comment by JohnGalt1717** [comment]
Same problem. Thinking it may be mdns issues with Unifi Dream Machine Pro but not sure?

**Comment by n1zzo** [comment]
I dug this further, in my case it's no mDNS issue, basically the Homebridge server does not reply 200 to a pairing request issued by my iPhone.
Here are two wireshark captures of a successful pair (obtained on another device):
![image](https://user-images.githubusercontent.com/6890834/107143789-4663de80-6937-11eb-808d-19275fbc0724.png)
and a failed pair, which I'm trying to investigate:
![image](https://user-images.githubusercontent.com/6890834/107143799-51b70a00-6937-11eb-879b-21d010630c28.png)
This seems like a Homebridge bug, tell me if you have some ideas to try.

**Comment by n1zzo** [comment]
Traced the issue back to the HAP-NodeJS library:
```
  HAP-NodeJS:EventedHTTPServer New connection from client at interface eth0 +18s
  HAP-NodeJS:EventedHTTPServer HTTP server listening on port 44827 +2ms
  HAP-NodeJS:EventedHTTPServer HTTP connection error:  getaddrinfo EAI_AGAIN localhost +5s
  HAP-NodeJS:EventedHTTPServer HTTP connection was closed +1ms
  HAP-NodeJS:EventedHTTPServer HTTP server was closed +3ms
  HAP-NodeJS:EventedHTTPServer Client connection closed +3ms
  ```
For some reason the docker container is unable to resolve localhost, thus the pairing fails.
