### ISSUE TITLE
Feature Request: Elgato History Service as Part of Homebridge

### ISSUE THREAD

**Issue by patrickpreuss** [homebridge/homebridge#2784]
Hi 

would it be Possible to Integrate the Elgato History Service as Part of Homebridge eighter as PlugIn or part of the Base Package?

This would enable any Plugin / Service / Accessoire to Utilize the History Feature.

Configuration should be Possible on a global Level and as part of the Accessoire / Service. 

Thanks for comments.

**Comment by Supereg** [comment]
I don't think that we will automatically package the Eve History module as of right now.
The plugin developers are responsible for themselves to package and enable that feature.
