### ISSUE TITLE
-

### ISSUE THREAD

**Issue by adriancable** [homebridge/homebridge#2785]
<deleted while I get more information>

**Comment by Supereg** [comment]
Sorry didn't had time yet to respond.
Seen your Email about a potential problem solution? Why did you remove it again?

**Comment by adriancable** [comment]
Hi Andi – I ended up realizing that Github probably isn’t the right venue to have a conversation, simply because it probably is too early to be actionable for people with discovery issues and I’m sensitive to adding noise to the existing conversation – are you OK to email me and we can discuss 1:1 to start with?

-Adrian
