### ISSUE TITLE
mDNS advertising on 1.3.0 

### ISSUE THREAD

**Issue by MatthewGCampbell** [homebridge/homebridge#2787]
**Describe Your Problem:**
I’m trying to get homebridge to advertise its self for setup on multiple interfaces (vlans) I have no problem accessing its UI from the different networks and used the `bridge.bind` to set it up, just not sure how to setup its advertisement: 

```
{
    "bridge": {
        "bind": [
            "eth0",
            "eth0.332",
            "eth0.25"
        ],
```
But it just doesn’t seem to advertise its self when on any of the latest 1.3.0s. I utilized the MDNS feature:
```
{
    "bridge": {
        "mdns": {
            "interface": [
                "10.9.10.108",
                "10.1.15.106"
            ]
        }, 
```
on 1.2.5 previously which i don’t believe is compatible with 1.3.0. Could just be that i’m just missing the link to docs where i can figure out how to do something like this.

```json

{
    "bridge": {
        "bind": [
            "eth0",
            "eth0.332",
            "eth0.25"
        ],
        "name": "Homebridge CC7C",
        "username": "0E:B1:6A:C2:4A:7B",
        "port": 51411,
        "pin": "293-38-178"
    },
```
**Environment:**

* **Node.js Version**:  v14.15.4
* **NPM Version**: v6.14.10
* **Homebridge Version**: v1.3.0-experimental.14
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
The bind feature only effects the mDNS advertisements when running the Ciao mDNS advertiser I think.

To do this set `.mdns.legacyAdvertiser` to `false` (note that `mdns` is not inside the `bridge` object):

```json
{
    "bridge": {
        ...,
        "bind": [
            "eth0",
            "eth0.332",
            "eth0.25"
        ]
      },
    "mdns": {
        "legacyAdvertiser": false
    },
    ...
}
```

This can be done in the UI by toggling off the "Use Legacy mDNS Advertiser" switch:

![image](https://user-images.githubusercontent.com/3979615/106375842-d5c33c00-63e3-11eb-976a-f55a4724a094.png)

**Comment by MatthewGCampbell** [comment]
@oznu so the Legacy mDNS Advertiser had been off previously and i still was unable to find homebridge with the home app when on vlan 25.
