### ISSUE TITLE
Concerned about mDNS traffic

### ISSUE THREAD

**Issue by sddgit** [homebridge/homebridge#2788]
**Describe Your Problem:**
I started noticing excess battery drain on iPhones in the house. I read somewhere this can be due to mDNS traffic from Homekit, and to use IGMP snooping on the network. I'm not sure my router and mesh points (Ubiquiti Amplifi HDs) support this, or even if it would help if they did. But it did start me thinking and I cranked up Wireshark on my MacBook Pro. There does seem to be a lot of mDNS traffic from the Mac Mini running Homebridge. I've attached a Wireshark screenshot. The mDNS PTR records for Envoy-S (solar system), all the TV devices (harmony plugin) and the Homebridge record appear a lot - at least every 2 seconds, maybe more frequently. Does anyone have any idea why I'm seeing these records so often and what I can do about it? I presume every device on the network, including iPhones, would be receiving them and spinning their wheels.

[**Screenshots:**
<img width="1427" alt="Screen Shot 2021-01-31 at 3 45 25 pm" src="https://user-images.githubusercontent.com/76281052/106375189-30f23000-63de-11eb-8b76-c34bad853865.png">

**Environment:**

* **Node.js Version**: V14.15.3
* **NPM Version**: V6.14.10
* **Homebridge Version**: V1.1.7
* **Operating System**: macOS Big Sur
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
The upcoming version of Homebridge v1.3.0 has a new opt-in mDNS advertiser to address some issues with the on included in < v1.2, one of which was being to chatty.

You can try the beta and see if this addressss your concerns:

https://github.com/homebridge/homebridge/wiki/Homebridge-Beta-Testing

**Comment by sddgit** [comment]
Oh, thank you. That sounds promising. I won't be able to test for a couple of days, but I'll definitely give it a go.
