### ISSUE TITLE
Xiaomi Mi Smart Speaker Plugin for Homebridge ?

### ISSUE THREAD

**Issue by FredBoekwijt** [homebridge/homebridge#2789]
Hello,

I am looking to buy some Xiaomi products to use with homekit.

I have found lots of plugins already but i am currentlly searching for a way to connect the Xiaomi Mi Smart Speaker to homekit.
I have searched for a plugin to use but i could not find any.

Can anyone point me in the right location as i have a feeling i did not search correctly as this must be present.

**Comment by oznu** [comment]
You may have better success with plugin suggestions on Reddit / Discord.
