### ISSUE TITLE
Child bridge address already in use if…

### ISSUE THREAD

**Issue by grzegorz914** [homebridge/homebridge#2790]
Hello,

the Child bridge is very nice and working fast and responsible but if we use in our config.json fixed range of ports for accessory and platforms then the bridge does not start and reports “addares already in use”

  ```
  "ports": {
        "start": 9101,
        "end": 9150,
        "comment": "In this section set the port for Homebridge accessories."
    },
```
![D178CE4B-0E2F-4BE4-9501-AF1AAE5F7F65](https://user-images.githubusercontent.com/28867813/106578537-e4bf0100-653f-11eb-951d-ccf9495623ab.png)

**Comment by oznu** [comment]
I did think about this while developing the feature.. then thought who would run an external accessory in a child bridge as it's just going to create an unnecessary duplicate bridge.

I'll have to think about how to fix this - but we'll get it done before the release.

**Comment by grzegorz914** [comment]
Hmm,

if remove the section with fixed port all working as excepted.

I have run all my external accessory wit this Child bridge and all working correct, no need it add again in HomeKit are automatically added with old settings from cashe,
This mode get me the nice feature to restart only one platform not the whole homebridge and see the process of main screen.

**Comment by oznu** [comment]
We'll fix it.

I'll probably need to create some "allocated port manager service" to handle port requests from both the main bridge and the n number of child bridges.
