### ISSUE TITLE
Homebridge Still accessible in Browser when VPN connected. However Home App says accessory not responding

### ISSUE THREAD

**Issue by p2kdev** [homebridge/homebridge#2797]
Homebridge Still accessible in Browser when VPN connected. However Home App says accessory not responding.

**Describe Your Problem:**

I have HomeBridge setup on a Ubuntu machine and everything seems to be working well. However, when I turn on VPN on the Ubuntu machine (it's also my Media Server) for some downloading, the Home App says accessories not responding. However, if I go to the browser and punch my homebridge IP http://192.168.86.21:8581 , I am able to get to it without any issues.

Any help will be appreciated as I also have home assistant running on the same machine and my NEST thermostat works in the Home App when connected to VPN.

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**:  14.15.4
* **NPM Version**:  6.14.10
* **Homebridge Version**:  1.1.7
* **Operating System**: Ubuntu
* **Process Supervisor**: launchctl

**Comment by woodfairy** [comment]
You can't control HomeKit devices through VPN. More info: https://www.reddit.com/r/HomeKit/comments/7xov68/homekit_and_vpn/

btw nice to see someone from jailbreaking here 👍

**Comment by mrfatboy** [comment]
Use the mdns setting in the config file. Should fix the problem. My vpn is always on and I can always see my devices.

**Comment by p2kdev** [comment]
> Use the mdns setting in the config file. Should fix the problem. My vpn is always on and I can always see my devices.

@mrfatboy Thanks. I don't see this under config. Are you using Homebridge Beta?

**Comment by p2kdev** [comment]
> You can't control HomeKit devices through VPN. More info: https://www.reddit.com/r/HomeKit/comments/7xov68/homekit_and_vpn/
> 
> Only solution is to use either an Apple TV, HomePod (mini) or iPad running 24/7 at home as your HomeKit hub.
> 
> btw nice to see someone from jailbreaking here 👍

@woodfairy - I think you misunderstood me. I already have a apple tv as my homekit hub. The issue is that if I turn on VPN on the machine running homebridge, then the accessories are not accessible until I turn the VPN Off. But the same works fine with my accessories setup with Home Assistant. Jailbreaking if fun man & I plan to work on my tweaks in the future!

**Comment by mrfatboy** [comment]
I am using just standard version. I don’t think there is any docs on the setting. I found it by accident reading the “issues”. Google “Homebridge mdns” and it might come up. If not, I can show you the setting when I get home. 

This setting allowed me to control Homebridge when it behind a vpn when I was on my home network. 

I can control Homebridge behind a vpn when I’m outside my network also.

**Comment by p2kdev** [comment]
> I am using just standard version. I don’t think there is any docs on the setting. I found it by accident reading the “issues”. Google “Homebridge mdns” and it might come up. If not, I can show you the setting when I get home.
> 
> This setting allowed me to control Homebridge when it behind a vpn when I was on my home network.
> 
> I can control Homebridge behind a vpn when I’m outside my network also.

@mrfatboy I will appreciate if you could. Thanks

**Comment by mrfatboy** [comment]
Add the mdns key to you Homebridge config file. Insert the Ip of your homebridge computer.

{
    "mdns": {
        "interface": "xxx.xxx.xxx.xxx" <------ The Lan IP of your homebridge computer
    },
    "bridge": {
        "name": "Homebridge",
        "username": "xxxxxxxxxx",
        "port": xxxxxx
        "pin": "xxxxxxxxx"
    }
}

**Comment by oznu** [comment]
See https://github.com/homebridge/homebridge/wiki/mDNS-Options for instructions on assigning which interfaces Homebridge should use.
