### ISSUE TITLE
JSON syntax error in GUI with default config

### ISSUE THREAD

**Issue by woodfairy** [homebridge/homebridge#2798]
**Describe The Bug:**
When trying to save the default config through the web GUI, an error notification appears, telling me that the JSON has an invalid syntax even though it is the default config that comes with installiation. Any JSON validator tells me that this is valid JSON.
```json
{
    "bridge": {
        "name": "Homebridge REDACTED",
        "username": "AA:AA:AA:AA:AA:AA",
        "port": 51927,
        "pin": "111-11-111"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

**To Reproduce:**
1. Open Homebridge GUI
2. Open /config
3. Save

**Expected behavior:**
The GUI tells me that the config file could have been saved succesfully.

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge REDACTED",
        "username": "AA:AA:AA:AA:AA:AA",
        "port": 51927,
        "pin": "111-11-111"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

**Screenshots:**

<img width="912" alt="Bildschirmfoto 2021-02-07 um 14 02 32" src="https://user-images.githubusercontent.com/66573402/107147214-23442980-694d-11eb-982f-5163bf7b944b.png">

**Environment:**

* **Node.js Version**:  14.15.4
* **NPM Version**:  7.5.2
* **Homebridge Version**:  1.1.7
* **Operating System**: Raspbian 
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment]
What browser version?

**Comment by woodfairy** [comment]
latest Chrome stable

**Comment by oznu** [comment]
Version?

**Comment by oznu** [comment]
Cannot replicate on Version 88.0.4324.150 with fresh install.

![image](https://user-images.githubusercontent.com/3979615/107162722-43c9bd80-69f9-11eb-95b2-a7bc2d0d6543.png)

**Comment by woodfairy** [comment]
I use 88.0.4324.146 and it is not working. On Firefox, this does not happen.

**Comment by oznu** [comment]
This seems to be an isolated case as there have been no other reports of this occurring (with approx 30k users already running the latest UI) and I cannot replicate.
