### ISSUE TITLE
HomeBridge 1.25 cannot show negative Temperatures in Degrees Celsius

### ISSUE THREAD

**Issue by worf0r** [homebridge/homebridge#2799]
Hi Team,

HomeBridge 1.25 cannot show negative Tamperatues in Degrees Celsius. It's cold. So this is valid right now.
HomeKit shows "Device not answering" in this cases.

Plugins:
Blink
Davis

Same behavior for all Plugins which deliver negative tempreatures in degress Celsius. -9 right now :)

Thanks for Checking!

Marc.

**Comment by oznu** [comment]
Each plugin can override the default min and max values.

Pinging @Supereg to see if changing the defaults to allow for negative values in HAP-Node.js directly would "fix" this sort of problem?

https://developers.homebridge.io/#/characteristic/CurrentTemperature

**Comment by worf0r** [comment]
Next week we will have positive temperatures again, then it is fixed :)
But for me, this is something we need to fix somehow in the code.

In which file could I change the values?

**Comment by MirkoKas** [comment]
I‘m having the same issue with the TaHoma plugin by @dubocr and a temperature sensor there. I remember there was an issue with negative values that he fixed in the plugin sometime ago but with Homebridge 1.2.5 it’s back again. Don’t know with which version the problem occurred but sometime late last year everything worked even with negative temperatures outside. A fix would be greatly appreciated.

**Comment by oznu** [comment]
Try the beta:

https://github.com/homebridge/homebridge/wiki/Homebridge-Beta-Testing

It probably won't display negative values (other changes are required to make that happen), but will fallback to "zero" instead of showing "Device not answering".

**Comment by MirkoKas** [comment]
The beta indeed fixes the device not answering problem and shows temperature of 0 degrees. Thanks. This will work for my automations for now!
I find it interesting though that in a previous version of homebridge it definitely showed negative temperatures for the same sensor. This is something that @dubocr enabled in his plugin for this particular sensor. So is it possible that he can fix it again within in his plugin or is a fix in Homebridge needed first?

**Comment by worf0r** [comment]
Hi all,

Temperatures are positive again. So it is working again now. But this needs to be fixed. It will get winter again...

Thank you!

Marc

**Comment by NorthernMan54** [comment]
@worf0r have you raised an issue with the plugin itself?  The plugin developer needs to make a one line code change to resolve this.

**Comment by oznu** [comment]
@NorthernMan54 as this impacts all "CurrentTemperature" characteristics I think this should be changed in HAP-Node.js to be a range from say `-100` to `100`.

**Comment by worf0r** [comment]
I would say nearly all plugins have this problem. Therefore a solution in HAP-Node.js makes more sense for me. Temperatures can be negative, that's simply the truth.

**Comment by oznu** [comment]
The fix for this is currently in the Homebridge beta builds.

The minimum value has been set to absolute zero.
