### ISSUE TITLE
Node.js won't update

### ISSUE THREAD

**Issue by mvkpe** [homebridge/homebridge#2801]
**Describe Your Problem:**
My Debian OS will not update Node.js to newer than 10.23.1, it goes through the motions of downloading and installing it then reverts to 10.23.1 and states that 10.23.1 is the newest version. Even if I try and pick a version like 12.x for instance it does the same. I am using the command:  sudo hb-service update-node.

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 10.23.1
* **NPM Version**: 7.5.3
* **Homebridge Version**:1.1.7 
* **Operating System**: Debian 
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment]
It sounds like you have multiple instances of Node.js installed that are conflicting - or your haven't installed Node.js as per wiki instructions initially.

See https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux for instructions on how to purge all copies of Node.js and get ready for a fresh install.

**Comment by mvkpe** [comment]
I have just done all that and at the point of reloading node.js following the Debian install it loads 14.x and then reverts to 10.23.1 again and when I then go to the  "sudo npm install -g --unsafe-perm homebridge hombridge-config-ui-x" input it comes back with npm not installed.

**Comment by oznu** [comment]
Can you share the path of Node?

Show the output of BOTH these:

```
which node
```

```
sudo which node
```

**Comment by mvkpe** [comment]
pi@pi:~ $ which node
/usr/bin/node
pi@pi:~ $ sudo which node
/usr/bin/node
pi@pi:~ $

**Comment by oznu** [comment]
And then:

```
node -v
```

**Comment by mvkpe** [comment]
v10.23.1

**Comment by oznu** [comment]
Did you run the script in step 2 of this:

 https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux

**Comment by mvkpe** [comment]
I ran these:-
sudo systemctl stop homebridge
sudo systemctl disable homebridge
sudo rm -rf /etc/systemd/system/homebridge.service
sudo systemctl daemon-reload_

**Comment by mvkpe** [comment]
then I ran
sudo curl -fL https://git.io/JfFFM | sudo bash

**Comment by oznu** [comment]
Directly after running `sudo curl -fL https://git.io/JfFFM | sudo bash`

what is the output of 

```
which node
```

**Comment by mvkpe** [comment]
I will have to go through it all again to answer that

**Comment by mvkpe** [comment]
pi@pi:~ $ which node
pi@pi:~ $ sudo which node

**Comment by oznu** [comment]
Cool, so node.js is removed as it should have been.

Now follow the node.js install instructions from the install guide:

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux

Please provide the full output of the commands executed in step 1.

**Comment by mvkpe** [comment]
pi@pi:~ $ curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

## Installing the NodeSource Node.js 14.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://ftp.debian.org/debian buster InRelease                            
Get:3 http://ftp.debian.org/debian buster-updates InRelease [51.9 kB]          
Hit:4 http://security.debian.org buster/updates InRelease                      
Hit:5 http://packages.microsoft.com/repos/code stable InRelease                
Hit:6 https://deb.nodesource.com/node_14.x buster InRelease                    
Hit:7 https://linux.teamviewer.com/deb stable InRelease                        
Fetched 51.9 kB in 6s (9,216 B/s)                                             
Reading package lists... Done

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/buster/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js 14.x repo...

+ echo 'deb https://deb.nodesource.com/node_14.x buster main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_14.x buster main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://ftp.debian.org/debian buster InRelease
Hit:2 http://ftp.debian.org/debian buster-updates InRelease                    
Hit:3 http://security.debian.org buster/updates InRelease                      
Hit:4 http://archive.raspberrypi.org/debian buster InRelease                   
Hit:5 http://packages.microsoft.com/repos/code stable InRelease                
Hit:6 https://linux.teamviewer.com/deb stable InRelease                        
Hit:7 https://deb.nodesource.com/node_14.x buster InRelease                    
Reading package lists... Done                                   

## Run `sudo apt-get install -y nodejs` to install Node.js 14.x and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

**Comment by mvkpe** [comment]
pi@pi:~ $ sudo apt-get install -y nodejs gcc g++ make python net-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:8.3.0-1).
gcc is already the newest version (4:8.3.0-1).
make is already the newest version (4.2.1-1.2).
net-tools is already the newest version (1.60+git20180626.aebd88e-1).
python is already the newest version (2.7.16-1).
The following packages were automatically installed and are no longer required:
  gyp libjs-inherits libjs-is-typedarray libnode-dev libssl-dev libuv1-dev
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  npm
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 30 not upgraded.
Need to get 0 B/87.3 kB of archives.
After this operation, 161 kB of additional disk space will be used.
Selecting previously unselected package nodejs.
(Reading database ... 166944 files and directories currently installed.)
Preparing to unpack .../nodejs_10.23.1~dfsg-1~deb10u1_i386.deb ...
Unpacking nodejs (10.23.1~dfsg-1~deb10u1) ...
Setting up nodejs (10.23.1~dfsg-1~deb10u1) ...
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
Processing triggers for man-db (2.8.5-2) ...

**Comment by mvkpe** [comment]
node -v
v10.32.1

**Comment by oznu** [comment]
Have you added any other node repo sources?

**Comment by oznu** [comment]
check `/etc/apt/sources.list` and all the files in the `/etc/apt/sources.list.d/` folder.

**Comment by mvkpe** [comment]
I have only ever done the install as above, I only use this computer for Homebridge, as you can see the nom is a suggested package it has not been installed yet

**Comment by mvkpe** [comment]
pi@pi:~ $ /etc/apt/sources.list
bash: /etc/apt/sources.list: Permission denied

pi@pi:~ $ /etc/apt/sources.list.d/
bash: /etc/apt/sources.list.d/: Is a directory
pi@pi:~ $

**Comment by oznu** [comment]
Something is not right / normal as the nodesource package are not working as they should. This is beyond the scope of homebridge support.

I would suggest starting on a fresh copy of Debian / ubuntu.

**Comment by oznu** [comment]
You may want to make use of the backup / restore so you don't loose your setup:

https://github.com/homebridge/homebridge/wiki/Backup-and-Restore

**Comment by mvkpe** [comment]
This is a fresh copy, I installed it then did the home bridge install that's when home bridge stated that the Node.js needed to be updated and was showing 10.23.1, even then the npm wasn't installed with the node.js

**Comment by mvkpe** [comment]
It is working but I worry that when 10.23.1 is no longer supported it will all stop working.

**Comment by oznu** [comment]
v10 will have support dropped in April this year.

Debian Buster is supported by Nodesource so it should just work:

https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions

**Comment by mvkpe** [comment]
Is it something to do with running raspberryPi on Debian? Can I just run home bridge directly on Debian? without Raspberry installed?

**Comment by oznu** [comment]
Could be. Try Raspberry Pi OS.

**Comment by oznu** [comment]
Or even better, the Homebridge Raspberry Pi image, it's based on Raspberry Pi OS Lite / Debian:

https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started

**Comment by mvkpe** [comment]
That is what I have, that's where Debian came from, can I just install a fresh copy of Debian and install homebridge directly, as I said I only use this computer for homebridge without the RasperryPi os?

**Comment by oznu** [comment]
I have spent some time double checking the wiki instructions.

The output of this (which you pasted above):

```
apt-get update
Hit:1 http://ftp.debian.org/debian buster InRelease
Hit:2 http://ftp.debian.org/debian buster-updates InRelease
Hit:3 http://security.debian.org buster/updates InRelease
Hit:4 http://archive.raspberrypi.org/debian buster InRelease
Hit:5 http://packages.microsoft.com/repos/code stable InRelease
Hit:6 https://linux.teamviewer.com/deb stable InRelease
Hit:7 https://deb.nodesource.com/node_14.x buster InRelease
```

Is not consistent with a fresh install of Raspberry Pi OS or the Homebridge image.

Please either follow this guide to use the Homebridge image:

https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started

or  re-flash with Raspberry Pi OS:

https://www.raspberrypi.org/software/operating-systems/

**Comment by oznu** [comment]
> hard drive

To confirm you are actually using a physical Raspberry Pi device?

**Comment by mvkpe** [comment]
I'm not using a physical Raspberry device I'm using RaspberryPi desktop on Debian on a compaq mini palmtop.  So I'm going to try for a straight Debian setup with Homebridge installed directly without the Raspberry element.
