### ISSUE TITLE
Upgrade guide for Ubuntu?

### ISSUE THREAD

**Issue by CRDunne** [homebridge/homebridge#2804]
I have an homebridge and homebridgeUI instance up and running on an Ubuntu VM but the OS is a little out of date now. Is there a guide for upgrading the OS, while keeping the homebridge installation intact?

**Comment by oznu** [comment]
You can follow the normal Ubuntu Upgrade process. You won't loose any Homebridge config, and the service should remain intact.

Backup first to be safe.

**Comment by CRDunne** [comment]
> You can follow the normal Ubuntu upgrade process. You won't loose any Homebridge config, and the service should remain intact.
> 
> Backup first to be safe.

I followed the Ubuntu upgrade process and homebridge stopped working. What's the best way to troubleshoot?

**Comment by oznu** [comment]
Follow the wiki guide for ubuntu to re-setup the service.
