### ISSUE TITLE
Config backup/magic...

### ISSUE THREAD

**Issue by dannydeut** [homebridge/homebridge#2806]
I installed HB on a windows machine. I also installed and configured the Shelly and Nest plugin. Everything was working fine. 

I decided to upgrade my hardware. I did not backup anything. I disconnected my old machine, and installed HB on a fresh Windows installation on a new pc.

I was surprised that all my settings were still configured. Even my Nest / Google tokens... How is this possible? Is this somehow backupped in the cloud or at my home installation?

I am working as IT and Security Specialist, and this magic worries me.... Please explain this or tell me I am getting crazy.

**Comment by oznu** [comment]
> How is this possible?

It's not. The homebridge config is stored in your user profile (`c:\users\xxxx\.homebridge`) if you copied that, or have some sort of sync service running, it may have ended up on your new machine that way.
