### ISSUE TITLE
Snapshot Updates?

### ISSUE THREAD

**Issue by brn2prgrm** [homebridge/homebridge#2813]
I’m running v1.3.0b58 and recently noticed that my Homebridge-nest-cam and Homebridge-Ring video snapshots are not updating the way they have in the past.

Nest Cams now refresh their snapshot every 60 seconds (previously 10 seconds), and Ring Cams are not refreshing at all. Both cameras work as expected when you open Live view, only Snapshots seem to be affected. I also believe this issue started within the passed few beta updates, not specific to build 58.

Can anyone else confirm this issue? Or can there be an option to specific snapshot refresh timing?  Would it be plug-in specific to get this resolved?  Thanks all!

Homebridge: v1.3.0 beta 58
Node.JS: v14.15.5
NPM: v7.5.4

**Comment by Supereg** [comment]
The update interval of camera snapshots are 100% dependent on the client side (meaning the Home App Running on your iDevice).

It is and has always been 10 seconds when inside your Network and 1 Minute when using Home Hub (outside your network).
Homebridge (or any other HomeKit accessory) **can‘t** influence that timing.

could it be that maybe your device thinks it is outside of your network and requests the image snapshot via the home hub?
