### ISSUE TITLE
Missing Accessories Homebridge V1.3

### ISSUE THREAD

**Issue by Tontonpat** [homebridge/homebridge#2822]
**Describe The Bug:**
Since i’ve update to V1.3, most of my 52 accessories disapear of the web interface, only two are visible.

**To Reproduce:**
Update homebridge V1.3

**Expected behavior:**
Like the previous version, i’d like to see all my accessories on the web interface

**Comment by donavanbecker** [comment]
@Tontonpat Can you give and idea of what your setup is like? This feature was not taken away, sounds more like a setup issue.

**Comment by Tontonpat** [comment]
Sorry, i’m french and don’t really understand what you want?
Homebridge is running on my NAS and i have 7 plugins. All was ok before update to V1.3

**Comment by donavanbecker** [comment]
What plugins?

**Comment by Tontonpat** [comment]
I have only one bridge (i think)
![968116AE-48C9-4A05-9E0E-95AB421D5DE2](https://user-images.githubusercontent.com/49283285/108607394-7cd23c80-73c0-11eb-87b0-4d09c8949d7b.jpeg)
![00930641-029E-45E6-BB09-DCB353725B23](https://user-images.githubusercontent.com/49283285/108607396-7e9c0000-73c0-11eb-99c3-b2bc3edd0da0.jpeg)

**Comment by donavanbecker** [comment]
@Tontonpat have you seen any logs? Also have you tried restarting and seen logs?

**Comment by Tontonpat** [comment]
There is nothing special in the log, and yes, i restart several times

**Comment by donavanbecker** [comment]
And all accessories are working in the Home app?

**Comment by Tontonpat** [comment]
Yes, all are working in Home app

**Comment by mitch7391** [comment]
It could be like my issue back in #2774, mine is caught in a loop starting up and that is why the accessories do not populate in the tab.

**Comment by rickypullan** [comment]
I'm having this same issue as well-- no devices are appearing in my Accessories section.

**Comment by MikeDeltaHH** [comment]
Same issue here!

**Comment by Tontonpat** [comment]
Accessories are back, but if i restart homebridge, they disapear again 
![181FACB6-E8C0-45CD-8D15-251070CADE4A](https://user-images.githubusercontent.com/49283285/108694773-c70e0780-74ff-11eb-80df-2149291a0ae0.jpeg)

**Comment by soulcook** [comment]
I’m having exactly the same problem. Accessories show up and work in HomeKit, but have all disappeared from Homebridge Config UI. 
:
Node v14.15.3
NPM v6.14.9
Homebridge v1.3.0
Homebridge Config UI v4.39.0
OS Big Sur (MacOS 11.2)
hb-service

**Comment by oznu** [comment]
Closing in favour of https://github.com/oznu/homebridge-config-ui-x/issues/1093

**Comment by MikeDeltaHH** [comment]
Why closed? 

This is a homebridge v1.30 issue, not an issue with config-ui-x.

**Comment by oznu** [comment]
It will be dealt with in https://github.com/oznu/homebridge-config-ui-x/issues/1093, don't need two issues for the same thing.

**Comment by MikeDeltaHH** [comment]
Yes but there is a comment:

"This is a homebridge v1.30 issue, not an issue with config-ui-x. Take a look at issue 2774 and issue 2822."

So i think it´s better to close the case at config-iu-x!

**Comment by Tontonpat** [comment]
I've update home bridge to V1.3.1 and it didn't solve the problem

**Comment by oznu** [comment]
v1.3.1 had no changes to address this issue. Without debug logs requested in  https://github.com/oznu/homebridge-config-ui-x/issues/1093 not much can be done at this point.

**Comment by oznu** [comment]
Please use https://github.com/oznu/homebridge-config-ui-x/issues/1093.
