### ISSUE TITLE
characteristic was supplied illegal value" warnings from Homebridge 1.3.0

### ISSUE THREAD

**Issue by Tontonpat** [homebridge/homebridge#2824]
Describe the bug
Homebridge 1.3.0 is logging warnings about illegal values for characteristics returned by homebridge-samsung-tizen.

To Reproduce
Upgrade to Homebridge 1.3

Information from the log:
[homebridge-samsung-tizen] This plugin generated a warning from the characteristic 'Active Identifier': characteristic was supplied illegal value: undefined! This might throw errors in the future! `

**Comment by donavanbecker** [comment]
This is an issue with the plugin not homebridge.
