### ISSUE TITLE
Hinzufügen von Rollladenaktoren nicht mehr möglich nach Homebridge Update auf v1.3

### ISSUE THREAD

**Issue by majacom** [homebridge/homebridge#2826]
Ich habe die Homebridge auf v1.3 aktualisiert. Danach startet sie nicht mehr.
Nach ewigem Fehlersuchen habe ich festgestellt, dass es an den Rollladenaktoren (egal ob HM oder HM-IP) liegt.
Sobald ich die Rollladenaktoren aus der Config nehme, startet die Homebridge wieder problemlos.
Testweise wieder einen Rollo hinzugefügt, erneut das Problem.
Nach Downgrade auf v1.25 läuft wieder Alles mit sämtlichen Rollladenaktoren.

woran kann das liegen?
Würde gerne auf die v1.3 gehen, aber ohne Rolläden eher schlecht....

markus

**Comment by NorthernMan54** [comment]
Google translate

```
I've updated the Homebridge to v1.3. After that it doesn't start anymore.
After endless troubleshooting, I found that it is due to the roller shutter actuators (regardless of whether HM or HM-IP).
As soon as I take the roller shutter actuators out of the config, the Homebridge starts again without any problems.
Another blind was added as a test, the problem again.
After downgrading to v1.25, everything runs again with all roller shutter actuators.

what can be the reason?
Would like to go to v1.3, but rather bad without shutters .... 
```

Can you share the plugin name with the issue ?

**Comment by majacom** [comment]
thkl / homebridge-homematic

**Comment by NorthernMan54** [comment]
Tks for reporting this and raising an issue against the plugin [itself](https://github.com/thkl/homebridge-homematic/issues/658).

We have added a note for other users to not upgrade until the issue is resolved with [homebridge-homematic](https://github.com/homebridge/homebridge/wiki/Homebridge-1.3.0-Release-Plugin-Testing-Status).

Did the error create any error log messages you can share ?

**Comment by oznu** [comment]
Could you try the 1.3.1 beta and see if anything is different?

https://github.com/homebridge/homebridge/wiki/Homebridge-Beta-Testing

**Comment by thkl** [comment]
the issue was fixed in the latest version of the plugin and was reported as fixed by the author of the issue (https://github.com/thkl/homebridge-homematic/issues/658#issuecomment-782840452)
