### ISSUE TITLE
Homebridge 1.3.0 blinds not opening with alexa voice command

### ISSUE THREAD

**Issue by chriskmn** [homebridge/homebridge#2828]
After update to 1.3.0 my fibaro roller shutters are not closing anymore by alexa command „open“. Closing works and manually dimming on alexa app is also working. The command „dim 99 percent“ is also working and opening the blinds.

My suggestion is, that the max. dim value of 99 percent isn‘t handled correctly. In the log window the command „open“ shows a dim value of 100 which is not accepted by fibaro roller shutter. Homebridge mapping is also limited (max value) to 99.

On 1.2.5 everything works fine.

**Comment by NorthernMan54** [comment]
Can you share an accessory dump from your blinds when your using homebridge 1.3.0

want to see what the difference is.

**Comment by chriskmn** [comment]
This is the dump I have taken with homebridge 1.3.1 - also not working with alexa command "open":

[23/02/2021, 10:55:16] [Alexa] RangeController SetRangeValue CC:22:3D:E3:CE:30 { characteristics: [ { aid: 108, iid: 11, status: -70410 } ] } { characteristics: [ { aid: 108, iid: 11, value: 100 } ] } null

**Comment by chriskmn** [comment]
and this is the log with 1.2.5:

[23/02/2021, 11:11:51] [Alexa] RangeController SetRangeValue CC:22:3D:E3:CE:30 undefined { characteristics: [ { aid: 112, iid: 11, value: 100 } ] } null

**Comment by NorthernMan54** [comment]
@chriskmn What I'm looking for is the accessory dump from your setup under 1.3 so I can run it thru the parser to make the adjustments to map the 100 to 99 in these scenarios.  If you can share it, I should be to adjust.

**Comment by chriskmn** [comment]
oh, sorry, I misunderstood this. Is there an easy way to do this accessory dump ? I suppose it is not just the conf.json ?!

**Comment by NorthernMan54** [comment]
Details on how to collect are here https://github.com/NorthernMan54/homebridge-alexa#homebridge-accessory-dump

I'm going to close this here, and ask that you raise a new issue against homebridge-alexa with the dump attached.
