### ISSUE TITLE
Combine RaspberryPi with Linux

### ISSUE THREAD

**Issue by iMonZ** [homebridge/homebridge#2830]
This issue was opened to combine the RaspberryPi section with the Linux section (RaspberryPI is not using linux?)

So that we have a clean:
Linux x64, arm64
and a separate link to the ready to go image

**Comment by oznu** [comment]
Are you talking about the wiki guides?

Users look for the "Raspberry Pi" guide so we have it separated out. Our website analytics show that the "Raspberry Pi" option is clicked about 5x more often than the "Linux" option.

**Comment by oznu** [comment]
Linux is actually the least popular option according to website clicks, behind Docker and Windows surprisingly.

I do thank you for your good intentions editing the wiki home page, I have reverted them however for the above reasons. What may make sense for "tech" people who know that "Raspberry Pi" === "Linux" may not make sense to a new user just looking to get started.

**Comment by iMonZ** [comment]
> Linux is actually the least popular option according to website clicks, behind Docker and Windows surprisingly.
> 
> I do thank you for your good intentions editing the wiki home page, I have reverted them however for the above reasons. What may make sense for "tech" people who know that "Raspberry Pi" === "Linux" may not make sense to a new user just looking to get started.

This is really bad and misleading!
People should know that RaspberryPi = Linux
But with that you put the opposite information in their brain which is really the opposite from what you want: a good experience and easy to use + understand!
This decision from your side will make everything harder and more misleading for the future.

**Comment by Supereg** [comment]
I'm not sure the homebridge Wiki is a place to educate people about RasperryPis and what operating systems they are running.
I think, most guides out there explaining how to setup an RaspberryPi already do that pretty well, by showing the inheritance of Debian. 

What we are here for is giving people, most of them new to the platform, a quick and easy way to setup homebridge. And RaspberryPi people typically search for "RaspberryPI + whatever they want to do". 
And this is fine. As most RaspberryPi guides out there are specifically tailored towards beginners.

> This decision from your side will make everything harder and more misleading for the future.

I think you exaggerate here a bit.
