### ISSUE TITLE
System crashes because of RAM Overload

### ISSUE THREAD

**Issue by MarkM500** [homebridge/homebridge#2832]
Describe the bug
Error in Homebridge Protokoll. Over hours too much RAM load at synology.
"[TuyaAccessory] Operating system complained of resource exhaustion; did I open too many sockets?"

Problem exist since updated to Homebridge version 1.30

Environment (please complete the following information):
OS: Homebridge 1.30
iOS version:
Homehubs:
Node Version:
Plugin Version: back from 1.40 to 1.30 because of #205
Accessory Type

Hope you can help. Because the hole system crashes because of RAM-Overload.

Thanks.
Mark

**Comment by oznu** [comment]
Closing in favour of https://github.com/iRayanKhan/homebridge-tuya/issues/208.

If you run more than one plugin, try and isolate them, or run one at a time to figure out which one may be causing the issue.

**Comment by MarkM500** [comment]
Hi,

thanks for comment. The plugin must be homebridge tuya. That’s why I made this issue.
Is it also normal, that the plugin fills the protocol with the accessories and command 8. What is command 8, only a return message or an error.
Perhaps also the messages fills my RAM?

It looks like this:

Thanks Mark
[TuyaAccessory] Heard back from Divers SD3 with command 8
stdout
17:01:13
[TuyaAccessory] Heard back from Küche 2 with command 8
stdout
17:01:15
[TuyaAccessory] Heard back from Küche Ecke with command 8
stdout
17:01:18
[TuyaAccessory] Heard back from Divers SD3 with command 8
stdout
17:01:20
[TuyaAccessory] Heard back from Küche Ecke with command 8
stdout
17:01:22
[TuyaAccessory] Heard back from AppleTV Switch SD4 with command 8
stdout
17:01:23
[TuyaAccessory] Heard back from Küche 2 with command 8
stdout
17:01:25
[TuyaAccessory] Heard back from Küche Ecke with command 8
stdout
17:01:28
[TuyaAccessory] Heard back from Divers SD3 with command 8
stdout
17:01:30
[TuyaAccessory] Heard back from Küche Ecke with command 8
stdout
17:01:32
[TuyaAccessory] Heard back from AppleTV Switch SD4 with command 8
stdout
17:01:33
[TuyaAccessory] Heard back from Küche 2 with command 8
stdout
17:01:38
[TuyaAccessory] Heard back from Divers SD3 with command 8
stdout
17:01:43
[TuyaAccessory] Heard back from Küche 2 with command 8
stdout
17:01:47
[TuyaAccessory] Heard back from AppleTV Switch SD4 with command 8
stdout
17:01:48
[TuyaAccessory] Heard back from Divers SD3 with command 8
stdout
17:01:52
[TuyaAccessory] Heard back from AppleTV Switch SD4 with command 8
stdout
17:01:53
[TuyaAccessory] Heard back from Küche 2 with command 8
stdout
17:01:55
[TuyaAccessory] Heard back from Küche Ecke with command 8
stdout
17:01:58
[TuyaAccessory] Heard back from Divers SD3 with command 8
stdout
17:02:02
[TuyaAccessory] Heard back from AppleTV Switch SD4 with command 8
stdout
17:02:03
[TuyaAccessory] Heard back from Küche 2 with command 8
stdout
17:02:07
[TuyaAccessory] Heard back from AppleTV Switch SD4 with command 8
stdout
17:02:08
[TuyaAccessory] Heard back from Küche 2 with command 8
stdout
17:02:10
[TuyaAccessory] Heard back from Küche Ecke with command 8
stdout
17:02:12
[TuyaAccessory] Heard back from AppleTV Switch SD4 with command 8
stdout
17:02:13
[TuyaAccessory] Heard back from Divers SD3 with command 8
stdout
17:02:13
[TuyaAccessory] Heard back from Küche 2 with command 8
stdout
17:02:15
[TuyaAccessory] Heard back from Küche Ecke with command 8
stdout
17:02:18
[TuyaAccessory] Heard back from Divers SD3 with command 8
stdout
17:02:20
[TuyaAccessory] Heard back from Küche Ecke with command 8
stdout
17:02:22
[TuyaAccessory] Heard back from AppleTV Switch SD4 with command 8
stdout
17:02:23
[TuyaAccessory] Heard back from Divers SD3 with command 8
stdout
17:02:23
[TuyaAccessory] Heard back from Küche 2 with command 8
stdout
17:02:25
[TuyaAccessory] Heard back from Küche Ecke with command 8
stdout
17:02:28
[TuyaAccessory] Heard back from Divers SD3 with command 8
stdout
17:02:30
[TuyaAccessory] Heard back from Küche Ecke with command 8
stdout
17:02:32
[TuyaAccessory] Heard back from AppleTV Switch SD4 with command 8
stdout
17:02:33
[TuyaAccessory] Heard back from Küche 2 with command 8
stdout
17:02:37
[TuyaAccessory] Heard back from AppleTV Switch SD4 with command 8
stdout
17:02:38
[TuyaAccessory] Heard back from Divers SD3 with command 8
stdout
17:02:40
[TuyaAccessory] Heard back from Küche Ecke with command 8
stdout
17:02:42
[TuyaAccessory] Heard back from AppleTV Switch SD4 with command 8
