### ISSUE TITLE
Homebridge Mi Acpartner doesn't work any more with 1.3.x

### ISSUE THREAD

**Issue by Ugmaxie** [homebridge/homebridge#2834]
**Describe The Bug:**
After updating to v1.3.0, managing AC is broken.
Plugin used: [MiACPartner](https://github.com/LASER-Yi/homebridge-mi-acPartner#readme) @latest

No errors.
Apple HomeKit sees AC as expected but any actions doesn't manage AC.

**To Reproduce:**
Update HB from 1.2.5 to 1.3.0.

**Expected behavior:**
AC actions should work and manage AC device via Apple Home.

**Homebridge Config:**

```
{
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "auto",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            },
            "platform": "config",
            "sessionTimeout": 28800
        }
```

```json
{
    "bridge": {
        "name": "RasBri",
        "username": "MAC",
        "port": 51826,
        "pin": "000-00-000",
        "advertiser": "ciao"
    },
    "description": "Homebridge",
    "platforms": [
        {
            "platform": "MiAqaraPlatform",
            "manage": {
                "port": 11128,
                "password": "1111111111"
            },
            "gateways": {
                "7c49eb7feba4": "apo6zi1dylght6h4"
            },
            "defaultValue": {
                "7c49eb7feba4": {
                    "AcPartner_LightSensor": {
                        "name": "gateway light sensor",
                        "disable": true
                    },
                    "AcPartner_Switch_JoinPermission": {
                        "name": "gateway join permission switch",
                        "disable": true
                    }
                }
            }
        },
        {
            "platform": "XiaoMiAcPartner",
            "devices": {
                "ipAddress": "deviceToken"
            },
            "accessories": [
                {
                    "name": "AC Partner",
                    "type": "climate",
                    "sensorSid": "lumi.158d0002272e48",
                    "breaker": false
                }
            ]
        },
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "auto",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            },
            "platform": "config",
            "sessionTimeout": 28800
        }
    ],
    "accessories": [
        {
            "name": "Cleaner",
            "ip": "IP address",
            "token": "myToken",
            "waterBox": false,
            "pause": false,
            "dock": false,
            "accessory": "XiaomiRoborockVacuum"
        }
    ]
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**:  v14.15.0
* **NPM Version**:  v6.14.8
* **Homebridge Version**:  1.3.0
* **Operating System**: Raspbian
* **Process Supervisor**: don't know

**Comment by oznu** [comment]
Please provide logs so we can see what's going on.

You additionally report the issue to the plugin author.

**Comment by oznu** [comment]
v1.3.1 is now out, please also test on this new version.

**Comment by Ugmaxie** [comment]
@oznu Sure, thanks for paying your attention for this issue.

Unfortunately, v1.3.1 has the same issue as v1.3.0. Have tried already.

For both cases (works/doesn't work) Apple Home app works almost the same, but with `v1.3.0` and `v1.3.1` sometimes when I set an action like `HEAT` or `COOL` it automatically foes to off. Sometimes not... But anyway it doesn't manage AC device.

This is for v1.2.5. start
<img width="1426" alt="Screenshot 2021-02-23 at 18 47 29" src="https://user-images.githubusercontent.com/7901557/108878004-76ce9c80-7608-11eb-8778-218c3113e729.png">


These are for 1.3.1 start
<img width="1426" alt="Screenshot 2021-02-23 at 18 50 37" src="https://user-images.githubusercontent.com/7901557/108878090-8f3eb700-7608-11eb-876d-6e66c33faf09.png">
<img width="1426" alt="Screenshot 2021-02-23 at 18 50 45" src="https://user-images.githubusercontent.com/7901557/108878142-9cf43c80-7608-11eb-93aa-282f7cf3ae2c.png">

**Comment by Ugmaxie** [comment]
In addition, unfortunately, no logs provided during usage of that module.. No errors nor for `v1.2.5` nor `1.3.1`.

**Comment by Ugmaxie** [comment]
###Update:
- v1.3.2 still has an issue.

**Comment by Ugmaxie** [comment]
**Update**
- v1.3.3 still has an issue.

**Comment by Ugmaxie** [comment]
**Update**
v1.3.4 still has an issue... @oznu @elfive would you be so kind, maybe to make a hint if something might be changed inside [ACPartner](https://github.com/LASER-Yi/homebridge-mi-acpartner) module - I think I can fork and re-release a new module which will work with updated `homebridge`.
