### ISSUE TITLE
Max value of current temperature

### ISSUE THREAD

**Issue by maisun** [homebridge/homebridge#2835]
Hi,
Thanks for the new version 1.3.1 which fixes the issue with min. temperature. But looks like the default max. temperature is still 35, which creates issues for my water boiler and geothermal heating system:

[2/23/2021, 10:17:13 AM] [homebridge-oh2] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 35.2 exceeded maximum of 35. See https://git.io/JtMGR for more info.

Can the default max. temperature be relaxed? Thanks!

**Comment by donavanbecker** [comment]
@maisun this plugin sets the [maxValue](https://github.com/steilerDev/homebridge-openhab2-complete/blob/3fe37367e05b095bb4ff1cc89eeb25bd4985b77d/accessory/characteristic/Climate.js#L67-L79) this looks like a plugin issue.

**Comment by maisun** [comment]
> @maisun this plugin sets the [maxValue](https://github.com/steilerDev/homebridge-openhab2-complete/blob/3fe37367e05b095bb4ff1cc89eeb25bd4985b77d/accessory/characteristic/Climate.js#L67-L79) this looks like a plugin issue.

Hi, sorry my bad I will investigate further. I made the assumption when I saw the release note for 1.3.1 and thought those default values were changed in 1.3.0. Apologise

**Comment by oznu** [comment]
The default values can be overridden by a plugin.

See the CurrentTemperature for default min and max values:

https://developers.homebridge.io/#/characteristic/CurrentTemperature

Default max for CurrentTemperature is 100.
