### ISSUE TITLE
Infinite service restart loop v1.3.x

### ISSUE THREAD

**Issue by TheEngineerGuy** [homebridge/homebridge#2839]
Any 1.3.x version seems to run into an infinite reboot scenario, going back to 1.1.7, or a non 1.3.x version resolves the issue.

Error is as listed below:
`TypeError: Cannot read property 'log' of undefined
    at debug (/usr/lib/node_modules/homebridge/src/logger.ts:143:10)
    at checkDeviceDetails (/usr/lib/node_modules/homebridge-samsungtv-control/src/utils/detectDevices.ts:85:5)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)`

**Environment:**

* **Node.js Version**: v15.9.0
* **NPM Version**: 7.5.5
* **Homebridge Version**:  1.3.x
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by NorthernMan54** [comment]
Looking at the log fragment you supplied, this appears to be related to the 'homebridge-samsungtv-control' plugin.  Can you raise an issue against the plugin itself for the plugin developer to take a look into ? And close this issue.

**Comment by TheEngineerGuy** [comment]
That is correct, but this doesn't show up for that plugin till HB1.3.x is used. Could we please understand why it happens in 1.3.x and above?

**Comment by donavanbecker** [comment]
@TheEngineerGuy because of the validations that we have in 1.3.x to have a more reliable home bridge, so that issues like `not responding` doesn't happen in the Home App.

**Comment by TheEngineerGuy** [comment]
Thanks guys. I have posted it on the plugin page as well, lets see how soon he can fix it. Not very confident as he hasn't replied in sometime.

**Comment by TheEngineerGuy** [comment]
So, Iooks like `deviceChecks.push(checkDeviceDetails(headers, rinfo, log, config))` call in `detectDevices.ts` is creating this issue, as `log` is uninitiated here.

I have asked him to initiate log `log?: Logger` etc and get this solved, but let's see if he even takes a look at it.
