### ISSUE TITLE
Installing zigbee2mqtt on homebridge OS

### ISSUE THREAD

**Issue by agoralive** [homebridge/homebridge#2840]
Has anybody successfully installed zigbee2mqtt on a Raspberry Pi running the Homebridge OS

I have followed the install tutorial on their own website (https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html)

This works "fine". After first install I am able to run z2m using "npm start", but not able to run as a Daemon.

After the reboot, the npm start function does not work anymore.

If I install homebridge on a raspberry pi running the PI os, everything is perfect. But I would like to use the Homebridge OS

**Comment by oznu** [comment]
The homebridge image is just headless Pi OS with homebridge pre-installed.

In step 5 make sure the exec path uses:

```
ExecStart=/usr/local/bin/npm start
```
Their guide incorrectly assumes the Node.js install location. Node is installed at /usr/local/bin not /usr/bin.

**Comment by agoralive** [comment]
Thank you, I will try :)

**Comment by CalvinLeong8208** [comment]
@agoralive  I have same problem .. did you solve it ?
