### ISSUE TITLE
Child bridge with platform create doppel accessory in UI and HomeKit 

### ISSUE THREAD

**Issue by grzegorz914** [homebridge/homebridge#2843]
Hi,

if enable Child bridge for platform plugin then will create duplicates accessory in Config UI X and HomeKit,
one time accessory are assigned to the Homebridge and other one to the Child Bridge.
Also for pairing in HomeKit are available the platform accessory itself and the Child Bridge
For example this happened with homebridge-mieleathome plugin.

**Screenshots:**
<img width="1744" alt="Zrzut ekranu 2021-02-24 o 16 06 42" src="https://user-images.githubusercontent.com/28867813/109020538-57904780-76ba-11eb-8f36-5196da603001.png">

**Environment:**

* **Node.js Version**: 14.15.3
* **NPM Version**: 7.5.4
* **Homebridge Version**: 1.3.3
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
Did you check the cache to ensure they have been removed from the main bridge?

**Comment by grzegorz914** [comment]
Yes, 
this was still in cache, after manually remove it the duplicates are gone.

**Comment by oznu** [comment]
Is the "keep cached accessories for uninstalled plugins  (-K)" option enabled in Homebridge settings?

**Comment by grzegorz914** [comment]
Yes

**Comment by oznu** [comment]
That makes sense then, we may need to re-label that option now we have child bridges and the ability to disable plugins, but it seems to be working as intended for now.
