### ISSUE TITLE
Child bridge, same plugin confuses homebridge

### ISSUE THREAD

**Issue by Salvora** [homebridge/homebridge#2845]
**Describe The Bug:**

I was previously using two homebridge instances with different names.

One of them was linked to IOS.
The other was linked to another home automation system.

There was no problem with this setup. After I moved to 1.3.1, I decided to do away with the second instance of hb since the new child bridge feature was perfect for it. In the second instance, only 1 plug-in was running (People x plus), so it was easy to transfer. However, the same plugin was also running in the main instance. It was using "platform" but the names of the entries were different so there should not be any conflict.

Anyway,
I added the child bridge to my main configuration. configuration is below.

The result is unstable system:
Homebridge works fine on the console.
However, on the accessories page of the homebridge-ui, "people" plug-in sensors doesn't show up at all. 
There should be 4 sensors coming from main instance
There should be another 4 sensors coming from child bridge.
But none of them show up.
On homekit, those 4 sensors coming from main instance is unresponsive.
And another unrelated device is unresponsive

So, this didn't exactly work.

**To Reproduce:**
Add a plugin using platform.
Add the same plug-in again with child bridge config
pair your child bridge to another system.
pair your main bridge to your homekit.
wait, restart etc

**Expected behavior:**
Not sure, exposing the same plugin to different bridges is supported. Since this feature was mostly aimed at isolating unstable plug-ins.

**Homebridge Config:**

```json
"platforms": [
        {
            "platform": "config",
            "name": "Homebridge",
            "port": 8581,
            "auth": "none",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "en"
        },
        {
            "platform": "PeopleXPlus",
            "threshold": 5,
            "anyoneSensor": false,
            "nooneSensor": false,
            "guestSensor": false,
            "anyoneSensorName": "Present",
            "nooneSensorName": "None",
            "guestSensorName": "Guests",
            "webhookEnabled": false,
            "webhookPort": 51828,
            "cacheDirectory": "./persistent",
            "checkInterval": 10000,
            "ignoreReEnterExitSeconds": 10,
            "people": [
                {
                    "name": "John",
                    "target": "JP1",
                    "macAddress": "**:**:**:**:**:**",
                    "threshold": 5,
                    "checkInterval": 10000,
                    "useArp": true,
                    "ignoreReEnterExitSeconds": 10
                },
                {
                    "name": "Amanda",
                    "target": "A2",
                    "macAddress": "**:**:**:**:**:**",
                    "threshold": 5,
                    "checkInterval": 10000,
                    "useArp": true,
                    "statusOnly": true,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Nicole",
                    "target": "Nii3",
                    "macAddress": "**:**:**:**:**:**",
                    "threshold": 5,
                    "checkInterval": 10000,
                    "useArp": true,
                    "isGuest": true,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Penny",
                    "target": "P5",
                    "macAddress":  "**:**:**:**:**:**",
                    "threshold": 5,
                    "checkInterval": 10000,
                    "useArp": true,
                    "statusOnly": true,
                    "ignoreReEnterExitSeconds": 0
                }
            ]
        },
        {
            "platform": "PeopleXPlus",
            "threshold": 5,
            "anyoneSensor": false,
            "nooneSensor": false,
            "guestSensor": false,
            "anyoneSensorName": "Present",
            "nooneSensorName": "None",
            "guestSensorName": "Guests",
            "webhookEnabled": false,
            "webhookPort": 51828,
            "cacheDirectory": "./persistent",
            "checkInterval": 10000,
            "ignoreReEnterExitSeconds": 10,
            "_bridge": {
                "username":  "**:**:**:**:**:**",
                "name": "Homebridge-HA"
            },
            "people": [
                {
                    "name": "John_hb",
                    "target": "JP1",
                    "macAddress":  "**:**:**:**:**:**",
                    "threshold": 5,
                    "checkInterval": 10000,
                    "useArp": true,
                    "ignoreReEnterExitSeconds": 10
                },
                {
                    "name": "Amanda_hb",
                    "target": "A2",
                    "macAddress":  "**:**:**:**:**:**",
                    "threshold": 5,
                    "checkInterval": 10000,
                    "useArp": true,
                    "statusOnly": true,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Nicole_hb",
                    "target": "Nii3",
                    "macAddress":  "**:**:**:**:**:**",
                    "threshold": 5,
                    "checkInterval": 10000,
                    "useArp": true,
                    "isGuest": true,
                    "ignoreReEnterExitSeconds": 0
                },
                {
                    "name": "Penny_hb",
                    "target": "P5",
                    "macAddress":  "**:**:**:**:**:**",
                    "threshold": 5,
                    "checkInterval": 10000,
                    "useArp": true,
                    "statusOnly": true,
                    "ignoreReEnterExitSeconds": 0
                }
            ]
        },
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v14.16.0
* **NPM Version**: v7.5.6
* **Homebridge Version**: 1.3.1
* **Operating System**:Raspberry Pi OS
* **Process Supervisor**:  hb-service

**Comment by donavanbecker** [comment]
@Salvora why not setup both plugins as child bridges? 
I have did this for the same plugin and they both work so just add:
```
"_bridge": {
                "username": "A1:B2:C3:D4:E5:F6",
                "port": 42150
            }
```
you can change the port and username to whatever you want that is different then the other plugin.

**Comment by Salvora** [comment]
> 
> 
> @Salvora why not setup both plugins as child bridges?
> I have did this for the same plugin and they both work so just add:
> 
> ```
> "_bridge": {
>                 "username": "A1:B2:C3:D4:E5:F6",
>                 "port": 42150
>             }
> ```
> 
> you can change the port and username to whatever you want that is different then the other plugin.

It makes super perfect workaround.

But using main instance is a bug or not in this case?

**Comment by Salvora** [comment]
Thanks, @donavanbecker for the advice.
As soon as I created the a second child bridge. I saw that everything shows up as expected in the homebridge-ui accessories.

**Comment by donavanbecker** [comment]
> It makes super perfect workaround.
> 
> But using main instance is a bug or not in this case?

Potentially.

**Comment by oznu** [comment]
One on the main bridge and one as a child bridge should work; you may need to clear the accessory cache of the main bridge to get it working the first time though.

**Comment by Salvora** [comment]
> One on the main bridge and one as a child bridge should work; you may need to clear the accessory cache of the main bridge to get it working the first time though.

Unless you make 2 child bridges, it becomes unstable.
Unresponsive, etc.
