### ISSUE TITLE
Homebridge instance name in the config.json is different from the one appearing in the Home App

### ISSUE THREAD

**Issue by ppapajohn** [homebridge/homebridge#2846]
Hi all,
I have performed a fresh install of homebridge on ubuntu 20.04 LTS on rpi4. When I change the name of the homebridge in the config.json file, it is changed. However when I am searching it in the Home App the name is appended by 4 random letters and/or digits. Please refer to the config.json below.  

When I open the Home App and open the Add Accessory menu the name I see is "Homebridge pph home **43A1**". I cannot understand from where string **43A1** is added. Is this something normal?  

This behavior is exactly the same even in child bridges. As another example I have a child bridge with name = "eWeLink bridge" and what I see in the Home app is "eWeLink bridge **F789**" 

The related log entry is provided below: 

What I have tried so far is to delete cached accessories (and the persist folder), even try to understand from where bonjour service gets this name, with no luck. I also added a displayName: tag in the json file, but is not respected; I guess it does not exist although I get no errors by adding it. 

**To Reproduce:**
Simply change the name of your bridge. 

**Expected behavior:**
To see the same name in the Home app as per the config.json name: tag.

Any ideas? Thank you in advance! 

[**Logs:**]()
[2/24/2021, 8:59:05 PM] Loaded 0 cached accessories from cachedAccessories.
[2/24/2021, 8:59:05 PM] ---
[2/24/2021, 8:59:06 PM] Loaded plugin: homebridge-config-ui-x@4.39.0
[2/24/2021, 8:59:06 PM] Registering platform 'homebridge-config-ui-x.config'
[2/24/2021, 8:59:06 PM] ---
[2/24/2021, 8:59:06 PM] Loading 1 platforms...
[2/24/2021, 8:59:06 PM] [Config] Initializing config platform...
[2/24/2021, 8:59:06 PM] [Config] Running in Service Mode
Preparing Advertiser for 'Homebridge ppj home 43A1' using bonjour-hap backend!
Setup Payload:
X-HM://0024XUA88R8U8

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge ppj home",
        "username": "0E:B3:4A:18:A6:01",
        "port": 52666,
        "pin": "888-66-888",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8266,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        }
    ],
    "disabledPlugins": []
}
```

**Environment:**

Node.js Version v14.16.0
npm Version v6.14.11
user homebridge
Storage Path /var/lib/homebridge
Config Path /var/lib/homebridge/config.json
Service Mode Yes

* **Node.js Version**: v14.16.0
* **NPM Version**: v6.14.11
* **Homebridge Version**: 1.3.1
* **Operating System**: Ubuntu 20.04 on rpi4
* **Process Supervisor**: hb-service

**Comment by ppapajohn** [comment]
Apparently this is a hash being appended to the instance name, while there was already an open discussion on the topic: https://github.com/homebridge/HAP-NodeJS/issues/852 "Display names automatically modified #852". 

What is not clear to me is whether it is safe to change the addIdentifyingMaterial to false. And if its ok, I suppose this needs to be done directly to Accessory.d.ts config file, right? 

Obviously feel free to change the tag from bug to question or even delete it. Sorry for that, but I search a lot and couldn't find anything. :)

Any response is much appreciated it. 

Thanks, 
Panos

**Comment by oznu** [comment]
The name is adjusted to ensure it is unique in the network, duplicate names would result in conflicts.

**Comment by ppapajohn** [comment]
thanks Oznu! I suppose thought that if I am willing to take this risk or I am careful in the naming provisioning, then changing the addIdentifyingMaterial var to false in the bridgeService.js will change this behavior. 

Wishes for a great night ahead and thank once again for your response!
