### ISSUE TITLE
Homebridge and all devices with no answer

### ISSUE THREAD

**Issue by emcepe** [homebridge/homebridge#2847]
Before today I had Homebridge 1.2.5 up and running almost fine for a long time, since Homebridge 1.1 ... had some troubles now and then with Ciao mDNS and was glad to see that Homebridge 1.3.x brings back Bonjour-HAP, so I decided to update.

Update went smooth, all was fine. I changed mDNS Advertiser to Bonjour HAP, restarted and nothing worked, all devices on my iPad and iPhone were offline with no answer. So I decided to roll back my change to Ciao mDNS again, restarted, and nothing worked too, for whatever reason.

Restarted iPad & iPhone, without success. Then I did a downgrade to 1.2.5, without success either. Then I did a complete restore of my previous backup of 1.2.5, guess what ... without any success. All devices are down with "no answer" or really "Keine Antwort" :-(

So I don't know what the problem is at all. Any hint? Any guess?

node v12.21.0
npm v6.14.11
homebridge v1.3.1 (HAP-NodeJS v0.9.2)
FHEM latest version + homebridge-fhem latest version
Raspbian Buster on a Raspberry Pi 4b 

thank you.

**Comment by oznu** [comment]
> I did a downgrade to 1.2.5, without success either. Then I did a complete restore of my previous backup of 1.2.5, guess what ... without any success. 

it sounds like you need to unpair homebridge from both the Homebridge UI and from the iOS Home app, and re-pair.

https://github.com/homebridge/homebridge/wiki/Connecting-Homebridge-To-HomeKit#how-to-remove-homebridge

**Comment by emcepe** [comment]
But if I do that all config of rooms etc. are lost no?

**Comment by mrMiimo** [comment]
I had the same problem and the only thing that worked was:
- delete all homebridge devices from homeapp.
- stop homebridge
- change the "username" of homebridge config.json
- re-add devices to the home app.

**Comment by emcepe** [comment]
well, I think if I do that everything customized in Home app and Eve App will be gone - so that's not an option for me (now) - it was a long hard work to configure that all like it was until yesterday and I really have no desire at all to do that again.

I really regret that I did an update yesterday :-(

**Comment by mrMiimo** [comment]
if you talk about "automations", yes .. they disappear or when you delete the accessories it doesn't work, so when you re-add the accessories again you have to reconfigure.

The rooms instead remain.

**Comment by vitaliy-kozlov** [comment]
Same issue. Tried to downgrade with no luck. What should I do?

**Comment by mrMiimo** [comment]
> Same issue. Tried to downgrade with no luck. What should I do?

did you read the comments above?

**Comment by vitaliy-kozlov** [comment]
> > Same issue. Tried to downgrade with no luck. What should I do?
> 
> did you read the comments above?

Yes but I don't wont delete my devices from homeapp and added them again manually. There a lot of devices (more than 50) with a lot of automations...

**Comment by emcepe** [comment]
I have 133 devices :-( ... and I am still waiting for a wonder ;-/

**Comment by mrMiimo** [comment]
well, i don't know if there is another way.
The only solution I found was https://github.com/homebridge/homebridge/issues/2847#issuecomment-785718092

**Comment by vitaliy-kozlov** [comment]
> I have 133 devices :-( ... and I am still waiting for a wonder ;-/

I was so angry) tried a lot of things, restore backups, downgrade to different hb versions, clear cached accessories, change DNS and etc so at last I go crazy and totally deleted the hb bridge from the homekit. After that I added bridge again to Home app and added all my devices manually during next hour!))

**Comment by vitaliy-kozlov** [comment]
OMG! After rebooting homebridge it happened again and all my devices is not available in homekit AGAIN!

**Comment by emcepe** [comment]
:-((((((((

I think there‘s a deeper bug in the new Homebridge 1.3.0/1.3.1 ... I still wait for a wonder and if its not happening till after the weekend I have to start from scratch also but will use 1.2.5 then...

**Comment by mrMiimo** [comment]
> :-((((((((
> 
> I think there‘s a deeper bug in the new Homebridge 1.3.0/1.3.1 ... I still wait for a wonder and if its not happening till after the weekend I have to start from scratch also but will use 1.2.5 then...

Do you confirm that you have changed your homebridge username (mac address) before re-pair the devices?

If you share some information (such as your configuration) it may be useful.

**Comment by mrMiimo** [comment]
> OMG! After rebooting homebridge it happened again and all my devices is not available in homekit AGAIN!

Do you confirm that you have changed your homebridge username (mac address) before re-pair the devices?

If you share some information (such as your configuration) it may be useful.

**Comment by vitaliy-kozlov** [comment]
> > OMG! After rebooting homebridge it happened again and all my devices is not available in homekit AGAIN!
> 
> Do you confirm that you have changed your homebridge username (mac address) before re-pair the devices?
> 
> If you share some information (such as your configuration) it may be useful.

No, I did not change username, just removed the bridge and re-added it again so all of my devices was available again, but after reboot issue was reproduced again. So for now I dowgraded homebridge to 1.2.5 version and on this build seems to be all is OK so I will wait some fix because don't want to kill a hours of restoring. Thanks.

**Comment by emcepe** [comment]
Excuse me Vitaliy, but do I understand you right that you just removed the bridge in iOS Home App (that would remove all devices too no?) and after that just re-added the bridge and all devices were back in place?

**Comment by mrMiimo** [comment]
> > > OMG! After rebooting homebridge it happened again and all my devices is not available in homekit AGAIN!
> > 
> > 
> > Do you confirm that you have changed your homebridge username (mac address) before re-pair the devices?
> > If you share some information (such as your configuration) it may be useful.
> 
> No, I did not change username, just removed the bridge and re-added it again so all of my devices was available again, but after reboot issue was reproduced again. So for now I dowgraded homebridge to 1.2.5 version and on this build seems to be all is OK so I will wait some fix because don't want to kill a hours of restoring. Thanks.

well, if you don't change your username, in fact it was like not doing anything.
I solved it by doing **exactly** these steps: https://github.com/homebridge/homebridge/issues/2847#issuecomment-785718092

**Comment by nadavgolden** [comment]
Don't know if my case is caused by the same problem but once I removed the HomeBridge from my Home app I could not for the life of me get it to connect again in the Home app. 
The Home app is stuck on "Connecting to Bridge" until it is "Unable to Add Accessory" with no logs on HomeBridge's console at all (even in debug mode). 
Btw, trying to setup a fresh install (using Docker) results in the same error.

**Comment by cefoster0** [comment]
Same issue on Mojave (10.14.6) and up to date iOS devices. iOS devices went no-response about a week ago. Restarted Homebridge server and iOS devices, iOS devices are fine, but Home app on Mac randomly goes into No Response. Tried switching between Bonjor-HAP and Caio with no change. 

Disabled Home in iCloud preferences, deleted Library/HomeKit, restarted, reenabled, restarted, and service was restored but it randomly flaked out again. iOS devices are fine when this happens.

**Comment by balddaddy33015** [comment]
Anybody have any fixes yet? I've run into this issue today and have not been able to remedy it.

**Comment by emcepe** [comment]
unfortunately not :-(

**Comment by cefoster0** [comment]
I did the procedure listed above [https://github.com/homebridge/homebridge/issues/2847#issuecomment-785718092](url) and it worked in Home App on my Mac, but then my phones stopped working. Removed HomeKit bridge, readded everything, and it worked on the Phone BUT STOPPED on the Mac again! finally restarted Homebridge, the whole server, and its dead on everything. I'm thinking downgrade is the only option.

**Comment by cefoster0** [comment]
One more piece of information. I think this started when I started trying to use the 'network interfaces' setting to manually bind Homebridge to my system's ethernet port. My ethernet is flaky (MacMini 1,1 upgraded to 2,1 running Debian Buster) so I disabled that setting and my phones at least are working normally. Home app still not working. Picking between Bonjour-HAP or Caio makes no difference.

**Comment by nadavgolden** [comment]
> One more piece of information. I think this started when I started trying to use the 'network interfaces' setting to manually bind Homebridge to my system's ethernet port. My ethernet is flaky (MacMini 1,1 upgraded to 2,1 running Debian Buster) so I disabled that setting and my phones at least are working normally. Home app still not working. Picking between Bonjour-HAP or Caio makes no difference.

I’ve noticed from the logs on my router that the ethernet to my server connects and disconnects rapidly. Also, MAC address resolution (ARP) fails on my Windows PC as long as Homebridge is running (found while trying to SSH to it). Weird 🤷🏻‍♂️

**Comment by emcepe** [comment]
For whatever reason my setup started to work again this night (1.2.5 restored from backup). I did exactly nothing because I was asleep. Funny things happening...

**Comment by balddaddy33015** [comment]
Mine has been going in and out for a few days now as well. If I leave it
alone it’ll come back when it pleases. Just waiting for a fix

**Comment by emcepe** [comment]
And I stick with 1.25 until 1.3 is fixed, whatever the problem is.
My 1.25 setup just works now w/o problems.

**Comment by balddaddy33015** [comment]
I’m struggling. My options for rolling back include 4.39.0 down to 4.26.0

**Comment by setBoolean** [comment]
Same problem running Homebridge 1.3.x, reverting to 1.2.5 fixes the issue.

**Comment by cefoster0** [comment]
Interestingly my ring cameras still work, as do all HomeKit native items, just nothing else.

**Comment by bubez81** [comment]
Same here...it's very strange sometimes after cleaning the cache the accessories work, after two days can't reach the homebridge accessories...

**Comment by bubez81** [comment]
I'm running homebridge on a Mac mini with Big Sur...could be a bonjour problem or permission problem maybe?

**Comment by cefoster0** [comment]
This is still an issue on the latest versions

**Comment by emcepe** [comment]
And I am still on 1.25 because of this.

**Comment by bubez81** [comment]
me too...can't understand the cause....maybe a specific plugin?
I'm using: Homebridge Alexa
                  Homebridge Arlo
                 Homebridge Camera FFmpeg
                 Homebridge Daikin Local
                 Homebridge Google Smart Home
                 Homebridge Harmony
                 Homebridge Mqttthing
                 Homebridge Shelly
                 Homebridge SwitchBot

**Comment by emcepe** [comment]
dunno.

I am just using 3 Plugins:

FHEM
Weather Plus
WOL

always latest...

**Comment by sclk34** [comment]
I can't connect to my devices either. After removing HB on the phone, it does not reconnect

**Comment by balddaddy33015** [comment]
> Same problem running Homebridge 1.3.x, reverting to 1.2.5 fixes the issue. 

This worked for me. Ran away from 1.3.x and have been stable on 1.2.5 ever since reading this comment

**Comment by bubez81** [comment]
yes but for example now I see a lot of warning with 1.2.5:

`[4/13/2021, 2:26:28 PM] [Lavatrice] Ignoring invalid value [0.027] for Electric Current - above maximum (null)
[4/13/2021, 2:26:34 PM] [Microonde] Ignoring invalid value [232] for Voltage - above maximum (null)
[4/13/2021, 2:26:34 PM] [Microonde] Ignoring invalid value [0.265] for Electric Current - above maximum (null)
[4/13/2021, 2:26:35 PM] [Asciugatrice] Ignoring invalid value [232] for Voltage - above maximum (null)
[4/13/2021, 2:26:36 PM] [Piano Cottura] Ignoring invalid value [2] for Current Consumption - above maximum (null)
[4/13/2021, 2:26:36 PM] [Piano Cottura] Ignoring invalid value [0.601] for Electric Current - above maximum (null)
[4/13/2021, 2:26:36 PM] [Frigorifero] Ignoring invalid value [239] for Voltage - above maximum (null)
[4/13/2021, 2:26:36 PM] [Frigorifero] Ignoring invalid value [0.009] for Electric Current - above maximum (null)
[4/13/2021, 2:26:38 PM] [Lavatrice] Ignoring invalid value [0.025] for Electric Current - above maximum (null)`

**Comment by bubez81** [comment]
maybe i found the cause of the problem...it could be homeassistant and homekit integration

**Comment by cefoster0** [comment]
> maybe i found the cause of the problem...it could be homeassistant and homekit integration

I don't have homeassistant but I do have Apple TVs as Hubs as well as MyQ devices that are native HomeKit.

**Comment by vitaliy-kozlov** [comment]
Strange, but after downgrading to 1.2.5 and update on latest 1.3.4 issue is fixed for me.

**Comment by bubez81** [comment]
errata corrige...it's not home assistant it's the HomePod Mini

**Comment by sneakypete70** [comment]
Still the same problem here - on 1.3.4 no answer from all Homebridge connected devices in the home app. Back to 1.2.5 - everything ok…

**Comment by bubez81** [comment]
Solved this problem migrating home assistant in another rpi maybe it's related to bonjour communication and macos

**Comment by cefoster0** [comment]
I am still getting this issue on my Mojave computer. I set up a Catalina computer and it worked.

**Comment by emcepe** [comment]
> Still the same problem here - on 1.3.4 no answer from all Homebridge connected devices in the home app. Back to 1.2.5 - everything ok…

same here, again and again. I've set up a test playground for it, but it doesn't matter what I do, >= 1.3 does not work at all.

Whats about the maintainer of homebridge? is he reading this? ;->

**Comment by sneakypete70** [comment]
Any updates?

**Comment by emcepe** [comment]
The root of all problems was:

https://github.com/justme-1968/homebridge-fhem/issues/82

**Comment by adamcoulombe** [comment]
For me, reverting to 1.2.5 fixed the issue of devices going unresponsive

**Comment by emcepe** [comment]
Unstale comment

**Comment by nixmeer** [comment]
I just updated homebridge from a version that I installed about 3.5 years ago. The raspberry pi used to crash like once a week. It also ran mosquitto and magic mirror 2. 

After installing a fresh raspberry pi OS, I installed homebridge, the plugins I had before and mosquitto. Reuploaded the old config.json (same bridge name and stuff) and... home app in iOS and macOS get "No Answer" (actually German in my case).

**Comment by iMonZ** [comment]
So I got the no response issue.
But most of the time I can still control my devices.
Only sometimes it greyed out but when I turne on my device manually it still recognizes that the device is turned on and I can control it again (but still shows no response)

**Comment by nixmeer** [comment]
I didn’t try that.

**Comment by cefoster0** [comment]
My “resolution” was to upgrade my computer to Catalina. While that made my computer worse in other ways, the Home app functions perfectly.

**Comment by ztalbot2000** [comment]
Hi,

  I'm a homebridge plugin developer, not a homebridge developer. May I suggest that for those who downgrade and still can't get things working again that they stop homebridge and then remove the accessories and persist files/directories. They may be in /var/lib/homebridge or $HOME/.homebridge, depending on the install.
This would be supposedly equivalent to deleting them from the GUI, but it would resolve possible downgrade issues. When you restart Homebridge, you will have to add *ALL* your devices again, but if they stopped working anyway why not.  This would be the sledge hammer approach.

take care,
John

**Comment by emcepe** [comment]
So 2 month later...

Is this a Homebridge bug or a homebridge-fhem plugin bug?

**Comment by ztalbot2000** [comment]
Hi,

  I read through HomeBridge-them #82.  It sounds like it's a them issue in
conjunction with the latest 1.3.4 of homebridge. The reason I say that is
the log POWER is not a number may be the key. I do know that the latest
Homebridge moved to typescript and did cause me a little problem with
passing a string containing a float value. I'm curious and will poke some
more.  I would not get your hopes up though. Neither is my specialty.  I
just like to poke.

Ttyl,
John

**Comment by nixmeer** [comment]
It's been almost 3 weeks since I did that and it took me like a day. I can't install the plugins 1 by 1 and wait for weeks to see if it works. The entire apartment relies on homebridge. And I'm currently in the final phase of writing my  master thesis so there's no time to re-add 80 devices, put them in rooms and link all the scenes and automations again. 

does the debug mode add any information to logging that might show the cause of this problem?

**Comment by nixmeer** [comment]
It's getting even more strange :D or maybe not strange but clear.

The home app on Big Sur works even from outside the local network (Apple TV as hub), and another iPhone on iOS 14.8 also works. The iOS 15 iPhone however...

**Comment by ztalbot2000** [comment]
As you narrow down what works and doesn't, sometimes even writing about it,
the issue can become clearer. In this case is it possible the problem then
is with IOS 15 or the combination of IOS 15 and the latest HomeBridge?  You
would not perhaps have another IOS 15 device to check that theory?

Ttyl,
John

**Comment by nixmeer** [comment]
Yesterday, it didn’t work at all, homebridge and/or the pi crashed. Neither the home App on an iOS 14 iPhone, nor my Mac home app nor the ssh connection to the pi worked. 

After that, I only checked my phone‘s home app, and tried a lot like rebooting or downgrading homebridge. I can’t say what made it work for iOS 14 and my Mac. When I opened the Mac home app, it just worked while my iPhone didn’t. I then checked the other iPhone and this worked as well. 

I won’t be home until next week to check if the iOS 15 has an issue with the remote connection to the Apple TV or a general issue.

**Comment by ztalbot2000** [comment]
Hi,

  So I just had a look at the code.  You should turn on debugging because
there are logs that would be generated. i.e.
this.log.info( 'fetching: ' + url );

Do this for what works and what does not.  That might give you more
insight.  If you would like to send me the logs for each, I can compare the
behaviour with what I suspect the code is doing/not doing.

To not clutter up the ticket.  You can send them to me directly at
***@***.***

ttyl,
John

**Comment by emcepe** [comment]
Hi @ztalbot2000,

thanks for your time and effort but I cannot and will not test the thing that won't work again because that will brick HomeKit completely and I have to start from scratch again - I did that more than twice and it's a pain in the a**. Even if I change the type of the outlet back it won't make any difference, HomeKit stays bricked :-(

**Comment by Damianod27** [comment]
Hello

Download the Controller for HomeKit app from the App Store. 
Purchase a paid monthly subscription. This will allow you to back up all your Home settings.

Follow the steps :
1. Make copies in Controller for HomeKit of your Home.
2. Make a copy of the Config.json file on Homebridge.
3. Reinstall clean Homebridge.
4. Reinstall all plugins. Don't configure them !!!
5. Restore the config.json file from the backup
6. Restart the bridge with "Restart Server". No Restart only option Restart Server !!!
7. Restore your copy of Home in the Controller for HomeKit app 

Best Regards 
Damian

**Comment by martinorob** [comment]
Same problem here. Reverted on 1.2.5.
Following for get update of fix 
Thank you all

**Comment by emcepe** [comment]
Unstale comment

**Comment by emcepe** [comment]
Unstale comment

**Comment by doctornakhare** [comment]
> I had the same problem and the only thing that worked was:
> 
> * delete all homebridge devices from homeapp.
> * stop homebridge
> * delete homebridge persist and accessories forlder
> * change the "username" of homebridge config.json
> * re-add devices to the home app.

Thank you very much ! I had deleted cached file of one of the working lights along with the problematic one; I tried clean install along with a fresh install of node.js ; but no matter what I did I could not get rid of file like npmignore.dll. I had given up until I came upon this — I only had to delete homebridge persists and Accesories folder to see all my connected Accesories back in homebridge. Thanks a ton @mrMiimo

**Comment by emcepe** [comment]
Unstale comment die 13673te :-(

**Comment by emcepe** [comment]
Unstale comment die 47742255te :-(

**Comment by RobinMac** [comment]
I never reported an issue

**Comment by ztalbot2000** [comment]
Maybe this should be closed so we no longer get annoying emails from GitHub actions?

**Comment by nixmeer** [comment]
> Maybe this should be closed so we no longer get annoying emails from GitHub actions?

but it does not solve the issue. However, it didn’t occur to me again

**Comment by faxioman** [comment]
Has anyone been able to figure out why this problem occurs in every HAP server related product? I have two IP addresses as in many other reports. I am already using the "bind" option.

**Comment by faxioman** [comment]
What is working in my case is to shutdown all the Apple hubs I was using (AppleTV and two HomePod Mini). I can power on the hubs after some minutes and all it's working again.
