### ISSUE TITLE
Create Child Bridge for whole Plugin

### ISSUE THREAD

**Issue by Luftloch80** [homebridge/homebridge#2849]
Hey. 
can you add possibility to add support for child bridge for whole group of plugin accessories 
For example i have a lot homebridge-mqttthing devices But i can only create Child Bridge for every Single device. 
i Want to create one Child bridge for all devices in mqtthing Plugin 
Thx

**Comment by mrMiimo** [comment]
I have the same question..

**Comment by oznu** [comment]
This is not possible right now, we will look into this for a future release.

**Comment by pa-friederich** [comment]
Hi,
While grouping all the accessories in a child bridge would be indeed a improvement, I think it would be good also to create child bridges with several accessories within the same plugin. It would give a bit more versatility.
Could it be considered also for a future release?
Thanks

**Comment by oznu** [comment]
The 1.3.2 beta has initial support for this.

https://github.com/homebridge/homebridge/wiki/Homebridge-Beta-Testing

* Only `accessory` type plugins can have multiple accessories on the same child bridge.
* All accessories on a single child bridge must be from the same plugin and using the same alias.

There is no UI for this, just edit the `config.json` manually and set the "username" for each accessory you want on the same bridge to be the same value. The bridge settings, such as port and name will be set from the first child bridge in the list for that username.

**Comment by mrMiimo** [comment]
> The 1.3.2 beta has initial support for this.
> 
> https://github.com/homebridge/homebridge/wiki/Homebridge-Beta-Testing
> 
> * Only `accessory` type plugins can have multiple accessories on the same child bridge.
> * All accessories on a single child bridge must be from the same plugin and using the same alias.
> 
> There is no UI for this, just edit the `config.json` manually and set the `"_bridge"."username"` for each accessory you want on the same bridge to be the same value. The bridge settings, such as port and name will be set from the first child bridge in the list for that username.
> 
> For example:
> 
> ```js
> "accessories": [
>         {
>             "accessory": "DummySwitch"
>             "name": "dummy switch one",
>             "_bridge": {
>                 "username": "0E:83:FD:29:58:C9",
>                 "port": 55197
>             }
>         },
>         {
>             "accessory": "DummySwitch",
>             "name": "dummy switch two",
>             "_bridge": {
>                 "username": "0E:83:FD:29:58:C9"  // same username as first one
>             }
>         }
> ]
> ```

That's great, thx!
Just one question ... I noticed in the "main" accessory that you specified a `port`. 
Is it optional or is it necessary in this case?

**Comment by oznu** [comment]
> Just one question ... I noticed in the "main" accessory that you specified a port.
Is it optional or is it necessary in this case?

It's optional, but preferred so it doesn't change with every restart. If you define a port in the second one it would just be ignored.

**Comment by pa-friederich** [comment]
> The 1.3.2 beta has initial support for this.
> 
> https://github.com/homebridge/homebridge/wiki/Homebridge-Beta-Testing
> 
> * Only `accessory` type plugins can have multiple accessories on the same child bridge.
> * All accessories on a single child bridge must be from the same plugin and using the same alias.
> 
> There is no UI for this, just edit the `config.json` manually and set the `"_bridge"."username"` for each accessory you want on the same bridge to be the same value. The bridge settings, such as port and name will be set from the first child bridge in the list for that username.
> 
> For example:
> 
> ```js
> "accessories": [
>         {
>             "accessory": "DummySwitch"
>             "name": "dummy switch one",
>             "_bridge": {
>                 "username": "0E:83:FD:29:58:C9",
>                 "port": 55197
>             }
>         },
>         {
>             "accessory": "DummySwitch",
>             "name": "dummy switch two",
>             "_bridge": {
>                 "username": "0E:83:FD:29:58:C9"  // same username as first one
>             }
>         }
> ]
> ```

Great, thank you !

**Comment by oznu** [comment]
If a few people confirm this works, or at least confirm this change does not break their existing child bridges (I've done testing on my setup and it's fine) - then I will push out a 1.3.2 release.

**Comment by mrMiimo** [comment]
> If a few people confirm this works, or at least confirm this change does not break their existing child bridges (I've done testing on my setup and it's fine) - then I will push out a 1.3.2 release.

For me works. Thanks @oznu !
