### ISSUE TITLE
Home app incorrectly shows 100%  brightness when light is switched on

### ISSUE THREAD

**Issue by soulcook** [homebridge/homebridge#2850]
Hi

This may be a well-known bug but I can't find anything matching it here, so reporting.

I've written a Homebridge plugin to connect to Rako lighting systems. It works really well, but there seems to be an infuriating bug in the Home app or the Homebridge/HomeKit interface. When you switch on a light, the Home app insists on displaying the brightness as "100%" even when it isn't (and even when you tell it multiple times that it isn't, and even when HomeBridge knows that it isn't).

Here is a detailed description.

When I switch on a light (via the Home app or the Accessories tab in the Homebridge Admin UI):

- the plugin restores the previous brightness level (and sets this using updateCharacteristic)
- it carefully ignores the unwanted "brightness: 100" event emitted by HomeKit on switch-on
- the actual brightness level is set correctly
- the Accessories tab in HomeKit Config UI shows the correct level

BUT

-  the brightness in the Home app shows 100% (incorrectly)
- it doesn't matter how often I use updateCharacteristic to modify the brightness, it continues to show 100%
- it is stuck on 100% until I manually change the brightness in the Home app

I've found a clunky workaround, which is to "waggle" the brightness level at 200mS intervals, increasing and then decreasing it to where it should be. Less than 200mS doesn't work, and I have to change it and change it back again, presumably because Homebridge discards duplicate values.

Is this a known bug? Is there a better workaround?

Many thanks.

**Environment:**

* **Node.js Version**: v14.15.5
* **NPM Version**: v6.14.11
* **Homebridge Version**: v1.3.0
* **Operating System**: macOS 11.2.1
* **Process Supervisor**: none

**Comment by theouitdenwaal** [comment]
I'm having the same issue with different integrations (Hue, IKEA, Wiz).

**Comment by NorthernMan54** [comment]
This is a plugin/device issue and not a homebridge issue.  I have both the homebridge-hue and homebridge-tasmota plugins and turning off and on a light maintains the level of brightness.

**Comment by ebaauw** [comment]
There is a bug in iOS 16.4: Home shows 100% brightness when a light is on, with 0% brightness.  Other HomeKit apps show the correct brightness.

Also, Home sometimes doesn't seem to refresh the accessory state.  Not sure if that's a "feature" of the new HomeKit architecture, where the device running Home no longer connects directly to your accessories (i.c. Homebridge); you might try and restart your home hub.  Anyways, close and re-open the app to make sure it shows the actual accessory state.
