### ISSUE TITLE
Restart child bridge from cmd 

### ISSUE THREAD

**Issue by WojtekWro** [homebridge/homebridge#2852]
Hi, 
Is there a chance to restart child bridge using cmd?
One of my accessories on child bridge tends to freeze. Restart of child bridge solves the problem. I would like to automatise this procedure.

**Comment by NorthernMan54** [comment]
If you use 

ps -ef | grep homebridge

it will show each child and the plugin name so you can kill it

**Comment by WojtekWro** [comment]
This is not I have expected. 
Each time process id is different so it's not possible to us this automatically.

**Comment by oznu** [comment]
On Linux systems systems, you can run:

```
kill -15 $(pidof 'homebridge: homebridge-dummy')
```

Replace `homebridge-dummy` with the name of the plugin.

**Comment by IMNotMax** [comment]
Hi, as usual, amazing work ! Thanx !
Works great, but a more user friendly solution should be great too for all users testing configs (as I am with my tizen TV... lot of restarts :) )
May be a feature request ???

**Comment by donavanbecker** [comment]
@IMNotMax why not just use Homebridge UI to make the easy restart?

**Comment by IMNotMax** [comment]
Because I don't want to restart all the plugins everytime. Child bridges are an excellent (amazing !) solution for testing config and isolating "unstable" plugings.
That's why "isolating" the restart could be a great function... i think ;)

**Comment by donavanbecker** [comment]
@IMNotMax on the Homebridge UI, this is an option to restart only the child bridges.
<img width="594" alt="Screen Shot 2021-03-04 at 4 18 54 PM" src="https://user-images.githubusercontent.com/9875439/110038397-52a84500-7d05-11eb-8800-881bce0c7de2.png">

**Comment by IMNotMax** [comment]
Can you give me a clue where to find this interface ? (everything is up to date on my container and I still can't find this !)

**Comment by donavanbecker** [comment]
<img width="199" alt="Screen Shot 2021-03-04 at 4 43 29 PM" src="https://user-images.githubusercontent.com/9875439/110040638-c26bff00-7d08-11eb-894d-f4433594c64c.png">
<img width="830" alt="Screen Shot 2021-03-04 at 4 43 41 PM" src="https://user-images.githubusercontent.com/9875439/110040737-e0d1fa80-7d08-11eb-904e-03f1001fe107.png">

**Comment by IMNotMax** [comment]
Thanx for your patience :)
