### ISSUE TITLE
Wind Sensor Service type needed

### ISSUE THREAD

**Issue by modellbobby** [homebridge/homebridge#2853]
We need a Wind Sensor (km/h) service type in homebridge please to implement sensors of multiple wind measure kits like Rademacher Umweltsensor etc.

https://developers.homebridge.io/#/characteristic/
Here we need service type "Wind Speed Sensor"

Netatmo has published a wind sensor compatible with Homekit so I think there is a device type in Homekit for a wind sensor now.

Product: https://www.apple.com/de/shop/product/HNTJ2ZM/A/smarter-windmesser-von-netatmo

Dev API for reference : https://dev.netatmo.com/apidocumentation/weather#product-details

**Comment by nscheffer** [comment]
I got the Netatmo weather station with the wind sensor and rain gauge with the station certified with Apple Home Kit.
Unfortunately the wind sensor and rain gauge are both unsupported natively on Homekit.

**Comment by modellbobby** [comment]
This is strange. I see an implementation in homebridge weather plus where they use the occupancy sensor to send wind speed data. Pretty hack. Maybe we can re use this idea. Have a look in the implementation. Honestly i don’t understand it as I thought only 0,1 can be set. But they managed it somehow.

**Comment by martind1983** [comment]
any news on this one?
