### ISSUE TITLE
 gAfter update to 1.3.0 and aboveoogle home cannot recognise lamp status anymore

### ISSUE THREAD

**Issue by Micha-123** [homebridge/homebridge#2861]
hi, if i update homebridge to 1.3.0 or above, google home cannot recognise the actual status of lights anymore, in the homebridge app is the state of lights always correct, but in the google home app it dont shows the staus anymore, also if i ask "which lights are still on"it says it cannot connect to the lights, but i can turn the lights on and off as wel within  google home, but only the status wil be not given in the home app. 

im reverted to 1.2.5 and now the light status is also working within the google home app.

**Comment by balddaddy33015** [comment]
My story goes that I woke up this morning, turned on light via Home, saw that there was an iOS update, hit download, went back to Home and nothing was HB responding. 

I ended up doing a bunch of troubleshooting (couldn't tell you all that I did), and didn't find a fix. 

When the iOS update was ready I installed it and then everything was back to normal.

**Comment by crouchingtiger** [comment]
Suggest you try the latest beta. Boolean logic had an issue. See #2855

**Comment by oznu** [comment]
See same issue: https://github.com/oznu/homebridge-gsh/issues/103

I'll take care of it soon.
