### ISSUE TITLE
Homepod  mini not working with Homebridge devices but iPhone does work 

### ISSUE THREAD

**Issue by wroblewski6** [homebridge/homebridge#2862]
**Describe The Bug:**
I bought recently Homepod Mini and I connected it to my home. 
I can control my Homekit native devices via HomePod but when I want to control Homebridge devices via HomePod I get " oh oh something is wrong, please try again".
I tried to reinstall Homebridge on new sd card and problem is the same. 
I use TPlink m4 mesh system and all devices are connected and works with out any problem. 
I came across  this issue #2782 https://github.com/homebridge/homebridge/issues/2782?fbclid=IwAR29UP11aGwKqdhxGCruUa1Ksqf6MArcVaWB4l5LK35Go1StDMHRXXv_l34 
and the problem seems to be similar but changing mdns settings did not  help me. 

i have 2 Apple TV and 1 HomePod an I disconnected my Apple TV to make my HomePod my accessory center. 

The issue make my HomePod useless so please help me to solve this issue 

**To Reproduce:**
command on HomePod 
hey Siri turn on sofa 

**Expected behavior:**
Turning on the sofa light 

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```{
    "mdns": {
        "interface": "192.168.1.200"
    },
    "bridge": {
        "name": "Homebridge BB00",
        "username": "0E:D4:73:.........0",
        "port": 51940,
        "pin": "2........2",
        "advertiser": "ciao",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [
        {
            "name": " Robot",
            "ip": "192.168.1.141.....
....
....
....

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**
RPI 3 B+ 
* **Node.js Version**: <!-v14.16.0->
* **NPM Version**: <v7.6.1 ->
* **Homebridge Version**: <v1.3.2 also tried 1.3 or 1.19 >
* **Operating System**: Raspbian Homebridge image 
* **Process Supervisor**: Homebridge image 

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by wroblewski6** [comment]
THis is also similar issue https://github.com/homebridge/homebridge/issues/2795 but did not find solution

**Comment by wroblewski6** [comment]
after update to homebridge 1.3.3 I have still the same issue

**Comment by wroblewski6** [comment]
Is domenie else has the same issue  or this issue is only on my HomePod ??

**Comment by Ayngush** [comment]
I ran with version v1.2.x into same issue: Can't control devices with HomePod Mini but with my iPhone / iPad. 
Fall back to version v1.1.7 works for me.

**Comment by wroblewski6** [comment]
> I ran with version v1.2.x into same issue: Can't control devices with HomePod Mini but with my iPhone / iPad.
> Fall back to version v1.1.7 works for me.

I tried 1.1.6 and 1.1.0 bit still the same. 
in my homebridge i can not find  version 1.1.7  . 
all in All the problem start to be anoying

**Comment by amarce** [comment]
Hi,

I had a similar problem on 1.2 and it was fixed by removing all the filters on my unifi AP deployment. The filters were filtering out bonjour traffic (the IGMP snooping settings on manageable switches also seems to filter out bonjour).

since I’ve updated to 1.3 the problem seems to repeat. Everything works perfect on IOS but sometimes it does not on HomePod mini. The “only” related thing that seems to be changed is the bonjour server, so I’ve switched back from ciao to the previous one right now and I’ll check if this cures the issue.

If this works for me I’ll let you know so you can check your AP’s settings

**Comment by tohubgit** [comment]
My HomePod minis are working flawlessly with Homebridge version 1.1.7., never had a problem with this setup.
Do you use VLANs in your network, @wroblewski6? If so, make sure that mDNS traffic is able to pass across those VLANs. With Unifi devices e.g. you have to turn on mDNS service (mDNS reflector).
