### ISSUE TITLE
Homebridge not running after update from v1.2.5, no error log output, through v1.3.1 to v1.3.3.

### ISSUE THREAD

**Issue by elfive** [homebridge/homebridge#2868]
**Describe The Bug:**
Homebridge stopped working after I update homebridge from v1.2.5 to v1.3.1/v1.3.2/v1.3.3 (v1.3.0 not tested).

**To Reproduce:**
1. freash install homebridge version 1.3.1-1.3.3 on my raspberry pi 3b+;
2. install plugin and configure it: 
```
npm i homebridge-petkit-feeder-mini
```
3. restart homebridge

**Expected behavior:**
homebridge running like what it did at version 1.2.5

[**Logs:**]()
[11/03/2021, 03:30:28] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[11/03/2021, 03:30:28] [HB Supervisor] Started Homebridge v1.3.3 with PID: 3977
Initializing HAP-NodeJS v0.9.3...
[11/03/2021, 03:30:31] Loaded config.json with 1 accessories and 1 platforms.
[11/03/2021, 03:30:32] Loaded 0 cached accessories from cachedAccessories.
[11/03/2021, 03:30:32] ---
[11/03/2021, 03:30:35] Loaded plugin: homebridge-config-ui-x@4.40.0
[11/03/2021, 03:30:35] Registering platform 'homebridge-config-ui-x.config'
[11/03/2021, 03:30:35] ---
[11/03/2021, 03:30:35] Loaded plugin: homebridge-petkit-feeder-mini@1.10.4
[11/03/2021, 03:30:35] Registering accessory 'homebridge-petkit-feeder-mini.petkit_feeder_mini'
[11/03/2021, 03:30:35] ---
[11/03/2021, 03:30:35] Loaded plugin: homebridge-raspberry-simplegpio@1.2.0
[11/03/2021, 03:30:35] Registering accessory 'homebridge-raspberry-simplegpio.raspberry_simple_gpio'
[11/03/2021, 03:30:35] ---
[11/03/2021, 03:30:35] Loading 1 platforms...
[11/03/2021, 03:30:35] [Config] Initializing config platform...
[11/03/2021, 03:30:35] [Config] Running in Service Mode
[11/03/2021, 03:30:35] Loading 1 accessories...
[11/03/2021, 03:30:35] [PetkitFeederMini] Initializing petkit_feeder_mini accessory...
[11/03/2021, 03:30:35] [PetkitFeederMini] begin to initialize petkit feeder mini.
[11/03/2021, 03:30:35] [PetkitFeederMini] header set X-Session should equal to header set F-Session, replace F-Session.

**Homebridge Config:**
```
{
    "bridge": {
        "name": "Homebridge Rasp3B",
        "username": "0E:31:E1:CA:18:5E",
        "port": 51191,
        "pin": "382-44-443",
        "advertiser": "ciao"
    },
    "accessories": [
        {
            "name": "PetkitFeederMini",
            "DropMeal_name": "DropMeal",
            "MealAmount_name": "MealAmount",
            "FoodStorage_name": "FoodStorage",
            "DesiccantLevel_name": "DesiccantLevel",
            "ManualLock_name": "ManualLock",
            "LightMode_name": "LightMode",
            "Battery_name": "Battery",
            "location": "cn",
            "headers": [
                {
                    "key": "X-Session",
                    "value": "*****=====hide personal information=====*****"
                }
            ],
            "autoDeviceInfo": false,
            "sn": "PetkitFeederMini",
            "firmware": "1.0.0",
            "manufacturer": "Petkit",
            "model": "Petkit feeder mini",
            "enable_polling": true,
            "polling_interval": 60,
            "enable_desiccant": false,
            "alert_desiccant_threshold": 7,
            "enable_autoreset_desiccant": false,
            "reset_desiccant_threshold": 5,
            "enable_manualLock": false,
            "enable_lightMode": false,
            "reverse_foodStorage_indicator": false,
            "fast_response": false,
            "accessory": "petkit_feeder_mini"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/12877854/110731553-84696080-825d-11eb-9df3-3dc58c9cf11a.png)
![image](https://user-images.githubusercontent.com/12877854/110733744-7289bc80-8261-11eb-81fa-521a66e66dd6.png)

**Environment:**

* **Node.js Version**: v14.15.4/v14.15.5/v14.16.0
* **NPM Version**: v7.5.2
* **Homebridge Version**: v1.2.5/v1.3.1/v1.3.2/v1.3.3
* **Operating System**: Raspbian GNU/Linux Buster (10)
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
I can't see anything in your code after the last log like that would prevent it reaching the end of the "getServices" method.

https://github.com/elfive/homebridge-petkit-feeder-mini/blob/master/index.js#L224

As the plugin developer, you're in the best position to debug this and work out where the your plugin code stops working. If you can find a bug, we'll happily fix it.

**Comment by elfive** [comment]
after some digging, I found the problem is node js thread was stucked at this line:
https://github.com/elfive/homebridge-petkit-feeder-mini/blob/master/index.js#L452

deasuncPromise is a 3rd-party library([deasync-promise](https://www.npmjs.com/package/deasync-promise)), which `Transforms async functions into sync with promise API`

I did not know what exactly Homebridge changed from v1.2.5 to v1.3.x to make this library not working any more.
Even worse I cannot find a substitute to the library...
It would be very helpful If you guys offer some help and look into this issue, and I think this may also the key to this issue: #2834 .

I use this library or it's functions to fetch some important information from the server in the plugin constructor() and getService() function, which can not use the await keyword to synchronize the http request.

**Comment by oznu** [comment]
I've compared the getServices() part of 1.1, 1.2.5 and 1.3.1 and can't see any functional difference.

1.2.5:

Constructor called:
https://github.com/homebridge/homebridge/blob/v1.2.5/src/server.ts#L355-L358
getServices() called:
https://github.com/homebridge/homebridge/blob/v1.2.5/src/server.ts#L447-L448

1.3.1:

Constructor called:
https://github.com/homebridge/homebridge/blob/v1.3.1/src/server.ts#L290-L293
getServices() called:
https://github.com/homebridge/homebridge/blob/v1.3.1/src/bridgeService.ts#L441-L442

Both act synchronously and there is no code executed between the `constructor` and `getServices` method in either 1.2.5 or 1.3.1 that may have been slowing things down.

**Comment by oznu** [comment]
I also tried copying the entire accessory loader function into the 1.3.x code base and can still replicate the issue you are facing.

Moving to a dynamic platform would be the best solution, as using `de-async` in the constructor isn't really good.

**Comment by elfive** [comment]
It seems no other way but moving to a dynamic platfrom, It may take some time to migrate, currently I can only suggest plugin users not update homebridge to version 1.3.x.

but still I hope you could find and fix the "bug".

**Comment by oznu** [comment]
> but still I hope you could find and fix the "bug".

While i have found the cause, the "bug" is in the `deasync-promise` library.

For whatever reason, if any promise is called before your plugin uses `deasync-promise`, then `deasync-promise` gets stuck and prevents further loading.

As you can see here we use `await` to load the cached accessories (v1.2.5 did not).

https://github.com/homebridge/homebridge/blob/master/src/server.ts#L153

This method is working as expected and all its promises are resolved before proceeding to the next step.

In fact, I was able to replicate the same "getting stuck" behaviour just by commenting out that line and replacing it with a simple timeout promise:

```ts
await new Promise(resolve => setTimeout(resolve, 2000));
```

**Comment by elfive** [comment]
That's great.
I currently working on two ways:
1. moving to dynamic platform
2. try to find a solution to solve this bug.
you did helped a lot, thank you!
