### ISSUE TITLE
CPU frequence increasing on Raspberry Pi 

### ISSUE THREAD

**Issue by bondskin** [homebridge/homebridge#2874]
Since 1.3 I see a constant growth of CPU frequency of my Raspberry Pi 4

<img width="529" alt="Bildschirmfoto 2021-03-15 um 15 48 48" src="https://user-images.githubusercontent.com/55050117/111174070-6e360a00-85a7-11eb-87f2-4b568174ade8.png">

A restart of the Raspbian OS resets the frequency and it starts again

**Describe The Bug:**
Over time the CPU frequency of my Raspberry Pi 4 is constantly increasing.
A reboot fixes the issue but it starts again.
This was introduced when I switched to homebridge 1.3.x

**Expected behavior:**
Remain CPU frequency on a regular level

**Environment:**

* **Node.js Version**: 14.6.0
* **NPM Version**: 7.6.1
* **Homebridge Version**: 1.3.3
* **Operating System**: Raspbian 
* **Process Supervisor**: hb-service

**Comment by ebaauw** [comment]
Your expectation is wrong.  The Pi throttles CPU speed when it gets hot, or when it has nothing much to do.

https://www.raspberrypi.org/documentation/hardware/raspberrypi/frequency-management.md

**Comment by bondskin** [comment]
@ebaauw my expectation is that the CPU frequency does not go constantly up (as it was before)

And I did reboot the device, so I know why it went down

**Comment by ebaauw** [comment]
So you're saying all the drops as of week 8 are due to restarts?  Do memory usage, system load, and CPU temperature also increase constantly after each restart?  If it's only the frequency, I really wouldn't worry, even if it is on a constant 1.5 GHz.  My five Pi 4B-s tend to switch frequency all the time, from 700 to 1500 MHz, and values in between.  I'm afraid I don't collect historic data.

**Comment by bondskin** [comment]
I am saying that the *constant increase* of CPU frequency started with homebridge 1.3.x
I am worried because this is new and abnormal behaviour which does not occur on other PIs without homebridge.

**Comment by bondskin** [comment]
upgrade auf v1.3.4 fixed it
<img width="533" alt="Bildschirmfoto 2021-03-18 um 10 03 41" src="https://user-images.githubusercontent.com/55050117/111600078-4f1ac080-87d1-11eb-8717-fc6654734dc0.png">

<img width="533" alt="Bildschirmfoto 2021-03-18 um 10 03 55" src="https://user-images.githubusercontent.com/55050117/111600095-5510a180-87d1-11eb-85b3-24ad562820e9.png">
