### ISSUE TITLE
Homebridge CURL commands not working anymore

### ISSUE THREAD

**Issue by smartystudios** [homebridge/homebridge#2876]
A few weeks back I used CURL commands like this:

curl -X PUT http://IP:PORT/characteristics --header "Content-Type: application/json" --header "authorization: XXX-XX-XXX" --data '{"characteristics":[{"aid":2,"iid":10,"value":"true"}]}'
to set various data in homebridge; for example turning switches or lightbulbs on to go hand-in-hand with some Terminal based automation I have set up.

This CURL worked until I updated homebridge and all my plugins recently. The switches/bulbs work fine from Homebridge and Homekit, so it's not a problem with them. The error is returns is 70410, which in the error code for this "INVALID_VALUE_IN_REQUEST" which from what I can see is caused by "data.length" equalling 0. Any ideas?

File I found to determine my debugging so far: https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/HAPServer.ts

**Comment by NorthernMan54** [comment]
The recent versions validate that the values align with the HomeKit spec.  So you need to use 1 rather than true for this.  To find the correct values please review apples published home accessory protocol spec.

**Comment by smartystudios** [comment]
THANK YOU

You are my new favourite person
