### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by mbierman** [homebridge/homebridge#2877]
**Describe Your Problem:**
I was trying to use the homebridge APIs (/api/status/homebridge-version and /api/status/server-information) in the Swagger UI and they fail. The error is 401 Error: Unauthorized but there is no way to put in credentials and I am already logged in to homebridge in the same browser. :slight_smile:  I tried using curl and including a valid token and that failed too. Am I missing something or is this a bug?

[**Logs:**]()

![image](https://user-images.githubusercontent.com/1205471/111691956-176d4200-87ec-11eb-8d33-839c8a548256.png)

```json
NA
```

**Screenshots:**
see above. 

**Environment:**

**Homebridge Config:**
* **Node.js Version**: 14.16.0
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.3.4
* **Homebridge Config UI X Version**: v4.40.0
* **Operating System**: Docker
* **Process Supervisor**: Docker 
* **Alpine Linux**:3.12.4

**Comment by mbierman** [comment]
Never mind, I figured out the issue.

**Comment by casuallyexisting** [comment]
How did you fix it? Also pro tip for the future, when you figure out the solution to your problem, put it in the issue so others can find it.

**Comment by mbierman** [comment]
I believe I had not signed in at the top of the swagger UI.
