### ISSUE TITLE
Advertising more than just HAP

### ISSUE THREAD

**Issue by AssetBurned** [homebridge/homebridge#2878]
**Describe The Bug:**
When looking at the Bonjour messages send out by the Homebridge installation, only HAP is advertised.

**Expected behavior:**
Homebridge offers more interfaces (HTTP and SSH) as well as some optional services such as DNS. These services should also be announced via the bonjour announcements.

**Comment by oznu** [comment]
Homebridge does not provide an SSH service, the underlying operating system does.

**Comment by AssetBurned** [comment]
Correct, sorry for being unclear there. Still would be nice to easily spot the device as well.
