### ISSUE TITLE
DHCP reserve IP setting

### ISSUE THREAD

**Issue by hill5408** [homebridge/homebridge#2879]
I have been installed homebridge on my iMac, but I found that the wifi device need static IP to connect  homebridge for stabilities. so how can I use MacOS commented  line to set my AP router in DHCP mode reserve IP for the other wifi device?

**Comment by oznu** [comment]
This needs to be done on your router, and is not something Homebridge controls.

Exactly how you do it on your own router depends on the brand and model, I suggest googling "how to set reserved IP on <brand> <model> router".
