### ISSUE TITLE
Broalink Air Quality (A1)

### ISSUE THREAD

**Issue by rucanunes** [homebridge/homebridge#2880]
Hello,

I have 3 Broalink Air Quality (A1) sensors. Is there anyone who knows how to integrate them in Homebridge?
I've found these two nut I think that they are no finished projects:

https://www.npmjs.com/package/homebridge-broadlink-a1
https://www.npmjs.com/package/homebridge-http-airquality

[https://www.google.com/url?sa=i&url=https%3A%2F%2Fpt.aliexpress.com%2Fitem%2F32680088457.html&psig=AOvVaw3GrXUN13HQBH-JTlOgLSb-&ust=1616415132254000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJiplN-twe8CFQAAAAAdAAAAABAD](url)

**Comment by rucanunes** [comment]
Anyone please?

**Comment by oznu** [comment]
You might find someone who knows on the Homebridge Reddit or Discord server. GitHub issues are more for bug reports etc.
