### ISSUE TITLE
hb-service: move log file

### ISSUE THREAD

**Issue by boehser-enkel** [homebridge/homebridge#2881]
Hi there,

I'm running hb-service @ /var/lib/homebridge.
How do is move homebridge.log to /var/log?

kind regards,
boehser enkel

**Comment by oznu** [comment]
This cannot be done with `hb-service`, it is a design decision that allows us to have the same setup across multiple platforms (Linux, macOS and Windows).

You can still run Homebridge without `hb-service`, and then you can configure your systemd unit file to save the log wherever you like:

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian,-Debian-or-Ubuntu-Linux-%5BNo-UI%5D

Note the features listed here will not be available when not running with `hb-service`:

https://github.com/oznu/homebridge-config-ui-x/wiki/Homebridge-Service-Command#features

**Comment by boehser-enkel** [comment]
Wow i did not expect that. Is it possible to make a syslink?

**Comment by oznu** [comment]
You can try a symlink, I don't see why that wouldn't work.

**Comment by oznu** [comment]
This seems to work:

```
rm -f /var/lib/homebridge/homebridge.log
touch /var/log/homebridge
sudo ln /var/log/homebridge /var/lib/homebridge/homebridge.log
sudo chown homebridge: /var/lib/homebridge/homebridge.log
```

Replace the `chown` user with the user you run homebridge as.

Then restart:

```
sudo hb-service restart
```

**Comment by boehser-enkel** [comment]
Thnks for the solution, but 
'sudo ln /var/log/homebridge /var/lib/homebridge/homebridge.log'
brings me:
'ln: failed to create hard link '/var/lib/homebridge/homebridge.log' => '/var/log/homebridge': Invalid cross-device link
'
