### ISSUE TITLE
Multiple InputSource wheel

### ISSUE THREAD

**Issue by carlosgamezvillegas** [homebridge/homebridge#2882]
Hello guys, I am working on a plugin for a Blu-ray. The category of the plugin is set to Television and I have the InputSource mapped to the inputs of the Blu-ray. I would like to add the ability to select the subtitles and the audio from the plugin. Is there a way to add a separate InputSourse-like wheel to select subtitles and audio?

**Comment by NorthernMan54** [comment]
@carlosgamezvillegas Unfortunately not
