### ISSUE TITLE
Can't get remote access to Homekit after update

### ISSUE THREAD

**Issue by gjniewenhuijse** [homebridge/homebridge#2883]
I updated my homebridge to the latest version (1.3.4) with a ciao backend.

Locally it works perfect, but remote (with appletv 4hd  hub latest version 14.4) i can't get connected. 

Is this a know bug or how to solve this?

**Comment by BjornvanSchie** [comment]
I personally think this is an issue with the homekit version running on the appletv 4hd hub, which is also the device that handles remote control. Could you check if non homebrige related accessoires are still functioning remote? I personally dont have any remote issues, i'll check my versions later today 👍

**Comment by gjniewenhuijse** [comment]
You're right, its not a Homebridge issue i see, because my devices from the Hue bridge are also broken. I check my apple tv

**Comment by gjniewenhuijse** [comment]
solved: two installation with the same problem and same solution.

Apple tv updating or changing settings doesn't work. So i added a Ipad as Hub and then my Apple tv works also as Hub again. Also after disabling the  Ipad as hub.
