### ISSUE TITLE
HeaterCooler accessory doesn't show fan speed control in Home app

### ISSUE THREAD

**Issue by maisun** [homebridge/homebridge#2884]
Hi,
I'd like to ask for some help here recently I notice that my HeaterCooler accessory stops showing the fan speed control in Home app. I'm not 100% sure if it has anything to be with 1.3 as I don't use it rarely, but I saw the control prior to HomeBridge 1.3 so might just ask the question here and hopefully get some suggestion where to look. 
The fan speed control is also not in HomeBridge UI, but the setting shows the rotation speed is there and the number looks correct:
<img width="295" alt="Screen Shot 2021-03-25 at 09 53 22" src="https://user-images.githubusercontent.com/5745785/112445997-07a3af80-8d50-11eb-9c63-bbf31c294f27.png">
<img width="797" alt="Screen Shot 2021-03-25 at 09 53 49" src="https://user-images.githubusercontent.com/5745785/112446006-0a060980-8d50-11eb-8036-33639d6261fe.png">
I also checked Eve app and I can see "Rotation Speed" control there and work as expected. So now I'm puzzled why rotation speed control isn't in Home app. Any suggestion is appreciated!

**Comment by oznu** [comment]
It's shown on my heater cooler. You need to go to the accessory settings to see it though.

**Comment by maisun** [comment]
> It's shown on my heater cooler in the Home App. You need to go to the accessory settings to see it though.
> 
> ![A0E21974-14FF-4D10-82C8-AA39DF882B3A](https://user-images.githubusercontent.com/3979615/112551637-6ed76780-8e15-11eb-99f5-9ce4e0d35db8.jpeg)

Hi thanks, it’s not shown in homebridge UI (pls see the screenshot) either, is it suppose to show there?

**Comment by oznu** [comment]
Correct, the Homebridge UI doesn't implement this characteristic for HeaterCooler. You can still see the value it's set to when looking at the "Rotation Speed".
