### ISSUE TITLE
App for Android tablet...

### ISSUE THREAD

**Issue by rucanunes** [homebridge/homebridge#2886]
Hello,

I would like to place an old tablet that I have on my kitchen with some of my switches and shutters displayed.
Something like this: [https://play.google.com/store/apps/details?id=app.homehabit.view](url)

Iknow that we have the "homebridge-display" plugin but the widgets are not showing (I use mostly mqtt).

Thank you!

**Comment by NorthernMan54** [comment]
@rucanunes If you use MQTT have you looked into node-red and its dashboard nodes ?  This is something I have been playing with lately

![image](https://user-images.githubusercontent.com/19808920/112662769-73f4e080-8e2e-11eb-9dc5-b84f8bfef224.png)

**Comment by rucanunes** [comment]
Node-red it's a bit complicated. I was searching for something like the link I posted.

**Comment by oznu** [comment]
You can access the Homebridge UI on an android tablet and organise either the Accessories tab or the dashboard to suit your requirement. Most popular accessory types can be controlled through this web interface.
