### ISSUE TITLE
Homebridge disrupting esp-homekit accessory

### ISSUE THREAD

**Issue by maccoylton** [homebridge/homebridge#2889]
I write accessories using the esp-homekit library, recently I have noted accessories going "not responding" every time I restart homebridge. Debugging my accessories I see a connection coming for hombridge

>>> homekit_client_process: [Client 3] Got 142 incoming data
Not encrypted data (142 bytes): "GET /accessories HTTP/1.1\x0D\x0AAccept: application/json, text/plain, */*\x0D\x0AUser-Agent: axios/0.21.1\x0D\x0AHost: 192.168.1.54:5556\x0D\x0AConnection: close\x0D\x0A\x0D\x0A"

While the esp-homekit library should be able to disregard this unsolicited message without causing impact to the accessory, equally why is homebridge sending this message in the first place, to an accessory to which is it not paired?

I'm running the home bridge-zigbee-nt accessory v 2.2.2 on the following environment

**Environment:**

* **Node.js Version**: v14.15.4
* **NPM Version**: v6.14.10
* **Homebridge Version**: 1.3.4
* **Operating System**: Raspbian 10
* **Process Supervisor**:  hb-service

**Comment by rjduncan564** [comment]
lol

**Comment by NorthernMan54** [comment]
@maccoylton this is homebridge-ui asking your esp-HomeKit device for the details of your accessory to include in the ui.

I would classify this as a defect in esp-HomeKit as it can’t protect itself from a simple web request.  Hopefully you raised this against esp-HomeKit and they are working to resolve it or even better supported the request.

going to close this as it is not a defect, but a feature.

**Comment by maccoylton** [comment]
@NorthernMan54 The hombridge-ui should not be asking accessories it is not paired to for details, and the get accessories message should not contain a "Connection: Closed"  per the HAP specification, section 5

FYI I have already fixed the esp-homekit code and sent a pull request for that end.
