### ISSUE TITLE
hb-service update-node not working on Debian 10

### ISSUE THREAD

**Issue by kaganae** [homebridge/homebridge#2890]
I did a fresh install of homebridge on a new Debian 10 instance (fresh Debian 10 install). The install (following the standard instructions from the homebridge GitHub site), resulted in applying node.js v10.24.0. I followed this process:

# setup repo
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -

# install Node.js
sudo apt-get install -y nodejs gcc g++ make python net-tools

Although everything is working, there are warnings in my log that my plugins require node.js v14.16.0 (LTS). 

I have tried to update node.js using the hb-service command and it says that it is installing v14.16.0, but, when I run node -v after, it remains v10.24.0. I have also tried to restart the Debian server to see if that helped, but it stays at v10.24.10.

alkagan@debian-vm:/$ node -v
v10.24.0

alkagan@debian-vm:/$ sudo hb-service update-node
ℹ Updating Node.js from v10.24.0 to v14.16.0...
ℹ Updating from NodeSource...

## Populating apt-get cache...

+ apt-get update
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://deb.debian.org/debian buster-updates InRelease                                                              
Hit:3 http://security.debian.org/debian-security buster/updates InRelease                                                
Hit:4 https://deb.nodesource.com/node_14.x buster InRelease                                                              
Hit:5 https://dl.yarnpkg.com/debian stable InRelease                                               
Reading package lists... Done

## Confirming "buster" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_14.x/dists/buster/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee /usr/share/keyrings/nodesource.gpg >/dev/null

## Creating apt sources list file for the NodeSource Node.js 14.x repo...

+ echo 'deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x buster main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x buster main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease                                                                                                         
Hit:3 http://deb.debian.org/debian buster-updates InRelease                                                                                                 
Hit:4 https://deb.nodesource.com/node_14.x buster InRelease                                                                                                 
Hit:5 https://dl.yarnpkg.com/debian stable InRelease                                              
Reading package lists... Done

## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn

Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (10.24.0~dfsg-1~deb10u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
ℹ Rebuilding for Node.js v14.16.0...
rebuilt dependencies successfully
rebuilt dependencies successfully
✔ Rebuilt modules in /usr/local/lib/node_modules/homebridge-config-ui-x for Node.js v10.24.0.
ℹ Restarting Homebridge Service...
✔ Homebridge Restarted

alkagan@debian-vm:/$ node -v
v10.24.0

**Comment by oznu** [comment]
You probably have multiple copies of Node.js install. One at `/usr/local/bin/node` and another at `/usr/bin/node`.

Check:

```
/usr/local/bin/node -v 
/usr/bin/node -v
```

How to fix: https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux

**Comment by Nbr1Sniper** [comment]
I have the same issue however I only have one file. 10.24.0.... I have tried forcing to 14 and it won't work:

nodejs is already the newest version (10.24.0~dfsg-1~deb10u1).

**Comment by bradrhoad** [comment]
Having the same issue. I performed the fix and reinstalled. checked for multiple installs using **/usr/bin/node -v** and **/usr/local/bin/node -v** but only /usr/bin/node is showing an install (v10.24.0). Any other thoughts? Thanks!
