### ISSUE TITLE
Homebridge service crash every 3~4 days

### ISSUE THREAD

**Issue by jonpeng** [homebridge/homebridge#2891]
**Describe Your Problem:**

Homebridge service takes about 0.08 GB more memory every day. And the service crashes in the 3rd or the 4th process day.
[**Logs:**]()
[2021-04-03, 7:08:02 p.m.] [SmartThings] Change Event: (Main Floor Bathroom) [TEMPERATURE] is 21
[2021-04-03, 7:08:39 p.m.] [SmartThings] Change Event: (Laundry room) [TEMPERATURE] is 20.1

<--- Last few GCs --->

[767:0x4806050] 295365959 ms: Scavenge 220.7 (233.8) -> 220.3 (233.8) MB, 2.6 / 0.0 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
[767:0x4806050] 295381831 ms: Scavenge 220.8 (232.3) -> 220.4 (233.0) MB, 6.5 / 0.1 ms  (average mu = 1.000, current mu = 1.000) allocation failure 
[767:0x4806050] 295382988 ms: Mark-sweep 220.8 (232.5) -> 212.8 (233.0) MB, 127.5 / 0.9 ms  (average mu = 1.000, current mu = 1.000) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory

**Homebridge Config:**
{ "bridge": {
        "name": "Homebridge AA",
        "username": "0E:B8:DD:26:AA:xx",
        "port": 512xx,
        "pin": "570-54-4xx",
        "advertiser": "ciao"
    },
"accessories": [
        {
            "accessory": "Volvo"
        }
    ],
    "platforms": [
        {
            "platform": "config"
        },
        {
            "platform": "orbit",
            "name": "orbit"
        },
        {
            "name": "TplinkSmarthome",
            "platform": "TplinkSmarthome"
        },
        {
            "name": "SmartThings",
            "platform": "SmartThings"
        },
        {
            "name": "myQ",
            "platform": "myQ"
        },
        {
            "name": "TuyaWebPlatform",
            "platform": "TuyaWebPlatform"
        },
        {
            "platform": "homebridge-magichome-dynamic-platform"
        },
        {
            "name": "SwitchBot",
            "platform": "SwitchBot"
        },
        {
            "platform": "BroadlinkRM",
            "name": "BroadlinkRM",    
        }
    ]
}

**Screenshots:**

![Capture1](https://user-images.githubusercontent.com/48269361/113731925-648b5800-96b6-11eb-9adc-d4f2498c5bb8.JPG)
![Capture2](https://user-images.githubusercontent.com/48269361/113731936-681edf00-96b6-11eb-9ff2-e2c84b8824d3.JPG)
![Capture3](https://user-images.githubusercontent.com/48269361/113731950-6b19cf80-96b6-11eb-9a45-1f48509cd8e6.JPG)
![Capture4](https://user-images.githubusercontent.com/48269361/113731958-6ce39300-96b6-11eb-8176-f65a0f89d71a.JPG)
![Capture5](https://user-images.githubusercontent.com/48269361/113731966-6ead5680-96b6-11eb-8929-6022941abe74.JPG)
![Capture6](https://user-images.githubusercontent.com/48269361/113731988-710fb080-96b6-11eb-8b83-dac4c8aaab85.JPG)
![Capture7](https://user-images.githubusercontent.com/48269361/113732005-74a33780-96b6-11eb-8400-4dab0917cf22.JPG)
![Capture8](https://user-images.githubusercontent.com/48269361/113732013-766cfb00-96b6-11eb-901e-e48d49c508f3.JPG)
![Capture9](https://user-images.githubusercontent.com/48269361/113732044-7bca4580-96b6-11eb-94d1-7fadc1d693b4.JPG)
![Capture10](https://user-images.githubusercontent.com/48269361/113732053-7d940900-96b6-11eb-9189-188fea230e2f.JPG)
![Capture11](https://user-images.githubusercontent.com/48269361/113732129-8dabe880-96b6-11eb-8edd-8482d6498c03.JPG)
![Capture12](https://user-images.githubusercontent.com/48269361/113735085-23487780-96b9-11eb-9eec-56fb0dbc6a82.JPG)

**Environment:**

* **Node.js Version**: v14.16.0
* **NPM Version**: 
* **Homebridge Version**: v1.3.4
* **Operating System**: Raspbian
* **Process Supervisor**:  hb-service

**Comment by martinnock** [comment]
I can second this in general on 
- a Pi 3 with 1 GB RAM with the official Homebridge Image
- Node.js Version: v14.16.0
- Homebridge Version: v1.3.4
- Operating System: Raspbian
- Process Supervisor: hb-service

Not sure about the exact decrease of RAM, but once the free RAM hits close to 0, the Pi and Homebridge get stuck and only a restart helps. No freeing up of memory and also the disk swap doesn't seem to help.

**Comment by oznu** [comment]
> Homebridge service takes about 0.08 GB more memory every day. And the service crashes in the 3rd or the 4th process day.

To figure this out you will need to isolate each plugin, running one at a time.

**Comment by martinnock** [comment]
I activated the swap file, it wasn't working somehow. This helped me along for a while, though it's running full, too.

Some of my plugins run as child bridges (they use memory, but not much) - is there a way to temporarily stop them for that try and error testing? Trying to avoid a full removal for each of them

**Comment by NorthernMan54** [comment]
This is from my main instance, that has been running for over a month

top with M

![Screen Shot 2021-04-19 at 6 09 04 PM](https://user-images.githubusercontent.com/19808920/115309831-d04fd500-a13a-11eb-8edf-60c6066ec814.png)

The top memory usage is the main home bridge instance, and the second one is a child bridge for 'homebridge-apple-tv-remote'

![image](https://user-images.githubusercontent.com/19808920/115310155-59670c00-a13b-11eb-8ea0-0ac913006e4f.png)

And this is from my system monitoring tool ( The last restart is in week 12 )

![image](https://user-images.githubusercontent.com/19808920/115310390-bfec2a00-a13b-11eb-91e4-5680e2d4e5de.png)

Am thinking that there may be slow memory leak somewhere, I'm using the ciao advertiser.  And all my plugins are running in a child bridge, and none are in the main bridge.  I have a total of 6 child bridges.

Any thoughts on a good memory analysis tool ?

To collect more data I'm going to leave this running for a few more days before restarting to see if I can confirm which homebridge instance is growing ie the main or a child bridge

**Comment by NorthernMan54** [comment]
24 hours later

It appears that the main homebridge instance grew by 10mb virtual and 4mb resident

![image](https://user-images.githubusercontent.com/19808920/115415762-2bc6a500-a1c5-11eb-9f0c-271f73f3d4f9.png)

**Comment by NorthernMan54** [comment]
Day 3, and the memory usage of the main bridge dropped.  Which 

![image](https://user-images.githubusercontent.com/19808920/115576115-30588f80-a291-11eb-81e2-6c9942efd53b.png)

Unfortunately I need to reset the environment so will need to start this investigation again.

**Comment by NorthernMan54** [comment]
Here is the same snapshot post restart

![image](https://user-images.githubusercontent.com/19808920/115578034-ea9cc680-a292-11eb-9b4c-d05a38c54fd8.png)
