### ISSUE TITLE
Homebridge (on Raspbian) - Thermostat widget in IOS Home app does not work

### ISSUE THREAD

**Issue by bjallefix** [homebridge/homebridge#2895]
I use Razberry (zwayserver 3.1.4) on a Pi4 as hub for my Z-Wave devices. The Pi is also hosting homebridge (1.3.4).
All my Z-wave devices works as expected in the homebridge UI and in IOS Home app except from my three thermostats of type HeatIt Z-TRM3. In homebridge UI I can change the set temperature on all three thermostats, but in IOS Home app it is not possible to even move the knob. My guess is that I have to configure something somewhere to make this work? The widget settings on IOS is missing temperature unit (C for celsius in my case) and I suspect the low/high degree is part of the problem. If i try to change set temp it always goes to 5 degree celsius.

As you can see in the below image the low and high limut is probably set to the same value (a tiny white line)
<img width=591 alt="" src="https://user-images.githubusercontent.com/37778495/114234209-c1209880-997e-11eb-9bdc-5e8485e1ec9c.jpeg">

As you can see in the below image the unit is missing (I would expect C for Celsius).
<img width=591 alt="" src="https://user-images.githubusercontent.com/37778495/114234349-eb725600-997e-11eb-9be7-6a01f31e1910.jpeg">

In Homebridge UI everything works great.
<img width="591" alt="Skjermbilde 2021-04-09 kl  22 04 47" src="https://user-images.githubusercontent.com/37778495/114234969-c9c59e80-997f-11eb-9001-28dcd0e31083.png">

Any help would be much appreciated :-)

**Comment by oznu** [comment]
Please report this to the plugin author. Thermostat / HeaterCooler plugins do work via Homebridge.

**Comment by bjallefix** [comment]
Thanks. The only plugin I have is the "Homebridge Zway Kevindayton". Am I wrong to assume the temperature widget is a standard component of homebridge? If so, how can I identify the author?

**Comment by oznu** [comment]
> Am I wrong to assume the temperature widget is a standard component of homebridge? 

The temperature "widget" in the Home app is provided by Apple, from your screenshots the "Homebridge Zway Kevindayton" is not providing the correct characteristic responses that Apple expects. The Homebridge UI implementation is less strict in what it expects, which is why it may work there but not  in the Apple Home app.

**Comment by bjallefix** [comment]
Thanks, oznu. 
This makes sense. Then I need to find out what is missing or wrong in the payload for my app. Fingers crossed that I can manage to figure this out :)

**Comment by bjallefix** [comment]
In case someone else have this problem I will share how I managed to resolve this issue.

I commented out these lines in /usr/lib/node_modules/homebridge-zway/index.js:
//cx.setProps({
//perms: [Characteristic.Perms.READ]
//});

**Comment by designfactory** [comment]
Hi @bjallefix 

I’m about to invest in a HeatIt thermostat for my electrical underfloor heating. Desperately need to get it to work with HomeKit as well so your solution is promising, thank you. 

How are the HeatIt products working out for you, any downsides or other cons I should be aware of? Do you also use them for electrical under floor heating?

mange takk
