### ISSUE TITLE
Wrong year listed for release v1.3.4 (2020-03-16)

### ISSUE THREAD

**Issue by lensherm** [homebridge/homebridge#2896]
Release v1.3.4 lists 2020 instead of 2021 as the date (see attached image). Please disregard if this is deliberate.

![image](https://user-images.githubusercontent.com/43871954/114432725-00bdcf00-9b8f-11eb-9bf6-5f32f74d0e2d.png)

**Comment by oznu** [comment]
Thanks; fixed.
