### ISSUE TITLE
"sudo: a password is required" when installing/uninstalling plugins

### ISSUE THREAD

**Issue by skosow** [homebridge/homebridge#2897]
When I try to install a plugin I get a password error

`USER: homebridge
DIR: /usr/local
CMD: sudo -E -n npm install -g @milo526/homebridge-tuya-web@latest

sudo: a password is required

Command failed. Please review log for details.`

I didn't have this problem yesterday and I haven't changed anything. I am running on a raspberry pi 4.

I tried to uninstall the plugins I had installed yesterday but they also give me this error.

This is through the Homebridge UI, if it makes a difference.

**Comment by oznu** [comment]
sudo hb-service uninstall
    sudo hb-service install --user pi

**Comment by iMonZ** [comment]
> sudo hb-service uninstall
> sudo hb-service install --user pi

Perfect this worked! But why is Homebridge changing automatically the port? This is pretty awkward
