### ISSUE TITLE
Tried changing log location to /var/log/ without success

### ISSUE THREAD

**Issue by AdeTheux** [homebridge/homebridge#2898]
**Describe Your Problem:**
I read the documentation of course, and tried a few variants of the config.json file, but after each reload and/or restart of homebridge, the change is not impacting where the log files are being stored: they keep on being stored in /var/lib default directory, and not in /var/**log** as I'd like to.

[**Logs:**]
No error appearing in logs, however the log file is still being served from the default location:
```
Loading logs using native method...
File: /var/lib/homebridge/homebridge.log
```
I also tried to manually create the new log file in /var/log, but not sure what permissions should be set.

**Homebridge Config:**
```json
    "platforms": [
        {
            "name": "Homebridge Config",
            "port": 8581,
            "sudo": true,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "loginWallpaper": "/home/abc/Pictures/IMG_3994.JPG",
            "log": {
                "method": "file",
                "path": "/var/log/homebridge/homebridge.log"
            },
            "platform": "config"
        },
```

**Environment:**

* **Node.js Version**: v14.16.1
* **NPM Version**: 7.9.0
* **Homebridge Version**: 1.3.4
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd (I think 🤔 ). It does auto start after reboot.

**Comment by oznu** [comment]
See https://github.com/homebridge/homebridge/issues/2881
