### ISSUE TITLE
`hb-service start` doesn't start the service but `hb-service run` works

### ISSUE THREAD

**Issue by finsprings** [homebridge/homebridge#2906]
**Describe Your Problem:**
When I do `sudo hb-service start` the service doesn't start. If I `su` to the `homebridge` user I can do `hb-service run` and it works fine.

Fom the `systemctl status homebridge.service` it appears that it fails to start then tries again repeatedly (the PIDs shown in the status change), so it never makes it past this  _Active: activating_ stage.

```
systemctl status homebridge.service
* homebridge.service - Homebridge
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2021-04-18 22:00:12 EDT; 3s ago
  Process: 9694 ExecStartPre=/bin/run-parts /etc/hb-service/homebridge/prestart.d (code=exited, status=0/SUCCESS)
  Process: 9699 ExecStartPre=/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js before-start $HOMEBRIDGE_OPTS (code=exited, status=0/SUCCESS)
  Process: 9725 ExecStart=/usr/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js run $HOMEBRIDGE_OPTS (code=exited, status=218/CAPABILITIES)
 Main PID: 9725 (code=exited, status=218/CAPABILITIES)
```

This is a brand new installation of Homebridge. I followed the [instructions on the wiki](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux), and did `sudo hb-service update-node` to get node up to date. Are there some permission I'm missing maybe?

**Homebridge Config:**

_(Issue occurred before I added any plugins too.)_

```json
{
    "bridge": {
        "name": "Homebridge CD5B",
        "username": "0E:89:DB:92:CD:5B",
        "port": 51248,
        "pin": "115-01-892",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "controllers": [
                {
                    "address": "..."
                    "password": "...",
                    "username": "...
                }
            ],
            "platform": "UniFi Protect"
        }
    ]
}
```

**Environment:**

* **Node.js Version**: v14.16.1
* **NPM Version**: 6.14.12
* **Homebridge Version**: 1.3.4
* **Operating System**: Debian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
What's your Kernel version? Provide the output of `uname -a`.

You're probably running an older kernel that doesn't support some of the systemd features used by hb-service.

See this comment:

https://github.com/oznu/homebridge-config-ui-x/issues/1104#issuecomment-787437885

**Comment by finsprings** [comment]
Thanks. Yes, this is on Debian Buster. Removing those capability lines did the trick!

**Comment by PeterWan816** [comment]
Now this happens in MacOS Monterey too. Adding the com.apple.homebridge.server.plist into the launchctl list manually and using hb-services start/restart does not work, only after doing hb-services run that it works. is there any permanent fix to this?
