### ISSUE TITLE
Can't link to google home

### ISSUE THREAD

**Issue by usergit123455** [homebridge/homebridge#2907]
I can't link homebridge to Google home. Please help to link.

https://user-images.githubusercontent.com/82658978/115571286-e93dbf00-a2cf-11eb-8479-ac37253ab50d.mp4

The recording is on the link

**Comment by oznu** [comment]
Make sure you have valid accessories in Homebridge before attempting to link.

Issues with GSH should be directed here: https://github.com/oznu/homebridge-gsh/issues
