### ISSUE TITLE
Manually added bridge, not exposing QR

### ISSUE THREAD

**Issue by greensouth** [homebridge/homebridge#2909]
I added the bridge property to an accessory and it's recognised by HomeKit, but when clicking in the wrench of the plugins page, it shows no QR but a link to the config file, which isn't working either.

Must be some kind of bug.

**Comment by oznu** [comment]
The QR code will only be displayed if the plugin implements the [config schema](https://developers.homebridge.io/#/config-schema) or the UI can figure it out.

You can such accessories pair manually using the PIN from the main bridge as per https://github.com/homebridge/homebridge/wiki/Child-Bridges#how
