### ISSUE TITLE
ERR_STRING_TOO_LONG

### ISSUE THREAD

**Issue by Splix123** [homebridge/homebridge#2911]
**Describe The Bug:**
Tried to install a plugin this morning but Homebridge wouldn't do it. Searched in the log and got:
`14:15:16 Cannot create a string longer than 0xffffff0 characters`

Thought it was a Plugin Problem and tried other ones but failed as well.
After a bit of research that would be caused by a file larger than 256MB in the persist-folder, but checking that with `ls -sh` shows no file above 8KB.

**Expected behavior:**
Install any Plugin

[**Logs:**]

> 23.4.2021, 13:37:00 HOOBS listening on port 80.
> 23.4.2021, 13:37:11 Initializing HAP-NodeJS v0.9.3...
> 23.4.2021, 13:37:35 Loaded plugin 'homebridge-dht'
> 23.4.2021, 13:37:35 [4/23/2021, 5:37:35 AM] Registering accessory 'homebridge-dht.Dht'
> 23.4.2021, 13:37:35 Loaded plugin 'homebridge-fritz-platform'
> 23.4.2021, 13:37:44 [4/23/2021, 5:37:44 AM] Registering platform 'homebridge-fritz-platform.FritzPlatform'
> 23.4.2021, 13:37:44 Loading 1 platforms...
> 23.4.2021, 13:37:44 [FritzPlatform] Initializing FritzPlatform platform...
> 23.4.2021, 13:37:45 Loading 1 accessories...
> 23.4.2021, 13:37:45 [Zimmer Temp] Initializing Dht accessory...
> 23.4.2021, 13:37:45 [Zimmer Temp] Adding Accessory
> 23.4.2021, 13:37:45 [Zimmer Temp] INIT: Zimmer Temp
> 23.4.2021, 13:37:45 [FritzPlatform] RuehmBox Wifi 2ghz: Configuring accessory...
> 23.4.2021, 13:37:45 [FritzPlatform] RuehmBox Wifi 5ghz: Configuring accessory...
> 23.4.2021, 13:37:45 [FritzPlatform] RuehmBox Wifi guest: Configuring accessory...
> 23.4.2021, 13:37:45 [FritzPlatform] Moritz: Configuring accessory...
> 23.4.2021, 13:37:45 Preparing Advertiser for 'HOOBS1 CA66' using bonjour-hap backend!
> 23.4.2021, 13:37:45 Starting to advertise 'HOOBS1 CA66' using bonjour-hap backend!
> 23.4.2021, 13:37:45 Bridge is running on port 51825.
> 23.4.2021, 13:49:33 npm ERR! code ERR_STRING_TOO_LONG
> 23.4.2021, 13:49:34 npm
> 23.4.2021, 13:49:34
> 23.4.2021, 13:49:34 ERR! Cannot create a string longer than 0xffffff0 characters
> 23.4.2021, 13:49:34
> 23.4.2021, 13:49:34 npm

**Environment:**

* **Node.js Version**:  12.19.0
* **Homebridge Version**:  3.3.5
* **Operating System**: Raspbian / macOS

**Comment by oznu** [comment]
Hi @Splix123,

You'll need to raise HOOBS issues with the HOOBS team.

Cheers
