### ISSUE TITLE
Can a plugin control accessories of another plugin?

### ISSUE THREAD

**Issue by jantimon** [homebridge/homebridge#2913]
I would like to create a Cron plugin which (when activated) modifies the characteristics depending on the time

One of different use cases could be to turn down the brightness of all lights (without turning them on) during the night

Therefore my plugin would need to control foreign Accessories
Is there an API to do that?

**Comment by mkellsy** [comment]
This is possible. If you run Homebridge with the -I flag, you can use the HAP-NodeJS API.

As a test, add the -I flag to your current setup. Then in your browser go to http://192.168.x.x:51826/accessories. You should see a list of accessories in JSON.

You can find examples of this in the homebridge-ui-x, homebridge-alexa plugins.

Hope this helps and good luck on your project.

**Comment by jantimon** [comment]
Would it be possible to add it without the rest workaround?

This would also allow plugins to listen to events from foreign accessories

**Comment by mkellsy** [comment]
No. Homebridge doesn't have a public exposed list of accessories. What you are looking for would require modifying Homebridge's source code.

**Comment by NorthernMan54** [comment]
Another approach to this is to leverage node-red and homebridge-automation to control your homebridge devices.
