### ISSUE TITLE
Connecting via plugin Homebridge RPi to official Homebridge RPi device - Getting ERR_BUFFER_OUT_OF_BOUNDS errors

### ISSUE THREAD

**Issue by jcpuzic** [homebridge/homebridge#2914]
When I add my Homebridge RPi to the Homebridge RPI Plugin, Homebridge gives me these errors in the log:

> [4/26/2021, 4:31:06 PM] [homebridge] homebridge: connected to 10.23.0.148:8581
> [4/26/2021, 4:31:06 PM] RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
>     at boundsError (internal/buffer.js:81:11)
>     at Buffer.readUInt32LE (internal/buffer.js:217:5)
>     at PigpioClient._onCmdData (/homebridge/node_modules/homebridge-rpi/lib/PigpioClient.js:494:24)
>     at Socket.emit (events.js:315:20)
>     at addChunk (internal/streams/readable.js:309:12)
>     at readableAddChunk (internal/streams/readable.js:284:9)
>     at Socket.Readable.push (internal/streams/readable.js:223:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
> [4/26/2021, 4:31:07 PM] Got SIGTERM, shutting down Homebridge...
> [4/26/2021, 4:31:07 PM] [homebridge] homebridge: disconnected from 10.23.0.148:858

**Comment by ebaauw** [comment]
Please don't double post.
See https://github.com/ebaauw/homebridge-rpi/issues/93#issuecomment-826999073
