### ISSUE TITLE
Error: Invalid character in entity name

### ISSUE THREAD

**Issue by ChrisChiera** [homebridge/homebridge#2917]
This is probably not an issue with Homebridge, but can't tell from the Homebridge log what file too look to find the issue.

Error: Invalid character in entity name

**Describe The Bug:**

Suddenly Homebridge is not running as it's running into an error and shutting down. Have been using successfully for a year or two. Not sure what changed that is causing the issue. says, "Error: Invalid character in entity name Line: 78 Column: 95" as seen in the photo, but what file is that referring to? Looked in the config and line 78 doesn't appear to have any issues. Under that error is mentions ISY and specific files but the line numbers for all of those it mentions is not 78. From the error report are you able to determine what file is causing the sudden syntax error?

**To Reproduce:**

Unknown. 

**Expected behavior:**

Should not show an error.

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/270079/116815067-d45ff780-ab29-11eb-9f69-5afef7072f51.png)

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment]
This is an error in the "homebridge-isy-js" plugin; please raise an issue over on the GitHub project page for that plugin.
