### ISSUE TITLE
Homebridge UI website working, app showing no response.

### ISSUE THREAD

**Issue by lauzca** [homebridge/homebridge#2918]
**Describe Your Problem:**
In the windows 10 running homebride website, all my accessories are responding and updating instantly.  My app on my phone and my iPad for HomeKit is showing “no response” for all devices.  I have tried restarting everything, no luck.  I am running a unifi dream machine as my router.  Not sure if this started before or after setting up the new router, but I’m not sure if a router would affect this in any way.

**Comment by Feilner** [comment]
I have same issue. The home App shows not reachable for the bridge. 
But it works after several restarts of homebridge.
