### ISSUE TITLE
Homebridge unreachable from the outside

### ISSUE THREAD

**Issue by jamesngob** [homebridge/homebridge#2919]
**Describe The Bug:**
We have our cameras on a VLAN-10.
Homebridge is on the main LAN, ID 1
Using Home App for iOS, I cannot access any camera streams (HIKVISION) and FordPass if the iPhone/iPad connected to 4G or Public wifi
If connected to local LAN, I can access all camera's stream and FordPass
Firewall config not to block VLAN-10 to reach out to the Homebridge IP on main LAN 
Hivision camera uses ffmpeg and streaming as rtsp protocol, port 554
Any idea where I might be checking to make this work? (accessible from 4G, outside WIFI)
Thank you
James

**To Reproduce:**

**Expected behavior:**

[**Logs:**]()
The camera said "not responding" and nothing ever happened.
No log record either
```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by Feilner** [comment]
Please check the Wiki if you have the prerequisites for remote access. You need a home hub:
https://github.com/homebridge/homebridge/wiki/Remote-Access

**Comment by jamesngob** [comment]
@Feilner: I do have Apple TV 4K as a Hub.
However, I found out the issues is that the mDNS Advertiser was set to "Ciao", which normally working but with our new VLANs setup, changing this to "Bonjour-HAP" works again.
Issue solved
