### ISSUE TITLE
Cannot view/access cameras  in HomeApp while connected to 4G or public Wifi

### ISSUE THREAD

**Issue by jamesngob** [homebridge/homebridge#2922]
**Describe Your Problem:**

Our network is pretty simple

Hikvision NVR on VLAN-CCTV (using HIKVISION and FFMpeg plugin)
Apple TV on VLAN-IOT
Lutron bridge on VLAN-IOT
Homebridge server, installed on Ubuntu 20.04.2 LTS, on main LAN
2x Pihole as our DNS server, on main LAN
Firewall has been update to allow the access from main LAN to VLAN-CCTV and VLAN-IOT (but not the other way around)

I have added successfully the homebridge into the Apple HomeApp on iPhone 8, latest firmware
If my iPhone connects to the main LAN, I can view all cameras in Apple HomeApp
If my iPhone connects to either 4G or public wifi, the camera shows "offline" almost immediately
In previous post, I said changing the mDNS Advertiser from Ciao to Bonjour-HAP would do the trick, but not anymore. I have toggled between the 2 modes without any success.
The log on the homebridge does not show anything!
It seems that the HomeApp couldn't "talk" to the Homebridge if my phone is on the 4G or public wifi
Other devices such as the Lutron Bridge or the Schlage Lock (via Apple TV as Home Hub) works just fine

How does the HomeApp connect to Homebridge originally? is it something from my Firewall that I need to do?

Thank you very much

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment]
> Apple TV on VLAN-IOT
> Homebridge server on main LAN
> allow the access from main LAN to VLAN-CCTV and VLAN-IOT(but not the other way around)

Remote access is done via the Apple TV. The Apple TV needs to be able to send and receive back UDP mDNS packets to the Homebridge instance, as well as communicate via TCP on the Homebridge server port. 

mDNS by default will not cross subnets or VLANS - you will need to setup some sort of mDNS reflector or have Homebridge on both VLANS.

**Comment by jamesngob** [comment]
> > Apple TV on VLAN-IOT
> > Homebridge server on main LAN
> > allow the access from main LAN to VLAN-CCTV and VLAN-IOT(but not the other way around)
> 
> Remote access is done via the Apple TV. The Apple TV needs to be able to broadcast and receive back UDP mDNS packets from the Homebridge instance, as well as communicate via TCP on the Homebridge server port.
> 
> mDNS discovery requests by default will not cross subnets or VLANS - you will need to setup some sort of mDNS reflector or have Homebridge on both VLANS.
> 
> Your Lutron Bridge works because it's on the same VLAN as the Apple TV.

@oznu: I am using a EdgeRouter from Ubiquiti. In the setting, there is mDNS repeater/reflector set-up. I actually had this setup previously. 
After reading your reply, I reset this mDNS setting (remove the interface and re-add it again), and now it works!
It must be disconnected during the change-over of the VLANs I guess...
Problem solved, now you can close this thread...
