### ISSUE TITLE
SSH/SCP access to Windows VM

### ISSUE THREAD

**Issue by blackbasket** [homebridge/homebridge#2925]
**Describe Your Problem:**
Unable to connect using ssh

I want to connect to the homebridge VM through ssh, to be able to copy files. I tried pi/raspberry as found in the (raspberry) wiki. I also tried setting the root's pw using root passwd in the web shell.
I got a successfull answer, but cannot connect anyway.

[**Logs:**]()

**Homebridge Config:**

**Screenshots:**

**Environment:**
Windows Server 2019 Hyper-V

* **Node.js Version**: 14.17.0
* **NPM Version**: 6.14.13
* **Homebridge Version**: 1.3.4
* **Operating System**: Windows
* **Process Supervisor**: ?

**Comment by oznu** [comment]
From the VM console (not the web terminal), set a password for the `docker` user:

```
sudo passwd docker
```

Once set you can ssh in using `docker` user and the password you have set.

```
ssh docker@homebridge-vm-ip
```

The `docker` user does not have a password set by default, effectively preventing any SSH connections.

**Comment by phena109** [comment]
Sorry for the noob request but i think this worth documented somewhere.
