### ISSUE TITLE
HomeKit accesories into Homebridge?

### ISSUE THREAD

**Issue by philibertc** [homebridge/homebridge#2926]
**Describe Your Question:**

How can I integrate a HomeKit accesory into Homebridge (to control it with Alexa)?

**Comment by NorthernMan54** [comment]
One method I use I find a homebridge plugin for the device and stop using the native integration.  I’m using this with my LG webos TVs

**Comment by philibertc** [comment]
Yep, but there is no plugin for all homekit devices. (eg: my Home Assistant HomeKit bridge emulation).

**Comment by NorthernMan54** [comment]
If your using home assistant it has its own Alexa integration

**Comment by philibertc** [comment]
5$ a month that's too much

**Comment by NorthernMan54** [comment]
So the cost of our Alexa integration is too cheap?  I need to increase the price to $5 a month?

**Comment by philibertc** [comment]
> So the cost of our Alexa integration is too cheap?

No, why?

**Comment by oznu** [comment]
See https://github.com/homebridge/homebridge/issues/2927
