### ISSUE TITLE
[Feature] Ability to add HomeKit into Homebridge accessories.

### ISSUE THREAD

**Issue by philibertc** [homebridge/homebridge#2927]
This would allow to control HomeKit devices using Alexa or Google.
https://github.com/homebridge/homebridge/issues/2926

**Comment by oznu** [comment]
A plugin could probably do this (it would not be a small amount of work), but this is out of scope for Homebridge itself.

**Comment by philibertc** [comment]
> A plugin could probably do this

Yes, "homebridge-homekit-controller" but it isn't maintained and doesn't work.
