### ISSUE TITLE
[Question] Homebridge Image Fails to Install Hyperion

### ISSUE THREAD

**Issue by mitch7391** [homebridge/homebridge#2930]
**Describe Your Problem:**

I am using the official Homebridge image on a Raspberry Pi 4 and am trying to install the ambilight service Hyperion on the same RPi. It seems to fail everytime being installed through the terminal saying it is not able to find the `root` directory. I have raised the issue on their Github ([link](https://github.com/hyperion-project/hyperion.ng/issues/1245)), but they have suggested it might be an issue with the Homebridge image.

**Steps to Reproduce:**

```
wget https://github.com/hyperion-project/hyperion.ng/releases/download/2.0.0-alpha.9/Hyperion-2.0.0-alpha.9-Linux-armv7l.deb
sudo apt install ./Hyperion-2.0.0-alpha.9-Linux-armv7l.deb
```
Response:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'hyperion' instead of './Hyperion-2.0.0-alpha.9-Linux-armv7l.deb'
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  hyperion
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/80.5 MB of archives.
After this operation, 215 MB of additional disk space will be used.
Get:1 /home/pi/Hyperion-2.0.0-alpha.9-Linux-armv7l.deb hyperion armhf 2.0.0 [80.5 MB]
Selecting previously unselected package hyperion.
(Reading database ... 46431 files and directories currently installed.)
Preparing to unpack .../Hyperion-2.0.0-alpha.9-Linux-armv7l.deb ...
---Hyperion ambient light preinst ---
/var/lib/dpkg/tmp.ci/preinst: 6: /var/lib/dpkg/tmp.ci/preinst: root: not found
Unpacking hyperion (2.0.0) ...
Setting up hyperion (2.0.0) ...
---Hyperion ambient light postinstall ---
/var/lib/dpkg/info/hyperion.postinst: 32: /var/lib/dpkg/info/hyperion.postinst: root: not found
---> init deamon: systemd
Failed to start hyperiond@.service: Unit name hyperiond@.service is missing the instance name.
See system logs and 'systemctl status hyperiond@.service' for details.
---> Install Hyperion desktop icons
--> systemctl start hyperiond for user
-----------------------------------------------------------------------------
---> Hyperion has been installed/updated!
---> 
---> Hyperion has been installed as service, it will start on each system startup
---> For configuration, visit with your browser: 192.168.0.175:8090
---> or if already used by another service try: 192.168.0.175:8091
-----------------------------------------------------------------------------
Webpage: www.hyperion-project.org
Wiki: wiki.hyperion-project.org
Forum: forum.hyperion-project.org
-----------------------------------------------------------------------------
```

**Environment:**

* **Node.js Version**: Latest stable
* **NPM Version**: Latest stable
* **Homebridge Version**: v1.3.4
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by oznu** [comment]
The image is just Raspberry Pi OS Lite with Homebridge pre-installed. Nothing fancy :)

The issue is with their installer:

> Failed to start hyperiond@.service: Unit name hyperiond@.service is missing the instance name.

**Comment by mitch7391** [comment]
Cheers for the info @oznu  :) I will pass this on!

**Comment by mitch7391** [comment]
Hey @oznu in the end it appeared that trying to install it through the web UI terminal was the problem. When I used ssh to log into the RPi instead and used the exact same installation commands; it all worked. 

I asked over there what the difference may have been but the devs do not know off the top of their heads and aren’t in a position to invest the time into finding out why. Would you have any idea? I also use the web UI terminal to install other programs and now wonder if I shouldn’t and if I should start using ssh again.
