### ISSUE TITLE
[Discuss] "This plugin slows down Homebridge..."

### ISSUE THREAD

**Issue by afharo** [homebridge/homebridge#2931]
**Describe Your Problem:**

As a developer, I'd like to know what's the typical timeout from Homebridge to show the slow logs. In the wiki, it's suggested to call [`callback()` immediately](https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings).

As a Node.js developer, I would expect callback/promise methods to allow async behaviours. If a method is expected to be sync, it'd rather return instead.

In my plugin, I'm asking the accessory about their state over the local connection. Some users are complaining that they're seeing those log entries (typically because they're experiencing some Network issues themselves).

IMO, according to Node.js IO behaviours, slow network requests should not block anything on the bridge's behaviour to recommend the approach of calling `callback()` immediately and later use `characteristic.updateValue`. I think that this suggested approach also affects the UX because any action will always succeed, even when a network misconfiguration might cause timeouts. I'd rather let the user know by having the Home app (or Siri), claiming that it failed, rather than silent errors (only to be discovered when looking at the logs).

What do you think?
Also, what's the current timeout to show the slow-log?

[**Logs:**]()

```
[5/16/2021, 4:19:22 AM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' was slow to respond! See git.io/JtMGR for more info.
[5/16/2021, 7:01:53 AM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Firmware Revision' was slow to respond! See git.io/JtMGR for more info.
[5/16/2021, 9:45:03 AM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' was slow to respond! See git.io/JtMGR for more info.
```

**Homebridge Config:**

not relevant

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by ebaauw** [comment]
The blocking doesn't happen in NodeJS nor in Homebridge, but in HomeKit on your iOS device.

HomeKit will only issue one request at a time to the HAP server.  For unbridged accessories this is no big deal, as you'd only block the next request to yourself, but for HomeKit bridges (i.c. Homebridge), you'd block all requests to all bridged accessories.

Use child bridges (i.e. a separate HAP server for your plugin) to limit the blocking to your own plugin.  Use an external accessories (with its own HAP server) to limit the blocking to the accessory itself.

Best practice is not to do any asynchronous I/O from the `get` handler.  Instead, poll the device asynchronously (assuming it doesn't support push notifications), updating the characteristic value, and let Homebridge/HAP-NodeJS return the cached value.  For set handlers, call `callback()` before the asynchronous I/O has returned.  Should the request to the device fail, set the characteristics to its previous value.

**Comment by afharo** [comment]
@ebaauw understood! So HomeKit is the culprit of serializing the requests for each bridge? 🤦 

I've been considering moving my plugin from Accessory to a Dynamic Platform. I believe that it will create a bridge of its own for this plugin, correct?

**Comment by ebaauw** [comment]
No.  The type of plugin determines how you link accessories to Homebridge: from config.json (accessory); through the API (dynamic platform); or through a callback before startup (static platform).  All these accessories are bridged by Homebridge's HAP server, though (that's the one you pair with HomeKit).  Use chid bridges or external accessories for separate HAP servers (each of which you need to pair with HomeKit separately)

**Comment by afharo** [comment]
Got it! Is there a way for the plugin to tell Homebridge that it should start in a child bridge or is it up to the user to set them?

**Comment by ebaauw** [comment]
Currently, it needs to be specified in `config.json`, see https://github.com/homebridge/homebridge/wiki/Child-Bridges.
