### ISSUE TITLE
Lost all Homebridge accessories after network switch

### ISSUE THREAD

**Issue by emcepe** [homebridge/homebridge#2932]
I've changed my Raspi network layout at home from WiFi to Ethernet and after that all Homebridge accessories are gone in the iOS app, only the bridge itself is there. Changed everything back like it was before without any luck, all accessories are gone :-(

What's the problem here?

Is there any trivial fix to bring them all back?

I really do not want to start from scratch the 3rd time in 1 year homebridge usage.

I'm using Raspbian Buster on a Raspberry Pi 4b with Homebridge 1.2.5 and FHEM plugin.

Thanks.

**Comment by emcepe** [comment]
ok, thanks for nothing ;->

I've started from scratch - again.

Tried it with v1.3.4 but as soon as I use the FHEM plugin with it I cannot add the bridge to Homekit on iOS, after some seconds I get the response that the bridge cannot be added. If I disable the FHEM plugin I can add the bridge w/o any problems on v1.3.4. After I re-enable the FHEM plugin everything stopped working, even after disabling the plugin again, the iOS Homekit is totally b0rked and I have to start from scratch - again. Even a 2nd bridge with FHEM-only does not work at all.

So I tried it with v1.2.5, I can add the bridge w/o any problems and see my 134 devices and all are up and running. Upgraded to v1.3.4 and the problems came back like in [https://github.com/homebridge/homebridge/issues/2847](https://github.com/homebridge/homebridge/issues/2847) - So again a restart from scratch.

So for whatever the problem was with Homekit on iOS, the network re-layout fucked it all up and v1.3.4 does not work at all with the FHEM plugin.

So I stay with v1.2.5 now forever (or until the next f*ck up ;->)

**Comment by emcepe** [comment]
no idea?

**Comment by emcepe** [comment]
The root of all problems was:

https://github.com/justme-1968/homebridge-fhem/issues/82

**Comment by emcepe** [comment]
Unstale comment

**Comment by emcepe** [comment]
Unstale comment again

**Comment by emcepe** [comment]
Unstale comment again

**Comment by Charliecheung2** [comment]
Maybe you should get the new ip address and just change the ip address in config file? That should work if you only change the network enviorment.

**Comment by emcepe** [comment]
*seufz*

**Comment by emcepe** [comment]
Unstale comment

**Comment by emcepe** [comment]
and again another unstale comment

**Comment by emcepe** [comment]
schallallalallalalalaaaaaaa, unstale the 7345845th
