### ISSUE TITLE
Homebridge wants to install globally

### ISSUE THREAD

**Issue by rvt** [homebridge/homebridge#2934]
**Describe Your Problem:**
Homebridge does want to do a global update :

<img width="797" alt="image" src="https://user-images.githubusercontent.com/720814/119864357-da73a900-bf1a-11eb-8515-2e6ff25a8004.png">

Obviously homebridge should not have access to `/usr/lib/node_modules/`

How can I configure homebridge to update locally?

**Comment by rvt** [comment]
That's a shame, nobody?!

**Comment by jochenpa** [comment]
Hello

Nothing new about this?
I also have this problem.
