### ISSUE TITLE
Unexpected ".0" added to firmware revision number

### ISSUE THREAD

**Issue by pro-sumer** [homebridge/homebridge#2936]
**Describe The Bug:**
When I (as plug-in developer) set the Firmware Revision to an integer number the Home App appends ".0" to that integer.

```
service.setCharacteristic(this.Characteristic.FirmwareRevision, 123)
```

Home App will show:

```
Firmware 123.0
```

**To Reproduce:**
Write a minimal plugin that only sets the Firmware Revision on the Accessory Information service to an integer number.

**Expected behavior:**
Home App displays the specified integer number (without the ".0" suffix):

```
Firmware 123
```

**Logs:**
n/a

**Homebridge Config:**
n/a

**Screenshots:**
n/a

**Environment:**

* **Node.js Version**: 14.17.0
* **NPM Version**: 7.15.0
* **Homebridge Version**: 1.3.4
* **Operating System**: Raspbian 
* **Process Supervisor**: hb-service

**Comment by pro-sumer** [comment]
PS: the issue is the same when I set a string (`"123"`) instead of an integer (123).

(a string is what I have been using, but I tried an integer hoping that would solve it - unfortunately not)

**Comment by codyc1515** [comment]
I'll double check but I think this is technically required within the HAP spec.
