### ISSUE TITLE
How to support multiway switch button in a switch Accessory

### ISSUE THREAD

**Issue by Hanh94** [homebridge/homebridge#2937]
I have a switchgear, it's a three-way switch, so I want to create multiple switch buttons in a switch Accessory, but according to the HomeBridge API documentation, switch serviceType only supports one object for one 'on' Characteristic, How can I solve this problem?

**Comment by oznu** [comment]
You can add multiple services to one accessory.

**Comment by Hanh94** [comment]
@oznu thanks
