### ISSUE TITLE
permission denied error on trying to access the config.json file  on mac

### ISSUE THREAD

**Issue by harsharo** [homebridge/homebridge#2938]
![image](https://user-images.githubusercontent.com/83968632/120677763-54fa7680-c48f-11eb-8479-f9d8267b2491.png)

**Describe Your Problem:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by oznu** [comment]
The json file is not executable so you can't just run it like that.

**Comment by mbierman** [comment]
Try an editor such as vi
`vi /Users/harsharoah/.homebridge/config.json`
