### ISSUE TITLE
HomeKit Automations does not work properly

### ISSUE THREAD

**Issue by vdebrist** [homebridge/homebridge#2939]
HomeKit Automations does not work properly

The Bug: There are added some motion sensors and wi-fi lights. Made an automation in HomeKit "When motion sensor detects smth -> Turn on the light". It works 5-10 times properly, after that - it doesn't work. Homebridge properly recognises information from zigbee motion sensor (motion detected), but automation does not starts. Bulbs are properly controlled from HomeKit all the time, information from sensors are correct too. I am not sure, that it is a HomeBridge bug, maybe it is a HomeKit bug, but all devices are integrated in HomeKit through Homebridge.

Environment:

* **Node.js Version**: v14.17.0
* **NPM Version**: v7.16.0
* **Homebridge Version**: v1.3.4
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service
* **Zigbee Hardware**: cc2652p
* **MQTT Broker**: Mosquitto v1.5.7
* **MQTT Server**: Zigbee2MQTT v.1.19.1
* **MQTT Plugin**: homebridge-z2m
* **Motion Sensor**: Xiaomi MCCGQ01LM
* **Wi-Fi Lights**: Tuya-compatible NoName E14 RGBTW

**Comment by vdebrist** [comment]
The problem was in iPad as HomeCenter or in a Wi-Fi connection between iPad and Router.

**Comment by bmounteer** [comment]
I'm having this issue and only set up my HomePod Mini as the hub. How did you fix it?

**Comment by vdebrist** [comment]
> I'm having this issue and only set up my HomePod Mini as the hub. How did you fix it?

As soon as I added HomePod to my Apple Account, I have removed from iPad settings checkbox (Use this iPad as HomeCenter). After that HomePod was assigned as HomeCenter. As soon as HomePod firmware was updated I have deleted and created again all automations. Now everything works perfectly. HomePod is connected to 5gHz wifi-network.

**Comment by bmounteer** [comment]
> > I'm having this issue and only set up my HomePod Mini as the hub. How did you fix it?
> 
> As soon as I added HomePod to my Apple Account, I have removed from iPad settings checkbox (Use this iPad as HomeCenter). After that HomePod was assigned as HomeCenter. As soon as HomePod firmware was updated I have deleted and created again all automations. Now everything works perfectly. HomePod is connected to 5gHz wifi-network.

Thanks for the reply. My solution was actually just restarting Homebridge. I guess somehow it just got stuck.
