### ISSUE TITLE
New: motion sensor notifications do not appear on iOS/macOS

### ISSUE THREAD

**Issue by adriancable** [homebridge/homebridge#2941]
Issue: motion sensors, when triggered, do not consistently produce notifications on iOS and macOS. This seems to be a 'new' issue in the past few days, experienced by others as well. It is not limited to a specific plug-in. It seems to only happen when multiple motion sensor services are added to a single accessory - unsure at this time.

Debug log from homebridge shows that the target iOS device is being registered for notifications:

2021-06-14T00:00:41.636Z HAP-NodeJS:Accessory [192.168.4.36] Registered Characteristic "Motion Detected" on "XXX" for events

And when motion is triggered, the event is sent:

2021-06-14T00:01:56.920Z HAP-NodeJS:EventedHTTPServer:Connection [192.168.4.36] Sending HAP event notifications [ { aid: 145, iid: 14, value: 1 } ]

The 'motion sensor' tile in Home app lights up, but no notification is produced. Same on iOS as with macOS.

Tried: rebooting iOS endpoints and HomeKit hubs, removing accessory from Home and re-adding, tearing down Homebridge (removing persist, changing config user ID etc.) + re-adding from scratch, moving plug-in to child bridge, running Homebridge on macOS vs. Raspberry Pi vs. PC etc. Nothing makes any difference.

Things that haven't changed recently enough to be the direct cause: Homebridge, the plug-ins, HAP-NodeJS etc. I have tried with Homebridge 1.3.4, 1.3.0 and 1.2.5 - no difference in behaviour.

Things that may have changed recently enough to be the direct cause: iOS -> 14.6, macOS -> 11.4, iCloud back end changes.

Anyone else confirm this is also an issue for them and/or have discovered any workarounds or resolutions?

**Comment by adriancable** [comment]
Added: it seems that, for cameras with multiple Motion Sensor services added, only the first Motion Sensor added triggers notifications (although they all show up, and update, correctly in HomeKit). Is this new? Is this known?

**Comment by gregjohnsonsaltaire** [comment]
Same observations ... have been through the same "rebooting iOS endpoints and HomeKit hubs, removing accessory from Home and re-adding, tearing down Homebridge (removing persist, changing config user ID etc.) + re-adding from scratch, moving plug-in to child bridge, running Homebridge on macOS vs. Raspberry Pi vs. PC etc. Nothing makes any difference." 

Motion Detector tiles are definitely triggering, you can click on a Motion Detector tile and watch "Motion Detected" change from No to Yes, but no notifications are being produced. Won't even pass a notification to a simple nfarina/homebridge-dummy "DummySwitch".

Have 10 Motion Detectors and attached automations work spasmodically ... can't determine conditions or a pattern as yet.

**Comment by adriancable** [comment]
@gregjohnsonsaltaire - yes, also, to my experience that the tiles reliably trigger, but notifications are not reliable. One more thing to add: the "real" HomeKit accessories I have with motion detectors do not seem to have this issue. Notifications from those always trigger reliably.

So I do think this is something not quite right in Homebridge/HAP-NodeJS but I can't prove it.

**Comment by gregjohnsonsaltaire** [comment]
Some findings:
* With a single Home Hub of Apple TV tvOS 14.7.1 (4 Gen) automations repeatably stop working at 5min 30secs (+- 5secs) after Apple TV reboot 
* With a single Home Hub of iPad IOS 14.7 (3 gen) automations work without a problem
Will retest with tvOS 15 betas when available ...
