### ISSUE TITLE
Accessories go online then offline constantly

### ISSUE THREAD

**Issue by binaryatlas** [homebridge/homebridge#2942]
**Describe The Bug:**
So when I add accessories, Ring Security or Nest at the moment. They go online then offline over and over again on my iPhone. I have tried different combinations of deleting plugins to see it one is causing an issue but I can't find anything. Also, the logs do not seem to be showing anything wrong.

I am on windows 10. I would appreciate guidance on what I need to look at and what you need to see to help.

**Comment by jimhosmer** [comment]
This appears to be a common problem that repeatedly gets blamed on Windows 10, which doesn't make a great deal of sense. In my case, restarting Homebridge causes all accessories to be visible and update status correctly for about 10 or so minutes, then all will change to "not responding" until I restart Homebridge again. I just removed and redefined my Home setup on IOS 15 beta with no change. Works for 10 minutes or so, then "not responding." No one appears to care. Shame. I had it all working flawlessly on Windows 10 for months before the first failure.

**Comment by jimhosmer** [comment]
PS. All accessories work correctly on the Homebridge Accessories page. Only the Apple technology (ios, ipados, Apple TV) fail to update correctly.

**Comment by adamcoulombe** [comment]
@binaryatlas @binaryatlas have you looked at https://github.com/homebridge/homebridge/issues/2847? I'm not sure if it might be a similar problem/solution. Have you tried rolling back to 1.2.5?
