### ISSUE TITLE
Homebridge as single accessory

### ISSUE THREAD

**Issue by alexwala** [homebridge/homebridge#2944]
Is there a mode to use Homebridge as a single accessory, without Homebridge UI.
Having a raspberry pi (zero) which should act as a HomeKit camera only.
Found package homebridge-camera-rpi which allows for standalone usage - is something possible with Homebridge too ?

**Comment by NorthernMan54** [comment]
This is 100% doable, just install the homebridge package and the camera plugin and go.

you will need to configure it by hand though, and create/edit the config.json

**Comment by oznu** [comment]
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian,-Debian-or-Ubuntu-Linux-%5BNo-UI%5D

**Comment by alexwala** [comment]
thanks a lot !
