### ISSUE TITLE
Problem to upgrade Homebridge 1.3.4

### ISSUE THREAD

**Issue by Reddyzinho** [homebridge/homebridge#2946]
Im stuck on 1.2.4 version of Homebridge. If i upgrade to 1.3.4 (latest), I get unresponsive equipments (Goovee, eWeLink, and all my breadline RM and PRO equipments). All the other plugins are ok. 

DOnt get any error message on the main board, so I can’t get there :/ 

I have upgraded the node as well for the latest version. 

Any ideia what’s going on? I’m a little “dumb” in this kind of Linux thing, but I will get there if you send me a signal :&

**Comment by newbiech** [comment]
No idea. With my recent experience of unrepsonsive devices I recommend to to a fresh installation. configs can be copy/pasted. Hope you have a spare SD to try it out.
