### ISSUE TITLE
Shelly HomekitBG

### ISSUE THREAD

**Issue by llKoull** [homebridge/homebridge#2947]
Hello!

I purchased 3 Shelly devices in Amazon modified to work with Homekit (https://www.amazon.com/-/es/HomekitBG-Persiana-enrollable-compatible-HomeKit/dp/B085HKH8LR/ref=sr_1_9?__mk_es_US=ÅMÅŽÕÑ&dchild=1&keywords=homekitbg&qid=1625174053&sr=8-9) those relays were working perfectly until i installed my raspberry Pi with the latests version of homebridge.

I don't know if it's a coincidence but is there some kind of compatibility issue between different homekit devices and the homebridge?

It's strange because those shelly devices are not connected to the homebridge they are directly connected to my network trough Wi-Fi and they were recognized by the homekit app (i were using them since January with no problem). But now they are getting disconnected all the time and doesn't work. 
I also have 38 Philips HUE lights and all of them are still working perfectly, Only the Shelly relays are getting disconnected.

I don't know if someone had the same problem with any device.

Thanks and best regards!

**Comment by mrfatboy** [comment]
How is the pi connected? Wifi or lan? 

If wifi, could it be causing interference?

Are you using dhcp for all devices on your router? Maybe try static ip🤷‍♂️

If you disconnect the Pi do the Shellies still drop from network?

**Comment by llKoull** [comment]
Hi @mrfatboy!

Thanks for your answer! My pi is connected via ethernet there are no interferences, the shelly devices are connected via wifi (they use the 2.4Ghz network).

It’s true that i’m using DHCP, i can try to assign static IPs to those devices.

Yes, if i disconnect the Pi, the shellies are still disconnected :s That’s because i said that it could be a coincidence but it all started when i connected the homebridge :o

**Comment by llKoull** [comment]
Hi!

I finally understood the problem and i know how to reproduce it but i don't know why is it happening.

If i plug in the homebridge when the shelly devices are already plugged in, all the shelly devices stop working, but if i plug in the homebridge first and the plug in the shelly devices, all is working perfectly.

The problem is that each time that i have to reboot the homebridge (because of an update, for example) i must disconnect and connect all my shelly devices again.

There is some kind of incompatibility between those devices 😮

Thanks!

**Comment by llKoull** [comment]
I’m still having the same issue 😟
