### ISSUE TITLE
Homebridge wifi doesn't show up :(

### ISSUE THREAD

**Issue by margzmi** [homebridge/homebridge#2948]
**Describe Your Problem:**
 I flashed my 32g sd card using both ways (Etcher and PI Imager) but none of them worked. The Homebridge wifi doesn't appear in my list of wifi around :/ I have a PI3+. Thank you very much for helping me

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**:  1.0.23
* **Operating System**: **Raspbian** / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by yukipastelcat** [comment]
I got the same issue, managed to manually connect to wifi via creating config in hb-config and then running `sudo nmcli con up "name of config"`, but unable to access UI neither via homebridge.local, nor via IP address.
