### ISSUE TITLE
Suddenly no NPM installed: npm: command not found

### ISSUE THREAD

**Issue by jeankone** [homebridge/homebridge#2949]
**Describe Your Problem:**
Today i tried upgrading homebridge-hue to the latest version which added the dependency for Node.js 14.17.2. So i tried upgrading it via hb-config which threw following error:

**Logs:**
```
pi@homebridge:/var/lib/homebridge $ sudo hb-config
Updating Node.js to LTS, please wait...
Installed: v14.17.1
Current Node.js LTS: v14.17.2
Updating Node.js to v14.17.2...
/usr/local/sbin/hb-config: 203: /usr/local/sbin/hb-config: npm: not found

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Node.js v14.17.1
/usr/local/sbin/hb-config: 208: /usr/local/sbin/hb-config: npm: not found
npm 
Node.js updated to v14.17.2
Rebuilding modules...
sudo: npm: command not found
```

**Environment:**

* **Node.js Version**: 14.17.1
* **NPM Version**: seems to be none
* **Homebridge Version**: 1.3.4
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by CooperCGN** [comment]
Same problem, I am completely lost :(

**Comment by jeankone** [comment]
@CooperCGN
```
sudo hb-service update-node
```

And a reboot solved it for me. Hope it'll help you out, too
