### ISSUE TITLE
can not update node

### ISSUE THREAD

**Issue by cabrandon** [homebridge/homebridge#2950]
I am trying to update the node. I use "sudo hb-service update-node".  I am prompted for my homebridge password.  I am entering in the correct password.  The utility is rejecting it.  Therefore the only way to update the node is to rebuild my machine.  The node has been getting updated rather frequently.  I am not going to continue rebuilding my machine twice a week just to update the node. Need to know what is going on.  Last attempt of from a clean install.  The password is admin. It is rejected.

**Comment by oznu** [comment]
The "homebridge" service user does not have a password so you cannot "sudo".

Login with an account that does have `sudo`.
