### ISSUE TITLE
nodejs is already the newest version (14.17.2-1nodesource1)

### ISSUE THREAD

**Issue by bondskin** [homebridge/homebridge#2953]
**Describe The Bug:**
Unable to update nodes from 14.17.2 to 14.17.3

**To Reproduce:**
ran "sudo hb-service update-node " multiple times

**Expected behavior:**
upgrade from 14.17.2 to 14.17.3

[**Logs:**]()
 Updating Node.js from v14.17.2 to v14.17.3...
ℹ Updating from NodeSource...

## Installing the NodeSource Node.js 14.x repo...
....
nodejs is already the newest version (14.17.2-1nodesource1).

**Screenshots:**
<img width="370" alt="Bildschirmfoto 2021-07-10 um 11 25 25" src="https://user-images.githubusercontent.com/55050117/125158449-90b0ec00-e171-11eb-8369-e79d08378900.png">

**Environment:**
* **Node.js Version**: 14.17.2
* **NPM Version**: 7.19.1
* **Homebridge Version**: 1.3.4
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by ebaauw** [comment]
See https://github.com/homebridge/homebridge/issues/2951#issuecomment-876102061.
