### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by lonkaars** [homebridge/homebridge#2958]
I'm trying to write an accessory plugin for homebridge, but it refuses to load it and doesn't provide any meaningful stack trace.

I think I might be missing some settings in my [package.json](https://git.pipeframe.xyz/lonkaars/beken-homebridge/tree/package.json) file because the stack trace looks like it's coming from internal nodejs stuff (maybe some `require()` call?)

The full source is available at <https://git.pipeframe.xyz/lonkaars/beken-homebridge/> (http(s) git clone works without .git extension). Though the [index.ts](https://git.pipeframe.xyz/lonkaars/beken-homebridge/tree/index.ts) and [plugin.ts](https://git.pipeframe.xyz/lonkaars/beken-homebridge/tree/plugin.ts) files are basically empty enough that they shouldn't cause any trouble.

I've also tried using the [homebridge dummy](https://github.com/nfarina/homebridge-dummy) plugin and that one works fine, so I don't think it's necessary to include my config.json file here.

```
[8/4/2021, 1:11:39 PM] ====================
[8/4/2021, 1:11:39 PM] ERROR LOADING PLUGIN homebridge-beken:
[8/4/2021, 1:11:39 PM] TypeError: String.prototype.startsWith called on null or undefined
    at startsWith (<anonymous>)
    at node:internal/errors:811:19
    at Array.filter (<anonymous>)
    at node:internal/errors:809:16
    at prepareStackTrace (node:internal/errors:96:12)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:38)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
[8/4/2021, 1:11:39 PM] ====================
```

* **Node.js Version**: 16.6.0
* **NPM Version**: 7.20.3
* **Homebridge Version**: 1.3.4
* **Operating System**: Arch Linux (kernel 5.13.7-arch1-1)
* **Process Supervisor**: Systemd

**Comment by NorthernMan54** [comment]
Spent about 20 minutes this am trying to get this to work then ran out of time for today.   Got stuck here

```
No plugins found. See the README for information on installing plugins.
Loading 1 accessories...
No plugin was found for the accessory "BekenBridge" in your config.json. Please make sure the corresponding plugin is installed correctly.
```

As my test environment isn't homebridge-ui enabled I needed to hand write the config.json and used this

```
{
  "bridge": {
    "name": "Heisenberg",
    "username": "AA:BB:CC:DD:EE:01",
    "port": 51826,
    "pin": "031-45-154"
  },

  "description": "HomeBridge HTTP Status Control",

  "plugins": [
    "beken-homebridge",
    "BekenBridge"
  ],

  "platforms": [
  ],

  "accessories": [
{
     "accessory": "BekenBridge",
      "name": "Test",
   "address": "ESP_8695EC.local"
  }
  ]
}
```

**Comment by ebaauw** [comment]
Have you tried without 	`"type": "module"` in `package.json`?

**Comment by lonkaars** [comment]
I've followed the homebridge install instructions using the `hb-service` command to set up a systemd service on my development machine. Then I used `sudo npm link` to install the package globally (of course after running `tsc` and setting up the python venv). It finds the package and tries to load it, but then crashes and doesn't load the plugin. I'm not sure if this is the intended way to install development plugins in homebridge, but it's one solution I found on reddit and it seemed to work fine.

> Have you tried without `"type": "module"` in `package.json`?

It's already in the package.json file, and afaik it's required because I'm using es6 `import`/`export` statements

**Comment by NorthernMan54** [comment]
First issue I found, not a biggie but a bit of a pain is the name of the package/install directory.  It needs to start with homebridge-

Now stuck here

```
git clone  https://git.pipeframe.xyz/lonkaars/beken-homebridge/
Cloning into 'beken-homebridge'...
Heisenberg:Code sgracey$ mv beken-homebridge/ homebridge-beken
Heisenberg:Code sgracey$ cd homebridge-beken/
Heisenberg:homebridge-beken sgracey$ npm install
npm WARN deprecated node-pre-gyp@0.17.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

added 162 packages, and audited 163 packages in 27s

37 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Heisenberg:homebridge-beken sgracey$ npm run build

> homebridge-beken@0.1.0 build
> tsc

Heisenberg:homebridge-beken sgracey$ cd
Heisenberg:~ sgracey$ ./homebridge 
Initializing HAP-NodeJS v0.9.4...
Loaded config.json with 1 accessories and 0 platforms.
Loaded 0 cached accessories from cachedAccessories.
---
====================
ERROR LOADING PLUGIN homebridge-beken:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/sgracey/Code/homebridge-beken/index.js from /Users/sgracey/npm/lib/node_modules/homebridge/lib/plugin.js not supported.
Instead change the require of index.js in /Users/sgracey/npm/lib/node_modules/homebridge/lib/plugin.js to a dynamic import() which is available in all CommonJS modules.
    at Plugin.load (/Users/sgracey/npm/lib/node_modules/homebridge/lib/plugin.js:129:31)
    at /Users/sgracey/npm/lib/node_modules/homebridge/lib/pluginManager.js:64:24
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/Users/sgracey/npm/lib/node_modules/homebridge/lib/pluginManager.js:62:22)
    at Server.start (/Users/sgracey/npm/lib/node_modules/homebridge/lib/server.js:106:28)
====================
Loading 1 accessories...
No plugin was found for the accessory "BekenBridge" in your config.json. Please make sure the corresponding plugin is installed correctly.
Preparing Advertiser for 'Heisenberg 4534' using bonjour-hap backend!
```

**Comment by lonkaars** [comment]
What nodejs version are you using? ES6 modules have only been introduced in nodejs recently, and they only work in node >=13.0.0

**Comment by lonkaars** [comment]
Turns out you can't use `"type": "module"` in package.json because homebridge loads plugins using the `require()` function in node which doesn't import modules. To fix this you have to remove `"type": "module"` from package.json, and if you're using typescript you can add `"module": "commonjs"` to the compiler options in tsconfig.json so you don't have to manually change all `import`/`export` statements to nodejs `require()` imports.

**Comment by NorthernMan54** [comment]
Can confirm that these tweaks resolved my issue

```
---
Loaded plugin: homebridge-beken@0.1.0
Registering accessory 'homebridge-beken.BekenBridge'
---
Loading 1 accessories...
[Test] Initializing BekenBridge accessory...
reached constructor
getting services
[Test] Accessory BekenBridge returned empty set of services; not adding it to the bridge
```
