### ISSUE TITLE
Warning on invalid value of TargetHeatingCoolingState

### ISSUE THREAD

**Issue by maisun** [homebridge/homebridge#2960]
**Describe Your Problem:**

Warning messages in log file stating "This plugin generated a warning from the characteristic 'Target Heating Cooling State': characteristic value 3 is not contained in valid values array. See https://git.io/JtMGR for more info."
Not sure why value 3 is invalid and just checked the code of HAP looks like value 3 means auto mode:
`export class TargetHeatingCoolingState extends Characteristic {

  public static readonly UUID: string = "00000033-0000-1000-8000-0026BB765291";

  public static readonly OFF = 0;
  public static readonly HEAT = 1;
  public static readonly COOL = 2;
  public static readonly AUTO = 3;

  constructor() {
    super("Target Heating Cooling State", TargetHeatingCoolingState.UUID, {
      format: Formats.UINT8,
      perms: [Perms.NOTIFY, Perms.PAIRED_READ, Perms.PAIRED_WRITE],
      minValue: 0,
      maxValue: 3,
      minStep: 1,
      validValues: [0, 1, 2, 3],
    });
    this.value = this.getDefaultValue();
  }
}`

https://github.com/homebridge/HAP-NodeJS/blob/7db36a4af63655f0c53a626ddf6f4f27665ccefa/src/lib/definitions/CharacteristicDefinitions.ts#L4082

**Comment by donavanbecker** [comment]
See HAP-NodeJS Issue #[896](https://github.com/homebridge/HAP-NodeJS/issues/896)

**Comment by maisun** [comment]
> See HAP-NodeJS Issue #[896](https://github.com/homebridge/HAP-NodeJS/issues/896), [855](https://github.com/homebridge/HAP-NodeJS/issues/855), [815](https://github.com/homebridge/HAP-NodeJS/issues/815), and [888](https://github.com/homebridge/HAP-NodeJS/issues/888)

Hi, thanks for the links but I'm not sure what you're hinting?
I completely understand CurrentHeatingCoolingState can be HEAT and COOL.
However TargetHeatingCoolingState can have four values: OFF; COOL, HEAT and AUTO. I believe 0 is OFF and 3 is AUTO, so I think it's a bug in HomeBridge, or maybe I missed something?

**Comment by maisun** [comment]
From HAP specification: 
<img width="907" alt="Screenshot 2021-08-07 at 22 46 39" src="https://user-images.githubusercontent.com/5745785/128613486-bcd3c848-a659-4f01-9b80-09a64e8707fe.png">

So looks to me like 3 is a valid value......

**Comment by donavanbecker** [comment]
@Supereg

**Comment by oznu** [comment]
Which plugin?

**Comment by maisun** [comment]
> Which plugin? If the plugin has used `setProps` to adjust what modes are available, then this message could appear if the HomeKit client isn't removing the "AUTO" option.

Hi, it’s a fork from homebridge-openhab2-complete plug-in. I just checked setProps isn’t used. I don’t understand what do you mean by “this message could appear if the HomeKit client isn't removing the "AUTO" option.”? The auto option is always there and in fact I never changed it to COOL or HEAT

**Comment by oznu** [comment]
Can you link to the plugin fork you are using?

**Comment by maisun** [comment]
> Can you link to the plugin fork you are using?

The heatercooler implementation:
https://github.com/maisun/homebridge-openhab2-complete/blob/master/accessory/HeaterCooler.js

**Comment by oznu** [comment]
set props is used several times in this file:

https://github.com/maisun/homebridge-openhab2-complete/blob/master/accessory/characteristic/ClimateThermostat.js#L130-L134

I added 4 unit tests to make sure this characteristic is working as expected: 

https://github.com/homebridge/HAP-NodeJS/commit/7c33f9226a2ddf380cf280bda132b3fe48c22c4f#diff-141fa21699d2e874f90e7b50c5520f05879b5d657c4fc585142f3755be0a6ea1R1884-R1965

These passed on all platforms:

https://github.com/homebridge/HAP-NodeJS/actions/runs/1110035296

I'd recommend raising an issue with the plugin author.

**Comment by maisun** [comment]
> set props is used several times in this file:
> 
> https://github.com/maisun/homebridge-openhab2-complete/blob/master/accessory/characteristic/ClimateThermostat.js#L130-L134
> 
> I added 4 unit tests to make sure this characteristic is working as expected:
> 
> [homebridge/HAP-NodeJS@7c33f92#diff-141fa21699d2e874f90e7b50c5520f05879b5d657c4fc585142f3755be0a6ea1R1884-R1965](https://github.com/homebridge/HAP-NodeJS/commit/7c33f9226a2ddf380cf280bda132b3fe48c22c4f#diff-141fa21699d2e874f90e7b50c5520f05879b5d657c4fc585142f3755be0a6ea1R1884-R1965)
> 
> These passed on all platforms:
> 
> https://github.com/homebridge/HAP-NodeJS/actions/runs/1110035296
> 
> I'd recommend raising an issue with the plugin author.

Hi, thanks for looking! The file you referred to is only for thermostat, but the warning is for heatercooler. Is there a way to trace what accessory generate the warning message? Thank you!

**Comment by oznu** [comment]
[TargetHeatingCoolingState](https://developers.homebridge.io/#/characteristic/TargetHeatingCoolingState) is only used by the [Thermostat](https://developers.homebridge.io/#/service/Thermostat) accessory.

The [HeaterCooler](https://developers.homebridge.io/#/service/HeaterCooler) accessory uses [TargetHeaterCoolerState](https://developers.homebridge.io/#/characteristic/TargetHeaterCoolerState) instead (where 3 really isn't a valid value).

**Comment by maisun** [comment]
> [TargetHeatingCoolingState](https://developers.homebridge.io/#/characteristic/TargetHeatingCoolingState) is only used by the [Thermostat](https://developers.homebridge.io/#/service/Thermostat) accessory.
> 
> The [HeaterCooler](https://developers.homebridge.io/#/service/HeaterCooler) accessory uses [TargetHeaterCoolerState](https://developers.homebridge.io/#/characteristic/TargetHeaterCoolerState) instead (where 3 really isn't a valid value).

Thanks! I think I know where to look now, your help is very much appreciated!

**Comment by oznu** [comment]
>  Is there a way to trace what accessory generate the warning message? Thank you!

See https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings, you can turn on debug mode.
