### ISSUE TITLE
How do you stop Homebridge from running at system startup on Raspberry Pi 4 model b?

### ISSUE THREAD

**Issue by SeemXD** [homebridge/homebridge#2965]
I got a raspberry pi for work and other stuff, but I also want to run homebridge on it. So, I installed homebridge on raspberry pi os (not using the flash homebridge os sd card method), and it worked pretty well. however, I do notice sometimes homebridge makes my raspberry pi sluggish running in the background, and I want to stop it from running when I don't want it to. How can I make homebridge not run at system startup, and only when I tell it to? I also want to be able to start and stop homebridge manually myself. I know you can stop homebridge using 'sudo hb-service stop', but does it completely shut down homebridge? and how can i stop it from running at system startup?

**Comment by oznu** [comment]
```
sudo systemctl disable homebridge
```
