### ISSUE TITLE
delete button under plugin has stopped working

### ISSUE THREAD

**Issue by djsmix** [homebridge/homebridge#2967]
when i click on "delete" on a plugin, then its just says "save" i think its after the new update. 

![image](https://user-images.githubusercontent.com/62570067/130668732-bb8c7fb1-50c5-4b34-b4a3-0d78e134896b.png)

Node.js Version | v14.17.5

Npm Version | v7.21.0

raspbian on a PI

Homebridge v1.3.4

**Comment by oznu** [comment]
Delete + Save = remove plugin config.

**Comment by djsmix** [comment]
no, thats why i made this issue - clicking on "edit" and then uninstall that works

**Comment by djsmix** [comment]
@oznu

**Comment by djsmix** [comment]
can this be reopened?
