### ISSUE TITLE
Add MFA / interactive input support

### ISSUE THREAD

**Issue by jgrimard** [homebridge/homebridge#2972]
Request to add MFA support.
Many services are now requiring Multi Factor Authentication and Homebridge currently does not include a good way to have the user input the code they receive through email or SMS when logging in for the first time.  Some plugins are offering a workaround to have the user go into terminal to login, then copy and paste a token from there into the config, then restarting homebridge.  It would be much more user friendly to have some sort of Homebridge feature that allows the user to interactively enter their MFA code.

**Comment by NorthernMan54** [comment]
This is not a homebridge issue per se, as authentication to a service provider is completed at the plugin level.  Please raise your feedback against the appropriate plugin, and even better provide a pull request to the plugin implementing your feature.

**Comment by jgrimard** [comment]
> This is not a homebridge issue per se, as authentication to a service provider is completed at the plugin level. Please raise your feedback against the appropriate plugin, and even better provide a pull request to the plugin implementing your feature.
> […](#)

Can you point me to some example code showing a Homebridge plug-in that interactively requests and uses a string input from a user? I have never seen any Interactive plug-ins other than the config ui plugin. And that one requires restarting homebridge after user input, so it wouldn't work for this issue.

**Comment by oznu** [comment]
See https://developers.homebridge.io/#/custom-plugin-ui and https://github.com/homebridge/plugin-ui-utils

If your looking for an example, the Ring plugin uses this to exchange a username, password and 2FA code for a token.

**Comment by jgrimard** [comment]
@oznu 
Thank you very much.  I found the example code in the Ring plugin as you suggested.  I didn't see that when I looked through the code before, just the CLI interface.  This is great!
