### ISSUE TITLE
Remote HomeBridge installation won't recognize my local network devices

### ISSUE THREAD

**Issue by marloostudio** [homebridge/homebridge#2977]
I have installed and ran the HomeBridge on my Macbook via local network and it worked pretty well, however since sometimes i take my laptop with me the home bridge obvisouly stops working. 
As a solution, I tried to set up the homebridge on a remote Cloud server like DigitalOcean, however since it only scans the local network, it won't add any devises to the home. please let me know what would be the best solution.

**Comment by scotho3** [comment]
you could do this with a VPN on your router to a DO droplet for instance

sorry - late to the party 😢

**Comment by PaTall** [comment]
Tailscale works great.  No charge and easy set up,secure. Tailscale.com

**Comment by 0PandaDEV** [comment]
How can I do it over tailscale I have Homebridge installed on a Raspberry Pi 5 with tailscale on it and I selected tailscale0 which is the network interface to accept homebridge connections.

![image](https://github.com/homebridge/homebridge/assets/70103896/5f796de4-58cd-47b9-96b5-a720aa2577a6)

and I'm trying to connect to it over my iPhone, which is also in the same tailnet, but it just does not connect.

![IMG_3428](https://github.com/homebridge/homebridge/assets/70103896/788aed30-d09e-484b-9c0e-3d1c16d2ce14)

**Comment by JCBird1012** [comment]
@0PandaDEV I believe the issue you’re seeing is expected because WireGuard (and Tailscale by extension) doesn’t pass multicast traffic - which is (sometimes, maybe always?) necessary for facilitating HomeKit. 

I’m sure there are _rare_ circumstances where things work over WireGuard but I wouldn’t count on it being the norm.
