### ISSUE TITLE
Homebridge & Accessories "No Response", ONLY when AWAY from home :(

### ISSUE THREAD

**Issue by achiskon** [homebridge/homebridge#2978]
Hi all, 

This has been driving me nuts... 

When I am away from home (home hub is Homepod Mini), the homebridge & accessories will eventually become unreachable. The Philips Hue and nanoleaf accessories work perfectly.

This does not happen always, if I restart homebridge, or homepod mini, it will most probably work for some time, but after a few hours it will again go dark. The second I am back at home and connected to WiFi, everything lights up again and works as expected, until I again leave and try to control them via WAN.

It most probably is something related to Bonjour/HAP and communication between homebridge and Homepod Mini, but I really haven't made any progress in understanding what is happening. Switching to ciao did not help. Updating homepod mini with iOS 15 did not seem to change a thing. I am wondering whether my router could be the problem (Huawei AX3 Pro Wifi 6)

My use case with homebridge is only away from home so it has been pretty frustrating.

**Comment by nixmeer** [comment]
The device that created the home in the home app and added the bridge. In my case, it's an iOS 15 iPhone and it cannot  connect (all device in the home app show "no response") but my Mac on big sur and my girlfriend's iOS 14 iPhone still work perfectly. I cannot check the behavior on my iOS 15 iPhone being in the local network since I am not at home, but there might be an issue with the home app on iOS 15, maybe in combination with the hub and homebridge.

**Comment by njuart** [comment]
Noticed the same issue, but until some time it was not a thing, it started most likely a couple of weeks ago, maybe month latest. I have ATV as a hub, and all my devices are on the latest OS 15.1, as I also take part in beta. So while I'm away from home, I open Home app and a few times a day I see all my HB devices are No Response, native Homekit devices are ok. Only thing that fixes this is HB restart. I use ciao as advertiser, if it's relevant. Nothing specific was done to my router recently (ASUS RT-AX86U), just regular firmware update.

**Comment by nixmeer** [comment]
Well, thee automations do work again most of the time, maybe iOS 15.0.2 made some improvement there?

**Comment by achiskon** [comment]
To anyone still following this, I think the problem appears resolved since upgrading home hub (homepod mini) to iOS 15.

**Comment by behradmoini** [comment]
So I got it to work by updating Apple TV (my hub) to the beta version public and everything worked with all my iPhones including 15 pro max and so on

it’s the Apple TV that bugs the system when I didn’t have it turned on all worked as well
