### ISSUE TITLE
Characteristic 'Heating Threshold Temperature' Throws A Warning When Setting To 4.5 Celsius

### ISSUE THREAD

**Issue by RampageTiger** [homebridge/homebridge#2980]
**Describe The Bug:**

Nest sets safety temperature to 4.5 Celsius which is a valid temperature. However, HomeBridge still sends a warning says it's illegal because it's below 9. HomeBridge should check whether it's Celsius or Fahrenheit then check the value. 

**To Reproduce:**

Use Celsius in IOS.

**Expected behavior:**

Successfully sets safety temperature to 4.5 Celsius which is a valid temperature. 

[**Logs:**]()

[homebridge-nest] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 4.5 exceeded minimum of 9. See https://git.io/JtMGR for more info.

**Comment by bwp91** [comment]
This would need to be and indeed has already been reported to the developer of the nest plugin.

See https://github.com/chrisjshull/homebridge-nest/issues/389

> the correct solution here is to ignore the warning. It is just a consequence of a quirk of the way Nest works. It does not mean anything is wrong.

**Comment by RampageTiger** [comment]
Submitted a new issue to homebridge-nest. Close this one. https://github.com/chrisjshull/homebridge-nest/issues/444
