### ISSUE TITLE
Hide Accessory from HomeKit.

### ISSUE THREAD

**Issue by jerzykolysz** [homebridge/homebridge#2982]
Hi, I have situation 
I have Somfy Tachoma and roller shutters working perfectly directly with Tachoma certified Integration.
But some Somfy Devices are not certified with Apple so I bring HomeBridge with Tacoma plugging to resolve issue but.....
I have all accessories once again plus those unsupported. But I want use HomeBridge only for those officially unsupported so. 
Please add single bit condition show/hide from HomeKit, or publish/unpublish to HomeKit.

**Comment by G0sch** [comment]
Why do you not use the config of the homebridge-tahoma plugin to exclude the devices?

from the config options:



exclude | String[] | [] | optional, list of protocols (hue,enocean,zwave,io,rts), ui name, widget name or _device name to exclude_
-- | -- | -- | --

**Comment by donavanbecker** [comment]
Pull request are welcomed.

**Comment by jspiro** [comment]
If I were able to I'd do so :-)

I simply feel this request should be left open, since it still seems quite relevant and reasonable. The Issues list is quite short, so maybe someone with the skills will be able to contribute the fix if they saw it in the Open list.

**Comment by donavanbecker** [comment]
I will reopen again, and if someone opens a PR, perfect! If not it will go stale again.

**Comment by JurgenLB** [comment]
Like @G0sch says.
From wiki homebrige;
{
    "platform": "LifxLan", <--- comma
    "name": "Lifx", <--- comma
    "ignoredDevices" : ["xxxxxxxx", "yyyyyyyyy"] <-- no comma
}
I have used “ disabledPlugins” in the past and that works for troubleshooting. So maybe you can use “ignoredDevices”

**Comment by MoTechnicalities** [comment]
The Ring plugin is a major plugin. But the developer has no way to prevent fake devices from entering HomeKit! For example: each Ring light bulbs exposed a useless fake motion sensor to HomeKit. The developer did update the plugin to remove them, but now Ring broke that ability by altering the accessory data with no way for him to distinguish accessory types. We need an accessory blockade option at the Homebridge handling level before they get to HomeKit. Also, we need to be able to alter aerating device types, such as the ability to expose switchable bulbs to HomeKit as Outlets.

**Comment by Andy589** [comment]
I guess i'm the 1 other weirdo who wants to be able to control what devices get shared from homebridge to homekit. Not everything that gets pulled in from the various integrations is something I want shared with homekit as there can be issues with that device or its not even relavent to my house. A grungy example of what would be great to see in the homebridge UI is hopefully attached. Thank you!


![Screenshot 2023-11-27 130104](https://github.com/homebridge/homebridge/assets/43658146/1d187cbb-5839-48d0-a3f2-a86246b6e092)

**Comment by donavanbecker** [comment]
as the plugin developer to add it to the plugin

**Comment by Andy589** [comment]
For each plugin I use? Why wouldn't this just be integrated into homebridge so it works with any accessory regardless? It seems obvious to me that one would want the ability to control which accessories homebridge shares with homekit.

**Comment by donavanbecker** [comment]
homebridge and homebridge ui are two different things. and what you are looking at is homebridge ui

**Comment by Andy589** [comment]
That makes sense, thank you for the explanation.
