### ISSUE TITLE
No response after update to v1.3.5

### ISSUE THREAD

**Issue by RCdiy** [homebridge/homebridge#2985]
None of the accessories respond after the up date. I’ve restarted (disconnect power) the Pi and the AppleTV. I’ve also tried going back to the previous version. 
The log is error free other than an occasional heartbeat drift error. 

**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

[**Logs:**]()

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other
* **Process Supervisor**: Systemd / init.d / pm2 / launchctl / Docker / hb-service / other / none

**Comment by RCdiy** [comment]
Config ui @rbswift

**Comment by RCdiy** [comment]
[homebridge.log.txt](https://github.com/homebridge/homebridge/files/7314861/homebridge.log.txt)

**Comment by rbswift** [comment]
Hmmmm heaps of people use configui so doubt that’s the cause

**Comment by nixmeer** [comment]
Just for my interest, is the main iOS device running iOS 15? How about iOS 14 devices or macOS Big Sur?

**Comment by nixmeer** [comment]
Ok. If this occurs again, maybe you can check if no response is also displayed on iOS 14 or Big Sur devices. Just for references, if that's only true for my case or if that's a general problem.

**Comment by RCdiy** [comment]
Question 
If I reinstall homebridge and reuse the config file do I usually have to delete the bridge in HomeKit and add it back or is the move transparent to HomeKit. 
I had to delete the bridge and add it back.
