### ISSUE TITLE
Home does not work on ipad4 IOS 10.3.3 and iphone 5s ios 10.3.3

### ISSUE THREAD

**Issue by 00enterausername00** [homebridge/homebridge#2987]
The same problem was described in #2647.
I booted in debug mode with the flag DEBUG = HAP-NodeJS:*. When I connect from a device with 10.3.3, nothing happens in the logs. Everything was working fine before.

**Environment:**

* **Node.js Version**: v14.18.0
* **NPM Version**: v6.14.15
* **Homebridge Version**: v1.3.5
* **Operating System**: macOS High Sierra

**Comment by definitec** [comment]
I have the same issue.

Environment:

Node.js Version: v14.17.0
NPM Version: v6.14.13
Homebridge Version: v1.3.4
Operating System: Raspbian GNU/Linux Stretch (9)
