### ISSUE TITLE
Can’t update node

### ISSUE THREAD

**Issue by Tapsel99** [homebridge/homebridge#2992]
I can't update node via Homebridge command sudo hb-config and if I try via ssh its stuck on downloading for ages
pi@homebridge:~ $ sudo hb-config
Updating Node.js to LTS, please wait...
Installed: v10.24.1
Current Node.js LTS: v14.18.1
Updating Node.js to v14.18.1...
Downloading to /tmp/tmp.k88zxPV5g4/node-v14.18.1-linux-armv6l.tar.gz ...
-=O#- #   #    #                                                               
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to unofficial-builds.nodejs.org:443 
Failed to download node-v14.18.1-linux-armv6l.tar.gz. See logs above.
pi@homebridge:~ $ 

node -v v10.24.1

npm -v 6.14.12

pi@homebridge:~ $ homebridge -V
Initializing HAP-NodeJS v0.9.6...
1.3.5

hb-service -v v4.41.2

**Comment by hwgilbert16** [comment]
What does `uname -a` show?
