### ISSUE TITLE
Homebridge Config Page Stops Responding After ~1.5 Days

### ISSUE THREAD

**Issue by alexiscordova** [homebridge/homebridge#3004]
**Describe The Bug:**

From a fresh restart, the Homebridge UI (homebridge-config-ui-x, I imagine) at https://homebride.local stops responding and I get a "Server Not Found" error in my browser. The devices connected to HomeKit via Homebridge **are not impacted** and still seem to work fine, but I cannot reach the config page and need to force restart my Raspberry Pi. However, if I go to the IP address of the Pi, the config UI loads fine.

Connecting to the Pi via ssh (`ssh pi@homebridge.local`) also times out; connecting via ssh to the IP address works fine.

**To Reproduce:**

- Boot Homebridge
- Wait a day or so

(Sorry this is so basic, but this is essentially what happens)

**Expected behavior:**

homebridge.local should stay up

[**Logs:**]()

The logs don't show anything happening on the DNS level, but I can post them if needed.

```
Secondary Homebridge Logs here
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**:  v12.18.3
* **NPM Version**: 6.14.8
* **Homebridge Version**:  1.3.5
* **Operating System**: Raspbian
* **Process Supervisor**: hb-service

**Comment by hwgilbert16** [comment]
Post your logs and config, it is very helpful for diagnosing any issues you may have.

**Comment by jarvismeier** [comment]
I have a similar issue and can't see anything it the home bridge logs.  It seems like its not doing the mdns broadcast for homebridge.local.  This happened after the upgrade to 1.3.6

**Comment by alexiscordova** [comment]
@jarvismeier this ended up resolving itself, oddly enough, which makes me think a plugin was the culprit. What do you have installed?

**Comment by ValoV83** [comment]
I've had this same issue for sometime as well. 

homebridge.local is reachable for around 1.5 days then I have to use the IP address of my pi in my browser to access homebridge config page. 

If I restart my pi completely homebridge.local becomes reachable again for around the same length of time as before.

**Comment by ebaauw** [comment]
If you’re running on a memory-challenged Pi (less than 1GB), double-check it’s not running out of swap space (e.g. using `htop`).  I suspect there’s a small memory leak in Homebridge/HAP-NodeJS, at least, I see increased memory usage by the NodeJS processes.  Not significant enough to cause issues on larger Pi systems, but bad enough to cause issues on my (512MB) Pi Zero 2 W, even when running Raspberry Pi OS Lite.  NodeJS is quite demanding, and with `hb-server`, the main Homebridge and a child bridge, you have already three of those running.  And then another one for `npm` when you update a plugin from the UI.

To increase the swap space, edit `/etc/dphys-swapfile` and reboot.

**Comment by ValoV83** [comment]
> If you’re running on a memory-challenged Pi (less than 1GB), double-check it’s not running out of swap space (e.g. using `htop`). I suspect there’s a small memory leak in Homebridge/HAP-NodeJS, at least, I see increased memory usage by the NodeJS processes over time. Not significant enough to cause issues on larger Pi systems, but bad enough to cause issues on my (512MB) Pi Zero 2 W, even when running Raspberry Pi OS Lite. NodeJS is quite demanding, and with `hb-server`, the main Homebridge and a child bridge, you have already three of those running. And then another one for `npm` when you update a plugin from the UI.
> 
> To increase the swap space, edit `/etc/dphys-swapfile` and reboot.

I'm using a Pi 3. Don't think this will effect me.

**Comment by ValoV83** [comment]
Here are my logs 

[homebridge.log.txt](https://github.com/homebridge/homebridge/files/7618936/homebridge.log.txt)

**Comment by bwp91** [comment]
> Here are my logs
> 
> [homebridge.log.txt](https://github.com/homebridge/homebridge/files/7618936/homebridge.log.txt)

I see this in your logs

```
TypeError: Class extends value undefined is not a constructor or null
```

If you’re running the rpi image, you should follow these steps here:
https://github.com/homebridge/homebridge/issues/3002#issuecomment-955994607

**Comment by ValoV83** [comment]
> > Here are my logs
> > [homebridge.log.txt](https://github.com/homebridge/homebridge/files/7618936/homebridge.log.txt)
> 
> I see this in your logs
> 
> ```
> TypeError: Class extends value undefined is not a constructor or null
> ```
> 
> If you’re running the rpi image, you should follow these steps here: [#3002 (comment)](https://github.com/homebridge/homebridge/issues/3002#issuecomment-955994607)

Thanks for your reply. I've applied that fix already, I'm running node.js v16.13.0 and npm v8.1.3

This error of losing homebridge.local was already happening before I updated node and npm.

**Comment by ValoV83** [comment]
Still not resolved
