### ISSUE TITLE
Updating node to v16 - armv6 error

### ISSUE THREAD

**Issue by athal7** [homebridge/homebridge#3005]
```
# Fatal error in , line 0
# Liftoff bailout should not happen. Cause: Armv6 not supported
```

_Originally posted in https://github.com/homebridge/homebridge/issues/3002#issuecomment-956263450_

**Comment by Jdemuren** [comment]
Same issue here. (raspberry pi Zero W)

**Comment by athal7** [comment]
@pietje63

**Comment by pietje63** [comment]
To add to this discussion
Same issue here, also Pi zero
- no issue on update (via hb-config or hb-service)
- no issue on update of npm 
- no issue on rebuilding
issue arises on restart of homebridge

Getting back to old node is possible (sudo hb-service update-node 14.18.1), though support drops (also by plugins)

**Comment by EnhancedMind** [comment]
using `--no-expose-wasm` as node argument did the trick for me. The command instade of `node .` is `node --no-expose-wasm .`

**Comment by wgxdz** [comment]
> using `--no-expose-wasm` as node argument did the trick for me. The command instead of `node .` is `node --no-expose-wasm .`

Where should we put this parameter?

**Comment by napdan** [comment]
> 

Same question here ¯\_(ツ)_/¯

**Comment by EnhancedMind** [comment]
> > using `--no-expose-wasm` as node argument did the trick for me. The command instead of `node .` is `node --no-expose-wasm .`
> 
> Where should we put this parameter?


I guess you start your code by typing `node .` or `node index.js` or something like that into your command line
so instead type `node --no-expose-wasm .` or `node --no-expose-wasm index.js`

**Comment by Haxim** [comment]
> > using `--no-expose-wasm` as node argument did the trick for me. The command instead of `node .` is `node --no-expose-wasm .`
> 
> Where should we put this parameter?

I edited /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js and changed the first line
`#!/usr/bin/env node`
to
`#!/usr/bin/env -S node --no-expose-wasm`

Depending on how you start homebridge, you may need to make the same edit to /usr/local/bin/homebridge as well

**Comment by superevr** [comment]
> I edited /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js and changed the first line
> `#!/usr/bin/env node`
> to
> `#!/usr/bin/env -S node --no-expose-wasm`

This worked for me, but was overwritten in the next update. Wouldn't mind seeing this issue re-opened.

**Comment by dlewanda** [comment]
My guess here is that we're boned on using official builds of Node.js with the Pi Zero per [this link](https://hassancorrigan.com/blog/install-nodejs-on-a-raspberry-pi-zero/). I'm dropping back to 14.9.0 for now to see if that will get me where I need to be and decide whether to shell out for a Pi with a different version of ARM by the time [Node.js v14 is dropped](https://nodejs.org/en/about/releases/) in April 2023.
