### ISSUE TITLE
Problem with update to 1.3.6

### ISSUE THREAD

**Issue by TheBassfly** [homebridge/homebridge#3009]
Hey Together

I tried to update my Homebridge to V 1.3.6

But it failed every time.
My first try via the config-ui resulted in an error with the some sort of token which was called to be missing.

Then I tried it via Terminal. This worked but resulted in a homebrdge not starting. so I switched back to 1.3.5 which then worked.

After that I tried it again via the config-ui and now the update runs but the Homebridge stuck in the reboot so I opened terminal again jumped back to 1.3.5.

Did I do something wrong?

**Comment by bwp91** [comment]
Can you paste the output/errors you receive when trying to update to 1.3.6?

**Comment by TheBassfly** [comment]
That's the biggest problem. I don't see any outputs, as the system seems to stuck after a reboot.

**Comment by bwp91** [comment]
Assuming you are running Homebridge with some *standard* setup eg the pi image you can try to update homebridge with this terminal command

```
sudo npm install -g --unsafe-perm homebridge
```

does this result in any error? If it works, you can restart homebridge with

```
sudo hb-service restart
```

or view the log file with any homebridge loading errors with

```
sudo hb-service logs
```

**Comment by TheBassfly** [comment]
Thank you but the problem ist not the installation.

1.3.5. Still works but 1.3.6 fails. That's the essence for me now.

**Comment by bwp91** [comment]
Okay, but there would normally be something in the homebridge log file as to why it keeps rebooting on 1.3.6?

**Comment by TheBassfly** [comment]
Maybe you have a clue how I can reach these logs when the system is not reachable.

**Comment by bwp91** [comment]
Yes if you can SSH into the system you can run this command to see the homebridge log

```
sudo hb-service logs
```

**Comment by ahwman** [comment]
I’m also getting errors trying to update from 1.3.5 to 1.3.6

CMD: pm install
-g homebridge@1.3.6
TypeError:
Class extends value undefined is not a constructor or null
at Object.<anonymous>
(/usr/local/lib/node modules/pm/node modules/socks-proxy-age
nt/dist/agent.js:114:44
at Module.
compile (node: internal/modules/cjs/loader:1101:14
at Object.Module.
extensions. . js (node: internal/modules/cjs/loader:1153:10)
at Module.load (node: internal/modules/cjs/loader:981:32
at Function.Module. load (node: internal/modules/cjs/loader:822:12
at Module.require (node: internal/modules/cjs/loader:1005:19)
at require (node: internal/modules/cjs/helpers:102:18)
at object.<anonymous> (/usr/local/lib/node modules/pm/node modules/socks-proxy-age
nt/dist/index.js:5:33)
at Module.
compile (node: internal/modules/cjs/loader:1101:14
at object.Module. extensions..js (node: internal/modules/cjs/loader:1153:10
at Module.load (node: internal/modules/cjs/loader:981:32
at Function.Module. load (node: internal/modules/cjs/loader:822:12
at Module.require (node: internal/modules/cjs/loader:1005:19)
at require (node: internal/modules/cjs/helpers:102:18)
at Object.<anonymous>
(/usr/local/lib/node modules/pm/node modules/make-fetch-happ
en/lib/agent. js:161:25)
at Module. compile (node: internal/modules/cjs/loader:1101:14
Command failed. Please review log for details.

**Comment by bwp91** [comment]
@ahwman this looks like a failed node update.

Run the commands here:

https://github.com/homebridge/homebridge/issues/3002#issuecomment-955994607

Then try updating homebridge again

**Comment by ahwman** [comment]
> @ahwman this looks like a failed node update.
> 
> Run the commands here:
> 
> [#3002 (comment)](https://github.com/homebridge/homebridge/issues/3002#issuecomment-955994607)
> 
> Then try updating homebridge again

That did the trick, thank you so much!  Is it ok to upgrade Node back to v16.13.0 or should I stay at v14.18.1?

**Comment by bwp91** [comment]
The commands from the link should have updated your node back to 16.13.0.

The main necessity is to update npm to the latest version before updating to node 16, which is what those commands do in order.

**Comment by TheBassfly** [comment]
I think I got the Problem. It seems, that the new Update need more Space and the 16GB Card of my Raspberry runs out of memory.  I saw one Error Message pointing this out, when I tried to update NPM to the latest Version.
Tomorow I wil have a 64GB Card and move the system to this one, and then I will have a look again.

**Comment by ahwman** [comment]
> The commands from the link should have updated your node back to 16.13.0.
> 
> The main necessity is to update npm to the latest version before updating to node 16, which is what those commands do in order.

Thanks, I had only completed the first step and didn’t see the others.  All is well now.  Thanks again for your help!

**Comment by TheBassfly** [comment]
Allright.

My Problem is solved. It was the low Disk Space on the SD Card of my Raspberry.

Now with a bigger Card everything seems to work again.
