### ISSUE TITLE
Server issue after UI upgrade

### ISSUE THREAD

**Issue by Stetocasa** [homebridge/homebridge#3018]
### Current Situation

Hello,
today I updated the newest UI but during the installation something was wrong and now I cannot access by Broswer
I can access by terminal but all command doesn't works
I don't have backup I need to recover at minimum my json to copy an save for potential reinstallation
<img width="650" alt="Schermata 2021-11-25 alle 20 17 04" src="https://user-images.githubusercontent.com/70729310/143492079-256b8b5f-ded4-46cf-bb06-007abc96743d.png">
 

### Logs

```markdown
pi@homebridge:~ $ sudo hb-service start
sudo: hb-service: command not found
pi@homebridge:~ $ hb-service start
-bash: /usr/local/bin/hb-service: Permission denied
pi@homebridge:~ $
```

### Configuration

```json
pi@homebridge:~ $ /var/lib/homebridge/config.json
-bash: /var/lib/homebridge/config.json: No such file or directory
```

### Environment

- OS: PI 3+
- Software: Homebridge 1.3.8
- Node:v14.18.1
- npm:8.1.0

### Process Supervisor

not applicable

**Comment by saltysmith1** [comment]
I'm having the same issue was updating the ui to the latest version and it crashed, Can't access via homebridge.local or the IP address and currently don't have a backup.

**Comment by Stetocasa** [comment]
> I'm having the same issue was updating the ui to the latest version and it crashed, Can't access via homebridge.local or the IP address and currently don't have a backup.
> 
> 

Are you able to access in ssh?

**Comment by Stetocasa** [comment]
Tried to install again the UI from SSH, see the log:

`pi@homebridge:~ $ sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-config-ui-x' -> '/usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-25T20_54_27_015Z-debug.log
pi@homebridge:~ $ `

**Comment by saltysmith1** [comment]
> > I'm having the same issue was updating the ui to the latest version and it crashed, Can't access via homebridge.local or the IP address and currently don't have a backup.
> > 
> > 
> 
> Are you able to access in ssh?

Yep tried to do a restart and got 

hb-service: command not found

Then tried config and tried to reinstall latest version and got the same error as you pretty much

**Comment by saltysmith1** [comment]
Looks like the same thing happened last year also 
https://github.com/oznu/homebridge-config-ui-x/issues/969?_pjax=%23js-repo-pjax-container

**Comment by Stetocasa** [comment]
> Looks like the same thing happened last year also 
> 
> https://github.com/oznu/homebridge-config-ui-x/issues/969?_pjax=%23js-repo-pjax-container

I'm not understanding how solve it. Await a new release le reflash the sd is the unique way
