### ISSUE TITLE
Ability to install without using npm -g

### ISSUE THREAD

**Issue by fluffy-critter** [homebridge/homebridge#3028]
### Current Situation

Right now, all of the installation instructions require giving the homebridge user superuser permissions so that it can install via `npm -g`, and the automatic upgrade functionality within homebridge itself also assumes `npm -g`. However, this is fairly unsafe especially if you're running homebridge on a machine which runs multiple purposes, and it's also unnecessary as packages can simply be installed into the application's own little workspace/sandbox by installing without `-g`. In my own setup I run homebridge in this way, and just have to manually upgrade my packages from the command line instead.

### Proposed Change

Make it an option to use `npm install` instead of `npm -g install` to allow better security practices on a multiuser system.

**Comment by ebaauw** [comment]
I second the request to be able to install Homebridge locally, without using `npm -g`.

Note however, that Homebridge itself does **not** require superuser privileges, nor does the UI.  The UI uses password-less `sudo` for `npm -g`, which `hb-service` sets up in `/etc/sudoers`:
```
homebridge    ALL=(ALL) NOPASSWD:SETENV: /usr/sbin/shutdown, /usr/bin/npm, /usr/bin/npm, /usr/local/bin/npm
```
(not sure why there's two entries for `/usr/bin/npm`).

**Comment by fluffy-critter** [comment]
Yes, I didn't mean to imply that homebridge itself needs sudo access, just that its updater does - and it shouldn't.

**Comment by NorthernMan54** [comment]
With my setup I have been using this npm config for years to remove the need for sudo on installation.

```
cat ~/.npmrc 

global-style=true
prefix=/home/homebridge/npm
```

And I have sudo false in the homebridge-config-ui-x config.

**Comment by fluffy-critter** [comment]
Ah, that's perfect! I'm not very versed in npm (since I don't do much JS dev) so it'd be really cool if that could be added to the documentation as an option.
