### ISSUE TITLE
Windows Hyper-V Installation

### ISSUE THREAD

**Issue by meluvalli** [homebridge/homebridge#3031]
### Current Situation

Any way to "install" permanently in VM?  I have to have the ISO always set to boot to launch. 

This also causes docker not to remember password change (sudo passwd docker).

Also, would like to "secure console" so login is required on boot.

### Logs

```markdown
N/A
```

### Configuration

```json
{
    "bridge": {
        "name": "HomeBridge",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

### Environment

- OS: Windows Hyper-V
- Software: HomeBridge-VM
- Node: v16.13.1
- npm: v8.1.2

### Process Supervisor

Docker (Mention image name in `Additional Context`)

**Comment by oznu** [comment]
Doing a manual install Homebridge on your favourite Linux distribution is would be the best way to meet your requirements.

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux

Setup your Hyper-V VM using the same network settings the wiki guide says too.
