### ISSUE TITLE
Cannot connect to Homebridge Hotspot

### ISSUE THREAD

**Issue by adriankae** [homebridge/homebridge#3032]
### Current Situation

Hi, 

Since for an unknown reason my installation of homebridge stopped working suddenly after around a year of no issues I'm trying to set up a new homebridge.

The problem: Homebridge hotspot doesn't show up so I cannot connect to homebridge and enter WIFI PW. It shows homebridge IP of 127.0.1.1 for after the setup which I find odd.

What I do: 
Follow the Getting started with Pi Imager.
Connect the Pi to a monitor.

I tried 3 different Pi 0w and one Pi 4, two different SD Cards and several different Power Supplies with up to 12W for Pi 0w and 15W for Pi 4.

### Logs

```markdown
not applicable
```

### Configuration

```json
not applicable
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by everyplace** [comment]
I just ran into this same problem w/ a freshly imaged Pi Zero 2 from the rpi-imager default homebridge image.

**Comment by oznu** [comment]
Thanks for pointing this out.

This should be fixed in the v1.0.28 / 2021-12-12 release.
