### ISSUE TITLE
/usr/local/sbin/hb-config: 200: [: !=: unexpected operator

### ISSUE THREAD

**Issue by jamieburchell** [homebridge/homebridge#3036]
### Analysis

On a fresh flash of Homebridge Raspberry Pi image "Raspbian-Homebridge-v1.0.28" after accessing `hb-config` and choosing the first option to update Node.js the message appears that it is already the latest version. After the message is dismissed this error shows:

```
pi@homebridge:~ $ sudo hb-config
Updating Node.js to LTS, please wait...
Installed: v16.13.1
Current Node.js LTS:
/usr/local/sbin/hb-config: 200: [: !=: unexpected operator
```

### Expected Behavior

No error

### Steps To Reproduce

- Flash Raspbian-Homebridge-v1.0.28
- `sudo hb-config`
- Option 1
- OK

### Logs

```markdown
N/A
```

### Configuration

```json
N/A
```

### Environment

- OS: Raspbian-Homebridge-v1.0.28
- Software:
- Node: 16.13.1
- npm:

### Process Supervisor

not applicable

### Additional Context

The Pi did not have a valid DNS server at the time, so this could have been part of the issue.

**Comment by oznu** [comment]
> The Pi did not have a valid DNS server at the time, so this could have been part of the issue.

Internet access is required for this tool to work properly.
