### ISSUE TITLE
Failed to update Node.js: Command failed: curl -sL https://deb.nodesource.com/setup_16.x | bash -

### ISSUE THREAD

**Issue by StarChild71** [homebridge/homebridge#3043]
### Current Situation

Trying to upgrade Node.js to 16.x from 14.17.2. Have used hb-service before successfully but now it fails. See log.

### Logs

```markdown
pi@raspberrypi:~ $ sudo hb-service update-node
ℹ Updating Node.js from v14.17.2 to v16.13.1...
ℹ Updating from NodeSource...

## Installing the NodeSource Node.js 16.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 https://deb.nodesource.com/node_14.x buster InRelease                                      
Get:2 http://archive.raspberrypi.org/debian buster InRelease [32.6 kB]                           
Get:3 http://raspbian.raspberrypi.org/raspbian buster InRelease [15.0 kB]                   
Reading package lists... Done       
E: Repository 'http://archive.raspberrypi.org/debian buster InRelease' changed its 'Suite' value from 'testing' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
E: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Error executing command, exiting
✖ Failed to update Node.js: Command failed: curl -sL https://deb.nodesource.com/setup_16.x | bash -
```

### Configuration

```json
n/a
```

### Environment

- OS: Raspbian GNU/Linux 10 \n \l
- Software: Homebridge
- Node: 14.17.2
- npm: 8.3.0

### Process Supervisor

hb-service

### Additional Context

What am I doing wrong?

**Comment by Cesco117** [comment]
Same issue here, waiting for help :(

**Comment by Cesco117** [comment]
Solution found here : 

First : allow release info change : 

sudo apt-get update --allow-releaseinfo-change

Then you can update Node with : 

sudo hb-service update-node

**Comment by StarChild71** [comment]
> Solution found here :
> 
> First : allow release info change :
> 
> sudo apt-get update --allow-releaseinfo-change
> 
> Then you can update Node with :
> 
> sudo hb-service update-node

This worked, thank you!

**Comment by Pblondin123** [comment]
had same error followed same workaround as 

> Solution found here :
> 
> First : allow release info change :
> 
> sudo apt-get update --allow-releaseinfo-change
> 
> Then you can update Node with :
> 
> sudo hb-service update-node

worked for me as well thanks

**Comment by joaocomarques** [comment]
Didn't work for me. Any additional tip?
