### ISSUE TITLE
Migrate from Cookie to refreshToken method – how to find install path (initial UI install)

### ISSUE THREAD

**Issue by mmorper** [homebridge/homebridge#3044]
### Current Situation

I noticed that this plug has started throwing errors related to authentication. I currently have the cookie method used, but would like to move to the refreshToken method. The instructions are all clear, less one item for this noob... I installed the plugin originally via the UI vs terminal and therefore don't know where the plugin was exactly installed.

If someone could please provide me a bit of guidance on how to find the prior install path, I'd sure appreciate it.

TIA

### Logs

```markdown
NA
```

### Configuration

```json
NA
```

### Environment

- OS: RPiOS Buster (10)
- Software:
- Node: 14.17.0
- npm: 6.14.13

If this helps, Homebridge references the storage path as /var/lib/homebridge

### Process Supervisor

hb-service

**Comment by oznu** [comment]
This is the main homebridge project page, please raise the issue on the plugin's own project page.
