### ISSUE TITLE
HELP - Homebridge stuck on Starting Now. Cannot access anything

### ISSUE THREAD

**Issue by FranciRoosters** [homebridge/homebridge#3045]
### Current Situation

Homebridge wouldn't update to the latest release through the plugin page, so I ran sudo service homebridge stop. After this I would've run sudo -E -n npm install -g homebridge-config-ui-x@latest. Now Homebridge is stuck on Starting Now and there's nothing I can do to sort this out, or at least I have no idea how to.

### Logs

```markdown
Cannot provide logs. Cannot access HB!
```

### Configuration

```json
Cannot provide config. Cannot access HB!
```

### Environment

- OS: N/A
- Software: N/A
- Node: N/A
- npm: N/A
Don't recall this information by heart.

### Process Supervisor

hb-service

**Comment by jamieburchell** [comment]
> After this I would've run sudo -E -n npm install -g homebridge-config-ui-x@latest

So did you run that after stopping the service? That updates homebridge. `sudo service homebridge start` starts the service again.

**Comment by iRayanKhan** [comment]
Closed. This isn't an issue relating to my plugin, and rather a result of updating homebridge. 


I'd suggest opening an issue there, or on their [Discord](https://discord.gg/cwkY6PrHXw) server. 

Please make backups of your config if you haven't already, in the event you have to factory restore.

**Comment by OxbloodUK** [comment]
I have the exact same issue

**Comment by bwalls** [comment]
I had to go in via SSH as noted above to get all the updates in sync.
