### ISSUE TITLE
Hombridge wifi setup

### ISSUE THREAD

**Issue by christianstaerkind** [homebridge/homebridge#3048]
### Current Situation

Hi,

I am trying to setup homebridge on my raspberry pi, however I do have some problems with the wifi setup - it does not appear to connec
![IMG_0977](https://user-images.githubusercontent.com/96787604/147586906-f315f7e4-f958-4be0-b5e5-dd49503578a3.jpeg)

Hope you can help me! Thanks!

### Logs

```markdown
.
```

### Configuration

```json
.
```

### Environment

.

### Process Supervisor

not applicable

**Comment by timrs2998** [comment]
I also have a similar problem with homebridge on raspberry pi being unable to connect to wi-fi. I've gone through the captive portal setup. I confirmed with `sudo nmtui` that the wi-fi connection was setup correctly, but it still doesn't connect. I have Raspberry Pi 3 Model B+ with the latest Raspbian image as of 2021-01-10.
