### ISSUE TITLE
Filtering of logs

### ISSUE THREAD

**Issue by vladimir-aubrecht** [homebridge/homebridge#3053]
### Current Situation

I hit the issue, that I have multiple plugins which are great, but also quite spammy in logs. Those data logged there are not even useful in some cases.

### Proposed Change

To fix the problem of spammy logs, I would suggest introducing some kind of filtering mechanism.

Ideal solution would be if I could enable/disable logging and verbosity per plugin.

**Comment by vladimir-aubrecht** [comment]
Comment to show activity as an issue is still valid.

**Comment by chrisw554** [comment]
Can we open this back up - I think its a great idea.

**Comment by arrmo** [comment]
Agreed here! Would like to filter by plugin, for example.

Thanks!

**Comment by oturn** [comment]
Agreed.

**Comment by Thijsjuh92** [comment]
+1 here!

**Comment by itavero** [comment]
> Ideally please consider adding a button on each plugin to view the logs only for that plugin.

Homebridge itself doesn't have a UI other than the command line output. I think such a feature would belong to [oznu/homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x).

**Comment by arrmo** [comment]
That makes sense - can we move it over there somehow?

Thanks!
