### ISSUE TITLE
Add a time delay to Homebridge autostart

### ISSUE THREAD

**Issue by iBaird44** [homebridge/homebridge#3058]
### Current Situation

Currently I'm using v1.3.9 on a Mac Mini. When the computer restarts the Homebridge platform begins while the bootup status bar is still progressing under the Apple Logo - I know this because I can see when it connects to my iPhone. However this seems to cause an issue with some of my plug ins that need more time after restart before Homebridge should start. Currently I can easily fix the issue by restarting Homebridge again from inside a browser mere seconds after the OSX Finder appears and then all my Plug-ins behave properly.

### Proposed Change

I would benefit from an option that allowed me to select a time delay for the Homebridge to start after computer reboot. 30 seconds would work for me but I have heard of other plugins that need up to 2 minutes after reboot to behave properly.

**Comment by iBaird44** [comment]
I'll add that of the three Plugins I use the third one that shows up in the LOG always works, just not the first 2. So if it's not possible to delay the actual Homebridge start up would it be possible to delay the plugins from loading for a variable amount of time?

**Comment by NorthernMan54** [comment]
I’m not familiar with how OS X manages the startup of various services, but under systemd on Linux you can as part of the service definition put a sleep command to delay startup and/or make the startup dependent on other services.

If you can find a similar approach for OS X it would solve your issue

**Comment by iBaird44** [comment]
I am new to all of this but in my early study I've found that the .json file has the order of startup homebridge startup events in it. First the actual Homebridge is loaded then all the plug-ins, is there a .json command line that would delay the program from continuing for a certain period of time. After Homebridge is up but before the first plug in is loaded.

 {
        "name": "Config",
        "port": 8581,
        "auth": "none",
        "theme": "auto",
        "tempUnits": "c",
        "lang": "auto",
        "platform": "config"
    },
DEALY COMMAND IN HERE!
    {
        "name": "xxxxxxxx",
        "user": "xxxxxxx",
        "pass": "xxxxxxx",
        "host": "xxxxxxx",
        "port": "xxxxxxxxx",
        "model": "2245",
        "refresh": "60",
        "server_port": "3000",
        "keepAlive": "true",
        "devices": [
            {

**Comment by iBaird44** [comment]
Or maybe even a delay before any of the processes begin?

**Comment by iBaird44** [comment]
> I’m not familiar with how OS X manages the startup of various services, but under systemd on Linux you can as part of the service definition put a sleep command to delay startup and/or make the startup dependent on other services.
> 
> If you can find a similar approach for OS X it would solve your issue

I will look for this option but even though I'm on a Mac I'm not familiar with the inner working of the OS
