### ISSUE TITLE
The homebridge module site links most pages to 404 (not found) pages.

### ISSUE THREAD

**Issue by patineboot** [homebridge/homebridge#3063]
### Analysis

The homebridge module site has many links involving **capital letter characters**.
But you deployed all of the pages on the homebridge module site with **only lower case letters**.

The homebridge module site:
https://developers.homebridge.io/homebridge/modules.html

For example, notice to the case letter of 'logger.'

Link URL from the homebridge module site:
https://developers.homebridge.io/homebridge/classes/Logger.html
Actual URL at 'logger':
https://developers.homebridge.io/homebridge/classes/logger.html

### Expected Behavior

I can move to the page by clicking all of the links on the homebridge module site.

### Steps To Reproduce

For example, notice to the case letter of 'logger.'

Link URL from the homebridge module site:
https://developers.homebridge.io/homebridge/classes/Logger.html
Actual URL at 'logger':
https://developers.homebridge.io/homebridge/classes/logger.html

### Logs

```markdown
Check your server log.
```

### Configuration

```json
Default.
```

### Environment

On you web site!

### Process Supervisor

not applicable

**Comment by Supereg** [comment]
This issue was fixed with the release of 1.4.0. Thanks for reporting it.
