### ISSUE TITLE
HomeBridge 1.4.0 beta 5,6,7 won't add to HomeKit

### ISSUE THREAD

**Issue by randomranran** [homebridge/homebridge#3067]
### Analysis

Was running version 1.4.0 beta 4 fine but since updating to beta 5 I can't add HomeBridge to HomeKit, also tried beta 6 and 7 with the same issue 

### Expected Behavior

Noticed I couldn't add a new Hombridge accessory to home kit after updating, it would just hang in homeKit after entering the set up code, so I completly removed my HomeBridge docker contaier and recreated it from scratch. 

After a clean install I could add Homebridge to HomeKit with the stable 1.3.9  and then removed it, so I proceeded to upgrade HomeBridge to 1.4.0 beta 7 again and couldn't add to HomeKit again  

Just hangs on Connecting to Bridge in HomeKit and then a few minutes later I get Unable to Add accessory

### Steps To Reproduce

Clean install of Homebridge, update to 1.4.0 beta 7 then try to add to Homekit

Just hangs on Connecting to Bridge in HomeKit and then a few minutes later I get Unable to Add accessory

### Logs

```markdown
[1/16/2022, 6:23:52 PM] [HB Supervisor] OS: Linux 4.4.180+ x64
[1/16/2022, 6:23:52 PM] [HB Supervisor] Node.js v16.13.2 /usr/local/bin/node
[1/16/2022, 6:23:52 PM] [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[1/16/2022, 6:23:52 PM] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[1/16/2022, 6:23:54 PM] [Homebridge UI] Homebridge Config UI X v4.41.5 is listening on :: port 8581
[1/16/2022, 6:23:54 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules -D
[1/16/2022, 6:23:55 PM] [HB Supervisor] Started Homebridge v1.4.0-beta.7 with PID: 2831
[1/16/2022, 6:23:55 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/16/2022, 6:23:55 PM] Loaded 0 cached accessories from cachedAccessories.
[1/16/2022, 6:23:55 PM] ---
[1/16/2022, 6:23:55 PM] Loaded plugin: homebridge-dummy@0.5.0
[1/16/2022, 6:23:55 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[1/16/2022, 6:23:55 PM] ---
[1/16/2022, 6:23:55 PM] Loaded plugin: homebridge-config-ui-x@4.41.5
[1/16/2022, 6:23:55 PM] Registering platform 'homebridge-config-ui-x.config'
[1/16/2022, 6:23:55 PM] ---
[1/16/2022, 6:23:55 PM] Loading 1 platforms...
[1/16/2022, 6:23:55 PM] [Config] Initializing config platform...
[1/16/2022, 6:23:55 PM] [Config] Running in Service Mode
[1/16/2022, 6:23:55 PM] Publishing bridge accessory (name: Homebridge 4F4F, publishInfo: {
  username: '0A:13:D2:64:4F:4F',
  port: 51393,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
Setup Payload:
X-HM://0023ISYWY8GP8
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[1/16/2022, 6:23:56 PM] Homebridge v1.4.0-beta.7 (HAP v0.10.0-beta.13) (Homebridge 4F4F) is running on port 51393.
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 4F4F",
        "username": "0E:17:D2:66:4F:4F",
        "port": 51393,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

### Environment

- OS: Official docker Image
- Software: Official docker Image
- Node: 16.13.2
- npm: 8.1.2

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

oznu/homebridge:ubuntu

**Comment by NorthernMan54** [comment]
@randomranran - Beta 7 changes the behaviour in selecting the default mDNS advertiser, and now defaults to using avahi on systems that potentially have it available.  Can you try setting the advertiser to `"advertiser": "bonjour-hap"` or `"advertiser": "ciao"` ?

**Comment by Kai9555** [comment]
After the update from version 1.4.0 beta 4 to beta 7, it is unfortunately no longer possible to add cameras from the homebridge-Camera-UI plugin to homekit. The camera configured in the plugin is offered for adding under Homekit. However, the camera cannot be added because the Homebridge code 648-72-*** is incorrect. However, the code is definitely correct. In addition, the system utilization is constantly at about 50%. After downgrading to Beta 4, utilization is back to around 20%. Unfortunately, devices can still no longer be added.

**Comment by seydx** [comment]
> After the update from version 1.4.0 beta 4 to beta 7, it is unfortunately no longer possible to add cameras from the homebridge-Camera-UI plugin to homekit. The camera configured in the plugin is offered for adding under Homekit. However, the camera cannot be added because the Homebridge code 648-72-*** is incorrect. However, the code is definitely correct. In addition, the system utilization is constantly at about 50%. After downgrading to Beta 4, utilization is back to around 20%. Unfortunately, devices can still no longer be added.

Hey @Kai9555 

Is this still the case? If yes, please delete the cameras from homebridge and cache (homebridge-config-ui-x > Settings > Homebridge Settings > Reset > Decouple Cameras)

Then change the name of the camera(s) in config.json and reboot HB

Try to add cameras to HB again

**Comment by Kai9555** [comment]
Hi @seydx 

I did not get the problem solved and had to add another camera that was not previously paired. Unfortunately, I can't reproduce it anymore because I've reinstalled Homebridge on my Raspberry Pi and I don't dare to update from beta 4 to beta 7 or 8 at the moment. It works again in beta 4.

**Comment by donavanbecker** [comment]
> Another question: It basically annoys me that the cameras get their stream from some China server and I am dependent on their stability and my internet connection. I am considering building an IP camera with a Pi Zero so that I can provide a local stream for Camera-UI. Have you experienced this in connection with Camera UI? Or can you even recommend a configuration or instructions?
> 

This should be moved away from this issue, and ask either in discord or the camera UI repo.

**Comment by randomranran** [comment]
My original issue is now resolved by deleting and rebuilding home bridge, please close this issue. Many Thanks
