### ISSUE TITLE
New Plugin Request

### ISSUE THREAD

**Issue by MattRoe84** [homebridge/homebridge#3071]
### Current Situation

Hi has anyone looked to create a plugin for Miboxer and ClickSmart. I would be grateful if someone could look into these please.

### Proposed Change

New Plugin Request

**Comment by mitch7391** [comment]
You might have a better chance to post this in the Homebridge Reddit; I do not think anyone here is going to create a plug-in for you and not too many people will see it here. Good luck! :)

**Comment by MattRoe84** [comment]
Thanks for the advice
