### ISSUE TITLE
homebridge.ca: Service down: 504 Gateway Time-out

### ISSUE THREAD

**Issue by aski71** [homebridge/homebridge#3078]
### Analysis

see subject

### Expected Behavior

Expected to be working

### Steps To Reproduce

none

### Logs

```markdown
none
```

### Configuration

```json
n/r
```

### Environment

n/r

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
The is for the homebridge-Alexa plugin, and the cloud server had an issue.  Please raise these their.

ps I reset the server

**Comment by aski71** [comment]
Sorry for the mix up. I was not sure where to raise.
Works again.
