### ISSUE TITLE
Bridge indication in plugin screen

### ISSUE THREAD

**Issue by RobBuijs** [homebridge/homebridge#3079]
### Current Situation

Currently the way to check if a plugin is behind it's own bridge is only visible when from clicking the wrench icon and selecting bridge settings. Also, the qr code is hidden there. This should be exposed a bit more in the UI

### Proposed Change

Move the bridge settings to it's own icon in the plugin tile if there is a bridge. Save a click and select from the drop-down and the status for all plugins is clear from the plugin screen/

**Comment by mtressl** [comment]
You can add the widget to the main status page, showing all child bridges and their status:
![image](https://user-images.githubusercontent.com/1140154/152328746-c8f60be0-f593-4651-a1a5-96761e66bfdf.png)

**Comment by RobBuijs** [comment]
Ah, that's nice!
