### ISSUE TITLE
Homebridge not working

### ISSUE THREAD

**Issue by tobias912** [homebridge/homebridge#3081]
### Current Situation

Hi Ive been trying to get home bridge to work, but I've been having some issues. I keep getting the same error message and it says Homebridge isn't connected.

### Logs

```markdown
[27/01/2022, 12:54:50] [HB Supervisor] OS: Linux 5.10.63-v7+ arm
[27/01/2022, 12:54:50] [HB Supervisor] Node.js v16.13.2 /usr/local/bin/node
[Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/homebridge/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/homebridge/package.json'
}
TypeError: Cannot read properties of undefined (reading 'bin')
    at HomebridgeServiceHelper.findHomebridgePath (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js:375:87)
    at async HomebridgeServiceHelper.launch (/usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/hb-service.js:233:37)
[27/01/2022, 12:54:55] [HB Supervisor] Homebridge Path: null
[27/01/2022, 12:54:55] [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[27/01/2022, 12:55:38] [Homebridge UI] Homebridge Config UI X v4.42.0 is listening on :: port 8581
[27/01/2022, 12:55:40] [HB Supervisor] Could not find Homebridge. Make sure you have installed homebridge using the -g flag then restart.
[27/01/2022, 12:55:40] [HB Supervisor] npm install -g --unsafe-perm homebridge
```

### Configuration

```json
.
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software:
- Node: v16.13.2
- npm: v8.3.1

### Process Supervisor

not applicable

### Additional Context

I'm not very familiar with all this stuff. I tried following the steps on the Wiki!

**Comment by NorthernMan54** [comment]
Did you do this ?

[27/01/2022, 12:55:40] [HB Supervisor] Could not find Homebridge. Make sure you have installed homebridge using the -g flag then restart.

**Comment by tobias912** [comment]
> Did you do this ?
> 
> [27/01/2022, 12:55:40] [HB Supervisor] Could not find Homebridge. Make sure you have installed homebridge using the -g flag then restart.

Im not sure what it means, that's why I asked. How do I install home bridge using the -g flag?

**Comment by NorthernMan54** [comment]
Step 2 here

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#step-2-install-homebridge-and-homebridge-ui

**Comment by tobias912** [comment]
> Step 2 here
> 
> https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian#step-2-install-homebridge-and-homebridge-ui

How do I get access to the terminal on the pi? If I go into my terminal it says command not found.

**Comment by NorthernMan54** [comment]
What wiki or instructions where you following to get this far ?

**Comment by tobias912** [comment]
> What wiki or instructions where you following to get this far ?

I flashed the SD card with the raspberry Pi image and plugged everything in and then accessed through the IP address

**Comment by NorthernMan54** [comment]
Instructions for the pi image are here, and ssh access details

https://github.com/homebridge/homebridge-raspbian-image#ssh-access

**Comment by tobias912** [comment]
> Instructions for the pi image are here, and ssh access details
> 
> https://github.com/homebridge/homebridge-raspbian-image#ssh-access

This might seem stupid to you, sorry and thanks already for your help! But what do I exactly need to do now?

**Comment by NorthernMan54** [comment]
This is level of support is best handled on the homebridge discord and not in an issue

https://github.com/homebridge/homebridge-raspbian-image#community

**Comment by tobias912** [comment]
Thanks for the help, but it is still an issue because I don't know hat to do :)

**Comment by NorthernMan54** [comment]
Switched to discord

**Comment by NorthernMan54** [comment]
For the people watching, chatted on discord and found that his RPI was rebooting during install, and after further investigation found that the power supply was not supplying enough power. aka under voltage detected
