### ISSUE TITLE
After IOS 15.3 update, all accessories in HomeKit have "unavailable\not responding" or "off" status

### ISSUE THREAD

**Issue by enricosoft** [homebridge/homebridge#3084]
### Analysis

I installed Homebridge 1.4.0 on raspberry pi 3b+ and added 5 accessories (4 shelly and 1 tp-link tapo 100).
Then I added the bridge accessory to homekit (HOME app) and all worked perfectly for many many days.

After IOS 15.3 update on my iphone, something has changed. 
All the accessories in Homekit has a wrong status like if they are OFF or UNAVAILABLE.
If I click on a button, for example, it works but its status is showed as OFF.

In this case when I invoke it via Siri, it answers that the accessory is not available.

### Expected Behavior

I think that the accessory state communication betweekn homekit and homebridge could be broken after IOS 15.3 update.
The expected behavior is to show the correct status of all accessories in homekit (HOME app).

### Steps To Reproduce

Using Homebridge 1.4 and an Iphone with IOS 15.3 installed, add an accessory and you should see that the status of that accessory on homekit (HOME app) is always "Off" or "Unavailable\Not responding"

### Logs

```markdown
No logs available to paste.
The logs page doesn't show specific errors.
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "xxxxxxx",
        "port": 51929,
        "pin": "xxxxxxx",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [
        {
            "accessory": "SimpleShelly",
            "name": "Btn1 ON",
            "url": "http://192.168.1.76",
            "channel": 0,
            "username": "xxxxxxx",
            "password": "xxxxxxx"
        },
        {
            "accessory": "SimpleShelly",
            "name": "Btn2 OFF",
            "url": "http://192.168.1.78",
            "channel": 0,
            "username": "xxxxxxx",
            "password": "xxxxxxx"
        },
        {
            "accessory": "SimpleShelly",
            "name": "Btn3 OPEN",
            "url": "http://192.168.1.54",
            "channel": 0,
            "username": "xxxxxxx",
            "password": "xxxxxxx"
        },
        {
            "accessory": "SimpleShelly",
            "name": "Btn4 CLOSE",
            "url": "http://192.168.1.66",
            "channel": 0,
            "username": "xxxxxxx",
            "password": "xxxxxxx"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Tapo Smart Platform",
            "username": "xxxxxxx",
            "password": "xxxxxxx",
            "devices": [
                {
                    "name": "Luci Esterne",
                    "host": "192.168.1.55",
                    "type": "Plug",
                    "updateInterval": 30,
                    "timeout": 2
                }
            ],
            "platform": "TapoP100"
        }
    ]
}
```

### Environment

OS: raspbian release 10 (codename: buster)
Homebridge: 1.4.0
Node: 16.13.11
npm: 8.1.2

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
Without logs of some sort we are kinda guessing where an issue could be, either homebridge itself or your plugins.  Please share.
