### ISSUE TITLE
[Feature Request] Option to Combine Two Plug-ins in a Child Bridge

### ISSUE THREAD

**Issue by mitch7391** [homebridge/homebridge#3087]
### Current Situation

Currently I have what I will call a 'sudo-plugin' that piggy backs off another plug-in. My plug-in essentially provides a shell script to this other plug-in which does all the Homebridge heavy lifting. My plug-in is Homebridge verified and integrated in Homebridge UI as a delivery method of keeping the shell script up to date for my user base. That being said, my plug-in cannot run without the other one and I would like a method to combine the two plug-ins as a child bridge; which I believe is currently not possible.

### Proposed Change

Create the option to be able to combine child bridges. 

### Additional Context

My [plug-in](https://github.com/mitch7391/homebridge-cmd4-AdvantageAir) and the [plug-in](https://github.com/ztalbot2000/homebridge-cmd4) it piggy backs off might be a unique situation, but I could see how it could be useful for users who would like to combine two similar themed plug-ins into a child bridge.

**Comment by mitch7391** [comment]
> Question, why do you think that you need to have this feature, what is the technical issue your trying to solve?

I will say that I do not <I>need</I> it, but it would just be a nice feature to have. I was hoping that others might find their on needs for it with the ability to do so.

> Personally if I was going to supply a set of of customized scripts for use with another plugin,I might look at just copying the whole other plugin into mine so that it was a complete package. If you fork the original plugin, and add your scripts to it you can publish it on npm with a different name

Two reasons here why I have not done something like that. First, the main plug-in is designed for the very reason of using scripts the user creates, or you can use some pre-made ones on the plug-in. 

Second, there is no point me copying over an entire plug-in that is capable of creating every single accessory (it is a large plug-in) for the few that I want. Also this is my first project in anything coding or plug-in related; I am still learning as I go and am not capable of creating my own full plug-in yet.

I did create this knowing more than likely the answer would be no, but thought I would float the idea at the very least. The idea would be for people who have so many plug-ins to not have to create a child bridge for every single one if you do not want to (I am already running of the neat space it uses on Homebridge UI). 

I believe with the creation of each one there is further memory usage and at a certain stage grouping like ones together could be ideal. I know this could be argued as a step back towards having just the one ‘mother’ bridge; but I do like that when a child bridge crashes it does not crash Homebridge. Currently the main plug-in that piggy backs mine has its own child bridge and my ‘sudo plug-in’ has to live on the ‘mother’ bridge.

I hope this all makes sense.

**Comment by NorthernMan54** [comment]
I'm not sure I fully understand what your attempting to do, and how child bridges impacts the issue.  To level set, this is my understanding of what you have today.

1) There is an existing plugin `homebridge-cmd4` that allows people to create custom devices and accessories and control them via `cmd's`.  Configuration of these devices is quite complex and potentially error prone.

2) You created a series of scripts and configuration samples `homebridge-cmd4` to dramatically simplify configuring an Advantage Air Air conditioner ( Very well done ).  And packaged them as a homebridge plugin to simplify installation for end users, but your plugin has no actual homebridge code in it as it just the shell scripts etc for `homebridge-cmd4` for the Advantage Air air conditioner

And my original response was from a plugin / code management perspective and how you could potentially do a merge between `homebridge-cmd4` and your series of scripts and configuration samples to create a new combined plugin.  ( under the covers, GitHub makes something like this reasonably straightforward, and their are a couple of methods of achieving it ).

With that said, what I believe your asking about is an enhancement to bundle or combine multiple plugins into a single child bridge, which is an existing feature for accessory plugins ( [series of scripts and configuration samples](https://github.com/homebridge/homebridge/wiki/Child-Bridges#multiple-accessories-on-the-same-child-bridge) ).  

Is this what your inquiring about ?

**Comment by mitch7391** [comment]
You have both of those points correct :)

> And my original response was from a plugin / code management perspective and how you could potentially do a merge between homebridge-cmd4 and your series of scripts and configuration samples to create a new combined plugin. ( under the covers, GitHub makes something like this reasonably straightforward, and their are a couple of methods of achieving it ).

This is also true, but not the direction I wanted to take my plug-in in; as I the future (when life permits) I would like learn how to make my own independent plug-in.

> With that said, what I believe your asking about is an enhancement to bundle or combine multiple plugins into a single child bridge, which is an existing feature for accessory plugins ( [series of scripts and configuration samples](https://github.com/homebridge/homebridge/wiki/Child-Bridges#multiple-accessories-on-the-same-child-bridge) ).

I had seen that, but I had also read the part about how it does not work for platforms; `homebridge-cmd4` being a platform. Or have I misunderstood this?

> Is this what your inquiring about ?

Spot on.

**Comment by NorthernMan54** [comment]
If you look at the docs for cmd4, it can be both, either a platform or an accessory

https://github.com/ztalbot2000/homebridge-cmd4/blob/master/docs/Developers.md#standard-accessories

**Comment by oznu** [comment]
Thanks for your suggestion. Currently we have no intentions to allow multiple plugins per child bridge, limiting them to a single plugin is intentional.
