### ISSUE TITLE
Camera FFmpeg process creation failed: spawn ffmpeg ENOENT

### ISSUE THREAD

**Issue by superhardi** [homebridge/homebridge#3092]
### Current Situation

I install plugins TAPO camera^ but see this error in logs FFmpeg process creation failed: spawn ffmpeg ENOENT
What me need doing, for resolve this situation? 

### Logs

```markdown
FFmpeg process creation failed: spawn ffmpeg ENOENT
```

### Configuration

```json
Mac Mini M1
```

### Environment

Last MACos and last homebridge

### Process Supervisor

other (Explain in `Additional Context`)

**Comment by jandreaucodes** [comment]
You ever figure this out? I'm seeing the same error on my new Mac Studio.

**Comment by NorthernMan54** [comment]
Is this the Homebridge-camera-ffmpeg plugin ?  Pls raise this issue against the plugin so the plugin developer can see the issue.

Also I think this is related

https://github.com/homebridge/ffmpeg-for-homebridge/issues/30

**Comment by shamoon** [comment]
I wonder if it’s https://github.com/homebridge/ffmpeg-for-homebridge/issues/44

**Comment by Oh4sh0** [comment]
Still seeing this on a Mac M1 Mini

**Comment by YiffyC** [comment]
Same for me with Macini mid 2012. Is there a workaround ?

**Comment by jcbriones** [comment]
Any updates to this?
