### ISSUE TITLE
Shortcuts in iOS Control Centre can't toggle devices off/on

### ISSUE THREAD

**Issue by syn-acks** [homebridge/homebridge#3096]
### Analysis

Hi Devs!

I'm experiencing a strange bug where the 'shortcut icons' when you pull the control centre down in iOS show as unusable.
'Clicking' one of these icons is meant to turn the device off and on, however it does nothing. The small shortcuts show an 'orange exclamation mark'.

'Long Pressing' one of these icons and using the manual switch seems to work fine (ie, using the brightness scroller, or toggling a boolean HS100 switch off or on). Manually opening the 'Home' app, and using those buttons (off/on) also works fine - so this issue is isolated to the single accessory shortcut available in the control centre.

I am using the homebridge-tplink-smarthome plugin for my TP Link devices. 

Homebridge is in a different subnet to the devices, however there is no firewalling, and mDNS is fully configured.
The issue appears to be intermittent, but is 9/10 times a problem.

### Expected Behavior

After clicking one of the shortcuts in control centre, the devices should turn off and on. 

### Steps To Reproduce

1. Pull down iOS Control centre. 
2. Press a shortcut icon (ie. Switch on light). 
3. Nothing happens. 

### Logs

```markdown
No logs are generated by Homebridge when this action is performed in iOS.
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge C834",
        "username": "0E:B1:C9:38:7A:05",
        "port": 51231,
        "pin": "862-70-619"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "devices": [
                {
                    "host": "192.168.12.108"
                },
                {
                    "host": "192.168.12.225"
                },
                {
                    "host": "192.168.12.28"
                }
            ],
            "platform": "TplinkSmarthome"
        }
    ]
}
```

### Environment

Version
7.0.1

Node Version
16.13.1

Homebridge Version
4.42.0

Which OS/Platform?
Linux

NPM
v8.1.2

### Process Supervisor

hb-service

**Comment by syn-acks** [comment]
Just a note, this also affects the usability of Siri.

**Comment by squishycat92** [comment]
Both Siri and the shortcut icons in Control Center work for me (Docker on Linux, homebridge-ewelink). You can try some troubleshooting if you have some natively-supported HomeKit devices. It sounds to me like there are perhaps issues with your network.
