### ISSUE TITLE
Homebridge UI Update Failed

### ISSUE THREAD

**Issue by GitHubGoody** [homebridge/homebridge#3097]
### Current Situation

I have a newly configured instance of Homebridge running on an RPi Zero W (image installed via the Raspberry Pi Imager) and am trying to update the Homebridge UI plugin (currently v4.41.2), but I keep getting the following error.

<img width="751" alt="HomebridgeUpdateFailure20220309" src="https://user-images.githubusercontent.com/46235745/157468783-88ed36ef-fd3a-4bc6-8e43-0cc270e6ad21.PNG">

I was able to successfully install many other plugins and Homebridge seems to be working well otherwise.

How can I get the update to complete?

### Logs

```markdown
[2022-03-09T14_38_51_245Z-debug-0.log](https://github.com/homebridge/homebridge/files/8215728/2022-03-09T14_38_51_245Z-debug-0.log)
```

### Configuration

```json
N/A
```

### Environment

- OS: RPi
- Software: Homebridge
- Node: v16.13.1
- npm: 8.3.0

### Process Supervisor

not applicable

**Comment by GitHubGoody** [comment]
This was never solved.

**Comment by donavanbecker** [comment]
First of all, this should be under the repo homebridge-config-ui-x repo since that is where the UI is maintained.

Secondly, have you tried updating again with the new release that came out today?

**Comment by GitHubGoody** [comment]
@donavanbecker Sorry about that. I just tried. It didn't work. Same error as the screenshot above.
