### ISSUE TITLE
Plugin Remote TVBed

### ISSUE THREAD

**Issue by SoNyz85** [homebridge/homebridge#3099]
### Current Situation

Remote Chip for TVBed

### Logs

```markdown
.
```

### Configuration

```json
.
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

Hi Guys,

does anybody know what kind of chip use this remote?
It is a tvbed remote, I would like to use it with siri, but I couldn’t find the chip of the remote.

![241A0AA0-32B9-417B-B2D3-F46E5A3DC7D0](https://user-images.githubusercontent.com/101674965/158479504-9100161c-6c1a-4133-8d2b-65dc2bce2b83.jpeg)
![5C2351F4-F048-4572-8278-C4FE65D22B6D](https://user-images.githubusercontent.com/101674965/158479525-2d1c4b98-310d-43ba-bf45-80859a119740.jpeg)
![56447E72-1BBB-449D-9083-E3B3864A01B1](https://user-images.githubusercontent.com/101674965/158479535-7e4664ce-b3eb-489a-93f5-eeb1d2b9aebd.jpeg)
![4E2D3124-A96A-4BB7-B21C-DFDDA632D8A4](https://user-images.githubusercontent.com/101674965/158479540-3b9c1ba0-77d6-4857-b974-cbe1633f8359.jpeg)
![A3903EAB-05F5-4E04-887B-64F2DCF6C587](https://user-images.githubusercontent.com/101674965/158479548-85bcc63e-7ae4-4460-917c-254a9979a5d9.jpeg)

**Comment by NorthernMan54** [comment]
Does the remote have a FCCID ? That would at least indicate that it uses RF, but I didn't see any antenna on the board like you get with an ESP8266/ESP32.  Also googling the stc15w408s it does not appear to support wifi,  but the data sheet I found was in Chinese ( https://datasheet.lcsc.com/lcsc/2003060933_STC-Micro-STC15W408S-35I-LQFP44_C42776.pdf ) so I could have missed that.

Looking at your pictures is that an IR LED in the bottom left of the first picture ?

**Comment by SoNyz85** [comment]
![image](https://user-images.githubusercontent.com/101674965/158525568-6462977a-83c4-4dc0-8d87-7e7cc575621d.jpeg)
![image](https://user-images.githubusercontent.com/101674965/158525591-0002e354-f7fd-4fa2-9c15-a03b361f4621.jpeg)
![image](https://user-images.githubusercontent.com/101674965/158525665-46e06676-8405-48ce-ae77-e2a896ab6db9.jpeg)
![image](https://user-images.githubusercontent.com/101674965/158526176-12c08016-9673-4e64-be50-4014363aaf92.jpeg)

I don't think it is IR because even if I put the remote under the pillow it works, it activate bluetooth, volume, lift tvbed.

**Comment by SoNyz85** [comment]
![image](https://user-images.githubusercontent.com/101674965/158526959-c855aacd-2309-42b2-a46c-bfac4e53e353.jpeg)


The led is for usb when it is in charge, red in charge, blue fully charged.
