### ISSUE TITLE
Best API service for representing boiler?

### ISSUE THREAD

**Issue by zdychacek** [homebridge/homebridge#3106]
### Current Situation

I want to implement plugin for setting water heating boiler temperature. I've started with `Thermostat` service, but this has temperature range limitation: 10-38 C. My boiler is able to set value up to 55 C.

Is there some better service I can use which allows me to set up temperature up to 55 C?

### Logs

```markdown
No logs, just a question.
```

### Configuration

```json
No config, just a question.
```

### Environment

Just a question.

### Process Supervisor

hb-service

**Comment by AssetBurned** [comment]
I have read that the HomeKit Accessory Simulator would allow you to have a look at what kind of services an accessory can offer. https://developer.apple.com/documentation/homekit/testing_your_app_with_the_homekit_accessory_simulator

**Comment by NorthernMan54** [comment]
The best would be a thermostat, but just adjust the max and minimum values with setprops.

https://github.com/NorthernMan54/homebridge-tcc/blob/7eae71d8637474f31a1e44a10931ada618ebbbab/index.js#L329

**Comment by zdychacek** [comment]
> The best would be a thermostat, but just adjust the max and minimum values with setprops.
> 

`maxValue` cannot be set higher than 38.

**Comment by zdychacek** [comment]
> The best would be a thermostat, but just adjust the max and minimum values with setprops.
> 
> https://github.com/NorthernMan54/homebridge-tcc/blob/7eae71d8637474f31a1e44a10931ada618ebbbab/index.js#L329

Sorry, you're right. It works. It was late yesterday:)

Closing issue.

Thank you.
