### ISSUE TITLE
Windows 11 Beta disables Homebridge Service after in place upgrade

### ISSUE THREAD

**Issue by kravena** [homebridge/homebridge#3112]
### Analysis

Using Windows 11 Beta, when an update is performed such as moving from Build 22598.1 to 22598.100, the Homebridge Service is disabled.

Recreating the Homebridge service using "hb-service install" restores the service.

> C:\Windows\System32>hb-service install
> i Installing Homebridge Service
> i Starting Homebridge Service...
> √ Homebridge Started

### Expected Behavior

Windows upgrades to not disable the service

### Steps To Reproduce

1. Install Windows 11 Beta on top of previous any previous Windows 11 release
2. Restart PC
3. Homebridge is not started due to missing service

### Logs

```markdown
C:\Windows\System32>hb-service install
i Installing Homebridge Service
i Starting Homebridge Service...
√ Homebridge Started
```

### Configuration

```json
Not applicable
```

### Environment

- OS: Windows 11 Beta Build 22598.1
- Software: 
- Node: v16.13.1
- npm: 8.3.2

### Process Supervisor

hb-service

### Additional Context

I appreciate Windows beta builds are not fully supported

**Comment by kravena** [comment]
Confirm the same issue occurred after upgrading to Windows 11 - 22621.1

**Comment by oznu** [comment]
Native Windows support for this project doesn't have much time left. Direct links to the install guide have been removed from the wiki and will be removed from the website soon.

If your version of Windows 11 supports it, you may want to look at swapping to a Hyper-V based install: https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10-Using-Hyper-V
