### ISSUE TITLE
I need help moving where the Homebridge portal directs to.

### ISSUE THREAD

**Issue by AnthonyScola** [homebridge/homebridge#3113]
### Current Situation

I would like to homebridge and the wifi setup to map to homebridge.local/config/ instead of the root directory homebridge.local/

I've changed the NGINX config like so:

    location /config/ {
    proxy_pass                  http://127.0.0.1:8581;
    proxy_http_version          1.1;
    proxy_buffering             off;
    proxy_set_header            Host $host;
    proxy_set_header            Upgrade $http_upgrade;
    proxy_set_header            Connection "Upgrade";
    proxy_set_header            X-Real-IP $remote_addr;
    proxy_set_header            X-Forward-For $proxy_add_x_forwarded_for;

But when I modify the package.json files and include for example:
`    "homepage" : "/usr/local/lib/node_modules/homebridge-config-ui-x/", `

I get a white screen, so I'm obviously missing something.

What all do I have to change to get it to map to a different location?

### Logs

```markdown
runtime-es2015.183cf24ad04e2c5c55f7.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found)

scripts.1af254983ce64e572c03.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found)

polyfills-es2015.e8bb8be2ebc926cac2d0.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found)

main-es2015.9d482d945810494ac85a.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found)

styles.5a95e73f51995fe4cdc8.css:1 
Failed to load resource: the server responded with a status of 404 (Not Found)

styles.5a95e73f51995fe4cdc8.css:1 
Failed to load resource: the server responded with a status of 404 (Not Found)

manifest.webmanifest:1 
Failed to load resource: the server responded with a status of 404 (Not Found)
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "XXXXXXXXXXX",
        "port": 51972,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

### Environment

- OS: homebridge for raspberry pi
- Software: homebridge
- Node: v16.14.0
- npm: 8.5.1

### Process Supervisor

hb-service

**Comment by AnthonyScola** [comment]
Anyone?

**Comment by NorthernMan54** [comment]
@AnthonyScola I don’t think any answered as your question is in regards to homebridge-config-ui and not homebridge itself.

And after reading your issue, it looks more like a question in regards to configuring an Apache proxy server to move the Web UI context root to a different location.   And I don’t know where you would ask such a question.

**Comment by AnthonyScola** [comment]
@NorthernMan54, that's correct. I am not too familiar with NGINX which is the default. I was hoping that whoever set up the networking for homebridge would know which modifications I would need to make to the config files in order to remap it to /config/

I suppose I could reverse engineer it to use Apache, but that seems like a lot of work for something that should be as simple as 2 if not 4 lines of code.
