### ISSUE TITLE
Homebridge in docker on a pi - avahi or no-avahi?

### ISSUE THREAD

**Issue by andrasg** [homebridge/homebridge#3115]
### Current Situation

I have looked at my homebridge logs and it has been complaining of multiple mDNS stacks found. Raspbian arm64 seems to arrive with avahi enabled out of the box.

As a test, I disabled avahi on my pi and the warning went away, but this started me thinking, what is the right way to run Homebridge?
- avahi disabled on host
- avahi enabled on host and using a `no-avahi` tagged image
- avahi enabled on host and just ignore the warning - all seems to be working fine with this config
- use an mDNS advertiser other than avahi in Homebridge

### Logs

```markdown
*** WARNING: Detected another IPv4 mDNS stack running on this host. This makes mDNS unreliable and is thus not recommended. ***
```

### Configuration

```json
"bridge": {
        "name": "Homebridge",
        "username": "0E:4E:E3:54:D9:ED",
        "port": 51826,
        "pin": "<removed>",
        "advertiser": "avahi",
        "bind": [
            "192.168.20.19"
        ]
    }
```

### Environment

- OS: rpi latest arm64
- Node: docker latest
- npm: docker latest

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

docker latest image on rpi (arm64)

**Comment by oznu** [comment]
Whatever works for you, as you mentioned, you can usually safely ignore the warning and everything still just works.
