### ISSUE TITLE
Check for Out of Date Items / Plugins (cli)

### ISSUE THREAD

**Issue by arrmo** [homebridge/homebridge#3120]
### Current Situation

Hi,

Similar to this [query](https://github.com/homebridge/homebridge/issues/1870), I am trying to determine what out of date items or plugins exist, via the cli (bash). I have executed the noted command (`sudo npm outdated -g`), but it comes back blank - in spite of the fact that the Homebridge UI shows out of date items. So it seems this command / approach does not work? Is there another (or better) way?

Thanks!

### Logs

```markdown
N/A - command output is blank.
```

### Configuration

```json
N/A
```

### Environment

- OS: Ubuntu 22.04
- Software: 1.4.0
- Node: v16.13.0
- npm: 8.8.0

### Process Supervisor

systemd

### Additional Context

N/A

**Comment by arrmo** [comment]
Hi,

Just checked - UI shows out of date items, but the (global) command still has no output. Any thoughts?

Thanks!

**Comment by oznu** [comment]
Newer installs on Debian will put plugins into /var/lib/homebridge/node_modules.

If you run `npm outdated` in `/var/lib/homebridge` you should be see the list.

You can use `sudo hb-shell` to enter the Homebridge Node.js environment from SSH.

**Comment by arrmo** [comment]
Thanks! Two things though 😞,
- not seeing the plugins in `/var/lib/homebridge/node_modules`. Reinstall perhaps? Is there a way to gracefully do that?
- `hb-shell` does not seem to exist? And I can't install it, on the latest version of Ubuntu.

Thanks again.

**Comment by oznu** [comment]
You must be using the older style install then, which is fine, it just means the comment above is not relevant to you.

If you re-install, while the old service is still running, it should put everything back in place.

Follow the wiki guide for Ubuntu; do a backup first.
