### ISSUE TITLE
Unfriendly handling of unhandled exceptions/rejections

### ISSUE THREAD

**Issue by adriancable** [homebridge/homebridge#3122]
My plug-in (homebridge-nest) unfortunately had a bug which led to an unhandled promise rejection in the case of a network error under specific circumstances. Shame on me! Fortunately I have now fixed it.

Unfortunately, Homebridge made this a little hard for me to debug (and my users to help me). It installs a default unhandled promise rejection handler which simply immediately quits, without showing any indication of where the unhandled rejection occurred, what caused it, etc. So my users just see Homebridge SIGTERM with no error. This makes things almost impossible to debug 'in the field'. Example:

```
[02/05/2022, 18:29:34] Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)
[02/05/2022, 18:29:34] [Nest] Retrying in 10 seconds.
**[02/05/2022, 18:29:34] Got SIGTERM, shutting down Homebridge...**
```

Can we make it more friendly? My recommendation: remove the handler completely. Modern versions of node already quit when there are unhandled promise rejections, so if you are going to quit, node does that already - and unlike Homebridge's 'minimal bomb' handler which says nothing, node prints useful info/stack trace which can help plug-in developers if this happens to end users.

**Comment by oznu** [comment]
It looks like this is the code that handles that, I think the intention was for it to still print a stack trace:

https://github.com/homebridge/homebridge/blob/master/src/cli.ts#L98-L107

@Supereg I'm happy to remove this.

> v15.0.0 - Changed default mode to `throw`. Previously, a warning was emitted.

* `throw`: Emit [unhandledRejection](https://nodejs.org/api/process.html#event-unhandledrejection). If this hook is not set, raise the unhandled rejection as an uncaught exception. This is the default.

https://nodejs.org/api/cli.html#--unhandled-rejectionsmode

**Comment by ebaauw** [comment]
Please don’t remove the handler.  The SIGTERM is so (other) plugins get a change to shutdown cleanly, rather than NodeJS crashing on them.

The useless stack trace is because of the asynchronous nature of NodeJS.  You won’t get better info if you simply let NodeJS crash.

**Comment by adriancable** [comment]
@ebaauw - if a plug-in needs to add extra logic to shutdown cleanly in the event of a SIGTERM, would it not add its own handler and do the clean-up there?

I do see that Homebridge's handler adds a short delay before the process dies, but it isn't clear to me really what the purpose of this is. On its own, this doesn't help a plug-in clean up, unless it knows it's being terminated. To know it's being terminated, it would need to add its own handler, in which case it can do whatever it wants there (including delay).

I suspect I am missing something here!

(Noted about the useless stack trace - unfortunately that is true.)

**Comment by ebaauw** [comment]
> if a plug-in needs to add extra logic to shutdown cleanly in the event of a SIGTERM, would it not add its own handler and do the clean-up there?

Last time I checked, NodeJS would only allow a single signal/uncaught exception/unhandled promise rejection handler, so if multiple plugins would try this, they’s interfere with each other (I think only the last one gets fired).

> I suspect I am missing something here!

Homebridge emits a `shutdown` event, and waits five seconds before terminating NodeJS.  It also flushes `cachedAccessories`.  The event allows multiple listeners, somewhere plugin can do their cleanup.

**Comment by adriancable** [comment]
@ebaauw - not true (regarding multiple handlers).

```
process.on('unhandledRejection', () => console.log('test 1'));
process.on('unhandledRejection', () => console.log('test 2'));
(async () => { throw('test') })()
```

```
$ node test.js
test 1
test 2
```

**Comment by adriancable** [comment]
Also @ebaauw / @oznu a clarification - I am not suggesting we remove the signal handlers. I am suggesting we remove the `uncaughtException` handler:

https://github.com/homebridge/homebridge/blob/master/src/cli.ts#L107

Looking at the code it doesn't do anything useful or helpful for plug-ins. I don't think discussion about the 'shutdown' event or process termination delays are really relevant to the question of removing the `uncaughtException` handler, which I don't think does anything useful.

**Comment by Supereg** [comment]
Citing from the [node docs](https://nodejs.org/api/process.html#event-uncaughtexception):

> By default, Node.js handles such exceptions by printing the stack trace to stderr and exiting with code 1, overriding any previously set [process.exitCode](https://nodejs.org/api/process.html#processexitcode). Adding a handler for the 'uncaughtException' event overrides this default behavior.

Once you override the `uncaughtException` handler you are also responsible yourself to exit the application (since this behavior will also be overridden). I would advocate to **not** remove the homebridge handler, as we use it to make sure that homebridge always exits cleanly and ensure that we have time to save the current state and configuration to disk (including plugins). If we wouldn't register the listener and e.g. a plugin might register one and then the plugin would be responsible to shutdown homebridge properly. This is unexpected and would just create weird issue. 

> An alternative to maintaining Homebridge's pointless handler is to make it less pointless. There are some low hanging fruit improvements e.g. it could print to the console "Homebridge is terminating due to an unhandled exception in a plug-in", which gives some feedback to the user and/or the plug-in developer why Homebridge just stopped.

I would side with @adriancable to print a much more detailed error message in the error handler, so issues can be resolved faster.

**Comment by adriancable** [comment]
> I would advocate to not remove the homebridge handler, as we use it to make sure that homebridge always exits cleanly and ensure that we have time to save the current state and configuration to disk

But the `uncaughtException` handler doesn't help Homebridge exit cleanly or make time for anything. It just immediately triggers a SIGTERM, which is what Node does anyway. It really is close to a 'no-op' right now.

The logic I think you're talking about (delayed exit) is implemented elsewhere and triggers whenever the process terminates - including if the `uncaughtException` handler is removed.

**Comment by ebaauw** [comment]
The logic is in the signal handler.  The `exit` event on `process` is emitted too late (after the event loop has terminated) for proper cleanup, so we re-use the signal handler.
