### ISSUE TITLE
Unable to install in Ubuntu 16 using npm as previously supported

### ISSUE THREAD

**Issue by rtrauer** [homebridge/homebridge#3123]
### Current Situation

Previously the homebridge installation was using npm using this command
sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x

We are using Ubuntu 16 on FriendlyArm NanoPi Neo.
Today I tryed to make a new homebridge installation, but it wasen´t possible to install gpg since it is not available.
The gpg version installed is gpg (GnuPG) 1.4.20
Then I tryed to use the old npm installation and this resulted in errors as well.

Please leave an option to be able to install HomeBridge on  Ubuntu 16.04.7 LTS

### Proposed Change

Leave an option to install homebridge as previously using npm

**Comment by oznu** [comment]
You can still install it the way you did previously. The instructions have just been updated for modern systems.

**Comment by oznu** [comment]
Note that "gpg" is not a dependency, it just required to add the repo signing key.

**Comment by oznu** [comment]
Looks like `gpg` is built in for 16.04 - not a package, so adding the key in the described way still works as intended.

However the glibc version is not high enough to run.

```
The following packages have unmet dependencies:
 homebridge : PreDepends: libc6 (>= 2.24) but 2.23-0ubuntu11.3 is to be installed
```

---

If you want to run on 16.04 - you will need to install Node.js and npm yourself then run:

```
sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x
```

```
sudo hb-service install --user homebridge
```

**Comment by oznu** [comment]
The apt package should now work on 16.04. Support will be dropped in October when we move to Node v18 which requires libc6>=2.28
