### ISSUE TITLE
Failing installing Homebridge

### ISSUE THREAD

**Issue by NebuNC2** [homebridge/homebridge#3132]
### Current Situation

Hey there,
I try to install Homebridge on my Raspberry Pi 4.
But I get following error:
Can someone help me?

![7FB0EEEF-2A09-460F-8D91-4CC0F56194D2](https://user-images.githubusercontent.com/75451781/167507314-2ca024d4-3f10-4b41-8bed-2ce9352e39be.jpeg)

### Logs

```markdown
Have none. See picture pleae
```

### Configuration

```json
Raspberry PI
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
Did you follow step 1 from here ?

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian

**Comment by NebuNC2** [comment]
Hey there,

I don’t know what I did wrong but now ist works…

Thanks

Freundliche Grüße
Malte Söhner
Mobil gesendet

Am 10.05.2022 um 01:41 schrieb Northern Man ***@***.***>:

﻿

Did you follow step 1 from here ?

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Raspbian
