### ISSUE TITLE
Command failed: vcgencmd get_throttled VCHI initialization failed

### ISSUE THREAD

**Issue by C4J** [homebridge/homebridge#3141]
### Current Situation

Latest HomBridge UI update on Raspberry Pi 4 8GB gives me this error in the log

Could not check vcgencmd get_throttled: Command failed: vcgencmd get_throttled
VCHI initialization failed.

I am using the raspberry pi  in headless mode.

Any ideas what I should do to resolve this ?

Dave

### Logs

```markdown
[16/05/2022, 17:44:01] [Homebridge UI] Could not check vcgencmd get_throttled: Command failed: vcgencmd get_throttled
VCHI initialization failed
```

### Configuration

```json
Problem not related to config
```

### Environment

- OS: Raspberry PI
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-config-ui-x/issues/1338
