### ISSUE TITLE
Hombridge stuck on Login page after entering credentials.

### ISSUE THREAD

**Issue by Honosapiens** [homebridge/homebridge#3142]
### Analysis

Hombridge running the latest updates, it is stuck in the Login page after entering the credentials
![Screen Shot 2022-05-16 at 2 22 29 PM](https://user-images.githubusercontent.com/79858019/168657975-bc71b308-d8d2-4f37-9876-e4b00babf4c7.png)
.

### Expected Behavior

Hombridge should be login in.  All plugins are up and running.  I can control all devices.  But can't enter to home bridge portal.

### Steps To Reproduce

I just enter the login credentials and then it would change to this page.
![Screen Shot 2022-05-16 at 2 22 29 PM](https://user-images.githubusercontent.com/79858019/168658231-ff0485c3-ebb8-4d96-81f1-102c8d04fdb9.png)

### Logs

```markdown
I can't produce any logs, since I can't enter to the hombridge portal.
```

### Configuration

```json
It is with the default configuration.
```

### Environment

- OS:  Mac OS Monterrey 12.3.1
- Software: Homebridge
- Node: v16.15.0
- npm: 8.5.5

### Process Supervisor

not applicable

**Comment by oznu** [comment]
Run this:

```
npm install -g homebridge-config-ui-x@latest
```

if that does not fix it, delete this file: `~/.homebridge/auth.json` and restart, you'll be prompted to setup new credentials
