### ISSUE TITLE
Characteristic 'CurrentHeaterCoolerState' of service 'Heater Cooler' is not properly reflected on the Home app UI

### ISSUE THREAD

**Issue by embee8** [homebridge/homebridge#3145]
### Analysis

Hi! I am the maintainer of [homebridge-panasonic-ac-platform](https://github.com/embee8/homebridge-panasonic-ac-platform).

A user recently reported an issue which led me to discover that the status icon of the air conditioner (Heater Cooler) in the Home app doesn't correctly reflect the status of the AC in some cases.

To be more precise: IDLE and INACTIVE are both shown as "Inactive" in the Home app.

On [this line](https://github.com/embee8/homebridge-panasonic-ac-platform/blob/a8bdd2ea702707f6533e78451779b8f56957f736/src/accessories/indoor-unit.ts#L208), we set the current state to IDLE when the AC is in cooling mode and the current temperature is less than the set temperature (i.e. the AC did its job but is still on).

However, the Home app displays the status of the AC as inactive, which isn't quite right. I also tested setting the current state to INACTIVE, which is also shown as inactive in the Home app (correctly in this case).

The question is: Does HomeKit actually know the states IDLE and INACTIVE as they are implemented for the Heater Cooler in Homebridge? Because it seems like there are only 3 modes shown on the UI: Heating, Cooling, and Inactive - the latter is displayed for both IDLE and INACTIVE.

### Expected Behavior

When I set CurrentHeaterCoolerState to IDLE, I expect(ed) the Home app to display the status icon of the AC as "Idle", as opposed to "Inactive".

### Steps To Reproduce

1. Install a plugin that provisions an accessory that implements the Heater Cooler service.
2. Set the CurrentHeaterCoolerState of the accessory to IDLE.
3. Observe what happens to the status icon of the accessory in the Home app. Current behaviour on my setup is that it says "Inactive".
4. Set the CurrentHeaterCoolerState to INACTIVE.
5. Observe what happens to the status icon of the accessory in the Home app. Current behaviour on my setup is that it says "Inactive" (same as 3).

### Logs

```markdown
No logs available for setting the characteristic to one of the available enums. Please let me know if further logs are required and where to enable and obtain them.
```

### Configuration

```json
{
    "mdns": {
        "interface": "192.168.x.xx"
    },
    "bridge": {
        "name": "Homebridge XXXX",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": xxxxx,
        "pin": "xxx-xx-xxx",
        "bind": [
            "eth0"
        ]
    },
    "platforms": [
        {
            "name": "Config",
            "port": xxxx,
            "platform": "config"
        },
        {
            "name": "Homebridge Panasonic AC Platform",
            "email": "xxx",
            "password": "xxx",
            "exposeOutdoorUnit": true,
            "debugMode": true,
            "suppressOutgoingUpdates": false,
            "platform": "Panasonic AC Platform"
        }
    ],
    "accessories": []
}
```

### Environment

- OS: Alpine Linux (3.12.9) 
- Software: 1.3.8
- Node: v16.13.1
- npm: 8.1.2

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

Docker image: oznu/homebridge:lates

**Comment by NorthernMan54** [comment]
Have you tried creating a similar accessory with the HomeKit Accessory Simulator to see if the issue is within homebridge or a gap within HomeKit ?

I spent a few minutes playing with the HomeKit Accessory Simulator and it appears to also work the same way, but please try it out and confirm.
