### ISSUE TITLE
Update to v4.45.0 failed

### ISSUE THREAD

**Issue by rupil10** [homebridge/homebridge#3146]
### Current Situation

When I updated to v4.43.3 I received a similar error to below. I was able to get around it by updating it via terminal from some guide that I found online however just trying to update to v4.45.0 the same thing has happened again.

Am I going to have to keep forcing it to happen via terminal or is there someway that I can fix this issue so that I can just update using the UI. I really don't understand the terminal side of things in great detail and feel like I might break my installation if I mess with it too much.

USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-config-ui-x@latest

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-config-ui-x
npm ERR! dest /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-config-ui-x' -> '/usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-05-24T22_06_22_459Z-debug.log

Cleaning up npm cache, please wait...
npm cache cleared, please try updating homebridge-config-ui-x again.

Command failed. Please review log for details.

Thanks

### Logs

```markdown
none
```

### Configuration

```json
none
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by oznu** [comment]
sudo rm -rf /usr/local/lib/node_modules/.homebridge-config-ui-x-3gtnOIj4
