### ISSUE TITLE
FreeBSD: Unsupported advertiser setting: 'avahi'

### ISSUE THREAD

**Issue by jgillet** [homebridge/homebridge#3147]
### Current Situation

Avahi is available on FreeBSD... but homebridge won't start with advertiser set to "avahi".
`Error: Unsupported advertiser setting: 'avahi'`

With default advertiser, it leads to `Error: bind EADDRINUSE 0.0.0.0:5353` when Avahi is already running (and used by other softwares...)

### Proposed Change

Enable Avahi support for FreeBSD-based platforms.

**Comment by adriancable** [comment]
I’m guessing here because I don’t use FreeBSD. But Homebridge talks to Avahi via the D-Bus API. It’s possible this is Linux only.

**Comment by jgillet** [comment]
Available as well ;-)
```
# pkg info dbus | head -3
dbus-1.12.20_5
Name           : dbus
Version        : 1.12.20_5
```

**Comment by adriancable** [comment]
That doesn’t show the D-Bus session bus is available.

Issue is probably the same as this: https://stackoverflow.com/questions/43147207/haskell-failing-to-connect-to-dbus-as-client-on-freebsd

**Comment by josser** [comment]
Having same issue
@adriancable CUPS using avahi+dbus on freebsd, so it shouldn't be an issue for homebridge 

Is there any way to test this locally?
