### ISSUE TITLE
Can't install via Synology package manager

### ISSUE THREAD

**Issue by jankeesvw** [homebridge/homebridge#3151]
### Analysis

When I add the package source to my Synology I don't see the homebridge package. I also see that the URL listed in the Readme does not give any package:

![CleanShot 2022-05-31 at 09 16 10](https://user-images.githubusercontent.com/167882/171114649-7ea9d398-39de-4e12-8e5e-0d5aa5dffbf3.png)

### Expected Behavior

I expected the package to be listed

### Steps To Reproduce

1. Open Package Center in DSM and select the Settings option.
2. Select the Package Sources tab.
3. Click Add
4. In the Name section enter Homebridge
5. In the Location section enter https://synology.homebridge.io
6. Click OK

**Comment by oznu** [comment]
Make sure you are running a supported model and DSM 7. The output you see from manually browsing to https://synology.homebridge.io/ is expected.

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Synology-DSM
