### ISSUE TITLE
Accessory not available via /api/accessories/<uniqueId> until accessories loaded in web UI

### ISSUE THREAD

**Issue by jimbju** [homebridge/homebridge#3152]
### Analysis

Accessory not available via /api/accessories/<uniqueId> until accessories loaded in web UI

### Expected Behavior

Accessory should be available even though accessories haven't been loaded in the web UI.

### Steps To Reproduce

1. Restart Homebridge.
2. Attempt to fetch an accessory via the REST API, e.g. /api/accessories/<uniqueId>
3. Accessory is not available.
4. Login to the web UI and load accessories.
5. Attempt to fetch an accessory again via the REST API and it works perfectly fine.

### Logs

```markdown
No logs available.
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 412F",
        "username": "xxx",
        "port": 51009,
        "pin": "xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "dark-mode",
            "tempUnits": "c",
            "lang": "auto",
            "sessionTimeout": 86400000,
            "platform": "config"
        },
        {
            "name": "FibaroHC",
            "host": "xxx",
            "username": "xxx",
            "password": "xxx",
            "securitysystem": "disabled",
            "platform": "FibaroHC"
        },
        {
            "email": "xxx",
            "password": "xxx",
            "token": "xxx",
            "alarmCode": "xxx",
            "doorCode": "xxx",
            "pollInterval": 60,
            "platform": "verisure"
        }
    ]
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11) 
- Software: 1.3.8
- Node: v14.18.2 
- npm: v6.14.15 

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
@jimbju - This is from the package Homebridge-config-ui-x, please raise the issue there for visibility of the developer.

PS Is this possibly a timing issue as a lot of things occur during startup, and the data / connection is likely not available for a minute or so ?

**Comment by jimbju** [comment]
@NorthernMan54 thanks for info! I'll head over to the "Homebridge-config-ui-x" github!

`PS Is this possibly a timing issue as a lot of things occur during startup, and the data / connection is likely not available for a minute or so ?`

I don't think so, accessory is not available until I load accessories in the web UI, no matter how long I wait.
