### ISSUE TITLE
Why does Fresenius have a trademark on the name HomeBridge?

### ISSUE THREAD

**Issue by philkunz** [homebridge/homebridge#3154]
### Current Situation

See here: https://www.tmdn.org/tmview/#/tmview/detail/WO500000001409792

### Logs

```markdown
not applicable
```

### Configuration

```json
not applicable
```

### Environment

not applicable

### Process Supervisor

not applicable

### Additional Context

not applicable

**Comment by NorthernMan54** [comment]
Very good question, as we are a small group of technical minded individuals who created this a few years, never expecting to get to this level of usage.

Personally, I have a little chuckle when I see this local company where I live ( do they support Homebridge ? )

![image](https://user-images.githubusercontent.com/19808920/173363079-4d5d25b0-85bd-4f20-ad7f-718715460063.png)

**Comment by Apollon77** [comment]
They added it 07/06/2017 ... according t this GitHub repo the project here was active already since 2015 ... so if it would come to the point of issues the question is if the trademark is valid ...

**Comment by oznu** [comment]
As long as they don't try and make us change the project name, it's probably of little concern unless they are actually developing a "smart home hub" or a similar category of device that is blatantly attempting to mislead consumers.

**Comment by justme-1968** [comment]
the problem with trademark law is: if you don't watch the market and don't defend your trademark you will lose it. so doing nothing is probably not the right thing to do.

there is a trademark registry where you should be able to look at the categories they have used to register. if there is no overlap then it is probably ok.
