### ISSUE TITLE
Accessory name don't save on Homekit

### ISSUE THREAD

**Issue by Zazou49** [homebridge/homebridge#3161]
### Current Situation

Hello,

With one device I have a problem. If I change the name in Homekit App, it returns to his previous name few seconds after. It happens with a Xiaomi Aqara Temperature Sensor. 

I have multiple other Xiaomi Aqara Temperature Sensor without problem.

### Logs

```markdown
Name changing don't appears in logs.
```

### Configuration

```json
{
            "nativeHomeKitSensors": true,
            "name": "Hue",
            "anyOn": true,
            "groups": false,
            "nativeHomeKitLights": true,
            "lights": true,
            "hosts": [
                "192.168.xx.xx:xxxx"
            ],
            "effects": true,
            "schedules": false,
            "scenes": true,
            "linkButton": false,
            "excludeSensorTypes": [],
            "platform": "Hue",
            "sensors": true,
            "users": {
                "xxx": "xxx"
            },
            "resource": true,
            "rules": true
        }
```

### Environment

- OS: unRAID 6.10.2
- Software: 1.4.1
- Node: 16.15.0
- npm: 8.5.5
- Image : oznu/homebridge

### Process Supervisor

Docker (Mention image name in `Additional Context`)

**Comment by oznu** [comment]
Hello,

This seems to be a plugin specific issue. Please raise this issue on the plugin's own project page.
