### ISSUE TITLE
Error message: npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead

### ISSUE THREAD

**Issue by neekul** [homebridge/homebridge#3166]
### Current Situation

When ever I update / install a plugin I have started to get the below warning. I understand that I need to change something (after some googling) but not sure where / show to do so for HB, and also if it matters? Can I just ignore it or should I go about fixing it?

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

### Logs

```markdown
-
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge C16D",
        "username": "-",
        "port": 51059,
        "pin": "-"
    },
    "accessories": [
        {
            "name": "Front Door Left Open",
            "timeout": 300,
            "_bridge": {
                "username": "-",
                "port": 55690
            },
            "accessory": "ContactLeftOpenAccessory"
        }
    ],
    "platforms": [
        {
            "name": "Homebridge UI",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "region": 132,
            "email": "-",
            "password": "-",
            "cameras": [
                {
                    "serial": "-",
                    "username": "-",
                    "code": "-"
                },
                {
                    "serial": "-",
                    "username": "-",
                    "code": "-"
                }
            ],
            "options": {
                "sleepSwitch": false,
                "audioSwitch": false
            },
            "_bridge": {
                "username": "-",
                "port": 43175
            },
            "platform": "EZVIZ"
        },
        {
            "name": "Shelly",
            "admin": {
                "enabled": true
            },
            "platform": "Shelly",
            "_bridge": {
                "username": "-",
                "port": 33206
            }
        },
        {
            "devices": [
                {
                    "api_key": "-",
                    "device_id": "-",
                    "name": "Projector",
                    "ip": "-",
                    "mac": "-",
                    "inputs": [
                        {
                            "type": "input",
                            "name": "Vero",
                            "value": "HDMI2"
                        },
                        {
                            "type": "app",
                            "name": "Netflix",
                            "value": "3201907018807"
                        },
                        {
                            "type": "app",
                            "name": "Youtube",
                            "value": "111299001912"
                        },
                        {
                            "type": "app",
                            "name": "Disney+",
                            "value": "3201901017640"
                        }
                    ],
                    "keys": {
                        "INFORMATION": "KEY_HOME"
                    }
                }
            ],
            "platform": "SamsungTizen",
            "_bridge": {
                "username": "-",
                "port": 59243
            }
        },
        {
            "name": "Wiz Lights",
            "enableScenes": false,
            "platform": "WizSmarthome",
            "_bridge": {
                "username": "-",
                "port": 36454
            }
        },
        {
            "auth": "api-key",
            "apiKey": "-",
            "platform": "GlueHomebridge",
            "_bridge": {
                "username": "-",
                "port": 59922
            }
        },
        {
            "name": "Meross",
            "username": "-",
            "password": "-",
            "userkey": "-",
            "connection": "default",
            "debug": false,
            "_bridge": {
                "username": "-",
                "port": 37375
            },
            "platform": "Meross"
        },
        {
            "name": "Elgato Key Lights",
            "powerOnBehavior": 1,
            "switchOnDurationMs": 100,
            "platform": "ElgatoKeyLights",
            "_bridge": {
                "username": "-",
                "port": 57389
            }
        }
    ]
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software: v4.47.0
- Node: 16.15.1
- npm: 8.11.0

### Process Supervisor

hb-service

### Additional Context

-

**Comment by oznu** [comment]
You can ignore this. We still need to support older versions of npm for now.

**Comment by neekul** [comment]
Thanks for the reply!

**Comment by Krypto219** [comment]
Node worked in version v14.xx.xx. I installed v16.xx.xx for hardhat. After new version install, I can see this error.

**Comment by oznu** [comment]
It's not an error, it's just a warning that can be ignored.

**Comment by SIGMARIPPER** [comment]
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
# npm audit report

ansi-regex  5.0.0
Severity: high
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/ansi-regex

follow-redirects  <=1.14.7
Severity: high
Exposure of Sensitive Information to an Unauthorized Actor in follow-redirects - https://github.com/advisories/GHSA-pw2r-vq6v-hr8c
Exposure of sensitive information in follow-redirects - https://github.com/advisories/GHSA-74fj-2j2h-c42q
fix available via `npm audit fix`
node_modules/follow-redirects

minimist  <1.2.6
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
fix available via `npm audit fix`
node_modules/minimist

simple-git  <=3.4.0
Severity: high
Command injection in simple-git - https://github.com/advisories/GHSA-3f95-r44v-8mrg
Command injection in simple-git - https://github.com/advisories/GHSA-28xr-mwxg-3qc8
fix available via `npm audit fix --force`
Will install simple-git@3.10.0, which is a breaking change
node_modules/simple-git

**Comment by SIGMARIPPER** [comment]
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
8.11.0

**Comment by Schahineze-lairedj** [comment]
hello 
i have un error after do this command : npm i -g native-run


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code EACCES
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/native-run/bin/native-run
npm ERR! dest /usr/local/bin/native-run
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/native-run/bin/native-run' -> '/usr/local/bin/native-run'
npm ERR!  [Error: EACCES: permission denied, symlink '../lib/node_modules/native-run/bin/native-run' -> '/usr/local/bin/native-run'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/native-run/bin/native-run',
npm ERR!   dest: '/usr/local/bin/native-run'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

I need help please

**Comment by Taureans** [comment]
Hi, any resolution on this..I get the same error while updating homebridge or any plugins..

![image](https://github.com/homebridge/homebridge/assets/104729347/d299874a-634e-4ad5-babd-3540cbdc19ee)

![image](https://github.com/homebridge/homebridge/assets/104729347/9b7a9035-a118-421a-bb56-c62ace290c29)

**Comment by Taureans** [comment]
@oznu Any help or comments on this?
Much appreciated...
