### ISSUE TITLE
Adding the Homebridge Repository GPG key fails

### ISSUE THREAD

**Issue by antiero** [homebridge/homebridge#3169]
### Analysis

Running through install steps on Raspberry Pi the first command returns this error:

$ sudo curl -sSfL https://repo.homebridge.io/KEY.gpg | sudo gpg --dearmor | sudo tee /usr/share/keyrings/homebridge.gpg  > /dev/null

```
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
gpg: no valid OpenPGP data found.
```

### Expected Behavior

The command should not return an error

### Steps To Reproduce

Run the first install command in the terminal:

sudo curl -sSfL https://repo.homebridge.io/KEY.gpg | sudo gpg --dearmor | sudo tee /usr/share/keyrings/homebridge.gpg  > /dev/null

### Logs

```markdown
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
gpg: no valid OpenPGP data found.
```

### Configuration

```json
Raspberry Pi Zero 2.

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
```

### Environment

- OS: Raspbian GNU/Linux 10

### Process Supervisor

not applicable

**Comment by oznu** [comment]
> SSL certificate problem: certificate is not yet valid

The date on your device is wrong. Fix the date/time and it will work.
