### ISSUE TITLE
How can i change Homebridge's Local IP?

### ISSUE THREAD

**Issue by Tatitooo** [homebridge/homebridge#3181]
### Current Situation

My current local IP on Homebridge (running on ubuntu) is 192.168.1.34, but I want it to run on local IP 10.10.0.34 which always shows first when listing IPs.
![image](https://user-images.githubusercontent.com/23179501/178413504-4fb3cda0-9678-4d01-a25c-9ccb331e8eda.png)

### Logs

```markdown
.
```

### Configuration

```json
.
```

### Environment

- OS: Ubuntu 20.04.3 LTS
- Software: 1.5.0
- Node: v16.13.1
- npm: 8.10.0

### Process Supervisor

not applicable

### Additional Context

.

**Comment by oznu** [comment]
The IP shown there is just the default adapters IP address.

If you change the default adapter in the OS, it will be reflected there.
