### ISSUE TITLE
Release 4.50.0 question regarding Node.js

### ISSUE THREAD

**Issue by jmporter34** [homebridge/homebridge#3189]
### Current Situation

The release notes for 4.50.0 say ""Node.js v14.15.0 or later is REQUIRED... Do not update to this version if you are not running v14.15.0 or later"
How do I tell what version I am running, so I know whether or not to upgrade to 4.50.0 ?  
We're not all Linux programmers...
Thank you

### Logs

```markdown
None
```

### Configuration

```json
None
```

### Environment

- OS:
- Software: homebridge-config-ui-x v4.49.0
- Node:
- npm:

### Process Supervisor

other (Explain in `Additional Context`)

### Additional Context

I don't even know what you mean by "Process Supervisor".  I ran the Homebridge installer on a Raspberry Pi 3B+ and it's worked fine without me ever having to spelunk into its internals.

**Comment by oznu** [comment]
It would have warned you after clicking update if you weren't. The Node.js version is also displayed on the status / dashboard page in the System Info widget.

**Comment by jmporter34** [comment]
Ah, the Node.js version was off the bottom of the Status screen.  I had to scroll down to see it.
Thank you!
