### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by shanemcw** [homebridge/homebridge#3190]
### Analysis

On documentation page

https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings

The link 

> characteristic.updateValue

to

`https://developers.homebridge.io/HAP-NodeJS/classes/characteristic.html#updatevalue`

in the text

> This plugin slows down Homebridge...
> …
> If the action does take some time to complete, adjust your plugin code to return the callback() instantly, and call **characteristic.updateValue** once the action has completed.

is 404

### Expected Behavior

Current URL

### Steps To Reproduce

Click on link to 404 URL.

### Logs

```markdown
404

File not found

The site configured at this address does not contain the requested file.
```

### Configuration

```json
https://developers.homebridge.io/HAP-NodeJS/classes/characteristic.html#updatevalue
```

### Environment

**Characteristic Warnings**
oznu edited this page on Aug 20, 2021 · 15 revisions

### Process Supervisor

not applicable

**Comment by oznu** [comment]
Fixed; thanks.
