### ISSUE TITLE
Raspberry Pi Setup - Questions

### ISSUE THREAD

**Issue by jahirfiquitiva** [homebridge/homebridge#3194]
### Current Situation

Hello, I'm currently planning on getting a Raspberry Pi to be able to work as a server for HomeBridge, so it's always on and running.

Anyway, I have some questions regarding its setup as I have never done it or used a Raspberry Pi before.

The questions are:
- What's the recommended Raspberry Pi model for HomeBridge?
- What's the recommended storage size and RAM to run HomeBridge smoothly on a Raspberry Pi?
- Does HomeBridge work if I keep the Raspberry Pi connected via Ethernet? Or it must be connected to the same WiFi network?
- If I previously setup HomeBridge on a Mac or Docker, can I easily migrate to the Raspberry Pi? or I must start from scratch?

Thanks in advance!

### Logs

```markdown
None
```

### Configuration

```json
None
```

### Environment

None

### Process Supervisor

hb-service

**Comment by oznu** [comment]
> What's the recommended Raspberry Pi model for HomeBridge?

Raspberry Pi 4. Avoid the Zero W - it's painfully slow to do anything.

> What's the recommended storage size and RAM to run HomeBridge smoothly on a Raspberry Pi?

1GB RAM is fine, go with whatever you can afford.

> Does HomeBridge work if I keep the Raspberry Pi connected via Ethernet? Or it must be connected to the same WiFi network?

It must be on the same subnet, eg. 192.168.1.xxx. Ethernet 

> If I previously setup HomeBridge on a Mac or Docker, can I easily migrate to the Raspberry Pi? or I must start from scratch?

You can. The backup /  restore feature in the Homebridge UI will take care of everything.
