### ISSUE TITLE
“Ports” configuration ignored for Homebridge-Harmony external accessories

### ISSUE THREAD

**Issue by tacoma69** [homebridge/homebridge#3195]
### Analysis

“Ports” defined within config.json as per attached screenshot

![EF834E58-C907-4278-9558-4220F1E98382](https://user-images.githubusercontent.com/47449832/180570761-281b1336-d498-4e29-b192-5471cb2a9c7e.jpeg)

### Expected Behavior

External accessories such as TV created via homebridge-harmony are allocated ports from the range allowing the use of a firewall on the homebridge host.

However, the ports allocated to the accessories are random and not within the defined range - see attached image
![0928AC5F-C932-437E-8E07-CCEE354C6BE7](https://user-images.githubusercontent.com/47449832/180571282-1e0faa19-2bdc-4e6b-a3a5-44ac087ba266.jpeg)

### Steps To Reproduce

As per configuration - deleting accessories and restarting services had no change on observed behaviour

### Logs

```markdown
Can be provided as needed
```

### Configuration

```json
See zip attachment on comment below
```

### Environment

- OS: Debian Buster
- Software:
- Node: current
- npm: current

### Process Supervisor

systemd

**Comment by oznu** [comment]
Please share the full config

**Comment by tacoma69** [comment]
[config.json.zip](https://github.com/homebridge/homebridge/files/9173254/config.json.zip)

Uploaded config - I have since made the Harmony Plugin a child bridge and the same issue was observed

**Comment by oznu** [comment]
The child bridge ports are pre-defined in your config (as is normal) - you can adjust these to be inside your allowed port range.

**Comment by tacoma69** [comment]
Apologies for the delay getting back to you - I have the config as we discussed and attached above, but unless I ma missing something the devices are not picking up ports in the range defined for the child bridge?

Config
![Screenshot 2022-07-25 at 08 11 00](https://user-images.githubusercontent.com/47449832/180718805-920a4cf4-40b9-41db-89b5-fc65bbf18542.png)

Ports assigned at service start
![Screenshot 2022-07-25 at 08 06 11](https://user-images.githubusercontent.com/47449832/180718414-58502ce6-6821-4eb7-a433-58e66177a44f.png)

**Comment by oznu** [comment]
Defining a port range for a child bridge is not a valid option. Port ranges can only be configured at the top level of the config.

You also have port set to 38792 in the config, this will override any port ranges.
