### ISSUE TITLE
Heater/Cooler target mode characteristic missing

### ISSUE THREAD

**Issue by grzegorz914** [homebridge/homebridge#3196]
### Analysis

Right now for heater/cooler target operating mode we have:
0 - AUTO
1 - HETA
2 - COOL

![AF877442-71F5-48E6-9478-32AF837ACF27](https://user-images.githubusercontent.com/28867813/180607359-fb961b42-6ab5-450d-9bde-04cc2d7c9658.jpeg)

### Expected Behavior

Use all available modes:
0 - AUTO
1 - HETA
2 - COOL
3 - OFF
![3DB515E2-AA3D-4898-A0C9-1B553E2D0F17](https://user-images.githubusercontent.com/28867813/180607397-87822806-5081-4788-9798-be3a22be8f5f.jpeg)

### Steps To Reproduce

Just use heater/coller

### Logs

```markdown
`This plugin generated a warning from the characteristic 'Target Heater-Cooler State': characteristic was supplied illegal value: number 3 exceeded maximum of 2. See https://homebridge.io/w/JtMGR for more info.`
```

### Configuration

```json
{NA}
```

### Environment

- OS: macOS
- Software:
- Node: 16.15
- npm:

### Process Supervisor

hb-service

**Comment by oznu** [comment]
Unlike a thermostat service, the heater cooler service uses "Active" characteristic is used for on/off.

https://developers.homebridge.io/#/service/HeaterCooler

It allows you to just tap the tile and have it return to the "target state".
