### ISSUE TITLE
Homebridge fail to start, node: /lib/ld-linux-armhf.so.3: version

### ISSUE THREAD

**Issue by LegendaryWiz** [homebridge/homebridge#3201]
### Current Situation

My homebridge failed suddenly. I am no longer able to update Node as well. typing homebridge or node -V gives this list of message. I don't get it. It seems that some libraries are missing? The RPI has been running steadily for over 2 years already and I have not altered it in any way. My config json should be error free since the system was running fine for a long time till yesterday when it suddenly crashed. Please help me, I am completely lost at how to approach this issue. Thank you so much!!

pi@raspberrypi:~ $ homebridge
node: /lib/ld-linux-armhf.so.3: version `l?BCW?.?BGC??!.}' not found (required by node)
node: /lib/arm-linux-gnueabihf/libdl.so.2: version `l?BCW?.?BGC??!.}' not found (required by node)
node: /lib/arm-linux-gnueabihf/libpthread.so.0: version `l?BCW?.?BGC??!.}' not found (required by node)
node: /lib/arm-linux-gnueabihf/libgcc_s.so.1: version `GC??!.}' not found (required by node)
node: /lib/arm-linux-gnueabihf/libgcc_s.so.1: version `GCA?<4CTZACY_?<;.$gLI?EXx_34,14 ?CBAKCR]51>s/KxXAB?3.3	9 GLICPpV3.t??8' not found (required by node)
node: /lib/arm-linux-gnueabihf/libm.so.6: version `l?BCW?.?BGC??!.}' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CTZACY_?<;.$gLI?EXx_34,14 ?CBAKCR]51>s/KxXAB?3.3	9 GLICPpV3.t??8' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `gLI?EXx_34,14 ?CBAKCR]51>s/KxXAB?3.3	9 GLICPpV3.t??8' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `?CBAKCR]51>s/KxXAB?3.3	9 GLICPpV3.t??8' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `KxXAB?3.3	9 GLICPpV3.t??8' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLICPpV3.t??8' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXECI_1.3FO	BcX?s.t,35' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `FO	BcX?s.t,35' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBKL?_3n<?@gNIBC?P3.t,09' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `gNIBC?P3.t,09' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `UL	CRZP?.4.20' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `gLIBCXZ_s&E?IJKX\?2/4.2CHhCC_&?GNM?AWv,9`?LiBCG".1' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `E?IJKX\?2/4.2CHhCC_&?GNM?AWv,9`?LiBCG".1' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `CHhCC_&?GNM?AWv,9`?LiBCG".1' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `GNM?AWv,9`?LiBCG".1' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `?LiBCG".1' not found (required by node)
1?LICO2/6GlA?C;:>7P@' not found (required by node)`FLyC_
node: /lib/arm-linux-gnueabihf/libc.so.6: version `?LICO2/6GlA?C;:>7P@' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `GlA?C;:>7P@' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `l?BCW?.?BGC??!.}' not found (required by node)
pi@raspberrypi:~ $ cd .homebridge

### Logs

```markdown
pi@raspberrypi:~ $ homebridge
node: /lib/ld-linux-armhf.so.3: version `l?BCW?.?BGC??!.}' not found (required by node)
node: /lib/arm-linux-gnueabihf/libdl.so.2: version `l?BCW?.?BGC??!.}' not found (required by node)
node: /lib/arm-linux-gnueabihf/libpthread.so.0: version `l?BCW?.?BGC??!.}' not found (required by node)
node: /lib/arm-linux-gnueabihf/libgcc_s.so.1: version `GC??!.}' not found (required by node)
node: /lib/arm-linux-gnueabihf/libgcc_s.so.1: version `GCA?<4CTZACY_?<;.$gLI?EXx_34,14 ?CBAKCR]51>s/KxXAB?3.3	9 GLICPpV3.t??8' not found (required by node)
node: /lib/arm-linux-gnueabihf/libm.so.6: version `l?BCW?.?BGC??!.}' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CTZACY_?<;.$gLI?EXx_34,14 ?CBAKCR]51>s/KxXAB?3.3	9 GLICPpV3.t??8' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `gLI?EXx_34,14 ?CBAKCR]51>s/KxXAB?3.3	9 GLICPpV3.t??8' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `?CBAKCR]51>s/KxXAB?3.3	9 GLICPpV3.t??8' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `KxXAB?3.3	9 GLICPpV3.t??8' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLICPpV3.t??8' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXECI_1.3FO	BcX?s.t,35' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `FO	BcX?s.t,35' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBKL?_3n<?@gNIBC?P3.t,09' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `gNIBC?P3.t,09' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `UL	CRZP?.4.20' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `gLIBCXZ_s&E?IJKX\?2/4.2CHhCC_&?GNM?AWv,9`?LiBCG".1' not found (required by node)
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `E?IJKX\?2/4.2CHhCC_&?GNM?AWv,9`?LiBCG".1' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `CHhCC_&?GNM?AWv,9`?LiBCG".1' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `GNM?AWv,9`?LiBCG".1' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `?LiBCG".1' not found (required by node)
1?LICO2/6GlA?C;:>7P@' not found (required by node)`FLyC_
node: /lib/arm-linux-gnueabihf/libc.so.6: version `?LICO2/6GlA?C;:>7P@' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `GlA?C;:>7P@' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `l?BCW?.?BGC??!.}' not found (required by node)
pi@raspberrypi:~ $
```

### Configuration

```json
Config.json file uploaded in Additional Context.
```

### Environment

- OS: Raspbian GNU/Linux 9 (stretch)
- Software:
- Node:
- npm:
I cannot find the homebridge or node or npm version. Typing either homebridge -V or node -V or rpm -V brings me the long error logs that I describe above. 

### Process Supervisor

other (Explain in `Additional Context`)

### Additional Context

Environment: Raspberry Pi 3
[configjson.zip](https://github.com/homebridge/homebridge/files/9215983/configjson.zip)

**Comment by NorthernMan54** [comment]
If you haven’t changed anything my theory is a corrupted SD card.  So purchase a new SD card, and reinstall everything.  If you can copy the .homebridge directory and subdirectories off the old card, you may avoid having to set everything up in the home app again.
