### ISSUE TITLE
[Feature request] - more options for rotation direction

### ISSUE THREAD

**Issue by SunnyTam** [homebridge/homebridge#3202]
### Current Situation

I am new to homebridge, This program look amazing to me. I just tried a bit integrating my dyson fan into homebridge. 

I am trying to make an automation so that I can simple point the dyson cooler to me once I am siting in front of my computer. But I found that there is no interface for the plugin to accept rotation degree (360 degree )signal.

### Proposed Change

Can the service of `Air Purifier`, `Fan` and etc provide an extra optional characteristics for slider control to setup the rotation degree of the fan. So that plugins can help to pass this signal in the devices level

**Comment by NorthernMan54** [comment]
Just reading this and it appears you’re asking for an additional control for the Dyson plugin.  For these type of enhancement requests, please open the issue against the plugin your looking for the enhancement so that the plugin developer can be aware of the request.

**Comment by oznu** [comment]
Available "controls" are listed in the docs:

* https://developers.homebridge.io/#/service/AirPurifier
* https://developers.homebridge.io/#/service/Fanv2

While you can create custom characteristics - they aren't very useful in most cases as the Apple Home app won't show any controls for them.
