### ISSUE TITLE
HomeBridge auto join Wi-Fi network

### ISSUE THREAD

**Issue by angeloghisi** [homebridge/homebridge#3204]
### Current Situation

Hello everyone,
I’m using HomeBridge on my Raspberry Pi Zero 2W and it’s working great.

My answer is: sometimes happens that my home modem and Raspberry restarts (power cable disconnected, black out etc) and once they are back on, I have to manually open the Raspberry web interface, type my Wi-Fi password and wait for a couple of minutes to be able to use it again. If I am not aware that the modem restarted, the risk is that everything in my Home app is not responding (for example I cannot open the gate from outside when I get back home) unless I manually reconnect the Raspberry to my Wi-Fi network either from the internal network or from outside using VPN. This is very annoying…
Is there a way to make Raspberry always remember my Wi-Fi password and automatically join my home network as soon as it boots? Is also possibile to make HomeBridge wait for some time before trying to join the Wi-Fi network? This is useful to let the modem boot and start broadcasting Wi-Fi signal.

Thanks in advance to everyone, if necessary I am available for any further e explanation.

Angelo G.

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software: HomeBridge 1.5.0
- Node: 16.14.0
- npm: 8.5.1

### Process Supervisor

hb-service

**Comment by oznu** [comment]
You can disable the wifi setup portal which will stop this from happening: https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Disable-WiFi-Setup-Portal

**Comment by angeloghisi** [comment]
Thanks for your answer.

I tried disabling Wi-Fi Setup Portal and it actually auto join the previous network.

However when my modem restarts it takes a few minutes to reconnect and in the meantime one of the plugins in my HomeBridge gives me "getaddrinfo ENOTFOUND px1.tuyaeu.com" error.

I think this error is related to HomeBridge not able to contact Tuya servers because the internet connection is not yet established.

Is there a way to tell HomeBridge to wait, for example, 5 minutes before trying to join the Wi-Fi network? In this way we can be sure that the internet connection is working.

Thank you very much
