### ISSUE TITLE
Why are Ports 80 and 443 enabeld next to 8581?

### ISSUE THREAD

**Issue by PvdGulik** [homebridge/homebridge#3206]
### Current Situation

I have Homebridge installed on a Rpi together with domoticz.

Normally I access Homebridge via port 8581, and the HomeKit port is 51070. So far, so good!

But now the webpage of Homebridge is also reachable on port 80 and 443.
This conflicts with domoticz which uses 808 and 443.

First question, why is Homebridge using 80 and 443?
Second: how to disable this.

Thanks!

### Logs

```markdown
No relevant log output
```

### Configuration

```json
No settings in config.json
```

### Environment

- OS: Bullseye
- Software: 1.5.0
- Node: 16.16.0
- npm:

### Process Supervisor

hb-service

**Comment by oznu** [comment]
See https://github.com/homebridge/homebridge-raspbian-image/wiki/SSL-HTTPS-Access

Use "hb-config" to adjust the Nginx options to your likening.
