### ISSUE TITLE
I cant update Node.js

### ISSUE THREAD

**Issue by masterfordev** [homebridge/homebridge#3208]
### Current Situation

Im trying to upgrade Node.js using this: https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js#macos-and-linux
 but i get this errors: 

<img width="912" alt="image" src="https://user-images.githubusercontent.com/29960705/183570545-b7a55405-91d2-4736-a940-e0bb5cdd48e4.png">

Any idea how upgrade? i used this command: 
`sudo hb-service update-node`

Thanks.

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

- OS: Raspbian
- Software: Hombridge v1.5.0
- Node: v14.17.0
- npm: 7.17.0

### Process Supervisor

hb-service

**Comment by oznu** [comment]
Google the error on the lines starting with "E:" and "N:".

The issue is with your OS's repo list; you won't be able to do an "apt" update/install commands until you fix the underlying problem.

**Comment by oznu** [comment]
This might do it:

```
sudo apt update --allow-releaseinfo-change
```

**Comment by daniestermann** [comment]
This is still an issue for me on **Debian Stretch**.

```
sudo apt update --allow-releaseinfo-change
E: Command line option --allow-releaseinfo-change is not understood in combination with the other options
```

This is my base os:
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
```
