### ISSUE TITLE
New accessory names not showing up correctly on iOS 16

### ISSUE THREAD

**Issue by SamTheGeek** [homebridge/homebridge#3210]
### Analysis

When a new accessory with multiple sub-accessories is added via HomeBridge on iOS 16, the sub-accessories are shown with the parent accessory's name. If you edit the accessory and clear the default name, the suggested name (in grey text) is the correct accessory name for that sub accessory.

### Expected Behavior

The sub-accessory's suggested name would also be set as that accessory's default name.

### Steps To Reproduce

1. Install HB latest and pair to a device running iOS 16
2. Install the SonosSoSimple plugin
3. Connect the SonosSoSimple plugin to a speaker system
(Note: Steps 2 and 3 can be done with any plugin that shows a composite accessory, one that allows you to "show accessories as separate tiles")
4. Observe the new accessories added
5. Tap the tile in HomeKit to expand the accessory
6. Tap any of the sub-tiles to expand one of the sub-accessories
7. Scroll down in the sub-accessory to view sub-accessory settings
_The sub-accessory name will be the same as that of the parent accessory_
8. Clear the name of the sub-accessory by tapping the 'x'
_The suggested name for the sub-accessory (in gray) will be the correct name

### Logs

```markdown
No logs are applicable to this issue.
```

### Configuration

```json
{
            "soundbarsOnly": true,
            "roomNameAsName": false,
            "volume": "none",
            "platform": "SonosSoSimplePlatform"
        },
```

### Environment

- OS: Synology DSM 7.1
- Software: 1.5.0 (HAP v0.10.2)
- Node: 16.16.0
- npm: 8.11.0

### Process Supervisor

hb-service

### Additional Context

Installed via hb-syno-spk latest (3.0.9) but observed on prior versions too

**Comment by bradennapier** [comment]
This is how homekit works at the moment -- if you erase the name it assigns (as the parent) it will show the name you are wanting as a placeholder so you know what to set.  It is annoying but not homebridge issue afaik

**Comment by adriancable** [comment]
It's an iOS 16 bug. Have you reported this via Apple Feedback? I have, but the more reports Apple receives on an issue, the higher it's prioritized.

**Comment by carlosgamezvillegas** [comment]
I found out if you add the following to the accessory, its name will show up correctly:

      service.addOptionalCharacteristic(Characteristic.ConfiguredName);
      service.setCharacteristic(Characteristic.ConfiguredName, accessoryName);

kind regards,

**Comment by NorthernMan54** [comment]
Tks

I have updated a couple of my plugins that had multiple services per accessory.

**Comment by nfarina** [comment]
Thanks so much @carlosgamezvillegas, I added this fix to my Tesla accessory which previously required manually renaming _quite a lot_ of services!

**Comment by maisun** [comment]
Does the fix work under iOS 17? Looks like in iOS 17 I lost names of all sub-accessories in a single tile, anybody who has noticed the same?

**Comment by carlosgamezvillegas** [comment]
Yes, it does fix it under iOS 17

**Comment by afharo** [comment]
> I found out if you add the following to the accessory, its name will show up correctly:
> 
> ```
>   service.addOptionalCharacteristic(Characteristic.ConfiguredName);
>   service.setCharacteristic(Characteristic.ConfiguredName, accessoryName);
> ```
> 
> kind regards,

When I applied this fix, some users complained that their custom renames of the buttons are reset whenever we run these APIs (when the bridge restarts). Does anyone know how to avoid that?

_If the user manually overwrote the name, do not apply the plugin's configured name_

**Comment by carlosgamezvillegas** [comment]
@afharo, unfortunately I have not found a way to avoid that but I can think of two ways of solving this:

1. Make the fix optional. When the fix is disabled, in most cases, the name of the accessory is shown when the default name is deleted, this way the user can rename the accessories manually.
2. Provide an option to name the accessories in the plugin settings.

**Comment by afharo** [comment]
I came up with this solution: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/master/src/utils/ensure_name.ts

Hopefully, it inspires a more global solution at the Homebridge level 😇

**Comment by carlosgamezvillegas** [comment]
Glad to see you found a solution. I tried to implement it but I got errors (“storage” undefined) and I am not sure how to fix it.

**Comment by hjdhjd** [comment]
If you’d like to see a robust example of how to address naming challenges, and naming synchronization, take a look at HBUP, which is one of my own plugins: https://github.com/hjdhjd/homebridge-unifi-protect/blob/main/src/protect-device.ts

Look at the accessoryName getter/setter at the end of the file. You can also take a closer look at how you can approach service creation and removal earlier in the file, including dealing with naming. 

Enjoy.

**Comment by afharo** [comment]
> I tried to implement it but I got errors (“storage” undefined) and I am not sure how to fix it.

@carlosgamezvillegas, in case it helps, `hap` comes from the `homebridgeApi.hap` (where `homebridgeApi` is the one you get through your plugin's constructor).
