### ISSUE TITLE
How to turn on apple home app when tv is turned on from normal remote.

### ISSUE THREAD

**Issue by MhmetSrkya** [homebridge/homebridge#3215]
### Current Situation

When I turn on the TV or air conditioner from its remote, I want to see it open in the apple home application. There is no problem in opening and closing through the application. What can I do to see that Apple home is on when I open it with its own remote.

### Logs

```markdown
.
```

### Configuration

```json
.
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
This question should be raised against the plugin you are using to control your TV or Air Conditioner, and not against homebridge itself.  That will allow the plugin developer to see your question.   Please close this and raise there.

**Comment by MhmetSrkya** [comment]
I control tv and air conditioner with broadlink rm mini3.
