### ISSUE TITLE
Raspberry Pi install error: "curl failed to verify the legitimacy of the server ..."

### ISSUE THREAD

**Issue by antiero** [homebridge/homebridge#3217]
### Analysis

Running through installation instructions for Raspberry Pi, running this line causes an error:

`curl -sSfL https://repo.homebridge.io/KEY.gpg | sudo gpg --dearmor | sudo tee /usr/share/keyrings/homebridge.gpg  > /dev/null
`

Error: 
```
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
gpg: no valid OpenPGP data found.
```

### Expected Behavior

curl command step should not error out.

### Steps To Reproduce

On Raspberry pi terminal, run the following line:

curl failed to verify the legitimacy of the server 

### Logs

```markdown
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
gpg: no valid OpenPGP data found.
```

### Configuration

```json
Raspberry Pi Zero
```

### Environment

- OS: Raspberry Pi OS
- Software: n/a
- Node: n/a
- npm: n/a

### Process Supervisor

not applicable

### Additional Context

The fix to this is to add the '-k' flag, to avoid strict checking of certificates.

`curl -k -sSfL https://repo.homebridge.io/KEY.gpg | sudo gpg --dearmor | sudo tee /usr/share/keyrings/homebridge.gpg  > /dev/null
`

**Comment by oznu** [comment]
`https://repo.homebridge.io` has a valid SSL certificate. Make sure your server has up to date CAs and the `-k` flag won't be necessary.

<img width="777" alt="image" src="https://user-images.githubusercontent.com/3979615/184888188-d5760cb9-4efe-4d6f-966c-4b41e5a1c11f.png">
