### ISSUE TITLE
timeout over flow warning: infinity does not fit into 32bit signed integer

### ISSUE THREAD

**Issue by Rohirrimus2** [homebridge/homebridge#3219]
### Analysis

After installing home bridge the logs keep being filled with the error
<img width="1913" alt="Screenshot 2022-08-17 at 15 01 27" src="https://user-images.githubusercontent.com/111438349/185142505-574207a8-ddd7-43d6-9e00-70db24438f33.png">

### Expected Behavior

Working homebridge

### Steps To Reproduce

Install on MacOS:
<img width="322" alt="Screenshot 2022-08-17 at 15 10 39" src="https://user-images.githubusercontent.com/111438349/185142659-fa56810d-6bb8-4468-a5af-3af15c803eb7.png">

### Logs

```markdown
see the screenshoot
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge BFA4",
        "username": "0E:1B:A0:38:BF:A4",
        "port": 51696,
        "pin": "492-74-211"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Homebridge",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "en",
            "platform": "config"
        },
        {
            "platform": "XiaomiMiio",
            "name": "XiaomiMiio",
            "pollChanges": true,
            "pollInterval": 15,
            "searchInterval": 1800
        }
    ]
}

```

### Environment

- OS: MacOS
- Software: latest
- Node: v16.16.0
- npm: 8.11.0

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Can you share more details from the log from before the timeout duration error?

Also looking at the issue https://github.com/nodejs/help/issues/2332 they were able to trace the issue with an additional command line option

 --trace-warnings
