### ISSUE TITLE
Network interface issues

### ISSUE THREAD

**Issue by firedevel** [homebridge/homebridge#3221]
### Analysis

I set the WAN network mode to PPPoE and the homekit server does not work.
I checked the listening IP and I found that it was listening to PPPoE-Wan.
I added this to the configuration:
        `"bind": [
            "br-lan"
        ]`
It still listening to pppoe-wan.

### Expected Behavior

It should listen to br-lan.

### Steps To Reproduce

I added this to the configuration:
        `"bind": [
            "br-lan"
        ]`

### Logs

```markdown
[8/8/2022, 4:05:58 AM] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge 153B) is running on port 51420.
[8/8/2022, 4:05:58 AM] [Air Purifier] Connected to "Air Purifier" @ 192.168.1.208!
[8/8/2022, 4:05:58 AM] [xiaomifan] [Xiaomi Fan] Connected to Fan dmaker.fan.p5
[8/8/2022, 4:06:11 AM] [Homebridge UI] Homebridge Config UI X v4.50.0 is listening on :: port 8581
```

### Configuration

```json
"bridge": {
        "name": "Homebridge 153B",
        "username": "0E:CB:CC:9C:15:3B",
        "port": 51420,
        "pin": "796-98-392",
        "advertiser": "bonjour-hap",
        "bind": [
            "br-lan"
        ]


    },
```

### Environment

- OS: OpenWRT
- Software: v1.5.0
- Node: v16.14.2
- npm: 8.5.0

### Process Supervisor

init-d

### Additional Context

nohup homebridge -U /root/homebridge >> /root/homebridge/home-bridge.log &
<img width="360" alt="截屏2022-08-21 下午12 07 03" src="https://user-images.githubusercontent.com/70802618/185775067-2d9481ac-1753-4632-8839-7df7a5061146.png">

**Comment by nikita-komissarov** [comment]
+1

**Comment by firedevel** [comment]
Anyone here?

**Comment by spcqike** [comment]
Any solution to this? 

I run homebridge in Docker on Ubuntu and see some similar bug. 

Whenever I restart the container (because if host restart, docker update, Container update, whatever) it stops working. 

My host has two NICs, I use bind: I’m config to bind it to NIC1. But it always comes up, listening to NIC2. So I need to put NIC2 down, restart container and start NIC2 again manually.
