### ISSUE TITLE
Cannot login to home bridge

### ISSUE THREAD

**Issue by katiewinton** [homebridge/homebridge#3223]
### Current Situation

I've installed Homebridge through terminal commands. Everything seems to have installed and started correctly. However, it doesn't give me a user name and password.  I tried admin and admin like I've done on previous devices, but it says incorrect username or password.  
I've tried my system login and password, that doesn't work either. 
I had previously put homebridge on this computer, so I ran an uninstall to see if it was stuck.  That got it all the way to the end when it said "Homebridge Setup Complete", but just no login credentials. 

### Logs

```markdown
Last login: Wed Aug 24 08:12:13 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
WW-Ipad:~ katiewumc$ sudo hb-service install
Password:
ℹ Installing Homebridge Service
✖ ERROR: Port 8581 is already in use by another process on this host.
✖ You can specify another port using the --port flag, eg.
✖ EXAMPLE: hb-service install --port 8581
WW-Ipad:~ katiewumc$ hb-service install --port 8582
ℹ Installing Homebridge Service
✖ ERROR: This command must be executed using sudo on macOS
✖ sudo hb-service install
WW-Ipad:~ katiewumc$ sudo hb-service uninstall
ℹ Removing Homebridge Service
ℹ Stopping Homebridge Service...
✔ Homebridge Stopped
✔ Removed Homebridge Service
WW-Ipad:~ katiewumc$ sudo npm uninstall --location=global homebridge homebridge-config-ui-x

removed 442 packages, and audited 1 package in 1s

found 0 vulnerabilities
WW-Ipad:~ katiewumc$ node -v
v16.16.0
WW-Ipad:~ katiewumc$ sudo npm install -g --unsafe-perm homebridge homebridge-config-ui-x
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

added 442 packages, and audited 443 packages in 31s

71 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (2 low, 2 moderate, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
WW-Ipad:~ katiewumc$ sudo hb-service install
ℹ Installing Homebridge Service
ℹ Starting Homebridge Service...
✔ Homebridge Started

Manage Homebridge by going to one of the following in your browser:

* http://localhost:8581
* http://192.168.1.159:8581
* http://[fe80::14c0:3f11:873:254e]:8581

✔ Homebridge Setup Complete
WW-Ipad:~ katiewumc$
```

### Configuration

```json
WW-Ipad:~ katiewumc$ config.json
-bash: config.json: command not found
WW-Ipad:~ katiewumc$
```

### Environment

- OS: Monterey 12.5
- Software:
- Node:16.16.0
- npm:

### Process Supervisor

hb-service

**Comment by JurgenLB** [comment]
you need to reset your password;

To reset your password, delete the "auth.json" file in your homebridge storage directory (probably `~/.homebridge/auth.json) and restart. The logs will tell you where this file is when you fail to login, so you could check your log file manually if you need to.

Once reset you can login using the default admin/admin.

sorry but
This was littery the first item in my Google search.

**Comment by katiewinton** [comment]
Sorry but
This was NOT "littery" the first item in my google search. I'm new to this and am teaching myself, so you don't have to be patronizing. I did plenty of research and troubleshooting before I asked a simple question.

Also, those instructions didn't work. Says it can't find that file or directory. But thanks for your time.

**Comment by JurgenLB** [comment]
the output from my mac is;
sudo hb-service install —user homebridge
ℹ Installing Homebridge Service
ℹ Creating Homebridge directory: /Users/$username.homebridge
ℹ Creating default config.json: /Users/$username/.homebridge/config.json
ℹ Starting Homebridge Service...
✔ Homebridge Started

Manage Homebridge by going to one of the following in your browser:

* http://localhost:8581
* http://10.0.1.103:8581
* http://[fe80::23:a7cd:8ebb:9186]:8581

✔ Homebridge Setup Complete

For managing the config.json from commandline there is nano /Users/$username/.homebridge/config.json

hb-service status
ℹ Testing hb-service is running on port 8581...
✔ Homebridge UI Running

But normal you use http://localhost:8581 from your browser.

Hope this helps
