### ISSUE TITLE
Support using systemd-resolved as mDNS responder

### ISSUE THREAD

**Issue by elyscape** [homebridge/homebridge#3224]
### Current Situation

Homebridge currently supports [three different mDNS advertisers][mdns], two that run in-process and one that uses Avahi over D-Bus. For a while now, systemd-resolved has supported acting as an mDNS advertiser and resolver. If Homebridge is run on a system that uses systemd-resolved for mDNS, this can cause conflicts similar to #3077.

[mdns]: https://github.com/homebridge/homebridge/wiki/mDNS-Options

### Proposed Change

systemd-resolved, like Avahi, exposes [a D-Bus interface][dbus] for managing mDNS services. Ideally, Homebridge would have a systemd-resolved mDNS advertiser added that makes use of this interface.

[dbus]: https://www.freedesktop.org/software/systemd/man/org.freedesktop.resolve1.html

### Additional Context

A couple of `RegisterService` method's arguments have slightly misleading names. From the documentation:
```
RegisterService(in  s name,
                in  s name_template,
                in  s type,
                in  q service_port,
                in  q service_priority,
                in  q service_weight,
                in  aa{say} txt_datas,
                out o service_path);
```
`name` here refers to the name the service should appear as _in systemd_. `name_template` is the actual server instance name, so called because [it supports template expansion][name_template]. Probably you'd want to set both `name` and `name_template` to the same value.

[name_template]: https://www.freedesktop.org/software/systemd/man/systemd.dnssd.html#Name=

**Comment by elyscape** [comment]
Did some experimenting and it looks like updating an mDNS service can't be done directly; you must instead call `UnregisterService()` to tear down the existing service and then register a replacement with whatever changes you want.

**Comment by elyscape** [comment]
How do I unstale the issue?

**Comment by Supereg** [comment]
Related PR at `hap-nodejs`: https://github.com/homebridge/HAP-NodeJS/pull/965

**Comment by peterneutron** [comment]
HB Version: `Homebridge v1.6.0-beta.0 (HAP v0.11.0-beta.11)`

Is this not implemented in the latest beta? Using `"advertiser": "resolved"` results in the following error `Value provided in bridge.advertiser is not valid, reverting to platform default.`

**Comment by peterneutron** [comment]
Got it to work by adding `"resolved" /* RESOLVED */,` to `lib/server.js`. I also needed to convert `homebridge.pkla` as this format is deprecated in newer `polkit` versions.

`/etc/polkit-1/rules.d/homebridge.rules
`
```
polkit.addRule(function(action, subject) {
    if	(action.id == "org.freedesktop.resolve1.register-service" ||
	action.id == "org.freedesktop.resolve1.unregister-service" &&
        subject.isInGroup("homebridge")) {
        return polkit.Result.YES;
    }
});

**Comment by elyscape** [comment]
> Got it to work by adding `"resolved" /* RESOLVED */`, to `lib/server.js`.

Good catch. I'll open a PR fixing this momentarily.

> I also needed to convert `homebridge.pkla` as this format is deprecated in newer `polkit` versions.

Interesting. Can you point me at some documentation for this?

**Comment by elyscape** [comment]
@Supereg Here's the updated documentation for the wiki:

    ### systemd-resolved (Linux only, experimental)

    As of Homebridge 1.6.0, Linux users can choose the `resolved` advertiser, which uses systemd-resolved via D-Bus. If your system already uses systemd-resolved for mDNS support, this will likely provide the best experience. You can check this by running `resolvectl mdns`; if the first line is `Global: yes`, you should use this advertiser.

    Using the `resolved` advertiser has the following prerequisites:

    - Having `systemd-resolved` and `dbus` services installed and running.
    - Having `MulticastDNS` configured and enabled (see https://linuxreviews.org/Systemd-resolved).
    - Having configured the respective permissions to allow Homebridge to access `systemd-resolved` (see below).

    Setting up the `resolved` advertiser is only advised for more experienced users.

    #### Configuring permissions for systemd-resolved

    The user that runs Homebridge must have permission to register and unregister DNS-SD services with `systemd-resolved`. If you installed Homebridge using the official `apt` package, this should be handled for you automatically. Otherwise, you'll need to do this manually. First, run `pkcheck --version` to see what version of Polkit you're running.

    ##### Polkit version 0.105 or lower

    If the version is 0.105 or below, create a file in `/etc/polkit-1/localauthority/30-site.d` named `homebridge.pkla` with the following contents:

    ```
    [Homebridge ManageService]
    Identity=unix-user:homebridge
    Action=org.freedesktop.resolve1.register-service;org.freedesktop.resolve1.unregister-service
    ResultAny=yes
    ```

    If you run Homebridge as a different user than `homebridge`, you'll need to adjust the `Identity` line accordingly.

    ##### Polkit version 0.106 or higher

    If the version is 0.106 or higher, create a file in `/etc/polkit-1/rules.d` named `homebridge.rules` with the following contents:

    ```
    polkit.addRule(function(action, subject) {
        if ((action.id == "org.freedesktop.resolve1.register-service" ||
             action.id == "org.freedesktop.resolve1.unregister-service") &&
            subject.user == "homebridge") {
            return polkit.Result.YES;
        }
    });
    ```

    If you run Homebridge as a different user than `homebridge`, you'll need to adjust the condition accordingly.

**Comment by Supereg** [comment]
Thanks a lot for providing the updated Wiki descriptions 👍 . I updated the page accordingly.
