### ISSUE TITLE
Allow for grouping of accessories

### ISSUE THREAD

**Issue by oilcan-productions** [homebridge/homebridge#3225]
### Current Situation

Right now devices with multiple functions i.e. cameras with two way audio show up as 3-4 different accessories.
camera, (IR) light, speaker, microphone for a gen 3 ring stickup cam for example

### Proposed Change

Would love for a way to group these into one stickup camera accessory and then expose it to HomeKit.

**Comment by NorthernMan54** [comment]
Grouping is a tricky topic

First is the the plugin itself, when the developer codes it they can group multiple services into a single accessory.  But the grouping needs to be supported within homekit itself.  I use this with several of my plugins

Second iOS 16 has a feature which allows you to group accessories.

For the grouping you’re looking for, can you raise this with the plugin developer so they have visibility to your question.  And close this against homebridge itself as this does not appear to be a homebridge issue

**Comment by oilcan-productions** [comment]
Thanks understood I am trying out the grouping feature in iOS 16 right now
