### ISSUE TITLE
Latest LTS Version: 16.17.0

### ISSUE THREAD

**Issue by Ludelag** [homebridge/homebridge#3230]
### Current Situation

The Version that runs today Homebridge is in the 16.16, will be soon or can already run in the version 16.17?

### Proposed Change

Will be the version 16.17 supported?

**Comment by Apollon77** [comment]
Why it should not be supported? it is a minor update and so should not contain any breaking changes ... also because nodejs 16 is LTS

**Comment by Ludelag** [comment]
Is it an Yes? So is possible to update to version 16,17?

**Comment by Apollon77** [comment]
In a normal world there should nothing speak against it

**Comment by Ronneke** [comment]
When updating HB using docker(-compose) it states 16.16.0 is the most recent version although some plug-ins ask for 16.17.0 (e.g. Homebridge RPi)
