### ISSUE TITLE
ELV HMIP-PSM2 is shown as Lightbulb even if added as outlet in config.json

### ISSUE THREAD

**Issue by glowfishDE** [homebridge/homebridge#3231]
### Analysis

HMIP-PSM2 Outlet is shown as lightbulb in homebridge regardless if you add it as outlet in config.json or not.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/44566242/190865313-1532af55-57ab-4723-ac09-d61c762f8f19.png">

### Expected Behavior

Device is shown as outlet

### Steps To Reproduce

Add the device to your homekit instance
configure your config.json

### Logs

```markdown
[9/17/2022, 3:50:09 PM] Initializing platform accessory 'HmIP PSM 2 0034DXXXXXX'...

This is all that can be found in the log for that device
```

### Configuration

```json
{
            "platform": "HomeMatic",
            "name": "HomeMatic CCU2",
            "ccu_ip": "XXXXXX",
            "enable_hmip": "true",
            "filter_device": [],
            "filter_channel": [],
            "outlets": [
---> THIS WORKS                "BidCos-RF.OEQ0XXXXX:1",
---> THIS DOES NOT WORK        "HmIP-RF.0034DXXXXX:3"
            ],
            "doors": [
                "BidCos-RF.OEQXXXXXX:4"
            ],
            "windows": [],
            "switches": [],
            "RotaryHandles": [],
            "WindowContacts": [],
            "SmokeDetector": [],
            "programs": [
                "Aufmachen"
            ],
            "ios10": true,
            "variables": [],
            "subsection": "Homekit",
            "special": [
                {
                    "name": "XXXXXXXXX",
                    "type": "HM-THKL-XXXXXX",
                    "parameter": {
                        "address_sensor_close": "BidCos-RF.OEQXXXXXXXX:1.STATE",
                        "state_sensor_close": false,
                        "state_sensor_open": true,
                        "address_actor_open": "HmIP-RF.0013XXXXXXXXX:3.STATE",
                        "message_actor_open": {
                            "on": true,
                            "off": false
                        }
                    }
                }
            ],
            "services": [
                {
                    "type": "HM-THKL-XXXXXX",
                    "service": "HomeMaticHomeKitGarageDoorService"
                }
            ]
        },
```

### Environment

- OS: Alpine Linux
- Software: Oznu Hombridge Docker Image for Synology
- Node: v16.17.0
- npm: v8.15.0

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
After a quick review of this, isn’t it an issue with plug-in and not homebridge ?

am thinking this should be raised against the plugin rather than homebridge.

**Comment by glowfishDE** [comment]
Thanks bro for pointing me into the right direction ! i didnt even know it´s a plugin that handles the Homematic Part.. i forgot it ^^ But yeah - you are right! of course its a plugin! 

I found this: https://github.com/thkl/homebridge-homematic#configuration-changes-version--214

After Version 2.14 they moved the configuration part out of homebridges config.json into homematic_config.json.

So i added all my stuff into homematic_config.json instead and it works now :)

Thanks so much. I´ll close this bug.
