### ISSUE TITLE
IOS 16 problem with homebridge

### ISSUE THREAD

**Issue by Farzin-Abdi** [homebridge/homebridge#3232]
### Current Situation

I have installed homebridge on multiple Raspberry Pis it works great but with newer version of IOS 16 its not stable and some times doesnt work at all !

### Logs

```markdown
default
```

### Configuration

```json
default
```

### Environment

OS: Raspbian bullseye
Homebridge: 1.5.0

### Process Supervisor

hb-service

**Comment by rooi** [comment]
Hi, 

I may be experiencing similar issues.

Today two pi's (one pi 0 and one pi 4), running single or multiple instances of homebridge with the same environment and with various plugins, have stopped working approximately the same time. After power cycling with pi's they still won't boot.

I'm expecting that this has to do with the SD-card, probably a full SD-card, perhaps by some homebridge or homebridge-plugin log filling it up. 
Unfortunately I cannot confirm this today by checking the SD-card itself on my Mac, but I will try tomorrow.

In the meanwhile could you perhaps indicate which plugins you have installed, your configuration, and what logs are displayed? That will give me a chance to see if something is related to my issue and I expect it to be of help to your issue as well.

Thanks

**Comment by NorthernMan54** [comment]
FYI - I have been running IOS 16 since the start of the beta and have not had any issues.

**Comment by SpotlightForBugs** [comment]
> FYI - I have been running IOS 16 since the start of the beta and have not had any issues.

Same for me

**Comment by tomzt** [comment]
Do you see error Like this?

![IMG_3804](https://user-images.githubusercontent.com/785388/193418420-6ad3f501-a696-4e2e-89e6-ab5de24d0169.PNG)

**Comment by SpotlightForBugs** [comment]
I personally do not have any of the above-mentioned errors. However, I can not use any iPad as a home hub

**Comment by JurgenLB** [comment]
I’m also running iOS 16 with no errors for the moment. IPad is not possible anymore for using as a homeHub, this is blocked by Apple

**Comment by SpotlightForBugs** [comment]
> I’m also running iOS 16 with no errors for the moment. IPad is not possible anymore for using as a homeHub, this is blocked by Apple

I have mentioned exactly that, but it got discarded.
#3234
