### ISSUE TITLE
Remove iPad as an option for supported Home Hubs.

### ISSUE THREAD

**Issue by SpotlightForBugs** [homebridge/homebridge#3234]
### Current Situation

_A home hub is required to take advantage of features like receiving accessory notifications and allowing other people to control your home. You will not be able to view shared homes until those homes are also upgraded to the latest HomeKit. iPad will no longer be supported as a home hub._ — Apple 

### Logs

```markdown
/
```

### Configuration

```json
/
```

### Environment

- OS: iOS 16+, iPadOS 16+, ...

### Process Supervisor

not applicable

### Additional Context

The Docs should be changed to prevent people from buying iPads to get cheap Home Hubs

**Comment by adriancable** [comment]
That is a quote from Steve Moser @ MacRumors, not a quote from Apple. It is also incorrect.

iPads work just fine as home hubs on iOS 16. (They will not work as home hubs for Matter devices, because they lack a Thread radio, but that has nothing to do with HomeKit.)

**Comment by SpotlightForBugs** [comment]
That's no true. Unfortunately, using the iPad as a home hub can only be done if the device which sets up the home is not OS16+

The claims Apple did there are not true this can be seen in the discover page of the Apple home app on OS16+ devices.

**Comment by SpotlightForBugs** [comment]
![image](https://user-images.githubusercontent.com/73603712/191895923-b56d8e23-0abf-4e19-a22f-44df5436533f.png)

**Comment by SpotlightForBugs** [comment]
You can not select your homes architecture. I am using iOS 16.1 (Dev Beta) but my stable builds also disallow selecting the architecture. 
When I set up my home hub, there are only 2 options available: HomePod (mini) and Apple TV my iPad on OS 15.7 can not be added as a home hub, despite it is claiming it could 

Excuse my bad English

**Comment by SpotlightForBugs** [comment]
![image](https://user-images.githubusercontent.com/73603712/191896316-b2647e58-4326-45ac-bd5f-94f3c86f9d9e.png)

**Comment by SpotlightForBugs** [comment]
Here you can see the home app listing the available options for home hubs. 

![image](https://user-images.githubusercontent.com/73603712/191896514-14df6927-1fee-4719-822d-9fce975e8751.png)

The iPad is missing

**Comment by adriancable** [comment]
@SpotlightForBugs - your original post talked about iOS 16, whereas your screenshots are from a dev beta of iOS 16.1. I can definitely say that, for iOS 16, your original post was incorrect. Home hub functionality continues to work as before, including on iPads.

For iOS 16.1, it is hard to say because we are still in beta and cannot predict how the final release will work. It is possible for example that homes created prior to 16.1 will continue to work with iPads as Home Hubs, but homes created with 16.1 will not.

Regardless, I do not think it is appropriate at this time to update Homebridge docs based on behaviour we are inferring from an unreleased OS.

**Comment by SpotlightForBugs** [comment]
@adriancable I totally agree, but I wanted to help. I hope that Apple does not purge iPad's functionality as a home hub.

**Comment by adriancable** [comment]
@SpotlightForBugs - I appreciate that! (Just to be clear, no criticism at all of your intention here!)

I do think we should wait to see what actually happens before making any changes to Homebridge or the docs, since there is so much uncertainty.

**Comment by SpotlightForBugs** [comment]
👍

**Comment by SpotlightForBugs** [comment]
I’m afraid we can reopen the issue...

**Comment by adriancable** [comment]
Do you have any additional information on this? The iPad still works as a home hub, even on the latest iPadOS 16.1 dev beta 11. I don’t see anything has changed.

**Comment by SpotlightForBugs** [comment]
[German page, is more direct](https://support.apple.com/de-de/HT207057)
_Das iPad wird nicht als Steuerzentrale in der neuen Home-Architektur unterstützt, die zuverlässiger und effizienter ist und im Laufe dieses Jahres als separates Upgrade in der Home-App erhältlich sein wird._
--> German version is explaining the abolishment.
ii) [tv-home](https://www.apple.com/tv-home)/ --> no more iPad image

iii)[home-app](https://www.apple.com/home-app/ )
---> _HomePod mini and Apple TV. The keys to even more control._

_The Home app can do even more with the help of your HomePod mini or Apple TV. Either one can be set up as a smart home hub, giving you access to your home while you’re away and letting you automate all of your home’s smart accessories. And your HomePod mini or Apple TV hub is also an essential building block for Matter — the new smart home industry standard that will be compatible with more accessories, and even connect them across platforms.[2](https://www.apple.com/home-app/#footnote-2_)_

The footnote leads to the following text:
[2 ](https://www.apple.com/home-app/#footnote-2_)_And with HomePod mini or Apple TV set up as the ultimate home hub[...]_

**Comment by adriancable** [comment]
It isn't clear to me that this provides any further information.

We know that 'the new architecture' is required for Matter support. We also know 'the new architecture' won't allow iPads to be supported as home hubs. We don't know what (if any) bearing 'the new architecture' has on HomeKit, which is the critical question.

The quote in the Apple support article you link to doesn't mention HomeKit, so it leaves that important question unanswered.

**Comment by SpotlightForBugs** [comment]
That's true. I hope the switch to the new architecture is not permanent and not forced...
Have a good day,
SFB

**Comment by NorthernMan54** [comment]
Where do we have this documented?  I saw this on homebridge.io

 With the addition of a [home hub (AppleTV, HomePod or iPad)](https://support.apple.com/en-au/HT207057) you can create powerful automations and securely control your devices even when you're not at home.

https://homebridge.io/

am thinking we just edit the page to remove the reference and direct people to the Apple support site. So if this changes in the future we don’t need to make any updates.

**Comment by SpotlightForBugs** [comment]
![image](https://user-images.githubusercontent.com/73603712/194601321-323e6765-abcd-4950-b787-e535fa48a946.jpeg)

I have the proof. It's from the home app, in the section bridges

**Comment by SpotlightForBugs** [comment]
@adriancable 
I am sorry to disturb you.

**Comment by SpotlightForBugs** [comment]
> Do you have any additional information on this? The iPad still works as a home hub, even on the latest iPadOS 16.1 dev beta 11. I don’t see anything has changed.

Yes, please read the message above

**Comment by adriancable** [comment]
Which part of the screenshot, specifically?

**Comment by SpotlightForBugs** [comment]
> Which part of the screenshot, specifically?

 ![image](https://user-images.githubusercontent.com/73603712/195652922-20645823-4fa5-43e6-96fa-a952bb91edb8.jpeg)

**Comment by adriancable** [comment]
@SpotlightForBugs - the wording of that message has been unchanged, at least since iOS 13, and maybe even earlier. The message has never mentioned iPad as a home hub option. This may be Apple 'nudging' people to use Apple TVs or HomePods. But because that message hasn't changed for many years, you cannot draw any conclusions from it.

See for example this article from March 2020 (i.e. iOS 13), which includes a screenshot showing the identical message: https://www.evehome.com/en-us/blog/the-home-hub-essential-device-for-homekit-enabled-accessories
