### ISSUE TITLE
"No Response" again

### ISSUE THREAD

**Issue by ssllii** [homebridge/homebridge#3238]
### Analysis

I was getting "No Response" for a while.  about a month ago, I removed the homebridge from HomeKit and re-added it.  It has worked since.
A few days ago, it started getting all the "No Response" again.  I do get notifications.
Just now, I removed the home bridge again and re-added everything.  It found everything.  Unfortunately, as soon as everything got re-added, it started getting "No Response" again.
There was no change on my Raspberry Pi setup.   I did upgrade to iOS 16 on my phone.

### Expected Behavior

Should be able to control the accessaries.

### Steps To Reproduce

Just run homebridge

### Logs

```markdown
Relevant log will be provided as needed
```

### Configuration

```json
no change
```

### Environment

- OS: Linux
- Software: 
- Node: v16.16
- npm: 8.11.0

### Process Supervisor

hb-service

**Comment by tomzt** [comment]
Do you see error like this

![](https://user-images.githubusercontent.com/785388/193418420-6ad3f501-a696-4e2e-89e6-ab5de24d0169.PNG)

**Comment by ssllii** [comment]
No.  Just each accessories has the status "No Response".

**Comment by dreondre** [comment]
I’m encountering something similar where it goes into “No response” until I restart homebridge. I’m running it using docker. 
I turned on debug logging to see if I get more info.

**Comment by genevera** [comment]
I'm experiencing the same thing, sort of.  My Home app on my laptop sees nothing but my iPad sees everything.

**Comment by martinstjqc** [comment]
Same for me!

**Comment by bradennapier** [comment]
Yepp homebridge is now broken - hope its not apple trying to put a stop to people using it... that would be ridiculous

**Comment by ssllii** [comment]
After another round of deleting the bridge and readding, it has been working again.    The only problem is that I will never know when the change is that causes it to fail again, and it will fail again based on my previous experiences. :-(

**Comment by JurgenLB** [comment]
For me homebridge is still working and even when I’m not at home my devices keep refreshing. Sometimes there are 1 or 2 devices not responding but that resolves itself. Maybe you can investigate your different plugins or use child-bridges to find your problem

**Comment by MoTechnicalities** [comment]
Often a No Response issue can arise from failing to separate plugins into their own Child Bridge. The Tuya plugin is definitely one needing its own Child Bridge.

You also want to reboot your router and Apple Hub first before strait up blaming Homebridge. Apple has had many bugs since it's updates to iOS 16 and above.

**Comment by ChrisColotti** [comment]
I just hit this after 16.1.1 (oddly 16.1 was fine).  Hubs are AppleTV's (all 16.1) and an iPad (16.1.1).  I may remove the iPad being iOS keeps a different version than AppleTV's.  All items have been rebooted as well as the core router (network is all Ubiquiti) but devices were showing prior to the iPhone going to 16.1.1 oddly.  It was all working great for months even through ios 15 updates and even the initial 16.0 / 16.1 update.  All devices are on the same L2 segment internally on the network as well with the HomeBridge Docker container.  Very odd and I removed the bridge and now can not even add it back to the home...

**Comment by ChrisColotti** [comment]
@bradennapier I checked my logs nothing was updated and I don't let them update automatically.  There hasn't been an update for about a month and it sort of recently stopped working.  It's almost impossible to track down the stoppage and even why now I can't re-add the bridge

**Comment by ChrisColotti** [comment]
@bradennapier very little on the UBNT side earliest is 4 months old...  https://community.ui.com/search/questions/?q=homebridge
