### ISSUE TITLE
Move home bridge to 64bit version of Raspbian GNU/Linux 11 (bullseye

### ISSUE THREAD

**Issue by rionshin** [homebridge/homebridge#3239]
### Current Situation

In the moment the HB is running on 32bit version of Raspbian and that is limitation because a lot of softwares requires 64bit architecture. 

### Proposed Change

Use Raspbian GNU/Linux 11 (bullseye) 64bit. 

### Additional Context

I am running docker on same Raspbian and I have issues install for example influxDB v2 which requires 64bit architecture.

**Comment by podycust** [comment]
its as simple as creating a backup of your config and remembering which plugs you have installed then installing Raspberry Pi OS 64bit then installing home bridge and finally restoring the config and plugins
