### ISSUE TITLE
ios 16 cannot add homebridge to  home app

### ISSUE THREAD

**Issue by captainstdin** [homebridge/homebridge#3240]
### Analysis

you can view this video link 

[https://vkceyugu.cdn.bspapp.com/VKCEYUGU-281cb6e1-62e4-45fd-877a-d8e9d83bfd8f/514c7e2d-3749-4f53-81da-761c3b47d65a.MP4](https://vkceyugu.cdn.bspapp.com/VKCEYUGU-281cb6e1-62e4-45fd-877a-d8e9d83bfd8f/514c7e2d-3749-4f53-81da-761c3b47d65a.MP4)

### Expected Behavior

1

### Steps To Reproduce

1

### Logs

```markdown
1
```

### Configuration

```json
1
```

### Environment

- OS: 16.0.2
- Software: homebridge@1.5.0

Node.js 版本	v16.13.1
Npm 版本	v8.1.2

### Process Supervisor

hb-service

**Comment by no-Legend** [comment]
Same problem here, iOS 16.0.2 and also iOS 16.1 beta with the same behavior
