### ISSUE TITLE
Can't connect to Homebridge UI since upate to Synology DSM 7.1 Update 1

### ISSUE THREAD

**Issue by canoben** [homebridge/homebridge#3245]
### Current Situation

I'm not sure, it may just be a coincidence, but since updating to Synology DSM 7.1.1-42962 Update 1 I can no longer connect to the Homebridge UI web interface.
Checking the logs, I noticed that there is a repeating string of "Registering..." and "Withdrawing..." messages. I'm running Homebridge in a Docker container on a Synology RS818 with an IP of 192.168.1.75. The addresses 192.168.1.175 / 176 and 177 that appear in the log are those of the unused (unconnected) 3 Ethernet ports out of the 4 on the device.
I've never encountered this problem in my years of using Homebridge before.

Is there anything I could try, short of downgrading DSM?

### Logs

```markdown
Withdrawing address record for 192.168.1.177 on ovs_eth2.                                                
Withdrawing address record for 192.168.1.176 on ovs_eth1.                                                
Withdrawing address record for 192.168.1.175 on ovs_eth0.                                                
Withdrawing address record for ::1 on lo.                                                                
Withdrawing address record for 127.0.0.1 on lo.                                                          
Host name conflict, retrying with homebridge-17                                                          
Registering new address record for fe80::3473:70ff:fe8d:2f59 on dockere25ba39.*.                         
Registering new address record for fe80::6c2b:adff:fe04:35cc on dockercb9c501.*.                         
Registering new address record for fe80::48d2:c1ff:feb1:7680 on docker1779d18.*.                         
Registering new address record for fe80::f887:50ff:fe16:5e87 on docker87b2cc7.*.                         
Registering new address record for fe80::42:66ff:fe3d:76 on docker0.*.                                   
Registering new address record for 172.17.0.1 on docker0.IPv4.                                           
Registering new address record for 192.168.10.1 on docker-aba84990.IPv4.                                 
Registering new address record for 192.168.1.75 on ovs_eth3.IPv4.                                        
Registering new address record for 192.168.1.177 on ovs_eth2.IPv4.                                       
Registering new address record for 192.168.1.176 on ovs_eth1.IPv4.
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:EC:88:E1:7D:A0",
        "port": 51826,
        "pin": "815-89-218"
    },
    "platforms": [
        {
            ... DELETED ....
        },
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        }
    ],
    "accessories": []
}
```

### Environment

- OS: Synology DSM 7.1.1-42962 Update 1
Can't verify version numbers, here's the output form terminal:
                                                                                                         
bash: node: command not found                                                                            
Node.js Version:                                                                                         
Node.js Path:                                                                                            
Plugin Path: /var/lib/homebridge/node_modules                                                            
                                                                                                         
Update Node.js: hb-service update-node                                                                   
                                                                                                         
Install Plugin: hb-service add homebridge-plugin-name                                                    
Remove Plugin: hb-service remove homebridge-plugin-name                                                  

### Process Supervisor

Docker (Mention image name in `Additional Context`)

**Comment by dyelton** [comment]
Same issue here

**Comment by bmg76** [comment]
I am having the same issue as well.
Is preventing me from updating anything as I cannot get into the logon screen as just sits there trying to "load"

**Comment by MiOrt** [comment]
Same here, already [opened an issue](https://github.com/oznu/homebridge-config-ui-x/issues/1422) at the oznu/homebridge-config-ui-x repo-page.

**Comment by canoben** [comment]
> Same connection problem here, already [opened an issue](https://github.com/oznu/homebridge-config-ui-x/issues/1422) at the oznu/homebridge-config-ui-x repo-page.
> 
> @canoben : Where did you find these logs?

When restarting the docker image, I click on "Details", there is a log tab.

**Comment by MarkM500** [comment]
same issue here. Is there just a solution?

**Comment by MiOrt** [comment]
Just figured out the same problem occurs on other docker-containers as well. All UI can be reached by mobile devices like iPad, iPhone etc but not from my my (no matter which browser). Just ran into that issue trying out scrypted, so it seems not to be a Homebridge (UI) problem?

**Comment by E-vd-H** [comment]
Same issue here as well
