### ISSUE TITLE
Issue when upgrading to Homebridge v1.5.1

### ISSUE THREAD

**Issue by grenona** [homebridge/homebridge#3249]
### Analysis

i try to upgrade to lates version, i get this error (screenshot) if i apply chown fix, Homebridge restart for ever

![2022-10-25_10-14-58](https://user-images.githubusercontent.com/88557992/197798599-169ce24a-c44d-4bac-95c6-b0692e4e09bf.jpg)

### Expected Behavior

.

### Steps To Reproduce

.

### Logs

```markdown
.
```

### Configuration

```json
.
```

### Environment

Mac OS Ventura 13 

### Process Supervisor

not applicable

**Comment by Gotcha182** [comment]
I am also getting no response from all of my homebridge devices with the newest update. Not sure if it is iOS 16.1 or something with homebridge causing it

**Comment by dilanpatel20** [comment]
I am having the same issue. I can delete the bridge from the app and readd it, then it will work for like 30 seconds then everything says 'No Response'. Tried deleteing and redownloading plugins and same issue. I am runing on on latest iOS and MacOS.

**Comment by mofitn3577** [comment]
Same something seriously wrong with this upgrade I can't do anything now

**Comment by donavanbecker** [comment]
@grenona Please indicate the process supervisor.

Same for everyone else.

I have updated 5 completely different homes/Homebridges and have no issues with this update.

**Comment by grenona** [comment]
@donavanbecker Hi how could i found this information Process Supervisor

**Comment by grenona** [comment]
![2022-10-25_9-57-40](https://user-images.githubusercontent.com/88557992/198045225-ddbf4990-8cd3-4b8c-82c6-694a4220e6a1.jpg)

**Comment by grenona** [comment]
![2022-10-26_9-54-16](https://user-images.githubusercontent.com/88557992/198045314-ec97ff59-5ab7-4a06-9356-33c659f3c401.jpg)

**Comment by grenona** [comment]
[2022-10-26t12_50_54_104z-debug-0.log](https://github.com/homebridge/homebridge/files/9870169/2022-10-26t12_50_54_104z-debug-0.log)

**Comment by donavanbecker** [comment]
@grenona this is what you will need to run in terminal:

```
sudo rm -R /usr/local/lib/node_modules/homebridge
```
and 
```
sudo rm -R /usr/local/lib/node_modules/.homebridge-pWGKwhUt
```
finally:
```
sudo npm install -g --unsafe-perm homebridge
```

**Comment by mofitn3577** [comment]
I need to hire someone that's proficient in this stuff or something to help when stuff like this happens but I am running a business and when shit like this happens I can't always fix it and it takes me forever I wasted 5 hours yesterday and today I sitll have my whole house not working because I lost all the plugins when this update glitched and the time it takes me to fix something like this I just don't have. Anyone have advice? I put a ton of time into getting all my plugins configured and all my automations and everything dialed in and then one day they come out with an update that wipes everything out of nowhere and its extremely inconvenient to have everything in my house depenent on this and then have it down for days trying to figure out how to fix it with my limited coding knowledge. I guess theres an auto backup on the pi but as far as me getting this update to install correctly and then get everything restored from that backup its not gonna happen until i get some free time unless I can pay someone to look at the logs and just tell my what commands to type in and make it happen.

**Comment by cheme75** [comment]
> I need to hire someone that's proficient in this stuff or something to help when stuff like this happens but I am running a business and when shit like this happens I can't always fix it and it takes me forever I wasted 5 hours yesterday and today I sitll have my whole house not working because I lost all the plugins when this update glitched and the time it takes me to fix something like this I just don't have. Anyone have advice? I put a ton of time into getting all my plugins configured and all my automations and everything dialed in and then one day they come out with an update that wipes everything out of nowhere and its extremely inconvenient to have everything in my house depenent on this and then have it down for days trying to figure out how to fix it with my limited coding knowledge. I guess theres an auto backup on the pi but as far as me getting this update to install correctly and then get everything restored from that backup its not gonna happen until i get some free time unless I can pay someone to look at the logs and just tell my what commands to type in and make it happen.

My step son runs a biz and since he is into apple and using HomeKit, he limits himself to apple compatible devices to avoid wasting his time on fixing things like homebridge plug-ins. I’m retired and don’t rely on much automation,  so for me, I got the time to fuss with this stuff. No judgement - Just sayin’  fwiw, there are some users on discord as well who may do this type of tech support. If no one here offers, try discord or maybe Reddit.

**Comment by mofitn3577** [comment]
Thanks yeah I guess Reddit would be a good place to look for that. Though I
would think on GitHub there would def be people that are self employed and
would want to take on clients to have some extra consistent coding work. I
need coding done on my website too and constantly need things done with
apis to integrate different platforms together for my online sales and
marketing platforms. Ironically part of my business is installation of home
automation equipment along with networking and security camera systems and
all that. My background is in installing large commercial audio/video
systems, URC systems for businesses, Directv lodging and institutions, etc.
but with non competes when I started my own business I had to switch to
residential. I just never learned coding young enough to really become
proficient with it but I end up having to fuck with it all the time and I
rely on people on here cuz I just follow what they tell me to do haha I’ve
learned a lot on here though but sometimes it’s still way over my head.
this one nothing is working it might require someone that knows what
they’re doing. I’m not on macOS but mine did the same exact thing as his
did at the exact same time when it tried to do this new update.

**Comment by mofitn3577** [comment]
> as stated before @mofitn3577, we specific device and supervisor info. This issue has to do with macOS and it sounds like your is raspbian. I had no issues with this update on all 5 instances that I run so it is something else that is causing this, potentially npm

Yes I think you're right. I follwed a whole tutorial yesterday to update nodejs node and npm and when it was all done it seemed good but I get this message when i try to install homebridge it tells me npm is not known to run on  node.js version 9.9.0 but it says i have version 12.22.12 installed. It makes no sense to me i followed everything i was supposed to do and got everything updated and fixed but npm still things its running on an older version of node.js for whatever reason. 
![Screenshot 2022-10-27 003625](https://user-images.githubusercontent.com/67087818/198192813-e2d0c953-9c5d-4bd7-b56c-dcca90bdd676.jpg)

**Comment by mofitn3577** [comment]
> > as stated before @mofitn3577, we specific device and supervisor info. This issue has to do with macOS and it sounds like your is raspbian. I had no issues with this update on all 5 instances that I run so it is something else that is causing this, potentially npm
> 
> Yes I think you're right. I follwed a whole tutorial yesterday to update nodejs node and npm and when it was all done it seemed good but I get this message when i try to install homebridge it tells me npm is not known to run on node.js version 9.9.0 but it says i have version 12.22.12 installed. It makes no sense to me i followed everything i was supposed to do and got everything updated and fixed but npm still things its running on an older version of node.js for whatever reason. ![Screenshot 2022-10-27 003625](https://user-images.githubusercontent.com/67087818/198192813-e2d0c953-9c5d-4bd7-b56c-dcca90bdd676.jpg)

I have node.js 18.02 or whatever the newest is on my windows computer but 12.22.12 is the newest it will let me install on the pi apparently and npm is the newest I can get and it thinks node.js is still at v.9.9.0

**Comment by mofitn3577** [comment]
NPM has enoent error it cant find the json file i guess. I looked this up and it tells me i need to clear the npm cache which when enter that command i get the npm is not known to run on node.js v9.9.0 message again. Everything has just been taking me in circles and gotten me nowhere since thie happened yesterday. 
![Screenshot 2022-10-27 005202](https://user-images.githubusercontent.com/67087818/198195611-abf773f5-ff78-4257-9686-3fcb783d82f5.jpg)

**Comment by mofitn3577** [comment]
Homebridge logs tell me to go to  https://homebridge.io/w/JJSgZ  for help which sends me back in the circle again and tells me to run 
sudo npm install -g --unsafe-perm homebridge

Which of course brings me to npm is know not to run on node.js v9.9.0

**Comment by mofitn3577** [comment]
Wow i had to use hb-config to upgrade node.js further to get it to 18.12.0 not follow these other tutorials for hours. That didnt fix it though NPM still gives me the same message about v9.9.0 if I try to do anything. 

Tried to uninstall npm and It wont do that. 

i just used this to purge both to reinstall to fix it
sudo apt --auto-remove purge npm
sudo apt --auto-remove purge nodejs

after I tried to reinstall node.js fresh since it was just unininstalled and it says node.js v18.12.0 is already up to date. Nothing has worked ive been doing this since yesterday going in circles.

**Comment by mofitn3577** [comment]
pi@homebridge:~ $ sudo apt-get remove nodejs npm
sudo apt-get update
sudo apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'nodejs' is not installed, so not removed
Package 'npm' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 https://repo.homebridge.io stable InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:3 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@homebridge:~ $ sudo apt-get install -y nodejs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libc-ares2 libjs-highlight.js libnode72 nodejs-doc
Suggested packages:
  npm
The following NEW packages will be installed:
  libc-ares2 libjs-highlight.js libnode72 nodejs nodejs-doc
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.5 MB of archives.
After this operation, 45.6 MB of additional disk space will be used.
Get:1 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libc-ares2 armhf 1.17.1-1+deb11u1 [96.0 kB]
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libjs-highlight.js all 9.18.5+dfsg1-1 [397 kB]
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf libnode72 armhf 12.22.12~dfsg-1~deb11u1 [7,263 kB]
Get:4 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf nodejs armhf 12.22.12~dfsg-1~deb11u1 [147 kB]
Get:5 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf nodejs-doc all 12.22.12~dfsg-1~deb11u1 [2,547 kB]
Fetched 10.5 MB in 3s (4,007 kB/s)
Selecting previously unselected package libc-ares2:armhf.
(Reading database ... 152839 files and directories currently installed.)
Preparing to unpack .../libc-ares2_1.17.1-1+deb11u1_armhf.deb ...
Unpacking libc-ares2:armhf (1.17.1-1+deb11u1) ...
Selecting previously unselected package libjs-highlight.js.
Preparing to unpack .../libjs-highlight.js_9.18.5+dfsg1-1_all.deb ...
Unpacking libjs-highlight.js (9.18.5+dfsg1-1) ...
Selecting previously unselected package libnode72:armhf.
Preparing to unpack .../libnode72_12.22.12~dfsg-1~deb11u1_armhf.deb ...
Unpacking libnode72:armhf (12.22.12~dfsg-1~deb11u1) ...
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_12.22.12~dfsg-1~deb11u1_armhf.deb ...
Unpacking nodejs (12.22.12~dfsg-1~deb11u1) ...
Selecting previously unselected package nodejs-doc.
Preparing to unpack .../nodejs-doc_12.22.12~dfsg-1~deb11u1_all.deb ...
Unpacking nodejs-doc (12.22.12~dfsg-1~deb11u1) ...
Setting up libc-ares2:armhf (1.17.1-1+deb11u1) ...
Setting up libnode72:armhf (12.22.12~dfsg-1~deb11u1) ...
Setting up libjs-highlight.js (9.18.5+dfsg1-1) ...
Setting up nodejs (12.22.12~dfsg-1~deb11u1) ...
update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
Setting up nodejs-doc (12.22.12~dfsg-1~deb11u1) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u5) ...
pi@homebridge:~ $ nodejs -v
v12.22.12
pi@homebridge:~ $ npm -v
8.19.2
pi@homebridge:~ $ sudo hb-config
ℹ Node.js v18.12.0 already up-to-date.

**Comment by mofitn3577** [comment]
Nothing at all works i need to get the homebridge backup and just restore this thing its a mess obviously I don't know what happened it was fine until that homebridge update tried to install but whatever happened nothing at all works now and ive followed every tutorial and I still cant do anything since npm is still convinced thjat nodejs is at vers 9.9.0 and wont work so i cant even input the commands to fix npm.

**Comment by mofitn3577** [comment]
part of the update was to update  hap-nodejs to [v0.10.4] and my homebridge is running that now but still on 1.5.0 could that be causing all this? Homebridge is running and my config file is all there its just that all my plugins are gone and i cant reinstall anything

**Comment by mofitn3577** [comment]
7684 timing reifyNode:node_modules/homebridge-roomba2/node_modules/ajv Completed in 95248ms
7685 timing reifyNode:node_modules/homebridge-smartglass/node_modules/@oclif/core Completed in 95344ms
7686 timing reifyNode:node_modules/homebridge-ring/node_modules/@peculiar/asn1-x509 Completed in 95393ms
7687 timing reifyNode:node_modules/homebridge-homey-socket-io/node_modules/engine.io-client Completed in 96059ms
7688 timing reifyNode:node_modules/homebridge-z2m/node_modules/js-sdsl Completed in 96237ms
7689 timing reifyNode:node_modules/homebridge-ring/node_modules/ajv Completed in 96167ms
7690 timing reifyNode:node_modules/find-my-iphone/node_modules/ajv Completed in 96010ms
7691 timing reifyNode:node_modules/homebridge-alexa/node_modules/ajv Completed in 96053ms
7692 timing reifyNode:node_modules/homebridge-hue/node_modules/node-forge Completed in 96183ms
7693 timing reifyNode:node_modules/homebridge-roomba2/node_modules/type Completed in 96299ms
7694 timing reifyNode:node_modules/homebridge-govee/node_modules/axios Completed in 96314ms
7695 timing reifyNode:node_modules/homebridge-myq/node_modules/js-sdsl Completed in 96536ms
7696 timing reifyNode:node_modules/homebridge-ring Completed in 96804ms
7697 timing reifyNode:node_modules/homebridge-roomba2/node_modules/es6-set/node_modules/type Completed in 96836ms
7698 timing reifyNode:node_modules/homebridge-roomba2/node_modules/ext/node_modules/type Completed in 96852ms
7699 timing reifyNode:node_modules/homebridge-ring/node_modules/tsyringe Completed in 97488ms
7700 timing reifyNode:node_modules/homebridge-smartglass/node_modules/xbox-webapi Completed in 97991ms
7701 timing reifyNode:node_modules/homebridge-button-platform/node_modules/validator Completed in 97822ms
7702 timing reifyNode:node_modules/homebridge-ring/node_modules/protobufjs Completed in 98010ms
7703 timing reifyNode:node_modules/homebridge-huejay/node_modules/huejay Completed in 98517ms
7704 timing reifyNode:node_modules/homebridge-ring/node_modules/binary-data Completed in 98873ms
7705 timing reifyNode:node_modules/homebridge-ring/node_modules/@types/node Completed in 99775ms
7706 timing reifyNode:node_modules/homebridge-roomba2/node_modules/es5-ext Completed in 104663ms
7707 timing reifyNode:node_modules/homebridge-plugin-govee/node_modules/usb Completed in 106490ms
7708 timing reifyNode:node_modules/homebridge-govee/node_modules/usb Completed in 106435ms
7709 timing reifyNode:node_modules/homebridge-huejay/node_modules/moment Completed in 109642ms
7710 timing reifyNode:node_modules/homebridge-ecobee-away/node_modules/moment Completed in 109848ms
7711 timing reifyNode:node_modules/homebridge-ring/node_modules/werift Completed in 110400ms
7712 timing reifyNode:node_modules/homebridge-smartglass/node_modules/lodash Completed in 112315ms
7713 timing reifyNode:node_modules/homebridge-roomba2/node_modules/lodash Completed in 112354ms
7714 timing reifyNode:node_modules/homebridge-button-platform/node_modules/lodash Completed in 112558ms
7715 timing reifyNode:node_modules/homebridge-ring/node_modules/lodash Completed in 112718ms
7716 timing reifyNode:node_modules/homebridge-alexa/node_modules/lodash Completed in 112584ms
7717 timing reifyNode:node_modules/homebridge-hue/node_modules/es-abstract Completed in 114663ms
7718 timing reifyNode:node_modules/homebridge-harmony/node_modules/es-abstract Completed in 114651ms
7719 timing reifyNode:node_modules/homebridge-button-platform/node_modules/es-abstract Completed in 114632ms
7720 timing reifyNode:node_modules/homebridge-alexa/node_modules/es-abstract Completed in 114615ms
7721 timing reifyNode:node_modules/homebridge-myq/node_modules/es-abstract Completed in 114717ms
7722 timing reifyNode:node_modules/homebridge-ring/node_modules/rxjs Completed in 127966ms
7723 timing reifyNode:node_modules/homebridge-blink-for-home/node_modules/rxjs Completed in 127954ms
7724 timing reifyNode:node_modules/homebridge-z2m Completed in 129592ms
7725 timing reifyNode:node_modules/homebridge-plugin-govee/node_modules/typescript Completed in 140000ms
7726 timing reifyNode:node_modules/homebridge-hue/node_modules/googleapis Completed in 164946ms
7727 timing reifyNode:node_modules/homebridge-ring/node_modules/date-fns Completed in 190422ms
7728 timing reifyNode:node_modules/homebridge-plugin-govee/node_modules/govee-bt-client Completed in 351417ms
7729 timing reify:unpack Completed in 351540ms
7730 timing reify:rollback:createSparse Completed in 37528ms
7731 timing reify:rollback:retireShallow Completed in 7ms
7732 timing command:install Completed in 462154ms
7733 verbose stack Error: process terminated
7733 verbose stack     at /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:199:39
7733 verbose stack     at process.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:53:5)
7733 verbose stack     at process.emit (node:events:525:35)
7734 verbose cwd /var/lib/homebridge
7735 verbose Linux 5.15.61-v7l+
7736 verbose node v18.12.0
7737 verbose npm  v8.19.2
7738 error process terminated
7739 error signal SIGTERM
7740 verbose exit 1
7741 timing npm Completed in 462658ms
7742 verbose unfinished npm timer reify 1666849395772
7743 verbose code 1
7744 error A complete log of this run can be found in:
7744 error     /home/pi/.npm/_logs/2022-10-27T05_43_15_273Z-debug-0.log

This is the end of the log it goes through the whole install and then just stops idk what this means

**Comment by mofitn3577** [comment]
> em eng’r at a small company IT fell into my lap and did ok. Built and ran Linux and NT servers, setup plant wide LAN, started company website and email server, etc. Then got on local town marketing committee so web/email/social media became a part time job. But I never really kept up so am quite a bit behind the curve now.

Gotcha! Any idea about my situation? I am at a loss nobody else responded with any input and I have tried every single thing that is supposed to resolve this and hit a wall. I dont know what else to do.

**Comment by cheme75** [comment]
> > em eng’r at a small company IT fell into my lap and did ok. Built and ran Linux and NT servers, setup plant wide LAN, started company website and email server, etc. Then got on local town marketing committee so web/email/social media became a part time job. But I never really kept up so am quite a bit behind the curve now.
> 
> Gotcha! Any idea about my situation? I am at a loss nobody else responded with any input and I have tried every single thing that is supposed to resolve this and hit a wall. I dont know what else to do.

Got no clue. I loaded it on an old win7 netbook that I dumped win and loaded lubuntu 18.x to make it somewhat useful again - only thing I got are 2 wyze plugs and 2 wyze bulbs. Only automation is sunset to bedtime for the bulbs/lamps. I don’t need any in HomeKit but it’s fun to fiddle around - sort of looking to potential for adding stuff in the future. After setup, it’s just run pretty well. I haven’t updated yet - I may hold off if these problems appear more widespread.

**Comment by mofitn3577** [comment]
Haha 4 devices that keeps it simple. I have a lot. the install log that
fails right at the end is like 18,000 pages long haha

**Comment by donavanbecker** [comment]
Okay I am locking and closing this issue. @mofitn3577 please open a separate issue as you still haven't given us specific info about your setup to be able to better help you out.
