### ISSUE TITLE
New Homekit Architecture Support (Introduced in iOS 16.2 beta)

### ISSUE THREAD

**Issue by KJTamas** [homebridge/homebridge#3250]
### Current Situation

Hi,
It's basically a question. Apple announced new Homekit architecture after ios (ipad) 16 (maybe 16.2). Homebridge is one of the biggest developments in the Homekit environment, and I really like it.
Does the new Homekit architecture affect the Homebridge application, or does everything continue as before?

br,
Tamás

### Proposed Change

I don't know, if it should be change.

**Comment by Apollon77** [comment]
Do you have any links to such announcements?

**Comment by Ricky-Garcia1110** [comment]
I have entered precisely to see if there was any information about this, since yesterday I also read the news of the new architecture of the app, I will be attentive to this topic

**Comment by Apollon77** [comment]
> I also read the news of the new architecture of the app

Ok again, what did you read? Is there a link? Screenshot?

It is known that the "next Home app" should also support Matter as pürotocol I assume ... but more I do not know personally, thats why I was interested in what exactly you read

**Comment by KJTamas** [comment]
Hi,

E.g. here: https://9to5mac.com/2022/10/25/ios-16-2-new-architecture-home-app/
As mentioned, if I upgrade to 16.2 and upgrade to the new home architecture (optional), the older devices will no longer be able to access the home. All devices must be on version 16.2. I don't know how Homebridge works (only a little), but I just hope it continues to work. (16.2 beta released)

**Comment by KJTamas** [comment]
![image](https://user-images.githubusercontent.com/20149128/197992281-48eb05c3-82b2-44df-8d90-7f52f1045e04.png)

**Comment by KJTamas** [comment]
If only the Home app would be affected by the change, why would it affect the operation of other devices?

**Comment by donavanbecker** [comment]
That warning is for iOS/iPadOS/tvOS/macOS devices not "HomeKit" devices.

**Comment by KJTamas** [comment]
As I mentioned above, if I upgrade to a new architecture, the older devices will not be able to access the Home screen. IMHO this means something is changing that older tools (below 16.1) can't handle.

**Comment by ebaauw** [comment]
Homebridge, like any other HomeKit accessory exposes itself to the HomeKit runtime over the HomeKit Accessory Protocol.  Introducing breaking changes to that protocol (other than blocking uncertified accessories) would not only impact Homebridge, but also every other (native) HomeKit accessory.  I doubt they will want to require firmware updates to all existing accessories to cope with such a change.

Note that HomeKit apps talk to the HomeKit runtime using the HomeKit framework, a different protocol from HAP.  The framework tends to be updated with each (major or minor) iOS version, but mostly adding features rather than breaking changes.  The Home app uses the HomeKit framework, but also has some undocumented way to talk to the HomeKit runtime (notably for TV accessories, notifications, and other features not available to other HomeKit apps).  In addition, it talks Airplay2 to speakers.

I think/hope the new HomeKit architecture has to do mostly with the HomeKit runtime, how it syncs over iCloud with it peers on other Apple devices and on the Home hubs, and maybe/hopefully how it deals with bridged accessories.  Currently there is a limit on the size of the HomeKit configuration, above which the syncing comes to a grinding hold.  I’m hoping that the improved stability, especially for larger homes with many accessories will address this.

**Comment by Apollon77** [comment]
I also hope that it is about the "Home Apps internal datastructures" (which would also be in line with "all systems needs to be updated to same 16.2 else do not work). This would mean it is irrelevant

**Comment by donavanbecker** [comment]
I will be upgrading mine once public beta comes out and I will report back.

**Comment by grzegorz914** [comment]
I have convert my Home to new architecture 16.2 also updated HomePod mini , iPad and iPhone to 16.2 and all working as before. Homebridge is not affected and working OK.

**Comment by jspiro** [comment]
@grzegorz914 Thanks for the report! Do you know if:
1) It's downgrade-able?
2) Do older iOS devices/OSes still work or do ALL need to be upgraded to interact with the beta? (i.e., will family members not participating in the betas be impacted)

**Comment by grzegorz914** [comment]
1. Downgrade is not possible.
2. Devices with iOS <= 16.1  will not work.

**Comment by CooperCGN** [comment]
Here is an article explaining what’s changing with the new architecture.

https://www.homekithelper.net/tips/ios-16-matter-thread-new-architecture

**Comment by ebaauw** [comment]
Bummer, so it only works when you have a home hub.

**Comment by drheck** [comment]
> I have convert my Home to new architecture 16.2 also updated HomePod mini , iPad and iPhone to 16.2 and all working as before. Homebridge is not affected and working OK.

grzegorz914:
Are the automation problems 
https://forum.smartapfel.de/forum/thread/10533-ios-16-zeitgesteuerte-automation-funktionieren-nicht/?pageNo=1 
in IOS 16.2 still existing?
Thank you.

**Comment by pelu89** [comment]
Does anyone know if the new home architecture affects the usage of a homepod that is still on 16.1. ? I have three homepods mini on 16.2 but cannot update to the beta on my original homepod.

**Comment by Apollon77** [comment]
When you see the official wording then as soon as you upgraded one device all "non 16.2" will be incompatible... but reality? ;-)

**Comment by pelu89** [comment]
> When you see the official wording then as soon as you upgraded one device all "non 16.2" will be incompatible... but reality? ;-)

Yeah that was what I thought. I have everything on 16.2 but can not update my original HomePod....was just wondering whether I use the ability to use it after I upgraded my home. Anyone here who tried this?

**Comment by pelu89** [comment]
I am on the public beta, es far as I know Apple only issues Betas to the HomePod minis right?
Am 17. Nov. 2022, 15:30 +0100 schrieb Donavan Becker ***@***.***>:

**Comment by jonasman** [comment]
@ebaauw that's not correct, i have some accessories outside of BT range, and when my iPhone gets close to them they go from No response to the actual state. So The hub is still only required when using remote access. I think the article shared is incorrect in saying that the state comes only from the hub.

**Comment by baschte** [comment]
since iOS 16.2 is public now i'm very interested how homebridge will handle the Apple Home upgrade.

**Comment by pelu89** [comment]
Worked like a charm, did not notice many changes. Cameras react a little faster but as far as the first impression goes, that's it.

**Comment by baschte** [comment]
@pelu89 
wow that sounds great! 😃

**Comment by pelu89** [comment]
I had this problem only on my Apple Watch before I updated the watch to the latest watchOS Version. I've got a wall mounted iPad that took a while to display anything in the home app, but since then it just works. Are all devices showing as "not responding" or just homebridge devices?

**Comment by kevinwestby** [comment]
I have two native Homekti devices and they appear to be back "on" now....they were previously showing the same No Response.  Everything else is via Homebridge and is still showing no response :-(

**Comment by pelu89** [comment]
might sound stupid but have you rebooted your homebridge? everything is working fine on my end

**Comment by kevinwestby** [comment]
Yeah, I am going to reboot everything (firewall, apple tv, etc) to see if I can get things back :-).  Will let you know how it goes

**Comment by kevinwestby** [comment]
SOOOOO relieved :-)......after rebooting the firewall, AppleTV, Homebridge docker and my Hubitat hub, all my devices are now back and functioning again.

**Comment by pelu89** [comment]
The universal solution: turning it off and back on again ^^

**Comment by pelu89** [comment]
👍🏼
Am 14. Dez. 2022, 16:22 +0100 schrieb kevinwestby ***@***.***>:

**Comment by remibou78** [comment]
Hi there !
Please could you confirm Homebridge is supported in IOS16.2 with the new architecture Matter ? Behind Homebridge I've a CC2531 to connect zigbee accessories. Thanks per advance !

**Comment by pelu89** [comment]
Well, I am not a homebridge developer or something, but why shouldn't it? All the other bridges also work without an update with iOS 16.2 (Hue, IKEA, ...), I think the interplay of devices using the new "architecture" only affects apples own devices. They heave to be updated in order to operate you Home (using HomeKit), all your "client devices" (bridges, lights, thermostats etc.) should keep working as they were.

**Comment by KJTamas** [comment]
Hi, yes, Homebridge working well with new Home architecture.i ’m using many zigbee, z-wave (!!) devices throught Homebridge, and everything working well.2022. dec. 17. dátummal, 14:45 időpontban remibou78 ***@***.***> írta:﻿
Hi there !
Please could you confirm Homebridge is supported in IOS16.2 with the new architecture Matter ? Behind Homebridge I've a CC2531 to connect zigbee accessories. Thanks per advance !

**Comment by thrangster** [comment]
For me, updating has cause some issues with the SimpliSafe plug in - mainly cameras are reporting as privacy shutter enabled (it’s not for all three conditions in the SS app), or i am seeing a No Response error in Home and any iOS or Mac OS device - opening the camera in Home doesn’t show a stream either 

Ring cameras via the plug in seem ok 

The new architecture reintroduced some major issues with original HomePods and Apple TVs, a bit that was nasty about two years ago and fixed - the Default Audio (“Home Theater”) option from ATV to original HP no longer works - only temporary Airplay connections and that is flaky - five Apple TVs with single and stereo pair HP’s

Also has reintroduced the Siri request failure to play music - the HP responds, but then “sorry there was a problem connecting to Apple Music”

You can push a stream from you phone usually to get around this, but I am finding if you set the associated AppleTv to use the HP as a temporary audio output it seems to interfere with this - eventually you bash things enough and it works again until it doesn’t…

**Comment by mcicak** [comment]
Is there any update regarding this issue? Is this working for the rest of you?

For me, nothing is working on my iOS 16.2 devices (I have accidentally adopted the new architecture).

I'm running homebridge with v2.0.0-beta.0 version (I tried with v1.6.0 too).

When I scan the QR code with my 16.2 iPhone, it gets stuck on "Connecting to Bridge" state and then after a few minutes results in failure.

It is working correctly though on my iOS 14 device.

**Comment by Apollon77** [comment]
I think the "new Architecture" is a topic for later  ... when I read newspapers right then new users can not activate that at all because removed by Apple because of many issues

**Comment by mcicak** [comment]
Thanks @Apollon77, so then I'm stuck until it gets resolved (one way or another) :)

**Comment by JurgenLB** [comment]
Switching to Ciao Advertiser. That solve the problem in other installations with homebridge 1.6.0
