### ISSUE TITLE
How to inform HB/NodeJS about new SSL/TLS cert?

### ISSUE THREAD

**Issue by HolgerAusB** [homebridge/homebridge#3252]
### Current Situation

I configured HB with SSL/TLS via config (not reverse proxy). I am generating/renewing the certs (wildcard domain) with certbot on a different maschine and push the new cert by scipt-hook automatically to my RaspberryPi where Homebridge is running. So certbot on server1 is AUTOMATICALLY renewing the cert every ~60 days and copies it to the Raspi. That works very good, so far.

But Homebrdige does not notice, that there is a new cert in /etc/letsencrypt/... even a restart of Homebridge does not help. When checking the cert by browser or [uptime-kuma](https://github.com/louislam/uptime-kuma), HB/Node delivers the old one. Meanwhile I am rebooting the complete RaspberryPi, after this, the new cert is in use. But I was wondering if there is a more elegant way to force HB or NodeJS to reload the cert?

### Logs

```markdown
-
```

### Configuration

```json
"platforms": [
   {
      "name": "Config",
      "port": 9876,
      "auth": "xxx",
      "theme": "auto",
      "tempUnits": "c",
      "lang": "auto",
      "ssl": {
      "key": "/etc/letsencrypt/live/example.com/privkey.pem",
      "cert": "/etc/letsencrypt/live/example.com/fullchain.pem"
      },
      "platform": "config"
   },
```

### Environment

- OS: Debian Bullseye /RapberryPi 4
- Homebridge: 1.5.1
- Node: 16.18.0
- npm: 8.19.2

### Process Supervisor

systemd

### Additional Context

hb-service is also available. `service mode = yes`

**Comment by NorthernMan54** [comment]
@HolgerAusB The Homebridge UI is this project here - https://github.com/oznu/homebridge-config-ui-x , can you close this and raise it there ?

**Comment by HolgerAusB** [comment]
sorry, moved to [homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x/issues/1425)
