### ISSUE TITLE
Change/show child bridge port in UI

### ISSUE THREAD

**Issue by MiOrt** [homebridge/homebridge#3253]
### Current Situation

HB running on Synology in Docker.

Was experimenting with child bridge (unifi protect plugin) since I read about it in the wiki. Setup was easy, but could not connect with iPhone after scanning QR-code. Then realised by checking the config that the child bridge uses a different port that was most probably blocked by Synology firewall. I opened that port TCP and voila... worked.

### Proposed Change

When enabling a child bridge by the slider one should be able to enter the desired port for that bridge in the UI. UI should show port and warn user to open this port on firewall if one is set up.

### Additional Context

Not sure if opening the port TCP is enough or if UDP is also necessary... maybe clarify this in the respective UI tab.

**Comment by NorthernMan54** [comment]
@MiOrt Great recommendation enhancement, can you raise this against https://github.com/oznu/homebridge-config-ui-x, which is the UI and not here, which is the main homebridge codebase.

PS The Homebridge port is TCP
