### ISSUE TITLE
I can’t open HomeBridge config UI web

### ISSUE THREAD

**Issue by sdgrs546547Q** [homebridge/homebridge#3262]
### Analysis

When I open http://<xx.xx.xx.xx>:8581 , the browser returns:
“This site can’t be reached,  refused to connect.”
Also, when I execute:
sudo hb-service start
it says this: 
ℹ Restarting Homebridge Service
ℹ Restarting Homebridge Service...
Running in chroot, ignoring request.
✔ Homebridge Restarted.

This bug issue was described and it was found a fix to this (https://github.com/homebridge/homebridge/issues/2581#issue-620742807) , but i don’t understand the fix, that says “ hb-service will not work there. It needs a running instance of systemd which you're chroot does not have. You can start homebridge manually.” The problem is that I don’t know how to start hombridge manually. The user that post this bug on the first time, says that this fix solve his problem, but i don’t really understand the fix. Thanks

### Expected Behavior

Start homebridge without the chroot problem and enter to the website UI of HomeBridge

### Steps To Reproduce

1. Install Linux Deploy
2. Install Ubuntu
3. Install HomeBridge with the instructions of your website
4. Execute sudo hb-service start
5. This error appears “ Running in chroot, ignoring request.”

### Logs

```markdown
Don’t have
```

### Configuration

```json
Don’t have any config
```

### Environment

- OS: Ubuntu 16.0.4 in Linux Deploy
- Software:
- Node:
- npm:

### Process Supervisor

other (Explain in `Additional Context`)

**Comment by BenKitesurfs** [comment]
I am having the same problem.  I just downloaded the pre-configured Homebridge Raspberry Pi image from the home bridge.io website.  I added ssh and WPA supplicant to my boot directory.  When I boot the Pi it connects to my network, and I can SSH into it using the pi/raspberry credentials.  When I type the ip address in my browser it brings me to the wifi setup screen, but no networks are present.  If I type the host name.local it takes me to the same screen.  If I type http://homebridge.local:8581 the page never loads.

I tried running sudo hb-service restart from the command line, but it just hangs up on Restarting Homebridge indefinitely.
