### ISSUE TITLE
Change display format of Setup Code to reflect iOS 16 format: NNNN-NNNN

### ISSUE THREAD

**Issue by jsiegenthaler** [homebridge/homebridge#3266]
### Analysis

In previous iOS versions, the Setup Code was shown in the Home app as NNN-NN-NNN eg 123-45-678
From iOS 16, the Setup Code is displayed in the Home app as NNNN-NNNN eg 1234-5678

In fact, you can enter much longer codes. The longest displayed code is 21 digits, and is shown as:
1234-5678-9012-3456-789-01

### Expected Behavior

For consistency, the displayed Homebridge Setup code should be displayed in the same format as is shown in the iOS Home app

### Steps To Reproduce

Observe the Setup code in Homebridge
Add any new accessory in the Home app
Manually enter the Setup Code in the Home app
Observe that the displayed formatting of the Setup Code in the Home app is different to the displayed formatting in Homebridge 

### Logs

```markdown
n/a
```

### Configuration

```json
n/s
```

### Environment

Homebridge 1.5.1
iOS 16.1.1

### Process Supervisor

hb-service

**Comment by jsiegenthaler** [comment]
Bump. This should be easy to implement.

**Comment by rasterize-art** [comment]
facing the same issue

**Comment by jsiegenthaler** [comment]
bump (to make this unstale)
