### ISSUE TITLE
When will there be an update on Node 18

### ISSUE THREAD

**Issue by tuxnetDE** [homebridge/homebridge#3268]
### Current Situation

When will there be an update on Node 18* ?

synology :
https://archive.synology.com/download/Package/Node.js_v18/18.12.0-0005

### Proposed Change

When will there be an update on Node 18* ?

synology :
https://archive.synology.com/download/Package/Node.js_v18/18.12.0-0005

**Comment by ebaauw** [comment]
You’ll have to ask Synology, see https://github.com/oznu/homebridge-syno-spk/issues/105.
