### ISSUE TITLE
Homebridge Terminal won't accept my admin password

### ISSUE THREAD

**Issue by AlexWalker47** [homebridge/homebridge#3276]
### Current Situation

I'm trying to run ps4-waker through the terminal interface within Homebridge on my Synology DSM7 native install. I'm asked to input the admin password to give temporary root access, yet the password is not recognized. I know it's the correct synology admin password. I've also tried the default password as well as the Homebridge account password. No luck. Any tips? Thanks in advance

### Logs

```markdown
homebridge@NAS1234:/volume1/homebridge $ ps4-waker
No credentials; Use the PS4 Second Screen App and try to connect to "PS4-Waker"
Root permissions required to start PS4 Dummy
Attempting to request root permissions now (we will relinquish them as soon as possible):
  sudo /volume1/@appstore/homebridge/app/bin/node /var/packages/homebridge/target/app/bin/ps4-waker --user-id 108668 -c /var/packages/homebridge/home/.ps4-wake.credentials.json

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password: 
Sorry, try again.
Password:
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 893B",
        "username": "0E:13:FB:2C:89:3B",
        "port": 51363,
        "pin": "949-08-674",
        "advertiser": "ciao"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "devices": [
                {
                    "name": "Living Room TV",
                    "ip": "192.168.1.245",
                    "mac": "A0:6F:AA:3A:E2:92",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "none",
                    "channelControl": false,
                    "screenControl": false
                }
            ],
            "_bridge": {
                "username": "0E:08:22:18:50:28",
                "port": 55552
            },
            "platform": "webostv"
        }
    ]
}
```

### Environment

- OS: Synology DS7
- Software: Homebridge v1.6
- Node: v16.16.0
- npm: 8.11.0

### Process Supervisor

not applicable

**Comment by AlexWalker47** [comment]
Thanks for the reply but I have already accounted for that

**Comment by Stevenlgts** [comment]
I'm having this same issue. I just updated my RPi to 64bit from 32bit OS. Everything was running smoothly other than I was unable to update the node and Ring plugin. The update went smoothly since I restored it from a backup file. Everything is up to date. The Ring plugin works but my RPi plugin gives me the following error. 
[02/01/2026, 11:17:20] [RPi] warning: 192.168.1.167: 192.168.1.167:8888: cannot connect: ECONNREFUSED
Any attempt to diagnose it in terminal results in a password for homebridge being requested. I type the very password that I logged into Homebridge and it rejects it. I typed past passwords with no luck. Any thoughts?

**Comment by NorthernMan54** [comment]
The terminal would use Linux passwords, while the Homebridge UI uses its own separate passwords.

You mentioned you recently upgraded the OS, which package did you install?  Are these the passwords your looking for

https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Connect-Via-SSH

**Comment by Stevenlgts** [comment]
Thank you for your reply. It is the Homebridge password.

<img width="968" height="384" alt="Image" src="https://github.com/user-attachments/assets/5b56e061-2816-4017-b4b0-d24abeddd2d4" />

**Comment by NorthernMan54** [comment]
What package did you install?  Raspbian image or ??

Are you having this issue ?  https://github.com/homebridge/homebridge-raspbian-image/pull/178
