### ISSUE TITLE
Update docker compose instructions

### ISSUE THREAD

**Issue by andrewgabler** [homebridge/homebridge#3282]
### Analysis

Docker compose has been updated and now the documentation for installing here is out of date

### Expected Behavior

docker-compose up -d 

should start homebridge on docker
instead it should now be 

docker compose up -d

### Steps To Reproduce

install docker compose and attempt to start homebridge

### Logs

```markdown
none
```

### Configuration

```json
none
```

### Environment

- OS:
- Software:
- Node:
- npm:
debian

### Process Supervisor

Docker (Mention image name in `Additional Context`)

**Comment by drunkrhin0** [comment]
Bumping: This documentation still hasn't been updated

**Comment by NorthernMan54** [comment]
Which page are you referring to?  If its the wiki, you should be able to edit it
