### ISSUE TITLE
Unable to install Homebridge due to error "libc6 (>= 2.28) but 2.24-11+deb9u4 is to be installed"

### ISSUE THREAD

**Issue by jakub-a** [homebridge/homebridge#3287]
### Current Situation

Following the instructions I am getting stuck at

`sudo apt-get install homebridge`

because I'm getting this error:

```
The following packages have unmet dependencies:
 homebridge : PreDepends: libc6 (>= 2.28) but 2.24-11+deb9u4 is to be installed
E: Unable to correct problems, you have held broken packages.
```

For libc6 that's what I am getting:

```
libc6:
  Installed: 2.24-11+deb9u4
  Candidate: 2.24-11+deb9u4
```

I have been running Homebridge for years now on my Raspberry Pi. It all broke when I tried to install an older version of the ui-x plugin in hopes it would run with node v10 as it's the last supported on armv6. Soon after I found out about experimental builds of node. But after installing it I am unable to install Homebridge again.
Thanks for any help on this

### Logs

```markdown
n/a
```

### Configuration

```json
n/a
```

### Environment

- Raspbian GNU/Linux 9.13 (stretch)
- Homebridge
- Node:18.12.1
- npm:8.19.2

### Process Supervisor

not applicable

**Comment by Knusbert** [comment]
same problem here with the comparable error message (only in German ;-) )
# Environment
* Ubuntu 18.04.6 LTS
* libc current: 2.27-3ubuntu1.6 to be installed: 2.27-3ubuntu1.6

**Comment by sethhall** [comment]
It looks like you're running Debian 9 which fell out of support last July. I think Knusbert is right. It's time to upgrade.

**Comment by jakub-a** [comment]
Thank you!
I tried upgrading to Buster (RaspberyPi) but ran into some Java problems related to the armv6 architecture not being supported. 
wondering if I should upgrade my RP Zero to the newest version 2.

**Comment by kaushik853** [comment]
Hi,
How did you solve this issue

**Comment by martenmatrix** [comment]
Assuming you are using a Raspberry Pi to run Homekit:

You'll have to update your Raspberry OS from Buster to Bullseye:
1. `sudo nano /etc/apt/sources.list`
2. Change `buster` to `bullseye`
3. `sudo apt update`
4. `sudo apt install gcc-9-base`
5. `sudo apt remove libc6-dev`
6. `sudo apt-get remove libgcc-8-dev`
7. `sudo apt full-upgrade`
8. `sudo apt auto-remove`
9. `sudo reboot`

Thats the steps I did until it worked, however maybe running `sudo apt-get remove libgcc-8-dev` is enough. Make sure that you **don't** need to type "Yes, do as I say!"!
