### ISSUE TITLE
Poll Failure on Fibaro Flood Sensor

### ISSUE THREAD

**Issue by cbonomo** [homebridge/homebridge#3290]
### Current Situation

I transitioned from a Hoobs instance of Homekit to having the software running on a Mac server.  I am getting the message "Poll Failure on Fibaro Flood Sensor" every few seconds on the console.  I have a couple of Fibaro Flood sensors in my home.  Does anyone know what I need to do to stop this message from coming up?

### Logs

```markdown
na
```

### Configuration

```json
I cannot find the config.json on my mac
```

### Environment

OS: Monterey 12.4
Software: Homebridge 1.6.0
Node: 18.12.1
npm: 8.19.2

### Process Supervisor

hb-service

### Additional Context

na

**Comment by JurgenLB** [comment]
homebridge is normally on a hidden folder in your home directory;
so
`ls .homebridge
nano .homebridge/config.json`

**Comment by cbonomo** [comment]
thanks.  i looked at the config.json file.  there isnt any reference to this device or any sensors.  Do you have any idea of why I am getting the polling error?

**Comment by JurgenLB** [comment]
but Fibaro is in the config file?
at your status page of homebridge-ui you can see your Storage Path and your config.json path.

So maybe there is some reference to the sensor in Fibaro-api but Homebridge can not communicate with the sensor is my best gamble

I do not have Fibaro, so no experience there
