### ISSUE TITLE
Thermostat Service Type Optional Characteristics

### ISSUE THREAD

**Issue by mitch7391** [homebridge/homebridge#3292]
### Current Situation

Hi, I maintain [homebridge-cmd4-advantageair](https://github.com/mitch7391/homebridge-cmd4-AdvantageAir) which helps brings a multi-zone ducted air conditioning system into HomeKit through Homebridge. Currently users can set the mode (off/cool/heat/auto) and temperature from a master thermostat and all the zones around the house will have temperature sensors (for some users) and dampers that open and close based on the feedback of the sensors temperature reading. 

Currently to keep things simple I have the master thermostat blanket set the same temperature across all zones. However, in the manufacturer's app, they can set an individual temperature for zone (mode has to stay the same across all zones). It has come to my attention recently that the Home Assistant integration for Advantage Air is using thermostats for each zone instead of temperature sensors, but have removed the characteristics `CurrentHeatingCoolingState` and `TargetHeatingCoolingState` to show a thermostat that only reads and writes temperature; this is the perfect solution for my plugin.

### Proposed Change

I have tried to work out a solution for this but have realised it is more than likely the Homebridge API that is stopping me from achieving it in the GUI. I think if the [Homebridge API](https://developers.homebridge.io/#/service/Thermostat) let me have `CurrentHeatingCoolingState` and `TargetHeatingCoolingState` as optional characteristics instead of required, then I would be able to achieve what I am after. It would also open up this more custom thermostat for other developers as well if they so need it.

### Additional Context

Screenshot provided to me by a user who had tried the Home Assistant integration which shows the thermostat service type without `CurrentHeatingCoolingState` and `TargetHeatingCoolingState`.

![image](https://user-images.githubusercontent.com/40288237/208644467-576e6f00-d1ae-4382-a48e-f2a749526d9c.png)

**Comment by ebaauw** [comment]
>  the Homebridge API that is stopping me 

No it’s not.  You could simply create your own service, re-using the UUID of the standard _Thermostat_ service and leaving out the mode characteristics.

> I think if the [Homebridge API](https://developers.homebridge.io/#/service/Thermostat) let me have CurrentHeatingCoolingState and TargetHeatingCoolingState as optional characteristics instead of required, then I would be able to achieve what I am after.

I fear not.  To my knowledge, these characteristics are mandatory, and HomeKit might ban I the Homebridge bridge for non-compliance.  There’s no real harm in trying, though; simply change the `username` (mac address value) in config.json when this happens, and HomeKit will treat Homebridge as a new accessory.

**Comment by mitch7391** [comment]
> No it’s not. You could simply create your own service, re-using the UUID of the standard Thermostat service and leaving out the mode characteristics.

Hmm I was not aware of this and will take a look into it; thanks for the tip.

> I fear not. To my knowledge, these characteristics are mandatory, and HomeKit might ban I the Homebridge bridge for non-compliance. There’s no real harm in trying, though; simply change the username (mac address value) in config.json when this happens, and HomeKit will treat Homebridge as a new accessory.

I am not sure I agree that Apple would take such a stance and ban Homebridge over this, considering the fact Homebridge is allowed to run due to them turning a blind eye towards it in the first place and allowing developers to learn. I think they have much bigger fish to fry at the moment and a lot to lose if Homebridge was to shut down…

**Comment by ebaauw** [comment]
Sorry, by “ban” I mean: HomeKit will remove the bridge accessory and refuse to pair with it.

**Comment by mitch7391** [comment]
Ahh yep, sorry I misunderstood then! Haha

**Comment by bwp91** [comment]
Hi @mitch7391 did this issue ever come to a resolution?

**Comment by mitch7391** [comment]
@bwp91 I do not believe so. I was testing the suggested solution by ebaauw a long time ago but I do not believe it would work for me, got too busy and just forgot about it…

**Comment by bwp91** [comment]
In this case, I am gonna go ahead and close this issue, since I don't consider this an _issue_ with homebridge.

> got too busy and just forgot about it…

In the future if you ever get back to this and wanna re-open this issue then please feel free!
