### ISSUE TITLE
Cannot update Node.js on your system. Synology DSM 7 does not currently support Node.js 18 or later.

### ISSUE THREAD

**Issue by Binog** [homebridge/homebridge#3301]
### Current Situation

Hey, if I try to update nodejs to 18. I get the error:
"Cannot update Node.js on your system. Synology DSM 7 does not currently support Node.js 18 or later."

although there is a nodejs_v18 in Synology update-center

I am asking, cause some modules say they need it,..

Anything I could do?

Thx Jimmy

### Proposed Change

use sinology's v18 from package center!?

**Comment by Tulpe84** [comment]
Same Problem. Update node.js to V18 is not possible. Although node.js 18 can now be installed independently on DSM 7.

**Comment by Manuel2023** [comment]
Same...

**Comment by chriho135** [comment]
+1 need this as well, my Nuki bridge plugin does not reliably work anymore.. the ringer is delayed a lot bc Ive updated home bridge but cannot update the plugin as it needs node.js 18

**Comment by alexindigo** [comment]
Same here

```
$ sudo hb-service update-node
Password: 
ℹ Updating Node.js from v16.16.0 to v18.13.0...
✖ Cannot update Node.js on your system. Synology DSM 7 does not currently support Node.js 18 or later.

$ node -v
v18.12.0
```

**Comment by lukenukemmp3** [comment]
Same problem. Installing the Node 18 package did not help. The warning is still present and the update not possible.

**Comment by Ohmnitude** [comment]
same problem

**Comment by alexindigo** [comment]
I "solved" it by installing Homebridge aa docker container, so far working great.
And migration was pretty straightforward, I did backup in the old one, and then restore in the new one, right on the login page first time I opened it.

**Comment by Ohmnitude** [comment]
Mines installed on an older synology 214play model and doesn’t support docker. Node 16 is supported until the end of 2023, hope they’ll fix this by then

**Comment by Gummibando** [comment]
The glibc version in DSM 7.1 is too old.
Should be resolved with DSM 7.2, which apparently will contain glibc 2.36.

**Comment by DannyNyce** [comment]
> The glibc version in DSM 7.1 is too old. Probably resolved with DSM 7.2, which apparently will contain glibc 2.36.

Did anyone tried DSM 7.2 BETA to solve this issue?

**Comment by Gummibando** [comment]
Chiming in again :)

I'm assuming the "Cannot update Node.js on your system" issues mentioned here are all related to Oznu's Homebridge Synology SPK package. Please correct me if I'm wrong.

The Homebridge SPK contains its own, bundled _node_ binary (located at `/var/packages/homebridge/target/app/bin/node`) that is – for lack of a better term – "unrelated" to the Node packages from DSMs Package Center.

My understanding is that the package still uses resources provided by the DSM "host". DSM 7.1 is built against glibc 2.26 at the highest (some Synology ARM CPU arch's are built against various even older glibc versions). But, Node v18 requires at least glibc 2.28.

Not sure if this is helpful for the unreliable Nuki plugin mentioned above, but it is possible to install the most recent Node v17 version (17.9.1) in the Homebridge SPK via the built-in terminal: `hb-service update-node 17`.

My assumption is that this _should_ be resolved with DSM 7.2, which is built against glibc 2.36 (which – as far as I can see – is now true for all Synology CPU arch's except two ARM variants).

In the interim, as noted above, switching to "dockerized" homebridge (which is usually a matter of backing up and the config from the SPK and restoring it to the dockerized version) will resolve the issue.

**Comment by tarek86salmi** [comment]
Ds214play not supported with 7.2 couldn’t download the beta

**Comment by alockbox** [comment]
it is possible to install the most recent Node v17 version (17.9.1) in the Homebridge SPK via the built-in terminal: `hb-service update-node 17`

THANK YOU! This was the fix for me. The Linux instructions say to run sudo hb-service update-node. I think this automatically looks for the latest version if you don't specify a version (18?). 

Since my installed plugin having issues (and most plugins so far) only need 16.9, I was able to run hb-service update-node 16z this updated from 16.4 to 16.9.

**Comment by ezajkul** [comment]
> it is possible to install the most recent Node v17 version (17.9.1) in the Homebridge SPK via the built-in terminal: `hb-service update-node 17`
> 
> THANK YOU! This was the fix for me. The Linux instructions say to run sudo hb-service update-node. I think this automatically looks for the latest version if you don't specify a version (18?).
> 
> Since my installed plugin having issues (and most plugins so far) only need 16.9, I was able to run hb-service update-node 16z this updated from 16.4 to 16.9.

Thank you, this works 👆

**Comment by Fearomoon** [comment]
After upgrade to DSM 7.2 still not possible to upgrade to node.js 18 :-(

**Comment by TroyG-Aus** [comment]
I was able to upgrade to 17.9.1 with the `hb-service update-node 17` command. I've also done a `hb-service rebuild --all`.

Now I'm getting this error quite regularly....

> [5/4/2023, 5:06:54 PM] [Homebridge UI] [homebridge-config-ui-x] Failed to check registry.npmjs.org for updates: "timeout of 10000ms exceeded" - see https://homebridge.io/w/JJSz6 for help.

Any thoughts? Anyone else?

**Comment by skmzwanke** [comment]
Oznu homebridge docker installed on Synology DSM 7.2  I am unable to update node js to 18. same error DSM 7 does not currently support node js 18 or later. Please update. Thank you for your support

**Comment by jkenth119** [comment]
Thank you so much; this was really driving me mad! I had updated a number of plugins and then annoyingly my swithcnot and ring plugins become unreliable.  I found out I needed to update my node.  Eventually I was able to go from node 16.16, to v17.9.1  !

My steps were
1. manually update to DSM 7.2   - https://www.synology.com/en-uk/support/download/DS1621+?version=7.1#system
2. ssh into my synology nas, allow SSH on the control panel.  I followed these  instructions:  https://kb.synology.com/en-id/DSM/tutorial/How_to_login_to_DSM_with_root_permission_via_SSH_Telnet 
3. once I'm logged into NAS, by entering admin account password, I then sued the following command
4.  sudo hb-service update-node 17
5. voila, it made me enter my admin password again and then updated the node.js!

**Comment by chriho135** [comment]
I also still have issue to install node.js 18… 17 is no problem but my Nuki Plug-in update requires 18.16.0 min. Version. I thought with DSM 7.2 this would be possible? Please support

**Comment by markbellus** [comment]
Guys, I'm facing an issue after SSH-d into the NAS and then trying to 'sudo hb-service update-node'. 
I'm getting the following reply: 
'command not found'

What could be the problem? What am I doing wrong?

**Comment by jkenth119** [comment]
did ssh cofirm that you were root for NAS? also try
"sudo hb-service update-node 17"  ie include 17

**Comment by enrogue** [comment]
Hi all,

The solution is below and it works! 
 
1. Install Node.js 18 from Synology Package Center 
2. SSH into the Synology shell and run the following commands (just copy paste the second command - don’t change anything!)
   a. sudo su
   b. sed -i.bak 's/\/var\/packages\/homebridge\/target\/app\/bin/\/var\/packages\/Node.js_v18\/target\/usr\/local\/bin/g' /var/packages/homebridge/target/app/source.sh
3. Go to Synology Package Center and stop and then run the Homebridge package.

That’s it - Done! HomeBridge on node.js v18.12

EnR

**Comment by nisus91** [comment]
I got the same error as mentioned above.
   **sed: -e expression https://github.com/homebridge/homebridge/issues/1, char 9: unknown option to `s'**
I made the following changes
   **sed -i.bak 's|/var/packages/homebridge/target/app/bin|/var/packages/Node.js_v18/target/usr/local/bin,|g' /var/packages/homebridge/target/app/source.sh**
Error is disappeared.
but, node version on homebridge is v16.3

**Comment by nisus91** [comment]
> I got the same error as mentioned above.
> **sed: -e expression #1, char 9: unknown option to `s'**
> I made the following changes
> **sed -i.bak 's|/var/packages/homebridge/target/app/bin|/var/packages/Node.js_v18/target/usr/local/bin,|g' /var/packages/homebridge/target/app/source.sh**
> Error is disappeared.
> but, node version on homebridge is still v16.3

**Comment by chrisdojnik** [comment]
> I got the same error as mentioned above. I made the following changes **sed -i.bak 's|/var/packages/homebridge/target/app/bin|/var/packages/Node.js_v18/target/usr/local/bin,|g' /var/packages/homebridge/target/app/source.sh** Error is disappeared. but, node version on homebridge is still v16.3

It seems the idea behind it is to change the reference in source.sh from older Node.js to a newer version file in the Synology Node.js v18 package. 

I was able to manually change that reference using WinSCP (which required adjusting permission for source.sh), but unfortunately, after that change, Homebridge would not start properly. I'm on DSM 7.1.1 (I don't see 7.2 available for my DS1513+).

At least updating Node.js to 17.9.1 using the above-mentioned method has stopped plugin updates from complaining about the outdated version of Node. 

Hopefully, this will get fixed at some point.

**Comment by chrisdojnik** [comment]
> I got the same error as mentioned above. I made the following changes **sed -i.bak 's|/var/packages/homebridge/target/app/bin|/var/packages/Node.js_v18/target/usr/local/bin,|g' /var/packages/homebridge/target/app/source.sh** Error is disappeared. but, node version on homebridge is still v16.3

It seems the idea behind it is to change the reference in source.sh from older Node.js to a newer version file in the Synology Node.js v18 package.

I was able to manually change that reference using WinSCP (which required adjusting permission for source.sh), but unfortunately, after that change, Homebridge would not start properly. I'm on DSM 7.1.1 (I don't see 7.2 available for my DS1513+).

At least updating Node.js to 17.9.1 using the above-mentioned method has stopped plugin updates from complaining about the outdated version of Node.

Hopefully, this will get fixed at some point.

**Comment by jkenth119** [comment]
Hi, my method works fine.   PS to update to 7.2, I had to manually download from https://www.synology.com/en-uk/support/download
 and then update manually from control panel.

**Comment by chrisdojnik** [comment]
> Hi, my method works fine on dsm 7.2. PS to update to 7.2, I had to manually download from https://www.synology.com/en-uk/support/download and then update manually from control panel.
> 
> Edit - i looked on the download centre page on Synology, and your model doesn't show the 7.2 updates like it did for me. I tried my initial method on DSM 7.1 and the node.js update wouldn't work.
> 

Thanks. I'll try to perform the manual update to 7.2. If this does not work, perhaps it is time to upgrade to a newer NAS,

**Comment by bmounteer** [comment]
> I got the same error as mentioned above. I made the following changes **sed -i.bak 's|/var/packages/homebridge/target/app/bin|/var/packages/Node.js_v18/target/usr/local/bin,|g' /var/packages/homebridge/target/app/source.sh** Error is disappeared. but, node version on homebridge is still v16.3

This completely broke my Homebridge installation. Now I can't access the homebridge UI at all. Says that the address is unreachable.

**Comment by chrisdojnik** [comment]
> > I got the same error as mentioned above. I made the following changes **sed -i.bak 's|/var/packages/homebridge/target/app/bin|/var/packages/Node.js_v18/target/usr/local/bin,|g' /var/packages/homebridge/target/app/source.sh** Error is disappeared. but, node version on homebridge is still v16.3
> 
> This completely broke my Homebridge installation. Now I can't access the homebridge UI at all. Says that the address is unreachable.

If you are not on DSM 7.2 this may not work, as it did not work for me on DSM 7.1.1.

I think you need to revert back one line of the code in source.sh file ( located in /var/packages/homebridge/target/app/ )
from: /var/packages/Node.js_v18/target/usr/local/bin 
back to: /var/packages/homebridge/target/app/bin

The safest way to make that adjustment may be with WinSCP.

**Comment by MitchRoz3** [comment]
> I got the same error as mentioned above.
> I made the following changes
> **sed -i.bak 's|/var/packages/homebridge/target/app/bin|/var/packages/Node.js_v18/target/usr/local/bin,|g' /var/packages/homebridge/target/app/source.sh**
> Error is disappeared.
> but, node version on homebridge is still v16.3



The problem is the comma at the end of the string "/var/packages/Node.js_v18/target/usr/local/bin,". That trailing command messes up the concatenation of /bin to /node, making it ..../bin,/node and that PATH does not exist.
As soon as I fixed this, my DSM 7.1.1 Update 5 run Node 18.12.0 and Homebridge without any issues.

**Comment by chrisdojnik** [comment]
> 

Thanks! This worked for me as well on DSM 7.1.1 update 5.

**Comment by swittmann** [comment]
Hmm I did this and homebridge now says node.js is version 18.5 but my synology is now missing my user called homebridge and it wont allow me to add it back saying that either that user already exists or the name homebridge is reserved

**Comment by connor-johnson** [comment]
@chrisdojnik @MitchRoz3 So what is the correct command to run?

sed -i.bak 's|/var/packages/homebridge/target/app/bin|/var/packages/Node.js_v18/target/usr/local/bin/g' /var/packages/homebridge/target/app/source.sh
?

**Comment by chrisdojnik** [comment]
> 

`sudo su`

followed by

`sed -i.bak 's|/var/packages/homebridge/target/app/bin|/var/packages/Node.js_v18/target/usr/local/bin|g' /var/packages/homebridge/target/app/source.sh`

worked for me.

**Comment by henkied** [comment]
Thanks this works for me too!! but how can i update the node "hb-service update-node" doesn't work anymore it says Note: This is a restricted shell, sudo cannot be used here.

**Comment by MitchRoz3** [comment]
> Thanks this works for me too!! but how can i update the node "hb-service update-node" doesn't work anymore it says Note: This is a restricted shell, sudo cannot be used here.

Since you are now sharing the Node from DSM, you don't need to update Homebridge separately. In DSM, go to Package Central, select All Packages, search for Node, and install Node from here. I only have Node v18 installed. If you have DSM Node set to auto-update, you won't even need to do this.

**Comment by 6MH89F3j** [comment]
@MitchRoz3 Do you by chance know how to tell which version of Node is already installed on DSM? And how do you set it to auto update? Do you just mean to download node 18 from package center and then set it to auto-update? Or is there a simpler way?

**Comment by MitchRoz3** [comment]
> @MitchRoz3 Do you by chance know how to tell which version of Node is already installed on DSM? And how do you set it to auto update? Do you just mean to download node 18 from package center and then set it to auto-update? Or is there a simpler way?

I think there are 2 ways. Since Homebridge is not sharing/using the DSM Node install, open the terminal of Homebridge and issue 'node --version'. Mine returns v18.12.0. The second way is in DSM, go to Package Center, Select 'Installed' on the left, and then in the search bar type in node and press enter. Click on the 'Installed' Node tile, and on the next screen it displays the installed version, for me, v18.12.0-0005. Hope that helps.

**Comment by allkindsofralph** [comment]
Just for more clarity and confirmation and what worked for me. I am on DSM 7.1 Update 6. I installed Node 18 via DSM

Run these commands (thanks [chrisdojnik](https://github.com/chrisdojnik))

`sudo su`

`sed -i.bak 's|/var/packages/homebridge/target/app/bin|/var/packages/Node.js_v18/target/usr/local/bin|g' /var/packages/homebridge/target/app/source.sh`


If you followed nisus91 and homebridge wont run anymore, run this command to fix the error due to a typo

`sed -i.bak 's|/var/packages/Node.js_v18/target/usr/local/bin,|/var/packages/Node.js_v18/target/usr/local/bin|g' /var/packages/homebridge/target/app/source.sh`


Good Luck all! Hope it works for you all too.

**Comment by dppeak** [comment]
This is working for me.  Thanks!

**Comment by iamluvinlife** [comment]
> Just for more clarity and confirmation and what worked for me. I am on DSM 7.1 Update 6. I installed Node 18 via DSM
> 
> Run these commands (thanks [chrisdojnik](https://github.com/chrisdojnik))
> 
> `sudo su`
> 
> `sed -i.bak 's|/var/packages/homebridge/target/app/bin|/var/packages/Node.js_v18/target/usr/local/bin|g' /var/packages/homebridge/target/app/source.sh`
> 
> If you followed nisus91 and homebridge wont run anymore, run this command to fix the error due to a typo
> 
> `sed -i.bak 's|/var/packages/Node.js_v18/target/usr/local/bin,|/var/packages/Node.js_v18/target/usr/local/bin|g' /var/packages/homebridge/target/app/source.sh`
> 
> Good Luck all! Hope it works for you all too.

this just worked for me too. thanks!

**Comment by iamluvinlife** [comment]
quick question, how do we continue to get updates? I just read this and am a little concerned? https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js#what-to-avoid 

_What To Avoid
It is important to update Node.js using the same method you originally used to install it, or using hb-service update-node.

Do not update Node.js using instructions you found on some random site on the internet.
Avoid nvm or n - these are great tools for developers, but require additional configuration when running Homebridge as a service user.
Failing to adhere to these guidelines will likely result in you having multiple copies of Node.js installed which will cause many strange problems (if you have done this, see how to fix it on [Linux](https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-Linux) and [macOS](https://github.com/homebridge/homebridge/wiki/How-To-Fix-Node.js-Install-Issues-On-macOS))._

**Comment by ekristen** [comment]
so I have node 18 installed via the DSM, but homebridge is still using node 16, how do I get it to use the DSM installed version?

**Comment by RufusJSquirrel** [comment]
The new DSM Homebridge package (3.0.17) requires node 18 to be installed and it still won't update to 18 on DSM 7.2.

**Comment by ebaauw** [comment]
Please follow these steps:
- Install the Node.js-v18 package provided by Synology;
- Install or upgrade to Homebridge package v3.0.17;
- Homebridge should now use the Synology provided NodeJS v18.15.0;
- To upgrade to the latest NodeJS, wait for Synology to provide an updated version of their Node.js-v18 package.  
`hb-service update-node` doesn't work, and even if it would, it wouldn't change anything, as Homebridge would still use the NodeJS version from the Node.JS-v18 package.

On **DSM 7.2 only** you might use the latest NodeJS version (still) bundled with the Homebridge package.  I wouldn't recommend this, unless you're proficient with the command line and understand what you're doing:
- Install Node.js-v18 package provided by Synology;
- Install or upgrade to Homebridge package v3.0.17;
- Homebridge should now use the Synology provided NodeJS v18.15.0;
- Edit `source.sh` (in `/var/packages/homebridge/target/app`) to comment out the check whether the Node.JS-v18 package has been installed and the `then` part:
  ```
  # Use Synology supplied NodeJS v18 - https://github.com/homebridge/homebridge-syno-spk/issues/124
  # if [ -f /var/packages/Node.js_v18/target/usr/local/bin/node ]; then
  #  NODE_BIN_PATH="/var/packages/Node.js_v18/target/usr/local/bin:$NODE_BIN_PATH"
  #  export HB_SERVICE_NODE_EXEC_PATH="/var/packages/Node.js_v18/target/usr/local/bin/node"
  # else
    export HB_SERVICE_NODE_EXEC_PATH="/var/packages/homebridge/target/app/bin/node"
  # fi
  ```
  Note that you cannot uninstall the Node.js-v18 package, without also uninstalling the Homebridge package.
- Stop and restart the Homebridge package;
- Homebridge should now use the Homebridge-bundled NodeJS v18.17.0;
- `hb-service update-node` still doesn't work.  Wait for Homebridge Config UI X to release a new version of `hb-service`, that allows you to upgrade NodeJS to a newer version, once that becomes available.

**Comment by ivokik** [comment]
I am on DSM 7.2.2, using Node JS 20 with Homebridge UI v4.69.0 with Homebridge v1.8.5. So at this point there is a NODE update v20.9.0 → v20.18.2. ( see screenshots ) , but I am not able to update the node via the official method ( hb-service update-node ) . I m getting the same error : "Cannot update Node.js on your system. Non-standard installation path detected" 
So, where Do i go form here? 
DO  I just wait until Synology updates its own Node , or do I need to take a different approach? 

See screenshots: 

![Image](https://github.com/user-attachments/assets/4ed03bf1-5ebb-430a-a2d7-482c5974d6da)
![Image](https://github.com/user-attachments/assets/d422982d-2a03-4a7c-b0d7-a5fe1b6e96f6)

**Comment by maaxdc** [comment]
I get the same error.  I assume we need to wait for the Homebridge package to get an update from Synology.  Please lmk how you solve this.
