### ISSUE TITLE
Fresh install of v1.6.0 (HAP v0.11.0) (Homebridge E3DB) - Restore broken

### ISSUE THREAD

**Issue by nextgenoperations** [homebridge/homebridge#3305]
### Analysis

Using a fresh install of Ubuntu 22.04 LTS server and node.js v18.13.0, i installed the Homebridge as per the instructions on this github space.

the installation was fine. I pointed my web browser at the server using port 8581 and I get the Welcome to Homebridge, Get started page.

I click on the restore from backup link. I am prompted to select my backup file, I select my local tgz backup that I took from another server.

I then just get the spinning wheel saying uploading for like 10-12 mins, then I just back to the upload button status with no notifications or anything.

No errors in the syslog or the hombridge.log file, so I am not sure where to look.

A quick google and I see others with the same issue (https://www.reddit.com/r/homebridge/comments/106mee0/cannot_restore_backup_to_homebridge/) , but I couldn't find it here so thought I would report it.

Thanks

### Expected Behavior

Restore to work

### Steps To Reproduce

Fresh install of Ubuntu server 22.04

### Logs

```markdown
No logs
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge E3DB",
        "username": "0E:41:D4:49:E3:DB",
        "port": 51188,
        "pin": "445-27-964",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

### Environment

- OS: Ubuntu 22.04
- Software: Homebridge 1.6.0
- Node: 18.13.0
- npm: 8.5.1

### Process Supervisor

hb-service

**Comment by aatifk** [comment]
I have the same issue with pretty much the same configuration, except that my Ubuntu new installation is 22.10

**Comment by RacknerGER** [comment]
it's the same for me too.  only the homebridge runs on VMwares.  the restore does not run without error messages

**Comment by dbanky** [comment]
I had the same issue earlier today. I managed to solve it as I rolled back the Homebridge UI ([homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x)) to version 4.50.0. After that, I could restore the configuration.

**Comment by yllwdg** [comment]
> I had the same issue earlier today. I managed to solve it as I rolled back the Homebridge UI ([homebridge-config-ui-x](https://github.com/oznu/homebridge-config-ui-x)) to version 4.50.0 under the "Plugins" menu. After that, I could restore the configuration.

Downgrading the UI also worked for me. Thanks for the workaround @dbanky!

**Comment by philiphayward** [comment]
Same experience. Restore broken under 4.50.2

**Comment by intrepidsilence** [comment]
Same issue for me. Restore also worked with 4.50.1, so the issue is limited to 4.50.2.

**Comment by jotala** [comment]
Same

**Comment by shanemcw** [comment]
I also see this behavior on
UI version 4.50.2

Ubuntu Jammy Jellyfish (22.04.2 LTS)
1.6.0 homebridge
v18.13.0 nodejs

/var/lib/homebridge
/var/lib/homebridge/config.json
/var/lib/homebridge/node_modules

**Comment by jotala** [comment]
Bump.

**Comment by Kydix** [comment]
Same for me on a fresh install of TrueNas...

**Comment by bostrt** [comment]
I also ran into this issue and rolling back to 4.50.0 helps.

**Comment by NorthernMan54** [comment]
This issue has been resolved with the
