### ISSUE TITLE
HTTP Headers

### ISSUE THREAD

**Issue by mrwestside12** [homebridge/homebridge#3307]
### Current Situation

I am using ubuntu with Homebridge. I use Cloudflared tunnel and I have set up HTTP headers inside of the tunnel. They work but I can't find the file in Homebridge to remove the headers in the config file. 

### Logs

```markdown
I don't have one
```

### Configuration

```json
config.json
```

### Environment

-OS: Ubuntu
- Software: Homebridge up to date
- Node: Up to date
- npm: Up to date 

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
The homebridge website is a different package that runs over top of homebridge, that may be why you can’t find it.

Please open this against homebridge-config-ui-x

**Comment by mrwestside12** [comment]
> The homebridge website is a different package that runs over top of homebridge, that may be why you can’t find it.
> 
> Please open this against homebridge-config-ui-x

Trust me I have looked there. I see no headers already in place.
