### ISSUE TITLE
Minor typo in Wiki

### ISSUE THREAD

**Issue by jsiegenthaler** [homebridge/homebridge#3311]
### Analysis

The Wiki page https://github.com/homebridge/homebridge/wiki/Remote-Access contains a minor typo.
The sentence "To enable remote access to your Homebridge connected accessories you need to setup a device act as a home hub." is missing a word. The correct sentence is shown below.

Incorrect: "To enable remote access to your Homebridge connected accessories you need to setup a device act as a home hub. "
Correct "To enable remote access to your Homebridge connected accessories you need to setup a device **to** act as a home hub. "

Also, the title "Set up your HomePod, Apple TV or iPad as a home hub" is no longer correct as the Apple iPad is no longer available for use as a home hub since iOS 16.2 new architecture. The title should be updated to "Set up your HomePod or Apple TV as a home hub"

### Expected Behavior

The sentence must be in correct English, the title must be correct

### Steps To Reproduce

1. Open Wiki at page https://github.com/homebridge/homebridge/wiki/Remote-Access
2. Read the first sentence
3. Read the Title "Set up your HomePod, Apple TV or iPad as a home hub"

### Logs

```markdown
n/a
```

### Configuration

```json
n/a
```

### Environment

n/a

### Process Supervisor

not applicable

### Additional Context

n/a

**Comment by NorthernMan54** [comment]
Tks for reporting this, I went and fixed the grammar issue in the first sentence.

In regards to to using the iPad as a Home Hub, if you look at the apple support page referred to in our wiki page, it indicates the current status of the iPad, which is supported, but not with the new architecture. And for the new architecture, as your probably aware, Apple has stopped the rollout of this feature.  Once Apple officially drops support for the iPad as a home hub, we will update our materials.
