### ISSUE TITLE
IOS 16.2 Speaker in HomeKit results in "Not Supported" even if publishedExternally

### ISSUE THREAD

**Issue by ztalbot2000** [homebridge/homebridge#3313]
### Analysis

The example independent platform plugin at: https://github.com/homebridge/homebridge-examples/tree/master/independent-platform-example-typescript does work when it is changed from a Switch that is published externally to a Speaker. HomeKit will complain the accessory is, "Not supported".
I seen others talk about the same issue with a SmartSpeaker, but this is just a Speaker.

### Expected Behavior

Like an externallyPublished Switch a Speaker should also be recognized by the Home App

### Steps To Reproduce

Use the independent-platform-plugin example, change the accessory from a Switch to a Speaker. (Code attached)
I removed all bridges/accessories from the Home App. Restarted the Home app.
Deleted /var/lib/homebridge/accessories and
/var/lib/homebridge/persist and rebooted my server.
Added the Bridge and then added the externally published Speaker. See images below

### Logs

```markdown
Logs are attached as an image.
```

### Configuration

```json
"platforms": [
        {
            "platform": "ExampleIndependentPlatform",
            "name": "homebridge-independent-platform-example"
        }
]
```

### Environment

- OS: iPadOS Version 16.2
- Model Name; iPad Pro (12.9-inch)(3rd generation)
- Software: Home
- Node: v16.13.1
- npm: npm@8.8.0 /usr/local/lib/node_modules/npm
uname -a: Linux MyHost 5.10.63-v8+ #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021 aarch64 GNU/Linux
homebridge -V
1.6.0

### Process Supervisor

hb-service

### Additional Context

Attached are my simple modifications to make the independent-platform-plugin a Speaker instead of a Switch as well as screenshots along the way.
[independent-platform.ts.txt](https://github.com/homebridge/homebridge/files/10551329/independent-platform.ts.txt)

![homebridge-ui](https://user-images.githubusercontent.com/6558047/215892929-e327fa1a-dd56-4f2d-a515-7c8c16a9ad4d.png)
![HomeExternal](https://user-images.githubusercontent.com/6558047/215892935-44c63f55-b87c-45d2-b74a-6d281c7f8554.png)
![HomeUnsupported](https://user-images.githubusercontent.com/6558047/215892948-3b9c6914-4771-48ca-81a2-c796fd83c8dc.png)

**Comment by ebaauw** [comment]
You’ll have to file this bug report with Apple.  Home only supports a _Speaker_ service as part of a video doorbell accessory.  You will be able to see it in other HomeKit apps, like Eve.

**Comment by ztalbot2000** [comment]
Hi,

   Apple fixing anything just because it used to work before would probably
happen when whales are seen flying to the moon. Thanks for your quick reply
and all your help. Much appreciated.

John
