### ISSUE TITLE
Truenas Scale mDNS settings solved 

### ISSUE THREAD

**Issue by jiameelorh** [homebridge/homebridge#3322]
### Current Situation

After setting up home bridge on TrueNas Scale I encountered issues getting my homekit to talk to my home bridge. 

I am currently using TrueNAS-SCALE-22.12.0

### Proposed Change

After playing around with the settings I have managed to fix it by changing the "advertiser" to "ciao". 
Could you include this step in the installation document?

**Comment by Supereg** [comment]
These options are discussed in the [mDNS Options](https://github.com/homebridge/homebridge/wiki/mDNS-Options) Wiki Page
