### ISSUE TITLE
IPv6 npmjs.org connection failure

### ISSUE THREAD

**Issue by DerekSeaman** [homebridge/homebridge#3325]
### Current Situation

When running Homebridge on a RPi 4, either "bare metal" or in Docker, the services are unable to connect to the npm registry:

npm ERR! request to https://registry.npmjs.org/homebridge failed, reason: connect EHOSTUNREACH 2606:4700::6810:1623:443

On a fresh Docker install, this results in the HB service not being installed, but the HB UI does come up. I freshly imaged a RPi4, installed Docker, installed Portainer, then created the Stack. My local LAN is IPv6 enabled, and my firewall is a Firewalla Gold Plus. 

### Logs

```markdown
verbose stack FetchError: request to https://registry.npmjs.org/homebridge failed, reason: connect EHOSTUNREACH 2606:4700::6810:1623:443
40 verbose stack     at ClientRequest.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
40 verbose stack     at ClientRequest.emit (node:events:513:28)
40 verbose stack     at TLSSocket.socketErrorListener (node:_http_client:496:9)
40 verbose stack     at TLSSocket.emit (node:events:525:35)
40 verbose stack     at emitErrorNT (node:internal/streams/destroy:151:8)
40 verbose stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
40 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
41 verbose cwd /homebridge
42 verbose Linux 5.15.84-v8+
43 verbose node v18.13.0
44 verbose npm  v8.19.3
45 error code EHOSTUNREACH
46 error syscall connect
47 error errno EHOSTUNREACH
48 error request to https://registry.npmjs.org/homebridge failed, reason: connect EHOSTUNREACH 2606:4700::6810:1623:443
49 verbose exit 1
```

### Configuration

```json
N/A as HB isn't up and running yet
```

### Environment

Docker/Portainer image: oznu/homebridge:latest

- OS: Raspberry Pi OS Lite v5.15
- Software: Homebridge
- Node: (in Docker image)
- npm: (in Docker image)

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

Portainer Stack:

version: '3'
services:
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - homebridge:/homebridge
volumes:
  homebridge:

**Comment by DerekSeaman** [comment]
hb@homebridge:/home $ ping registry.npmjs.org
PING registry.npmjs.org(2606:4700::6810:1b23 (2606:4700::6810:1b23)) 56 data bytes
From 2600:1700:2ec0:dc40::1 (2600:1700:2ec0:dc40::1) icmp_seq=1 Destination unreachable: Address unreachable
From 2600:1700:2ec0:dc40::1 (2600:1700:2ec0:dc40::1) icmp_seq=2 Destination unreachable: Address unreachable

**Comment by DerekSeaman** [comment]
Looks like the root cause is a Firewalla/IPv6 issue, unrelated to HomeBridge software. Troubleshooting further.

**Comment by HunterDG** [comment]
Ever find a solution?
