### ISSUE TITLE
Integration with Influx DB for reporting purposes

### ISSUE THREAD

**Issue by azurecrash** [homebridge/homebridge#3327]
### Current Situation

I would love to report on data flowing out of some of the devices currently configured in  Homebridge. This week I investigated piping Nest data, for example, into Grafana via Influxdb. While I was successful - I deployed Home Assistant which has a native integration to Influx - I think it would have been have been even more useful to have this integration directly from within Homebridge so that the rest of my sensor data was available. 

### Proposed Change

As a result, I propose building an integration with InfluxDB (or any other TSDB) in order to facilitate sensor reporting.

### Additional Context

Thank you for everything you already do! I LOVE this solution!

**Comment by NorthernMan54** [comment]
While this is a great feature enhancement, I don’t see it being tackled as part of homebridge but as a side project/module.  Which should be do-able today without coding via node-red and homebridge-automation.  You would need to integrate node-red to influx, but am thinking existing patterns already exist for this

**Comment by macjl** [comment]
You can try this plugin. It’s not Influxdb, but Prometheus. But also compatible with Grafana. 

https://github.com/seanson/homebridge-prometheus-exporter

**Comment by azurecrash** [comment]
Thanks!
