### ISSUE TITLE
Unable to control accessory from iPhone

### ISSUE THREAD

**Issue by jeff-at-theranch** [homebridge/homebridge#3328]
### Current Situation

I have an accessory installed:
homebridge-garagedoor-command v0.8.4 by apexad - (https://www.npmjs.com/~apexad)

And it works as expected from the accessory tab via the browser (from a computer on the lan) AND I get the notifications on my phone, however I am unable to control the plugin from the iPhone, as it reports as "No response".

I have tried running the accessory as part of Homebridge and as a child process but neither work, if I remove and reinstall the bridge on the iPhone, it initially reports the correct status, but if I try to use it it will timeout and report "This accessory is not responding"

Incidentally I did have home bridge and this plugin working on a raspberry pi (that died a while ago) so it is either something to do with the version of home bridge 1.6.0 or the MacOS.

I did read some comments about downgrading to version 1.5.1 but I don't see anyway of getting that version.

Any insights much appreciated.

### Logs

```markdown
homebridge log:
Setup Payload:
X-HM://0023RR2XFQH17
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ -> I deleted this <-
    └────────────┘     
                       
[3/3/2023, 12:03:55 PM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge) is running on port 51892.
[3/3/2023, 12:03:56 PM] [Garage Door] Launched child bridge with PID 5212
[3/3/2023, 12:03:56 PM] Registering accessory 'homebridge-garagedoor-command.GarageCommand'
[3/3/2023, 12:03:56 PM] [Garage Door] Loaded homebridge-garagedoor-command v0.8.4 child bridge successfully
[3/3/2023, 12:03:56 PM] Loaded 0 cached accessories from cachedAccessories.0EE18FDC5B4E.
[3/3/2023, 12:03:56 PM] Publishing bridge accessory (name: Garage Door, publishInfo: {
  username: '0E:E1:8F:DC:5B:4E',
  port: 37659,
  pincode: '***-**-***',
  category: 2,
  bind: [ 'en0', [length]: 1 ],
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'bonjour-hap'
}).
[3/3/2023, 12:03:56 PM] Homebridge v1.6.0 (HAP v0.11.0) (Garage Door) is running on port 37659.
[3/3/2023, 12:03:57 PM] [Garage Door] State of Garage Door is: OPENING
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:D5:5D:5E:D7:35",
        "port": 51892,
        "pin": "-> I deleted this <-",
        "advertiser": "bonjour-hap",
        "bind": [
            "en0"
        ]
    },
    "accessories": [
        {
            "name": "Garage Door",
            "open": "/Users/jeffr/Home/open.sh",
            "close": "/Users/jeffr/Home/close.sh",
            "state": "/Users/jeffr/Home/status.sh",
            "status_update_delay": 10,
            "poll_state_delay": 30,
            "log_polling": true,
            "accessory": "GarageCommand",
            "_bridge": {
                "username": "0E:E1:8F:DC:5B:4E",
                "port": 37659
            }
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ],
    "disabledPlugins": []
}
```

### Environment

- OS:
- Software:
- Node:
- npm:

MacOS 12.6.3
node -v gives: v19.7.0
npm -v gives: 9.5.0

### Process Supervisor

hb-service

### Additional Context

If I run this from the terminal:

curl 10.0.1.164:37659
{"status":-70409}%      

curl 10.0.1.164:51892
{"status":-70409}%  

Not sure if the has any bearing

**Comment by NorthernMan54** [comment]
With your setup do you have a ‘home hub’ ? And have you followed the steps here ?  https://support.apple.com/en-ca/guide/iphone/iph1d10f7f2b/ios

**Comment by jeff-at-theranch** [comment]
> With your setup do you have a ‘home hub’ ? And have you followed the steps here ? https://support.apple.com/en-ca/guide/iphone/iph1d10f7f2b/ios

I do, I have a couple AppleTV and the Accessory shows up on the iPhone. 
![IMG_E446EB26537A-1](https://user-images.githubusercontent.com/74747656/222843028-efff8e98-6fcb-47c1-94bb-bfeb839068c6.jpeg)

**Comment by NorthernMan54** [comment]
`And it works as expected from the accessory tab via the browser (from a computer on the lan) AND I get the notifications on my phone, however I am unable to control the plugin from the iPhone, as it reports as "No response".`

Can you share a log from homebridge when it reports `no response` am thinking this may be a plugin issue and not with homebridge itself.

**Comment by jeff-at-theranch** [comment]
So..

For no apparent reason it has started working, I ended up restarting pretty much everything on my network as well as my iPhone and I'm all good.  There was never anything in the logs that the iPhone was trying to reach the home hub.

I do appreciate you input, I wish I could provide a definitive I did 'x' to get it to work.

Thanks again,

j.
