### ISSUE TITLE
Docker brings up Homebridge outdated version 1.4.1 instead of 1.6.0

### ISSUE THREAD

**Issue by LordVoodoo** [homebridge/homebridge#3333]
### Current Situation

I have set up a new mini computer during last week and installed the docker image oznu/homebridge via Portainer.

I am wondering, why is the v1.4.1 of Homebridge loaded and the Web Interface offers me directly the upgrade to 1.6.0, which works fine. But as soon as I restart the container, I am back on 1.4.1. There are no older images or something like this. Is this happening for a reason?

`version: "3.3"
services:

  homebridge:
    image: oznu/homebridge:latest
    container_name: Homebridge
    network_mode: host
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=880
    volumes:
      - data_homebridge:/homebridge
      
volumes:
  data_homebridge:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/data/homebridge
    `

### Logs

```markdown
none relevant
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 9374",
        "username": "0E:E5:06:E6:93:74",
        "port": 52100,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 880,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "de",
            "platform": "config"
        }
    ]
}
```

### Environment

- OS: Debian 11
- Software: 1.4.1
- Node: 16.15.0
- npm: 8.5.5

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

oznu/homebridge:latest
oznu/homebridge:no-avahi

**Comment by kremerol** [comment]
It looks that you’ve forgot to use the docker pull feature
