### ISSUE TITLE
NAS and Homebridge server

### ISSUE THREAD

**Issue by schmittyd** [homebridge/homebridge#3341]
### Current Situation

Hello,

I'm looking at building my own NAS for content creation plus a small Homebridge server with CCTV storage. Am I best keeping the two separate or would it be fine to incorporate the two in the same server?

### Logs

```markdown
n/a
```

### Configuration

```json
n/a
```

### Environment

- OS: Ubuntu 22.04
- Software: rclone
- Node:
- npm:

### Process Supervisor

not applicable

### Additional Context

n/a

**Comment by NorthernMan54** [comment]
Homebridge is pretty light weight ( except camera plugins, due to transcoding ) so you should be fine.

**Comment by kspears** [comment]
I'm running homebridge in docker on my Synology nas and it works great
