### ISSUE TITLE
Apple Home OS 16.4 -> Homebridge issues

### ISSUE THREAD

**Issue by andrzejom** [homebridge/homebridge#3344]
### Analysis

Today I updated my Apple TV to OS 16.4. Just after the update all of my devices

- Govee H6056
- Roborock S5max
- WizLight G95
stopped working. HomeKit was stating that "Device is not responding." I did restart Homebridge/Rasp3B+ and Govee lights came back online, Roborock as well, however, WizLight was gone. Though Govee and Roborock devices were online they were not functioning properly:
- Govee light intensity can't be turned up to 100% (when setting 100% in Govee app in HB it is set to 39%). Setting light intensity has a very low impact on the actual effect (if none actually). Color settings seem to work properly (I don't use scenes). 
- Roborock was worse (I lost logs as I restarted the server several times). Roborock was pinging constantly Homebridge and back. It was killing the Raspberry so I had to shut down the plugin ([homebridge-xiaomi-roborock-vacuum v0.29.0](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum)) 
- WizLight plugin doesn't work at all. I can't detect/discover/add Smart Bulb, nor to HB or HomeKit. 

### Expected Behavior

When setting light intensity for Govee devices, they should change the intesity, however, they don't. Setting it to 40% doesn't change anything. Setting it to 20% they are turned off almost completely, after that setting them to 100% from HB doesn't have any effect (I have to go to the app to change it). Once in the app I set to 100% in HB it is set to 39%.

Roborock should limit of pings from the robot to the server, it is impossible to handle that large amount of messages.

WizLight Bulb should be discoverable. However, it is not. In the app Bulb works just fine.

### Steps To Reproduce

Updating Apple Home OS to 16.4 should definitely have some impact on the home bridge. Multiple users on discord reported issues with their devices after this. 

### Logs

```markdown
Govee:
[29/03/2023, 21:21:22] [Govee] [Andrew Lights] current colour [2300K / 435M].
[29/03/2023, 21:21:22] [Govee] [Andrew Lights] current scene [3305150108fc08fc000000000000000000000022] [op:aa].
[29/03/2023, 21:21:22] [Govee] [Gabrysia Lights] current colour [3300K / 303M].
[29/03/2023, 21:21:24] [Govee] [Andrew Lights] could not find device [############].
[29/03/2023, 21:21:24] [Govee] [Andrew Lights] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1719:13.
[29/03/2023, 21:22:10] [Homebridge UI] Changes to config.json saved.
[29/03/2023, 21:25:23] [Homebridge UI] [homebridge-govee] Terminating child process...
[29/03/2023, 21:25:23] [Homebridge UI] [homebridge-govee] Child process ended
[29/03/2023, 21:25:51] [Govee] [Andrew Lights] could not connect as Error: Unknown Connection Identifier (0x2).
[29/03/2023, 21:56:05] [Homebridge UI] [homebridge-govee] Terminating child process...
[29/03/2023, 21:56:05] [Homebridge UI] [homebridge-govee] Child process ended

Roborock: Gone :/

WizLight: 
[29/03/2023, 21:21:14] [WizSmarthome] Initializing WizSmarthome platform...
[29/03/2023, 21:21:14] [WizSmarthome] [Refresh] Pings are off
[29/03/2023, 21:21:14] Loading 1 accessories...
[29/03/2023, 21:21:14] [WizSmarthome] [Socket] Setting up socket on ############
                       
[29/03/2023, 21:21:15] [WizSmarthome] [Discovery] Sending discovery UDP broadcast to 255.255.255.255:############
```

### Configuration

```json
{
    "bridge": {
        "name": "############",
        "username": ############,
        "port": ############,
        "pin": "############",
        "advertiser": "avahi"
    },
    "accessories": [
        {
            "name": "Roborock S5 Max",
            "ip": "############",
            "token": "############",
            "serviceType": "fan",
            "waterBox": false,
            "dustBin": false,
            "dustCollection": false,
            "disableCareServices": false,
            "silent": false,
            "pause": true,
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "goTo": true,
            "goToWord": "go to coordinates",
            "goToX": 25500,
            "goToY": 25500,
            "dock": true,
            "cleanword": "cleaning",
            "roomTimeout": 0,
            "autoroom": false,
            "accessory": "XiaomiRoborockVacuum"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": ############,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Govee",
            "username": "############",
            "password": "############",
            "apiKey": "############",
            "apiWhitelist": true,
            "debug": true,
            "platform": "Govee"
        },
        {
            "devices": [
                {
                    "name": "Roborock S5 Max",
                    "ip": "############",
                    "token": "############",
                    "deviceId": "############",
                    "model": "roborock.vacuum.s5e",
                    "pollingInterval": 10,
                    "deepDebugLog": false,
                    "micloud": {
                        "username": "############",
                        "password": "############",
                        "country": "############"
                    },
                    "buzzerControl": true,
                    "ledControl": true,
                    "childLockControl": true,
                    "modeControl": true
                }
            ],
            "platform": "miot"
        },
        {
            "name": "WizSmarthome",
            "enableScenes": true,
            "lastStatus": true,
            "refreshInterval": 0,
            "platform": "WizSmarthome"
        }
    ],
    "disabledPlugins": [
        "homebridge-miot",
        "homebridge-xiaomi-roborock-vacuum"
    ]
}
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Homebridge v1.6.0 with PID: 1225: 
- Node: [v18.12.1]
- npm: 8.19.2
- homebridge-govee v8.1.0
- homebridge-xiaomi-roborock-vacuum v0.29.0
- homebridge-wiz-lan v3.2.7

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
I have been running 16.4 right thru the whole beta cycle, and have not had any issues or concerns.  But looking at your log fragment, it looks like a connectivity issue between your RPI and the various devices in your setup.  If the upgrade of your ATV was the root cause, then it would not likely show up in the logs like this.

Local Usage

iPhone --> Homebridge --> plugin --> devices

Remote Usage

iPhone --> iCloud --> ATV --> Homebridge --> plugin --> devices

If your ATV was the root cause, it is likely to show up as a remote access issue, and not in the homebridge logs as errors connecting to your devices.

The errors look like connectivity issues between your various plugins, and the individual devices/vendor backends.   Is their any issues with your local network or isp connectivity or ????

**Comment by andrzejom** [comment]
Hey, thanks for the reply. So as for the update of ATV, looking at the discord I wasn't the only one who was complaining about the issues after the release of 16.4. Some users had to remove/restart and add devices all over again in order to make them work. 

I did not see/encounter issues with the internal connectivity of my network. I'm using the most basic/traditional version of connectivity ( I believe), meaning: 

1. iPhone with HomeKit as a remote
2. ATV as a HomeHub
3. Homebridge as an external bridge to the devices
If I may ask how can I control homebridge directly from my iPhone without interaction with ATV in between? I thought that ATV was a necessary step in this communication.

**Comment by IonutMindrescu** [comment]
Same issue here, almost all the devices lost connection with HB in the Home App...I blame the iOS 16.4 for this I guess. I reseted everything, I even changed the IP address of my HB but I can't add it back to Home App, it's saying "accessory already added". I can add the devices only if I'm creating child bridges for each plugin x_x

**Comment by frogstar** [comment]
Same issue here. It did start after I upgraded HomeKit to the new HomeKit architecture. Funny enough - only some plugins stop responding. Sonos and Unifi stop responding for me, while Harmony still works.
Quick reboot of home bridge fixes it for a a short time - maybe an hour or so....need to monitor.

**Comment by IonutMindrescu** [comment]
> Same issue here. It did start after I upgraded HomeKit to the new HomeKit architecture. Funny enough - only some plugins stop responding. Sonos and Unifi stop responding for me, while Harmony still works. Quick reboot of home bridge fixes it for a a short time - maybe an hour or so....need to monitor.

Quick question, are using the Smartthings plugin on HB? I managed to fix the issue by removing that outdated plugin...

**Comment by frogstar** [comment]
> Quick question, are using the Smartthings plugin on HB? I managed to fix the issue by removing that outdated plugin...

I do not use Smartthings. I tried to disable all other plugins and only leave Sonos on (which I am most concerned about) but no luck. I do not see any error in the home bridge logs either - they just stop responding. last time I measured about ~50 minutes after rebooting home bridge until they stopped responding.

**Comment by IonutMindrescu** [comment]
I think the only solution it's to reset the HB hub id from settings and try to activate plugins one by one to find the faulty one.

**Comment by frogstar** [comment]
Yesterday I remove it from HomeKit, changed the id and added it back. However - with all PlugIns active. Maybe Sonos and Unifi are both in need of an update. Harmony plugin continues to work. So maybe I need to wait for an update for this plugins then. I only have this 3 plugins installed.

**Comment by frogstar** [comment]
Maybe too early to celebrate, but changing mDNS Advertiser from Ciao to Avahi appears to have fixed it for me. Let me observe a day or two - but its stable for a couple hours so far - which is much more than I have seen in the past days.

**Comment by cheme75** [comment]
FWIW, I’ve left hb at 1.5 and have not updated the ui or the Wyze plugin. Updated all devices and tv hub to 16.4. HB is basically just setup with the default settings from my initial install. Only got 2 plugs and 2 bulbs, but seeing no problems using them in HomeKit. Maybe just my simple needs since I rarely ever change the bulb settings.

**Comment by andreasgrill** [comment]
I had the same issue. Since, I switched to Avahi the problem appears to be gone.
