### ISSUE TITLE
Restore backup stuck on uploading

### ISSUE THREAD

**Issue by sefasenturk95** [homebridge/homebridge#3346]
### Analysis

When I press restore backup it is stuck on uploading after selecting a backup. I tried this from the initial setup as well as setting up as new homebridge and then try to restore..

<img width="776" alt="Screenshot 2023-04-03 at 12 28 33" src="https://user-images.githubusercontent.com/3214653/229484441-9f53a6b4-a7c7-4f47-ba26-0d75684d6d22.png">

### Expected Behavior

To restore my backup so I can pick up where I left off

### Steps To Reproduce

1. Backup homebridge
2. Reinstall homebridge
3. Try to restore
4. And see it is stuck in uploading

### Logs

```markdown
-
```

### Configuration

```json
Default
```

### Environment

- OS: Debian GNU/Linux Bullseye (11)
- Software: 1.6.0
- Node: 18.13.0
- npm: 8.19.3

### Process Supervisor

hb-service

**Comment by pponce** [comment]
There seems to be a bug. 
For a restore to work for me I had to make sure i was using homebridge 1.5.1 and Config-UI-X 4.50.1. Otherwise it would not restore from backup.
You can downgrade both from the homebridge UI then restore from backup.

**Comment by sefasenturk95** [comment]
@pponce Only downgrading the config UI X to 4.50.1 while staying on 1.6.0 worked for me as well. Thank you!

**Comment by pponce** [comment]
Glad it worked. 
Hope they fix this soon. See lots of people having this issue. 
 I’m also having an issue with upgrading node using hb-service, after an `apt-get install homebridge`.

**Comment by Patr-ick** [comment]
Same for me, staying on Homebridge 1.6.0 but downgrading to UI-X v4.50.1 solved the backup function.

I quess they messed something up with the backup function in homebridge-config-ui-x, see Release note for 4.50.2:

Release Notes
4.50.2 (2022-11-10)
Notable Changes

**Homebridge:** 
Add systemd-resolved Advertiser to UI ([#1430](https://github.com/oznu/homebridge-config-ui-x/pull/1430))
Bug Fixes

**Backups:** 
Backups now ignore symlinks, sockets, pipes etc.

**Comment by speedingcheetah** [comment]
This been an issue for a while now. Run into it 3x now. Just had to setup HB up from near scratch (i had saved the config file) because Restore does not work. I tried downgrade the UI-X version, and restore succeed, but upon reboot, it failed to load at all. Gave a bunch of errors.

**Comment by ronaldmendoza** [comment]
+1 hitting this same symptom now. Downgrading to homebridge-config-ui-x v4.50.1 also resolved my issue

**Comment by Firemanjoe** [comment]
Was thinking of moving over from my Pi to my NAS and now I am unable to restore from my pi export. Hopefully this will be fixed or if someone can point me to how to downgrade to v4.50.1, that would be great!

**Comment by donavanbecker** [comment]
https://github.com/homebridge/homebridge-config-ui-x/issues/1457

**Comment by speedingcheetah** [comment]
> Was thinking of moving over from my Pi to my NAS and now I am unable to restore from my pi export. Hopefully this will be fixed or if someone can point me to how to downgrade to v4.50.1, that would be great!

Until this is fixed, what i did was skip restore and manually install my plugins, then copy paste the entire config file i had saved, save, reboot and all was back to normal on the HB side. Did have to remove then re-add the bridge and all accessories to Apple Home though.

**Comment by donavanbecker** [comment]
@speedingcheetah you can use an older version and wouldn't have to re-setup your bridges.

**Comment by speedingcheetah** [comment]
> @speedingcheetah you can use an older version and wouldn't have to re-setup your bridges.

As i mentioned, i tried that and it borked things. HB failed to start.

**Comment by NorthernMan54** [comment]
Steps to downgrade config-ui-x are here

https://github.com/homebridge/homebridge-config-ui-x/issues/1457#issuecomment-1534886496

**Comment by donavanbecker** [comment]
@Weidav Did you follow work around?

**Comment by Weidav** [comment]
Yes, downgrading the UI worked for me.

I switched from a RaspberryPi 3 to a Pi 4 and installed Homebridge in a Docker Container.
All the settings and plug-ins are restored, but I lost the connection to all my devices.
Is this behavior expected when switching hardware?

**Comment by RyleaStark** [comment]
Latest `homebridge-config-ui-x v4.50.3-test.1` UI resolved this issue for me.
