### ISSUE TITLE
HB  - randomly No respone in homekit app

### ISSUE THREAD

**Issue by JacekKac** [homebridge/homebridge#3351]
### Current Situation

HB running with few plugins one of them is homebridge-ewelink v10.4.0. Few sonoff devices linked, everythink is running OK but randomly homekit app gives no responding for this accessories - in the same time they are working in web panel of homebride and i can use them. After restarting homebridge devices are once again responding and working ok also in homekit app. 

Any ideas how to debug/fix this ? 

p.s. at the same time other plugins are working fine in home app

### Logs

```markdown
nothing special in the logs sonoff devices are up and running (reporting)
```

### Configuration

```json
{
            "name": "eWeLink",
            "username": "...",
            "password": "...",
            "mode": "auto",
            "debug": false,
            "language": "en",
            "ignoredHomes": "6208df3c1882c9000992d8fb",
            "platform": "eWeLink"
        },
```

### Environment

- OS: PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

- Software: [v1.6.0]
- Node:v14.21.3
- npm: 6.14.18

### Process Supervisor

systemd

**Comment by przemekgithub** [comment]
I can confirm this issue, most of my devices goes off twice a day. All zigbee2mqtt, some wifi, even my roomba. One thing i am now checking is mdns/interface configuration but have to wait if it will help. 
It started for me after upgrade to 1.6.1. Node is 18.16. 
No other changes in network in the meantime.

**Comment by lukyer** [comment]
same problem here with random homebridge plugins using child bridges .. restart of homebridge always helps. However when some accessories are stucked in Home app with NO RESPONSE, if I open homebridge UI, I can click on accessories and it works normally. So only Home <> HB is broken few times per day. Workaround - restart homebridge every few hours :(

RAM, SSD, CPU, all good.

**Comment by JacekKac** [comment]
upgrading ewelink plugin to development version resolved my problem
