### ISSUE TITLE
npm update (or install), Deletes other Plugins

### ISSUE THREAD

**Issue by arrmo** [homebridge/homebridge#3352]
### Analysis

Hi,

I have seen this a few times now, so it seems to be somewhat consistent. If I try to update npm modules (using `npm update`, in `/usr/lib/node_modules`), or manually install a plugin from GitHub (e.g. `homebridge-blink-for-home`) ... I find that other Plugins seem to get deleted (e.g. `homebridge-ring`).

Is this expected, or a known issue? Are there things I can capture to help debug? Want to help if I can.

Thanks!

### Expected Behavior

New plugin would be installed, but existing ones not deleted.

### Steps To Reproduce

Steps as above, repeated,
1. cd /usr/lib/node_modules
2. sudo npm update

### Logs

```markdown
Not sure what to capture here - but I will, NP!
```

### Configuration

```json
I don't think this is configuration related?
```

### Environment

- OS: Ubuntu 22.04
- Software: Homebridge v1.6.0
- Node: v18.16.0
- npm: 9.5.1

### Process Supervisor

systemd

**Comment by NorthernMan54** [comment]
Yeah that is pretty consistent behaviour of the npm install and update command and is will know - https://stackoverflow.com/questions/69780698/npm-removes-all-packages-at-install-or-update

When you use npm install` command, the proper location to start is from the home directory of your account and use the form `sudo npm install -g homebridge-ring`.  This will install the plugin without erasing the current directory contents.

And for `npm update` this is to be run from inside a plugin ( npm package ) directory.  ie `/usr/lib/node_modules/homebridge-ring`

**Comment by arrmo** [comment]
Thanks, appreciate it!

BTW, if you don't mind ... having issues with this (not working?). Have you seen this before?
https://github.com/oznu/homebridge-syno-spk/issues/29

Thanks again!
