### ISSUE TITLE
Ring Cameras "Stuck" in HomeKit

### ISSUE THREAD

**Issue by arrmo** [homebridge/homebridge#3360]
### Analysis

Hi,

I had some Ring cameras connected to Homebridge. I have removed them ... and the Plugin, also the cameras from the cache. They don't seem to show up now in Homebridge - looking at accessories. But, they still show up in HomeKit, and there is no option to delete them. If I look at the (Homebridge) bridge in HomeKit, the camera(s) are still there, just stuck in Updating state.

How to get them removed from HomeKit? In the past, removing devices ... they auto-removed. But it seems to not be the case for cameras?

Thanks!

### Expected Behavior

When the devices are removed from Homebridge, auto-remove from HomeKit!

### Steps To Reproduce

Steps as above ... 
1) Remove the Plugin from Homebridge (Ring)
2) Remove the cameras from the cache
3) Restart Homebridge
4) Exit, re-open HomeKit

### Logs

```markdown
Not sure what to provide here, as the device isn't in Homebridge now, but is in HomeKit?
```

### Configuration

```json
Nothing in the config file related to the removed plugin!
```

### Environment

- OS: Ubuntu 22.04.2 LTS
- Software: v1.6.0
- Node: v18.16.0
- npm: 9.5.1

### Process Supervisor

systemd

**Comment by donavanbecker** [comment]
This not a Homebridge issue, but a plug-in issue. Please open an issue on the plugin repo.

**Comment by arrmo** [comment]
NP, but ... I have no option in HomeKit (at all) to remove the "rogue" device => tie that to the Plugin? Just to understand.

Thanks!

**Comment by donavanbecker** [comment]
Is it tied to a bridge? Do you have screenshots?

**Comment by arrmo** [comment]
Only tied to Homebridge (bridge) it seems to say. A couple of pics, attached => no option to delete, only in the Homebridge bridge (but not seen from the server?). Thanks!
![IMG_1227](https://user-images.githubusercontent.com/8756384/235334537-004544b2-c753-424a-98cc-9cf9f9040ba4.PNG)
![IMG_1228](https://user-images.githubusercontent.com/8756384/235334540-7a39ca60-ab03-4ca5-acd4-0f1ea5b7607e.PNG)

**Comment by donavanbecker** [comment]
on the homebridge UI > Homebridge Settings (Under, 3 dots upper right) > Remove Single Cached Accessory (Find accessory name here and delete)

**Comment by arrmo** [comment]
Yep, had already tried that 😉. That's the screwy thing ... I don't see it there. Any way it could be "hidden" from that list?

Thanks!

**Comment by donavanbecker** [comment]
nope, you could try hiding the device Id in the ring plugin.

**Comment by arrmo** [comment]
And that makes sense, except - it's not showing up in the list of accessories ... so the Plugin isn't seeing it? It seems to be there from before ... but no option to delete it in HomeKit, and it's not visible in Homebridge?

Thanks!

**Comment by donavanbecker** [comment]
Have you tried adding it to the config?

**Comment by arrmo** [comment]
So remove the Plugin I have now, delete it all out .. re-add, see if I can delete the items then?

I can, NP - just making sure 😆 

Thanks!

**Comment by arrmo** [comment]
Hmm ... OK, removed the Plugin, manually removed all Ring related items in the cache, restarted Homebridge just to be sure => devices still in HomeKit. Arrgh 😜 

Thoughts?

Thanks!

**Comment by donavanbecker** [comment]
Did you restart once you had the plugin uninstalled?

**Comment by arrmo** [comment]
Yep! And did it again, just for good measure 😆.

Checked ... device is not in Accessories, not in Homebridge cache ... but is in HomeKit, and points at Homebridge as it's bridge (actually, homebridge.io).

Still no option to delete. It does say near the top, "There is an unconfigured button.". Not sure if that helps?

Thanks!

**Comment by donavanbecker** [comment]
Then I feel like this has to be a setup issue. Sorry.

**Comment by bwp91** [comment]
You don't have this option?

![IMG_960C692B1A92-1](https://user-images.githubusercontent.com/43026681/235381260-1fef2d1e-e70c-4afd-bc5d-6419756b86f3.jpeg)

**Comment by donavanbecker** [comment]
No his camera is a bridged one

**Comment by arrmo** [comment]
OK, something very screwy going on ... LOL. I noticed some other devices missing also, so tried to config that (different) Plugin. But I got the error, "Failed to load plugins config schema". Hun?

Thoughts?

Thanks!

**Comment by arrmo** [comment]
Arrgh - not sure why / how, but adding almost any new plugin results in the error,
```
failed to load plugins config schema
```
But all adding / removing has been done through the UI. Not sure what causes this issue?

Thanks!

**Comment by arrmo** [comment]
OK, some more digging - it seems I'm not the only person who has had this happen 😞. I tried the one recommended fix ... check in Eve - but no joy.
https://www.reddit.com/r/HomeKit/comments/efd0ps/remove_accessory_option_missing/
https://www.reddit.com/r/HomeKit/comments/u5d3gc/cant_delete_accessory_from_home_app/

The other suggestion is to remove the entire (Homebridge) bridge? I have 21 devices, don't want to set them all up again ... a lot of pain, Is there really no way to remove these rogue devices?

Thanks!

**Comment by 7AC** [comment]
This happened to me with Ring cameras. I was able to fix via the Home app: I went on the settings of the lingering camera and clicked settings. From there, there was a link to the bridge and for whatever reason the bridge was a window sensor (also stale). Deleted the stale sensor and the issue went away.
