### ISSUE TITLE
Accessories ok in HomeBridge UI and working but not appearing in Home app on iOS

### ISSUE THREAD

**Issue by mcnahum** [homebridge/homebridge#3363]
### Current Situation

I will extra simplify the situation as I'm looking if it's a known issue:

1 Rasberypi linked to 1 accessory working for at least a couple of year

The accessory is correctly display on the Accessories part of the UI and working correctly

The accessory on HomeKit stop to work, after looking why, I removed the bridge on HomeKit and put it back.
now it cannot see any accessories attached to that bridge.

### Logs

```markdown
N/A
```

### Configuration

```json
N/A
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

### Additional Context

N/A

**Comment by jefferson136** [comment]
I am also experiencing this same issue for the last few days. I can connect and control accessories via the Homebridge UI, but everything in Home app is "No Response". I do not want to have to nuke everything as I have a ton of accessories, scenes, and automations in place that would need to be rebuilt and that would take quite some time. Let me know if you find a solution!

**Comment by mcnahum** [comment]
Ok that was a child bridge ... not sure since when it's there.... added it and it's ok

**Comment by BENJAMINZSIMON** [comment]
can you explain??? I am having the issue everything on hb ui and controllable but in home app shows no response I've tried everything even starting over from scratch

**Comment by FelipemCorreia** [comment]
> I am also experiencing this same issue for the last few days. I can connect and control accessories via the Homebridge UI, but everything in Home app is "No Response". I do not want to have to nuke everything as I have a ton of accessories, scenes, and automations in place that would need to be rebuilt and that would take quite some time. Let me know if you find a solution!
> 
> Edit: I started disabling plugins and eventually got everything back and running. I think in my case the culprit was [homebridge-levoit-air-purifier](https://github.com/RaresAil/homebridge-levoit-air-purifier). Trying to work around that.

Thank you. I disabled the [homebridge-levoit-air-purifier](https://github.com/RaresAil/homebridge-levoit-air-purifier) here and everything went back to normal.
