### ISSUE TITLE
Google Nest not showing correct temp in HomeKit 

### ISSUE THREAD

**Issue by Rickskar456** [homebridge/homebridge#3366]
### Current Situation

After linking my nest to HomeBridge and linking HomeBridge to HomeKit, my home temperature has been stuck at 73 degrees when it has risen to 80+. Checking HomeBridge I get this error:
This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 32.7 exceeded maximum of 32.22222222222222. See https://homebridge.io/w/JtMGR for more info.
I have no idea what that means or what to do to fix it. 

### Logs

```markdown
[5/11/2023, 2:38:30 PM] [homebridge-google-nest-sdm] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 32.7 exceeded maximum of 32.22222222222222. See https://homebridge.io/w/JtMGR for more info.
```

### Configuration

```json
},
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "clientId": "179980024156-2m7v9qf2h2lgckhpde6ebs1iq8f6517e.apps.googleusercontent.com",
            "clientSecret": 
            "projectId": "f454ead3-7517-4446-bd56-d408091f60e3",
            "refreshToken":
            "subscriptionId": "projects/NestHomebridge/subscriptions/nesthomebridge",
            "platform": "homebridge-google-nest-sdm"
        }
    ]
}
```

### Environment

- OS: Mac OS 13.2.1 
- Software: Homebridge 1.6.1
- Node: 18.16.0
- npm: 9.5.1

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
As this issue is triggered by the google nest plugin, pls raise an issue against the plugin itself and close this.  The plugin developer will need to resolve this.
