### ISSUE TITLE
Error: EACCES: permission denied, rename 

### ISSUE THREAD

**Issue by richierockskool** [homebridge/homebridge#3369]
### Current Situation

When I try to npm install -g these errors occur

It loads the plugin 

[5/17/2023, 4:05:29 PM] Loaded plugin: homebridge-inkbird-wifi-gateway@1.0.7
[5/17/2023, 4:05:29 PM] Registering platform 'homebridge-inkbird-wifi-gateway.homebridge-inkbird-wifi-gateway'

But when I go to setting I get this ..Error... Failed to load Plugins Config Schema

### Logs

```markdown
npm ERR! code 236
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/richjagger/.npm --prefer-offline=false --prefer-online=true --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm ERR! code ENOTDIR
npm ERR! npm ERR! syscall rename
npm ERR! npm ERR! path /usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! npm ERR! dest /usr/local/lib/node_modules/.homebridge-inkbird-wifi-gateway-4ACtSijX
npm ERR! npm ERR! errno -20
npm ERR! npm ERR! ENOTDIR: not a directory, rename '/usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/usr/local/lib/node_modules/.homebridge-inkbird-wifi-gateway-4ACtSijX'
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/richjagger/.npm/_logs/2023-05-17T19_51_37_748Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richjagger/.npm/_logs/2023-05-17T19_51_29_340Z-debug-0.log
```

### Configuration

```json
{"displayName":"Homebridge Inkbird Wifi Gateway",
"name":"homebridge-inkbird-wifi-gateway",
"author":"R.Jagger",
"version":"1.0.7",
"description":"Control Inkbird BT devices through the WiFi Gateway App",
"license":"Apache-2.0",
"type":"module",
"repository":{"url":"https://github.com/richierockskool/homebridge-inkbird-wifi-gateway.git"},
"bugs":{"url":"https://github.com/richierockskool/homebridge-inkbird-wifi-gateway/issues"},
"funding":[
    {"type":"github","url":"https://github.com/sponsors/richierockskool"},
    {"type":"paypal","url":"https://www.paypal.com/paypalme/RichJagger"}],
    "engines":{"node":">=16.17.0",
    "homebridge":">=1.5"},
    "main":"src/index.js",
    "scripts":{"lint":"eslint src/**.ts --max-warnings=0",
    "watch":"npm run build && npm link && nodemon",
    "build":"rimraf ./dist && tsc",
    "prepublishOnly":"npm run lint && npm run build"},
    "keywords":
    ["homebridge-plugin",
    "bluetooth",
    "temperature",
    "sensor",
    "inkbird",
    "homebridge"],
    "devDependencies":
    {"@types/node":"^16.10.9",
    "@typescript-eslint/eslint-plugin":"^5.0.0",
    "@typescript-eslint/parser":"^5.0.0",
    "eslint":"^8.0.1",
    "homebridge":"^1.3.9",
    "nodemon":"^1.3.3",
    "rimraf":"^3.0.2",
    "ts-node":"^10.3.0",
    "typescript":"^4.4.4"},
    "dependencies":
    {"@abandonware/noble":"^1.9.2-21",
    "chokidar":"^3.5.3",
    "homebridge-inkbird-wifi-gateway":"github:richierockskool/homebridge-inkbird-wifi-gateway",
    "latest-version":"^7.0.0",
    "module-name":"^0.0.1-security",
    "my-package":"^0.0.0",
    "node-fetch":"^2.6.1"}}
```

### Environment

- OS: 12.6.5
- Software: 1.6.1
- Node: 18.16.0
- npm: 9.5.1

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Your package.json refers to itself

https://github.com/richierockskool/homebridge-inkbird-wifi-gateway/blob/1016c432266f63356968475a1e5abf24bcbcca71/package.json#L39

Pls use an editor that supports code formatting, the files in your repo etc are very very hard to read/follow

I cloned your repo, fixed the package.json and it worked.

**Comment by richierockskool** [comment]
Thank you,

Did you just delete that line?

**Comment by NorthernMan54** [comment]
npm remove homebridge-inkbird-wifi-gateway

Which cleans up the directory and package.json

**Comment by richierockskool** [comment]
It is still failing in Homebridge?

cmd: npm install -g homebridge-inkbird-wifi-gateway@1.0.9npm ERR! code 236npm ERR! git dep preparation failednpm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/richjagger/.npm --prefer-offline=false --prefer-online=true --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-runnpm ERR! npm ERR! code ENOTDIRnpm ERR! npm ERR! syscall renamenpm ERR! npm ERR! path /Users/richjagger/.npm-global/lib/node_modules/homebridge-inkbird-wifi-gatewaynpm ERR! npm ERR! dest /Users/richjagger/.npm-global/lib/node_modules/.homebridge-inkbird-wifi-gateway-tvb7A6ROnpm ERR! npm ERR! errno -20npm ERR! npm ERR! ENOTDIR: not a directory, rename '/Users/richjagger/.npm-global/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/Users/richjagger/.npm-global/lib/node_modules/.homebridge-inkbird-wifi-gateway-tvb7A6RO'

**Comment by richierockskool** [comment]
Still not loading after everything?

The error are less.

cmd: npm install -g ***@***.*** ERR! code ENOENTnpm ERR! path /usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gatewaynpm ERR! enoent ENOENT: Cannot cd into '/usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway'npm ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent

**Comment by NorthernMan54** [comment]
If you look at the error message it is still referring to homebridge-inkbird-wifi-gateway within the node_modules directory which is an issue.Maybe erase everything in homebridge-inkbird-wifi-gateway, ensure package.json is cleaned up and try to install again.On May 17, 2023, at 10:36 PM, richierockskool ***@***.***> wrote:﻿
Still not loading after everything?

The error are less.

cmd: npm install -g ***@***.*** ERR! code ENOENTnpm ERR! path /usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gatewaynpm ERR! enoent ENOENT: Cannot cd into '/usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway/node_modules/homebridge-inkbird-wifi-gateway'npm ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent

**Comment by richierockskool** [comment]
Use this command again?

npm remove homebridge-inkbird-wifi-gateway

I have used 3 times now and always the same result?

**Comment by richierockskool** [comment]
The permission errors are solved, now we are back to these errors.

npm ERR! code 190
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/richjagger/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code ENOTEMPTY
npm ERR! npm ERR! syscall rename
npm ERR! npm ERR! path /usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! npm ERR! dest /usr/local/lib/node_modules/.homebridge-inkbird-wifi-gateway-4ACtSijX
npm ERR! npm ERR! errno -66
npm ERR! npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/usr/local/lib/node_modules/.homebridge-inkbird-wifi-gateway-4ACtSijX'

Thank you for all your help so far.

Rich
