### ISSUE TITLE
Cannot update Node.js on Windows HyperV 

### ISSUE THREAD

**Issue by WoodsyLawyer** [homebridge/homebridge#3371]
### Analysis

I am currently on Homebridge UI 4.50.2. When trying to update it to the latest version I get the following popup:

 "The homebridge-config-ui-x plugin recommends running on Node.js v16.20.0 or later. You are currently running Node.js v16.14.2.

Are you sure you want to update homebridge-config-ui-x?"

However when attempting to update Node.js I am informed the latest version is incompatible. I haven't taken any steps as my current setup works and didn't want to break anything tinkering with stuff I don't understand.

### Expected Behavior

Some way of prompting the user on how to update the version of linux when attempting to update Node.js on an incompatible version. 

### Steps To Reproduce

1) Running Homebridge on Windows HyperV from the provided iso file
2) run  "sudo hb-service update-node"
3) get an error informing you can't update

### Logs

```markdown
root@homebridge-vm:/homebridge# sudo hb-service update-node
ℹ Updating Node.js from v16.14.2 to v18.16.0...
✖ Your version of Linux does not meet the GLIBC version requirements to use this tool to upgrade Node.js. Wanted: >=2.28. Installed: 2.27
```

### Configuration

```json
I'm assuming my config of my accessories are not necessary, but can provide them if needed

{
    "bridge": {
        "name": "Homebridge XXXX",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": XXXXX,
        "pin": "XXX-XX-XXX",
        "advertiser": "ciao"
    },
```

### Environment

- OS: Windows 10 HyperV ((Ubuntu GLIBC 2.27-3ubuntu1.5) 2.27)
- Software: 1.6.1
- Node: v16.14.2
- npm: 8.5.0

### Process Supervisor

hb-service

### Additional Context

I have attempted to search to make sure this isn't a duplicate issue. Isuue #3343 describes my same problem however it has been closed due to being "stale" and wanted to open this to show that this is still ongoing. In that thread the users documented them making a new Homebridge server and copying a backup file to the new one. However this discussion was after the issue was closed so I'm not sure if this is the intended solution. Apologies if I missed somewhere else where this may have been addressed.

**Comment by TheAustinG** [comment]
I'm also experiencing this issue right now. Frustrating that there isn't a simpler solution/fix for this.

**Comment by bwp91** [comment]
To update to the newest version of node 16 you should be able to use a command like:

```
sudo hb-service update-node 16
```

Nowadays, you should be looking to update to node 18 :)

**Comment by TheAustinG** [comment]
> To update to the newest version of node 16 you should be able to use a command like:
> 
> ```
> sudo hb-service update-node 16
> ```
> 
> Nowadays, you should be looking to update to node 18 :)

Correct. And I have updated to node 17 using that command. However, I am not able to update to node 18 because of the same error in the OP: 
>Your version of Linux does not meet the GLIBC version requirements to use this tool to upgrade Node.js. Wanted: >=2.28. Installed: 2.27
