### ISSUE TITLE
Homebridge does not start again

### ISSUE THREAD

**Issue by Snoopy5570** [homebridge/homebridge#3372]
### Current Situation

When restoring electricity, Raspberry Pi4 with homebridge does not restart the service. I have to turn off the power to the Raspberry and put it back on. Can you show me a resolution to the problem?

### Logs

```markdown
.
```

### Configuration

```json
.
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software:v1.6.1
- Node:v18.16.0
- npm:

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Sounds like your raspberry pi is possibly starting before your network is available.

**Comment by Snoopy5570** [comment]
Obviously the modem starts after Raspberry, it seems strange to me that it doesn't line up after

**Comment by JurgenLB** [comment]
I heard about this problem earlier, you must put a delay in your bootconfig so the Pi's networkadaptor comes after the modem.

**Comment by JurgenLB** [comment]
under raspi-config you can choose:
Boot options - Wait for network at boot.

**Comment by Snoopy5570** [comment]
> under raspi-config you can choose:
> Boot options - Wait for network at boot.

Not present
![image](https://github.com/homebridge/homebridge/assets/67944815/66753f0f-4d91-4551-974a-698b3d9b81b8)

**Comment by JurgenLB** [comment]
> > under raspi-config you can choose:
> 
> > Boot options - Wait for network at boot.
> 
> 
> 
> Not present
> 
> ![image](https://github.com/homebridge/homebridge/assets/67944815/66753f0f-4d91-4551-974a-698b3d9b81b8)
> 
> 

You must do it from the terminal/command line;
sudo raspi-config 
![image](https://github.com/homebridge/homebridge/assets/77586573/8429fdde-ff8b-4198-8828-549962f39a4b)

**Comment by Snoopy5570** [comment]
> > > under raspi-config you can choose:
> > 
> > 
> > > Boot options - Wait for network at boot.
> > 
> > 
> > Not present
> > ![image](https://user-images.githubusercontent.com/67944815/240978177-66753f0f-4d91-4551-974a-698b3d9b81b8.jpeg)
> 
> You must do it from the terminal/command line; sudo raspi-config ![image](https://user-images.githubusercontent.com/77586573/241062558-8429fdde-ff8b-4198-8828-549962f39a4b.jpeg)

Is there a table to read for the commands?

**Comment by Snoopy5570** [comment]
> > > > under raspi-config you can choose:
> > > 
> > > 
> > > > Boot options - Wait for network at boot.
> > > 
> > > 
> > > Not present
> > > ![image](https://user-images.githubusercontent.com/67944815/240978177-66753f0f-4d91-4551-974a-698b3d9b81b8.jpeg)
> > 
> > 
> > You must do it from the terminal/command line; sudo raspi-config ![image](https://user-images.githubusercontent.com/77586573/241062558-8429fdde-ff8b-4198-8828-549962f39a4b.jpeg)
> 
> Is there a table to read for the commands?



> > > under raspi-config you can choose:
> > 
> > 
> > > Boot options - Wait for network at boot.
> > 
> > 
> > Not present
> > ![image](https://user-images.githubusercontent.com/67944815/240978177-66753f0f-4d91-4551-974a-698b3d9b81b8.jpeg)
> 
> You must do it from the terminal/command line; sudo raspi-config ![image](https://user-images.githubusercontent.com/77586573/241062558-8429fdde-ff8b-4198-8828-549962f39a4b.jpeg)

I enabled the boot that starts after network, but it doesn't work. If I turn off the electricity, the services will not start again. I have to restart the Raspberry with there network on. The connection between modem and Raspberry is in Wi-Fi.

**Comment by JurgenLB** [comment]
A computer running Homebridge is a server, it is a good practice to always connect a server with LAN.

WiFi is not a good solution for this.

**Comment by Snoopy5570** [comment]
> A computer running Homebridge is a server, it is a good practice to always connect a server with LAN.
> 
> WiFi is not a good solution for this.

Is it possible that you can't set a boot start time?

**Comment by FarmerAndrew** [comment]
I have the same issue. When I connect to Homebridge (over wi-fi) it is stuck at the wi-fi configuration screen.  Select the SSID and enter password and it then works until the next power outage. 

I strongly recommend that a periodic check be added on the Homebridge wifi configuration routine that if: 
 Wi-fi is connected AND no one is logged in to the web interface then Homebridge is automatically restarted.

**Comment by Snoopy5570** [comment]
> I have the same issue. When I connect to Homebridge (over wi-fi) it is stuck at the wi-fi configuration screen after a power outage. If I select the SSID and enter password and it then works until the next power outage.
> 
> I strongly recommend that a periodic check be added on the Homebridge wifi configuration routine that if: Wi-fi is connected AND no one is logged in to the web interface then Homebridge is automatically restarted.

It doesn't happen to me. Try assigning a static IP for homebridge. In the Homebridge/ network interface settings see if it has taken static IP and does not flag wlan0. So it should maintain the network without plugg in every time it restarts.

**Comment by FarmerAndrew** [comment]
> > I have the same issue. When I connect to Homebridge (over wi-fi) it is stuck at the wi-fi configuration screen after a power outage. If I select the SSID and enter password and it then works until the next power outage.
> > I strongly recommend that a periodic check be added on the Homebridge wifi configuration routine that if: Wi-fi is connected AND no one is logged in to the web interface then Homebridge is automatically restarted.
> 
> It doesn't happen to me. Try assigning a static IP for homebridge. In the Homebridge/ network interface settings see if it has taken static IP and does not flag wlan0. So it should maintain the network without plugg in every time it restarts.

It’s only a problem when the wi-fi router is not running yet. On power on, without a wifi connection the homebridge wifi configuration tool starts as there is no network to connect to at the moment.  The problem is that once it’s in the configuration tool it requires a restart to leave, leaving the main part of Homebridge not running, even after it restores a wifi connection.

**Comment by Snoopy5570** [comment]
> 

The problem remains for me if you start homebridge first and then the modem. But if I restart homebridge with modem ok then it resumes normal operation and does not ask me for the ssid. I'm just looking for a method for an automatic reboot when he sees Wi-Fi on reboot
