### ISSUE TITLE
Ring Cameras no longer showing detected motion

### ISSUE THREAD

**Issue by TNOTA** [homebridge/homebridge#3375]
solution found, not Homebridge related.

**Comment by NorthernMan54** [comment]
As this is an issue with your ring cameras, please open this issue against the Ring Plugin on GitHub so that the plugin developer is aware and can action this issue for you.

**Comment by TNOTA** [comment]
Hi

 The reason I didn’t is because it’s not working with any version of the Ring plugin, even versions it used to work on. The only change was an update to HomeBridge itself. So my thought was this was a HomeBridge level issue not a plugin issue.
