### ISSUE TITLE
Can not uninstall a homebridge plug-in 

### ISSUE THREAD

**Issue by richierockskool** [homebridge/homebridge#3380]
### Current Situation

Error operation failed please review log 

### Logs

```markdown
CMD: npm uninstall -g homebridge-inkbird-wifi-gateway

npm ERR! code EISDIR
npm ERR! syscall rename
npm ERR! path /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway
npm ERR! dest /Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w
npm ERR! errno -21
npm ERR! EISDIR: illegal operation on a directory, rename '/Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway' -> '/Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w'

npm ERR! A complete log of this run can be found in: /Users/richjagger/.npm/_logs/2023-05-31T20_24_57_167Z-debug-0.log
```

### Configuration

```json
{
  "pluginAlias": "HomebridgeInkbirdWifiGateway",
  "pluginType": "platform",
    "schema": {
    "type": "object",
    "properties": {
      "name": {
        "title": "Name of the device",
        "type": "string",
        "required": true,
        "default": "Homebridge Inkbird Wifi Gateway Dynamic Platform",
        
        
      },
      {
        "name": "HomebridgeInkbirdWifiGateway",
        "devices": [
            {
                "name": "Inkbird Wifi Gateway",
                "type": "IBSM1S",
                "deviceId": "<<Ble MAC Address>>"
            }
        ],
        "update_interval": 15,
        "storage": "filesystem",
        "loglevel": 3,
        "platform": "homebridge-inkbird-wifi-gateway"
    }
  }
}
    
}
```

### Environment

- OS: 12.6.6
- Software: VS Code
- Node: 18.16.0
- npm: 9.6.7

### Process Supervisor

hb-service

### Additional Context

Lock in a loop can not uninstall or reinstall without error and unable to remove from HomeBridge

**Comment by dampney** [comment]
Can someone please share the solution for this error? 

I really want to avoid having to reset Homebridge - it's my last resort

**Comment by donavanbecker** [comment]
Run this in terminal
```
sudo rm -R /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway && sudo rm -R /Users/richjagger/.npm-packages/lib/node_modules/.homebridge-inkbird-wifi-gateway-3htFxu5w
```

**Comment by dampney** [comment]
I got this: 

`rm: /Users/richjagger/.npm-packages/lib/node_modules/homebridge-inkbird-wifi-gateway: No such file or directory`

My error is:

`USER: server
DIR: /usr/local
CMD: npm uninstall -g @switchbot/homebridge-switchbot

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/@switchbot/homebridge-switchbot
npm ERR! dest /usr/local/lib/node_modules/@switchbot/.homebridge-switchbot-UUyzm0HE
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/@switchbot/homebridge-switchbot' -> '/usr/local/lib/node_modules/@switchbot/.homebridge-switchbot-UUyzm0HE'

npm ERR! A complete log of this run can be found in: /Users/server/.npm/_logs/2023-12-23T12_19_39_843Z-debug-0.log

Operation failed. Please review log for details.
`
