### ISSUE TITLE
unable to add accessory

### ISSUE THREAD

**Issue by jesusvlogs98** [homebridge/homebridge#3384]
### Current Situation

i try to ad homebridge to homekit app but before conect shows me this issue saying "unable to Add Accesory"

### Logs

```markdown
no important
```

### Configuration

```json
.
```

### Environment

- OS: osx ventura
- Software: ios 16.5
- Node: v16.16.0
- npm: 8.11.0
![IMG_7B918CBD799C-1](https://github.com/homebridge/homebridge/assets/134891437/ddd1f183-7465-428f-a009-3a7d53f9bfc2)

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Before you add it, you need some accessories

From the log you had originally included

[6/9/2023, 9:55:39 AM] Loaded config.json with 0 accessories and 1 platforms.

**Comment by pjezquenazy** [comment]
estoy en la misma restablecí y en ios17 ya no madeja agregarlo me dice accesorio no compatible!!

**Comment by jesusvlogs98** [comment]
> Before you add it, you need some accessories
> 
> From the log you had originally included
> 
> [6/9/2023, 9:55:39 AM] Loaded config.json with 0 accessories and 1 platforms.

I try with a ring camera added but same issue

**Comment by jesusvlogs98** [comment]
> estoy en la misma restablecí y en ios17 ya no madeja agregarlo me dice accesorio no compatible!!

Igual puede que iOS 17 no deje por ahora… es algo de desarrollo igualmente

**Comment by pjezquenazy** [comment]
haciendo investigación y pruebas también en iOS 16.5... eso ya es preocupante.....
