### ISSUE TITLE
Sudo hb-service can’t be used to update node.js

### ISSUE THREAD

**Issue by jraget** [homebridge/homebridge#3387]
### Current Situation

I would like to update to the latest Homebridge UI. However it recommends Node.js 16.20.0 and I am still on 14.18.1.
I would to use the recommended route to update Node.js: sudo hb-service update-node On a raspberry Pi running Stretch.
However I get this:
Your version of Linux does not meet the GLIBC version requirements to use in this tool to upgrade node.js. Wanted 2.28. Installed 2.24.
I guess it’s because I m still on Stretch? Reading around the GLIBC it’s NOT recommended ti try to upgrade it.
Can anyone help me out?
I suppose I am after a safe way to upgrade Node.js for Homebridge for those who cannot use hb-service.

### Logs

```markdown
None
```

### Configuration

```json
Raspberry Pi Stretch
```

### Environment

- OS: Stretch
- Software: Homebridge 1.6.1
- Node: 14.18.1
- npm: 9.7.1

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Easiest update approach in your setup, would be to create a homebridge backup, get a new SD card for your RPI, install the latest homebridge image, then restore your backup.
