### ISSUE TITLE
Cannot add user in Apple Home

### ISSUE THREAD

**Issue by avoud** [homebridge/homebridge#3388]
### Current Situation

I updated to latest v.1.6.1 and I do not have the option to add another user in Apple Home app. Anything has to do with config in Homebridge?

### Logs

```markdown
.
```

### Configuration

```json
standard
```

### Environment

- OS:  Raspbian GNU/Linux Buster (10)
- Software:
- Node:v18.16.0
- npm: 9.5.1

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
This is very doubtfully a homebridge issue, and likely an issue with your home setup.  Do you have a home hub ?

**Comment by avoud** [comment]
I do not have a home hub. I am using the Raspberry for Home Hub

**Comment by NorthernMan54** [comment]
I went into the Home App, and created a new home called `Test'. I did not pair homebridge with it, but went to `Home Settings' and was able to Invite people.

I then went and added homebridge to my test home, and am still able to Invite people.

Am thinking there is a potential issue with your apple user id, and not related to homebridge

**Comment by JurgenLB** [comment]
The raspberry with HomeBridge can act as a bridge, only a HomePod (original or mini) and a AppleTV can act as a HomeHub

**Comment by mbaumgae81** [comment]
Hey i had the same Problem. But now i see there some changes on IOS 16. So you can connect the homebridge. But on IOS 16 theres without an hub, no chance to share.  So more than one person should youse you will need an AppleTV or HomePod mini.

**Comment by avoud** [comment]
> 

This should be it. Thanks!
