### ISSUE TITLE
Validation error in Docker Compose file: Additional property 'ersion

### ISSUE THREAD

**Issue by Rfkgaming89** [homebridge/homebridge#3389]
### Current Situation

Copying the current docker compose file you will get the error 

Validation error in Docker Compose file: Additional property 'ersion

 The current docker compose Manifest is 
 
 version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1" 

### Proposed Change

The correct one should be as followed 

version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '1'

    Removed unnecessary quotation marks around the max-size value. It should be provided as a numeric value without quotes.
    Enclosed the value of max-file in quotes to ensure it is treated as a string.

**Comment by NorthernMan54** [comment]
Tks for noticing this

could you raise this against docker-homebridge, https://github.com/homebridge/docker-homebridge

**Comment by Rfkgaming89** [comment]
Sure let me go make a issue
