### ISSUE TITLE
Remove ANSI Colorization from Log File

### ISSUE THREAD

**Issue by williamtrelawny** [homebridge/homebridge#3391]
### Current Situation

By default, the logs in the log file are colorized. When forwarding Homebridge logs with syslog-ng, the ANSI color codes are escaped and appear in the resulting log output:

<img width="1185" alt="image" src="https://github.com/homebridge/homebridge/assets/22324745/232b74dc-e9e4-4046-ba57-5186cce075cc">

### Proposed Change

Provide an option to disable log colorization, at least in the log file on the OS. Colorization is fine in the UI.

### Additional Context

Not sure if [this PR](https://github.com/homebridge/homebridge/pull/1889) has anything to do with this, but this purports to give a `-C` command line option to optionally colorize the logs, however logs seem to be colorized by default now.

**Comment by ebaauw** [comment]
Afaik, by default, the logs contain colour when output to a tty, and not when redirected to a file.  As mentioned in the linked PR, the `-C` option is to also include colour when the output is redirected.

**Comment by williamtrelawny** [comment]
Oh ok you're right. When `less`ing the homebridge.log:

<img width="1219" alt="image" src="https://github.com/homebridge/homebridge/assets/22324745/4123a660-3225-4a73-b9cc-a2384e697e5e">

But my point still remains- is there any way to disable this? Because now I have to do some weird parsing on-the-fly within syslog-ng, which add unnecessary processing load.

**Comment by williamtrelawny** [comment]
Also, I don't have the `-C` option enabled and my log output to a tty and the Homebridge UI is still colorized.

**Comment by williamtrelawny** [comment]
I just tried setting `NODE_DISABLE_COLORS=1` in NODE_OPTIONS, restarted Homebridge, but colorization is still in effect in the log file. ref: https://nodejs.org/api/cli.html#node_disable_colors1

**Comment by ebaauw** [comment]
The colours are added using the `chalk` library, so I wouldn't expect a Node option to influence this.  I'm not sure which version Homebridge is using, but `chalk` does support disabling the colours through an environment variable, see https://github.com/chalk/chalk#supportscolor.

**Comment by williamtrelawny** [comment]
Ok and I see references in the PR to the chalk library and the various color arguments it supports, but I can't figure out where to see chalk settings or how to change them in my env. Any ideas?

**Comment by williamtrelawny** [comment]
Sorry, just getting back around to this... How do I set `chalk` env vars in Homebridge?

**Comment by williamtrelawny** [comment]
@ebaauw in your PR (linked in OP above) did you set the `-C` command line argument to have a default value of true or something? I don't know the language too well, so I can't tell for sure.
