### ISSUE TITLE
Unable to access web GUI across LAN

### ISSUE THREAD

**Issue by adamsdp** [homebridge/homebridge#3392]
### Current Situation

Hello

I am having trouble accessing the web GUI across my LAN. I can access it with no issues from the Raspberry Pi that I have my instance running on xxx.xxx.xxx.xxx:8581, but when I try to access the same address from another machine on the same LAN it fails to connect.

What am I doing wrong?

Many thanks for your help in advance

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software: 1.6.1
- Node: 18.16.0
- npm: 9.5.1

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Are you using the homebridge image or something else ?

**Comment by NorthernMan54** [comment]
This sounds like a potential networking or firewall issue between your other machine and the RPI, are you able to ping the RPI from your other machine ?
