### ISSUE TITLE
https://synology.homebridge.io host not responding.

### ISSUE THREAD

**Issue by aslankose** [homebridge/homebridge#3394]
### Current Situation

https://synology.homebridge.io host not responding. 

### Logs

```markdown
n/a
```

### Configuration

```json
n/a
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
@oznu Do you have admin rights for this ?

**Comment by oznu** [comment]
I had a traffic usage warning earlier today saying I'd used 85% of my 1000000 free AWS Lambda requests for July already so I turned on the CloudFlare proxy in an attempt to cache the records; clearly that didn't work. I've turned it off.

**Comment by aslankose** [comment]
> I had a traffic usage warning earlier today saying I'd used 85% of my 1,000,000 free AWS Lambda requests for July already so I turned on the CloudFlare proxy in an attempt to cache the responses / stop any misuse; clearly that didn't work. I've turned it off.



> I had a traffic usage warning earlier today saying I'd used 85% of my 1,000,000 free AWS Lambda requests for July already so I turned on the CloudFlare proxy in an attempt to cache the responses / stop any misuse; clearly that didn't work. I've turned it off.

**Comment by aslankose** [comment]
Thank you very much for quick response.
