### ISSUE TITLE
[docs] Synology package install steps: install nodejs

### ISSUE THREAD

**Issue by sebestindragos** [homebridge/homebridge#3401]
### Analysis

Hello,

Thank you for making homebridge installable via synology package center.
This is just a small request to update the docs on how to install it since it took me a while to figure out.
After installing the package it was marked as running in package center, but opening the Web UI would result in a connection error (the server wasn't actually running).

I tried looking at the contents of the `/homebridge` folder and saw just the `package.json` file which led me to believe the install did not go through properly. After a while I figured out I need to manually install nodejs from the package center. After I did that and restarted homebridge it worked like a charm.

Please add this very important step to the docs to make sure other people don't struggle with it like I did.

All the best,
Dragos

### Expected Behavior

Should be able to install and get it working on first try.

### Steps To Reproduce

Install homebridge package on DSM7 without nodejs installed

### Logs

```markdown
none
```

### Configuration

```json
none
```

### Environment

- OS: DSM7
- Software: 
- Node: 18
- npm:

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
@sebestindragos - That is an outstanding issue with the build, and will be looking for a fix.

**Comment by NorthernMan54** [comment]
Release 3.0.17 Fixes the dependency for the Synology NodeJS 18 package, and makes sure that it is installed prior allowing the homebridge package to be installed.   Also included are fixes to the command line sudo interface made by @ebaauw
