### ISSUE TITLE
Better integration for Aqara led strip T1

### ISSUE THREAD

**Issue by KatyPurry** [homebridge/homebridge#3420]
### Current Situation

The [Aqara led strip T1](https://www.aqara.com/eu/product/led-strip-t1/led-strip-t1-specs/) is equipped with RGB leds and dedicated leds for tunable white accent light. However, in the Homekit app, only RGB leds are used, even for white accent light. The leds dedicated to whites never light up. 

Also if possible add adaptive lighting.

P.S: I don't know if it's related to Homebrige or Deconz/Phoscon app. Let me know !

Thank you

![image](https://github.com/homebridge/homebridge/assets/89610869/3908a74c-1e26-444c-84d3-fda33c3fad08)

### Proposed Change

Using Whites leds

I'm using Homebridge with Conbee II stick with Deconz docker on UnRAID OS.

**Comment by ebaauw** [comment]
This is not an issue with Homebridge.  Maybe with the Homebridge plugin you’re using, maybe with deCONZ, but most likely with the strip firmware.  Best do a device request in deCONZ, including all requested screen shots, to check how the firmware exposes the strip over Zigbee.  We would need to do something there to support the gradient and effects features as well.

**Comment by ebaauw** [comment]
Looks like my local webshop now has the light strip available.  ETA Saturday…

**Comment by KatyPurry** [comment]
Awesome thank you ! Do I need to open a device request in deCONZ or you will ?

**Comment by ebaauw** [comment]
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/7200
