### ISSUE TITLE
Which RPI for homebridge in container

### ISSUE THREAD

**Issue by Nick-smar** [homebridge/homebridge#3421]
### Current Situation

Hi,

for the last 4? years I'm running Homebridge in a docker container on my Rpi 3 Model B.
I had some issues with the stability of the system and I started all over from scratch on this RPI3.
With pulling the latest container I have the impression it's all a little bit to much for my pi.
Htop is giving sick values.

Is this correct? Should I go to a newer raspberry with more memory? 

### Logs

```markdown
no logs
```

### Configuration

```json
RPI
1 container for Zigbee2mqtt
1 container for nodered
1 container for homebridge
```

### Environment

- OS: Raspberry PI OS 64 bit
- Homebridge

### Process Supervisor

Docker (Mention image name in `Additional Context`)

**Comment by JurgenLB** [comment]
If you put only homebridge on the system a Pi 3 is enough.
But if you use also other containers and programs you use best a Pi 4 / 4 Gb.

**Comment by Nick-smar** [comment]
I use 2 other containers. Zigbee2mqtt and Nodered.
Is it possible by pulling and updating everything that is has become to much?
I just can't figure out why my CPU is so high. I thought it was my sd-card that got corrupted but also with a new one i'm overloaded.
My Red and Green LED are also always on...

very stange and very inconvienient since I now notice the first time how much our house is depending on Homebridge & homekit

**Comment by JurgenLB** [comment]
In the beginning I used 3 raspberry Pi 3 for my homeautomations and homebridge. Now I have everything running on a Pi4 / 8 Gb My services; ['pigpiod', 'mosquitto', 'apcupsd', 'homebridge', 'containerd', 'upswift', 'watchdog', 'Domoticz'] with 2,62 free memory
