### ISSUE TITLE
Tile (button) Size in Home app

### ISSUE THREAD

**Issue by arjena** [homebridge/homebridge#3422]
### Current Situation

I have been using Homebridge for several years and apart from some hiccups when Apple decides to change things, I am very happy with Homebridge. Some time ago (don't remember when) the interface in the home app changed. From square buttons to horizontal rectangles. But not for everything...
I have a Tado thermostat coupled through Homebridge. I can read the temperature in the home app in a large rectangle double the hight of the rest of the buttons. I like that a lot, I need glasses to read and these numbers are big enough to read without them. 
I have a light sensor connected through MQTT (with mqtt-thing), which is now a very small entry somewhere in the top op the apps interface. I would like the light value in the same large letters on my screen, but I don't have a clue where to start...
Any pointers?

### Logs

```markdown
n.a.
```

### Configuration

```json
"accessories": [
        {
            "type": "lightSensor",
            "name": "homeLux",
            "username": "xxxx",
            "password": "xxxxx",
            "topics": {
                "getCurrentAmbientLightLevel": "homeLux"
            },
            "accessory": "mqttthing"
        },
```

### Environment

OS | Raspbian GNU/Linux Bullseye (11)
node.js v18.12.1
Homebridge 1.6.1

### Process Supervisor

not applicable

### Additional Context

none

**Comment by caitken-com** [comment]
Hi @arjena,
Homebridge doesn’t have any control over how accessories appear in the Home app. The accessory type determines how it’ll appear.
Eg: thermostat is double height, lights are single height, as set by Apple.
There is no API for appearance.

**Comment by arjena** [comment]
Thanks. Have to turn it into a thermostat then ;).
In the latest Home.app it is not even possible to get a 'button' for a sensor. So a sensor value is always a small entry on the top of the page. Since the latest update only visible on the page for the room the sensor is set to be in.
So to make it bigger I need to create a clickable item. Should be possible, but too busy now to work it out. Looks like I will need to use my glasses for now...
