### ISSUE TITLE
Node 16 to 18 update - Alpine - Docker - Synology

### ISSUE THREAD

**Issue by mitchoklemen** [homebridge/homebridge#3423]
### Current Situation

I would like to update Node.js but on Alpine there is no way I would know to update it.
Any suggestions? Since Node.js 16 version is supported till september.

### Proposed Change

trick

**Comment by NorthernMan54** [comment]
FYI - We have dropped support for the Alpine based docker images - https://github.com/homebridge/docker-homebridge/issues/437

PS This issue should have been against docker-homebridge
