### ISSUE TITLE
M2 Mac hb-service plist not found/wrong directiry

### ISSUE THREAD

**Issue by TeslaOwnerTips** [homebridge/homebridge#3425]
### Analysis

sudo hb-service restart /Library/LaunchDaemons/com.homebridge.server.plist
Not found

sudo hb-service stop; sudo service uninstall; sudo service install —port 8581
Complains another service is already using port 8581 (I had just uninstalled it. Reboot made no difference)

I located it in
/Librarary/LaunchAgents
Moved from agents to daemons fixed all the problem 

### Expected Behavior

plist file is in the wrong folder?

### Steps To Reproduce

Mac OS install of homebridge with UI

### Logs

```markdown
Not relevant?
```

### Configuration

```json

"bridge": {
        "name": "Mac Mini",
        "username": "0E:7B:93:23:AB:62",
        "port": 51793,
        "pin": "110-00-110",
        "advertiser": "bonjour-hap"
    },
———————

"platforms": [
        {
            "name": "Web UI",
            "port": 8581,
            "platform": "config",
            "auth": "none"
        },

```

### Environment

- OS: macOS Ventura
- Software: hb-service v4.50.4
- Node: v20.5.1
- npm: 9.8.0

Node according to Web UI v18.16.1

### Process Supervisor

hb-service

**Comment by bwp91** [comment]
Hi @TeslaOwnerTips 

> Mac OS install of homebridge with UI
Could you expand on how you installed homebridge on your mac?

**Comment by RCdiy** [comment]
port="8581"
  instance="homebridge"
  sudo hb-service stop --service-name $instance --port $port
  sleep 2
  sudo hb-service uninstall --service-name $instance --port $port
  sleep 1
  sudo pkill homebridge
  sleep 1
  sudo hb-service install --service-name $instance --port $port
  sleep 1
  sudo hb-service start --service-name $instance
