### ISSUE TITLE
Accessory Widgets in macOS Sonoma

### ISSUE THREAD

**Issue by brak265** [homebridge/homebridge#3429]
### Current Situation

Hello, I know it may not be implemented because Sonoma is still in beta, but I noticed despite the Home app working, I cannot get my WiZ bulbs to show up as widget accessories on my desktop.  I can select them by editing the widget, but it just says "No Home Hub" when I exit the edit screen.  Is this is a limitation of Homebridge or simply something not implemented yet?  I think this is a new feature to the macOS Sonoma beta, but I could be wrong.

### Logs

```markdown
None generated in the UI when editing widgets
```

### Configuration

```json
N/A
```

### Environment

- OS: macOS Sonoma 14.0
- Software: Homebridge 1.6.1
- Node: 18.17.0
- npm: 9.6.7

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
Do you have a Home Hub?
