### ISSUE TITLE
Accessory with multiple services has it's extra options "hidden" in Home app

### ISSUE THREAD

**Issue by kovapatrik** [homebridge/homebridge#3435]
### Current Situation

I'm currently developing a plugin for an air conditioner, and for this I'm using the Heater Cooler characteristic. The unit has also an outdoor temperature sensor, which I also add to the accessory. When I do so, the extra, AC related options (like oscillation or fan speed) are "hidden" away, so I have to navigate into the "Accessories" submenu in the Home app (where I see the AC and the temperature sensor seperately) if I want to tinker with these settings.

Is there a way to have those options at "top-level", as if there were no temperature sensor attached to the accessory?

Of course I could create the tempertature sensor as a seperate accessory, but I want them to be in one single accessory.

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

-

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
@kovapatrik How accessories appear in the Home app is limited to what Apple thinks a proper accessory should be.   Have you tried experimenting with the `HomeKit Accessory Simulator` to see what combinations are supported

**Comment by kovapatrik** [comment]
Yes, I had tried, but without any success, I've experienced the same thing. Also tried with linking, but it had no effect.

I thought about Apple limitations, but I've found a screenshot in Reddit, which shows a thermostat with 3 accessories, and the thermostat specific option is visible: https://imgur.com/VJBwP0T.
