### ISSUE TITLE
Support for installing plugins from custom / private NPM repositories

### ISSUE THREAD

**Issue by jahudka** [homebridge/homebridge#3438]
### Current Situation

Currently, Homebridge doesn't document any way to install a plugin from a custom / private / 3rd party NPM repository. For example, I'm running a private Gitea instance; one of Gitea's features is a built-in package registry. I have made some very custom hardware which I doubt anyone else apart from me will ever have, so it doesn't make sense to pollute the public NPM repository with my custom Homebridge plugins. But the UI doesn't offer any way to set up custom NPM repositories; the only way I found is by manually running the pertinent `npm config` commands in `hb-shell`.

### Proposed Change

The best solution from my point of view would be to add UI which would allow one to define custom scoped NPM repositories - basically an UI for `npm config set <@scope>:registry <url>` and `npm config set -- "<url>:_authToken" <token>`. But I suppose this is probably too niche a feature to warrant custom UI.. which is fine, but it would be nice to at least have this mentioned in the docs.

### Additional Context

~~`hb-service add @scope/plugin@1.0.0` tells me `@scope/plugin` is an invalid plugin name - probably because scopes aren't supported - which is fine, at this point I'm just gonna `npm install` the plugin manually - but if the custom registry configuration is enabled, then this might also need some love.~~

(turns out the issue was that the plugin name didn't adhere to Homebridge convention, my bad - you _can_, indeed, install scoped plugins, the name just has to start with `homebridge-`, e.g. `@my-scope/homebridge-plugin`)

**Comment by NorthernMan54** [comment]
Since you resolved your issue, can we close this ?

**Comment by bwp91** [comment]
@NorthernMan54 I know your question wasn't pointed towards me but I am happy to close this.

NPM package naming conventions are documented in the plugin template:
- https://github.com/homebridge/homebridge-plugin-template#update-packagejson

I appreciate this is a bit hidden within the docs, but I also don't really think there is anywhere that we could make this more visible.

@jahudka please feel free to re-open if needed 👍
