### ISSUE TITLE
"Hey Siri" no longer sets switch actuators to 0% via HomePod (17.0 / 21J354).

### ISSUE THREAD

**Issue by SebastianStorb** [homebridge/homebridge#3443]
### Analysis

When I send the command "Hey Siri, darken the living room 0%" or , it is executed correctly via the iPhone or iPad. (Where darken the livingroom are only two words in German and are represented that way: "Verdunkelung Wohnzimmer").
If I send the same command via my HomePod, the Homebridge web overview only shows that the device has been switched off - but the blinds are not running. All other positions from 1-100% are controlled correctly.

### Expected Behavior

The blinds should also be able to be moved to 0% position via the Homepod and not just via the iPhone or iPad

### Steps To Reproduce

Temporary solution: Move the blinds to the 1% position to open them

### Logs

```markdown
WORKING WITH iPhone14 (17.0.3):
[8.10.2023, 13:53:09] [FHEM] Jalousie_Sebastian: executing set cmd for Brightness with value 0
[8.10.2023, 13:53:09] [FHEM]   executing: http://192.168.1.100:8083/fhem?cmd=set%20Jalousie_SebastianXXXXXXXXXXX=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=1

NOT WORKING with HomePod (17.0)

[8.10.2023, 13:51:38] [FHEM] Jalousie_Sebastian: executing set cmd for On with value false
[8.10.2023, 13:51:38] [FHEM]   executing: http://192.168.1.100:8083/fhem?cmd=set%20Jalousie_SebastianXXXXXXXX=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=1
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge XXXX",
        "username": "XXXXXXXXXXXX",
        "port": 51656,
        "pin": "XXXXXXXXXX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "FHEM",
            "server": "192.168.1.100",
            "port": 8083,
            "auth": {
                "user": "sebastian",
                "pass": "XXXXXXX"
            },
            "filter": "room=Homekit",
            "platform": "FHEM"
        }
    ]
}
```

### Environment

- OS: debian-linux
- Software: v.1.6.1
- Node: v.18.18.0
- npm: --

### Process Supervisor

not applicable

### Additional Context

i do not know process supervisor / i did not change anything.

**Comment by NorthernMan54** [comment]
This is something that I'm not sure is within our control.   It looks like Siri via the iPhone is working differently than the HomePod, and sending different commands to Homebridge.

I'm wondering if the plugin developer could tweak or change the device interface to have brightness 0 and setting On to false do the same thing ?

**Comment by SebastianStorb** [comment]
I heard from a friend that the problem with controlling Homeassistant with iPhone or HomePod has been exactly as I described since the Apple update to 17.x. So I assume that the Apple problem will never be fixed (because as we all know, Apple doesn't make mistakes - and if they do, it's always a feature).
;-)
