### ISSUE TITLE
Unable to update/install myQ plugin

### ISSUE THREAD

**Issue by ericdhkim** [homebridge/homebridge#3451]
### Current Situation

When I try to update the myQ plugin via the Homebridge web UI, I get an error. I'm able to update other plugins, homebridge UI, as well as the Raspberry Pi without issue, but am seeing this error with only this plugin update. I see the below error:
USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-myq@3.2.0

npm ERR! Cannot read properties of undefined (reading 'isStream')

npm ERR! A complete log of this run can be found in: /home/homebridge/.npm/_logs/2023-08-22T04_23_04_678Z-debug-0.log

I thought maybe uninstalling and reinstalling would help but I’m not able to reinstall as when I try to install via homebridge ui x I get the same error as above

### Logs

```markdown
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.6.7
2 info using node@v18.17.1
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 8ms
8 warn config global-style This option has been deprecated in favor of --install-strategy=shallow
9 timing config:load:env Completed in 2ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/homebridge/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 3ms
16 timing config:load Completed in 26ms
17 timing npm:load:configload Completed in 26ms
18 timing npm:load:mkdirpcache Completed in 1ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install homebridge-myq@3.2.0
21 verbose argv "install" "--global" "homebridge-myq@3.2.0"
22 timing npm:load:setTitle Completed in 3ms
23 timing config:load:flatten Completed in 10ms
24 timing npm:load:display Completed in 13ms
```

### Configuration

```json
Config is empty for myQ as I’m not able to reinstall
```

### Environment

- OS: Raspbian GNU/Linux Buster (10)
- Software: Homebridge
- Node: 18.17.1
- npm: 9.6.7

### Process Supervisor

hb-service

**Comment by parisbite** [comment]
There is no reason I should feel uncomfortable in my own home!!!
