### ISSUE TITLE
Help, can’t update node.JS says I need to change the repo anybody have a fix or command line to fix this

### ISSUE THREAD

**Issue by swylie1970** [homebridge/homebridge#3454]
### Analysis

Won’t allow updates to node 

### Expected Behavior

Well update says has an expired repo

### Steps To Reproduce

Everytime 

### Logs

```markdown
SCRIPT DEPRECATION WARNING
This script, located at https://deb.nodesource.com/setup_X, used to install Node. js is deprecated now and will eventually be made inactive.
Please visit the NodeSource distributions Github and follow the instructions to migrate your repo.
https://github.com/nodesource/distributions
The NodeSource Node. js Linux distributions GitHub repository contains information about which versions of Node.js and which Linux distributions are supported and how to install it.
https://github.com/nodesource/distributions
SCRIPT DEPRECATION WARNING
```

### Configuration

```json
SCRIPT DEPRECATION WARNING
This script, located at https://deb.nodesource.com/setup_X, used to install Node. js is deprecated now and will eventually be made inactive.
Please visit the NodeSource distributions Github and follow the instructions to migrate your repo.
https://github.com/nodesource/distributions
The NodeSource Node. js Linux distributions GitHub repository contains information about which versions of Node.js and which Linux distributions are supported and how to install it.
https://github.com/nodesource/distributions
SCRIPT DEPRECATION WARNING
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

### Additional Context

SCRIPT DEPRECATION WARNING
This script, located at https://deb.nodesource.com/setup_X, used to install Node. js is deprecated now and will eventually be made inactive.
Please visit the NodeSource distributions Github and follow the instructions to migrate your repo.
https://github.com/nodesource/distributions
The NodeSource Node. js Linux distributions GitHub repository contains information about which versions of Node.js and which Linux distributions are supported and how to install it.
https://github.com/nodesource/distributions
SCRIPT DEPRECATION WARNING

**Comment by NorthernMan54** [comment]
With the next release of Homebridge-config-ui-x, later this week we will resolve this.

Duplicate https://github.com/homebridge/homebridge-config-ui-x/issues/1589
