### ISSUE TITLE
Build fails due to ancient "smc" code

### ISSUE THREAD

**Issue by tangentsoft** [homebridge/homebridge#3455]
### Analysis

I am getting the logging output below in the Homebridge UI since updating the underlying dependencies via Homebrew on macOS:

Digging into its suggestion to install the smc package with NPM manually, the problem comes down to it attempting to call sprintf(), which current compilers now reject unless you go out of your way to arm-twist it into accepting — via -Wdeprecated-declarations, perhaps? — for good and sufficient reasons, IMHO.

Looking into [the smc package](https://www.npmjs.com/package/smc), it hasn't been updated in 7 years. Either someone needs to adopt this and bring it up to modern secure coding standards, or HB shouldn't be depending on it.

### Expected Behavior

It should build and run. :)

### Steps To Reproduce

1. Update everything
2. Attempt to restart Homebridge.

### Logs

```markdown
Error: The module '/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/osx-temperature-sensor/build/Release/smc.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 120. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.cpuTemperature (/usr/local/lib/node_modules/homebridge-camera-ui/node_modules/osx-temperature-sensor/lib/index.js:49:15)
    at /usr/local/lib/node_modules/homebridge-camera-ui/node_modules/systeminformation/lib/cpu.js:1188:28
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

### Configuration

```json
n/a
```

### Environment

- OS: macOS
- Software: 1.6.1
- Node: 21.1.0
- npm: 10.2.0

### Process Supervisor

hb-service

**Comment by tangentsoft** [comment]
Removing the Homebrew versions of node and npm and then installing the LTS binary versions [as is now documented](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS) solved this. I was certain that when I started with HB that the docs claimed Homerew compatibility, but then again, it seemed like with every "`brew upgrade`" HB would break again to the point that I had to run this `hb-fix` script I wrote:

``` shell
#!/bin/sh
for v in stop uninstall rebuild install start
do
    sudo hb-service $v
done

echo -n "Waiting..."
sleep 3
echo

sudo hb-service status
```

I am hoping that switching to the LTS version of Node will avoid the need for that as well, or at least the need to run it as often.

I'm not closing this because you will at some point have to support Node 21 and current NPM packages.

**Comment by NorthernMan54** [comment]
I'm moving this to the Homebridge-camera-ui plugin for the SMC discussion

For your NodeJS issue, if you use the `hb-service update-node` it will include the rebuild as part of updating NodeJS.

**Comment by NorthernMan54** [comment]
Well I can't transfer this to the Homebridge-camera-ui plugin, so please raise the SMC discussion with an issue there.
