### ISSUE TITLE
Script hook when server started?

### ISSUE THREAD

**Issue by mrfatboy** [homebridge/homebridge#3456]
### Current Situation

I would like to run a script or terminal command when the server is fully running. Specifically, I want to use a curl command to send a push notification to my phone. 

Does Homebridge support this now? If so, how?

thanks

### Logs

```markdown
No logs
```

### Configuration

```json
Standard Ubuntu install
```

### Environment

- OS:
- Ubuntu
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
You can run something like this to block until the homebridge UI is running

```
until hb-service status; do sleep 10; done
```

In a bash script you could place this before curl command

**Comment by mrfatboy** [comment]
Thanks for a solution. I will try it.
