### ISSUE TITLE
Is there a way for two independent plugins to communicate with each other?

### ISSUE THREAD

**Issue by Sinclair81** [homebridge/homebridge#3457]
### Current Situation

-

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
No there isn’t a method internally to homebridge.  But you could use a tool like node-red and homebridge-automation and HomeKit-bridged to pass messages etc
