### ISSUE TITLE
CHANGELOG has not been updated since 1.5.0

### ISSUE THREAD

**Issue by jsiegenthaler** [homebridge/homebridge#3458]
### Analysis

CHANGELOG has not been updated since 1.5.0
Last entry is "[v1.5.0 (2022-06-22)](https://github.com/homebridge/homebridge/blob/latest/CHANGELOG.md#v150-2022-06-22)"

### Expected Behavior

I expect CHANGELOG to be updated with every release

### Steps To Reproduce

1. View the CHANGELOG at https://github.com/homebridge/homebridge/blob/latest/CHANGELOG.md
2. Observe that the last entry is v1.5.0

### Logs

```markdown
n/a
```

### Configuration

```json
n/a
```

### Environment

n/a

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
this will be fixed in next release
