### ISSUE TITLE
Beta version Release Note Commit history = 404 page not found

### ISSUE THREAD

**Issue by jsiegenthaler** [homebridge/homebridge#3461]
### Analysis

When updating a beta version (1.7.0-beta.0 to 1.7.0-beta.3) the Release Notes show the following:

"See the commit history for recent changes: https://github.com/homebridge/homebridge/commits/beta"

The link to https://github.com/homebridge/homebridge/commits/beta is a dead link, resulting in 404 page not found.

### Expected Behavior

I expect the links to work and a commit history to be available

### Steps To Reproduce

1. Navigate to https://github.com/homebridge/homebridge/commits/beta
2. Observe that the page is not found

### Logs

```markdown
n/a
```

### Configuration

```json
n/a
```

### Environment

- Software: 1.7.0-beta.0 upgrading to beta.3

### Process Supervisor

hb-service

**Comment by bwp91** [comment]
Hi @jsiegenthaler this should be fixed for now.

@NorthernMan54 @donavanbecker we will have to remember to keep any beta branch called `beta` as the link in the UI directs to this page.

In fact it would be better if we could get release notes to show **before** the update, much like the UI does for the UI itself and also plugins.

**Comment by jsiegenthaler** [comment]
I'll close this issue as it has been fixed
