### ISSUE TITLE
Different Node.js versions in Homebridge UI and Terminal!?

### ISSUE THREAD

**Issue by Sinclair81** [homebridge/homebridge#3463]
### Current Situation

How is it possible that Node.js version 18.18.2 is in the Homebridge UI but the terminal only outputs v18.13.0?
I always thought Node.js was installed for the entire system!
If there are 2 different Node.js installations, how can I keep them up to date in the terminal for development purposes without affecting the second installation?

Homebridge version in UI and terminal: 1.6.1! 

### Logs

```markdown
npm WARN EBADENGINE   required: { node: '^18.17.0', homebridge: '^1.6.0' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '9.2.0' }


node -v
v18.13.0
```

### Configuration

```json
-
```

### Environment

- OS: Debian GNU/Linux Bookworm (12)
- Homebridge: 1.6.1
- Node: v18.18.2 in UI / or v18.13.0 in Terminal
- npm: 9.2.0

### Process Supervisor

hb-service

### Additional Context

-

**Comment by JurgenLB** [comment]
Homebridge is probably running in a container, its one environment.
Therefore the CLI of the computer and the commands for Homebridge-terminal can give a different result

**Comment by jsiegenthaler** [comment]
@Sinclair81 
You can also update the bundled Node.js runtime independently by running:
```
# don't use sudo if running from the Homebridge UI Terminal
sudo hb-service update-node 
```
