### ISSUE TITLE
Cannot update Synology DSM 7  to Node.js 20

### ISSUE THREAD

**Issue by ruck486** [homebridge/homebridge#3473]
### Current Situation

Hi, I‘m new here. I am using Homebridge.

My System: Synology DSM OS
Node.js: v18.15.0

I want to update node.js .
I used: hb-service update-node

but my system says… (see on the picture)

what can I do to update to v20
![IMG_8900](https://github.com/homebridge/homebridge/assets/149681650/e52f5401-f5f3-4327-b854-30cdc70f295d)

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by mkz212** [comment]
Your Homebridge Image is to old to node 20. Make backup, do fresh install using newest Homebridge Image, restore from backup. Turn off all your Apple hubs until you finish.

**Comment by donavanbecker** [comment]
See [homebridge-config-ui-x#1599](https://github.com/homebridge/homebridge-syno-spk/issues/138)

**Comment by EjvindHald** [comment]
I am also facing some challenges upgrading node.js in a Docker environment
@oznu : it would be great if the [Dockerhub](https://hub.docker.com/r/oznu/homebridge/) would be updated to newest UI + Node.js. 
Thanks.

**Comment by NorthernMan54** [comment]
@EjvindHald We moved the docker image to homebridge/homerbidge in the spring of 2023.  It is updated there

**Comment by EjvindHald** [comment]
> @EjvindHald We moved the docker image to homebridge/homerbidge in the spring of 2023. It is updated there

Thanks for your reply, @NorthernMan54 . I have recreated my Docker instances from this new location, and it is correct that the node.js version is updated there. This enables me to upgrade Homebridge UI + Homebridge server, which is not latest version in current image on homebridge/homerbidge.

**Comment by NorthernMan54** [comment]
@EjvindHald - We are just waiting for the current release levels to stabilize, then will be refreshing the images.  Don't want to release something with issues.
