### ISSUE TITLE
Unable to update to 1.7.0

### ISSUE THREAD

**Issue by aatifk** [homebridge/homebridge#3480]
### Current Situation

I'm trying to update to version 1.7.0 from 1.6.1 but getting the following message. Node version is 20.9.0 according to Homebridge UI. Can't figure out how to fix this. Any help will be appreciated.

USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save homebridge@1.7.0

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /nonexistent
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/nonexistent'
npm ERR!  [Error: EACCES: permission denied, mkdir '/nonexistent'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/nonexistent'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! Log files were not written due to an error writing to the directory: /nonexistent/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal

Operation failed. Please review log for details.

### Logs

```markdown
Log doesn't show anything.
```

### Configuration

```json
Not a config issue
```

### Environment

- OS: Debian 12
- Software: 1.6.1
- Node: 21.1.0
- npm: 10.2.0

### Process Supervisor

hb-service

**Comment by akod1ng** [comment]
Same as above! on Ubuntu:

```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /nonexistent
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/nonexistent'
npm ERR!  [Error: EACCES: permission denied, mkdir '/nonexistent'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/nonexistent'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! Log files were not written due to an error writing to the directory: /nonexistent/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

**Comment by akod1ng** [comment]
I made a settings backup and completely removed homebridge, reinstalled, restored backup and than was able to apply the update.

**Comment by adispenza** [comment]
I ran into the same thing trying to update via the UI, but I was able to get it to work by ssh-ing in and running sudo `apt-get update && sudo apt-get upgrade`. Oddly enough, it downgraded node to 18.18.2 when I was on 20.x.x before. `sudo hb-service update-node` got that back to the proper version.

**Comment by NorthernMan54** [comment]
@adispenza That is the expected behaviour, as the apt package includes NodeJS
