### ISSUE TITLE
Sorting Television Inputs

### ISSUE THREAD

**Issue by maxileith** [homebridge/homebridge#3481]
### Current Situation

Hi,

I am developing a plugin and currently looking for a way to sort the inputs of a television device, see https://github.com/maxileith/homebridge-appletv-enhanced/issues/17.

Do you have any suggestions for that. I could only find the [DisplayOrder](https://developers.homebridge.io/#/characteristic/DisplayOrder) Characteristic but no useful documentation on how to use that. Is it event for setting an order of the inputs?

Thanks in advance.

### Logs

```markdown
no logs
```

### Configuration

```json
no configuration
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
[NodeJS#644](https://github.com/homebridge/HAP-NodeJS/issues/644)

**Comment by maxileith** [comment]
Thank you for that hint.
