### ISSUE TITLE
[Help] My homebridge.local now show Aria2. How can I take homebridge UI back ?

### ISSUE THREAD

**Issue by mkizzle2906** [homebridge/homebridge#3482]
### Current Situation

My homebridge.local now show Aria2 instead of Homebridge UI, even my Pi ip address also so this. Homebridge works normally in the background but I can't access it UI through homebridge.local & ip address. How can I take homebridge UI back ?

<img width="1792" alt="Screen Shot 2023-11-07 at 14 53 01" src="https://github.com/homebridge/homebridge/assets/32402155/85c4eb9d-7d00-4996-82e6-daf763580d88">

### Logs

```markdown
.
```

### Configuration

```json
.
```

### Environment

- OS: Pi
- Software:
- Node: 18.18.2
- npm: 9.6.4

### Process Supervisor

hb-service

**Comment by maxtm** [comment]
Think something may have changed in your port forwarding/mDNS settings. You can access it by adding :8581 to the address, such as homebridge.local:8581 as this is the port Homebridge listens on.

**Comment by mkizzle2906** [comment]
> Think something may have changed in your port forwarding/mDNS settings. You can access it by adding :8581 to the address, such as homebridge.local:8581 as this is the port Homebridge listens on.

I think I broke Nginx, it has some problem so I uninstall and reinstall, but after reinstall it can't run. I don't see folder /etc/nginx/ in my pi. Do you know how to fix it ?
