### ISSUE TITLE
impossible to update nodeJS

### ISSUE THREAD

**Issue by cinaxx** [homebridge/homebridge#3483]
### Analysis

Dear all,
I can't update the NodeJS version on my HomeBrige Debian.
When I follow the procedure i have an error

### Expected Behavior

hb-service update-node

### Steps To Reproduce

hb-service update-node

### Logs

```markdown
root@home-homebriedge-01:/# hb-service update-node
ℹ Updating Node.js from v16.20.2 to v20.9.0...
ℹ Updating from NodeSource...
Atteint :1 http://security.debian.org/debian-security buster/updates InRelease
Atteint :2 http://deb.debian.org/debian buster InRelease
Atteint :3 http://deb.debian.org/debian buster-updates InRelease
Réception de :4 https://deb.nodesource.com/node_20.x nodistro InRelease [12,1 kB]
Err :4 https://deb.nodesource.com/node_20.x nodistro InRelease
  Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 2F59B5F99B1BE0B4
Lecture des listes de paquets... Fait
W: Erreur de GPG : https://deb.nodesource.com/node_20.x nodistro InRelease : Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 2F59B5F99B1BE0B4
E: Le dépôt https://deb.nodesource.com/node_20.x nodistro InRelease n'est pas signé.
N: Les mises à jour depuis un tel dépôt ne peuvent s'effectuer de manière sécurisée, et sont donc désactivées par défaut.
N: Voir les pages de manuel d'apt-secure(8) pour la création des dépôts et les détails de configuration d'un utilisateur.
✖ Failed to update Node.js: Command failed: apt-get update --allow-releaseinfo-change && sudo apt-get install -y ca-certificates curl gnupg
```

### Configuration

```json
hb-service update-node
```

### Environment

- OS:  Linux home-homebriedge-01 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
- Software:  [v1.6.1]
- Node: v16.20.2
- npm: 8.19.4

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
This is more then likely due to you still being on buster

**Comment by cinaxx** [comment]
what should I do in this case. is there a procedure?

**Comment by donavanbecker** [comment]
Update to bookworm. I would recommend doing a homebridge backup so that you can restore if you run into any issues.

**Comment by cinaxx** [comment]
Apt-get update or another

**Comment by donavanbecker** [comment]
https://duckduckgo.com/?q=debian+update+from+buster+to+bookworm&t=osx&ia=web

**Comment by cinaxx** [comment]
same same 

root@home-homebriedge-01:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster



root@home-homebriedge-01:~# sudo hb-service update-node
ℹ Updating Node.js from v16.20.2 to v20.9.0...
ℹ Updating from NodeSource...
Atteint :1 http://security.debian.org bullseye-security/updates InRelease
Atteint :2 http://deb.debian.org/debian bullseye InRelease
Atteint :3 http://deb.debian.org/debian bullseye-updates InRelease
Atteint :4 http://deb.debian.org/debian bullseye-backports InRelease
Réception de :5 https://deb.nodesource.com/node_20.x nodistro InRelease [12,1 kB]
Err :5 https://deb.nodesource.com/node_20.x nodistro InRelease
  Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 2F59B5F99B1BE0B4
Lecture des listes de paquets... Fait
W: Erreur de GPG : https://deb.nodesource.com/node_20.x nodistro InRelease : Les signatures suivantes n'ont pas pu être vérifiées car la clé publique n'est pas disponible : NO_PUBKEY 2F59B5F99B1BE0B4
E: Le dépôt https://deb.nodesource.com/node_20.x nodistro InRelease n'est pas signé.
N: Les mises à jour depuis un tel dépôt ne peuvent s'effectuer de manière sécurisée, et sont donc désactivées par défaut.
N: Voir les pages de manuel d'apt-secure(8) pour la création des dépôts et les détails de configuration d'un utilisateur.
✖ Failed to update Node.js: Command failed: apt-get update --allow-releaseinfo-change && sudo apt-get install -y ca-certificates curl gnupg

**Comment by NorthernMan54** [comment]
Reading this message, it looks like your node source setup is having issues.  Please take a look at this - https://github.com/nodesource/distributions#installation-instructions

Am thinking something is incorrect
