### ISSUE TITLE
Update Node version shown in Wiki from v12 to v20

### ISSUE THREAD

**Issue by jsiegenthaler** [homebridge/homebridge#3497]
### Current Situation

Wiki page 
https://github.com/homebridge/homebridge-config-ui-x/wiki/Homebridge-Service-Command#update-nodejs
shows an example referencing a very old version of node 
`sudo hb-service update-node 12.18.1`

### Proposed Change

Update the example to show a much more current node version: 
`sudo hb-service update-node 20.10.0`

**Comment by jsiegenthaler** [comment]
Bump

**Comment by bwp91** [comment]
Done!
