### ISSUE TITLE
H706A Support

### ISSUE THREAD

**Issue by Route105** [homebridge/homebridge#3498]
### Current Situation

looking to add my new H706A LED Lights

### Proposed Change

H706A led lights support 

### Additional Context

[Front LED Lights] is not currently supported, do create a Github issue with the following info:
{"ip":"192.168.1.210","device":"36:99:F1:F1:A7:4B:D6:80","sku":"H706A","bleVersionHard":"3.04.01","bleVersionSoft":"1.00.14","wifiVersionHard":"1.04.01","wifiVersionSoft":"1.01.17","httpInfo":{"groupId":0,"device":"36:99:F1:F1:A7:4B:D6:80","sku":"H706A","spec":"","versionHard":"3.04.01","versionSoft":"1.00.14","deviceName":"Front LED Lights","deviceExt":{"deviceSettings":"{\"wifiName\":\"DMB #41 (2G)\",\"address\":\"F1:F1:A7:4B:D6:80\",\"bleName\":\"Govee_H706A_D680\",\"topic\":\"GD/8d0e8155b27869a8bb1c047b29c69a5b\",\"wifiMac\":\"60:74:F4:7D:72:CD\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.01.17\",\"wifiHardVersion\":\"1.04.01\",\"ic\":60,\"secretCode\":\"f2Hx8adL1oA=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"dspVersionSoft\":\"13\",\"segmentCount\":9,\"sku\":\"H706A\",\"device\":\"36:99:F1:F1:A7:4B:D6:80\",\"deviceName\":\"Front LED Lights\",\"versionHard\":\"3.04.01\",\"versionSoft\":\"1.00.14\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/110c816f749f75640260511c333a1065-add_list_type_device_706a.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/8e57eab8d1c8c6d9f280be7e4460b0d2-706a_light_title_on.png\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/a4e9d925c3c788fc25adde52e44349a8-706a_light_title_off.png\",\"ext\":\"\",\"ic\":120}"},"pactType":1,"pactCode":1,"share":0,"goodsType":180,"attributesId":49,"supportScene":0},"model":"H706A","deviceName":"Front LED Lights","isLANDevice":true}

**Comment by maxileith** [comment]
What does this has to do with homebridge itself? I am pretty sure that the log message wants you to open the issue at the repository of the corresponding plugin ...

**Comment by Route105** [comment]
sorry i put it in the wrong place, did not know how to remove it
