### ISSUE TITLE
Change Dimmer into Switch?!

### ISSUE THREAD

**Issue by KSchimmel1992** [homebridge/homebridge#3499]
### Current Situation

Hi,
is it possible to Change the Type of „Lüfter“ (it‘s a Fan) from Lights to AC?

The Device is a Shelly Dimmer.

It would be also ok if I can change it in Homebridge to a switch because the Dimmer runs every time on 80%. 

Thanks for any advice! 
Kevin 

<img width="331" alt="Bildschirmfoto 2023-11-26 um 15 18 26" src="https://github.com/homebridge/homebridge/assets/101293630/5be40eae-1b80-4d0e-9008-d5f0e5a63b2e">

### Logs

```markdown
Not needed
```

### Configuration

```json
???
```

### Environment

- OS: iOs 
- Software: Homebridge
- Node: last stable
- npm: ?

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
This is a question more geared to the plugin developer, as the device type is set by the plugin

**Comment by jsiegenthaler** [comment]
@KSchimmel1992 : your issue needs to be directed to the plugin developer, not to the Homebridge platform. Can you please close this issue, as this is not a Homebridge issue.

**Comment by bwp91** [comment]
Closing this, as @NorthernMan54 and @jsiegenthaler have correctly stated, that this is a feature that the plugin developer would need to implement.
