### ISSUE TITLE
latest update breaks home bridge, can't connect to web GUI anymore

### ISSUE THREAD

**Issue by geigerzaehler242** [homebridge/homebridge#3505]
### Analysis

i just performed an update with home bridge and now i can't access the local web page anymore to check status or anything

### Expected Behavior

applying an update should not break anything

### Steps To Reproduce

perform the update on a raspberry pi platform

### Logs

```markdown
no logs
```

### Configuration

```json
no config
```

### Environment

- OS: raspian
- Software:
- Node: 18x
- npm:

### Process Supervisor

hb-service

### Additional Context

none

**Comment by ivanvorobei** [comment]
same, can't run gui after update. no see any log

**Comment by castle-rocker-99** [comment]
I am having the same issue and cannot even roll back. I am running on an Ubuntu Server.

**Comment by ivanvorobei** [comment]
Solution which work for me. Via `pi` user run 

```
sudo hb-config
```

and choose Update HomeBridge
<img width="567" alt="Screenshot 2023-12-07 at 23 31 46" src="https://github.com/homebridge/homebridge/assets/10995774/e0e72e9b-ee8a-44dc-b730-57d04379830d">

**Comment by ivanvorobei** [comment]
I tried again install new GUI update and its crashed again. So bug stable and critical. 

Now way with update home bridge not work, I think its related to rebuild. No I can't install update and rebuild and its hold process.

**Comment by jonnyborbs** [comment]
Please also see https://github.com/homebridge/homebridge-config-ui-x/issues/1912 - lots of discussion over here as well. Everything has kinda gone to heck in an instant 😄 any help is appreciated.

**Comment by jonnyborbs** [comment]
https://github.com/homebridge/homebridge-config-ui-x/issues/1912#issuecomment-1846093839

**Comment by geigerzaehler242** [comment]
home bridge folder is empty after the update. the GitHub links for raspberry pi seem broken also.

**Comment by jonnyborbs** [comment]
Also while troubleshooting, I discovered the wiki is all 404s...

https://github.com/homebridge/homebridge/issues/3507

**Comment by brain-slug2102** [comment]
Refreshing the page after the update I got “ {"statusCode":500, "message" : "Internal server
error"}” now I get nothing at all

running sudo hb-service -D or -V shows “ /usr/bin/env: 'node' :No such file or directory”

there are no new logs to triage since the update

**Comment by jonnyborbs** [comment]
This appears to have been resolved by an updated release of the homebridge-ux plugin, check out the issue I crosslinked for more details.
