### ISSUE TITLE
The wiki is entirely broken links - everything 404s

### ISSUE THREAD

**Issue by jonnyborbs** [homebridge/homebridge#3507]
### Current Situation

All of the links on the Homebridge wiki currently 404

### Logs

```markdown
See https://github.com/homebridge/homebridge/wiki

Click any link.
```

### Configuration

```json
NA
```

### Environment

NA

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
I just checked and the wiki is working ?  Are you having a local issue ?

**Comment by jonnyborbs** [comment]
Wild. I see the same now. GitHub Pages was throwing a 404 on every single link, I swear 😅

Perhaps it was having a moment itself. Thanks for replying though!

**Comment by NorthernMan54** [comment]
No problem, have a great night

**Comment by donavanbecker** [comment]
@jonnyborbs It was happening to me too, so I wonder something happened with GitHub which caused this and the issue with the Homebridge UI update.
