### ISSUE TITLE
Everything died

### ISSUE THREAD

**Issue by lottomotto** [homebridge/homebridge#3511]
### Current Situation

1. Hello. I have the synology app installed (not docker anymore)
2. So I recently update to Version: 7.2.1-69057 Update 3 on my Ds1520+
I think because of that nothing is working anymore. I cannot access with myip:8581 (this site cannot be reached)
in Homekit the hub is not responding
when I ssh into the nas I can find homebridge folder but log doesn't produce new data:
In Package center it looks like the service is running, same as Node.Js V18.
I stopped and restarted the service... rebooted.... nothing changed...
What should I do?

### Logs

```markdown
No logs produced
```

### Configuration

```json
"bridge": {
        "name": "Homebridge XXXX",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 51022,
        "pin": "XXX-XX-XXX",
        "advertiser": "avahi"
    },
    "accessories": [
        {
            "name": "Roborock V7 Max",
            "ip": "192.168.86.41",
            "token": "523778306a726c75316762434a495872",
            "serviceType": "fan",
            "waterBox": false,
            "dustBin": false,
            "dustCollection": false,
            "disableCareServices": false,
            "silent": false,
            "pause": true,
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "goTo": false,
            "goToWord": "go to coordinates",
            "goToX": 25500,
            "goToY": 25500,
            "dock": true,
            "cleanword": "cleaning",
            "roomTimeout": 0,
            "autoroom": false,
            "rooms": [
                {
                    "name": "kittchen",
                    "id": 1
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "sessionTimeout": 50000,
            "platform": "config"
        },
        {
            "refreshToken": XXX>
            "showPanicButtons": true,
            "platform": "Ring"
        },
        {
            "refreshToken": XXX,
            "options": {
                "ffmpegCodec": "libx264",
                "streamQuality": 3,
                "alertCheckRate": 10,
                "alertCooldownRate": 180,
                "importantOnly": true,
                "motionDetection": true,
                "streamingSwitch": true,
                "announcementsSwitch": true,
                "audioSwitch": true,
                "fieldTest": false
            },
            "_bridge": {
                "username": "XXX",
                "port": 55254
            },
            "platform": "Nest-cam"
        },
        {
            "name": "SmartThings-v2",
            "app_url": "https://graph-na04-useast2.api.smartthings.com:443/api/smartapps/installations/",
            "app_id": "XXX",
            "access_token": "XXX",
            "polling_seconds": 5,
            "update_method": "direct",
            "direct_ip": "192.168.86.56",
            "direct_port": 8000,
            "temperature_unit": "C",
            "validateTokenId": false,
            "logConfig": {
                "debug": false,
                "showChanges": true,
                "hideTimestamp": true,
                "hideNamePrefix": true,
                "file": {
                    "enabled": true,
                    "level": "good"
                }
            },
            "platform": "SmartThings-v2"
        },
        {
            "clientId": "XXX",
            "clientSecret": "XXX",
            "projectId": "XXX",
            "refreshToken": XXX,
            "subscriptionId": "XXX",
            "vEncoder": "libx264",
            "fanDuration": 900,
            "_bridge": {
                "username": "XXX",
                "port": 46458
            },
            "platform": "homebridge-google-nest-sdm"
        }
    ],
    "disabledPlugins": [
        "homebridge-gogogate2",
        "homebridge-xiaomi-roborock-vacuum",
        "homebridge-nest-cam"
    ]
}
```

### Environment

- OS: Synology NAS 7.2.1-69057 Update 3 
- Software: from syno repo 3.0.20
- Node: 18.15.0-1008
- npm: 10.1.0

### Process Supervisor

hb-service

**Comment by bstillitano** [comment]
Same thing has happened to me on a QNAP server running docker image node version v20.10.0 and homebridge v1.7.0

I can control all the accessories via the homebridge UI but in HomeKit they are all showing "not responding"

**Comment by bstillitano** [comment]
I fixed this for a few minutes by removing all accessories from the Home app and performing "Remove all cached accessories" in the homebridge settings. I had to re-add every single camera, light, fan, blind, aircon, automation, scene, etc but they were all briefly working.

Unfortunately after about 20 mins or so, it went back to "No response"

**Comment by bstillitano** [comment]
Digging further it would appear that one of my plugins was causing things to die. The two that I've disabled were both LG thinq/webos plugins so presumably something has become incompatible on that front. Having disabled those two, my lights and speakers are all working fine after a clean homebridge install and reconfiguring everythitng.

**Comment by diepeterpan** [comment]
Similar experience yesterday, still not 100% sure which plugin caused it or whether 100% fixed, currently still running Webos TV but I did remove and added the TV again to Apple Home, also downgraded the plugin 2 versions, and this time I added it as a separate bridge.  Disabled some NUT UPS plugins which I added lately.  Had to clear the device cache from Homebridge in the app UI menu and all working now.  Restarted Homebridge a couple of times to make 100% sure it's working as it sometimes appears to and on the second or 3rd restart all plugins died again. Later this week when stable I will upgrade the Webos plugin and test stability to get some more clarity; also in the new year add the NUT UPS's back again.

**Comment by JurgenLB** [comment]
If you use child-bridges only the child-bridge will fail and not the whole homebridge. And you can restart a child-bridge separately

**Comment by bstillitano** [comment]
> If you use child-bridges only the child-bridge will fail and not the whole homebridge. And you can restart a child-bridge separately 

It's not a case of the bridge failing, in-fact homebridge is still able to control ALL of the accessories without issue. 

The issue is that we're seeing a plugin bring down the Home app on iOS/macOS. The accessories and homebridge are still working fine.

**Comment by diepeterpan** [comment]
> > If you use child-bridges only the child-bridge will fail and not the whole homebridge. And you can restart a child-bridge separately
> 
> It's not a case of the bridge failing, in-fact homebridge is still able to control ALL of the accessories without issue.
> 
> The issue is that we're seeing a plugin bring down the Home app on iOS/macOS. The accessories and homebridge are still working fine.

Agree, on my PC in the Homebridge UI I could turn the lights on and off but on IOS and MacOS all things were not responding. Only after clearing the accessory cache in Homebridge and restarting were they functional in IOS and MacOS.

**Comment by bwp91** [comment]
Hi @lottomotto is this still an issue? or did you get this resolved?
