### ISSUE TITLE
Getting ENETUNREACH intermittently (since update to 1.7.0 ?)

### ISSUE THREAD

**Issue by champagnealexandre** [homebridge/homebridge#3517]
### Analysis

Since a recent update to 1.7.0 (which might be a coincidence—or not) Homebridge intermittently throws `ENETUNREACH` errors.

```
Unhandled rejection Error: send ENETUNREACH 192.168.0.50:8899
    at doSend (node:dgram:717:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:464:18)
    at afterDns (node:dgram:663:5)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

However the device is clearly reachable:

```
PING 192.168.0.50 (192.168.0.50): 56 data bytes
64 bytes from 192.168.0.50: icmp_seq=0 ttl=255 time=80.002 ms
```

Homebridge is bound to `en0`, which is my LAN. Nothing changed recently.

Rebooting Homebridge (temporarily) fixes the issue, but it has happened every day now for a couple days. These `ENETUNREACH` errors affect several accessories from multiple plugins.

### Expected Behavior

Not getting this error.

### Steps To Reproduce

Nothing specific besides controlling an accessory.

### Logs

```markdown
See above.
```

### Configuration

```json
Nothing has been changed in my config for months.
```

### Environment

- OS: macOS Sonoma 14.2 (23C64)
- Software: 1.7.0
- Node: v21.1.0
- npm: 10.2.3

### Process Supervisor

hb-service

**Comment by bwp91** [comment]
Hi just placing some context here. 

There really was not much between the v1.6 and v1.7 of Homebridge, except for dependency updates.

The changes are here:
https://github.com/homebridge/homebridge/commit/50f91541bc8731ed0c794f1370d9b76f49443d11

Will keep this issue open for now, @champagnealexandre have you managed to fix this at all?

**Comment by champagnealexandre** [comment]
After the last reboot the issue hasn’t presented itself. I was still on the lookout since the issue persisted for some time but I guess we can close this for now. I’ll reopen if it arises again.
