### ISSUE TITLE
Built in Cloudflare Tunnel Access

### ISSUE THREAD

**Issue by abarbarich** [homebridge/homebridge#3518]
### Current Situation

A future addition that would be nice would be a Cloudflared token input build into to the UI.

I have manually installed and run Cloudflared in the docker image, however, anytime the server restarts it breaks the Cloudflared tunnel and it needs to be removed and reinstalled. I even added this to the start-up script however it breaks after a restart.

 I normally use DDNS and port forwarding to access my instances from anywhere however my new Internet provider serves IP address and Internet access via a methodology that breaks DDNS functionality, and Fixed IPS are becoming expensive now.

### Proposed Change

Add a Cloudflared installation to the docker image and integrate an input for the Cloudflare token in the U.I. to allow for easy tunnelling to your Homebridge Instance.

**Comment by donavanbecker** [comment]
This could be done with a plugin. Let me see if I can do it.

**Comment by donavanbecker** [comment]
Working on this: https://github.com/donavanbecker/homebridge-cloudflared-tunnel

Should have something soon

**Comment by donavanbecker** [comment]
[v.1.0.0 Released](https://github.com/donavanbecker/homebridge-cloudflared-tunnel)

**Comment by rayenking** [comment]
> [v.1.0.0 Released](https://github.com/donavanbecker/homebridge-cloudflared-tunnel)

I am sorry I want to ask 

how to use it ? I mean is it possible to scan the qr outside the local connection ?

**Comment by donavanbecker** [comment]
First why would you scan a QR code? And second the plugin allows you to access your UI outside of your network with cloudflare
