### ISSUE TITLE
Automatic restart after network change/ router reboot

### ISSUE THREAD

**Issue by thejae** [homebridge/homebridge#3519]
### Current Situation

This is a very similar ticket to #1948

Am running homebridge through a Synology package. Every time the network goes out or when I restart my router, homebridge would be stuck in a limbo state - unable to connect to any devices since their IPs have been refreshed after the network reboot.

### Proposed Change

Automatically reload all devices after a network change

### Additional Context

Node.js Version v18.15.0
Homebridge UI 4.54.1
Homebridge Synology package 3.0.20

**Comment by JurgenLB** [comment]
I have my devices on a DHCP-static lease, so they have always the same IP. Just program your router this way is a better solution then asking homebridge to fors the IP-addresses, your router is the master in the network not homebridge.

**Comment by bwp91** [comment]
Hi @thejae 

by this comment

> unable to connect to any devices since their IPs have been refreshed

are you referring to devices that are managed by plugins?

**Comment by thejae** [comment]
> Hi @thejae
> 
> by this comment
> 
> > unable to connect to any devices since their IPs have been refreshed
> 
> are you referring to devices that are managed by plugins?

Yes correct, referring to the devices that are managed by plugins.

I think I'll try @JurgenLB's method of setting a DHCP-static lease if there's no easy workaround.

**Comment by grzech1991** [comment]
I have the same problem, after restarting the router homebridge falls - iphone does not see devices in the house at all. When it restarts the homebridge then it starts to respond.

Anyone have any idea how to fix this?
