### ISSUE TITLE
no response / Control4 Plugin

### ISSUE THREAD

**Issue by jkoopmann** [homebridge/homebridge#3521]
### Current Situation

Running Homebridge on Unraid. Bridge mode (host mode did not do the trick either). Only plugin: Control4

Control4 is speaking to home bridge like a charm. I can find and install bridge and devices on my home app. However the devices all show as "no response".

homebridge is bound to 0.0.0.0
It does advertise the bridges via mDNS including correct IP and port (and the ports are listened on). I disabled IGMP snooping everywhere.

The devices show (and react) correctly in the homebridge GUI. Only the no response issue. Any idea where to look?

### Logs

```markdown
[12/29/2023, 1:48:06 PM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge A624) is running on port 51682.
[12/29/2023, 1:48:06 PM] [Control4 Home Connect FAA8] Launched child bridge with PID 5086
[12/29/2023, 1:48:06 PM] Registering platform 'homebridge-control4-home-connect.Control4HomeConnect'
[12/29/2023, 1:48:06 PM] [Control4 Home Connect FAA8] Loaded homebridge-control4-home-connect v1.2.1 child bridge successfully
[12/29/2023, 1:48:07 PM] Loaded 3 cached accessories from cachedAccessories.2A5F331CB360.
[12/29/2023, 1:48:07 PM] [Control4 Home Connect FAA8] Loading accessory from cache: Esszimmer Essen
[12/29/2023, 1:48:07 PM] [Control4 Home Connect FAA8] Loading accessory from cache: Küche dunkel
[12/29/2023, 1:48:07 PM] [Control4 Home Connect FAA8] Loading accessory from cache: Küche kochen
[12/29/2023, 1:48:07 PM] Publishing bridge accessory (name: Control4 Home Connect FAA8, publishInfo: {
  username: '2A:5F:33:1C:B3:60',
  port: 43254,
  pincode: '***-**-***',
  category: 2,
  bind: [ '0.0.0.0', [length]: 1 ],
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: 'avahi'
}).
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge A624",
        "username": "XXX",
        "port": 51682,
        "pin": "YYY",
        "advertiser": "avahi",
        "bind": [
            "0.0.0.0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "_bridge": {
                "port": 43254,
                "username": "XXX"
            },
            "name": "Control4 Home Connect FAA8",
            "platform": "Control4HomeConnect",
            "port": 35570
        }
    ]
}
```

### Environment

- OS: unraid / Docker Ubuntu Focal Fossa (20.04.5 LTS)
- Software:
- Node: v18.13.0
- npm:

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

oznu/homebridge:ubuntu

**Comment by jkoopmann** [comment]
Just changed image to homebridge/homebridge and updated node.js to v20.10.0. No change.

**Comment by NorthernMan54** [comment]
If the devices are working correctly from the Homebridge UI, you likely have an issue with the networking between your homebridge instance and your iPhone.  Please review your network configuration

**Comment by jkoopmann** [comment]
Thanks. I totally agree (unless of course the one plugin is disturbing the status. Some seem to have posing these issues in the past according to google). 

I have reviewed it for hours. mDNS seems accurate. Ports are open. Homebridge is listening. IGMP snooping is of on switches and WLAN... Hence my post. Even if it is a network issue I am afraid I need a few external ideas where to look.

**Comment by NorthernMan54** [comment]
Typically a plugin or homebridge instance not responding will cause not responding issues, hence these type of things showing up regularly.  If you don't think it is network, have you tried resetting your HomeKit Pairing ? - https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#reset-pairingaccessories
