### ISSUE TITLE
Compatibility with bun 1.0

### ISSUE THREAD

**Issue by volschin** [homebridge/homebridge#3526]
### Current Situation

Bun states to be a drop in replacement for nodejs. I found no information whether homebridge is able to run on bun.

### Proposed Change

Bun ([https://bun.sh/guides/ecosystem/docker](url=https://bun.sh/guides/ecosystem/docker)) is a blazing fast new replacement for node.js. Has someone checked the compatibility? 
It would be interesting to have it in the support matrix.

**Comment by bukhalo** [comment]
bun (and Deno by the way) do not have a compatibility layer for the node:dgram module and therefore will not be able to run homebridge

**Comment by volschin** [comment]
Thank you for your answer. I have searched for dgram status and it seems a lot of interest in having this.
https://github.com/oven-sh/bun/issues/1630 and hopefully integration of this pr https://github.com/oven-sh/bun/pull/7271

**Comment by volschin** [comment]
Up.

**Comment by hjdhjd** [comment]
We don't currently have any intention to support anything beyond the current LTS releases of Node. If someone wants to undertake an effort to create a PR that's maintainable on an ongoing basis with a minimum of effort, you're welcome to do so and we'll assess - but we are not committing to incorporating it at this time.

Thanks for the request.
