### ISSUE TITLE
Plugin does not appear when searching

### ISSUE THREAD

**Issue by kakopappa** [homebridge/homebridge#3528]
### Current Situation

Hi guys,

Our plugin: sinricpro does not appear when searching. It's already in npm.  just wondering whether we missed something. 

https://www.npmjs.com/package/homebridge-sinricpro
https://registry.npmjs.org/homebridge-sinricpro

### Logs

```markdown
hb-service logs do not show anything related to the search.
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge C78A",
        "username": "xxx",
        "port": 51821,
        "pin": "xxxx",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        } 
    ]
}
```

### Environment

- OS: Linux 6.1.0-rpi7-rpi-v8 arm64
- Software: Homebridge UI v4.53.0 , Homebridge v1.7.0
- Node: v18.18.2
- npm: 

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
To your package.json add the keyword "homebridge-plugin" - https://github.com/homebridge/homebridge-plugin-template/blob/fe5bb73eee3efa007f137b9268e9a6c59b88d9ef/package.json#L27

**Comment by kakopappa** [comment]
that worked. thanks
