### ISSUE TITLE
HomePod Mini error when Homebridge is connected 

### ISSUE THREAD

**Issue by gamlielalon1983** [homebridge/homebridge#3532]
### Current Situation

Hi,

when trying to add new HomePod mini to home its stuck on setting up and when I remove the Homebridge from home  all working.

Any known issues with or configuration change I can add to solve it

### Logs

```markdown
07/01/2024, 10:29:02] Loaded 0 cached accessories from cachedAccessories.
[07/01/2024, 10:29:02] ---
[07/01/2024, 10:29:04] Loaded plugin: homebridge-config-ui-x@4.54.2
[07/01/2024, 10:29:04] Registering platform 'homebridge-config-ui-x.config'
[07/01/2024, 10:29:04] ---
```

### Configuration

```json
"bridge": {
        "name": "Homebridge 4CAB",
        "username": "XXXXXXXXX",
        "port": XXXXXXXXX,
        "pin": "XXXXXXXXXX",
        "bind": [
            "wlan0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": XXXXXXXX,
            "platform": "config"
        },
```

### Environment

- OS: RPI 11 
- Software: Homebridge v4.54.2 
- Node:v20.10.0
- npm:10.2.3

### Process Supervisor

hb-service

### Additional Context

RPI 4

**Comment by donavanbecker** [comment]
Do you have any plugins installed when adding the HomePod mini? I have never heard of this happening

**Comment by gamlielalon1983** [comment]
Hi 

Yes in have some plugins not a lot 
Hikvision nvr
Risco alarms
Tadiran ac
EWeLink 
Switcher platform
Homebridge Tuya

**Comment by donavanbecker** [comment]
Are any of them in child bridges?

**Comment by gamlielalon1983** [comment]
No but I'll try to remove one by one and see if one of them is causing and update

**Comment by donavanbecker** [comment]
if you are removing them, you might as well add them back as child bridges so that in the future you can disable the child bridge to troubleshoot easier.

**Comment by gamlielalon1983** [comment]
Wow thanks for the tip.
Removing the risco and Tuya helped me I guess the risco maybe cause it was the only one not verified

**Comment by donavanbecker** [comment]
Here is info on [Child Bridges](https://github.com/homebridge/homebridge/wiki/Child-Bridges)

**Comment by gamlielalon1983** [comment]
Thanks I'll read about 

Appreciated
