### ISSUE TITLE
Not able to "Log in"

### ISSUE THREAD

**Issue by skittle0764** [homebridge/homebridge#3538]
### Current Situation

first: i didnt know that you needed to on in on your own homebride server (im usin it via umbrel). firstly: i dont know how to log in cause i created an account on homebridge.ca and the log in details dont work on my gui. pls help.

### Logs

```markdown
idk
```

### Configuration

```json
idk
```

### Environment

- OS: UmbrelOS
- Software: 1.7.0
- Node: idk
- npm: idk

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Homebridge.ca is used as the cloud backend from the homebridge-Alexa plugin and not connected to the homebridge gui at all.
