### ISSUE TITLE
Add / amend docs for using `avahi` advertiser from Docker

### ISSUE THREAD

**Issue by bdruth** [homebridge/homebridge#3539]
### Current Situation

The docs on the wiki for advertiser don't really provide information on how to configure homebridge to use `avahi` from a docker container if the host is already setup w/ `avahi`.

### Proposed Change

Add some aspect of (this is docker compose specific):

1. mount `dbus` and `avahi-daemon/socket` volumes to homebridge container
```
    volumes:
      - /opt/homebridge:/homebridge
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
```
2. disable (please enhance if there's a better way!) apparmor so container can use `dbus`
```
    security_opt:
      - apparmor:unconfined
```

### Additional Context

Without the `apparmor:unconfined`, I got errors like this:

```

**Comment by donavanbecker** [comment]
@bdruth I just gave you access to the wikis. Please update and let me know when you are done. Thanks!

**Comment by bdruth** [comment]
Roger that, thanks!

**Comment by bdruth** [comment]
Done! https://github.com/homebridge/homebridge/wiki/mDNS-Options

Lemme know if there's edits you would like to see. Thanks again!

**Comment by donavanbecker** [comment]
Looks good to me! Thanks
