### ISSUE TITLE
Repository version out of sync with latest release and Node version

### ISSUE THREAD

**Issue by lmjabreu** [homebridge/homebridge#3540]
### Analysis

Running `apt info homebridge` displays an older version (1.1.6), although `apt upgrade homebridge` does seem to update to the correct version (1.7.0), but also downgrades Node to v18 if already upgraded to v20 via `hb-service node-update`.

### Expected Behavior

The package info in the official repo should be in sync with the latest release version on GH (1.7.0). I'd also expect the Node version to remain unchanged when upgrading, unless it's lower than the required version (forced upgrade).

Additionally, I suspect the node module rebuild command issued by the package install doesn't work properly, one or more of my plugins requires a manual `rpm rebuild` from the plugin dir itself whenever the node version is changed (eg `homebridge-benq-projector`).

### Steps To Reproduce

1. Run `apt info homebridge` to verify the version discrepancy between the latest official release and the repo package
1. Run `apt install homebridge` to install homebridge
2. Update Node from the current bundled v18 to v20 via `hb-service node-update`
3. Wait for a few days (until the repo gets updated, even though there hasn't been a new official release)
4. Run `apt upgrade` and observe how Node gets downgraded, and the homebridge version remains the same

### Logs

```markdown
n/a
```

### Configuration

```json
n/a
```

### Environment

- OS: Raspbian
- Software: 1.7.0
- Node: v20.11.0
- npm: 10.2.4

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
APT package is built on Node 18 and will be for the next few months.

**Comment by lmjabreu** [comment]
@donavanbecker fair enough, maybe the issue is that the package is being updated, without a new Homebridge release, and when someone upgrades their system the node version gets reverted.

I wonder how many people are getting their setup broken because of this 🤔 To be honest, the management of the Node is non-standard compared to other packages, it should be a separate package altogether, but I understand the bundling simplifies setup and maintenance.

**Comment by donavanbecker** [comment]
What would break on setups?

**Comment by donavanbecker** [comment]
The plugin you reference looks like it hasn't been updated for 3 years and is still min of node 12. So yes this could cause issues on a per plugin basis but that also tells you that that plugin could be causing problems.

**Comment by lmjabreu** [comment]
True it doesn't have the best maintenance score 😅

The issue is that going into the plugin folder and manually running npm rebuild does solve the issue, is this not what `hb-service node-update` should do for all plugins? (honestly don't know).

I haven't looked into the `homebridge-benq-projector` plugin code to be honest, is the issue that it hasn't been updated in 3 years, is it that it sets node 12 as its dependency, or is it the nature of the plugin (interaction with hardware devices, specifically serial devices, and the possible higher sensibility to this issue, whereas most other plugins are just interacting with the network). Hence my question: are there more other plugins that interact with the actual hardware being impacted by unexpected node downgrades/change and the module rebuild process? (no need to answer)

Sorry is this issue is a combination of:
- Package info <> homebridge version mismatch
- Unexpected Node downgrade on package update
- Some (okay, one) homebridge plugin requires a manual rpm rebuild when changing node versions as `hb-service node-update` doesn't suffice.
