### ISSUE TITLE
Config tab missing but direct url still working

### ISSUE THREAD

**Issue by JustAnotherIssue** [homebridge/homebridge#3549]
### Current Situation

on top left there is Homebridge / Status / Plugins / **CONFIG** / Accessories / Settings
but now out of a sudden *Config* is missing.
Strange when I call  [http://omebridge:8581/config ](url)  it is still browsable

### Logs

```markdown
could not find any relevant, no error or issue shown
```

### Configuration

```json
this is not config related
```

### Environment

- OS: docker at Ubuntu Focal Fossa (20.04.5 LTS)
- Software: Installed: v1.7.0 [UI v4.55.1]
- Node: v20.11.0
- npm: 

### Process Supervisor

Docker (Mention image name in `Additional Context`)

**Comment by donavanbecker** [comment]
It is not missing but has been moved to settings.

![image](https://github.com/homebridge/homebridge/assets/9875439/c894ba78-2026-4a65-812a-2c4c4245fbbd)

**Comment by JustAnotherIssue** [comment]
indeed! But I do hate the new possition already

**Comment by donavanbecker** [comment]
> indeed! But I do hate the new possition already

It really shouldn't be needed if you are using verified plugins.
