### ISSUE TITLE
New power consumption plugin help

### ISSUE THREAD

**Issue by socquique** [homebridge/homebridge#3550]
### Current Situation

I want to make a new plugin to receive the power consumption data from an API. What service should I use to show this kind of info?

Thanks!

### Logs

```markdown
not applicable
```

### Configuration

```json
not applicable
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by ebaauw** [comment]
There are no standard HomeKit services nor characteristics for power consumption.  Eve have defined custom variants for these, and everybody else seems to be using these as well.  See https://github.com/ebaauw/homebridge-lib/blob/main/lib/EveHomeKitTypes.js.

**Comment by socquique** [comment]
Thanks for your help!

There is any guide about how ti integrate this Eve variants using the homebridge template?
