### ISSUE TITLE
Add a way to change the detected device type in HomeKit for a switch

### ISSUE THREAD

**Issue by tomlaf** [homebridge/homebridge#3552]
### Feature Description

What is happening?

- A switch is show as a lamp in HomeKit

What you expect to happen?

- To be show as a switch or as the end device that is control by that switch

What problems would this new feature solve?

- Better integration in HomeKit, ensuring that global request (like Siri light on does trigger no light element)

**Comment by NorthernMan54** [comment]
Did you look at this in the home app?

<img width="1080" alt="image" src="https://github.com/homebridge/homebridge/assets/19808920/7a28573d-c8d6-4436-9b5d-48b2488b3c07">

**Comment by tomlaf** [comment]
This does not show in my Apple HomeKit

**Comment by NorthernMan54** [comment]
This will need to be raised against the plugin then, as the plugin specifies the device type for HomeKit.

please raise this against the plugin do the developer is aware.
