### ISSUE TITLE
Point of Contact for Raspberry Pi Imager

### ISSUE THREAD

**Issue by tdewey-rpi** [homebridge/homebridge#3553]
### Current Situation

As of release v1.8.1, I have required vendors offering operating systems via the Raspberry Pi Imager OS list to provide a named point of contact to help coordinate breaking changes to Raspberry Pi Imager and associated software.

### Logs

```markdown
N/A
```

### Configuration

```json
N/A
```

### Environment

- OS: 
- Software: Raspberry Pi Imager

### Process Supervisor

not applicable

### Additional Context

Please contact me through the Raspberry Pi contact page to establish a point of contact and the associated offers.

https://www.raspberrypi.com/contact/

**Comment by donavanbecker** [comment]
@tdewey-rpi We have reached out.
