### ISSUE TITLE
Typo in Wiki Page

### ISSUE THREAD

**Issue by jsiegenthaler** [homebridge/homebridge#3554]
### Proposed Change

`If your running an older operating system you will not be able to update...` is incorrect. 
The word "your" is spelt incorrectly.

Correct is:
`If you are running an older operating system you will not be able to update...`
or alternatively:
`If you're running an older operating system you will not be able to update...`

### Wiki Page Link

https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js#does-my-operating-system-support-an-updated-nodejs

**Comment by donavanbecker** [comment]
You should be able to update the wiki now, once done let me know.

**Comment by jsiegenthaler** [comment]
@donavanbecker Thanks, typo fixed, I'll close this issue
