### ISSUE TITLE
Where is the menu entry "Konfiguration" for faster open the config.json?

### ISSUE THREAD

**Issue by drheck** [homebridge/homebridge#3559]
### Analysis

The newest version has no fast entries for some things, which exists in homebridge-config-ui-x v4.53.0:
1. No menu entry "Konfiguration" for faster open the config.json? - Why?
2. If you click on the i button there comes an info dialog where you can click a further button to go to the git. - Why this dialog and no direct way to the git?

Thank you for a short answer or adding the missing points.

kind regards,
Peter

### Expected Behavior

This ist not necessary...

### Steps To Reproduce

Look at the new version.

### Logs

```markdown
This ist not necessary...
```

### Configuration

```json
This ist not necessary...
```

### Environment

This ist not necessary...
- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
Config is in Settings and Info has a link within the popup to GitHub.

**Comment by drheck** [comment]
> Config is in Settings and Info has a link within the popup to GitHub.
Yes, but you have to click sttings on the left side of the window and in settings the buttons are on the right side...
Same with the the info button: I would prefer a direct link into the git..
