### ISSUE TITLE
My plugin is verified but it's not shown in Search properly

### ISSUE THREAD

**Issue by minamoanes** [homebridge/homebridge#3566]
### Current Situation

My plugin is verified but it's not shown when you search for it in the plugins tab, only if you write the full name like that  "homebridge-homekit-control"
however if you search for "homekit control" or anything else it never shows up.

https://github.com/minamoanes/homebridge-homekit-control

**Comment by bwp91** [comment]
You need to add the keywords here https://github.com/minamoanes/homebridge-homekit-control/blob/6847ca622282b7d5db94c98502a093e4a8fc1974/package.json#L8-L16

**Comment by bwp91** [comment]
These keywords are what the plugin search uses in the UI

**Comment by minamoanes** [comment]
@bwp91 but as you can see, if you search using any of those keywords (f.e. `homekit-control`, the plugin doesn't show up at all

**Comment by NorthernMan54** [comment]
@minamoanes - I took a moment to look into the npm registry search, and not sure what is happening.  Our npm registry search is here - https://github.com/homebridge/homebridge-config-ui-x/blob/e11fc5a3d1049e8dfe8523b6e3ad70c7115b0307/src/modules/plugins/plugins.service.ts#L261

And if you manually run that in a browser, it gives the same result.   Looks the something on the NPM side of the equation

PS Try this - https://www.npmjs.com/search?q=HomeKit-control
