### ISSUE TITLE
No Homebridge after reboot MacOS

### ISSUE THREAD

**Issue by tsmitsmitonline** [homebridge/homebridge#3569]
### Current Situation

I have an active Homebridge running on my MacOS (latest OS).
But after rebooting, I lost my Homebridge connection to the web interface.
Any ideas how I can fix this?

I am a simple techie, so I need some guidance if I should do some stuff via terminal app :-) 

### Logs

```markdown
na
```

### Configuration

```json
na
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
Did you follow the steps here?

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS#step-2-install-homebridge-and-homebridge-ui

After restart the UI should automatically start, but if not you can try the start command listed towards the bottom of the page.

**Comment by tsmitsmitonline** [comment]
deinstalled and installed (followed the instructions). now it works. many thanks for the prompt advise!
