### ISSUE TITLE
Check if child bridge or not from plugin perspective

### ISSUE THREAD

**Issue by maxileith** [homebridge/homebridge#3575]
### Current Situation

Hi,

is it possible to determine whether or not a plugin is running as a child bridge from the plugin perspective? I thought I could just do something like this:

```typescript
const isChildBrdige: boolean = this.config._bridge !== undefined;
```

However, this does not work out since the `._bridge` attribute is always undefined, even if the plugin is running as a child bridge.

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

### Additional Context

-

**Comment by bwp91** [comment]
When the child bridge feature was introduced, the extra configuration property `_bridge` in a plugin config is held back from the plugin so it cannot detect this.

I'm not sure why this decision was made, but it is just how it is right now!
