### ISSUE TITLE
Can't update to Node.js from v20.11.1 to v20.12.1

### ISSUE THREAD

**Issue by Hillann** [homebridge/homebridge#3586]
### Analysis

Running the `sudo hb-service update-node` I can't update to version v20.12.1
I get the following result:

ℹ Updating Node.js from v20.11.1 to v20.12.1...
ℹ Target: /opt/homebridge
✖ Request failed with status code 404

### Expected Behavior

update to latest node.js version

### Steps To Reproduce

running `sudo hb-service update-node`

### Logs

```markdown
ℹ Updating Node.js from v20.11.1 to v20.12.1...
ℹ Target: /opt/homebridge
✖ Request failed with status code 404
```

### Configuration

```json
..
```

### Environment

- OS: Raspbian GNU/Linux Bookworm (12)
- Software: Homebridge v1.7.0 · UI v4.56.1
- Node: v20.11.1
- npm:

### Process Supervisor

hb-service

**Comment by saschafuhrmann** [comment]
Same here 

Homebridge v1.7.0
UI v4.56.1]
Linux homebridge 5.4.79-v7+ #1373 SMP Mon Nov 23 13:22:33 GMT 2020 armv7l GNU/Linux

```
Updating Node.js to LTS, please wait...
Installed: v20.11.1
Current Node.js LTS: v20.12.1
Updating Node.js to v20.12.1...
Downloading to /tmp/tmp.rOtIuLklQl/node-v20.12.1-linux-armv6l.tar.gz ...
-#O=#    #     #                                                                                                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Failed to download node-v20.12.1-linux-armv6l.tar.gz. See logs above.
```

**Comment by AppleTechy** [comment]
We have been relying on unofficial builds from NodeJS for armv6. It looks like they had some automated build failures for 20.12.x which is currently being tracked over at nodejs/unofficial-builds#126.   Once that issue gets resolved you should be able to upgrade like normal, however until then `hb-service update-node` will not work. It looks like it might be fixed with in the next week, based on the PR today that fixed one of the other failed builds.

**Comment by Sir3lly** [comment]
Having an issue updating from 18.18.2 using Truenas TrueNAS-13.0-U6.1 tried using command  pkg update && pkg upgrade.

This is the result
<img width="677" alt="Screenshot 2024-04-05 at 9 10 42 PM" src="https://github.com/homebridge/homebridge/assets/154022160/75d0fccc-a32a-4101-94fe-cbf03229d605">

looking for guidance
thanks  Chris

**Comment by saschafuhrmann** [comment]
Works again

**Comment by AppleTechy** [comment]
> Works again

Perfect. I am going to go ahead and close this ticket now. Looks like the unofficial builds that anyone using homebridge would get appear to be compiling successfully, most importantly is the armv61 build is fully functional.

@Sir3lly  Please open a separate ticket. You are having a different issue.

**Comment by Sir3lly** [comment]
Trying to get some required information that’s needed to fill out a ticked how do I obtain logs and configuration?
