### ISSUE TITLE
SmartHQ Plug-in Request  (GE Profile Smart Appliances) 

### ISSUE THREAD

**Issue by JasonGoldenDDT** [homebridge/homebridge#3587]
### Current Situation

I've seen two previous attempts to create SmartHQ (GE's Smart Appliance App) plugin, each appears abandoned.  I'll assume demand for this is low or not visible, hence this post. 

I own an GE Opal 2.0  ice maker and use SmartHQ app to turn on/off, monitor status, and create schedules.  I don't currently have any other smart GE appliances.  This devices is embedded in our daily routine and to use it efficiently we have to tailor its cycles around our schedule. 

Doing this in a separate app is cumbersome and when we travel.  We often forget to disable its schedule or turn it back on when we are heading home. 

### Proposed Change

I have limited coding experience, however what I do have I am willing to lend to the development of a SmartHQ plugin for Homebridge.  

The ideal plugin would allow the user to start/stop ice production.  See the current status of the ice bin.  See the current status of the water filter (on/off sensor).  See if the machine is due for cleaning (on/off sensor). 

HomeKit would then manage cycle schedules and Siri / Light could alert the user action.

**Comment by joeyb** [comment]
@bwp91 - Looks like this was closed as completed. Could you link to the SmartHQ plugin? As far as I can tell, the only plugins listed are the abandoned ones that @JasonGoldenDDT mentioned.
