### ISSUE TITLE
DYMO Labelwriter Homebridge Plugin 

### ISSUE THREAD

**Issue by JasonGoldenDDT** [homebridge/homebridge#3588]
### Current Situation

I have a usb connected Dymo Labelwriter I rarely use.  I would like to have Siri print labels using data I include in my request.  For example, I have the demo labelwriter dual, one side has receipt paper, the other a standard mailing label. 

If I wanted to have my Grocery List printed I could ask Siri to "print our grocery list."  and have the list printed to the receipt paper. 

Often we need to label food we place in the fridge/freezer or storage.  I'd like to have Siri print these labels by voice.  For example;  asking Siri to print a "freezer label for chicken thighs" would produce a formatted label that includes "Chicken Thighs", a date time stamp for printing the label, and a calculated expiration or use by date based on the food item or specified preference. 

I can think of several types of labels I could request, ideally the solution uses Dymo Connect's web interface to allow for templated label. 

### Proposed Change

A plug in that uses Dymo Connect to print labels using Siri.

**Comment by bwp91** [comment]
Hi @JasonGoldenDDT 

Thanks for sharing your suggestion!

Just to clarify, the 'issues' section here on GitHub is mainly for reporting problems or suggesting features directly related to the Homebridge application itself, rather than for plugins.

Since all Homebridge plugins are developed by the community, you might find it more effective to reach out on our Reddit or Discord servers for plugin-related requests.

I'll go ahead and close this issue for now. But feel free to get in touch if you have any other questions or ideas!

Cheers

**Comment by JasonGoldenDDT** [comment]
Thanks Ben, I saw similar and thought it was a good place to start… I’ll share via discord and reddit.





Jason Golden | Founder
[signature_4231052164]
“Helping people do great things.”

Day Dream Technologies Inc.
(808) 351-9202 | (844) 23DREAM
55 S Kukui, Honolulu, Hawaii 96813
https://www.daydreamtechnologies.com<https://www.daydreamtechnologies.com/>

From: Ben ***@***.***>
Date: Friday, April 19, 2024 at 12:28 PM
To: homebridge/homebridge ***@***.***>
Cc: Jason Golden ***@***.***>, Mention ***@***.***>
Subject: Re: [homebridge/homebridge] DYMO Labelwriter Homebridge Plugin (Issue #3588)

Hi @JasonGoldenDDT<https://github.com/JasonGoldenDDT>

Thanks for sharing your suggestion!

Just to clarify, the 'issues' section here on GitHub is mainly for reporting problems or suggesting features directly related to the Homebridge application itself, rather than for plugins.

Since all Homebridge plugins are developed by the community, you might find it more effective to reach out on our Reddit or Discord servers for plugin-related requests.

I'll go ahead and close this issue for now. But feel free to get in touch if you have any other questions or ideas!

Cheers
