### ISSUE TITLE
Can't update to Node.js from v20.9.0 to v20.11.1

### ISSUE THREAD

**Issue by CBPnow** [homebridge/homebridge#3592]
### Current Situation

I'm trying to update Node.js from v20.9.0 to v20.11.1 in order to satisfy a requirement for a plugin.  

I run the sudo hb-service update-node command, I get an unexpected error
 

### Logs

```markdown
Running the sudo hb-service update-node I can't update to version v20.11.1
I get the following result:

bodhi@indy:/volume1/@appstore/Node.js_v20/usr/local$ sudo hb-service update-nodeℹ Updating Node.js from v20.9.0 to v20.12.2...
✖ Cannot update Node.js on your system. Non-standard installation path detected: /volume1/@appstore/Node.js_v20/usr/local

bodhi@indy:/volume1/@appstore/Node.js_v20/usr/local$ ls -ltr
total 0
drwxr-xr-x 1 root root 24 Nov  9 08:49 lib
drwxr-xr-x 1 root root 30 Nov  9 08:49 bin
drwxr-xr-x 1 root root 10 Nov  9 08:50 etc
```

### Configuration

```json
Node.js Path	/volume1/@appstore/Node.js_v20/usr/local/bin
Storage Path	/volume1/homebridge
Config Path	/volume1/homebridge/config.json
Plugin Path	/volume1/homebridge/node_modules
```

### Environment

- OS:    Synology DSM
- Software:    1.7.0
- Node:    v20.9.0
- npm:    10.1.0

### Process Supervisor

hb-service

### Additional Context

I've seen that there are comments around this error, but didn't find anything that was current.  So, was unsure if this had either been resolved and I needed to do additional work first OR if I needed to move to 20.12?

**Comment by TheCableGuy99** [comment]
I also need to update node.js according to the dashboard but it's installed using Synology package centre so I cannot do it as there's no later package than version 20.

**Comment by CBPnow** [comment]
Is there a work-around that I could do, or since this is a Synology limitation (no newer Node.js) you don't know?  

Thanks for your help,
Chris

**Comment by bwp91** [comment]
@NorthernMan54 am I correct in thinking that synology users should stay on the node version installed from the package center?

Anyway, in the next version of the Homebridge UI, the update notification for node will be hidden for synology users to avoid any misunderstanding!

**Comment by CBP980** [comment]
Before this gets marked stale, as I’m still stuck with this issue, had a follow up question / alternative….

Would the way for me or others with this same issue to get around this be to back everything up in Homebridge UI and then remove Homebridge from Synology and install it but not updating the Node.js and then restoring the backup (though that restore might reference the newer Node version - unsure)?

Thanks,
Chris

**Comment by NorthernMan54** [comment]
@CBP980 The homebridge UI restore does not include NodeJS.   On Synology you will need to wait for Synology to provide an updated NodeJS package.

**Comment by astubbs** [comment]
I'm also running on DSM.

Is the plugin the Apple TV plugin by any chance? Mine is telling me: 

> The plugin "homebridge-appletv-enhanced" requires Node.js version of ^20.12.1 || ^18.20.1 which does not satisfy the current Node.js version of v20.9.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF

So I'm also stuck :/ Do any other DSM people here know the process to try to get this updated in the DSM package manager?

**Comment by TheCableGuy99** [comment]
You just have to wait for Synology to update the Node.js package before you can run that plugin. Maybe send them a support ticket and get on their case?

**Comment by astubbs** [comment]
Thanks @TheCableGuy99 , I will do that. I've also created an issue requesting a downgrade on the plugin: https://github.com/maxileith/homebridge-appletv-enhanced/issues/459

**Comment by TheCableGuy99** [comment]
> Thanks @TheCableGuy99 , I will do that. I've also created an issue requesting a downgrade on the plugin: [maxileith/homebridge-appletv-enhanced#459](https://github.com/maxileith/homebridge-appletv-enhanced/issues/459)

Good idea :)
