### ISSUE TITLE
Automatically create iptables rules for UI and main/child bridges

### ISSUE THREAD

**Issue by kevinji** [homebridge/homebridge#3593]
### Current Situation

I use `ufw` with my Ubuntu server and currently need to manually open up ports for the UI and the main/child bridges:
```bash
sudo ufw allow 8581/tcp               # UI
sudo ufw allow 36149,41388,59102/tcp  # Main and child bridges
```

### Proposed Change

Homebridge could look up the ports used by the UI, main bridge, and child bridges, and automatically add/update corresponding `iptables` rules so that users don't need to add them manually to their firewall.

**Comment by NorthernMan54** [comment]
@kevinji While this is a great suggestion, we support a lot of different operating systems, environments and configurations and adding something specific like this would become a one off component.  As it would also need to take into account the settings potential needed for plugins as well.

So at this time we would need to decline this suggestion.
