### ISSUE TITLE
Cannot install the hb-service on OSX with M2 chipset

### ISSUE THREAD

**Issue by ams-ryanolson** [homebridge/homebridge#3599]
### Current Situation

I am trying to install the hb-service onto my Mac Studio M2. When I run the installer on my mac, I get the following error
`✖ ERROR: User "XXX" does not have write access to the global npm modules path.
✖ You can fix this issue by running the following commands:

sudo chown -R xxx:admin "/Users/xxx/Library/Application Support/Herd/config/nvm/versions/node/v21.7.2/lib/node_modules"
sudo chown -R xxx:admin "$(dirname $(which npm))"

✖ Once you have done this run the hb-service install command again to complete your installation.
`

After running those commands, the issue still persists

### Logs

```markdown
no logs with validating info
```

### Configuration

```json
not applicable
```

### Environment

- OS: OSX Sonoma 14.4.1
- Software:
- Node: 21.7.2
- npm: 10.5.0

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
Have you installed nodejs already?

**Comment by ams-ryanolson** [comment]
Yes, fully installed. I am also a full stack Dev. So to add some additional context

I use NVM but global and node versions are all set and validated based on the commands requested
I am also using a Laravel Helper called Herd. It is just an enviro management for my dev sites locally but has no bearing on this

I can also run hb-service run and it works fine

**Comment by NorthernMan54** [comment]
@ams-ryanolson - This is a bit odd, as I do my development on a M2 MacBook Pro without issue.  Did you follow these instructions ?

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS

Looking at the provided log, it directly calls out `herd` which is not something we work with

```
/Library/Application Support/Herd/config
```

**Comment by ams-ryanolson** [comment]
I agree on herd. So before I posted the issue I did change the location of node/npm with the same issue as above. The node location doesn't seem to be the issue. 

Honestly I'm going to try purge and reinstall this weekend and see if that works but I don't have high hopes.
