### ISSUE TITLE
Update to Homebridge 1.8.0 from 1.7.0 fails

### ISSUE THREAD

**Issue by cl4udiu5** [homebridge/homebridge#3600]
### Current Situation

Update from Homebridge 1.7.0 to 1.8.0 from Homebridge UI fails. See log.

### Logs

```markdown
.
```

### Configuration

```json
.
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software:
- Node: v20.12.2
- npm:

### Process Supervisor

hb-service

### Additional Context

[homebridge-error.log](https://github.com/homebridge/homebridge/files/15090738/homebridge-error.log)

**Comment by NorthernMan54** [comment]
If you try the update again, does it work ?

**Comment by cl4udiu5** [comment]
I tried it 4 times now. Always the same error.

**Comment by bwp91** [comment]
Hi @cl4udiu5 

this sudden 'stop' that appears in the log can sometimes be due to running out of memory.

can you try updating homebridge from the terminal inside the UI? You can run:

```
sudo npm i -g homebridge
```

**Comment by cl4udiu5** [comment]
Hi @bwp91 

unfortunately, it only worked partially.
I started the console via Homebridge UI and executed the command you mentioned. Also went through.
Then I restarted Homebridge, but unfortunately the log still shows 1.7.0. The update to 1.8.0 is then also displayed again in Homebridge UI. I hope there is another option.
But thanks for everything so far.
