### ISSUE TITLE
Getting target temperatures (setpoints) in Fahrenheit?

### ISSUE THREAD

**Issue by jarrodkrauszer** [homebridge/homebridge#3612]
### Current Situation

Is there a way to have the Homebridge send setpoints in Fahrenheit instead of Celcius?  I did find the setting option to have them display in F which works but when I asked Siri to change the setpoint it is sending it out as C and truncating it, so when I request a setpiont of either 70 or 71 I get 21 in return which converts to 70.

### Logs

```markdown
No Logs
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 8ECF",
        "username": "0E:34:4D:0E:8E:CF",
        "port": 51350,
        "pin": "537-43-608",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "HomebridgeCrestron",
            "host": "10.0.0.20",
            "port": "50001",
            "HeaterCooler": [
                {
                    "id": 1,
                    "name": "Kitchen"
                },
                {
                    "id": 2,
                    "name": "Living Room"
                }
            ],
            "platform": "HomebridgeCrestron"
        }
    ]
}
```

### Environment

- OS: Debian GNU/Linux Bookwarm (12)
- Software: 1.8.1
- Node: 20.13.0
- npm: 10.5.2

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
HomeKit internally only uses Celsius, so not much can be done.  I do think they are using 1/2 degree rounding so 71 is 21.5 and 70 is 21.  Please raise as an issue with the plugin dev so they can look at this further.

**Comment by jarrodkrauszer** [comment]
Thanks for getting back to me.  I did send a message to the plugin developer hoping to hear back.

**Comment by NorthernMan54** [comment]
Going to close this, as it appears to be a plugin concern
