### ISSUE TITLE
Homebridge hangs and stops responding to HomeKit inputs

### ISSUE THREAD

**Issue by yffud** [homebridge/homebridge#3615]
### Analysis

Homebridge will stop responding to inputs from HomeKit until it is rebooted. 

The last log messages before hanging will be something similar from the Smartthings Plugin 

[5/14/2024, 4:33:14 AM] [Smartthings Plug (IK)] Error getting devices from Smartthings: Error: getaddrinfo EAI_AGAIN api.smartthings.com
[5/14/2024, 4:33:14 AM] [Smartthings Plug (IK)] Could not load devices from Smartthings: undefined.  Check your configuration

No more long messages after than until rebooted 

### Expected Behavior

A better behavior would be an automatic restart of home bridge or the plug-in or automatic retries by the smart things plugin of the API on failures. 

### Steps To Reproduce

Running Homebridge and SmartThings plugin 

The system will sometimes hang if the SmartThings plugin doesn't get a response from the smartthings API 

Service will have to be restarted to allow control again. 

### Logs

```markdown
Final logs entry will be something similar to 

[5/14/2024, 4:33:14 AM] [Smartthings Plug (IK)] Error getting devices from Smartthings: Error: getaddrinfo EAI_AGAIN api.smartthings.com
[5/14/2024, 4:33:14 AM] [Smartthings Plug (IK)] Could not load devices from Smartthings: undefined.  Check your configuration

No more longs after this until restarted
```

### Configuration

```json
{
            "name": "Smartthings Plug (IK)",
            "BaseURL": "https://api.smartthings.com/v1/",
            "AccessToken": "XXX",
            "GarageDoorMaxPoll": 40,
            "PollLocksSeconds": 10,
            "PollDoorsSeconds": 10,
            "PollSensorsSeconds": 5,
            "PollSwitchesAndLightsSeconds": 10,
            "PollWindowShadesSeconds": 20,
            "platform": "HomeBridgeSmartThings"
        }
```

### Environment

- OS: Debian GNU/Linux Bullseye (11)
- Software:
- Node: v18.16.0
- npm:

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
@yffud This is either an issue with your network / connection from where you are running homebridge to the Smartthings cloud servers or an internal issue with the Smartthings plugin.  If it isn't a network issue, please raise this against the Smartthings plugin so that the developer is aware and can look into it.

**Comment by yffud** [comment]
Noted as an issue in the SmartThings Plugin Github repo 

https://github.com/iklein99/homebridge-smartthings/issues/257

**Comment by NorthernMan54** [comment]
Tks, going to close this here
