### ISSUE TITLE
How to schedule a child bridge restart - raspberry pi - config UI

### ISSUE THREAD

**Issue by jat80** [homebridge/homebridge#3616]
### Current Situation

Hi there,

I have a plugin that works great except after a few days it loses connection and requires a reboot then it works fine again.  I'm wondering if there is a way I can schedule a reboot of the specific child bridge on my raspberry pi.  I'm using config UI.

Yes I understand this is an issue with the plugin itself and I have (and others) mentioned this and raised issues to the plugin's developer but no response.   As mentioned it works flawlessly for a few days then requires a reboot. 

Any help would be appreciated.

### Logs

```markdown
n/a
```

### Configuration

```json
n/a
```

### Environment

n/a

### Process Supervisor

hb-service

**Comment by Patr-ick** [comment]
Please see https://github.com/homebridge/homebridge/issues/2852

previously `sudo kill `pidof "homebridge: homebridge-deconz"`` worked by I guess this was back then in 2021. I think current solution is `sudo killall "homebridge: homebridge-deconz"`
This should force a reboot of the child bridge

Either create a cronjob or a SSH command to schedule a reboot.
