### ISSUE TITLE
Multiple HomeBridge instance (in multiple location) issue

### ISSUE THREAD

**Issue by rfbsurf** [homebridge/homebridge#3618]
### Current Situation

Didn't see anything obvious in the FAQs other than mDNS comments.  Apologies if this is a known issue or in the guides

I have a Homebridge instance running at my primary residence (running on a Mac Studio) with an Apple TV as the hub on a Eero-based LAN.  All has been working just fine with no issues.

We have a second home where I decided to install Homebridge as well (this time on a Mac Mini), also using an Apple TV as a hub (also an Eero-based LAN).

The new one fails ... Homebridge is running just fine (and I can control the accessories from within the HB web page) and while HB registered my accessories correctly in Home (the second Home), those devices within Home are listed as having "No Response".

Within Home itself, I have both Homes individually added (and Home Switching is enabled). I have logged into both (on the ATV) using the same Apple ID.

I've checked both instances (primary and secondary) and the configuration of HB is identical as well as the Eero networks.  Both are running HAP / Bonjour ... I tried Ciao at the secondary site but it makes no difference (the only odd thing is when I change my secondary site HB instance to use Ciao, "Discover DNS" running at the primary network, I will see my HB instance at the secondary site pop up ... weird ... but I'm not familiar with Ciao so perhaps that's expected behavior).

As noted, everything works in the primary home. In the secondary, what's not working is being able to control devices from within Home (as the devices are not responding) -- within Homebridge itself, I can turn on lights, etc., just fine (so it's the active connection between Home and Homebridge which is the issue). Given that the devices show up in Home, obviously Homebridge is able to register (to the right Home instance) the devices, just can't control them (hence my looking into DNS).

My gut tells me it's either in the networking (which is why I started exploring DNS) somewhere or the Home is getting confused because of the multiple instances (not at registration though ... for instance, I can look at each Home instance separately and see the right Homebridge and it's associated devices registered correctly with the right Home instance ... just can't communicate with them).

It’s clearly a HomeBridge-only issue (as with my current setup, native Home devices work fine within Home at both locations, it’s only the multiple HomeBridge case that doesn’t)

Any ideas ?  Someone on Reddit suggested using different Apple IDs for Home instances (and perhaps adding the secondary as a guest to the first) but that sort of defeats the purpose of both having a common ID as well as being able to have other Home instances managed by the Home app (then again, if this is a bug)

I've removed all devices from my current configuration (other than a Dummy Switch to test with) which is reflected in the configuration and logs below

### Logs

```markdown
[5/25/2024, 10:48:35 AM] Homebridge v1.8.2 (HAP v0.12.1) (Homebridge 0CCD) is running on port 51307.
[5/25/2024, 10:48:35 AM] [Test Switch] Launched child bridge with PID 14471
[5/25/2024, 10:48:35 AM] Registering accessory 'homebridge-dummy.DummySwitch'
[5/25/2024, 10:48:35 AM] [Test Switch] Loaded homebridge-dummy v0.9.0 child bridge successfully
[5/25/2024, 10:48:35 AM] Loaded 0 cached accessories from cachedAccessories.0E6466CA419A.
[5/25/2024, 10:48:35 AM] [Test Switch] Setting switch to false
[5/25/2024, 10:48:35 AM] Homebridge v1.8.2 (HAP v0.12.1) (Test Switch) is running on port 46236.
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge 0CCD",
        "username": "0E:44:F8:3A:34:11",
        "port": 51307,
        "pin": "534-69-584",
        "advertiser": "bonjour-hap"
    },
    "accessories": [
        {
            "name": "Test Switch",
            "stateful": true,
            "dimmer": false,
            "reverse": false,
            "time": 1000,
            "random": false,
            "resettable": false,
            "brightness": 0,
            "disableLogging": false,
            "accessory": "DummySwitch",
            "_bridge": {
                "username": "0E:64:66:CA:41:9A",
                "port": 46236
            }
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ],
    "disabledPlugins": []
}
```

### Environment

- OS:  Mac OS Sonoma 14.5
- Software: Homebridge is latest version
- Node: v20.13.1
- npm:
- {
  npm: '8.11.0',
  node: '16.16.0',
  v8: '9.4.146.24-node.21',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.7',
  openssl: '1.1.1q+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Your setup and config sounds correct, in a multi home setup I have the following

1 - Am using an Apple TV as the hub in both locations
2 - Am using the same Apple ID on the Apple TV in both locations
3 - In the Home App I have 2 separate homes configured

Am thinking your suspicion in regards to network may be correct, and the connection between your Mac mini and your iPhone.  One thing to look into is the mDNS information that homebridge is sharing in the second home.   On your iPhone, install the `Discovery` app, and look at _hap and in particular the ip addresses shared from your homebridge instances.  This is the address used by your iPhone to connect to homebridge.

**Comment by rfbsurf** [comment]
Figured out part of the mystery ... after checking a bunch of IPs, turns out that one of my Eeros (the one my ATV was connected to) was handing out IPs on a slightly different subnet.  Why ?  TBD ... but forcing the ATV to connect to the subnet everything else was on got it to work

Odd ... but now I know the reason, will reconfigure the eero network and see if they can now behave 

Thanks
