### ISSUE TITLE
Cant Update from Homebrige UI Terminal

### ISSUE THREAD

**Issue by Piotronic** [homebridge/homebridge#3625]
### Current Situation

Wenn I Update as usual via command: sudo apt full-upgrade
I geht the Error: The Homebridge package must not be upgraded from the Homebridge UI Terminal
![error](https://github.com/homebridge/homebridge/assets/98609963/45b647f4-3ecc-41b1-ab8f-213afee01dab)

### Logs

```markdown
pi@homebridge:/var/lib/homebridge $ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  homebridge
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
46 not fully installed or removed.
Need to get 0 B/37.6 MB of archives.
After this operation, 9,456 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Reading changelogs... Done
(Reading database ... 72465 files and directories currently installed.)
Preparing to unpack .../homebridge_1.2.1_armhf.deb ...
Running pre-upgrade steps...

ERROR: The homebridge package must not be upgraded from the Homebridge UI Terminal.

dpkg: error processing archive /var/cache/apt/archives/homebridge_1.2.1_armhf.deb (--unpack):
 new homebridge package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/homebridge_1.2.1_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Configuration

```json
No Clue
```

### Environment

- OS: Windows10
- Software: Homebridge Raspberry Pi4
- Node: v20.14.0
- npm:

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
It is design to not allow you too.

**Comment by Piotronic** [comment]
> It is design to not allow you too.

Hello, But I used to do it this way. Its the only way I have access to Homebridge, via Browser UI terminal

**Comment by dfberger** [comment]
the deb preinst code does this:
```
  pstree -s $$ | grep "hb-service" > /dev/null
  if [ "$?" -eq 0 ]; then
    echo
    >&2 echo "ERROR: The homebridge package must not be installed from the Homebridge UI Terminal."
    echo
    exit 1
  fi
```

this code doesn't perform as desired in all cases.

I'm running homebridge in an lxc/lxd container, and it refuses to be ugpraded from a shell spawned via

```lxc exec <container> bash```

this is from inside the homebridge web terminal

```
$ echo $$
971760
$ pstree -s $$ | grep "hb-service"
systemd---hb-service---bash-+-grep
$ echo $?
0
```

this is from a shell spawned in the container

```
# echo $$
971121
#   pstree -s $$ | grep "hb-service"
        |-hb-service-+-bash
        |            `-15*[{hb-service}]
# echo $?
0

# pstree -s $$
systemd─┬─agetty
        ├─cron
        ├─dbus-daemon
        ├─hb-service─┬─bash
        │            ├─homebridge─┬─ffmpeg
        │            │            ├─homebridge: hom───14*[{homebridge: hom}]
        │            │            └─14*[{homebridge}]
        │            └─15*[{hb-service}]
        ├─networkd-dispat
        ├─packagekitd───2*[{packagekitd}]
        ├─polkitd───2*[{polkitd}]
        ├─rsyslogd───2*[{rsyslogd}]
        ├─snapd───14*[{snapd}]
        ├─4*[snapfuse]
        ├─snapfuse───2*[{snapfuse}]
        ├─snapfuse───10*[{snapfuse}]
        ├─sshd
        ├─systemd-journal
        ├─systemd-logind
        ├─systemd-network
        ├─systemd-resolve
        ├─systemd-udevd
        └─unattended-upgr───{unattended-upgr}
# ps -f $$
UID          PID    PPID  C STIME TTY      STAT   TIME CMD
root      971121       0  0 09:51 pts/1    Ss     0:00 /bin/bash
```

**Comment by baltun2010** [comment]
i have the same error

ERROR: The homebridge package must not be upgraded from the Homebridge UI Terminal.

dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/homebridge_1.3.2_arm64.deb (--unpack):
 �neues pre-installation-Skript des Paketes homebridge�-Unterprozess gab den Fehlerwert 1 zur�ck
Fehler traten auf beim Bearbeiten von:
 /var/cache/apt/archives/homebridge_1.3.2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by dfberger** [comment]
Unfixed. Commenting to hold off the staleness bot.

**Comment by mkz212** [comment]
You have two options:

1. Exclude homebridge from this command (from apt update and apt full-upgrade). Then this command will update everything except homebridge.

- To do this: `sudo apt-mark hold homebridge`. 
- To bring back use `sudo apt-mark unhold homebridge`.

2. Connect to Homebridge via SSH in external Terminal.

**Comment by leesonthenet** [comment]
I had this same error with Proxmox and I have an update for future searchers:
If you are in your pve node and you type in pct enter 1XX (or whatever your container ID is), and then try to apt update/apt upgrade, you will get this error.
However, if you go to the console of your actual container and log in to your homebridge terminal there, you won't get this error.

**Comment by pcktm** [comment]
For proxmox LXC simply stopping homebridge before `apt upgrade` works:
```
hb-service stop
```
