### ISSUE TITLE
Add ultrabrite to this!

### ISSUE THREAD

**Issue by MrTecHead** [homebridge/homebridge#3627]
### Current Situation

I have been testing this out and i LOVE IT! One small problem though... all our smart lights are ultrabrite, which is not supported by homebridge or homekit and i dont want to change.

### Proposed Change

So, please, add a plugin for ultrabrite!

**Comment by Zer0x00** [comment]
Ultrabrite seems to use tuya. There are a couple of plugins for tuya, just try one of those.  
Alternatively flash them with Tasmota / ESPHome and enjoy a cloud independent lighting system!

**Comment by NorthernMan54** [comment]
Two thumbs up on Tasmota or openbk
