### ISSUE TITLE
HomeBridge broken after latest update

### ISSUE THREAD

**Issue by geigerzaehler242** [homebridge/homebridge#3628]
### Analysis

I just did a sudo update/full upgrade on my raspberry pi and now home bridge won't start. anyone else having this issue? i only have one plug-in installed. i can't even ssh to the pi anymore.

### Expected Behavior

ive updated many times over the last number of years and usually it always updates without issue.

### Steps To Reproduce

sudo apt update then full upgrade

### Logs

```markdown
n/a
```

### Configuration

```json
n/a
```

### Environment

- OS: raspberry pi
- Software:
- Node: 20.13 but it looked like it was being updated to 20.14?
- npm:

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Logs or something to show what broke ....

**Comment by geigerzaehler242** [comment]
looks like the problem was with raspberry pi update which caused SD card corruption. i did a full new raspberry pi installation on a new SD card, even upgraded from 32 bit to 64 bit R-OS. then i recovered the plugin from a backup i luckily had done previously and now everything is back working again. props to home bridge developers for the plugin recovery feature
