### ISSUE TITLE
Child Accessories

### ISSUE THREAD

**Issue by YoaverageApplefanboy** [homebridge/homebridge#3629]
### Feature Description

There should be a way to have child accessories, which would essentially be a child bridge on the Homebridge side but a simple home accessory on the HomeKit side, without the accessory being attached to a bridge.

Currently, the only way to have a plug-in be separated from the main Homebridge process is to use a child bridge. Although I assume that this works for plug-ins which only handle one accessory which is what this feature would mainly be targeted towards, I haven't actually tried it and I am only using child bridges for the plug-ins that I utilize which handle more than one accessory, the use of a bridge is completely unnecessary when the plug-in only bridges in one accessory, and I assume it also unnecessarily clutters things up.

What should happen is that there should be a button called "add plug-in to separate process" or something like that. This would be the exact same as child bridging a plug-in on the Homebridge side. However, in this current state, the accessories of the bridged plug-in would stay on the main Homebridge bridge.

Another button should be added called "unbridge accessory". You would then select the accessory that you wanted to unbridge.
If the plug-in combines multiple attributes of the same accessory into a single accessory with separate tiles, then there should be an option for if each of these individual tiles should be unbridged as individual accessories or if the entire multi-tile  accessory should be unbridged and advertised as such.

Child bridging should be available still, but allowing a person to unbridge an accessory from a plug-in without having to rely on the developer adding such a function to their plug-in and also without the creation of an unnecessary bridge would be great.

Note: I would be OK with the first button listed above being axed and instead you would just child bridge the plug-in and add another button called "advertise accessories individually", which would get rid of the bridge and advertise each of the plug-ins accessories as individual accessories, with the option to pick and choose which accessories are advertised individually and which ones are added to the bridge, if the plug-in handles more than one accessory.

There are two instances in my set up where this would be helpful:
1: Homebridge Govee, where we only have one heater device.
2: Homebridge Frigidaire AC plug-in, where we only have one Frigidaire air conditioner.
In both of these cases, the plug-ins group the multiple attributes of the accessory into a single accessory with multiple tiles.

edit: I just realized that this was being posted in the Config UIX issues page, not sure how to move it to the Homebridge issues page. So sorry about that.

**Comment by NorthernMan54** [comment]
I'm kinda confused about what your are asking about, as bridges and child bridges don't impact how accessories are structured.  The structure of an accessory and its component services / characteristics come from the plugin, and reflect how the plugin created the accessory.

**Comment by YoaverageApplefanboy** [comment]
So, basically what I want is for the plug-in to be essentially child bridged on the Homebridge side but for each of the accessories that the plug-in brings in to be advertised to HomeKit as individual accessories, this will be useful if the plug-in only brings in one accessory so that you don't have to bring in a bridge for that accessory as well.

**Comment by NorthernMan54** [comment]
Can you explain what you are asking about with images from the home app ?  That may make it easier to understand.

This is likely nothing to do with bridges and child bridges

**Comment by YoaverageApplefanboy** [comment]
Hi. Just wanted to clarify that I am the same person from Discord, it's_Andrew. Remember I am blind but I will try.

 As you can see, this is the hubs and Bridges view of the home app. In this view there are a couple of child bridges from my omebridge set up, my home hubs, and my Phillips Hugh Bridge. Like I said in the original post, I have two Homebridge plug-ins in my set up which only bridge in one accessory. if I were to bridge these, there would be two more bridges in the hubs and bridges section, with each bridge bringing in just that single accessory. As there is a limit on the amount of HomeKit accessories that you can have in one home, and I'm assuming that bridges count towards that limit,  This is inefficient.
Instead of having this setup, I would prefer if there was a way to make it so that the accessarles that the plug-ins bridge  in anre advertised individually to HomeKit. However, on the Homebridge side, it would be as if the plug-in was running as a child bridge. It would run in its own process. I would expect this to be called child accessory, and I would be fine if child bridging the plug-in automatically triggered this mode when the plug-in had less than two accessories.

**Comment by ebaauw** [comment]
The proposition of Homebridge (what’s in a name?) is to offer a HomeKit bridge for your accessories, so you only have to pair the bridge to HomeKit, rather than the individual accessories.  It also saves resources as each (non-bridged) accessory has its own secure web server.

Homebridge also supports non-bridged accessories, called external accessories, but a plugin must create these explicitly.  Typically, this is only done for accessories that technically cannot be bridged, like TV accessories.  This is what Homebridge ZP uses.

I’m not aware of any hard limit on the amount of accessories in a HomeKit home.  There used to be a limit on the size of your Home when synced over iCloud, but that has been lifted with the new Home architecture.

**Comment by YoaverageApplefanboy** [comment]
> 
> Homebridge also supports non-bridged accessories, called external accessories, but a plugin must create these explicitly.

All right. I would like if homebridge was able to be set up so that the accessories brought in by any plug-in could be treated as external accessories, again having an entire bridge for a single HomeKit accessories seems really stupid. But at the same time, on the homebridge side, the plug-in is separated into its own process, meaning that you get all of the benefits of running it in a child bridge without the creation of the bridge, especially useful if the plug-in only bridges in one accessory. I also think that you are taking the name "Homebridge" a bit too literally.
