### ISSUE TITLE
Govee Smart Plug Pro not working with current version of Homebridge

### ISSUE THREAD

**Issue by dalbergotti** [homebridge/homebridge#3642]
### Current Situation

I am unable to get my Govee Smart Plug Pro with Energy Monitoring x2 to work with Homebridge. The plugins do have bluetooth capabilities, but they are are mainly used on wifi, as they cannot work without wifi. The logs state that they are not supported somehow and I am wondering why. Did changing the name of the device at start have something to do with this or does support need to be created for the plug ins to work?

### Logs

```markdown
[6/30/2024, 1:36:35 PM] [Govee] [LR - Lamp (Smart Plug Pro Energy Monitoring)] is not currently supported, do create a Github issue 
[6/30/2024, 1:36:35 PM] [Govee] [Master - Light (Smart Plug Pro Energy Monitoring)] is not currently supported, do create a Github issue
```

### Configuration

```json
{
    "name": "Govee",
    "username": "   ",
    "password": "   ",
    "switchDevices": [
        {
            "label": "Living Room Left Corner",
            "deviceId": "11:3F:60:74:F4:AA:0A:56",
            "showAs": "default"
        },
        {
            "label": "MasterBed Light",
            "deviceId": "68:05:60:74:F4:AA:0C:F4",
            "showAs": "default"
        }
    ],
    "_bridge": {
        "username": "0E:6C:91:1D:D3:1F",
        "port": 36570
    },
    "platform": "Govee"
}
```

### Environment

- OS: macOS Sonoma
- Software: Homebridge 1.8.3
- Node: 20.15.0
- npm: 10.8.1

### Process Supervisor

hb-service

### Additional Context

[6/30/2024, 12:56:58 PM] [Govee] [LR - Lamp] is not currently supported, do create a Github issue with the following info:
{"device":"11:3F:60:74:F4:AA:0A:56","deviceName":"LR - Lamp","model":"H5086","httpInfo":{"groupId":0,"device":"11:3F:60:74:F4:AA:0A:56","sku":"H5086","spec":"","versionHard":"1.02.00","versionSoft":"1.00.24","deviceName":"LR - Lamp","deviceExt":{"deviceSettings":"{\"wifiName\":\"._____\",\"address\":\"______\",\"bleName\":\"GVH50860A57\",\"topic\":\"GD/83513ab20725e2e7782f8b527a117924\",\"wifiMac\":\"60:74:F4:AA:0A:56\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.24\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"_______\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H5086\",\"device\":\"11:3F:60:74:F4:AA:0A:56\",\"deviceName\":\"LR - Lamp\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.24\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/30618491c95bab32822318b89c92ae62-add_list_type_device_5086.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/a83b02799483139a7b4f61d9984886f7-new_h5086_pics_device_1.png\",\"headOnImgNew\":\"\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/94daf8d493a64a7ff592de961c123205-new_h5086_pics_device_1_close.png\",\"headOffImgNew\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"deviceId":22062052,"gidConfirmed":false,"goodsType":195,"attributesId":0,"supportScene":0}}

[6/30/2024, 12:56:58 PM] [Govee] [Master - Light] is not currently supported, do create a Github issue with the following info:
{"device":"68:05:60:74:F4:AA:0C:F4","deviceName":"Master - Light","model":"H5086","httpInfo":{"groupId":20362240,"device":"68:05:60:74:F4:AA:0C:F4","sku":"H5086","spec":"","versionHard":"1.02.00","versionSoft":"1.00.24","deviceName":"Master - Light","deviceExt":{"deviceSettings":"{\"wifiName\":\"_____\",\"address\":\"______\",\"bleName\":\"GVH50860CF5\",\"topic\":\"GD/d224a5d2111c06b3c6ef87c1343b7130\",\"wifiMac\":\"60:74:F4:AA:0C:F4\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.00.24\",\"wifiHardVersion\":\"1.02.00\",\"ic\":0,\"secretCode\":\"_______",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H5086\",\"device\":\"68:05:60:74:F4:AA:0C:F4\",\"deviceName\":\"Master - Light\",\"versionHard\":\"1.02.00\",\"versionSoft\":\"1.00.24\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/30618491c95bab32822318b89c92ae62-add_list_type_device_5086.png\",\"headOnImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/a83b02799483139a7b4f61d9984886f7-new_h5086_pics_device_1.png\",\"headOnImgNew\":\"\",\"headOffImg\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/94daf8d493a64a7ff592de961c123205-new_h5086_pics_device_1_close.png\",\"headOffImgNew\":\"\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"share":0,"deviceId":22062584,"gidConfirmed":false,"goodsType":195,"attributesId":0,"supportScene":0}}

**Comment by donavanbecker** [comment]
This needs to be opened on the plugin repo
