### ISSUE TITLE
Updating to 2.0 link broken

### ISSUE THREAD

**Issue by coneslayer** [homebridge/homebridge#3656]
### Proposed Change

In the v1.8.4 release notes, the link:

https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

does not work for me and instead redirects to the top of the Wiki. I couldn't find the page about updating to 2.0.

### Wiki Page Link

https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

**Comment by donavanbecker** [comment]
The release has been updated with the correct link.
https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

**Comment by coneslayer** [comment]
Is it possible to add a redirect so the release note link works for people?

**Comment by donavanbecker** [comment]
It has all already been posted.
