### ISSUE TITLE
Attempting to use systemd-resolved mDNS on Docker

### ISSUE THREAD

**Issue by Jafalex** [homebridge/homebridge#3657]
### Current Situation

After running into several issues with Avahi as the mDNS advertiser I saw on the [HB project's options page](https://github.com/homebridge/homebridge/wiki/mDNS-Options#avahi-linux-and-docker) that ``systemd-resolved`` was another (better?) option. 

I followed the instructions with no luck, all plugins revert to bonjour:
``[Plugin XYZ] The selected advertiser, "resolved", isn't available on this platform. Reverting to "bonjour-hap"``

My guess is that in ``homebridge.pkla``, I am not setting the right user. I used ``unix-user:alex`` because I have the homebridge container user ``PGID`` set to ``1000`` which happens to be me, ``alex``.

Any help highly appreciated!

### Logs

```markdown
dbus-daemon[96]: [system] Activated service 'org.freedesktop.resolve1' failed: Launch helper exited with unknown return code 1
[@kellojo/homebridge-http-webhooks D267] The selected advertiser, "resolved", isn't available on this platform. Reverting to "bonjour-hap"
```

### Configuration

```json
> /etc/systemd/resolved.conf as follow:

[Resolve]
DNS=1.1.1.1
FallbackDNS=1.0.0.1
MulticastDNS=yes
DNSStubListener=yes


> /etc/polkit-1/localauthority/30-site.d/homebridge.pkla as follow: 

[Homebridge ManageService]
Identity=unix-user:alex
Action=org.freedesktop.resolve1.register-service;org.freedesktop.resolve1.unregister-service
ResultAny=yes

> sudo systemctl status systemd-resolved.service
● systemd-resolved.service - Network Name Resolution
     Loaded: loaded (/lib/systemd/system/systemd-resolved.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2024-07-20 00:48:01 NZST; 20min ago
       Docs: man:systemd-resolved.service(8)
             man:org.freedesktop.resolve1(5)
             https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
             https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients
   Main PID: 12980 (systemd-resolve)
     Status: "Processing requests..."
      Tasks: 1 (limit: 3932)
        CPU: 356ms
     CGroup: /system.slice/systemd-resolved.service
             └─12980 /lib/systemd/systemd-resolved

Jul 20 00:48:01 raspberrypi systemd[1]: Starting Network Name Resolution...
Jul 20 00:48:01 raspberrypi systemd-resolved[12980]: Positive Trust Anchors:
Jul 20 00:48:01 raspberrypi systemd-resolved[12980]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
Jul 20 00:48:01 raspberrypi systemd-resolved[12980]: Negative trust anchors: 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa 19.172.in-addr.arpa 20.172.in-addr.ar>
Jul 20 00:48:01 raspberrypi systemd-resolved[12980]: Using system hostname 'raspberrypi'.
Jul 20 00:48:01 raspberrypi systemd[1]: Started Network Name Resolution.

❯ /etc/NetworkManager/NetworkManager.conf
[main]
plugins=ifupdown,keyfile
dns=systemd-resolved

[ifupdown]
managed=false
```

### Environment

- OS: Docker (on Raspbian Bullseye)
- Software: Homebridge v1.8.4 
- Node:  20.15.0
- npm: 10.7.0

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

Docker image: homebridge/homebridge

**Comment by donavanbecker** [comment]
Use ciao instead.

Clearly resolved isn't available on docker.

**Comment by Jafalex** [comment]
> Use ciao instead.
> 
> Clearly resolved isn't available on docker.

Thanks for the quick answer! I thought that could be the case, until I saw this post https://superuser.com/questions/1702091/how-should-systemd-resolved-and-docker-interact

Also, the HB page I linked above doesn't recommend using Ciao when HB is containerised.

**Comment by Jafalex** [comment]
Fixed my issue and can confirm nor Resolved no Avahi worked on my Raspberry Pi 4 when running Homebridge in docker. There seemed to be conflict with other mDNS services/applications on the network that I wasn't able to located and address. Back to Ciao.
