### ISSUE TITLE
Can’t update homebridge from 1.8.2 to 1.8.4

### ISSUE THREAD

**Issue by Stef1972** [homebridge/homebridge#3658]
### Describe The Bug

I receive this log:

```
USER: pi
DIR: /var/lib/homebridge
CMD: npm install --save homebridge@1.8.4
npm error code ENOTEMPTY
npm error syscall rename
npm error path /var/lib/homebridge/node_modules/home bridge
npm error dest /var/lib/homebridge/node_modules/.homebridge-WyWR98qy
npm error errno -39
npm error ENOTEMPTY: directory not empty, rename '/var/lib/homebridge/node_modules/homebridge' -> '/var/lib/homebridge/node_modules/.homebridge-WyWR98qy'
npm error A complete log of this run can be found in: /home/pi/.npm/_logs/2024-07-19T18_24_19_363Z-debug-0.log
```

Operation failed with code 217.

You can download this log file for future reference.

See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

### Homebridge UI Version

4.56.4

### Homebridge Version

1.8.2

### Node.js Version

20.15.1

### Operating System

Official Homebridge Raspberry Pi Image

### Environment Info

None

### Raspberry Pi Model

None

**Comment by donavanbecker** [comment]
you will need to remote into and execute the command outlined here: 
[Troubleshooting](https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting#unable-to-find-homebridge-installation)

**Comment by Stef1972** [comment]
Tried, but I receive the same error

**Comment by donavanbecker** [comment]
you will want to do a backup before doing these next commands

```
sudo rm -R /var/lib/homebridge/node_modules/.homebridge-WyWR98qy && rm -R /var/lib/homebridge/node_modules/homebridge && sudo npm install -g --unsafe-perm homebridge
```

**Comment by mkz212** [comment]
Sometimes easiest way is to: backup Homebridge, make fresh installation from newest Homebridge image and restore backup. You must know that sometimes the update is impossible, e.g. if you have Linux Bullseye and want to upgrade to Linux Bookworm.
