### ISSUE TITLE
1.8.4 accessory name warning

### ISSUE THREAD

**Issue by grzegorz914** [homebridge/homebridge#3660]
### Analysis

As You see in the log the plugin name itself generate warning in log console.

### Expected Behavior

No warning.

### Steps To Reproduce

Just install some plugin

### Logs

```markdown
[7/20/2024, 7:35:52 AM] Registering platform 'homebridge-enphase-envoy enphaseEnvoy'
[7/20/2024, 7:35:52 AM] [homebridge-enphase-envoy] Loaded homebridge-enphase-envoy v9.0.0-beta. 0 child bridge successfully
HAP-NodeJS WARNING: The accessory 'homebridge-enphase-envoy' has an invalid 'Name' characteristic ('homebridge-enphase-envoy'). Ple ase use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and
avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
[7/20/2024, 7:35:52 AM] Loaded 0 cached accessories from cachedAccessories.02054B191.
HAP-NodeJS WARNING: The accessory 'homebridge-enphase-envoy 793F' has
invalid 'Name'
93F'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric char acter, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
```

### Configuration

```json
N/A
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by donavanbecker** [comment]
Fix the name and the warning will go away.

**Comment by grzegorz914** [comment]
If I change the plugin name then get other error:

```[7/20/2024, 12:41:42 PM] One of your plugins incorrectly registered an external accessory using the platform name (Enphase Envoy) and not the plugin identifier. Please report this to the developer!```

**Comment by n0rt0nthec4t** [comment]
> Fix the name and the warning will go away.
@donavanbecker  As per the HAP-NodeJS pull discussions,  the dash character is perfectly acceptable to HomeKit and and really, should be allowed without warning.

**Comment by donavanbecker** [comment]
https://github.com/homebridge/HAP-NodeJS/pull/1054#issuecomment-2254133907
