### ISSUE TITLE
Homebridge 2.0  Unsupported plugin check 

### ISSUE THREAD

**Issue by rionshin** [homebridge/homebridge#3661]
### Current Situation

Users needs to know which plugins are not supported

### Proposed Change

Create a scan to identify which plugins are not 2.0 certified or have break changing code. 

### Additional Context

It will be great if users can scan and check plugins they are using before update to 2.0.

**Comment by donavanbecker** [comment]
v2 has breaking changes, plugin developers must make the updates to make sure their plugin is supported. 

Visit [Updating To Homebridge v2.0](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0) to find developer info and also plugins we have found have issues.

**Comment by rionshin** [comment]
> v2 has breaking changes, plugin developers must make the updates to make sure their plugin is supported.
> 
> Visit [Updating To Homebridge v2.0](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0) to find developer info and also plugins we have found have issues.

Yeah , i know, but some people has many plugins and its much easier if homebridge can identify which plugins are not updated and warn the user ;)

**Comment by donavanbecker** [comment]
We will be referring to that page in the release note.

**Comment by rionshin** [comment]
> We will be referring to that page in the release note.

So we wait till all plugins are updated to 2.0 compatibility . If plugin is updated to 2.0 will it be working with 1.* version of Homebridge ?

**Comment by bwp91** [comment]
> If plugin is updated to 2.0 will it be working with 1.* version of Homebridge ?

Yes updated plugins will still work with homebridge 1.x releases

A lot of plugins may not need updating at all and will work with homebridge 2 right away.

There are just a number of plugins which use old deprecated/removed functions that have been removed and so need to be updated.

**Comment by rionshin** [comment]
> > If plugin is updated to 2.0 will it be working with 1.* version of Homebridge ?
> 
> Yes updated plugins will still work with homebridge 1.x releases
> 
> A lot of plugins may not need updating at all and will work with homebridge 2 right away.
> 
> There are just a number of plugins which use old deprecated/removed functions that have been removed and so need to be updated.

Ok, clear, i thought it will affect all plugins, as this functions are commonly use.  Thank you !

**Comment by tavicu** [comment]
@donavanbecker have you planned a release period for v2?

**Comment by mitch7391** [comment]
Hey everyone, have we thought about updating the plug-in template too? Also I have found a few plug-ins that will break with the update and created issues for the developers on their pages; how do we go about adding them to the mentioned list?

**Comment by NorthernMan54** [comment]
Mention them here and we can add them to the wiki page

**Comment by bwp91** [comment]
the plugin template in fact does not need any code changes to support HB 2.0

**Comment by Quickstep3** [comment]
https://github.com/merdok/homebridge-webos-tv v2.4.4 fails under Homebridge 2.0 beta
Issues reported on plugin page https://github.com/merdok/homebridge-webos-tv/issues/537 with logs

**Comment by donavanbecker** [comment]
> https://github.com/merdok/homebridge-webos-tv v2.4.4 fails under Homebridge 2.0 beta Issues reported on plugin page [merdok/homebridge-webos-tv#537](https://github.com/merdok/homebridge-webos-tv/issues/537) with logs

Added to Wiki, thanks!

**Comment by mitch7391** [comment]
> Mention them here and we can add them to the wiki page

Thanks @NorthernMan54, I have found the following:

* [homebridge-cmd4](https://github.com/ztalbot2000/homebridge-cmd4)
* [homebridge-xiaomi-roborock-vacuum](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum)
* [homebridge-broadlink-rm](https://github.com/kiwi-cam/homebridge-broadlink-rm)
* [homebridge-BOMgovau](https://github.com/SteveCohen/homebridge-BOMgovau)

**Comment by donavanbecker** [comment]
> * [homebridge-cmd4](https://github.com/ztalbot2000/homebridge-cmd4)
> * [homebridge-xiaomi-roborock-vacuum](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum)
> * [homebridge-broadlink-rm](https://github.com/kiwi-cam/homebridge-broadlink-rm)
> * [homebridge-BOMgovau](https://github.com/SteveCohen/homebridge-BOMgovau)

These have all been added to the wiki. However, I did look at the issues that you have open on each repo and no logs have been provided. I would recommend providing the plugin developer with logs so it is easier to narrow down what needs to be updated to fix the plugin to support Homebridge v2.0.0

**Comment by mitch7391** [comment]
Thank you @donavanbecker, I will try and go back and collect some logs, surprised I got time to do that much newborn twins haha

**Comment by donavanbecker** [comment]
> surprised I got time to do that much newborn twins haha

That's awesome! Congrats!!🍾🎉🎈

**Comment by bwp91** [comment]
when reporting a plugin here for the wiki, please also keep us updated on any fixed versions so that we can keep the lists properly updated

**Comment by mitch7391** [comment]
homebridge-broadlink-rm [v4.4.18-beta.0](https://github.com/kiwi-cam/homebridge-broadlink-rm/releases/tag/v4.4.18-beta.0) appears to have been fixed.

**Comment by donavanbecker** [comment]
> homebridge-broadlink-rm [v4.4.18-beta.0](https://github.com/kiwi-cam/homebridge-broadlink-rm/releases/tag/v4.4.18-beta.0) appears to have been fixed.

added.

**Comment by mitch7391** [comment]
Might be a silly question guys, but which version should we be testing these against, the beta or the alpha? I had not noticed the alpha version initially...

**Comment by mitch7391** [comment]
Not sure if you guys are able to point us in the right direction, but we seem to be having a little trouble with accessories being removed on reboot with Homebridge v2 in the following plugin:

https://github.com/ztalbot2000/homebridge-cmd4/issues/146#issuecomment-2274635613

**Comment by muenzpraeger** [comment]
I ran a simple script to:
- get all npm packages that have `homebridge` in their name
- identify which ones have an associated GitHub repo
- grep which repos may need a change because of the breaking changes

Result:
- 1.2k npm packages without an associated GitHub repo
- 3.5k npm packages with an associated GitHub repo
- 2.5k repos that will be (very likely) affected by the breaking changes 🤷 

The script is _really_ basic, and eventually the checks are not very sophisticated (nor complete). So the mileage may vary. See the attached txt for preliminary results.

[breaking_changes.txt](https://github.com/user-attachments/files/16588474/breaking_changes.txt)

 ```bash
#!/bin/bash

# Variables to track counts
total_with_github=0
total_without_github=0
total_with_breaking_changes=0

# Input and temporary files
input_file="breaking_changes.txt"
temp_file="breaking_changes_temp.txt"
sorted_file="breaking_changes_sorted.txt"

# Function to search npmjs for packages with "homebridge" in the name
search_npmjs_packages() {
    local page=0
    local has_more=true
    > npm_packages.txt

    while $has_more; do
        echo "Fetching npmjs packages from page $page..."
        result=$(curl -s "https://registry.npmjs.org/-/v1/search?text=homebridge&size=20&from=$((page * 20))")
        echo "$result" | jq -r '.objects[].package | "\(.name) \(.links.repository)"' >> npm_packages.txt

        total=$(echo "$result" | jq -r '.total')
        current_page_size=$(echo "$result" | jq -r '.objects | length')

        if [ "$((page * 20 + current_page_size))" -ge "$total" ]; then
            has_more=false
        else
            page=$((page + 1))
        fi
    done
}

# Function to search a GitHub repo for breaking changes
search_github_for_breaking_changes() {
    local repo_url=$1
    local repo_name=$2
    local repo_has_changes=false
    
    echo "Searching $repo_name for breaking changes..."
    
    # Clone the repo into a temporary directory
    git clone --depth=1 $repo_url temp_repo > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "  - Failed to clone $repo_url"
        return
    fi

    cd temp_repo

    # Search for deprecated methods or breaking changes in the code
    grep -rnw '.' -e 'Characteristic.Formats' -e 'Characteristic.Perms' -e 'Characteristic.Units' -e 'getServiceByUUIDAndSubType' -e 'getValue()' -e 'updateReachability' -e 'BatteryService' -e 'BridgeConfiguration' -e 'BridgingState' -e 'CameraControl' -e 'CameraEventRecordingManagement' -e 'CloudRelay' -e 'TimeInformation' -e 'TunneledBTLEAccessoryService' -e 'StreamControllerOptions' | while read -r line ; do
        echo "  - $repo_name: $line" >> ../$input_file
        repo_has_changes=true
    done

    # If breaking changes were found, increment the counter
    if [ "$repo_has_changes" = true ]; then
        total_with_breaking_changes=$((total_with_breaking_changes + 1))
    fi

    # Cleanup
    cd ..
    rm -rf temp_repo
}

# Main script execution
echo "Starting the search for breaking changes in homebridge plugins..."

# Step 1: Search npmjs for packages with "homebridge" in their name
search_npmjs_packages

# Step 2: Parse GitHub repository URLs and search for breaking changes
while IFS= read -r line; do
    repo_name=$(echo $line | awk '{print $1}')
    repo_url=$(echo $line | awk '{print $2}')
    
    if [[ $repo_url == *"github.com"* ]]; then
        total_with_github=$((total_with_github + 1))

        # Extract the GitHub organization/user from the repo URL
        github_org=$(echo $repo_url | awk -F '/' '{print $4}')

        # Exclude the "homebridge" GitHub organization
        if [ "$github_org" != "homebridge" ]; then
            search_github_for_breaking_changes $repo_url $repo_name
        else
            echo "  - Skipping $repo_name: Repository belongs to 'homebridge' organization."
        fi
    else
        total_without_github=$((total_without_github + 1))
        echo "  - Skipping $repo_name: No GitHub repository link found."
    fi
done < npm_packages.txt

# Step 3: Cleanup `breaking_changes.txt`
grep -v 'getValue' "$input_file" > "$temp_file"
grep 'getValue()' "$input_file" >> "$temp_file"

# Replace the original file with the cleaned-up version
mv "$temp_file" "$input_file"

# Step 4: Sort the breaking changes file alphabetically
sort "$input_file" > "$sorted_file"
mv "$sorted_file" "$input_file"

# Step 5: Counting unique GitHub repositories
unique_repos=$(awk '{print $3}' "$input_file" | awk -F '/' '{print $4"/"$5}' | sort | uniq | wc -l)

# Final Output
echo "Cleanup complete. Only lines with 'getValue()' retained and file sorted alphabetically."
echo "Total number of npm packages with an associated GitHub repo: $total_with_github"
echo "Total number of npm packages without an associated GitHub repo: $total_without_github"
echo "Total number of unique GitHub repositories where at least one breaking change was identified: $unique_repos"
echo "Breaking changes identified in $total_with_breaking_changes repositories."
```

**Comment by muenzpraeger** [comment]
Given the vast amount of plugins (and potentially a good amount not well maintained) - thoughts about adding some runtime checks and warnings for 1.x versions?

This pull request [has a potential design](https://github.com/homebridge/homebridge/pull/3674) without modifying the core libraries.

**Comment by mkz212** [comment]
> Given the vast amount of plugins (and potentially a good amount not well maintained) - thoughts about adding some runtime checks and warnings for 1.x versions?
> 
> This pull request [has a potential design](https://github.com/homebridge/homebridge/pull/3674) without modifying the core libraries.

Interesting. Great potential. Not only as a tool to check whether the plugin meets the requirements of Homebridge 2.0, but also for other purposes - e.g. checking how many plugins there are in general and how many of them have been updated in the last year or two.

One thing: Sometimes it gives a lot of code in response and is therefore long and unreadable. I suggest that the list look like this:
- plugin name
- a specific file and line to which the comment relates
- short comment, e.g 'BatteryService is deprecated'.

E.G.: 
- homebridge-abc123 :: file.ts, line: 123 :: BatteryService is deprecated

How long does it take for such a script to check 3.5k packages?

**Comment by muenzpraeger** [comment]
@mkz212 The provided design doesn't lint the installed plugins (which could be an alternative approach), it's injecting itself into the runtime invocation for the specified elements.

For example when a new `Service.BatteryService` instance is created it'll log it. Or if there is a `get` call on the enum `Characteristic.Perms`.

There's def room for improvement on logging, as well as adding tracking to avoid duplicative log output. Before putting the work into that it's first important to have the discussion if this is something that would be applicable for the core homebridge package.

FWIW, it would also need a small change on the TS definition of the deprecated `Characteristic` enums (no `const`).

**Comment by mkz212** [comment]
> @mkz212 The provided design doesn't lint the installed plugins (which could be an alternative approach), it's injecting itself into the runtime invocation for the specified elements.
> 
> For example when a new `Service.BatteryService` instance is created it'll log it. Or if there is a `get` call on the enum `Characteristic.Perms`.
> 
> There's def room for improvement on logging, as well as adding tracking to avoid duplicative log output. Before putting the work into that it's first important to have the discussion if this is something that would be applicable for the core homebridge package.
> 
> FWIW, it would also need a small change on the TS definition of the deprecated `Characteristic` enums (no `const`).

We didn't understand each other.. I meant more about the script you posted higher, not the PR you added. About braking_changes.txt file.

**Comment by muenzpraeger** [comment]
Got it. You mentioned the PR that was put up in your message (guess b/c of using the reply action via email), hence I related to that.

The script took around 1.5h as it clones all the repos for inspection. I didn't want to mess with rate limits on the GitHub API.

Around the output -> sure, feel free to modify the output schema for your own needs.

For this initial run I think it's key to have detailed information, so that it's clear on first sight why the "violations" are detected without going into the code. There are def some false-positives in there (i. e. around `getValue`, which is very generic), or some people did commit their `node_modules` to the repo.

Lots of options from here on, like auto-generating a (very long) wiki page with supported/non-supported plugins, auto-creating GitHub issues, etc. etc.

**Comment by merdok** [comment]
@donavanbecker I have updated https://github.com/merdok/homebridge-webos-tv to support homebridge v2. 
As of version 2.4.5 it should now work.
Commit: https://github.com/merdok/homebridge-webos-tv/commit/7283f42c3032d599e3b269182983b1c1acb9fd0b
Could you please adjust the list in the wiki? thanks

**Comment by davidjbradshaw** [comment]
Has anyone asked whether the advantages of moving a few ENUMs is worth breaking over half the existing ecosystem? It does not seem like a good trade off to me.

it would be good to create some stats on which breaking changes cause the most issues, so a discussion on how worthwhile they are could be had.

**Comment by JurgenLB** [comment]
I found that Homebridge Rfx Shutter does not work on HomeBridge V2.0 and there is not must respons from the developer on the repo.
[https://github.com/howm/homebridge-rfx-shutter](url)

kind regards

**Comment by NorthernMan54** [comment]
@JurgenLB You could just try it out

**Comment by JurgenLB** [comment]
I already did.

This is the log error;
`USER: root
DIR: /var/lib/homebridge
CMD: npm install --save --omit=dev homebridge-rfx-shutter@2.1.1

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: undefined@undefined
npm error Found: homebridge@2.0.0-beta.29
npm error node_modules/homebridge
npm error   homebridge@"^2.0.0-beta.29" from the root project
npm error
npm error Could not resolve dependency:
npm error peer homebridge@"^1.3.4" from homebridge-rfx-shutter@2.1.1
npm error node_modules/homebridge-rfx-shutter
npm error   homebridge-rfx-shutter@"2.1.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/homebridge/.npm/_logs/2025-07-04T16_20_45_790Z-eresolve-report.txt
npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2025-07-04T16_20_45_790Z-debug-0.log

Error: Operation failed with code 1.
You can download this log file for future reference.`

I also have made a PR to update to version 2.0,
[https://github.com/howm/homebridge-rfx-shutter/pull/439/files](url)

kind regards

**Comment by Crajs20** [comment]
Homebridge-Homeatic will not work anymore under 2.0.0.
Details: https://github.com/thkl/homebridge-homematic/issues/738
