### ISSUE TITLE
Add Windows 11 instructions (or adapt Win10 to include Win11)

### ISSUE THREAD

**Issue by jsiegenthaler** [homebridge/homebridge#3676]
### Proposed Change

Add Win11 to the Win10 page, or add a separate Win11 page
Also need to check and update these pages:
https://homebridge.io/
https://homebridge.io/how-to-install-homebridge
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10
https://github.com/homebridge/homebridge/wiki

### Wiki Page Link

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10

**Comment by NorthernMan54** [comment]
@jsiegenthaler Would you be able to author these changes ?  We can add you as a maintainer.

**Comment by jsiegenthaler** [comment]
@NorthernMan54 sure, add me and I can do it

**Comment by NorthernMan54** [comment]
@jsiegenthaler If you check you should now have edit access to the Wiki.  Tks to @donavanbecker

**Comment by jsiegenthaler** [comment]
@NorthernMan54  I do have edit access. I'll try and edit tonight. I also see the NPM reference is very old, I'll update that as well

**Comment by jsiegenthaler** [comment]
@NorthernMan54 : have a look:
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10

**Comment by NorthernMan54** [comment]
Looks good, thank you

PS I'm a Mac user, so can't comment on the Windows install process.
