### ISSUE TITLE
Update All action

### ISSUE THREAD

**Issue by fluffy-critter** [homebridge/homebridge#3679]
### Current Situation

Right now it's a bit annoying to have to go through multiple phases of updating Homebridge (core, then UI, then each plugin individually) and then restarting Homebridge each time.

### Proposed Change

An "update all" button that runs the npm update process for all things pending updates simultaneously, possibly adding a separate "hold version" function to individual plugins that the user does not want to be mass-updated in this way for some reason.

### Additional Context

Since these are all NPM packages it seems like it should be possible to just update everything all at once, right?

**Comment by mkz212** [comment]
Run each plugin in child bridge mode then you won't have to restart Homebridge after the plugin is updated. 

Updates don't appear so often that it's a hassle. 

Before each update, a window appears with information about changes - sometimes it is a big change and sometimes the user does not want to update. How do you solve this if you provide one button to update all?

**Comment by fluffy-critter** [comment]
It's not just about the plugins, but also having to separately update the core and the UI.

I've been running Homebridge for several years now and only use a handful of plugins. I only ever update things when they stop working, usually due to an external API change (Switchbot is particularly notorious for this). If I didn't feel that it was getting annoying to deal with I wouldn't have made this feature request.
