### ISSUE TITLE
Homebridge app not available in Synology DSM Package Center

### ISSUE THREAD

**Issue by airart320** [homebridge/homebridge#3680]
### Analysis

Hello!
Added the repo https://synology.homebridge.io in Package Center sources 

Homebridge app not available for download.

SA6400 running DSM 7.2.1-69057 Update 5

### Expected Behavior

Homebridge app downloable

### Steps To Reproduce

1. Open Package Center in DSM and select the Settings option.
2. Select the Package Sources tab.
3. Click Add
4. In the Name section enter Homebridge
5. In the Location section enter https://synology.homebridge.io
6. Click OK
7. Go back to Package Center and search for Homebridge
8. Homebridge app not available 

### Logs

```markdown
-
```

### Configuration

```json
-
```

### Environment

- OS: DSM 7.2.1U5
- Software:
- Node: v20.09
- npm:

### Process Supervisor

not applicable

**Comment by vespino** [comment]
You can easily install it on Synology using Docker.

**Comment by airart320** [comment]
Doesn't solve the issue, does it?

**Comment by vespino** [comment]
Actually it does while Docker is a more stable solution running Homebridge on Synology.

**Comment by carlin010** [comment]
@airart320 I encountered the same problem and discovered that my DNS settings were the culprit. I had previously set up a local DNS, but after moving my device to a new network, I updated my DNS to 8.8.8.8 and 8.8.4.4. This allowed me to successfully add the source and download the homebridge package.
