### ISSUE TITLE
setProps for TargetHeaterCoolerState and TargetHeatingCoollingState not working

### ISSUE THREAD

**Issue by grzegorz914** [homebridge/homebridge#3682]
### Analysis

related to this code in HAP:  https://github.com/homebridge/HAP-NodeJS/blob/3652113ae28e33dd9b832dcc292e48c9a1463ffc/src/lib/definitions/CharacteristicDefinitions.ts#L4172i

my accessory TargetHeaterCoolerState is set to:
```
setProps({
                 minValue: 1,
                 maxValue: 2,
                 validValues: [1, 2] //HEAT, COOL
})
```
but isn't working. The accessory display all model `AUTO, HEAT, COOL`

### Expected Behavior

Display configured modes only

### Steps To Reproduce

Just create Thermostat or Heather/Cooler accessory with this setProps config

### Logs

```markdown
N/A
```

### Configuration

```json
N/A
```

### Environment

- OS: macOS
- Software: HB 1.8.4 and 2.0.0 beta
- Node: 20.17.0
- npm: 

### Process Supervisor

hb-service

**Comment by ebaauw** [comment]
I doubt this is an issue with Homebridge / HAP-NodeKS.  In my experience HomeKit apps (notably Apple's Home app) simply don't always honour these settings.  Best check with HomeSpy whether the properties have actually been set.

I use OFF, HEAT as min/max values (no valid values) on my thermostats, but Home displays all four options (OFF, HEAT, COOL, AUTO) anyway.  Eve only shows an On/Off switch for _Mode_, which corresponds to HEAT, OFF (as their Eve Thermo cannot cool).  Home+ correctly shows only OFF and HEAT.  HomeSpy show the correct min and max values.

I see the same on other characteristics, notably _Programmable Switch Event_.

**Comment by grzegorz914** [comment]
Hm, i have parallel run openHAB with HomeKit integration, so the Thermostat and Heather/Cooler accepted validValues and  in HomeKit app display only configured modes. So must be something wrong in HAP or Homebridge itself.

**Comment by ebaauw** [comment]
Did you check in HomeSpy how the openHAB accessory is exposed?  Is that any different from your accessory?

**Comment by grzegorz914** [comment]
HomeSpy app is not available in PL App Store

**Comment by grzegorz914** [comment]
Strange is that Homebridge UI also display all modes instead the configured modes.

**Comment by bwp91** [comment]
This may be unsuccessful, but you could try:
 - removing the accessory from the cache so it is re-added and the characteristic set props are used at the point of it being added
 - restart homekit network, old props might get cached and it needs a reboot to apply the valid values
 - ensure that the value of the characteristic is never `0` even the first time the accessory is added

**Comment by bwp91** [comment]
i’ve had some success in the past hiding modes from a purifier service.

But i haven’t tried it in a long time and it might be that a newer version of ios stopped modes being hidden
