### ISSUE TITLE
HB 1.3.5 update crashes my Pi, reinstall does not help

### ISSUE THREAD

**Issue by bondskin** [homebridge/homebridge#3692]
### Analysis

I just updated home bridge von my Bookworm Pi installation, coming from 1.3.4
The Pi crashed during configuration.

Update #1: I have re-installed the package but still not successful.

Update #2: purge the installation and installed 1.3.5, seems to be stable now

> pi@raspberrypi64:~ $ sudo apt install --reinstall homebridge
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> 0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
> 1 not fully installed or removed.
> Need to get 39.8 MB of archives.
> After this operation, 0 B of additional disk space will be used.
> Get:1 https://repo.homebridge.io stable/main arm64 homebridge arm64 1.3.5 [39.8 MB]
> Fetched 39.8 MB in 3s (12.8 MB/s)
> (Reading database ... 171948 files and directories currently installed.)
> Preparing to unpack .../homebridge_1.3.5_arm64.deb ...
> Running pre-upgrade steps...
> Stopping Homebridge service...
> Unpacking may take several minutes on low powered devices.
> Unpacking homebridge (1.3.5) over (1.3.5) ...
> dpkg: error processing archive /var/cache/apt/archives/homebridge_1.3.5_arm64.deb (--unpack):
>  unable to securely remove '/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/common/services/index.js.dpkg-tmp': Read-only file system
> dpkg: error while cleaning up:
>  unable to securely remove '/var/lib/dpkg/tmp.ci': Read-only file system
> dpkg: error: unable to create new file '/var/lib/dpkg/status-new': Read-only file system
> /usr/lib/needrestart/dpkg-status: 37: touch: Input/output error
> E: Sub-process /usr/bin/dpkg returned an error code (2)
> W: Problem unlinking the file /var/cache/apt/pkgcache.bin - pkgDPkgPM::Go (30: Read-only file system)
> E: Problem executing scripts DPkg::Post-Invoke 'test -x /home/pi/reboot-notification.sh && /home/pi/reboot-notification.sh|| true'
> E: Sub-process returned an error code

### Expected Behavior

succesful update from 1.3.4 to 1.3.5

### Steps To Reproduce

tried it twice, same result

### Logs

```markdown
pi@raspberrypi64:~ $ sudo apt install --reinstall homebridge
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 39.8 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://repo.homebridge.io stable/main arm64 homebridge arm64 1.3.5 [39.8 MB]
Fetched 39.8 MB in 3s (12.8 MB/s)
(Reading database ... 171948 files and directories currently installed.)
Preparing to unpack .../homebridge_1.3.5_arm64.deb ...
Running pre-upgrade steps...
Stopping Homebridge service...
Unpacking may take several minutes on low powered devices.
Unpacking homebridge (1.3.5) over (1.3.5) ...
dpkg: error processing archive /var/cache/apt/archives/homebridge_1.3.5_arm64.deb (--unpack):
 unable to securely remove '/opt/homebridge/lib/node_modules/homebridge-config-ui-x/node_modules/@nestjs/common/services/index.js.dpkg-tmp': Read-only file system
dpkg: error while cleaning up:
 unable to securely remove '/var/lib/dpkg/tmp.ci': Read-only file system
dpkg: error: unable to create new file '/var/lib/dpkg/status-new': Read-only file system
/usr/lib/needrestart/dpkg-status: 37: touch: Input/output error
E: Sub-process /usr/bin/dpkg returned an error code (2)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - pkgDPkgPM::Go (30: Read-only file system)
E: Problem executing scripts DPkg::Post-Invoke 'test -x /home/pi/reboot-notification.sh && /home/pi/reboot-notification.sh|| true'
E: Sub-process returned an error code
```

### Configuration

```json
"bridge": {
        "name": "Homebridge DA8A",
        "username": "0E:62:8A:C9:DA:8A",
        "port": 51001,
        "pin": "420-69-285",
        "log": {
            "method": "file",
            "path": "/var/log/homebridge.log"
        },
        "advertiser": "avahi",
        "bind": [
            "eth0"
        ]
    },
```

### Environment

- OS: Bookworm
- Software: Linux raspberrypi64 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux
- Node: 20.17.0
- npm: 10.8.2

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Please try the install again, we re published the package as it appears that apt pkg 1.3.5 has caused problems for people
