### ISSUE TITLE
After Apple Home hubs upgrade to OS v18: Delegate finished streaming... without setting RecordingPacket.isLast. Cant notify Controller about endOfStream

### ISSUE THREAD

**Issue by Kositch** [homebridge/homebridge#3696]
### Current Situation

After performing update to all Home hubs to current version 18 I started getting those error messages in Homebridge log (see Logs screenshot below). I have 2 cameras via Camer.UI plugin which seems to be working without any problems in HKSV mode (notifying about event, recording events, no issue here except slow live feed). I am not sure even, if it is this Camera plugin related or it is general Homebridge error, because there is no prefix of plugin nema before the message. Version of everything in screenshot here with logs.

![2024-09-19_13-32-41](https://github.com/user-attachments/assets/de656c3c-a2f4-4c16-9479-72c5820aad5b)

### Logs

```markdown
See screenshot above.
```

### Configuration

```json
N/A
```

### Environment

- OS: macOS Sonoma
- Software: Homebridge 1.8.4
- Node: 20.17
- npm: 10.8.

### Process Supervisor

hb-service

**Comment by mkz212** [comment]
There is new version of camera.ui (currently alpha version but it works very well when it comes to HomeKit). You can add there every IP camera.

https://github.com/seydx/camera.ui/issues/448

**Comment by Kositch** [comment]
> There is new version of camera.ui (currently alpha version but it works very well when it comes to HomeKit). You can add there every IP camera.
> 
> [seydx/camera.ui#448](https://github.com/seydx/camera.ui/issues/448)

I know, it is not public yet and I am not in a hurry with that when everything with old plugin version works. I was just curious how update of Apple hubs can cause those messages and what they mean when Camera.UI works (records, notyfies, cameras are live..).

**Comment by Kositch** [comment]
Issue resolved by hb-service restart, closing the ticket.
