### ISSUE TITLE
ENOTFOUND/ECONNRESET and getaddrinfo: random errors in log on Homebridge running on Mac OS

### ISSUE THREAD

**Issue by Kositch** [homebridge/homebridge#3697]
### Current Situation

Mayby some devs or someone facing same behaviour can help me - I have moved from RPi4 to Mac Mini M1, Homebridge is running fine and is much faster, but when I check logs, I see sometimes some connection error (ENOTFOUND and getaddrinfo) on different plugins in different times. It take usually a few seconds and issue resolves by itself without any restarts and everything is running fine, but this was not happening on RPi4.

Except Homebridge I am running also Node-RED and Unifi servers without any issues on same Mac. Node-RED is performing lots of communication to the internet each few seconds and no errors during the times when those errors happen in homebridge, so I suppose it is not internet outage related issue.

See examples of logs below.

Network is pretty stable (Unifi), Mac is connected on LAN and also WiFi.

Any ideas, what can cause that and what could I do? Many thanks!

### Logs

```markdown
[0;37m[9/20/2024, 3:54:57 PM] [0m[0;36m[Homebridge UI][0m [homebridge-airthings] Failed to check registry.npmjs.org for updates: "getaddrinfo ENOTFOUND registry.npmjs.org" - see https://homebridge.io/w/JJSz6 for help.

[37m[9/18/2024, 3:28:53 PM] [39m[36m[Connexoon][39m [31mFailed to get the list of events Error: getaddrinfo ENOTFOUND ha101-1.overkiz.com[39m
[31m    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {[39m
[31m  errno: -3008,[39m
[31m  code: 'ENOTFOUND',[39m
[31m  syscall: 'getaddrinfo',[39m
[31m  hostname: 'ha101-1.overkiz.com'[39m
[31m}[39m

[0;37m[9/20/2024, 3:54:57 PM] [0m[0;36m[Homebridge UI][0m [homebridge-airthings] Failed to check registry.npmjs.org for updates: "getaddrinfo ENOTFOUND registry.npmjs.org" - see https://homebridge.io/w/JJSz6 for help.


[37m[9/22/2024, 12:33:12 AM] [39m[36m[@0x5e/homebridge-tuya-platform][39m [31m[TuyaOpenMQ] Error: Error: getaddrinfo ENOTFOUND m1.tuyaeu.com[39m
[31m    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {[39m
[31m  errno: -3008,[39m
[31m  code: 'ENOTFOUND',[39m
[31m  syscall: 'getaddrinfo',[39m
[31m  hostname: 'm1.tuyaeu.com'[39m
[31m}[39m
```

### Configuration

```json
Not any plugin config related.
```

### Environment

OS: Mac OS 14.6.1
Node.js: v20.17.0
Homebridge version: 1.8.4
NPM version: 10.8.2
Node.js Path: /usr/local/bin
Homebridge location: /Users/michal/.homebridge
Config location: /Users/michal/.homebridge/config.json
Plugin location: /usr/local/lib/node_modules
IPv4 (en0): 10.0.0.38
IPv6 (en0): fe80::c66:8a9f:61ce:e5f3

### Process Supervisor

hb-service

**Comment by Apollon77** [comment]
Check your DNS and name resolving because this error means that the domain could not be resolved

**Comment by Kositch** [comment]
> Check your DNS and name resolving because this error means that the domain could not be resolved

Yeah, I have found that, but no issue with that on any of devices inside same network and as I write, it happens few times a day just for a few seconds.
