### ISSUE TITLE
English error on https://developers.homebridge.io/#/api/characteristics

### ISSUE THREAD

**Issue by jsiegenthaler** [homebridge/homebridge#3698]
### Analysis

English error on https://developers.homebridge.io/#/api/characteristics
Section "Characteristic.onSet"
This sentence makes no sense:
"value: This the value device should be changed to."

### Expected Behavior

Fix the sentence "value: This the value device should be changed to."
Maybe it should be "value: This is the value the device should be changed to."

### Steps To Reproduce

Open https://developers.homebridge.io/#/api/characteristics in browser
View the section Characteristic.onSet
Read the sentence "value: This the value device should be changed to."

### Logs

```markdown
n/a
```

### Configuration

```json
n/a
```

### Environment

n/a

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Tks for pointing this out, I have corrected the rough wording

https://github.com/homebridge/homebridge.github.io/pull/59
