### ISSUE TITLE
Govee COB strip light

### ISSUE THREAD

**Issue by dan77g** [homebridge/homebridge#3702]
### Analysis

[COB Strip Light 2] is not currently supported, do create a Github issue with the following info:
{"ip":"10.0.0.103","device":"2A:A7:CF:C8:00:86:36:17","sku":"H61E6","bleVersionHard":"3.05.00","bleVersionSoft":"1.00.10","wifiVersionHard":"1.04.01","wifiVersionSoft":"1.01.17","httpInfo":{"groupId":0,"device":"2A:A7:CF:C8:00:86:36:17","sku":"H61E6","spec":"","versionHard":"3.05.00","versionSoft":"1.00.10","deviceName":"COB Strip Light 2","deviceExt":{"deviceSettings":"{\"wifiName\":\"cathdan\",\"address\":\"CF:C8:00:86:36:17\",\"bleName\":\"Govee_H61E6_3617\",\"topic\":\"GD/aee8226088c822368d430a71f0822c49\",\"wifiMac\":\"D0:C9:07:9A:C8:50\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.01.17\",\"wifiHardVersion\":\"1.04.01\",\"ic\":60,\"secretCode\":\"lEggJ+9p2fg=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H61E6\",\"device\":\"2A:A7:CF:C8:00:86:36:17\",\"deviceName\":\"COB Strip Light 2\",\"versionHard\":\"3.05.00\",\"versionSoft\":\"1.00.10\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/9cdee2111cfec739a5def963b77cbecb-add_list_type_device_61e6.png\",\"headOnImg\":\"\",\"headOnImgNew\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/363f43f15b4a541b4008d85c6a2c4a64-light_pics_61e5e6_on.png\",\"headOffImg\":\"\",\"headOffImgNew\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/22bf9eb6791678e031f4653059ed5e87-light_pics_61e5e6_off.png\",\"ext\":\"\",\"ic\":60}"},"pactType":1,"pactCode":1,"share":0,"deviceId":23995801,"gidConfirmed":true,"goodsType":246,"attributesId":103,"supportScene":0},"model":"H61E6","deviceName":"COB Strip Light 2","isLANDevice":true}

### Expected Behavior

a signaute for the above item

### Steps To Reproduce

restart the plugin govee

### Logs

```markdown
[COB Strip Light 2] is not currently supported, do create a Github issue with the following info:
{"ip":"10.0.0.103","device":"2A:A7:CF:C8:00:86:36:17","sku":"H61E6","bleVersionHard":"3.05.00","bleVersionSoft":"1.00.10","wifiVersionHard":"1.04.01","wifiVersionSoft":"1.01.17","httpInfo":{"groupId":0,"device":"2A:A7:CF:C8:00:86:36:17","sku":"H61E6","spec":"","versionHard":"3.05.00","versionSoft":"1.00.10","deviceName":"COB Strip Light 2","deviceExt":{"deviceSettings":"{\"wifiName\":\"cathdan\",\"address\":\"CF:C8:00:86:36:17\",\"bleName\":\"Govee_H61E6_3617\",\"topic\":\"GD/aee8226088c822368d430a71f0822c49\",\"wifiMac\":\"D0:C9:07:9A:C8:50\",\"pactType\":1,\"pactCode\":1,\"wifiSoftVersion\":\"1.01.17\",\"wifiHardVersion\":\"1.04.01\",\"ic\":60,\"secretCode\":\"lEggJ+9p2fg=\",\"boilWaterCompletedNotiOnOff\":1,\"completionNotiOnOff\":1,\"autoShutDownOnOff\":1,\"sku\":\"H61E6\",\"device\":\"2A:A7:CF:C8:00:86:36:17\",\"deviceName\":\"COB Strip Light 2\",\"versionHard\":\"3.05.00\",\"versionSoft\":\"1.00.10\",\"playState\":false}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/9cdee2111cfec739a5def963b77cbecb-add_list_type_device_61e6.png\",\"headOnImg\":\"\",\"headOnImgNew\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/363f43f15b4a541b4008d85c6a2c4a64-light_pics_61e5e6_on.png\",\"headOffImg\":\"\",\"headOffImgNew\":\"https://d1f2504ijhdyjw.cloudfront.net/sku-img/22bf9eb6791678e031f4653059ed5e87-light_pics_61e5e6_off.png\",\"ext\":\"\",\"ic\":60}"},"pactType":1,"pactCode":1,"share":0,"deviceId":23995801,"gidConfirmed":true,"goodsType":246,"attributesId":103,"supportScene":0},"model":"H61E6","deviceName":"COB Strip Light 2","isLANDevice":true}
```

### Configuration

```json
default
```

### Environment

- OS: sinology
- Software: latest
- Node:
- npm:

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
This is for the Govee plugin, please raise the issue there, so the developer is aware
