### ISSUE TITLE
Add Auto-Update Feature for Plugins and Homebridge Core

### ISSUE THREAD

**Issue by jcherrera** [homebridge/homebridge#3710]
### Current Situation

Currently, Homebridge requires manual intervention to update plugins and the core application. This can be a significant inconvenience for users, especially when outdated plugins cause integrations (such as with Ring cameras) to break. For example, I’ve experienced issues where my Ring cameras stopped working because a plugin wasn’t updated. This leads to extra work to monitor and manually update plugins regularly, which can be avoided.

### Proposed Change

Introduce an option within Homebridge to enable automatic updates for:

1. **Plugins** – Similar to how WordPress offers an automatic update feature, Homebridge should allow users to opt-in for auto-updates of installed plugins.
2. **Homebridge Core** – An additional option to auto-update the core application itself would be beneficial.
3. **Node.js** (if possible) – Automatically update Node.js to its latest compatible version to avoid potential issues with older Node versions breaking functionality.

These automatic updates should be optional, and users should be able to toggle them on/off for each component (plugins, core, and Node.js).

### Additional Context

This feature would greatly enhance the user experience by removing the need to manually manage updates and ensuring that Homebridge setups remain functional with minimal maintenance. It could prevent system failures or integrations from breaking due to outdated plugins or core software.

Thank you for considering this feature! It would help many users like myself streamline Homebridge management and reduce the risk of broken plugins impacting daily use.

**Comment by jcherrera** [comment]
😭

**Comment by ihatetoregister** [comment]
Alternative solution:
1. install unattened-upgrades
2. add "site=repo.homebridge.io" to Origins-Pattern in /etc/apt/apt.conf.d/50unattended-upgrades
3. reboot
