### ISSUE TITLE
can not update node.js using hb-service update-node 

### ISSUE THREAD

**Issue by idle0095** [homebridge/homebridge#3714]
### Analysis

 hb-service update-node 
ℹ Updating Node.js from v20.9.0 to v20.18.0...
✖ Cannot update Node.js on your system. Non-standard installation path detected: /volume1/@appstore/Node.js_v20/usr/local

### Expected Behavior

 hb-service update-node 
ℹ Updating Node.js from v20.9.0 to v20.18.0...
✖ Cannot update Node.js on your system. Non-standard installation path detected: /volume1/@appstore/Node.js_v20/usr/local

### Steps To Reproduce

 hb-service update-node 
ℹ Updating Node.js from v20.9.0 to v20.18.0...
✖ Cannot update Node.js on your system. Non-standard installation path detected: /volume1/@appstore/Node.js_v20/usr/local

### Logs

```markdown
hb-service update-node 
ℹ Updating Node.js from v20.9.0 to v20.18.0...
✖ Cannot update Node.js on your system. Non-standard installation path detected: /volume1/@appstore/Node.js_v20/usr/local
```

### Configuration

```json
hb-service update-node 
ℹ Updating Node.js from v20.9.0 to v20.18.0...
✖ Cannot update Node.js on your system. Non-standard installation path detected: /volume1/@appstore/Node.js_v20/usr/local
```

### Environment

 hb-service update-node 
ℹ Updating Node.js from v20.9.0 to v20.18.0...
✖ Cannot update Node.js on your system. Non-standard installation path detected: /volume1/@appstore/Node.js_v20/usr/local

### Process Supervisor

hb-service

### Additional Context

 hb-service update-node 
ℹ Updating Node.js from v20.9.0 to v20.18.0...
✖ Cannot update Node.js on your system. Non-standard installation path detected: /volume1/@appstore/Node.js_v20/usr/local

**Comment by NorthernMan54** [comment]
This appears to be a vendor supplied nodejs install, what platform is this ?
