### ISSUE TITLE
Cannot add Homebridge to Home app

### ISSUE THREAD

**Issue by Neighborkid01** [homebridge/homebridge#3717]
### Current Situation

I'm having issues with my HomeBridge setup. I have it running on my Mac mini and everything was working until I ran a software update a few days ago. Now all my devices show as unresponsive in the Home app, but I can toggle them all in the HomeBridge UI. I deleted the bridge from the Home app, but now every time I try to add the bridge back, the Home app gives me the error "Accessory Not Found: You may need to restart your accessory before you can add it to your home."

I have run `dns-sd -B _hap._tcp local` and Homebridge shows up there. I've restarted Homebridge, my iPhone, and Mac mini countless times, I've signed in and out of iCloud, I've deleted the accessory cache and persist directories, I've disabled and reenabled by firewall rules as well. None of this has made any difference as far as I can tell. I've restarted Homebridge in debug mode a few times and never saw anything in the logs that looked like my phone trying to add the bridge and failing.

I'm completely at a loss for things to try, so any help would be greatly appreciated.

### Logs

```markdown
See additional context
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:31",
        "port": 51826,
        "pin": "031-45-154",
        "advertiser": "ciao"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "broadcast": "192.168.255.255",
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "devices": [
                // ...
            ],
            "devicesUseDiscoveryPort": false,
            "_bridge": {
                "username": "0E:64:BB:A3:1A:C3"
            },
            "platform": "TplinkSmarthome"
        }
    ],
    "accessories": []
}
```

### Environment

- OS: macOS 15.0.1
- Software: Homebridge 1.8.4
- Node:  20.9.0
- npm: 8.8.0

### Process Supervisor

hb-service

### Additional Context

[homebridge.log](https://github.com/user-attachments/files/17452890/homebridge.log)

**Comment by NorthernMan54** [comment]
Do you have this issue ? https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS#macos-150--sequoia

**Comment by Neighborkid01** [comment]
Holy crap that fixed it! Thank you so much!

**Comment by back-2-95** [comment]
I have macOS 15.1 and I got Node 20.15 installed with nvm. First the connection did not work but after I updated Node to 20.18 with nvm, then it just worked 🤷‍♂️
