### ISSUE TITLE
Error When Trying To Install Plugins on fresh install of Homebridge

### ISSUE THREAD

**Issue by bhamblinonair** [homebridge/homebridge#3720]
### Current Situation

I have just recently gotten Homebridge setup, but I'm unable to install them from the GUI.

The error I get is the following (Error: The module '\\?\C:\Users\tlcole\AppData\Roaming\npm\node_modules\homebridge-config-ui-x\node_modules\@homebridge\node-pty-prebuilt-multiarch\build\Release\conpty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 115. This version of Node.js requires
NODE_MODULE_VERSION 131. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).)

ANY and all help would be GREATLY appreciated!

Thank you! 

### Logs

```markdown
Not sure how to access this information
```

### Configuration

```json
N/A
```

### Environment

- OS: Windows 11 24H2
- Software: V4.62.0
- Node: v20.18.0
- npm: 10.8.2

### Process Supervisor

not applicable

**Comment by NorthernMan54** [comment]
Did you change NodeJS version ?  You will need to redo the installation to fix the issue

**Comment by bhamblinonair** [comment]
> Did you change NodeJS version ? You will need to redo the installation to fix the issue

@NorthernMan54 I don’t believe I changed the version of NodeJS… Should I completely uninstall the NodeJS program and reinstall it? Or is there another way to do it? I’m completely new to this and I’m very confused.

**Comment by bwp91** [comment]
I think you need to install `homebridge-config-ui-x` so that it is build against the new node version.

Do you know the command that you would use to install/uninstall an npm package?

**Comment by bhamblinonair** [comment]
Thank you, @NorthernMan54 & @bwp91 for your help, I am now able to install plugins on Homebridge, but I am now not able to get them to communicate to Homekit. Homekit says "Accessory Not Found You may need to restart your accessory before you can add it to your home". both the host computer (Windows 11 Pro) and my iOS Device are on the same WIFI network. I can't figure it out. I am able to see and interact with the devices via the accessories tab in homebridge, but that's all.

**Comment by bwp91** [comment]
Maybe try setting your mdns advertiser to ciao

https://github.com/homebridge/homebridge/wiki/mDNS-Options#how-to-set-mdns-advertiser
