### ISSUE TITLE
I can't install plugins after update Raspbian

### ISSUE THREAD

**Issue by SzilagyiR** [homebridge/homebridge#3724]
### Current Situation

I updated my Pi Raspbian and now I can't update or install any plugins. The error is the same all time.

### Logs

```markdown
USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-webos-tv@2.4.5
sudo: jelszó szükséges

Error: Operation failed with code 1.

You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.
```

### Configuration

```json
-
```

### Environment

- OS: Raspbian
- Node: v22.11
- npm: v10.9

### Process Supervisor

hb-service

### Additional Context

![hberror](https://github.com/user-attachments/assets/238416e7-828e-4b27-a6fb-736ef1c5d35b)

**Comment by SzilagyiR** [comment]
The problem solved with this post: https://www.reddit.com/r/homebridge/comments/j99i1o/help_with_sudo_in_the_configuix_terminal/

The new problem is here:

USER: homebridge
DIR: /usr
CMD: sudo -E -n npm install -g homebridge-webos-tv@2.4.5
> bufferutil@4.0.8 install
> node-gyp-build
make: Entering directory '/usr/lib/node_modules/homebridge-webos-tv/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
make: g++: Nincs ilyen fájl vagy könyvtár
make: *** [bufferutil.target.mk:134: Release/obj.target/bufferutil.node] Error 127
make: Leaving directory '/usr/lib/node_modules/homebridge-webos-tv/node_modules/bufferutil/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:216:23)
gyp ERR! System Linux 5.10.103-v7l+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-webos-tv/node_modules/bufferutil
gyp ERR! node -v v22.11.0
gyp ERR! node-gyp -v v10.2.0
gyp ERR! not ok
npm error code 1
npm error path /usr/lib/node_modules/homebridge-webos-tv/node_modules/bufferutil
npm error command failed
npm error command sh -c node-gyp-build
npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-11-02T18_12_48_664Z-debug-0.lo


Error: Operation failed with code 1.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

**Comment by NorthernMan54** [comment]
This is a bit odd, how did you update your RPI?

**Comment by SzilagyiR** [comment]
I did it based on this description. https://www.linuxuprising.com/2021/11/how-to-upgrade-raspberry-pi-os-10.html

**Comment by SzilagyiR** [comment]
The problem solved!
https://github.com/homebridge/homebridge-config-ui-x/issues/2030

sudo apt install build-essential

**Comment by NorthernMan54** [comment]
Tks for sharing
