### ISSUE TITLE
Automations?

### ISSUE THREAD

**Issue by aardvark123456789** [homebridge/homebridge#3725]
### Current Situation

Hello, not seeing the option for automations with my Homebridge-connected water shutoff. Would like to if this, then that in the Home app. Is this intentionally disabled or am I doing something wrong?

### Proposed Change

Enable automations with devices.

**Comment by NorthernMan54** [comment]
That's odd, are you seeing the devices in the HomeApp ?  Have you tried the Eve app ?

**Comment by aardvark123456789** [comment]
> That's odd, are you seeing the devices in the HomeApp ? Have you tried the Eve app ?

Thank you for the reply - I see it in Eve (oddly) and can even make an automation there, but still not seeing it in Home, even on the created automation? Kinda bizarre.

Edit: Just removed, then re-added the YoLink plugin - still nothing.

![image](https://github.com/user-attachments/assets/ff64afe1-f168-43cb-be34-2f1fafe9edf2)
![image](https://github.com/user-attachments/assets/473550e0-95cb-4cf9-b0ec-8058d25342cd)
![image](https://github.com/user-attachments/assets/9a061617-fadf-409b-9030-3b3324e366a4)

**Comment by NorthernMan54** [comment]
I don't have a valve to test with, but it is know that the Eve app supports more accessory types and has more automation options than the Home app.  So I think the valve type is another of these.

**Comment by aardvark123456789** [comment]
> I don't have a valve to test with, but it is know that the Eve app supports more accessory types and has more automation options than the Home app. So I think the valve type is another of these.

Makes sense. Using Eve, I was able to create an automation - which seems to work when I test it in the Home app - even though it doesn't display the valve itself!

![image](https://github.com/user-attachments/assets/4e4b8f7e-a179-4d11-b9dc-85fc248f6823)
![image](https://github.com/user-attachments/assets/d6a22f86-3771-44dd-9e4d-1ef268e85fc2)
