### ISSUE TITLE
Shutdown homebridge plugin programatically

### ISSUE THREAD

**Issue by maxileith** [homebridge/homebridge#3729]
### Current Situation

Hi,

as a plugin developer I have certain situations where I want to stop the plugin programatically. On startup my plugin checks if the environment is compatible with my plugin, e.g. if the Python version is supported.

In case a criteria is not met, the plugin won't finish the boot procedure, instead it is entering an endless loop:

```typescript
            while (true) {
                this.log.error(`Python ${version} is installed. However, only Python \
${supportedPythonVersions[0]} to ${supportedPythonVersions[supportedPythonVersions.length - 1]} is supported.`);
                await delay(300000);
            }
```

### Proposed Change

Instead of entering an endless loop, I would love to just call some kind of `shutdownPlugin()` method that I can import from the homebridge package. That way I could shutdown the plugin programatically and the user can just start the plugin via the UI again once he fixed the environment.

**Comment by hjdhjd** [comment]
You can already effectively shutdown a plugin by returning rather than sleeping in your code snippet. User can restart the plugin once they’ve resolved the issue through the Homebridge webUI.

I do a version of this across several of my plugins…there’s not really a need for anything else here, but open to hearing a meaningful use case / argument for it.

**Comment by maxileith** [comment]
Hi @hjdhjd,

thanks for the fast response. When I am exiting by calling `process.exit(0):` the plugin will be restarted by homebridge. Maybe I am missing something obvious.

**Comment by hjdhjd** [comment]
Don’t do that. 😄 

Just literally return. Don’t exit the process.

```
if(some condition you want is not met) {

  return;
}
```

That’s it.

**Comment by maxileith** [comment]
Yeah, but then I am just skipping the rest of the method that I am currently in. In which method do I have to do that to shutdown the plugin?

I don't really get it ^^.

**Comment by hjdhjd** [comment]
Plugins are essentially fancy callbacks from Homebridge. You can return from the “callback” anytime, effectively stopping the instance.

Plugins are instantiated as a class with a specific contract. Simply return from the class. It’s as simple as that.

I’ll refer you to one of my plugins with a real life working example - all my plugins are pretty extensively documented:

https://github.com/hjdhjd/homebridge-unifi-protect/blob/87fc75de4671ded6c0f5a7eb194c5721b8f35818/src/protect-platform.ts#L65

**Comment by maxileith** [comment]
Now it is clear. Thanks!

"Just return" was a bit rudimentary as an explenation ;)

**Comment by hjdhjd** [comment]
> Now it is clear. Thanks!
> 
> "Just return" was a bit rudimentary as an explenation ;)

I gave you a code sample and then a link to actual code! 😄

**Comment by maxileith** [comment]
> > Now it is clear. Thanks!
> 
> > 
> 
> > "Just return" was a bit rudimentary as an explenation ;)
> 
> 
> 
> I gave you a code sample and then a link to actual code! 😄

Yeah, all good. The link was very helpful. But the first code sample was just a generic return basically. That could be anywhere in the code.

Anyhow, thanks a lot!
