### ISSUE TITLE
plugin 'Hue' stopped after upgrade 1.8.5

### ISSUE THREAD

**Issue by skipper79** [homebridge/homebridge#3734]
### Analysis

After Homebridge update v1.8.5 connection with my plugin 'Hue' gives an error: `This plugin is taking long tie to load and preventing Homebridge from starting`. I installed also a previous version with the same result. 
Homebridge is still in status 'Starting'

### Expected Behavior

After pressing the link button on the Philips Hue, no error should appear 

### Steps To Reproduce

Update Homebridge till version 1.8.5

### Logs

```markdown
[11/12/2024, 8:55:42 AM] [Hue] Hue Bridge: request 8: POST / {"devicetype":"homebridge-hue#homeassistant"}
[11/12/2024, 8:55:42 AM] [Hue] Hue Bridge: press link button on the bridge to create a user - retrying in 15s
[11/12/2024, 8:55:42 AM] [Hue] Hue Bridge: request 8: : api error 101: link button not pressed
[11/12/2024, 8:55:57 AM] [homebridge-hue] This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info.
[11/12/2024, 8:55:57 AM] [Hue] Hue Bridge: request 9: POST / {"devicetype":"homebridge-hue#homeassistant"}
[11/12/2024, 8:55:57 AM] [Hue] Hue Bridge: request 9: 200 OK
[11/12/2024, 8:55:57 AM] [Hue] Hue Bridge: created user - please edit config.json and restart homebridge
```

### Configuration

```json
{
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "hosts": [
                "192.168.1.100"
            ],
            "lights": true,
            "linkButton": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": false,
            "resource": true,
            "platform": "Hue"
        },
```

### Environment

- OS: Ubuntu 22.04.5 LTS
- Software: 1.8.5
- Node: v20.18.0
- npm: 14.16.1

### Process Supervisor

hb-service

**Comment by ebaauw** [comment]
Better open an issue with Homebridge Hue https://github.com/ebaauw/homebridge-hue/issues, attaching the debug dump file (see README).

> After Homebridge update v1.8.5 connection with my plugin 'Hue' gives an error: This plugin is taking long tie to load and preventing Homebridge from starting. 

Homebridge Hue should work with Homebridge 1.8.5.  Note that the message is _not_ an error.  Homebridge Hue is a very old plugin, that still uses the static platform accessory model.  By design, Homebridge Hue halts Homebridge startup, until it has created accessories for the devices connected to your Hue bridge(s).  

> After pressing the link button on the Philips Hue, no error should appear

Please include the actual error that prevents Homebridge Hue from starting.

**Comment by skipper79** [comment]
> Better open an issue with Homebridge Hue https://github.com/ebaauw/homebridge-hue/issues, attaching the debug dump file (see README).
> 
> > After Homebridge update v1.8.5 connection with my plugin 'Hue' gives an error: This plugin is taking long tie to load and preventing Homebridge from starting.
> 
> Homebridge Hue should work with Homebridge 1.8.5. Note that the message is _not_ an error. Homebridge Hue is a very old plugin, that still uses the static platform accessory model. By design, Homebridge Hue halts Homebridge startup, until it has created accessories for the devices connected to your Hue bridge(s).
> 
> > After pressing the link button on the Philips Hue, no error should appear
> 
> Please include the actual error that prevents Homebridge Hue from starting.

Issue was also opened in [homebridge-hue](https://github.com/ebaauw/homebridge-hue/issues/1199)
