### ISSUE TITLE
Enhancement for macOS instructions specific to SSL certificates

### ISSUE THREAD

**Issue by nstuyvesant** [homebridge/homebridge#3735]
### Proposed Change

I would like to add some details on how to get a self-signed certificate working with Homebridge on macOS as it's something many people are finding difficult.

Here are the steps...

These directions assume you already have Node.JS and Homebridge UI working.

To setup Homebridge on MacOS Sequoia to use a self-signed SSL certificate...

1. Do NOT generate the certificate with Keychain Access. It will export export certificate/key combinations in .p12 format with the RC2-40-CBC Algorithm which is NOT supported by OpenSSL 3.x.
2. Install Homebrew if that hasn't already been done.
3. Use homebrew to install openssl which will be 3.4.0 at the moment... `brew install openssl`
4. Generate the key and certificate signing request (replace My-Server-Name with whatever you call your server substituting hyphens for spaces)... `openssl req -new -newkey rsa:2048 -nodes -keyout homebridge.key -out homebridge.csr -subj "/CN=My-Server-Name.local"`
5. Generate a certificate with whatever validity period you want `openssl x509 -req -days 365 -in homebridge.csr -signkey homebridge.key -out homebridge.crt`
6. Convert the certificate and private key to a p12 file (replace MY_SECRET with a secure passphrase of your own) `openssl pkcs12 -export -out homebridge.p12 -inkey homebridge.key -in homebridge.crt -name "Homebridge Certificate" -passout pass:MY_SECRET`
7. Use chown to change the owner and group of your p12 file to match whichever account Homebridge runs under like `chown myusername:staff homebridge.p12`
8. Use chmod to change the permissions of your p12 file `chmod 600 homebridge.p12`
9. In the Homebridge UI, go to the three vertical dots on the upper right -> Settings
10. Select UI Advanced Settings.
11. Expand SSL Settings accordion.
12. In the Path To PKCS#12 Certificate field, enter the full path to the newly created p12 file.
13. In the PKCS#12 Certificate Passphrase field, enter the passphrase you entered in place of MY_SECRET above.
14. Click Save.
15. Do not restart the server when asked.
16. On the Settings page, click the button next to JSON Config.
17. In the JSON for "platforms", there is an object in the array called "Config". Change its "port" value to 443 as long as this does not conflict with anything else running on your Mac.
18. Click the Save button (floppy disk icon for some unknown reason).
19. Restart the Homebridge UI.
20. Access your Homebridge server at https://YOUR_SERVERS_IP_ADDRESS

### Wiki Page Link

https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-macOS

**Comment by NorthernMan54** [comment]
Tks, page has been updated
