### ISSUE TITLE
Adding KL420L5 Support

### ISSUE THREAD

**Issue by zch11109** [homebridge/homebridge#3737]
### Current Situation

Hello, I have a KL420L5 and I would like to use it with homebridge. 

### Proposed Change

Add support for the KL420L5 to the plugin

**Comment by ZeliardM** [comment]
@zch11109 Is this for my plug-in that you are asking? If so, lighting support is coming in the future. Right now, only plugs and basic switches are supported. Any dimming features with switches or any lights are not supported yet. I do not have a timeframe for this yet as I personally don't have these items available for implementation. So, I will be working with others that have them to implement the changes. If you would be willing to help out in this, let me know.

Thanks!

**Comment by ZeliardM** [comment]
@zch11109 I have pushed out beta 2.7.0-beta.1 with initial support for lighting. Test it out and give me some feedback. If you have problems, open an issue on the plug-in page.
