### ISSUE TITLE
Unable to install plugins

### ISSUE THREAD

**Issue by wanderleyteixeira** [homebridge/homebridge#3746]
### Analysis

Unable to install any plugins

### Expected Behavior

Able to install plugins

### Steps To Reproduce

Open UI and search for a plugin (eg homebridge-govee), tried to install and it hangs until the 217 error 

### Logs

```markdown
> [Homebridge UI] Error: Operation failed with code 217.
> You can download this log file for future reference.
> See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.
```

### Configuration

```json
na
```

### Environment

- OS: Raspbian GNU/Linux Bullseye (11)
- Software: v1.8.5 · UI v4.64.0
- Node:  v22.11.0
- npm: 10.9.0

### Process Supervisor

hb-service

**Comment by AugustMiller** [comment]
Can you follow the instructions in the [Examine Logs for Errors](https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#examine-logs-for-errors) section of the troubleshooting guide and share any error output that mentions `node` or `npm`? This same error code will probably appear somewhere. `tail` may not immediately display the log history—you'll have to re-trigger the error by attempting the installation again!

You can also return to your Homebridge **Status** screen and add the **Homebridge Logs** widget to view logs in your browser.

**Comment by wanderleyteixeira** [comment]
This is what I see

> USER: homebridge
> DIR: /usr
> CMD: sudo -E -n npm install -g homebridge-govee@10.12.1
> 
> npm error code ENOTEMPTY
> npm error syscall rename
> npm error path /usr/lib/node_modules/homebridge-govee
> npm error dest /usr/lib/node_modules/.homebridge-govee-1galVPG5
> npm error errno -39
> npm error ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-govee' -> '/usr/lib/node_modules/.homebridge-govee-1galVPG5'
> npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-12-04T21_44_53_069Z-debug-0.log
> 
> Error: Operation failed with code 217.
> You can download this log file for future reference.
> See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.
> 


inside that debug log we have at the bottom

> ....
> 1056 silly placeDep node_modules/homebridge-govee/node_modules/wrap-ansi emoji-regex@9.2.2 OK for: string-width@5.1.2 want: ^9.2.2
> 1057 silly placeDep node_modules/homebridge-govee/node_modules/wrap-ansi ansi-regex@6.1.0 OK for: strip-ansi@7.1.0 want: ^6.0.1
> 1058 silly reify mark retired [ '/usr/lib/node_modules/homebridge-govee' ]
> 1059 silly reify moves {
> 1059 silly reify   '/usr/lib/node_modules/homebridge-govee': '/usr/lib/node_modules/.homebridge-govee-1galVPG5'
> 1059 silly reify }
> 1060 verbose stack Error: ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-govee' -> '/usr/lib/node_modules/.homebridge-govee-1galVPG5'
> 1060 verbose stack     at async Object.rename (node:internal/fs/promises:783:10)
> 1060 verbose stack     at async moveFile (/usr/lib/node_modules/npm/node_modules/@npmcli/fs/lib/move-file.js:30:5)
> 1060 verbose stack     at async Promise.allSettled (index 0)
> 1060 verbose stack     at async [reifyPackages] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)
> 1060 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:142:5)
> 1060 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:150:5)
> 1060 verbose stack     at async Npm.exec (/usr/lib/node_modules/npm/lib/npm.js:207:9)
> 1060 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli/entry.js:74:5)
> 1061 error code ENOTEMPTY
> 1062 error syscall rename
> 1063 error path /usr/lib/node_modules/homebridge-govee
> 1064 error dest /usr/lib/node_modules/.homebridge-govee-1galVPG5
> 1065 error errno -39
> 1066 error ENOTEMPTY: directory not empty, rename '/usr/lib/node_modules/homebridge-govee' -> '/usr/lib/node_modules/.homebridge-govee-1galVPG5'
> 1067 silly unfinished npm timer reify 1733348694395
> 1068 silly unfinished npm timer reify:retireShallow 1733348851489
> 1069 verbose cwd /usr
> 1070 verbose os Linux 5.10.63-v7l+
> 1071 verbose node v22.11.0
> 1072 verbose npm  v10.9.0
> 1073 verbose exit -39
> 1074 verbose code -39
> 1075 error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-12-04T21_44_53_069Z-debug-0.log
> 

I removed both these folders '/usr/lib/node_modules/homebridge-govee' and '/usr/lib/node_modules/.homebridge-govee-1galVPG5'
Re-ran the install and I get this:

> USER: homebridge
> DIR: /usr
> CMD: sudo -E -n npm install -g homebridge-govee@10.12.1
> 
> npm error process terminated
> npm error signal SIGTERM
> npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-12-04T21_55_24_330Z-debug-0.log
> 
> Error: Operation failed with code 1.
> You can download this log file for future reference.
> See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.

Again the debug file (bottom) 

>...
> 1284 http fetch GET 200 https://registry.npmjs.org/@isaacs/cliui/-/cliui-8.0.2.tgz 6164ms (cache revalidated)
> 1285 verbose stack Error: process terminated
> 1285 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:293:39
> 1285 verbose stack     at process.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:53:5)
> 1285 verbose stack     at process.emit (node:events:518:28)
> 1286 error process terminated
> 1287 error signal SIGTERM
> 1288 silly unfinished npm timer reify 1733349325624
> 1289 verbose cwd /usr
> 1290 verbose os Linux 5.10.63-v7l+
> 1291 verbose node v22.11.0
> 1292 verbose npm  v10.9.0
> 1293 verbose exit 1
> 1294 verbose code 1
> 1295 error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-12-04T21_55_24_330Z-debug-0.log
>

**Comment by wanderleyteixeira** [comment]
Downgraded to Node `v20.18.1` and my problems are resolved.

**Comment by wanderleyteixeira** [comment]
Downgraded to Node v20.18.1 and my problems are resolved.
