### ISSUE TITLE
Implement IGPU support from Intel

### ISSUE THREAD

**Issue by Barichon21** [homebridge/homebridge#3750]
### Current Situation

Nowdays all CPU has GPU chipset onboard. intel GPU is one of these. Thtas wouls be great to get Container that supports IGPU so CPU dont spike when streaming (transocding) is request to some plugin (like Unif Protect for example). 

### Proposed Change

For Intel base GPU you just need to compile a docker that embed: dev/dri/RenderD129

**Comment by NorthernMan54** [comment]
How and where would this be implemented ?

Homebridge itself doesn’t do this but some of the plugins do.

**Comment by Barichon21** [comment]
To allow UnifiProtect plugin to use the IGPU

**Comment by NorthernMan54** [comment]
Pls raise this against that plugin, so the developer is aware and can respond to your ask.
