### ISSUE TITLE
Unable to install due to python3.12

### ISSUE THREAD

**Issue by nicknick923** [homebridge/homebridge#3755]
### Current Situation

Just updated my OS and hb was no longer running, and it seems to be no longer installed. tried to install it via the guide, and coming across the logs shown below.

### Logs

```markdown
sudo apt-get install --reinstall homebridge
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpython3.12-dev : Depends: libpython3.12-stdlib (= 3.12.3-1ubuntu0.3) but 3.12.8-1+jammy1 is to be installed
                     Depends: libpython3.12t64 (= 3.12.3-1ubuntu0.3) but it is not going to be installed
 python3.12-dev : Depends: python3.12 (= 3.12.3-1ubuntu0.3) but 3.12.8-1+jammy1 is to be installed
                  Depends: libpython3.12t64 (= 3.12.3-1ubuntu0.3) but it is not going to be installed
 python3.12-venv : Depends: python3.12 (= 3.12.3-1ubuntu0.3) but 3.12.8-1+jammy1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

### Configuration

```json
unapplicable
```

### Environment

- OS: Ubuntu 24.04.1 LTS
- Software: current/latest?
- Node: 18.19.1
- npm: 9.2.0

### Process Supervisor

not applicable

**Comment by ZeliardM** [comment]
@nicknick923 Try the following:

sudo apt-get install -f

sudo apt-get install libpython3.12-stdlib=3.12.3-1ubuntu0.3 libpython3.12t64=3.12.3-1ubuntu0.3 python3.12=3.12.3-1ubuntu0.3

sudo apt-get install --reinstall homebridge

Let me know if that resolves the install.

**Comment by nicknick923** [comment]
Thanks, this got it working as expected. I did lose all installed plugins, but the configs remain, so adding them should be a breeze.On Dec 21, 2024, at 10:31 PM, ZeliardM ***@***.***> wrote:﻿
@nicknick923 Try the following:
sudo apt-get install -f
sudo apt-get install libpython3.12-stdlib=3.12.3-1ubuntu0.3 libpython3.12t64=3.12.3-1ubuntu0.3 python3.12=3.12.3-1ubuntu0.3
sudo apt-get install --reinstall homebridge
Let me know if that resolves the install.

**Comment by NorthernMan54** [comment]
@ZeliardM Was this an issue with the Homebridge apt package or something else ?

**Comment by ZeliardM** [comment]
@NorthernMan54 It looks like it was an issue with the OS. I believe he did an in-place upgrade of Ubuntu 22.04 to 24.04 and the python packages corrupted somehow and wouldn't fix without manual intervention.

**Comment by nicknick923** [comment]
It was an in place upgrade exactly as explained. I could have been the one who corrupted it, then tried to upgrade os to upgrade python, so that may very well have been my own doing.

**Comment by NorthernMan54** [comment]
Tks for confirming, I had recently made updates to the Homebridge-apt-pkg, and wanted to ensure I didn't break something
