### ISSUE TITLE
Platform Accessories check

### ISSUE THREAD

**Issue by bgottsch** [homebridge/homebridge#635]
Hi,

I am trying to create a dynamic platform which fetches once on home bridge startup all available devices from a specific server. To identify these devices they have a unique ID assigned to them.

How would the logic inside the plugin work for it to fetch all devices, check if they already exists, remove the ones that don't exist on the server but exists on homebridge, and add devices that exist on the server but don't exist on homebridge.

How can I check in the didFinishLaunching the devices that already exist?

Thanks,
Beno

**Comment by bgottsch** [comment]
Solved it by using ```newAccessory.context.sceneId = sceneId;``` and comparing it after the ```didFinishLaunching```

**Comment by jdtsmith** [comment]
@bgottsch Can you expand on this technique a bit?

**Comment by bgottsch** [comment]
@jdtsmith sure!

I was creating a plugin to interface with my ISY-994i (for Insteon devices). I wanted to take advantage of the dynamic plugin features avaliable in homebridge.

I sumbled upon many different answers and approaches to solve it, and found a solution by using the accessory.context property. With that property, I can save the ISY-994i ID (defines internally by ISY), and check it at startup with the newly discovered ones.

To better explain:

- first time I run the plugin (no accessories registered): it fetches all devices registered in the config file and creates them. For every created accessory, the property accessory.context.sceneId is set with the internal ISY-994i ID. Once registered, homebridge saves those accessories internally (.context property is preserved).
- Start the plugin after it has already been started before: it will read the config file and compare it with the already registered accessories inside homebridge. For the comparison logic, I use the property accessory.context.sceneId and compare it to the scene ID in the config file. If the device is matched to the config, it skips it and simply initializes it. If the device is new, it registers it as a new accessory. And if it is found in homebridge, but not in the config, the accessory is deleted.

This is done to maintain persistance across restarts. Also, it is useful to manage, add, edit and delete devices (as with the delete logic, if data, such as name has cahnged from the config to the registered devices, it will delete and readd the edited device).

I did this implementation some time ago so I´m not 100% sure if that was all. Back then I remeber this issue was way more complicated than needed. This was the solution I found to implement what seemed like the correct implementation of a dynamic plugin.

For reference, check my ISY-994i plugin, inside the platform.js file: https://github.com/bgottsch/homebridge-isy994i

Let me know if I wasn´t clear in my explanation.

Best regards,

bgottsch

**Comment by jdtsmith** [comment]
Thanks, this is very useful, and sounds like what I want to do (except with Denon receivers and a uniq "boot id" for each of them).  There is sadly such limited information on dynamic platforms.  

Couple of questions: when you say "read the config file", you mean an auto-generated and stored config file, yes (not `/etc/homebridge/config.json`)?  Do you also merge in user config via that path should they choose to set anything?   Are they passed in separately if you recall?  

Also, suppose the devices available dynamically changes (e.g. someone unplugs a device, or they get a new network address), do you query for them during runtime and add/remove devices, or only when homebridge starts?  

Thanks again.

**Comment by bgottsch** [comment]
@jdtsmith 

I agree, information on it is scarse, unfortunatelly.

1- when you say "read the config file", you mean an auto-generated and stored config file, yes (not /etc/homebridge/config.json)?

I read the homebridge config.json file (depending on your install, located at /etc/homebridge/config.json). This file will have all the devices I as a user chose to add (before runtime).

2- Do you also merge in user config via that path should they choose to set anything? Are they passed in separately if you recall?

It is possible to handle user configs, but for my plugin all I needed was a user, password, IP address and port. Since ISY-994i has a REST API, I call http requests on it, to fetch the status and control devices. Take a look at my config.json example in the plugin I mentioned above. There, "global" variables and devices are all part of the json.

3- Also, suppose the devices available dynamically changes (e.g. someone unplugs a device, or they get a new network address), do you query for them during runtime and add/remove devices, or only when homebridge starts?

I do not query the devices at all. It would be unecessarilly complicated to query them everytime (although that would be the best practice). I read them from the config.json file and thats it. When I refer to the devices stores in homebridge, I refer to the devices saved in the persistentStore folder, located inside .homebridge folder.

To update the device info, should it change a name or whatever property, I delete it and add a new one. For the deletion logic, I first compare each device on the persistentStore to each device in the config.json, and if they don´t match, I delete the unmatched case from the persistentStore. Than, I add all the new ones found in the config.json, but not found in the persistentStore.

I know it seems like a hacky or not elegant way to implement the dynamic plugin features, but that was the solution I found.

There are a number of plugins that handle runtime discovery and updating of devices, though I could not implement it (for the time I had on this project).

Regards,

bgottsch

**Comment by jdtsmith** [comment]
I see.  I know the Nest plugin for example requires "no config", and then discovers and presumably stores pertinent configuration with the cached accessories themselves.  I haven't looked closely, but it must also check if they are still valid on reload from cache.  But it can also take user-specified config to override discovered information.

An example I'm considering: I can use uPnP to find all connected receivers, and query them to find out the name of all inputs on each.  But the user may want to override that list in some way (e.g. if they don't use several of them).  So on auto-discovery of devices, if the user config mentions such a named device, I'd like to allow their config options to override the automatically discovered data.  And so on.  And this information may change, so even if a given accessory is cached, it may need some of its configuration updated (at the user's request via `config.json`, or because the information on the receiver end actually changed — e.g. a given input was renamed). 

For now I put a note at the [top of the most relevant wiki page](https://github.com/nfarina/homebridge/wiki/On-Programming-Dynamic-Platforms)... it needs serious help!  Really appreciate your assistance.  I do also wonder what light @ebaauw could shed on all this, as I know he's put considerable energy into a dynamic Sonos platform that does auto-discovery and presumably had to deal with syncing up configurations via `config.json` and what is discovered automatically in the "real world".  

Thanks again!

**Comment by bgottsch** [comment]
@jdtsmith 

You´re welcome! Glad to help.

I think your proposed solution can work, and with some logic in the event handler methods, you could automate the addition, removal and updating of devices.

I also made a Spotify Connect plugin (inspired by @ebaauw´s Sonos plugin), but I stripped away the auto-discovery feature for a config.json based approach, and have to manually add the devices that I want to be discovered.

There was a plugin for Harmony Hub (I think it´s deprecated now) that implemented the auto-discovery feature in a LAN environment. It was very reliable and I remember it beign really useful (until Logitech changed their APIs, unfortunatelly).

Honestly, homebridge is wonderful but has ways to go before becoming an intuitive and user-friendly solution. Homekit is a complex topic and I can imagine the hassle it was to develop this platform (and HAP-NodeJS).

Ideally, plugins should have a better way to register devices, while keeping in sync with homekit. I think the dynamic features of a plugin came to solve this issue, but it´s a very complex approach. Also, last commit to the documentation explaining dynamic plugins happened on 28 Jun 2017. 

My homebridge instance running for a few years now, and it works as expected. But things should be updated, or else they will be forgotten/replaced.

I believe Homekit is now open-source for non profit use cases. Therefore, even with this amazing accomplishment, the open-source solutions are extremely limited.

In a perfect world, we woudl ahve the abiltiy to install an app that acts as a Hub for a variety of plugins, each with it´s own configuration page, in a dedicated UI. I know there are homebridge plugins that try to create a UI to customize the config.json, but it feels like a hacky solution, rather than a production ready approach.

Just my 2 cents on the topic (glad to discuss more about homebridge and Homekit, if you or anyone is interested).

Best regards,

bgottsch

**Comment by NorthernMan54** [comment]
I also have a number of dynamic plugins, that work with a minimal configuration file.  All it has in it is alias mapping between the device ID and the name I want to use in HomeKit.

I also implemented device auto discovery on startup, that creates accessories for new devices during startup.

For approach, I use the didFinishingLaunching event to perform auto discovery of new devices and the configureAccessories function to refresh my existing devices.

What I have found missing from the homebridge/hap-nodeJS codebase, is the ability to lookup an accessory by name or UUID.  When I do my device auto discovery, to prevent duplicate existing devices I need to consult I list I need to build in memory rather having an API check.  A little bit painful.

My other rant, is the get Event.  To ensure we have responsive devices, the get Event needs to be deprecated, and plugins forced to use updateValue to update status.

**Comment by jdtsmith** [comment]
Thanks both.  I'm trying to reopen an issue over [on homebridge](https://github.com/nfarina/homebridge/issues/1271), so it'd be great if you each could comment there on what is needed to document and fully use dynamic platforms.  Very useful info about `didFinishLaunching`btw.

**Comment by NorthernMan54** [comment]
@jdtsmith For a recent example with didFinishLaunching, take a look at this https://github.com/NorthernMan54/homebridge-connex

**Comment by jdtsmith** [comment]
Thanks, will take a look.  Hopefully we can get this documented so anyone can have access to the dynamic style of plugin development!
