### ISSUE TITLE
Configure camera port

### ISSUE THREAD

**Issue by llemtt** [homebridge/homebridge#927]
Is there a way to configure a camera listening port?

It's somehow an issue it changes whenever I restart homebridge.

Thanks

**Comment by KhaosT** [comment]
Why do you need a fixed port for camera?

**Comment by llemtt** [comment]
Camera behind a NAT that I have to configure port mapping manually...

**Comment by KhaosT** [comment]
Huh... Since every plugin can publish new cameras, I'm afraid homebridge will not provide the ability for you to set the port camera is going to bind on. Would it be helpful if homebridge restricts the port range a camera can bind?

**Comment by llemtt** [comment]
Yes, at least if I can configure that with a range of just one port my problem will be solved.

Wouldn't it be better to add support for a "port" field in camera's plugins?

**Comment by KhaosT** [comment]
It will cause extra confusion and most developer won't think about port being occupied.

**Comment by sequencer** [comment]
possible to get the port range for cameras?
I do think it's not ok that server firewall should be open all port for homebridge.
or is it possible to add a plugin to dynamic add firewall rule for homebridge?

**Comment by llemtt** [comment]
I managed to configure port by modifying server.js like this (added the "port: ..." line)

    hapAccessory.publish({
      username: advertiseAddress,
      pincode: accessoryPin,
      category: accessory.category,
port: accessory.cameraSource.port
    }, this._allowInsecureAccess);

but then is up to each (camera) plugin to configure accessory.cameraSource.port so for instance I also modified my ffmpeg.js to do that.

**Comment by jannnfe** [comment]
Thanks @IIemtt i unterstand the First Part of your soloution adding the Part to Server.js. But where i have to edit the camara plugin in this case homebridge-camera-ffmpeg

**Comment by llemtt** [comment]
Not completely sure but I think this is the only mod required to ffmpeg.js:

`function FFMPEG(hap, cameraConfig) {
  uuid = hap.uuid;
  Service = hap.Service;
  Characteristic = hap.Characteristic;
  StreamController = hap.StreamController;

  var ffmpegOpt = cameraConfig.videoConfig;
  this.name = cameraConfig.name;
  this.vcodec = ffmpegOpt.vcodec;
this.port = cameraConfig.port;`

the last line added!

Then I just add a "port" property into my config.json like this:

`     "platforms": [
			{
				"platform": "Camera-ffmpeg",
				 "cameras": [
					{
					  "name": "iSight ffmpeg",
					  "videoConfig": {
						"source": "-nostats -re -f avfoundation -pix_fmt bgr0 -video_size 640x480 -r 5 -i 0:0 -preset ultrafast",
						"stillImageSource": "-f avfoundation -video_size 640x480 -r 5 -i 0: -frames:v 1",
						"maxStreams": 2,
						"maxWidth": 640,
						"maxHeight": 480,
						"maxFPS": 5
					  },
					  "port": 50000
					}
				] 		  
			}
     ] `

**Comment by jannnfe** [comment]
Thanks! Its working. Wow over months its now working thanks!
Make sure the "port" argument must be >= 0 and < 65536 :)

**Comment by loki29pl** [comment]
This solution is not working in new version.

**Comment by Ubicumque** [comment]
Coming here from [homebridge-videodoorbell](https://github.com/Samfox2/homebridge-videodoorbell)

I've managed to get it working in the new version. Same server.js mod suggested by @llemtt 

Small change on ffmpeg.js mod, as [homebridge-videodoorbell](https://github.com/Samfox2/homebridge-videodoorbell) uses the variable "port" for the listening port to trigger the notification then another name for the variable should be used.

ffmpeg.js -> this.port = cameraConfig.portc;

In config.js:

                "platform": "Video-doorbell",
                "cameras": [{
                        "name": "Video Doorbell",
                        "port": 50000,
                        "portc": 50001,
                        "videoConfig": {

Log: 
Video-doorbell Video Doorbell is listening on port 50000
Video Doorbell is running on port 50001.

It is now working for me, there should be an easier/smarter solution but my programming skills are limited, or maybe you just ned to move the "port" variable to another section in the config :)

**Comment by soldni** [comment]
Replying to this to make sure it doesn't get lost: while the temporary solution is great, it would be great if we could specify at least a range of ports homebridge should use to set up accessories, esp. cameras.

**Comment by roe1974** [comment]
i use 2 cams with homebridge (ffmpeg)
How can i manage NAT in this case ?

**Comment by Codelica** [comment]
Ran into this issue tonight trying to see what ports I needed to open for homebridge-camera-ffmpeg.  
 Even a fixed range would be workable.  But patching a Docker install of homebridge/homebridge-camera-ffmpeg between updates is more than I'm looking to do. ;) Seems most people must be running wide open.

**Comment by llemtt** [comment]
@roe1974 

I don't understand what kind of issues you have to solve given that homekit isn't built to run across nets...

Anyway I once did it, see the above suggested mods.

**Comment by bleistift2** [comment]
I'm having the same port problem (Homebridge in a Docker on Synology NAS in need of fixed ports for the firewall) with the homebridge-doorbird plugin, unfortunately I didn't succeed with the solution from @llemtt and @Ubicumque so far.
My servers.js already had `port: accessoryPort`, I've tried both adding `port: accessory.cameraSource.port` and replacing it with the further.
Since I don't have a camera I don't have ffmpeg installed, I added `this.port = cameraConfig.portc` to ffmpeg.js in the homebridge-doorbird folder. In the config.js I added `"portc": 5001`. Unfortunately the Plugin still uses a random port at startup.
Since that didn't work, what's the right way to do it?

**Comment by AASluke** [comment]
same problem here. (Homebridge in a Docker on Synology NAS)
turning off the firewall isnt really a good option... so i can't get it to work reliably.
im not sure if i get this - why isn´t it possible to optionally (!) configure a port for the camera?

**Comment by Vertigo-7** [comment]
Hiyas, I'm late to the party but thought I would throw in my 2 cents. I just this evening threw homebridge and the Ring plugin on a Windows 2016 server and I've been running into the random port assignment issues outlined above with the Ring accessories. It would be supremely helpful if there was a port range that accessories could be assigned to for setting up firewall rules accordingly. I haven't been able to immediately find what the default possible port range is but I've seen it jump anywhere from 40000 to 60000. Maybe a narrow range of 500 to 1000 ports would be useful. I can't imagine a scenario where someone would need that many accessories outside of a 400 floor hotel.

**Comment by Nuclear-Conger** [comment]
Still appears to be an issue in 2024, can't find the files as in suggested fixes, any further help appreciated.

Sorry (not sorry) for raising old thread.
